### PR TITLE
Remove dependencies

### PR DESCRIPTION
**Pull request by kceiw**
## Description
This module used to depend on Az module which makes the loading time a little long. The reason why that's needed is to solve conflict when they both are loaded. They both depend on Microsoft.Azure.PowerShell.Common.dll and Microsoft.Azure.PowerShell.Authentication.Abstractions.dll. That cause conflicts in loading the assemblies. Once one module is loaded, the other one won't work. Though technically this module only augments Az module experience and it won't add anything if that doesn't exist, we can usually have Az module loaded when this module is used. The problem is loading Az module also takes a long time. The fix here is to remove the dependencies on Microsoft.Azure.PowerShell.Common.dll and Microsoft.Azure.PowerShell.Authentication.Abstractions.dll. We only need to find the configuration file about data collection. So I copied piece of the code to do that. This also bring down the our module size when we package it since we don't need to package the dependencies.

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by kceiw** [comment]
@albaloo @daxian-dbw @BethanyZhou  Can you review it?

**Comment by isra-fel** [comment]
Hi @kceiw thanks for the contribution. Our team are just back from national holiday so sorry for late response. Anyway the changes LGTM :)

**Comment by kceiw** [comment]
@isra-fel Thanks.

**Pull request merged**
