### PR TITLE
Adding firewall prerequisite information

### PR DESCRIPTION
**Pull request by johnmart82**
While trying to follow the example in this page I was getting GatewayTimeout errors. After updating the firewall to allow Azure services the examples work fine. This is important information to the success of the reader executing the example code. As this is essential information required for user success it has been highlighted as Important.

## Description

After trying to get the example code to work I tested with Allow azure services option enabled on the firewall. As this is important for the readers success when testing I have added it as Important information.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Thanks for your contribution again @johnmart82 !
@brandong-ms @xaliciayang could you review the change to the doc of `New-AzSqlDatabaseExport`, or suggest someone to review please? Thank you

**Comment by isra-fel** [comment]
@mikefrobbins Hello Mike could you help Sql team to review this PR? Thanks in advance 😀

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Pull request merged**
