### PR TITLE
Adding SQL AutoDr support

### PR DESCRIPTION
**Pull request by franktsa**
Adding support for AutoDr functionality, which is a configuration object under the server. Operations include:
•Create (PUT)
•Read (GET)
•Update / Failover (POST)
•Delete (DELETE)

CR: http://codeflow/dashboard/review/display/franktsa-c410159bf86f4ca8b7a9f2c6b5768b9f

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@franktsa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (franktsa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@franktsa , please pull from upstream dev branch and resolve conflicts.

**Comment by hovsepm** [comment]
@franktsa please fix and reopen PR. There shouldn't be 2,270 changes.

**Pull request closed without merging**
