### PR TITLE
[Release-1.2.4] azurestack admin tp2 changes

### PR DESCRIPTION
**Pull request by larisaborodina-zz**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@larisaborodina__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@larisaborodina please rebase your fork. There are changes that are already merged to release-1.2.4 branch of Azure.

**Comment by hovsepm** [comment]
moved to PR https://github.com/Azure/azure-powershell/pull/2582

**Pull request closed without merging**
