### PR TITLE
Remove default for wmfversion for set cmdlets

### PR DESCRIPTION
**Pull request by eshaparmar**

### CODE REVIEW

**Comment by markcowl** [comment]
@eshaparmar No test coverage?

**Comment by eshaparmar** [comment]
@markcowl - we already have test coverage for this as scenario test and also in our daily CI system. This pr is only changing the default for this param when it is not present.

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/338/

**Comment by markcowl** [comment]
@eshaparmar There are failures in the on-demand run that are fixed in the dev branch.  Please sync to the dev branch

**Comment by markcowl** [comment]
@eshaparmar Please update so that the on dermand run passes, or we will not be able to merge this PR.

**Comment by eshaparmar** [comment]
@markcowl - I am out on vacation with limited internet access. I will let the team know about this. @narrieta

**Comment by markcowl** [comment]
@narrieta @eshaparmar Code complete is today, so if this doesn't get updated, it will have to wait for the January release.

**Comment by narrieta** [comment]
No problem, it is a non-critical fix that can wait until the next release

**Comment by markcowl** [comment]
@eshaparmar Closing for now per discussion with Norberto.  Please reopen when ready.

**Comment by eshaparmar** [comment]
This pr has been updated with the latest from azure dev 
@markcowl - please merge this.

**Pull request merged**
