### PR TITLE
update docs

### PR DESCRIPTION
**Pull request by datr93**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by datr93** [comment]
@dolauli @VeryEarly hey you guys I can't seem to run the tests in -Live/-Record mode. So I'm not able to record the new response. I posted in the teams channel:

Cannot run test-module.ps1 -Record missing psd1.
How do I get this file?

PS C:\azure-powershell\src\DesktopVirtualization [Az.DesktopVirtualization]> .\test-module.ps1 -Record
Creating isolated process...
Get-Item : Cannot find path 'C:\Users\datr\.PSSharedModules\Resources\Az.Resources.TestSupport.psd1' because it does not exist.

more details:

using powershell core.
ran autorest-beta

ran .\build-module.ps1

ran .\test-module.ps1 -Record
Edited<https://teams.microsoft.com/l/message/19:7599cc34651544b295371ded3fca0810@thread.skype/1593466035498?tenantId=72f988bf-86f1-41af-91ab-2d7cd011db47&amp;groupId=da8d67c5-f19d-4799-b158-5dbbef868d49&amp;parentMessageId=1593466035498&amp;teamName=Azure DevEx SDK, CLIs&amp;channelName=Az PowerShell&amp;createdTime=1593466035498>

**Comment by datr93** [comment]
@dolauli @VeryEarly hey guys can you pls take a look!

**Comment by datr93** [comment]
@dolauli when is a major release? You do you mean I just need to bump the release version to 1.1.0?

**Pull request merged**
