### PR TITLE
Added virtual network support for Batch cmdlets

### PR DESCRIPTION
**Pull request by brnleehng**
Updated Changelog.md with Batch virtual network support
Updated recordings to use Batch service api version
Updated documentation for New-AzureBatchPool
Added parameter to New-AzureBatchPool
Added unit test for virtual network support
Added new models from Batch version 5.0 to Batch Object Model generator

Reference to #2706

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brnleehng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
On demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1071/

**Comment by markcowl** [comment]
@brnleehng  To prepare you, this PR may be too large and too late for us to accept.  Will have a review by EOD, but if any changes are required from the review, this is likely not to make it in for this release.

**Comment by markcowl** [comment]
@brnleehng One change:  The New-AzureRmBatchPool cmdlet should implement ShouldProcess.

Add ```SupportsShouldProcess=true``` to the Cmdlet attribute, and place cmdlet execution in the then block of an if promptected by a call to ShouldProcess:
```C#
if (ShouldProcess(target, processAction)) {
... //cmdlet execution
}
```

Otherwise, this looks good.

**Comment by brnleehng** [comment]
@markcowl @cormacpayne Added ShouldProcess attribute

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1086/

**Pull request merged**
