### PR TITLE
Corrected invalid links from docs ops report

### PR DESCRIPTION
**Pull request by mikefrobbins**
## Description

Corrected invalid links from the docs OPS report.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by VeryEarly — APPROVED** [review]

**Comment by VeryEarly** [comment]
Hi @mikefrobbins ,

This module Az.Functions is auto-generated, which means the docs you updated would be overwritten by any changes in this module (which cause everything include docs been re-generated)
to update these invalid links we should either:

- update descriptions in swagger spec
- or add directive in README.md to modify swagger spec

We'd better ask @Francisco-Gamino (owner of this module) to choose between these two options and use this PR as a reference.

**Comment by Francisco-Gamino** [comment]
Hello @VeryEarly -- Thank you for including me on this conversation. Could you please a directive in README.md to modify swagger spec? Thank you.

**Comment by VeryEarly** [comment]
Hi @Francisco-Gamino ,
please see below example from Az.DataProtection, you can easily replace the paths and description

- from: swagger-document
    where: $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/findRestorableTimeRanges"].post
    transform: $["description"] = "Finds the valid recovery point in time ranges for the restore."

**Comment by VeryEarly** [comment]
> > Hi @Francisco-Gamino , please see below example from Az.DataProtection, you can easily replace the paths and description
> > 
> > * from: swagger-document
> >   where: $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/findRestorableTimeRanges"].post
> >   transform: $["description"] = "Finds the valid recovery point in time ranges for the restore."
> 
> @VeryEarly -- Thank you for the example. Could you please open an issue? I will try to work on this on my next code change. Thank you.

Issue created and assigned to you: https://github.com/Azure/azure-powershell/issues/19938

**Comment by Francisco-Gamino** [comment]
> > > Hi @Francisco-Gamino , please see below example from Az.DataProtection, you can easily replace the paths and description
> > > 
> > > * from: swagger-document
> > >   where: $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.DataProtection/backupVaults/{vaultName}/backupInstances/{backupInstanceName}/findRestorableTimeRanges"].post
> > >   transform: $["description"] = "Finds the valid recovery point in time ranges for the restore."
> > 
> > 
> > @VeryEarly -- Thank you for the example. Could you please open an issue? I will try to work on this on my next code change. Thank you.
> 
> Issue created and assigned to you: #19938

Great, thanks @VeryEarly.

**Pull request closed without merging**
