### PR TITLE
[Resources] fix redundant quotes in list pagination

### PR DESCRIPTION
**Pull request by VeryEarly**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @VeryEarly , I would expect the test cases for both the handwritten cmdlets and generated ones to run (or at least the generated ones), but from the CI log it seemed none tests were run. Can you check what is wrong?
https://dev.azure.com/azure-sdk/public/_build/results?buildId=1478228&view=logs&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=478d3a05-a1a2-5ee2-6dbe-5e69ce2a5ac6

**Comment by VeryEarly** [comment]
> Hi @VeryEarly , I would expect the test cases for both the handwritten cmdlets and generated ones to run (or at least the generated ones), but from the CI log it seemed none tests were run. Can you check what is wrong? https://dev.azure.com/azure-sdk/public/_build/results?buildId=1478228&view=logs&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=478d3a05-a1a2-5ee2-6dbe-5e69ce2a5ac6

test for handcraft cmdlets are skipped intentionally, and tests for MSGraph are live only I think that is the reason no test cases were executed.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
