### PR TITLE
display login announcements less often

### PR DESCRIPTION
**Pull request by isra-fel**
## Description

This pull request primarily focuses on improving the user experience by reducing the frequency of sign-in announcement messages when executing `Connect-AzAccount`. 

* [`src/Accounts/Accounts/Account/ConnectAzureRmAccount.cs`](diffhunk://#diff-9e2da2a40574803af7396e2385e84dc0f1d77a7b171266f1a1109a88b7baf8efL606-R627): Extracted the logic for writing announcements into a new method `WriteAnnouncementsPeriodically()`. This method uses the `IFrequencyService` to control the frequency of announcements, reducing the number of times they are displayed.

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by isra-fel** [comment]
Test: second `Connect-AzAccount` doesn't show announcements

```powershell
$ PS>conn
Please select the account you want to login with.

Retrieving subscriptions for the selection...
WARNING: ***

[Announcements]
With the new Azure PowerShell login experience, you can select the subscription you want to use more easily. Learn more about it and its configuration at https://go.microsoft.com/fwlink/?linkid=2271909.     

If you encounter any problem, please open an issue at: https://aka.ms/azpsissue

Subscription name                  Tenant
-----------------                  ------
***

$ PS>conn
Please select the account you want to login with.

Retrieving subscriptions for the selection...

Subscription name                  Tenant
-----------------                  ------
***
```

**Review by BethanyZhou — APPROVED** [review]
LGTM

**Review by YanaXu — APPROVED** [review]

**Comment by YanaXu** [comment]
LGTM +1

**Comment by isra-fel** [comment]
Related to #25678

**Pull request merged**
