### PR TITLE
Updated Get-AzAutomationJobOutputRecord to handle JSON and Text record values

### PR DESCRIPTION
**Pull request by lwajswaj**
## Description

This PR addresses issue #7977 and #8600. Root cause of the issue was identified as stream outputs always expecting to be a JSON file; however, this ain't true in all cases as String or PSObjects are not returned as JSON. To fix it, a RegEx was put in place to identify JSON output from text output. 

## Checklist

- [X] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@lwajswaj Hey Leandro, thanks for another contribution 😀 

@vrdmr would you mind taking a look at these changes. or assigning this to someone on our side to take a look?

**Comment by lwajswaj** [comment]
Any update on this PR?

**Comment by cormacpayne** [comment]
@lwajswaj the proper contacts from the Automation team have been notified offline -- @NicoletazMS @NarayanThiru

**Comment by safeermohammed** [comment]
@lwajswaj, Do we have any tests?

**Comment by lwajswaj** [comment]
@safeermohammed, this should be covered by existing (if any) test cases.

@cormacpayne, any update on this review?

**Comment by vladimir-shcherbakov** [comment]
@NicoletazMS  @NarayanThiru @vrdmr  Would you mind taking a look at these changes?

**Comment by lwajswaj** [comment]
@vladimir-shcherbakov, @NicoletazMS, @NarayanThiru , @vrdmr , any update on this?

**Comment by NarayanThiru** [comment]
Leandro, can you please explain how you tested the fix?  Asking because, when I look at the existing code, it is already taking care of the case where the jobStream.Value may not be JSON.  The Deserialize (line 61) would throw exception if the value is not JSON format; and the catch block checks if the exception message contains 'Invalid JSON primitive'.  If it doesn't it assigns the value to paramValue (line 68).  Was this not working?  Moreover, the fix will match the pattern **{"error" : {"code" : "AuthenticationFailed", "message" : "Authentication failed."} }**; but not the pattern **{"error" : {"code" : "AuthenticationFailed", "message" : "Authentication failed."}, {"value" : "somevalue" } }**.  Will there always be only one child property? I am new to this code base - so pardon my questions; and apologize for the delay in responding.

**Comment by vladimir-shcherbakov** [comment]
@lwajswaj Ping on the comments above.

**Comment by MiYanni** [comment]
@lwajswaj No activity for 2 weeks. Closing. Feel free to reopen the PR when you have time to address the comments above.

**Comment by lwajswaj** [comment]
Hello, I've been with some business trips + vacations and it was not possible to stay on top of this PR. How should I proceed? opening a new one or can this one be re-open?

@NarayanThiru, in order to test it, just reference to the linked issues. If you try to repro, you will see.

**Pull request closed without merging**
