### PR TITLE
Fix a formatting issue in new-AzureRMResourceGroupDeployment.md

### PR DESCRIPTION
**Pull request by mumian**
## Description

Fix a formatting issue.

## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
wait for ci to complete

**Comment by markcowl** [comment]
@mumian We no longer update documets in the preview branch, as AzureRM is no longer under active development, however, if you could take a look at the corresponding document in the master branch for the `Az` module, we would be ahppy to take this fix there.

Also, please add a changelog entry in the changelog for this service (`src/<service-name>/<service-name>`), under the `Upcoming Releases` heading.  We need this in order to release a new version fo the mdouel with this fix.

**Comment by markcowl** [comment]
@mumian  We would like to take this change in the master branch, if it is valid there, can you make the requested changes?

**Comment by mumian** [comment]
The az cmdlet content is fine.  Close this PR.

**Pull request closed without merging**
