### PR TITLE
update Compute package to 44.0.0

### PR DESCRIPTION
**Pull request by grizzlytheodore**
updating compute package to 44.0.0 and removing remaining ContainerService reference to resolve build error.

And also needed to specify when setting encryptionAtHost property when creating security profile because there is a new property now for securityProfile. Also to resolve build error 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
@Sandido  why dont we want to update compute package to 44.0.0 like here?  

do we need to put in breaking change suppression for the CI checks here?

**Comment by Sandido** [comment]
> @Sandido why dont we want to update compute package to 44.0.0 like here?
> 
> do we need to put in breaking change suppression for the CI checks here?


We can use this PR to update to .Net 44, but it does have the breaking changes we discussed (removed properties and renamed properties) so additional mitigations would be needed before merging this.

**Comment by grizzlytheodore** [comment]
@sandido @dingmeng-xue breaking change suppression added for removed properties: 'kbid', 'RebootStatus' and 'StartedBy' 
breaking change exception was approved by Damien.  What's his github @?

**Comment by dingmeng-xue** [comment]
@dcaro , please check this one.

**Comment by dcaro** [comment]
Breaking change exception approved as per our conversation. 
Please make sure that the docs are clearly indicating the need to update the module.

**Comment by grizzlytheodore** [comment]
please merge

**Comment by grizzlytheodore** [comment]
@VeryEarly please remove 'do not merge' and merge

**Pull request closed without merging**
