### PR TITLE
Adding Azure PowerShell for Microsoft.Cdn

### PR DESCRIPTION
**Pull request by kuangweizhang**
This is a newer version of an old pull request:https://github.com/Azure/azure-powershell/pull/1926

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kuangweizhang__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kzhan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whiteslit

**Comment by hovsepm** [comment]
@kuangweizhang Please add your module to azure-powershell\tools\AzureRM\AzureRM.psd1 file.

**Comment by hovsepm** [comment]
LGTM

**Comment by kuangweizhang** [comment]
@hovsepm 
This doesn't look like related with my change

112.9839399s ✘  Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupPolicyTests.SetProtectionPolicyTests
System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find a matching HTTP request for URL 'GET /Subscriptions/f5303a0b-fae4-4cdb-b44d-0e4c032dde26/resources?$filter=resourceType%20eq%20'Microsoft.Backup/BackupVault'&$top=100'. Calling method ListAsync().

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
sign job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/317/

**Comment by hovsepm** [comment]
@kuangweizhang there is one issue with your PR. AzureRmCdn.psd1 is incorrect name. it should be AzureRM.Cdn.psd1. Please fix it everywhere in your PR (file name, test project imports, wxi file).

**Comment by hovsepm** [comment]
sign: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/320/

**Pull request merged**
