### PR TITLE
Azure SQL Database Set Secondary Failover cmdlet

### PR DESCRIPTION
**Pull request by dominiqa**
Azure SQL Database Set Secondary Failover cmdlet

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dominiqa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
@dominiqa looks like the pull request needs to be updated

**Comment by dominiqa** [comment]
Tests Fixed.  Merges applied and building.

**Comment by dominiqa** [comment]
Build and test issues resolved.  Please integrate before EOW if possible.  This cmdlet is critical to our customers.  Thank you.

**Comment by dominiqa** [comment]
Merged latest changes

**Pull request merged**
