### PR TITLE
Email service data plane operations - Send email and get email send status

### PR DESCRIPTION
**Pull request by v-vprasannak**
## Version 0.1.0
* First preview release for module Az.CommunicationServicesEmail, root module is Az.Communication
    - Added support for Email service data plane operations.
    - Send email and get email send result are the data plane operations.
    
[ChangeLog.md](https://github.com/user-attachments/files/16061913/ChangeLog.md)

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by VeryEarly** [comment]
Is this new submodule coresponding dataplane to https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest ?

**Comment by v-vprasannak** [comment]
> Is this new submodule coresponding dataplane to https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest ?

Yes, its a new module for dataplane

**Comment by VeryEarly** [comment]
> > Is this new submodule coresponding dataplane to https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest ?
> 
> Yes, its a new module for dataplane

I mean is https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest  related to these dataplane API? Are they the same resource?

**Comment by v-vprasannak** [comment]
> > > Is this new submodule coresponding dataplane to https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest ?
> > 
> > 
> > Yes, its a new module for dataplane
> 
> I mean is https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest related to these dataplane API? Are they the same resource?

https://github.com/Azure/azure-powershell/tree/generation/src/Communication/EmailService.Autorest is the control plane module for Email Communication services. and this PR is for data plane module for Email Communication Services. Yes, the same resource.

**Comment by VeryEarly** [comment]
if so, please update module name to EmailServicedata.Autorest (folder name, 'Title' in README.md) and regenerate

**Comment by v-vprasannak** [comment]
> if so, please update module name to EmailServicedata.Autorest (folder name, 'Title' in README.md) and regenerate

Regenerated the code by updating the folder name and Title in README.md file.

**Comment by VeryEarly** [comment]
please add/record test to cover these new cmdlets

**Comment by v-vprasannak** [comment]
> please add/record test to cover these new cmdlets

Added test scenarios, please review

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
