### PR TITLE
[SQL] [LogReplay] Make Start-AzSqlInstanceDatabaseLogReplay synchronous command 

### PR DESCRIPTION
**Pull request by milanbrkic-ms**
## Description

We have experience issues whit this command as it was failing in background and customer was unable to get error message as this was async call.
Making it sync, command will fail with appropriate message.

Added `AsJob` so user can execute this as background process

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Code LGTM. Please regenerate help documents. See https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md

**Comment by MilanBrkicFON** [comment]
@isra-fel thanks for review! Help file is regenerated. 
Can you please tell me when will this fix be released ?

**Review by isra-fel — APPROVED** [review]
LGTM

**Comment by isra-fel** [comment]
Yes it will

**Pull request merged**
