### PR TITLE
NAT Port Range for VPN

### PR DESCRIPTION
**Pull request by henry416**
## Description

Add Port Range support for VPN NAT. PortRanges are optional parameters for the NAT objects.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1041 
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by henry416** [comment]
:rebuild:

**Comment by henry416** [comment]
@isra-fel Please review

**Review by isra-fel — COMMENTED** [review]
Maybe it's just I'm not familiar with the business scenario, but could you add one or two examples (which use port range parameters) in the documents? Others look good to me

**Comment by henry416** [comment]
> Maybe it's just I'm not familiar with the business scenario, but could you add one or two examples (which use port range parameters) in the documents? Others look good to me

@isra-fel  Examples have been added in the updated md files. Please review

**Review by isra-fel — APPROVED** [review]
LGTM, thanks

**Pull request merged**
