### PR TITLE
Fix OU validation hanging in Azure RemoteApp cmdlets

### PR DESCRIPTION
**Pull request by zaevans**
Fixes an issue where catastrophic backtracking caused validation for the organizational unit to cause the Powershell window to hang for a very long time.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@zaevans__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zaevans). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@zaevans please pull from upstream dev branch latest changes.

**Comment by zaevans** [comment]
I've pulled from the upstream dev branch and re-pushed the branch.

**Comment by zaevans** [comment]
The builds are failing with a failed test in Azure.Commands.Profile.

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Pull request merged**
