### PR TITLE
Tag support for deployment

### PR DESCRIPTION
**Pull request by Grayer123**
## Description

* Updated nuget Microsoft.Azure.Management.ResourceManager to "3.4.0-preview"
* Removed specific test cases as Error property in DeploymentValidateResult has changed to readonly from nuget 3.4.0-preview
* Brought GenericResourceExpanded from SDK ResourceManager 3.4.0-preview
* Added tag support for all Get cmdlets for deployment, as well as
    - NewAzureManagementGroupDeploymentCmdlet
    - NewAzureSubscriptionDeploymentCmdlet
    - NewAzureResourceGroupDeploymentCmdlet
    - NewAzureTenantDeploymentCmdlet

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
@Grayer you may use automapper to create the map from new type to old one.

Here is the example of Az.Compute module.

https://github.com/hyonholee/azure-powershell/blob/7e39607e419dd6535a671e4dfbd6f2ab245333e6/src/Compute/Compute/Generated/Models/ComputeAutoMapperProfile.cs

https://github.com/hyonholee/azure-powershell/blob/7e39607e419dd6535a671e4dfbd6f2ab245333e6/src/Compute/Compute/Generated/ContainerService/ContainerServiceCreateOrUpdateMethod.cs

**Comment by msJinLei** [comment]
Hello @Grayer123, we are going to close this PR in few days since no update for this PR for a long time.  After that, you can continue your job by submitting a new one.

**Comment by filizt** [comment]
> Hello @Grayer123, we are going to close this PR in few days since no update for this PR for a long time. After that, you can continue your job by submitting a new one.

Please don't close the PR, there are new commits.

**Comment by filizt** [comment]
About the static analysis failures related to 'Error' and 'Aliases' properties, the failures are due to fixing of faulty models in swagger. The faulty models haven't been out too long and we don't expect these changes to affect any customers. Is there any way to suppress them?

**Pull request merged**
