### PR TITLE
Batch autoscale cmdlets

### PR DESCRIPTION
**Pull request by jasper-schneider**
3 new cmdlets around Batch autoscale features.  Includes tests and help updates.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jasper-schneider__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaschnei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@jasper-schneider please pull from "upstream dev" and update your fork

**Comment by stankovski** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/119/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/418/

**Comment by jasper-schneider** [comment]
The build error in your first link looks like an error in the SQL tests, unrelated to my changes:

  D:\workspace\powershell-on-demand\AzurePowershell.test.targets(75,5): error MSB3073: The command "MSTest.exe /testcontainer:.\src\ServiceManagement\Sql\Commands.SqlDatabase.Test\bin\Debug\Microsoft.WindowsAzure.Commands.SqlDatabase.Test.dll /testsettings:.\src\Local.testsettings /category:"!Functional&!Scenario&!AzureRTScenario&!Sequential&!PIRTest&!Preview&!ADDomain&!Network&!AzureRTUpload&!AzureRTCleanUp" /resultsfile:.\src\Publish\TestResults\SqlDatabaseDebug.trx" exited with code 1. [D:\workspace\powershell-on-demand\build.proj]

**Comment by jasper-schneider** [comment]
Looks like more SQL test changes went into Azure\dev.  I'll merge and restart the build.

**Comment by jasper-schneider** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/122/

**Comment by jasper-schneider** [comment]
Tests that are unrelated to my change are still failing.  Do I just wait until those teams submit fixes, merge, and try again?

"D:\workspace\powershell-on-demand\build.proj" (ForceRestorePackages;Clean;BuildDebug;InvokeXUnitAll;TestHDInsight;TestServiceManagement;TestSqlDatabase;TestStorage;BuildSetupDebug;BuildRelease;BuildSetupRelease target) (1) ->
(InvokeXUnitAll target) -> 
  D:\workspace\powershell-on-demand\AzurePowershell.test.targets(92,5): error MSB3073: The command "D:\workspace\powershell-on-demand\packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe ".\src\ResourceManager\Sql\Commands.Sql.Test\bin\Debug\Microsoft.Azure.Commands.Sql.Test.dll" -notrait "RunType=LiveOnly" -html ".\src\Publish\TestResults\Microsoft.Azure.Commands.Sql.Test.html"" exited with code 8. [D:\workspace\powershell-on-demand\build.proj]

"D:\workspace\powershell-on-demand\build.proj" (ForceRestorePackages;Clean;BuildDebug;InvokeXUnitAll;TestHDInsight;TestServiceManagement;TestSqlDatabase;TestStorage;BuildSetupDebug;BuildRelease;BuildSetupRelease target) (1) ->
(TimeoutErrorHandler target) -> 
  D:\workspace\powershell-on-demand\AzurePowershell.test.targets(99,5): error : XUnit tests in assembly "Microsoft.Azure.Commands.AzureBackup.Test.dll" failed or timed out. Ensure that all tests in a project pass and collectively take less than 1 minute to run. [D:\workspace\powershell-on-demand\build.proj]

**Comment by markcowl** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/426/

**Comment by markcowl** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/133/

**Comment by jasper-schneider** [comment]
Looks like more changes with test fixes went in yesterday.  Merging Azure/develop and trying again: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/137/

**Comment by markcowl** [comment]
@jasper-schneider Please resubmit against the release branch (release-0.9.7)

**Comment by jasper-schneider** [comment]
Done: https://github.com/Azure/azure-powershell/pull/737

**Comment by markcowl** [comment]
@jasper-schneider closing in favor of the new PR #737

**Pull request closed without merging**
