### PR TITLE
Update Storage preview from master

### PR DESCRIPTION
**Pull request by markcowl**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by blueww** [comment]
@markcowl 
I have fixed the test failure for storage cases. The code the pushed to your repo.
Let's see if the PR check can pass.

**Comment by markcowl** [comment]
signing: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/10/

**Comment by markcowl** [comment]
signing: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/13/

**Comment by markcowl** [comment]
https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/14/

**Comment by markcowl** [comment]
https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/19/

**Comment by blueww** [comment]
Fix an issue:
create Storage account with “enableAzureFilesAadIntegrationForSMB" not work. (anyway, update account works)

And start a new sign build: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/21/

**Pull request merged**
