### PR TITLE
Fixing bugs in restore and get\list recoverypoint cmdlet for enrcyptedVM

### PR DESCRIPTION
**Pull request by mkherani**

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@mkherani could you please squash the commits.

**Comment by mkherani** [comment]
Will squash both the commits into one and create another PR.

**Pull request closed without merging**
