### PR TITLE
Update sync-aliases CI to fix issue caused by PowerShell upgrade

### PR DESCRIPTION
**Pull request by vidai-msft**
## Description

Fix the PowerShell to 7.4.x and .NET version to 8.0.x.

The reason I chose to use 7.4 is that we don't need to update the version for 2 years.

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by NoriZC** [comment]
@vidai-msft Could you explain more about why we don't need to update the version for 2 years? Is it because powershell will not have new version?

**Comment by vidai-msft** [comment]
> @vidai-msft Vincent Dai FTE Could you explain more about why we don't need to update the version for 2 years? Is it because powershell will not have new version?

@NoriZC Due to PowerShell support lifecycle document, PowerShell 7.4 will be EOL on Nov 2025 while PowerShell 7.3 will be EOL on May 2024. So If we choose 7.3, then we will update the CI again in 6 months. That is the reason why I chose 7.4. Hope that makes sense.

**Comment by NoriZC** [comment]
> > @vidai-msft Vincent Dai FTE Could you explain more about why we don't need to update the version for 2 years? Is it because powershell will not have new version?
> 
> @NoriZC Due to PowerShell support lifecycle document, PowerShell 7.4 will be EOL on Nov 2025 while PowerShell 7.3 will be EOL on May 2024. So If we choose 7.3, then we will update the CI again in 6 months. That is the reason why I chose 7.4. Hope that makes sense.

I understand that 7.4 would be better than 7.3. But the original code is using latest version. Why are we hard coding it? Is it because `dotnet tool install powershell` will not use the latest version by default any more?

**Comment by vidai-msft** [comment]
> > > @vidai-msft
> > >             
> > >             Vincent Dai
> > >             FTE Vincent Dai FTE Could you explain more about why we don't need to update the version for 2 years? Is it because powershell will not have new version?
> > 
> > 
> > @NoriZC
> >             
> >             Nori Zhang
> >             FTE Due to PowerShell support lifecycle document, PowerShell 7.4 will be EOL on Nov 2025 while PowerShell 7.3 will be EOL on May 2024. So If we choose 7.3, then we will update the CI again in 6 months. That is the reason why I chose 7.4. Hope that makes sense.
> 
> I understand that 7.4 would be better than 7.3. But the original code is using latest version. Why are we hard coding it? Is it because `dotnet tool install powershell` will not intsall the latest version by default any more?

Because the "latest" is too changeable and in addition, PowerShell version is built based on a specific .NET version. Since we have to pin the version of .NET, then we must pin the version of PowerShell as well.

**Review by NoriZC — APPROVED** [review]
Hopefully this hard code could help save efforts and last long

**Pull request merged**
