### PR TITLE
Fixed DNS RecordSet messages

### LINKED ISSUE #6509: New-AzureRmDnsRecordSet verbose output is misleading or incorrect
### Description

When using the `-Verbose` parameter with New-AzureRmDnsRecordSet the verbose output stream appears to output information that is at best misleading and at worst incorrect. Specifically if a RecordConfig is provided for the `-DnsRecords` parameter the verbose output explicitly says "The record set is empty" and that further commands are required to complete the intent of adding a recordset to a zone. Without performing the further commands the intended recordset does appear to have been created successfully by checking both the portal and using powershell commands.

### Script/Steps for Reproduction

```powershell
PS > $testRc = New-AzureRmDnsRecordConfig -Ipv4Address "1.1.1.1"
PS > $testRecordSet = New-AzureRmDnsRecordSet -Name "somehost" -ZoneName somedomain.com -ResourceGroupName some-known-good-rg -Ttl 3600 -RecordType A -DnsRecords $testRc -Verbose
VERBOSE: Performing the operation "Creating record set ..." on target "somehost".
VERBOSE: Success!
VERBOSE: Record set 'somehost' was created in zone 'somedomain.com'.The record set is empty. Use Add-AzureRmDnsRecordConfig to add A records to it and Set-AzureRmDnsRecordSet to save your changes.
VERBOSE: After you create A records in this record set you will be able to query them in DNS using the FQDN 'somehost.somedomain.com.'
```

### Module Version

```powershell
ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     6.3.0      AzureRM
Script     5.7.0      AzureRM
```

### Environment Data
```powershell
Name                           Value
----                           -----
PSVersion                      5.1.17134.112
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.17134.112
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Debug Output

```
DEBUG: 2:59:23 PM - NewAzureDnsRecordSet begin processing with ParameterSet 'Fields'.
DEBUG: 2:59:23 PM - using account id 'nathan.stohlmann@somedomain.com'...
VERBOSE: Performing the operation "Creating record set ..." on target "somehost".
DEBUG: [Common.Authentication]: Authenticating using Account: 'nathan.stohlmann@somedomain.com', environment: 'AzureCloud', tenant: '12345678-1234-1234-1234-123456789012'
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 33bc6229-c478-4668-a94c-425cda9a1d63 - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/12345678-1234-1234-1234-123456789012/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/21/2018 19:59:23: 33bc6229-c478-4668-a94c-425cda9a1d63 - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 33bc6229-c478-4668-a94c-425cda9a1d63 - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/21/2018 19:59:23: 33bc6229-c478-4668-a94c-425cda9a1d63 - TokenCache: 39.8619220266667 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 33bc6229-c478-4668-a94c-425cda9a1d63 - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 33bc6229-c478-4668-a94c-425cda9a1d63 - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: df2B/Ft8Sez1tEE0nRKKDAYlORCkDR0/5Rjp65f4Vbs=
 Refresh Token Hash: EWntP8nTRdFjFsS+ZG/wGpD3yUJaAVECkaqrQsA0t4A=
 Expiration Time: 06/21/2018 20:39:15 +00:00
 User Hash: vCSaOxLfTO0PbO33L8GtjlttHW4wuBb8NZ/7zy160B0=

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 2635e6bc-4651-4f07-8c67-82f77ce8513c - AcquireTokenHandlerBase: === Token Acquisition started:
 Authority: https://login.microsoftonline.com/12345678-1234-1234-1234-123456789012/
 Resource: https://management.core.windows.net/
 ClientId: 1950a258-227b-4e31-a9cf-717495945fc2
 CacheType: Microsoft.Azure.Commands.Common.Authentication.ProtectedFileTokenCache (1 items)
 Authentication Target: User

DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23:  - TokenCache: Deserialized 1 items to token cache.
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/21/2018 19:59:23: 2635e6bc-4651-4f07-8c67-82f77ce8513c - TokenCache: Looking up cache for a token...
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 2635e6bc-4651-4f07-8c67-82f77ce8513c - TokenCache: An item matching the requested resource was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Verbose: 1 :
DEBUG: 06/21/2018 19:59:23: 2635e6bc-4651-4f07-8c67-82f77ce8513c - TokenCache: 39.86170532 minutes left until token in cache expires
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 2635e6bc-4651-4f07-8c67-82f77ce8513c - TokenCache: A matching item (access token or refresh token or both) was found in the cache
DEBUG: Microsoft.IdentityModel.Clients.ActiveDirectory Information: 2 :
DEBUG: 06/21/2018 19:59:23: 2635e6bc-4651-4f07-8c67-82f77ce8513c - AcquireTokenHandlerBase: === Token Acquisition finished successfully. An access token was retuned:
 Access Token Hash: df2B/Ft8Sez1tEE0nRKKDAYlORCkDR0/5Rjp65f4Vbs=
 Refresh Token Hash: EWntP8nTRdFjFsS+ZG/wGpD3yUJaAVECkaqrQsA0t4A=
 Expiration Time: 06/21/2018 20:39:15 +00:00
 User Hash: vCSaOxLfTO0PbO33L8GtjlttHW4wuBb8NZ/7zy160B0=

DEBUG: ============================ HTTP REQUEST ============================

HTTP Method:
PUT

Absolute Uri:
https://management.azure.com/subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/some-known-good-rg/providers/Microsoft.Network/dnsZones/somedomain.com/A/somehost?api-version=2018-03-01-preview

Headers:
x-ms-client-request-id        : 1e218e0b-c232-4066-a75e-1f1ed3c3cba5
If-None-Match                 : *
accept-language               : en-US

Body:
{
  "properties": {
    "TTL": 3600,
    "ARecords": [
      {
        "ipv4Address": "1.1.1.1"
      }
    ]
  }
}

DEBUG: ============================ HTTP RESPONSE ============================

Status Code:
Created

Headers:
X-Content-Type-Options        : nosniff
Strict-Transport-Security     : max-age=31536000; includeSubDomains
x-ms-request-id               : 2f304970-05ed-413f-92ca-1e80d3908770
x-ms-ratelimit-remaining-subscription-resource-requests: 11999
x-ms-correlation-request-id   : 9443c5cc-7fc4-40d8-adf1-dabf01a6dc0f
x-ms-routing-request-id       : NORTHCENTRALUS:20180621T195924Z:9443c5cc-7fc4-40d8-adf1-dabf01a6dc0f
Cache-Control                 : private
Date                          : Thu, 21 Jun 2018 19:59:24 GMT
ETag                          : 72d735a3-5e90-4de6-b4a0-2a2db8576c80
Server                        : Microsoft-IIS/8.5
X-AspNet-Version              : 4.0.30319
X-Powered-By                  : ASP.NET

Body:
{
  "id": "/subscriptions/12345678-1234-1234-1234-123456789012/resourceGroups/some-known-good-rg/providers/Microsoft.Network/dnszones/somedomain.com/A/somehost",
  "name": "somehost",
  "type": "Microsoft.Network/dnszones/A",
  "etag": "72d735a3-5e90-4de6-b4a0-2a2db8576c80",
  "properties": {
    "fqdn": "somehost.somedomain.com.",
    "TTL": 3600,
    "ARecords": [
      {
        "ipv4Address": "1.1.1.1"
      }
    ]
  }
}

VERBOSE: Success!
VERBOSE: Record set 'somehost' was created in zone 'somedomain.com'.The record set is empty. Use Add-AzureRmDnsRecordConfig to add A records to it and Set-AzureRmDnsRecordSet to save your changes.
VERBOSE: After you create A records in this record set you will be able to query them in DNS using the FQDN 'somehost.somedomain.com.'
DEBUG: AzureQoSEvent: CommandName - New-AzureRmDnsRecordSet; IsSuccess - True; Duration - 00:00:01.0347594; Exception - ;
DEBUG: Finish sending metric.
DEBUG: 2:59:25 PM - NewAzureDnsRecordSet end processing.
DEBUG: 2:59:25 PM - NewAzureDnsRecordSet end processing.
```

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
## Description

Fixes #6509.
Sample output after:

image

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by EvgenyAgafonchikov** [comment]
@karravi-msft, could you please review this update?

**Comment by maddieclayton** [comment]
@karravi-msft Ping - can you give this a quick review?

**Comment by maddieclayton** [comment]
@EvgenyAgafonchikov Are we ready to merge this? Should I remove the Do not merge tag?

**Comment by EvgenyAgafonchikov** [comment]
@maddieclayton, I've dropped "Do not merge", please merge if no other changes required.

**Pull request merged**
