### PR TITLE
Get-AzStorageFileContent documentation for Context parameter is wrong

### PR DESCRIPTION
**Pull request by mikedouglasdev**
Context parameter contains contents for the Force parameter.  Copied verbiage from another cmdlet.

## Description

I noticed that the document is wrong for the -Context parameter.  It appears to be copied from -Force parameter.  I updated it to match another PowerShell cmdlet.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by blueww** [comment]
@mikedouglasdev 
Thanks for the finding!
You change looks good to me and I have approved it. 
But it looks like some other parameters of this cmdlet also need change. Would you like to change them also in this PR. If you can't do so, I can also change them in a later PR.

`CheckMd5`
Specifies whether to check the Md5 sum for the downloaded file.

`ClientTimeoutPerRequest`
Specifies the client-side time-out interval, in seconds, for one service request. If the previous call fails in the specified interval, this cmdlet retries the request. If this cmdlet does not receive a successful response before the interval elapses, this cmdlet returns an error.

`ConcurrentTaskCount`
Specifies the maximum concurrent network calls. You can use this parameter to limit the concurrency to throttle local CPU and bandwidth usage by specifying the maximum number of concurrent network calls. The specified value is an absolute count and is not multiplied by the core count. This parameter can help reduce network connection problems in low bandwidth environments, such as 100 kilobits per second. The default value is 10.

`PassThru`
Indicates that this cmdlet returns the **AzureStorageFile** object that it downloads.

`ServerTimeoutPerRequest`
Specifies the service side time-out interval, in seconds, for a request. If the specified interval elapses before the service processes the request, the storage service returns an error.

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
@mikedouglasdev Hey Mike, thanks for making this fix. As @blueww pointed out above, you can feel free to make the other changes if you'd like, or we can handle it in a separate PR. Just let us know, otherwise, this PR should be good to merge!

**Comment by blueww** [comment]
@mikedouglasdev , @cormacpayne 
I have raise a commit and add the change for other parameters in this PR. 
Please help to review.

**Comment by cormacpayne** [comment]
@blueww thanks for making these changes -- they look good to me

@mikedouglasdev Hey Mike, before we can merge this PR, you will need to sign the CLA, which you can do from the comment above posted by the `msftclas` bot

**Comment by vladimir-shcherbakov** [comment]
@mikedouglasdev Ping on the comments above.

**Comment by blueww** [comment]
Since the license not signed for 7 days, I have send another PR for the same code change: https://github.com/Azure/azure-powershell/pull/8751

@cormacpayne 
If the license still not signed tomorrow, would you please help to merge PR https://github.com/Azure/azure-powershell/pull/8751, then the same code change will be in.

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/pull/8751

**Pull request closed without merging**
