### PR TITLE
Rename some help files

### LINKED ISSUE #13860: Help mark down files cannot find its cmdlet implementation
## Description

Below errors show up during pipeline checks the mapping between cmdlet and helps. We need to remove those issues. Some are due to inconsistent of upper/lower case.
```
  Help record Disable-AzAksAddon has no cmdlet.
  Help record Enable-AzAksAddon has no cmdlet.
  Help record Invoke-AzVmPatchAssessment has no cmdlet.
  Help record Disconnect-AzP2sVpnGatewayVpnConnection has no cmdlet.
  Help record Get-AzExpressRouteCrossConnectionARPTable has no cmdlet.
  Help record Get-AzOperationalInsightsLinkTarget has no cmdlet.
  Help record Get-AzOperationalInsightsSavedSearchResult has no cmdlet.
  Help record Get-AzOperationalInsightsSearchResult has no cmdlet.
  Help record DIsable-AzSecurityAdvancedThreatProtection has no cmdlet.
  Help record Disable-AzSqlServerAdvancedThreatProtection has no cmdlet.
  Help record Enable-AzSqlServerAdvancedThreatProtection has no cmdlet.
  Help record Set-AzDataLakeGen2ItemACLObject has no cmdlet.
```

### PR DESCRIPTION
**Pull request by Youri970410**
## Description
Fix #13860
Rename some help files

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Why are some help files deleted?

**Comment by Youri970410** [comment]
@isra-fel 
Those cmdlets do not exist now so we need to remove the help files of them,"Az.ResourceGrap" is not fixed now.Here are a list for all cmdlets:


ServiceName | Cmdlet Name | Issue
-- | -- | --
Az.Aks | Disable-AzAksAddon | "On" is different from   "on"
Az.Aks | Enable-AzAksAddon | "On" is different from   "on"
Az.Compute | Invoke-AzVmPatchAssessment | "VM“ is different from "Vm"
Az.Network | Disconnect-AzP2sVpnGatewayVpnConnection | "S" is different from "s"
Az.Network | Get-AzExpressRouteCrossConnectionARPTable | "RP" is different from "pr"
Az.OperationalInsights | Get-AzOperationalInsightsLinkTarget | Alias Cmdlet and  Help file do not   regenerate
Az.OperationalInsights | Get-AzOperationalInsightsSavedSearchResult | Alias Cmdlet and  Help file do not   regenerate
Az.OperationalInsights | Get-AzOperationalInsightsSearchResult | Alias Cmdlet and  Help file do not   regenerate
Az.ResourceGraph | Search-AzGraph | Do not exist in psd1
Az.Security | DIsable-AzSecurityAdvancedThreatProtection | "I" is different from "i"
Az.Sql | Disable-AzSqlServerAdvancedThreatProtection | Alias Cmdlet and  Help file do not   regenerate
Az.Sql | Enable-AzSqlServerAdvancedThreatProtection | Alias Cmdlet and  Help file do not   regenerate
Az.Storage | Set-AzDataLakeGen2ItemACLObject | "CL" is different from    "cl"

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
