### PR TITLE
Add support for the APIM Reconnect API cmdlet Reset-AzAPIManagementBackendConnection

### PR DESCRIPTION
**Pull request by thefaftek**
## Description

In this PR the cmdlet Reset-AzApiManagementBackendConnection was added. This implements the Reconnect API: https://docs.microsoft.com/en-us/rest/api/apimanagement/2019-12-01/backend/reconnect

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Please submit a cmdlet design review in this repository before submitting pull request, thanks
https://github.com/Azure/azure-powershell-cmdlet-review-pr

**Comment by msJinLei** [comment]
@thefaftek  Have you finished the cmdlet review? If yes, could you provide the link?

**Comment by thefaftek** [comment]
> @thefaftek Have you finished the cmdlet review? If yes, could you provide the link?

My apologies, this fell off my radar, been a crazy few weeks. I'll get one submitted this week at the latest.

**Comment by thefaftek** [comment]
Issue has been created in the cmdlet review section: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/828

**Comment by BethanyZhou** [comment]
Hi @thefaftek , some revisions needs be done for your design design, could you have a look?

**Comment by msJinLei** [comment]
@thefaftek Since no update for design review of the PR, we are going to close this PR soon. If you can continue your work by submitting a new one.

**Pull request closed without merging**
