### PR TITLE
Azure Backup Vault Cmdlet Changes

### PR DESCRIPTION
**Pull request by dragonfly91**
Added prompt for deletion in Remove Vault. Please review / merge.

### CODE REVIEW

**Comment by markcowl** [comment]
@dragonfly91 test failures. please fix

**Comment by markcowl** [comment]
@dragonfly91 still test failures

**Comment by markcowl** [comment]
@dragonfly91 merge conflicts and test failures, please address or this will not make it into the December release

**Comment by jianghaolu** [comment]
@dragonfly91 Looks like the test named `Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupVaultTests.AzureBackupVaultScenarioTests` is failing. Please address.

**Comment by markcowl** [comment]
@dragonfly91 This PR has not been updated for 11 days, despite repeated requests.  Closing.  Please open a new PR when you have addressed the issues.

**Pull request closed without merging**
