### PR TITLE
[Audit policy] Set-AzSqlDatabaseAudit - support Hyperscale database

### PR DESCRIPTION
**Pull request by OlegSternbergIBM**
Fix in Set-AzSqlDatabaseAudit - support Hyperscale database
Show descriptive error when database edition cannot be determined

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @Oleza1972 if you are a Microsoft employee please join Azure orgnization on https://aka.ms/AzureGithub so that CI can be automatically triggered.

**Comment by Oleza1972** [comment]
> Hi @Oleza1972 if you are a Microsoft employee please join Azure orgnization on https://aka.ms/AzureGithub so that CI can be automatically triggered.

Done

**Review by isra-fel — APPROVED** [review]
LGTM
Pending @bashahee 's approval

**Review by bashahee — APPROVED** [review]

**Comment by bashahee** [comment]
@isra-fel Please merge :)

**Pull request merged**
