### PR TITLE
Updating Package version for ExpressRoute Commandlets

### PR DESCRIPTION
**Pull request by nupurkot**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nupurkot__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nkothar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@nupurkot Tests?  This should at least be covered by a unit test using Moq, or the like.  Also, I assume this is targeted at the January release. LMK if not.

**Comment by nupurkot** [comment]
Modified the existing tests to also test BillingType. This is targeted for the January release.

**Comment by dihan0604** [comment]
LGTM

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/425/

**Pull request merged**
