### PR TITLE
[Storage] Add Ps1XmlAttribute to Storage cmdlets output types properties.

### PR DESCRIPTION
**Pull request by blueww**
## Description

The detail implementation has been discussed and agreed with @vladimir-shcherbakov in https://github.com/Azure/azure-powershell/issues/6582#issuecomment-405302493

For Azure.Storage, 

- we will use Ps1XmlAttribute for type which defined in PowerShell code, and add new file: Microsoft.WindowsAzure.Commands.Storage.generated.format.ps1xml
- we will keep the type from XSCL still in original format.ps1xml file

For AzureRm.Storage:

- Besides adding Ps1XmlAttribute to original type "PSNetworkRuleSet", also add it for type "PSStorageAccount"

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@blueww To fix the build, please update the changelog for src/Storage, src/ResourceManager/Profile, and src/ResourceManager/Storage

**Comment by blueww** [comment]
@maddieclayton 

Change log is added, please check.

**Comment by blueww** [comment]
@maddieclayton 
The build still fail since there's changes in the common project "Commands.Common.Storage", but there's no change log in the project, so I can't update it.

Do you have any idea how to fix it?

**Comment by maddieclayton** [comment]
@blueww Per my comment above, you are missing the changelog entry for src/ResourceManager/Profile - I'll take care of that now.

**Comment by maddieclayton** [comment]
@vladimir-shcherbakov The build is now passing, so this PR is ready for review.

**Comment by vladimir-shcherbakov** [comment]
on-demand: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/1006/
sign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/887/

**Comment by blueww** [comment]
@maddieclayton 
Thanks for helping update the change log of src/ResourceManager/Profile. 
But why we need update the change log of this project?

**Pull request merged**
