### PR TITLE
Stack: AzureRM.Dns module for stack, the latest module version breaks

### PR DESCRIPTION
**Pull request by bganapa**
## Description

Azurerm.Dns module copy for stack, as the latest 2018-03-01-preview not supported in stack, copying the module from the commit 5f8826d272c8235a7aabb91e19d70a0bcf5a5468, 3.4.1 version

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by vladimir-shcherbakov** [comment]
@deathly809, Could you provide more information? 
When you say "existing cmdlets from a previous commit"-  what exact commit do you mean, and on the basis of which cmdlet review were they implemented?

**Comment by deathly809** [comment]
@vladimir-shcherbakov Azure Stack supports an older API version for AzureRM.Dns.  So we use the previous Azure-Powershell cmdlets for that API version.  As you can see from the description above we took a previous Azure-Powershell commit (5f8826d).

**Comment by vladimir-shcherbakov** [comment]
@deathly809 According to @markcowl you had a discussion and agreed on the need for a cmdlet review.

**Comment by bganapa** [comment]
It was me who had a discussion with Mar. I will create an issue for cmdlet review

**Comment by bganapa** [comment]
@vladimir-shcherbakov Here is the cmdlet review issue. https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/38

This module is essentially a copy of the existing module AzureRm.DNS version 3.4.1 in to stack folder for the sake consuming the new common runtime. The module looks good in terms of guildelines and pipelining..

**Comment by markcowl** [comment]
Closing per this week's discussion

**Pull request closed without merging**
