### PR TITLE
Azure RemoteApp: per-app publishing support

### PR DESCRIPTION
**Pull request by vadimp-msft**
@azuresdkci - Test this please!

### CODE REVIEW

**Comment by vadimp-msft** [comment]
@azuresdkci - Test this please!

**Comment by yadavbdev** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
@azuresdkci - Test this please!

**Comment by amarzavery** [comment]
@azuresdkci - Add to whitelist.

**Pull request merged**
