### PR TITLE
Add clarification around Set-AzWebApp -AppSettings

### PR DESCRIPTION
**Pull request by richardszalay**
It wasn't clear whether the provided Hashtable would merge or replace the existing app settings

## Description

Add clarification around `-AppSettings` parameter, specifically that it replaces existing values rather than merges with them.

**Question:** I'm not 100% clear if I should be appending the changelog for this, and what "version" I should put the notes under (the [anchor tag](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log) in CONTRIBUTING.md that's linked below doesn't exist). Let me know and I'll update the PR.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md) (N/A)
- [x] If applicable, the changes made in the PR have proper test coverage  (N/A)
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only) N/A
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md) N/A

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by erich-wang** [comment]
@panchagnula, are you fine with updated description?

**Comment by panchagnula** [comment]
@richardszalay are you saying that the -AppSettings is replacing other existing AppSettings or something else? i want to understand the scenario here before merging this change. Thanks!

**Comment by richardszalay** [comment]
@panchagnula Yes, it replaces existing appsettings, rather than merging with them.

**Comment by panchagnula** [comment]
thanks in that case add the same to the Set-AzWebAppSlot -AppSettings as well. thank you.

**Comment by cormacpayne** [comment]
@richardszalay would you mind updating the `Set-AzWebAppSlot` documentation to reflect this change as well? Also, please update the [Websites change log](https://github.com/Azure/azure-powershell/blob/master/src/Websites/Websites/ChangeLog.md) with a snippet about the change being made in this PR.

**Comment by richardszalay** [comment]
Done!

**Pull request merged**
