### PR TITLE
Adding optional target subscription Id parameter in order to enable cross-subscription movement

### PR DESCRIPTION
**Pull request by jovancevic123**
…ross subscription db move/copy.

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by NoriZC** [comment]
Hi @jovancevic123, Could you please add a test case for this update?

**Comment by jovancevic123** [comment]
> Hi @jovancevic123, Could you please add a test case for this update?

Hi, I am not sure that we can write automated test since this is cross subscription feature and it is not possible to change context without hard-coding values. If you have any advice on how to do this please let me know.

**Comment by NoriZC** [comment]
@jovancevic123 You can add a [LiveOnly] test referring the following example:
https://github.com/Azure/azure-powershell/blob/f67aaf4dbe62a9b9ed08bbb1fe885a1d39d4fce5/src/Sql/Sql.Test/ScenarioTests/AuditTests.cs#L235

Please share the successful test status in the PR description section, and then you can update the hard-coded sub id with a placeholder (like 0000-0000-0000-0000). This sub id will not be left in json files/ psd1 scripts.

This is just to confirmed the correctness of the newly added feature. And next time when you update related features, this can also help verify whether this feature is affected or not.

**Comment by jovancevic123** [comment]
> @jovancevic123 It is recommended to add a [LiveOnly] test referring the following example:
> 
> https://github.com/Azure/azure-powershell/blob/f67aaf4dbe62a9b9ed08bbb1fe885a1d39d4fce5/src/Sql/Sql.Test/ScenarioTests/AuditTests.cs#L235
> 
> Please share the successful test status in the PR description section, and then you can update the hard-coded sub id with a placeholder (like 0000-0000-0000-0000). This sub id will not be left in json files/ psd1 scripts.
> 
> This is just to confirm the correctness of the newly added feature. And next time when you update related features, this can also help verify whether this feature is affected or not.

Thank you for the feedback, I added tests.

**Review by NoriZC — APPROVED** [review]

**Pull request merged**
