### PR TITLE
[AzureRT] Update Release 1.2.4 Compute library with the latest 2015-06-15 Swagger spec.

### PR DESCRIPTION
**Pull request by hyonholee**
- Update Compute client library to 11.3.1-prerelease
- Add Set-AzureRmVMPlan cmdlets
- Add -LicenseType parameter for New-AzureRmVM (Bring your own license feature)
- Add -SecureExecution parameter for Set-AzureRmVMCustomScriptExtension
- Add -ForceRerun parameter for Set-AzureRmVMExtension

### CODE REVIEW

**Comment by hovsepm** [comment]
:shipit:

**Comment by markcowl** [comment]
LGTM once the tests pass

**Comment by markcowl** [comment]
@hyonholee There are merge conflicts, please update

**Comment by markcowl** [comment]
@hyonholee CredScan issues have been resolved, please pull the latest

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/942/

**Pull request merged**
