### PR TITLE
Vnetpeering

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by DeepakRajendranMsft** [comment]
I am getting unrelated test failure: 20:29:42   d:\workspace\powershell\src\ServiceManagement\Services\Commands.Test\WAPackIaaS\Operations\JobOperationsTests.cs(48): error : Microsoft.WindowsAzure.Commands.Test.WAPackIaaS.Operations.JobOperationsTests.WaitOnJobCompletesImmediately [FAIL] [D:\workspace\powershell\build.proj]
20:29:42 

Could you please kick off an ondemand build

**Comment by markcowl** [comment]
@DeepakRajendranMsft Please pull the latest.  There is a fix for the flakiness of this test at the tip of the branch

**Comment by DeepakRajendranMsft** [comment]
closing PR. the changes are contained in https://github.com/Azure/azure-powershell/pull/2552

**Pull request closed without merging**
