### PR TITLE
Use best practice to avoid potential attack

### PR DESCRIPTION
**Pull request by wyunchi-ms**
## Description

This pull request includes a change in the `.github/workflows/pr-labeled.yml` file. The change updates the `process label` job by replacing the direct use of `github.event.label.name` in the `run` command with an environment variable `LABEL` to prevent code injection.

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by AllyW** [comment]
Practice recommend:
1. add trigger condition - branch: main 
2. scan and delete other branches that contains this problematic expression, if exists.

**Comment by wyunchi-ms** [comment]
> Practice recommend:
> 
> 1. add trigger condition - branch: main
> 2. scan and delete other branches that contains this problematic expression, if exists.

For the first comment. In most cases, we use this github action in `main` and `generation` branch. But we may have other 
 scenarios that need to use this in other branch.

**Comment by wyunchi-ms** [comment]
> Practice recommend:
> 
> 1. add trigger condition - branch: main
> 2. scan and delete other branches that contains this problematic expression, if exists.

For the first comment. In most of the cases, we use this github action in `main` and `generation` branch. But we may have other 
 scenarios that need to use this in other branch.

**Review by isra-fel — COMMENTED** [review]
Please add a note in PR description or simply link to the official doc.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
