### PR TITLE
[Synapse] Add Support for SqlPoolsV3 and SqlDatabases

### PR DESCRIPTION
**Pull request by idear1203**
## Description

This change introduces a version parameter for Sql Pools to allow customers to provision the latest version of SqlPools. It also introduces the SqlDatabase resource and allows basic CRUD operations for it. Sql Pools make up the compute and can be scaled, connected to, and used to issue queries. The queries operate on the data contained in the SqlDatabase. SqlPools can be used to query different Sql Databases within the same Synapse workspace.

Design review link: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/673

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by idear1203** [comment]
Please DO NOT merge this PR. Currently we are using a self-built SDK, we will switch to a official bit that will be available next week.  Other than this issue, the PR is ready for a review.

**Comment by idear1203** [comment]
@isra-fel I switched to the official SDK package. Could you please take a look again?

**Pull request merged**
