### PR TITLE
RDBug 6919611:[PSH] Get-AzureRmStorageAccountKey: change the cmdlets …

### PR DESCRIPTION
**Pull request by blueww**
RDBug 6919611:[PSH] Get-AzureRmStorageAccountKey: change the cmdlets support both key1/key2 and [0].Value 
     After the change, Both Key1/Key1 and [0].Value works. And the output looks also good.

RDBug 7069788:[PSH] fix the breaking change on New/Get/Set-AzureRMStorageAccount for Sku.Name, and New-AzureRMstorageAccountKey
- New/Get/Set-AzureRMStorageAccount: Add the AccountType Back to the return value with same class name and namespace
- New-AzureRMstorageAccountKey: make the returned value support both ".StorageAccountKeys.Key1" and ".Keys[0].Value"

Storage regression test passed on this PR.

### CODE REVIEW

**Comment by blueww** [comment]
On Demand test: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1096

**Comment by shahabhijeet** [comment]
@markcowl can you take a look at this change please.

**Comment by blueww** [comment]
On Demand Test Passed.
Storage regression passed.

**Comment by markcowl** [comment]
@blueww I think we should also add back Sku and Sku.Type to the storage account type

**Comment by blueww** [comment]
@markcowl 
Add following fix to the PR, and on demand test is running : http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1098/

RDBug 7069788:[PSH] fix the breaking change on New/Get/Set-AzureRMStorageAccount for Sku.Name, and New-AzureRMstorageAccountKey

- New/Get/Set-AzureRMStorageAccount: Add the AccountType Back to the return value with same class name and namespace

- New-AzureRMstorageAccountKey:
 make the returned value support both ".StorageAccountKeys.Key1" and ".Keys[0].Value"

**Comment by blueww** [comment]
on Demand test passed: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1100/

**Pull request merged**
