### PR TITLE
Az.recovery services to master 

### PR DESCRIPTION
**Pull request by viverm**
## Description

Breaking Change release . Taking API version bump up

# New feature support for Azure Site Recovery.
Reference::
https://github.com/Azure/azure-powershell/pull/9173

Preview Changes 
Cmdlet Review :: 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/300#issuecomment-491092895

**Changes** 
* Azure Site Recovery Support to write to managed disk for vMWare to Azure. 
* Azure Site Recovery Support to NIC reduction for vMWare to Azure. 
* Azure Site Recovery Support to accelerated networking for Azure to Azure. 
* Azure Site Recovery Support to agent auto update for Azure to Azure. 
* Azure Site Recovery Support to Standard SSD for Azure to Azure. 
* Azure Site Recovery Support to Azure Disk Encryption two pass for Azure to Azure. 
* Azure Site Recovery Support to protect newly added disk for Azure to Azure.

## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by viverm** [comment]
I don't have write access to review repository . How can I resolve conflict

**Comment by viverm** [comment]
I don't have rights to write on Az.RecoveryServices  to resolve merge conflict.
Small conflicting changes  .. Please suggest the way to go ahead.

**Comment by wyunchi-ms** [comment]
> I don't have rights to write on Az.RecoveryServices to resolve merge conflict.
> Small conflicting changes .. Please suggest the way to go ahead.

You can pull `Az.RecoveryServices` to your repository, then merge it to your branch and resolve the confilict locally. Then push your branch to remote.

**Comment by wyunchi-ms** [comment]
Hi @viverm , could you please recolve the conflicts?

**Comment by viverm** [comment]
https://github.com/Azure/azure-powershell/pull/10339

Request created from private branch to resolve merge conflict.

Closing the current pull request as it is not required

**Pull request closed without merging**
