### PR TITLE
Fix wrong parameter in example2 ObjectId vs Id

### PR DESCRIPTION
**Pull request by cblackuk**
## Description

ObjectId is not a parameter that gets returned by Get-AzureRMADGroup.

Instead Id is being returned that inside has got GUID.

This has been broken since the first iteration of the help file as I have checked all versions and they have the same mistake.

To reproduce:

```powershell
Get-AzureRMADGroup -SearchString "AzureStackUsers"

SecurityEnabled DisplayName     Id                                   Type
--------------- -----------     --                                   ----
           True AzureStackUsers 03b88d3c-43d4-4c16-a02f-9fd906bf26d0 Group
```

To see error message:

```powershell
Get-AzureRMADGroup -SearchString "AzureStackUsers" | Select-Object -ExpandProperty ObjectId
Select-Object : Property "ObjectId" cannot be found.
At line:1 char:54
+ ... archString "AzureStackUsers" | Select-Object -ExpandProperty ObjectId
+                                    ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (Microsoft.Azure...ctory.PSADGroup:PSObject) [Select-Object], PSArgumentException
    + FullyQualifiedErrorId : ExpandPropertyNotFound,Microsoft.PowerShell.Commands.SelectObjectCommand
```

To see GUID:

```powershell
Get-AzureRMADGroup -SearchString "AzureStackUsers" | Select-Object -ExpandProperty Id

Guid
----
03b88d3c-43d4-4c16-a02f-9fd906bf26d0
```

To get clean GUID:

```powershell
Get-AzureRMADGroup -SearchString "AzureStackUsers" | Select-Object -ExpandProperty Id | Select-Object -ExpandProperty Guid
03b88d3c-43d4-4c16-a02f-9fd906bf26d0

### Or .NET notation

(Get-AzureRMADGroup -SearchString "AzureStackUsers" | Select-Object -ExpandProperty Id).Guid
03b88d3c-43d4-4c16-a02f-9fd906bf26d0
```

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by vladimir-shcherbakov** [comment]
@cblackuk 
Unfortunately, changing output table column label in the help file will make it more confusing. PowerShell labels columns by property name in the [output type](https://github.com/Azure/azure-powershell/blob/8bd4c84a1b51b86ffc2d8977d5dcc438df480afa/src/Common/Commands.Common.Graph.RBAC/ActiveDirectory/PSADObject.cs#L23).  So. it would be strange to have label "ObjectId" in the example and "Id" in the real output.

Could you please open an issue instead and share your idea on improving the cmdlet user experience?

**Comment by cblackuk** [comment]
@vladimir-shcherbakov I do not really understand the problem.

Example listed is just plain wrong and I want to correct it to be what it actually is... It is massively confusing for me as it is now because simply it is incorrect output that looks like somebody just typed instead of copied from the actual command...

**Comment by vladimir-shcherbakov** [comment]
@cblackuk 
Ignore my comment please.

**Pull request merged**
