### PR TITLE
Add Premium SKU to PS

### PR DESCRIPTION
**Pull request by ahosnyms**
This PR is urgent for March release.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ahosnyms__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ahosny). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by shefaliv** [comment]
approved.

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
on demand run here:http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/613/

**Pull request merged**
