### PR TITLE
Remove Location Restriction from All Cmdlets for AzureChinaCloud

### PR DESCRIPTION
**Pull request by solankisamir**
All Cmdlets have Location check for Public Cloud Region, which is not needed for powershell to be compatible in both Public and AzureChinaCloud. The RP is doing that validation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@solankisamir__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by solankisamir** [comment]
On Demand Run http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/941/

**Comment by markcowl** [comment]
@solankisamir Please pull the latest - test failures look like a potential merge issue

**Comment by solankisamir** [comment]
started another on-demand run after merging to latest.
http://azuresdkci.cloudapp.net/job/powershell-demand/962/

**Comment by markcowl** [comment]
finally!  This is the hard luck PR that hit every flaky test

**Pull request merged**
