### PR TITLE
Add PowerShell commands support  for Azure Media Services.

### PR DESCRIPTION
**Pull request by fredericky**
- CRUD operations of media service account.
- List and regenerate the keys of media service account.
- Synchronize storage account keys for a storage account associated with the media service account.

ScenarioTests:
Done

UT:
Done (Playback mode of ScenarioTests)

Validation of sync storage account keys:
1. upload an asset to a media service account.
2. regenerate two keys of storage account and the above asset cannot be deleted because of different storage account keys.
3. run the sync cmdlet and after a while the above asset can be deleted.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@fredericky__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (yulei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@fredericky Have you onboarded with the team and had a design review of these cmdlets.  Please schedule a review with us.

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@fredericky Is this ready for us to look at?

**Comment by fredericky** [comment]
@markcowl , thanks very much for your feedback. I will let you know if we're ready.

**Comment by hovsepm** [comment]
@fredericky Code freeze for July sprint was on 7/01. Your changes will go in for August release.

**Pull request closed without merging**
