### PR TITLE
AzureRT 0.8.14 update

### PR DESCRIPTION
**Pull request by AzureRT**
Change IconName and SmallIconName from Uri to string

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AzureRT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by huangpf** [comment]
retest this please

**Comment by markcowl** [comment]
@huangpf failign in CI

**Comment by AzureRT** [comment]
@hyonholee

**Comment by huangpf** [comment]
retest this please

**Comment by markcowl** [comment]
@AzureRT @huangpf Closing in favor of this PR: https://github.com/Azure/azure-powershell/pull/155

**Pull request closed without merging**
