### PR TITLE
Azure-Powershell pull

### PR DESCRIPTION
**Pull request by vijaynar**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vijaynar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vijaynar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@vijaynar There are merge conflicts, please update the PR

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by ogail** [comment]
@vijaynar test failed please investigate

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
Why is there a test dll included in this PR?  Please remove the test dll.  This makes it very difficult for contributors.  If this is necessary, why can't it be built in this repo?

**Comment by markcowl** [comment]
@vijaynar Please add updates to changelog.txt for these changes

**Pull request merged**
