### PR TITLE
Major refactoring: name changes, adding more cmdlets and fixins some bugs

### PR DESCRIPTION
**Pull request by gucalder**

### CODE REVIEW

**Comment by gucalder** [comment]
Last failure was in some other team's tests. Merging and checking in again to see if that resolves the issue.

**Comment by gucalder** [comment]
Still failing one test in another project.

**Comment by gucalder** [comment]
Failing this way: D:\workspace\powershell\AzurePowershell.test.targets(104,5): error : Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ElasticPoolCrudTests.TestElasticPoolMetricGet [FAIL] [D:\workspace\powershell\build.proj]

**Comment by markcowl** [comment]
@gucalder this normally indicates an assembly load issue in the SQL cmdlets - does your PR update an assembly used by SQL?  If so, have you updated the appropriate assembly reference?

**Comment by gucalder** [comment]
I changes the name of the CmdLet called in the Sql test from Get-Metrics to Get-AzureRmMetric

**Comment by gucalder** [comment]
Another test is failing:

Microsoft.Azure.Commands.AzureBackup.Test.ScenarioTests.AzureBackupPolicyTests.SetProtectionPolicyTests
System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find a matching HTTP request for URL 'GET /Subscriptions/f5303a0b-fae4-4cdb-b44d-0e4c032dde26/resources?$filter=resourceType%20eq%20'Microsoft.Backup/BackupVault'&$top=100'. Calling method ListAsync().

That call does not seem like related to us. I am merging from dev.

**Comment by gucalder** [comment]
The tests passed.

**Comment by hovsepm** [comment]
on-demand:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/605/

**Comment by hovsepm** [comment]
new-ondemand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/607/

**Pull request merged**
