### PR TITLE
merge preview branch change to Storage branch

### PR DESCRIPTION
**Pull request by blueww**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@blueww What is being merged into preview here?

**Comment by blueww** [comment]
@maddieclayton 
I have target the PR to "AzureRM.Storage.Locatio" branch. This is to merge changes in preview to storage branch. Sorry for the wrong target before.

**Comment by blueww** [comment]
@maddieclayton 

The netcore build still fail with 

> System.Management.Automation.CommandNotFoundException : The term 'Set-AzRmStorageAccountManagementPolicy' is not recognized as the name of a cmdlet, function, script file, or operable program.

This cmdlet only exist in preview branch. I have added it to `tools\AliasMapping.json` and `src\ResourceManager\Profile\Commands.Profile\AzureRmAlias\Mappings.cs` . Do I miss anything?

Would you please help to fix this issue, and merge the PR if not other issue?

**Comment by maddieclayton** [comment]
@blueww Should pass now - looks like it was missing the entries in Az.Storage.psd1, and only the storage cmdlets with a name conflict between dataplane and management should have the "AzRm" prefix (all others will be Az)

**Comment by blueww** [comment]
@maddieclayton 
Thanks very much for fixing the build and merging the PR!

**Pull request merged**
