### PR TITLE
[Az.RecoveryServices.Backup] [preview] Adding support for cross tenant DS move

### PR DESCRIPTION
**Pull request by hiaga**
## Description

Adding support for cross tenant DS move in preview.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - Azure/azure-powershell-cmdlet-review-pr#932
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
will review after https://github.com/Azure/azure-powershell/pull/15139 is merged

**Comment by hiaga** [comment]
> will review after #15139 is merged

@msJinLei : I have added the commits on top of PR  https://github.com/Azure/azure-powershell/pull/15139 and re-recorded the test cases, is it is possible to directly merge this PR?

**Comment by msJinLei** [comment]
@hiaga It's cool to see your PR has passed pipeline check. However, i cannot merge feature PR with master sync PR for the reason that the latter one requires a non-squash merge while the previous one should be squashed.

**Comment by hiaga** [comment]
> @hiaga It's cool to see your PR has passed pipeline check. However, i cannot merge feature PR with master sync PR for the reason that the latter one requires a non-squash merge while the previous one should be squashed.

@msJinLei I will fix the tests in the other PR so that it can be merged. But I've a doubt - last time when I synced preview branch with master @isra-fel recommended that the commits should Ideally not be squashed. I'll leave it to you to decide whether it's better to squash or not. 

working on Sync PR test cases (so that it can be merged first)

**Comment by msJinLei** [comment]
Please syn with Az.RecoveryServices-preview

**Comment by hiaga** [comment]
> Please syn with Az.RecoveryServices-preview

@msJinLei Could you please review now ?

**Comment by BethanyZhou** [comment]
Hi @hiaga , have you proposed any design review on https://github.com/Azure/azure-powershell-cmdlet-review-pr? Please link it with this pr.

**Comment by hiaga** [comment]
Hi @BethanyZhou : We've the cmdlet review PR here - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/932

Others are minor changes.

**Review by BethanyZhou — APPROVED** [review]
LGTM

**Pull request merged**
