### PR TITLE
Change the type of parameter "Tags" to Hashtable

### PR DESCRIPTION
**Pull request by TianoMS**
1. Update the help methods in TagsConversionHelper to take Hashtable instead of Hashtable[]. 
2. Change the type of parameter "Tags" from Hashtable[] to Hashtable for all cmdlets. 
3. Update all test cases for the Tags change. 
4. Fix test failures. 
5. Update help messages for all resources cmdlets. 

[TODO]: Update help messages for all the other projects.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TianoMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by TianoMS** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1028/

**Comment by hovsepm** [comment]
LGTM. Merge after partner will sign off.

**Comment by hyonholee** [comment]
LGTM.

**Comment by markcowl** [comment]
@TianoMS Please update - there are merge conflicts.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1044/

LGTM once the build passes

**Comment by markcowl** [comment]
@TianoMS Two teat failures in the on-demand run

**Comment by TianoMS** [comment]
@markcowl Latest on demand job. All clear. 
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1048/.

**Pull request merged**
