### PR TITLE
[SQL] Merge branch 'preview' into 'AzureRM.Sql.STR'

### PR DESCRIPTION
**Pull request by adeal**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by dealaus** [comment]
From the Travis failure, it looks like we need to map the Az.->AzureRM cmdlets now, but I don't see any docs on doing this. Are we supposed to run tools/CreateAliasMapping.ps1?

**Comment by jaredmoo** [comment]
I didn't directly review, but merge preview into STR is fine to do.

**Comment by maddieclayton** [comment]
@dealaus Apologies, we don't have docs on the aliases as they are just a temporary measure.  To update, run the tools/CreateAliasMapping script.  This will update the tools/AliasMappings.json.  From there you will need to copy over the contents of the file into the src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.cs file in the jsonMappings string.  Alternatively, since you are just adding a few cmdlet mappings, you could do it manually in src/ResourceManager/Profile/Commands.Profile/AzureRmAlias/Mappings.cs file in the jsonMappings string

**Comment by dealaus** [comment]
@maddieclayton hmmm, I think I've done that in in this commit https://github.com/Azure/azure-powershell/pull/7050/commits/f81e97f17b1301febb72cfce2a11e789918c9e23 but Travis still thinks the cmdlets don't exist. What am I doing wrong here?

**Comment by maddieclayton** [comment]
Oh yeah looks like it isn't picking up the name of the Az cmdlet, but the alias is working.  Can you make sure all the new cmdlets made it into Az.Sql.psd1?

**Comment by dealaus** [comment]
Closing due to the above problem and this merge is not a pressing issue.

**Pull request closed without merging**
