### PR TITLE
fix network watcher skipped tests

### PR DESCRIPTION
**Pull request by junyezhu**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@junyezhu Looks like some of your tests are still failing: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/6803/artifact/src/Publish/TestResults/FailingTests/Microsoft.Azure.Commands.Network.Test.dll.html.  Assigning back to you.

**Comment by junyezhu** [comment]
@maddieclayton The failed test is caused by issue "The term 'New-AzureStorageContext' is not recognized as the name of a cmdlet, function, script file, or operable program.", but this command works fine in powershell window, and it works in my local test run. So according to Cormac, " We're in the process of moving from shipping the AzureRM module, which only works on Windows, to shipping an Az module, which works on Windows/Mac/Linux, and that is currently what Travis is using. This change changes the AzureRm prefix for all cmdlets to be just Az, so I would assume that the cmdlet is now New-AzStorageContext." He is helping me check with the devs who is on this change when they get in to see how we should mitigate this issue so it works on Travis but doesn't break the Jenkins build. Please let me know if you have any context on this issue. Thanks

**Comment by maddieclayton** [comment]
@junyezhu I'll take a look at the Travis failure.  Looks like the failure on Jenkins (which I linked) is an actual error on your side - can you take a look?

**Comment by maddieclayton** [comment]
@junyezhu Looks like now you are just hitting cred scan issues: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/6999/console (bottom of the console output has the path to the matches and the doc on how to address the credscan issues).

**Comment by junyezhu** [comment]
@maddieclayton According to the doc, which file should I add to suppressions array of CredScanSuppressions.json file?

**Comment by maddieclayton** [comment]
@junyezhu The file here: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/6999/artifact/src/Package/CredentialScannerOutput/CredScanIssues.csv/*view*/

**Pull request merged**
