### PR TITLE
Update to R5 RP 2019-07-01 API

### PR DESCRIPTION
**Pull request by leonardbf**
- new .net SDK version
 - nfsv4 renamed to nfsv4.1
 - snapshot creation date renamed to created
 - internal ticket ANF-243
 - replaces PR https://github.com/Azure/azure-powershell/pull/10294

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @leonardbf , the change of output will be a breaking change, we can only accept these PR at a breaking change release.

**Comment by leonardbf** [comment]
> Hi @leonardbf , the change of output will be a breaking change, we can only accept these PR at a breaking change release.

ok, thanks. My first thought though is to confirm that the NetApp PowerShell is not in preview. Of course the service is GA but I thought the ANF PS itself was still in preview. At least I know that the CLI is still in preview but I'm not sure where to check for the PS.

If it is indeed not preview, when can we expect a breaking change release, how often do they occur? Is there any action required by me?

Finally, how can we handle this going forward. We have new swaggers almost monthly at the moment, and I'd expect each of these to cause breaking changes in the resulting PowerShell. Actually, this also makes me wonder whether the last update to ANF PS, relating to swagger version 2019-06-01, also involved breaking changes.

**Comment by wyunchi-ms** [comment]
Hi @leonardbf we do ignite release every 6 months. Unfortunately our ignite release just finish at 2019-11-04, so the next ignite release will be in 2020 May. I think if your cmdlets is not stable, you can publish them in preview version first. You can find some info [here](https://gist.github.com/cormacpayne/5ff303250b92d6a3f7392a42c2d67088).

**Comment by wyunchi-ms** [comment]
Hi @leonardbf sorry I misunstand your words. I thought your module is already in GA. It's acceptable since your module is not in GA yet.

**Pull request merged**
