### PR TITLE
Desktopvirtualization 2024 04 08

### PR DESCRIPTION
**Pull request by ryanosh**
## Description

Updated preview cmdlets for HostPoolUpdate feature to be compliant with OKW security requirements. 
    Removed the get-SessionHostManagementOperationStatus endpoint and replaced it with Get-SessionHostManagementUpdateStatus
    Removed the get-SessionHostConfigurationOperationStatus endpoint

Added a new custom MSI Identity definition and HostPool reference to it.

New properties added to Appattach Object: PackageOwnerName, PackageLookbackURL, and CustomData to support 3rd party applications

Added "MultiplePersistent" enum value to HostPool property loadBalancerType

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [X] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by ryanosh** [comment]
Hi @msJinLei, I'm trying to get this preview release completed by October 15th. Looking at the StaticAnalysis these errors all seem to be false positives. I know a teammate of mine ran into a similar issue on our GA release. Is there anything I can do to clear these up?

**Comment by msJinLei** [comment]
@ryanosh 
The reported breaking changes are caused by type changes are not false positive.
You have example issues in static analysis

**Comment by ryanosh** [comment]
Added changelog in the description copied below: 

Updated preview cmdlets for HostPoolUpdate feature to be compliant with OKW security requirements. 
    Removed the get-SessionHostManagementOperationStatus endpoint and replaced it with Get-SessionHostManagementUpdateStatus
    Removed the get-SessionHostConfigurationOperationStatus endpoint

Added a new custom MSI Identity definition and HostPool reference to it.

New properties added to Appattach Object: PackageOwnerName, PackageLookbackURL, and CustomData to support 3rd party applications

Added "MultiplePersistent" enum value to HostPool property loadBalancerType

**Pull request merged**
