### PR TITLE
update OperationalInsights sdk version reference.

### PR DESCRIPTION
**Pull request by haitch**
to support paging for Microsoft.OperationalInsights/Workspaces/DataSources

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@haitch__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by haitch** [comment]
Can anyone remove this cla-required label? I am MSFT employee, just change my GitHub alias yesterday.

**Comment by markcowl** [comment]
@haitch done

On demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1070/

LGTM once the build passes.

**Comment by haitch** [comment]
it appears to fail with Microsoft.WindowsAzure.Commands.Test.Websites.SaveAzureWebsiteLogTests.**SaveAzureWebsiteLogWithNoFileExtensionTest**, while I didn't touch this area.

**Comment by cormacpayne** [comment]
On demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1076/

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@azuresdkci test this please

**Pull request merged**
