### PR TITLE
Adding US Government Connection

### PR DESCRIPTION
**Pull request by zakramer**
Changing the name of the Gov Cloud and adding an RM connection section for Azure
Gov.

I was working with some Azure Gov customers and this was not clear to them so it seemed like we should add it since we need this type of connection to create KeyVault and other services with PowerShell in Azure Gov.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@zakramer__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zakramer). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@azuresdkci test this please.

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Pull request merged**
