### PR TITLE
Update Start-AzureRmRecoveryServicesAsrTestFailoverCleanupJob.md

### PR DESCRIPTION
**Pull request by maorteg**
The example 2 "Clean up Test Failover using Recovery Plan" code is incorrect. I tested this on my lab and confirmed that correct syntax should be  < Start-AzureRmRecoveryServicesAsrTestFailoverCleanupJob -RecoveryPlan $recoveryPlan -Comment "testing done" >.

Please, update the documentation accordingly.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
@maorteg Hey Marvin, thanks for the fix! 😀 

@viverm Hey Vipin, would you mind taking a look at this PR when you have the chance?

**Comment by viverm** [comment]
@maorteg  Thanks for PR.

@cormacpayne can we merge this PR for next release.  

Change is in help file.

**Pull request merged**
