### PR TITLE
[NetAppFiles] Add 2022-05-01 changes

### PR DESCRIPTION
**Pull request by audunn**
## Description

This updates the Azure NetAppFiles module to api-version 2022-05-01

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1299

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by dingmeng-xue** [comment]
We found below errors in reference docs. Please help to resolve them.

  "Az.NetAppFiles","Remove-AzNetAppFilesVolumeQuotaRule","1","0","MissingExampleDescription","5046","1","Description of the example is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Remove-AzNetAppFilesVolumeQuotaRule.md","Add description for the example. Remove any placeholders."
  "Az.NetAppFiles","Reset-AzNetAppFilesVolumeCifsPassword","0","0","MissingSynopsis","5040","1","Synopsis is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Reset-AzNetAppFilesVolumeCifsPassword.md","Add Synopsis. Remove any placeholders."
  "Az.NetAppFiles","Reset-AzNetAppFilesVolumeCifsPassword","0","0","MissingDescription","5041","1","Description is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Reset-AzNetAppFilesVolumeCifsPassword.md","Add Description. Remove any placeholders."
  "Az.NetAppFiles","Reset-AzNetAppFilesVolumeCifsPassword","1","0","MissingExampleCode","5044","1","Code of the example is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Reset-AzNetAppFilesVolumeCifsPassword.md","Add code for the example. Remove any placeholders."
  "Az.NetAppFiles","Reset-AzNetAppFilesVolumeCifsPassword","1","0","MissingExampleDescription","5046","1","Description of the example is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Reset-AzNetAppFilesVolumeCifsPassword.md","Add description for the example. Remove any placeholders."
  "Az.NetAppFiles","Reset-AzNetAppFilesVolumeCifsPassword","1","0","NeedDeleting","5050","1","The prompt of example need to be deleted.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Reset-AzNetAppFilesVolumeCifsPassword.md","Delete the prompt of example."
  "Az.NetAppFiles","Restore-AzNetAppFilesReplication","0","0","MissingSynopsis","5040","1","Synopsis is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Restore-AzNetAppFilesReplication.md","Add Synopsis. Remove any placeholders."
  "Az.NetAppFiles","Restore-AzNetAppFilesReplication","0","0","MissingDescription","5041","1","Description is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Restore-AzNetAppFilesReplication.md","Add Description. Remove any placeholders."
  "Az.NetAppFiles","Restore-AzNetAppFilesReplication","1","0","MissingExampleCode","5044","1","Code of the example is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Restore-AzNetAppFilesReplication.md","Add code for the example. Remove any placeholders."
  "Az.NetAppFiles","Restore-AzNetAppFilesReplication","1","0","MissingExampleDescription","5046","1","Description of the example is missing.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Restore-AzNetAppFilesReplication.md","Add description for the example. Remove any placeholders."
  "Az.NetAppFiles","Restore-AzNetAppFilesReplication","1","0","NeedDeleting","5050","1","The prompt of example need to be deleted.","D:\a\_work\1\s\src\NetAppFiles\NetAppFiles\help\Restore-AzNetAppFilesReplication.md","Delete the prompt of example."
  "Az.NetAppFiles","Get-AzNetAppFilesVolumeQuotaRule","1","1","Invalid_Cmdlet","5000","1","Get-AzNetAppFilesVolumeQuotaRule is not a valid command name.","Get-AzNetAppFilesVolumeQuotaRule -ResourceGroupName 'MyRG' -AccountName 'MyAnfAccount' -VolumeName 'MyAnfVolume' -Name 'MyVolumeQuotaRuleName'","Check the spell of Get-AzNetAppFilesVolumeQuotaRule."
  "Az.NetAppFiles","Get-AzNetAppFilesVolumeReplication","1","1","Invalid_Cmdlet","5000","1","Get-AzNetAppFilesVolumeReplication is not a valid command name.","Get-AzNetAppFilesVolumeReplication -ResourceGroupName MyGroup -AccountName MyAccount -PoolName MyPool -Name MyVolume","Check the spell of Get-AzNetAppFilesVolumeReplication."
  "Az.NetAppFiles","New-AzNetAppFilesAccount","1","1","Invalid_Cmdlet","5000","1","New-AzNetAppFilesAccount is not a valid command name.","New-AzNetAppFilesAccount -ResourceGroupName 'MyRG' -Name 'MyAnfAccount' -Location 'westus2'","Check the spell of New-AzNetAppFilesAccount."
  "Az.NetAppFiles","New-AzNetAppFilesVolume","1","1","Invalid_Cmdlet","5000","1","New-AzNetAppFilesVolume is not a valid command name.","New-AzNetAppFilesVolume -ResourceGroupName 'MyRG' -AccountName 'MyAnfAccount' -PoolName 'MyAnfPool' -Name 'MyAnfVolume' -Location 'westus2' -CreationToken 'MyAnfVolume' -UsageThreshold 1099511627776 -ServiceLevel 'Premium' -SubnetId '/subscriptions/subsId/resourceGroups/MyRG/providers/Microsoft.Network/virtualNetworks/MyVnetName/subnets/MySubNetName'","Check the spell of New-AzNetAppFilesVolume."
  "Az.NetAppFiles","New-AzNetAppFilesVolumeQuotaRule","1","1","Invalid_Cmdlet","5000","1","New-AzNetAppFilesVolumeQuotaRule is not a valid command name.","New-AzNetAppFilesVolumeQuotaRule -ResourceGroupName $resourceGroup -Location $resourceLocation -AccountName 'MyAnfAccount' -PoolName 'MyAnfPool' -VolumeName 'MyAnfVolume' -Name 'MyAnfVolumeQuotaRule' -QuotaType 'DefaultGroupQuota' -QuotaSizeInKiBs 100006","Check the spell of New-AzNetAppFilesVolumeQuotaRule."
  "Az.NetAppFiles","Remove-AzNetAppFilesVolumeQuotaRule","1","1","Invalid_Cmdlet","5000","1","Remove-AzNetAppFilesVolumeQuotaRule is not a valid command name.","Remove-AzNetAppFilesVolumeQuotaRule -ResourceGroupName 'MyRG' -AccountName 'MyAnfAccount' -VolumeName 'MyAnfVolume' -Name 'MyVolumeQuotaRuleName'","Check the spell of Remove-AzNetAppFilesVolumeQuotaRule."
  "Az.NetAppFiles","Update-AzNetAppFilesPool","1","1","Invalid_Cmdlet","5000","1","Update-AzNetAppFilesPool is not a valid command name.","Update-AzNetAppFilesPool -ResourceGroupName 'MyRG' -Location 'westus2' -AccountName 'MyAnfAccount' -PoolName 'MyAnfPool' -PoolSize 4398046511104 -QosType 'Auto'","Check the spell of Update-AzNetAppFilesPool."
  "Az.NetAppFiles","Update-AzNetAppFilesVolume","1","1","Invalid_Cmdlet","5000","1","Update-AzNetAppFilesVolume is not a valid command name.","Update-AzNetAppFilesVolume -ResourceGroupName 'MyRG' -Location 'westus2' -AccountName 'MyAnfAccount' -PoolName 'MyAnfPool' -Name 'MyAnfVolume' -UsageThreshold Size","Check the spell of Update-AzNetAppFilesVolume."
  "Az.NetAppFiles","Update-AzNetAppFilesVolumeQuotaRule","1","1","Invalid_Cmdlet","5000","1","Update-AzNetAppFilesVolumeQuotaRule is not a valid command name.","Update-AzNetAppFilesVolumeQuotaRule -ResourceGroupName 'MyRG' -AccountName 'MyAnfAccount' -VolumeName 'MyAnfVolume' -Name 'MyVolumeQuotaRuleName' -QuotaSizeInKiBs 100006","Check the spell of Update-AzNetAppFilesVolumeQuotaRule."

**Comment by dingmeng-xue** [comment]
@audunn , you forgot to record this test case https://github.com/Azure/azure-powershell/blob/main/src/NetAppFiles/NetAppFiles.Test/ScenarioTests/AccountTests.cs#L44

**Comment by audunn** [comment]
@dingmeng-xue  is it possible to re-run pipeline here,  Seems I don't have access to run `/azp run` on this repo but it would like to re run if there are piplien issues like `API rate limit exceeded`

**Review by dingmeng-xue — APPROVED** [review]

**Pull request merged**
