### PR TITLE
Update New-AzureRmDeployment.md

### PR DESCRIPTION
**Pull request by fleckert**
fixed cmdlet name

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
LGTM

**Comment by wyunchi-ms** [comment]
LGTM

**Comment by wyunchi-ms** [comment]
Hi @fleckert , as we are migrating to `Az` module and this have been fixed in the [lastest document](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azdeployment?view=azps-3.5.0#description). I'm closing this issue. Thanks a lot for your feedback again!

**Comment by fleckert** [comment]
Hi @wyunchi-ms,
 
the cmdlet [New-AzureRmDeployment](https://docs.microsoft.com/en-us/powershell/module/azurerm.resources/new-azurermdeployment?view=azurermps-6.13.0) is still in use at customers and supported by Microsoft until end of 2020.

The [latest document](https://docs.microsoft.com/en-us/powershell/module/az.resources/new-azdeployment?view=azps-3.6.1) is about 'New-AzDeployment' and might not be found by somebody searching for 'New-AzureRmDeployment'.

**Pull request closed without merging**
