### PR TITLE
release notes updates for the release 1.2.11

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Comment by markcowl** [comment]
on demand:http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1931/

packaging: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/posh-pack/46/

**Comment by bganapa** [comment]
@markcowl  posh-pack did not produce AzureStack package, im looking

**Comment by bganapa** [comment]
@markcowl fixed, kicking off ondemand and posh-pack

**Comment by bganapa** [comment]
Ondemand - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1933/
Posh-pack - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/posh-pack/48/

**Comment by bganapa** [comment]
@markcowl @cormacpayne  this PR is good to merge, i have quickly validated the new packages, Ondemand is successful as well

**Pull request merged**
