### PR TITLE
Revert "Pass principal type during role assignment put operations"

### PR DESCRIPTION
**Pull request by dagoroz**
Reverts Azure/azure-powershell#13590

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @dagoroz , any particular reason this need to be reverted?

**Comment by dingmeng-xue** [comment]
LGTM except changelog. I prefer that you just explain the change you did. For instance, removed (past tense is recommended) principal type on New-AzRoleAssignment and Set-AzRoleAssignment because …. (if there is any reason)

**Comment by dagoroz** [comment]
@VeryEarly added you to the email thread

**Comment by VeryEarly** [comment]
Hi @dagoroz ,

Due to the Divergence of master branch (base branch of your PR) and release branch, I've created a new PR (from release branch and cherry-picked your commits).
https://github.com/Azure/azure-powershell/pull/14122

**Pull request closed without merging**
