### PR TITLE
ARM compliance changes for Azure Site Recovery (ASR) Service, Support for RecoveryServices Vault operations and RDFE Recovery Services dll name change in order to differenciate from the ARM dll

### PR DESCRIPTION
**Pull request by avneeshrai**
1) ARM compliance changes for Azure Site Recovery (ASR) Service.
2) Support for RecoveryServices Vault operations.
3) RDFE Recovery Services dll name change in order to differenciate from the ARM dll.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@avneeshrai__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (avrai). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jianghaolu** [comment]
@azuresdkci test this please

**Comment by jianghaolu** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@avneeshrai Are these part of the release this week?  If so, please target at the SiteRecovery branch.  Also, there are merge conflicts, please update for these

**Comment by sriramvu** [comment]
yes, have resolved merge conflicts, will target to SiteRecovery branch.
Thank you.

**Comment by sriramvu** [comment]
Closed this PR and opened new one targetting Azure:SiteRecovery
https://github.com/Azure/azure-powershell/pull/1268

Thank you.

**Pull request closed without merging**
