### PR TITLE
[CosmosDB] Bug Fixes and Enhancements

### PR DESCRIPTION
**Pull request by MehaKaushik**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
- As you have add new parameters, please update the related cmdlets' help file
- please add change description into https://github.com/Azure/azure-powershell/blob/339d8dbda1816fc7b5151b753c75df2c1831c769/src/CosmosDB/CosmosDB/ChangeLog.md below upcoming release

**Comment by MehaKaushik** [comment]
> In NewAzCosmosDBAccount.cs and UpdateAzCosmosDBAccount.cs
> 
> https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/CosmosDBAccount/NewAzCosmosDBAccount.cs#L191 through line 203
> 
> https://github.com/Azure/azure-powershell/blob/master/src/CosmosDB/CosmosDB/CosmosDBAccount/UpdateAzCosmosDBAccount.cs#L175 through line 187
> 
> I suggest handling the IP filter range like this, replacing the above blocks within the check that IpRangeFilter was non-null (i.e. the following only applies when IpRangeFilter was actually passed).
> 
> string IpRangeFilterAsString = IpRangeFilter?.Aggregate(string.Empty, (output, next) => string.Concat(output, (!string.IsNullOrWhiteSpace(output) && !string.IsNullOrWhiteSpace(next) ? "," : string.Empty), next)) ?? string.Empty;
> 
> Reasons:
> 
> 1. This is one line, not a block that has different code for [0] and indexes > 0.
> 2. IpRangeFilterAsString will always be non-null this way. In the current implementation and this PR, IpRangeFilterAsString can still be null if a non-null but empty IpRangeFilter is passed, implying any existing rules should be removed. Would it make more sense to pass an empty string, i.e. not null, to back end in this case? The above code does that.

Thanks for the suggestion, addressed it.

**Comment by MehaKaushik** [comment]
> * As you have add new parameters, please update the related cmdlets' help file
> * please add change description into https://github.com/Azure/azure-powershell/blob/339d8dbda1816fc7b5151b753c75df2c1831c769/src/CosmosDB/CosmosDB/ChangeLog.md below upcoming release

@msJinLei 
Addressed your comments, rebasing with latest master resulted in showing the diff of commits merged in master by other teams.

**Comment by MehaKaushik** [comment]
Moving to PR https://github.com/Azure/azure-powershell/pull/11513

**Pull request closed without merging**
