### PR TITLE
Remove permission from ResourceGroup cmdlet output

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivsriaus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (visriniv). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
Please update Microsoft.Azure.Commands.ResourceManager.Cmdlets.dll-Help.xml documentation for the affected cmdlets.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/256/

**Comment by vivsriaus** [comment]
@markcowl The tests are failing with this error. Not sure if these are related to my changes, but I'm running the job again to ensure it's not a one-off issue

Cannot load Windows PowerShell snap-in Microsoft.PowerShell.Management because of the following error: Could not load file or assembly 'Microsoft.PowerShell.Commands' or one of its dependencies. The system cannot find the file specified.
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadMshSnapinAssembly(PSSnapInInfo mshsnapinInfo)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIn(PSSnapInInfo mshsnapinInfo)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadPSSnapIns(Collection`1 mshsnapinInfos, PSConsoleLoadException& warning)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.LoadConsole(PSConsoleLoadException& warning)
   at System.Management.Automation.Runspaces.RunspaceConfigForSingleShell.CreateDefaultConfiguration()
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace(PSHost host)
   at System.Management.Automation.Runspaces.RunspaceFactory.CreateRunspace()
   at System.Management.Automation.PowerShell.get_Runspace()
   at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in d:\workspace\powershell-on-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs:line 331
   at Microsoft.Azure.Commands.SiteRecovery.Test.ScenarioTests.SiteRecoveryTestsBase.RunPowerShellTest(String[] scripts) in d:\workspace\powershell-on-demand\src\ResourceManager\SiteRecovery\Commands.SiteRecovery.Test\ScenarioTests\SiteRecoveryTestsBase.cs:line 105
   at Microsoft.Azure.Commands.SiteRecovery.Test.ScenarioTests.SiteRecoveryTests.EnumerationTests() in d:\workspace\powershell-on-demand\src\ResourceManager\SiteRecovery\Commands.SiteRecovery.Test\ScenarioTests\SiteRecoveryTests.cs:line 26

**Comment by markcowl** [comment]
new run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/267/

**Comment by hovsepm** [comment]
new run here - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/276/

**Pull request merged**
