### PR TITLE
changes to Get-WAPackVM cmdlet to fetch more information

### PR DESCRIPTION
**Pull request by sanjkum**
The pull request contains changes to Get-WAPackVM to retrieve following informations:
VirtualNetworkAdapters
VMCheckpoints
VirtualSCSIAdapters
VirtualHardDisks
VirtualDVDDrives
VirtualDiskDrives

### CODE REVIEW

**Comment by shahabhijeet** [comment]
@sanjkum please sign CLA and then submit the PR again next week.

**Comment by sanjkum** [comment]
@shahabhijeet could you please help me on how to sign the CLA. I am not finding any link to do so.

**Comment by cormacpayne** [comment]
@sanjkum you can read on how to sign the CLA here: https://azure.github.io/guidelines/#cla

**Comment by sanjkum** [comment]
@cormacpayne @shahabhijeet  I am MSFT and as per the CLA , Microsoft full time employees are not required to sign CLA. Is it still required ?

**Comment by shahabhijeet** [comment]
@sanjkum can you intergrate with aka.ms/azuregithub so that the bot knows you are internal to MSFT.

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@sanjkum Can we add a test for the changes?

**Pull request merged**
