### PR TITLE
LB documentation update

### PR DESCRIPTION
**Pull request by anavinahar**
Updated help associated with few load balancer cmdlets

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anavinahar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (annahar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@anavinahar It looks like your update removed the help for several Newtwork cmdlets, see: http://azuresdkci.cloudapp.net/job/powershell/6106/artifact/src/Package/HelpIssues.csv  You will need to put the help back,

**Comment by markcowl** [comment]
on demand run here:http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1075/

LGTM once the build passes.

**Comment by cormacpayne** [comment]
On demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1078/

**Pull request merged**
