### PR TITLE
Remove culture from help markdown files

### PR DESCRIPTION
**Pull request by Youri970410**
## Description

update MarkDown file to remove specified language

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Like we discussed, after we removed the locale info in document url, static analysis failed.
I'll try to find a solution.

**Comment by isra-fel** [comment]
Please update the pattern we use to check online doc urls as well to fix static analysis issue:

https://github.com/Azure/azure-powershell/blob/master/tools/HelpGeneration/HelpGeneration.psm1#L228

**Comment by Youri970410** [comment]
@isra-fel  Thanks for your reminder,Updated.

**Comment by isra-fel** [comment]
Hi there are still a few conflicts blocking CI

**Comment by isra-fel** [comment]
A few new cmdlets' document need to be updated, and I think that's the only thing left.
```
  Target                                  Description
  ------                                  -----------
  Get-AzContainerRegistryManifest.md      Online version in the header of the file is incorrect. The corresponding URL s.
  Get-AzContainerRegistryRepository.md    Online version in the header of the file is incorrect. The corresponding URL s.
  Get-AzContainerRegistryTag.md           Online version in the header of the file is incorrect. The corresponding URL s.
  Remove-AzContainerRegistryManifest.md   Online version in the header of the file is incorrect. The corresponding URL s.
  Remove-AzContainerRegistryRepository.md Online version in the header of the file is incorrect. The corresponding URL s.
  Remove-AzContainerRegistryTag.md        Online version in the header of the file is incorrect. The corresponding URL s.
  Update-AzContainerRegistryManifest.md   Online version in the header of the file is incorrect. The corresponding URL s.
  Update-AzContainerRegistryRepository.md Online version in the header of the file is incorrect. The corresponding URL s.
  Update-AzContainerRegistryTag.md        Online version in the header of the file is incorrect. The corresponding URL s.
  Add-AzRouteServerPeer.md                Online version in the header of the file is incorrect. The corresponding URL s.
  Get-AzRouteServer.md                    Online version in the header of the file is incorrect. The corresponding URL s.
  Get-AzRouteServerPeer.md                Online version in the header of the file is incorrect. The corresponding URL s.
  New-AzRouteServer.md                    Online version in the header of the file is incorrect. The corresponding URL s.
  Remove-AzRouteServer.md                 Online version in the header of the file is incorrect. The corresponding URL s.
  Remove-AzRouteServerPeer.md             Online version in the header of the file is incorrect. The corresponding URL s.
  Update-AzRouteServer.md                 Online version in the header of the file is incorrect. The corresponding URL s.
  Update-AzRouteServerPeer.md             Online version in the header of the file is incorrect. The corresponding URL s.
  Import-AzWebAppKeyVaultCertificate.md   Online version in the header of the file is incorrect. The corresponding URL s.
  Get-AzWindowsIotServicesDevice.md       Online version in the header of the file is incorrect. The corresponding URL s.
```

**Comment by Youri970410** [comment]
@isra-fel updated,thanks

**Review by wyunchi-ms — DISMISSED** [review]

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
