### PR TITLE
Upgrade ADAL 2.28.1

### PR DESCRIPTION
**Pull request by cormacpayne**
Upgrade ClientRuntime.Authentication 2.2.7-preview
Upgrade Hydra Test Framework 1.0.6052.28118-prerelease

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@cormacpayne__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
On demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1039/

**Comment by cormacpayne** [comment]
On demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1046/

**Pull request merged**
