### PR TITLE
KeyVault: Show DisplayName in Access Policies for AAD groups

### LINKED ISSUE #2243: get-azurermkeyvault does not return "display name" when the object is a group
Create a group in AD
Grant permission to the group to your vault (keys and/or secrets)
Run get-AzureRmKeyVault
Expected: for permission listing on the group, a valid display name
Actual: nothing

### PR DESCRIPTION
**Pull request by pshelton-skype**
## Description
Properly display the `Display Name` attribute when the AAD object that holds the access policy is a AAD Group, rather than just when it is a ServicePrincipal or User.

This changes the access policy output of:
```
> Get-AzureRmKeyVault -VaultName MyVault
```
from:
```
Tenant ID                   : <TenantId>
Object ID                   : <ObjectId>
Application ID              : <ApplicationId>
Display Name                :
Permissions to Keys         : list
Permissions to Secrets      : get, list
Permissions to Certificates : get, list
```
to:
```
Tenant ID                   : <TenantId>
Object ID                   : <ObjectId>
Application ID              : <ApplicationId>
Display Name                : MyAADGroupName
Permissions to Keys         : list
Permissions to Secrets      : get, list
Permissions to Certificates : get, list
```
Resolves #2243 

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [ ] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [ ] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.
- [ ] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [ ] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [ ] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [ ] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [ ] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [ ] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by pshelton-skype** [comment]
I verified the changes by building the project, running the built installer, and comparing the output against my production KeyVault configuration. I spent some time looking into unit tests, but the guidance for how to leverage the functional test infrastructure for this change was unclear and there appear to be no unit tests against `Get-AzureRmKeyVault` functionality currently.

If tests are required here, suggestions would be appreciated.

**Comment by pomortaz** [comment]
@pshelton-skype thanks for the fix. [This](https://github.com/Azure/azure-powershell/blob/dev/src/ResourceManager/KeyVault/Commands.KeyVault.Test/Scripts/readme.txt) is how we test powershell for key vault.

**Comment by pshelton-skype** [comment]
@pomortaz - Is the CI step stuck? It seems like it's been waiting on the "default" check since last night.

**Comment by pomortaz** [comment]
@cormacpayne why is the CI job stuck?

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by shahabhijeet** [comment]
@pshelton-skype is there any test that can cover your changes? If yes can you point me the test.
If there isn't any, you will need to add a test for this change.
If the test can be added today, we will take this fix, else you will have to submit it again next week, when we are open to accept PRs

**Comment by pshelton-skype** [comment]
@shahabhijeet, based on my investigations, there's currently no test coverage of this function in unit tests and no unit tests are mocking the KeyVault management plane, only the data plane. My first try made it seem non-trivial to do so, but this is my first time in the code base, so I could be mistaken.

The instructions for adding a functional test, particularly one on the management plane, were unclear, and any tests need to use multiple types of pre-created AAD accounts to verify this particular fix. A handful of tests verify add/remove access policies for ServicePrincipals and Users, but nothing for Groups, and none of these tests are related to Get-AzureRmKeyVault. 

I need guidance for how we would test this change. If someone tells me that it's as simple as writing a test similar to an existing one, I'm happy to investigate adding it, but that doesn't appear to be the case.

**Comment by shahabhijeet** [comment]
@pshelton-skype as we talked over email, I am closing this PR for now.
Please reopen the same PR once the PR is ready with the tests and ready for review.

**Pull request closed without merging**
