### PR TITLE
Fix Get-AzureRmVM paging with ResourceGroupName

### PR DESCRIPTION
**Pull request by jabbera**
Add paging support to Get-AzureRmVM when -ResourceGroupName parameter is set.

Many apologies. I was trying to make the change requested by the code review at Ignite on a new machine and accidentally rebased away all history on my branch causing the [PR](https://github.com/Azure/azure-powershell/pull/7292) to close. (Curse you depth of 1 clone) I was not able to recover it.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@jabbera @hyonholee do we know how long this scenario has been broken? It seems that there is already an [existing test](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute.Test/ScenarioTests/VirtualMachineTests.ps1#L2015-L2074) that covers this paging functionality (specifically, more than 50 entries), and it hasn't been failing, so do we know why this test isn't failing or how it was previously recorded?

**Comment by jabbera** [comment]
Our vendor couldn’t reproduce the issue. Maybe it was tennant or subscription specific? It broke for us on 9/17 and was resolved  yesterday.

**Comment by jabbera** [comment]
As for why the test worked it’s because that api never seemed to page before. The test erroneously assumed it was because the paving code existed when in reality that api didn’t page.

**Comment by hyonholee** [comment]
LGTM.   Paging will be available only for the latest version (2018-10-01 version and after). 

@cormacpayne  Please merge this PR.  Then I will update Compute client library to the latest version so that the cmdlet returns all pages.  (Note that this PR does not break old API version, because for old API version, the service does not return nextlink, in which this PR behaves the same as before.)

Thanks,

**Pull request merged**
