### PR TITLE
Add Optional Parameter "Billing Type" to Express Route Direct

### PR DESCRIPTION
**Pull request by nimaller**
## Description

Adding optional property "Billing Type" to express route direct. 
Design approved: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1124

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @nimaller the changelog needs to go under the "Upcoming Release" section instead of any released versions. I've changed it for you.

**Review by isra-fel — DISMISSED** [review]

**Comment by isra-fel** [comment]
Correct me if I'm wrong @nimaller but your feature doesn't rely on a new release of the network SDK, so you should be able to go directly to the main branch.

**Comment by nimaller** [comment]
@isra-fel Thanks you for reviewing. I have added the property billing type in swagger and it should be part of the latest sdk. If I understand correctly, the guidelines for Networking is to use the release branch and not main

**Comment by nimaller** [comment]
@isra-fel gentle ping on this PR :)

**Comment by isra-fel** [comment]
Will merge once #20693 is resolved.

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DistributedAvailabilityGroupTests.TestManagedInstanceLinkPiping [FAIL] failing
could be a random failure, retrying

**Pull request merged**
