### PR TITLE
Add new parameter for New-AzPublicIpPrefix

### PR DESCRIPTION
**Pull request by gitlwh**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @gitlwh , please sync your branch with latest network-march and add your change log under the top of upcoming section.

**Comment by gitlwh** [comment]
> Hi @gitlwh , please sync your branch with latest network-march and add your change log under the top of upcoming section.

What do you mean by that. I already added in the upcoming section and my other branch hasn't checked in yet. I need to wait for another to check in before I merge.

**Comment by BethanyZhou** [comment]
Hi @gitlwh , 

Could you add change log as following picture says? If not, your change log will not display in upcoming release section.  
image

**Review by BethanyZhou — APPROVED** [review]

**Pull request merged**
