### PR TITLE
Azure site recovery powershell release after moving to version 2021-02-10

### PR DESCRIPTION
**Pull request by nilgupta6**
* Fixing PFO/TFO/UFO build errors

* mulltiple ip per nic - cmdlet changes

* review changes

* code review changes

* moved validaton to nicConfig cmdlet and review changes

* minor fix

* handled review comments

* parameter validation changes, logs

* design review changes

* Fixing PFO/TFO/UFO build errors

* mulltiple ip per nic - cmdlet changes

review changes

code review changes

moved validaton to nicConfig cmdlet and review changes

minor fix

handled review comments

parameter validation changes, logs

design review changes
subash's multiple IP per NIC PR changes

* Fixing B2A, E2A and E2E Tests and added recording

* [ASR][V2A/H2A] TargetVmSize, AvSet, Sql RP and ResourceTagging changes for V2A and H2A

* Minor fix

* vmss changes -1

* 2) vmss changes - MD files

* Addressed review comments and added new tests and recordings for B2A

* vmss changes

* Addressed review comments

* Minor fixes

* Added V2A tests and recordings

* PR comments

* Update New-AzRecoveryServicesAsrReplicationProtectedItem.md

* Minor Fix

* Adding null for OdataQuery as its default value is also null.

* V2A test record json files

* Fix for Resource Tagging to clear off tags

* Minor fix in playback mode for v2a unit tests

Co-authored-by: Arpita Gupta <arpgup@microsoft.com>
Co-authored-by: subashchandra31 <subash.chandra@microsoft.com>
Co-authored-by: subashchandra31 <66659771+subashchandra31@users.noreply.github.com>
Co-authored-by: Arpitaji <78065343+Arpitaji@users.noreply.github.com>
Co-authored-by: Vidyadhari Jami <vijami@microsoft.com>
Co-authored-by: vidyadharijami <57709079+vidyadharijami@users.noreply.github.com>
Co-authored-by: prmyaka <prmyaka@microsoft.com>

## Description

SRS has updated API version to 2021-02-10
swagger PR: https://github.com/Azure/azure-rest-api-specs/pull/13525
SDK PR: https://github.com/Azure/azure-sdk-for-net/pull/20004

*  Azure Site Recovery support for Multiple IP per NIC for Azure to Azure provider.
* Azure Site Recovery support for SqlServerLicenseType for VMware to Azure and HyperV to Azure providers.
* Azure Site Recovery support for Availability set for VMware to Azure and HyperV to Azure providers.
* Azure Site Recovery support for TargetVmSize for VMware to Azure and HyperV to Azure providers.
* Azure Site Recovery support for ResourceTagging for VMware to Azure and HyperV to Azure providers.
* Azure Site Recovery support for Virtual Machine Scale Set for Azure to Azure provider.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/883   [Virtual Machine Scale Set for azure to azure design PR]
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/879   [Availability set, TargetVmSize for VMware to Azure and HyperV to Azure providers design PR]
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/888 [SqlServerLicenseType, ResourceTagging for VMware to Azure and HyperV to Azure providers design PR]
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/886 [Multiple IP per NIC design PR]
        
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
when will SDK be published?

**Comment by nilgupta6** [comment]
> when will SDK be published?

@VeryEarly We are targeting this week before 23rd april 2021.

**Comment by nilgupta6** [comment]
@Xynoclafe : can you please review this PR. We want to merge it for upcoming powershell release.

**Comment by Xynoclafe** [comment]
> 
> 
> @Xynoclafe : can you please review this PR. We want to merge it for upcoming powershell release.

@nilgupta6 I am not a part of the PowerShell team, so I can't really help with this PR. @VeryEarly should be able to help you with this.

**Comment by VeryEarly** [comment]
please fix conflicts

**Comment by nilgupta6** [comment]
@VeryEarly : All CI has passed. Can you please merge.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
