### PR TITLE
Modified test cases and examples of BlockChain.

### PR DESCRIPTION
**Pull request by LucasYao93**
#### Test cases
 - All changed. 

#### Examples
 - All changed.

#### Docs
 - Rebuild docs

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
@LucasYao93 please regenerate the md file under doc folder.

**Comment by LucasYao93** [comment]
> @LucasYao93 please regenerate the md file under doc folder.

**Comment by LucasYao93** [comment]
> @LucasYao93 please regenerate the md file under doc folder.

@msJinLei  I have regenerated the md file under doc folder.

**Pull request merged**
