### PR TITLE
[Storage] Upgrade to SRPSDK 11.0

### PR DESCRIPTION
**Pull request by blueww**
## Description

The change of this PR is also include in https://github.com/Azure/azure-powershell/pull/9005
（Since we need to upgrade both SDK in Build release, and they have some code change need merge）

Upgrade to SRP SDK 11.0.
The storage account Kind in SRP SDK is change from a enum to string, but the value is same.
So the PSStorageAccount.Kind also change type to string, but the value is same, so it won't block customer script.

There're 2 breaking changes :
1. change output type of `New/Get/Set-AzStorageAccount` : The `PSStorageAccount.Sku.Name` value is changed ('-' added). The Change is expected, since in New/Set-AzStorageAccount cmdlet, the input SkuName has '-' (before, the output don't have '-'), so with the change the input and output Sku Name value will be aligned. 
       "StandardLRS" -> "Standard_LRS";
       "StandardGRS" -> "Standard_GRS";
       "StandardRAGRS" -> "Standard_RAGRS";
       "StandardZRS" -> "Standard_ZRS";
       "PremiumLRS" -> "Premium_LRS";
       "PremiumZRS" -> "Premium_ZRS";

2. The default Storage Account Kind in  `New-AzStorageAccount` is changed to StorageV2. Since per SRP team, this should be the default Storage Kind.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by blueww** [comment]
@markcowl 

Would you please help to review this? We target this PR for Build release.
This only build failure is caused by the test machine issue:
Error message is:

> The command "sudo apt-get install -qq dotnet-sdk-2.1=2.1.400*" failed and exited with 100 during

**Comment by blueww** [comment]
@markcowl 
I see the build for powershell-core failed with following error, seems is a test machine issue. Would you please help to look?

> /.azure-pipelines/powershell-core.yml: Could not find /.azure-pipelines/util/analyze-steps.yml in repository self hosted on https://api.github.com using commit 3f9776c6862610fac08e9285b9147905437575c4. GitHub reported the error, "Not Found"

**Comment by markcowl** [comment]
@blueww Yes, it is queued, but may take a while to show up

**Comment by blueww** [comment]
@markcowl 
The build failed on powershell-core, which seems is test machine issue, would you please help to look?

> /.azure-pipelines/powershell-core.yml: Could not find /.azure-pipelines/util/analyze-steps.yml in repository self hosted on https://api.github.com using commit 3f9776c6862610fac08e9285b9147905437575c4. GitHub reported the error, "Not Found"

**Pull request merged**
