### PR TITLE
Dev: Azure Automation additional ARM cmdlets

### PR DESCRIPTION
**Pull request by safeermohammed**
Automation ARM cmdlets for mid July release, PR has following

New ARM cmdlets
Tests

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@safeermohammed__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (safeerm). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@azuresdkci retest this please

**Comment by safeermohammed** [comment]
Last build seems to have failed with infra issue. Took latest from Azure and started new build.

**Comment by safeermohammed** [comment]
build succeeded

**Pull request merged**
