### PR TITLE
Generated container-group-profile commands and added container group properties for reuse scenario

### PR DESCRIPTION
**Pull request by kaushik-ms**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by kaushik-ms** [comment]
\azp run

**Review by jrathore-msft — APPROVED** [review]

**Review by jrathore-msft — APPROVED** [review]

**Comment by vidai-msft** [comment]
@kaushik-ms Please fix the static analysis issue as detected in the CI.

**Comment by drishtipeshwani09** [comment]
### Az.ContainerInstance 4.0.3
* Added `ContainerGroupProfileId` `ContainerGroupProfileRevision` `StandbyPoolProfileFailContainerGroupCreateOnReuseFailure` `StandbyPoolProfileId` to Container Group properties. 
* Added `ConfigMapKeyValuePair` to Container object properties.
* Added new cmdlet to define container without using the preset default properties `New-AzContainerInstanceNoDefaultObject`
* Added new cmdlets for Container Group Profile - `Get-AzContainerInstanceContainerGroupProfile`, `New-AzContainerInstanceContainerGroupProfile`, `Remove-AzContainerInstanceContainerGroupProfile`, `Update-AzContainerInstanceContainerGroupProfile`, `Get-AzContainerInstanceContainerGroupProfileRevision`
* For Container Group properties, the default value for OsType is no longer preset to Linux and has to be explicitly specified.

**Review by vidai-msft — APPROVED** [review]
LGTM

**Pull request merged**
