### PR TITLE
Create Load Balancer cmdlets with generated code

### PR DESCRIPTION
**Pull request by khannarhea**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by praries880** [comment]
@khannarhea 

The LB tests will need to re re-recorded.

Failures: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/7478/artifact/src/Publish/TestResults/FailingTests/Microsoft.Azure.Commands.Network.Test.dll.html

https://travis-ci.org/Azure/azure-powershell/builds/427835583#L1660

**Comment by praries880** [comment]
Retrying Jenkins build because of randon test failure in service management

**Comment by praries880** [comment]
@khannarhea  kindly take care of merge conflicts

**Comment by khannarhea** [comment]
resolved merge conflicts

**Pull request merged**
