### PR TITLE
preview -> AzureRM.Storage.Location

### PR DESCRIPTION
**Pull request by vladimir-shcherbakov**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@blueww Can you take a look at this merge and see if the storage files look okay in the merge? If not, can you open a new PR to merge preview into Storage.Location? Thanks

**Comment by blueww** [comment]
@maddieclayton 
Since there are so many changes, it might not be possible for me to look at the 1200+ files.
It there any specific changes that I should take care?

If no specific change to the whole framework, and for storage, I think we can just take it in with build pass. And I will run regression on it later.

**Comment by vladimir-shcherbakov** [comment]
@blueww 
I think you just need to verify 
* src/Storage 
* src/ResourceManager/Storage

**Comment by blueww** [comment]
@vladimir-msft ， @maddieclayton 
Sorry for the late responds.
There are so many change in this storage module, as I see all my recent changes are included.

Since the build can pass. I would prefer we merge this PR, and we can fix if any issue found.
BTW, I will be OOF on 8/9-8/21. Will verify it after I am back.

The next release from this branch is planned on 8/29. As I discussed with MArk, it will be .net module. So we might don't need merge the change for 8/24 release to this branch.

**Pull request merged**
