### PR TITLE
Az.StackHCI May release

### PR DESCRIPTION
**Pull request by ritviknagpal48**
## Description
**********************Change log:**********************

1. Added support for Managed Service identity (MSI) in Azure China Cloud
2. Added support for Mandatory extensions, for OS versions starting 23H2
3. Added parameter validations for Register-AzStackHCI cmdlet
4. Improved Error logging in Registration and Unregistration
5. Minor bug fixes and improvements

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by bniranjanbhat — APPROVED** [review]

**Comment by msJinLei** [comment]
Breaking change issue

```
  D:\a\_work\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv Errors
  "Module","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.StackHCI","Get-AzStackHciExtension","Get-AzStackHciExtension","0","3000","The type of property 'ParameterProtectedSetting' of type 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.Api20220501.IExtension' has changed from 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny' to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IExtensionParametersProtectedSettings'.","Change the type of property 'ParameterProtectedSetting' back to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny'."
  "Az.StackHCI","Get-AzStackHciExtension","Get-AzStackHciExtension","0","3000","The type of property 'ParameterSetting' of type 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.Api20220501.IExtension' has changed from 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny' to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IExtensionParametersSettings'.","Change the type of property 'ParameterSetting' back to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny'."
  "Az.StackHCI","New-AzStackHciExtension","New-AzStackHciExtension","0","3000","The type of property 'ParameterProtectedSetting' of type 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.Api20220501.IExtension' has changed from 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny' to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IExtensionParametersProtectedSettings'.","Change the type of property 'ParameterProtectedSetting' back to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny'."
  "Az.StackHCI","New-AzStackHciExtension","New-AzStackHciExtension","0","3000","The type of property 'ParameterSetting' of type 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.Api20220501.IExtension' has changed from 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny' to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IExtensionParametersSettings'.","Change the type of property 'ParameterSetting' back to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny'."
  "Az.StackHCI","New-AzStackHciExtension","New-AzStackHciExtension","0","2020","The cmdlet 'New-AzStackHciExtension' no longer supports the type 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny' for parameter 'ExtensionParameterProtectedSetting'.","Change the type for parameter 'ExtensionParameterProtectedSetting' back to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny'."
  "Az.StackHCI","New-AzStackHciExtension","New-AzStackHciExtension","0","2020","The cmdlet 'New-AzStackHciExtension' no longer supports the type 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny' for parameter 'ExtensionParameterSetting'.","Change the type for parameter 'ExtensionParameterSetting' back to 'Microsoft.Azure.PowerShell.Cmdlets.StackHCI.Models.IAny'."
  "Az.StackHCI","Register-AzStackHCI","Register-AzStackHCI","0","2000","The cmdlet 'Register-AzStackHCI' no longer supports the parameter 'GraphAccessToken' and no alias was found for the original parameter name.","Add the parameter 'GraphAccessToken' back to the cmdlet 'Register-AzStackHCI', or add an alias to the original parameter name."
  "Az.StackHCI","Register-AzStackHCI","Register-AzStackHCI","0","2000","The cmdlet 'Register-AzStackHCI' no longer supports the parameter 'EnableAzureArcServer' and no alias was found for the original parameter name.","Add the parameter 'EnableAzureArcServer' back to the cmdlet 'Register-AzStackHCI', or add an alias to the original parameter name."
  "Az.StackHCI","Register-AzStackHCI","Register-AzStackHCI","0","1050","The parameter set '__AllParameterSets' for cmdlet 'Register-AzStackHCI' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'Register-AzStackHCI'."
  "Az.StackHCI","Set-AzStackHCI","Set-AzStackHCI","0","2000","The cmdlet 'Set-AzStackHCI' no longer supports the parameter 'GraphAccessToken' and no alias was found for the original parameter name.","Add the parameter 'GraphAccessToken' back to the cmdlet 'Set-AzStackHCI', or add an alias to the original parameter name."
  "Az.StackHCI","Set-AzStackHCI","Set-AzStackHCI","0","1050","The parameter set '__AllParameterSets' for cmdlet 'Set-AzStackHCI' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'Set-AzStackHCI'."
  "Az.StackHCI","Test-AzStackHCIConnection","Test-AzStackHCIConnection","0","1000","The cmdlet 'Test-AzStackHCIConnection' has been removed and no alias was found for the original cmdlet name.","Add the cmdlet 'Test-AzStackHCIConnection' back to the module, or add an alias to the original cmdlet name."
  "Az.StackHCI","Unregister-AzStackHCI","Unregister-AzStackHCI","0","2000","The cmdlet 'Unregister-AzStackHCI' no longer supports the parameter 'GraphAccessToken' and no alias was found for the original parameter name.","Add the parameter 'GraphAccessToken' back to the cmdlet 'Unregister-AzStackHCI', or add an alias to the original parameter name."
  "Az.StackHCI","Unregister-AzStackHCI","Unregister-AzStackHCI","0","1050","The parameter set '__AllParameterSets' for cmdlet 'Unregister-AzStackHCI' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'Unregister-AzStackHCI'."
```

**Comment by msJinLei** [comment]
We cannot release breaking change for the upcoming release if no notification before
```
All the pull requests contain [breaking changes](https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md) is going to break the pipeline. You are required to avoid breaking changes in regular releases. If you do want to release a breaking change, please follow the steps below.

Notify customers of Breaking Changes
Add the [breaking change notifications](https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-attribute-help.md) to the cmdlets that is about to breaking-changed in the main branch Please note breaking change notification should be released 2 sprints ahead of the breaking change itself is released.

Release the breaking changes
Breaking changes can only be release in major release, usually twice a year. Major releases are identified in the [Release Schedule](https://github.com/Azure/azure-powershell/milestones).

Please commit your breaking changes to main in the sprint of major release.

In the commit, you should

suppress the breaking change errors in "tools/StaticAnalysis/Exceptions/${ModuleName}/BreakingChangeIssues.csv"
"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
"Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzFirewallPolicyNatRuleCommand","New-AzFirewallPolicyNatRule","0","1050","The parameter set '__AllParameterSets' for cmdlet 'New-AzFirewallPolicyNatRule' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'New-AzFirewallPolicyNatRule'."

remove the unnecessary breaking change notifications
```

**Comment by isra-fel** [comment]
- The issues about `IAny` do not count as breaking changes, because they didn't work. Simply suppress them.
- `GraphAccessToken` was [announced to break](https://github.com/Azure/azure-powershell/blob/3072c26742fe30897accc78bbfa75ae946c7e140/src/StackHCI/custom/stackhci.ps1#L2429), so we can allow it. Suppress the related issues.
- `EnableAzureArcServer` was not preannounced. **Revert the breaking change.**
- Those related to `__AllParameterSets` are because of the removal of the parameters (the removed parameters are positional parameters) so they are fine. Suppress them.
- The one about `Test-AzStackHCIConnection` [was announced](https://github.com/Azure/azure-powershell/blob/3072c26742fe30897accc78bbfa75ae946c7e140/src/StackHCI/docs/Test-AzStackHCIConnection.md?plain=1#L13). Simply suppress it.

Besides all these, note that the official way to mark something as deprecated is to use [these attributes](https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/breakingchange-for-autogen-module.md#for-customized-cmdlets) instead of just `[Obselete]`.

**Comment by msJinLei** [comment]
Could you provide the migration guide of StackHCI for this major release? 

Please fill in the following table 
|cmdlet|breaking change|old usage|new usage| 
|-|-|-|-| 

Thanks

**Comment by ritviknagpal48** [comment]
</html>
</body>


<body>
<html>

Cmdlet | Breaking change | Old usage | New usage
-- | -- | -- | --
`Test-AzStackHCIConnection` | Removed `Test-AzStackHCIConnection` cmdlet from `Az.StackHCI` PowerShell module. Customers can use `Invoke-AzStackHciConnectivityValidation` from `AzStackHCI.EnvironmentChecker` module for enhanced connectivity verification tests | Customers used `Test-AzStackHCIConnection` for connectivity verification tests | Customers can use `Invoke-AzStackHciConnectivityValidation` from `AzStackHCI.EnvironmentChecker` module for enhanced connectivity verification tests
`Register-AzStackHCI` | Removed `GraphAccessToken` and `EnableAzureArcServer` parameters from `Register-AzStackHCI` | Customers had an option to pass `GraphAccessToken`  parameter in `Register-AzStackHCI`, which used to be ignored by the cmdlet. Customers had an option to pass `EnableAzureArcServer` as true or false. `Register-AzStackHCI` used to fail for customers who passed `EnableAzureArcServer` as false. | `Register-AzStackHCI` won’t support `GraphAccessToken` and `EnableAzureArcServer` as parameters
`Unregister-AzStackHCI` | Removed `GraphAccessToken` from `Unregister-AzStackHCI` | Customers had an option to pass `GraphAccessToken`  parameter in `Unregister-AzStackHCI`, which used to be ignored by the cmdlet | `Unregister-AzStackHCI ` won’t support `GraphAccessToken` as a parameter
`Set-AzStackHCI` | Removed `GraphAccessToken` from `Set-AzStackHCI` | Customers had an option to pass `GraphAccessToken`  parameter in `Set-AzStackHCI`, which used to be ignored by the cmdlet | `Set-AzStackHCI` won’t support `GraphAccessToken` as a parameter

**Review by msJinLei — APPROVED** [review]

**Comment by ritviknagpal48** [comment]
PFB the updated change log. Ignore the change log in the PR description.

Change log:

1. Made `Region` parameter mandatory in `Register-AzStackHCI` cmdlet.
2. Removed `EnableAzureArcServer` parameter from `Register-AzStackHCI` cmdlet.
3. Removed `Test-AzStackHCIConnection` cmdlet. Customers can use `Invoke-AzStackHciConnectivityValidation` from `AzStackHCI.EnvironmentChecker` module for enhanced connectivity verification tests.
4. Added support for Managed Service identity (MSI) in Azure China Cloud.
5. Added support for Mandatory extensions, for OS versions starting 23H2.
6. Added parameter validations for `Register-AzStackHCI` cmdlet.
7. Improved Error logging in Registration and Unregistration.
8. Minor bug fixes and improvements.

**Pull request merged**
