### PR TITLE
New parameters in New-AzureVMSqlServerAutoBackupConfig cmdlet to support Auto Backup for SQL Server 2016 VMs (Classic cmdlet changes)

### PR DESCRIPTION
**Pull request by anilkyelam**
## Description

- Added new parameters for New-AzureVMSqlServerAutoBackupConfig that reflect changes for Auto Backup V2 for SQL IaaS Extension.
- Fixed bug in Get-AzureVMSqlServerExtension to correctly get values of parameters by parsing the SQL Configuration substatus (the correct one) in the response.

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [x] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
  **[anilyela]** In this change though, the existing xml help file was generated using PS Cmdlet help editor. I've regenerated the whole file using platyPSHelp.
- [x] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.
- [x] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [N/A] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [N/A] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThrough` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [x] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [x] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [x] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by cormacpayne** [comment]
@anilyela Hey Anil, would you mind adding test coverage for these newly added parameters?

**Comment by anilyela** [comment]
@cormacpayne Hi Cormac, will do that. The existing tests for our extension cmdlets ([AzureVMSqlServerExtensionTests.cs](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement.Test/FunctionalTests/ExtensionTests/AzureVMSqlServerExtensionTests.cs)) are very old and were added under functional tests (not scenario tests) and I don't understand how they work, as in, how they are recorded for playbacks. It looks like these kind of tests are not added anymore, am I right? I'm planning to add new set of (scenario) tests for our extension in [Commands.ScenarioTest](https://github.com/Azure/azure-powershell/tree/dev/src/ServiceManagement/Common/Commands.ScenarioTest) project, like [DscExtensionTests.cs](https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Common/Commands.ScenarioTest/DscExtension/DscExtensionTests.cs). Does this sound okay?

**Comment by cormacpayne** [comment]
@anilyela I don't believe those types of tests are added anymore. The model that you have for DscExtensionTests.cs should be fine for the new tests.

**Comment by anilyela** [comment]
Thanks @cormacpayne , added tests.

**Comment by cormacpayne** [comment]
@anilyela LGTM once we get the appropriate sign-offs

**Comment by anilyela** [comment]
@cormacpayne got the signoff needed.

**Pull request merged**
