### PR TITLE
Delete template commands from Resources project

### PR DESCRIPTION
**Pull request by chidmdxx**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by vivsriaus** [comment]
@chidmdxx Can we also make sure the help contents for this cmdlet, if any, are removed from the xml file?

**Comment by chidmdxx** [comment]
deleted all the references in the help xml files to these two cmdlets

**Comment by ogail** [comment]
@chidmdxx thanks for the contribution! In order to take this change please:
- Pull from the dev branch and resolve conflicts
- Follow the contribution guidelines, specifically sign [CLA doc](http://azure.github.io/guidelines.html#cla)

**Pull request closed without merging**
