### PR TITLE
Az Databricks uses more intuitive parameter names for the ESC feature

### PR DESCRIPTION
**Pull request by windoze**
## Description

Az Databricks uses more intuitive parameter names for the ESC feature, the new names match the text on Azure Portal UI.
The original names are kept as aliases to maintain the backward compatibility.

| Original Name | New Name |
| ---------------- | ---------------- |
| EnhancedSecurityMonitoringValue | EnhancedSecurityMonitoring |
| AutomaticClusterUpdateValue | AutomaticClusterUpdate |
| ComplianceSecurityProfileValue | EnhancedSecurityCompliance |
| ComplianceSecurityProfileComplianceStandard | ComplianceStandard |

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [X] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by VeryEarly** [comment]
changing parameter names are breaking changes, which are not allowed outside of breaking change window. please reschedule this work around next build event

**Comment by VeryEarly** [comment]
.

**Comment by windoze** [comment]
> changing parameter names are breaking changes, which are not allowed outside of breaking change window. please reschedule this work around next build event

Hi, @VeryEarly,
Thanks for your comments.
I kept the original parameter names as the aliases, so this is not a breaking change.

**Comment by VeryEarly** [comment]
close this use #26823 instead.

**Pull request closed without merging**
