### PR TITLE
Admin Export Template Image: Add Ops, TA Cmdlet and security check for exporting template image out of ARA

### PR DESCRIPTION
**Pull request by arcadiahlyy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arcadiahlyy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hele). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by azurecla** [comment]
Hi __@arcadiahlyy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hele). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by cormacpayne** [comment]
LGTM

**Comment by cormacpayne** [comment]
On-demand: **waiting**

**Comment by cormacpayne** [comment]
@arcadiahlyy Hey Lei, would you mind pulling from dev to get the latest changes that fix the on-demand build?

**Comment by cormacpayne** [comment]
On-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1209

**Comment by markcowl** [comment]
@arcadiahlyy Please fix the shouldprocess implementation.  If you cna do this early this morning, we may be able to take the change for this release, otherwise this will not be possible.

**Comment by cormacpayne** [comment]
On-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1224/

**Comment by cormacpayne** [comment]
On-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1227/

**Comment by markcowl** [comment]
LGTM once the build passes

**Pull request merged**
