### PR TITLE
New-AzVm and New-AzVmConfig licenseType description edits

### PR DESCRIPTION
**Pull request by Sandido**
Work for https://msazure.visualstudio.com/One/_workitems/edit/8323663. 
The AzVM documentation in PS had similar incorrect text stating the LicenseType cannot be updated, when in fact it can be. 
The VMSS documentation had no mention of LicenseType and so is not included here. 
I improved the New-AzVmConfig LicenseType description while I was in the area. 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by grizzlytheodore — APPROVED** [review]
lgtm

**Comment by isra-fel** [comment]
LGTM too. @Sandido let me know when it's ready to merge please

**Comment by Sandido** [comment]
Ready to merge.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
