### PR TITLE
New-AzApplicationGatewayPathRuleConfig: Fix path-based rewrite rules

### PR DESCRIPTION
**Pull request by cbuchanan**
## Description

New-AzApplicationGatewayPathRuleConfig: Validate rewrite rule set is referenced in pathruleconfig. Do this by setting the rewrite rules in executecmdlet and newobject in Microsoft.Azure.Commands.Network.AzureApplicationGatewayPathRuleConfigBase.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@cbuchanan Can you join the Azure org? http://aka.ms/azuregithub
I don't know who you are, so I cannot run this PR until then.

**Comment by cbuchanan** [comment]
@MiYanni I would love to but I'm not sure how I can. It looks like it doesn't want to accept my gmail.com address as a valid email address at all (I thought Azure / Gmail B2B worked out of the box) and I used an alternative olde tyme live.com address but it would need to be added to the tenant as an external user. 

Really, I'm just a guy who had a problem with the path based rewrite rules and needed to fix the problem to proceed with my work. I figured I'd submit the PR rather than open a bug and make someone else do it because I had already solved the problem (and it seemed silly to make someone else duplicate the effort).

**Comment by cbuchanan** [comment]
@MiYanni thank you for running the build, but it looks like it failed for some unknown (to me) reason. I tried looking at the test artifacts, but I have the same problem because I don't have permission to look at them. So I guess the question is how do I join the azure tenant so I can retrieve the test results? The tests ran successfully for me on my system (and I even took a TDD approach and saw the tests fail before I updated the test suite), so now I really want to track down the problem on principle.

**Comment by MiYanni** [comment]
@akshaysngupta Please review these changes when you have the chance.

**Comment by number213** [comment]
Can you please re-target to `network-april`? That's a branch for next Az.Network release

**Comment by MiYanni** [comment]
@number213 I need to update `network-april` with latest from master before changing the base for this one.

**Pull request merged**
