### PR TITLE
Fixes Set-AzKeyVaultSecret to allow objects as Tags (Issue #8494)

### PR DESCRIPTION
**Pull request by lwajswaj**
Fixes issue #8494 by forcing all values in Tags hashtable to be strings.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by lwajswaj** [comment]
Attempted to use methods exposed at "TagsHelper" but they didn't adjust properly as they are receiving Dictionary<string, string> to get a HashTable OR a hashtable to return a Dictionary<string,string>. Made more sense to just create a new extension method.

**Comment by maddieclayton** [comment]
@lwajswaj I think what makes the most sense here is to convert the Hashtable to a Dictionary<string, string> using https://github.com/Azure/azure-powershell-common/blob/84adc2e8e833a22caa8ea714cd5c367e63da227c/src/ResourceManager/Version2016_09_01/Tags/TagsConversionHelper.cs#L47, then convert that dictionary back to a Hashtable using https://github.com/Azure/azure-powershell-common/blob/84adc2e8e833a22caa8ea714cd5c367e63da227c/src/ResourceManager/Version2016_09_01/Tags/TagsConversionHelper.cs#L82.  This should do exactly what your code is doing, and will guarantee that KeyVault works the exact same as other cmdlets in our repo that convert between Hashtable and Dictionary<string, string>.  I believe that this cmdlet fails where others do not because most services accept the Dictionary<string, string> rather than a Hashtable, so we are doing the CreateTagDictionary call which casts all tag keys and values to strings for all other cmdlet calls.

**Comment by lwajswaj** [comment]
@maddieclayton, the problem with using that approach is the actual exception is being thrown by these lines:

```c#
if (tag.Value != null && !(tag.Value is string))
                    throw new ArgumentException("Tag has invalid value");
```

In TagHelper.ConvertToDictionary. Should we remove that check and replace the following line with a ToString() instead of casting it?

```c#
string value = (tag.Value == null) ? string.Empty : tag.Value.ToString();
```

thoughts? That's why I chose create that extra extension, it seemed cleaner

**Comment by lwajswaj** [comment]
so, ConvertToDictionary would look like this:

```c#
public static Dictionary<string, string> ConvertToDictionary(this Hashtable tags)
        {
            Dictionary<string, string> tagsDictionary = new Dictionary<string, string>();
            foreach (DictionaryEntry tag in tags)
            {
                string key = tag.Key as string;
                if (string.IsNullOrWhiteSpace(key))
                    throw new ArgumentException("Invalid tag name");

                string value = (tag.Value == null) ? string.Empty : tag.Value.ToString();
                tagsDictionary[key] = value;
            }

            return tagsDictionary;
        }
```

**Comment by lwajswaj** [comment]
Hey @maddieclayton, sorry for the coming and going.... I think updating "ConvertToDictionary" with the logic I just pushed (it's basically based on your recommendation) it's better as I see it's referenced 16 different times and each one of them is a possible issue if the passed hashtable doesn't contain all strings. In this way, we prevent other issues to occur.

**Comment by maddieclayton** [comment]
In my opinion, rather than fixing the KeyVault specific implementation, we should change the cmdlet to use the general implementation: https://github.com/Azure/azure-powershell-common/blob/84adc2e8e833a22caa8ea714cd5c367e63da227c/src/ResourceManager/Version2016_09_01/Tags/TagsConversionHelper.cs. I believe this already does what you are fixing in the KeyVault implementation.

If this is too much work, I can take over the PR - just let me know

**Comment by lwajswaj** [comment]
yeap, you are right. For this cmdlet to use general implementation, it's an easy fix. Just pushed the updates to do so

**Comment by maddieclayton** [comment]
Just to make this a little more simple I edited the change down to just the error handling of the Tag hashtable - should be good to go once CI passes!

**Comment by maddieclayton** [comment]
@lwajswaj Thanks for the contribution!!

**Pull request merged**
