### PR TITLE
Rely on "ReferenceName" property  to get fully qualified extension name; Status Message's name changes from "Automatic to Automated"

### PR DESCRIPTION
**Pull request by sethusrinivasan**
Issues:
1) Azure RDFE service model now reports "ReferenceName" property as fully qualified extension name "Microsoft.SqlServer.Management.SqlIaaSAgent"
2) Status message's name was updated from "Automatic to Automated. 

Fixes:
1) remove code that was concatenating publisher and extension name and just rely on "ReferenceName" when we look for Extension Status in powershell cmdlet
2) fix up constants AutoPatchingStatusMessageName & AutoBackupStatusMessageName ( rename Automatic to Automated )

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sethusrinivasan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (seths). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by AzureRT** [comment]
Can one of the admins verify this patch?

**Comment by azurecla** [comment]
Hi __@sethusrinivasan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (seths). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by AzureRT** [comment]
Can one of the admins verify this patch?

**Comment by hovsepm** [comment]
Are you still working on this PR or you need CR and merge?

**Pull request merged**
