### PR TITLE
[Azure Backup] [Breaking Change Release] Replaced BackupManagementType MARS with MAB, added SAPHana workload support for few cmdlets

### PR DESCRIPTION
**Pull request by hiaga**
## Description

1) Replaced MARS backupManagementType with MAB

2) Added support for SAPHANA workload with `Disable-AzRecoveryServicesBackupProtection`, `Unregister-AzRecoveryServicesBackupContainer`, `Get-AzRecoveryServicesBackupItem`, `Get-AzRecoveryServicesBackupContainer` cmdlets.

3) updated MSI based restore flow for TargetStorageAccount

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by hiaga** [comment]
@isra-fel: Please review this PR

**Review by isra-fel — APPROVED** [review]
Looks good. @hiaga Hi, as this is the major release of Az we are going to write a migration guide for customers. Could you fill in a table like this about the breaking changes in RecoveryServices module? Thanks

|cmdlet|breaking change|old usage|new usage|
|-|-|-|-|

**Comment by hiaga** [comment]
<html xmlns:o="urn:schemas-microsoft-com:office:office"
xmlns:dt="uuid:C2F41010-65B3-11d1-A29F-00AA00C14882"
xmlns="http://www.w3.org/TR/REC-html40">

<head>

<meta name=ProgId content=OneNote.File>
<meta name=Generator content="Microsoft OneNote 15">
</head>

<body lang=en-US style='font-family:Calibri;font-size:11.0pt'>


<div style='direction:ltr'>



cmdlet | breaking   change | old   usage | new   usage
-- | -- | -- | --
Get-AzRecoveryServicesBackupContainer | Changed   the BackupManagementType from MARS to MAB. Functionality remains same, this   is to bring consistency across cmdlets | $containers   = Get-AzRecoveryServicesBackupContainer -ContainerType Windows   -BackupManagementType MARS -VaultId   $vault.ID | $cont   = Get-AzRecoveryServicesBackupContainer -ContainerType Windows   -BackupManagementType MAB -VaultId   $vault.ID
Get-AzRecoveryServicesBackupItem | Changed   the BackupManagementType from MARS to MAB. Functionality remains same, this   is to bring consistency across cmdlets | Get-AzRecoveryServicesBackupItem   -BackupManagementType MARS -VaultId $vault.ID -WorkloadType FileFolder | Get-AzRecoveryServicesBackupItem   -BackupManagementType MAB -VaultId $vault.ID -WorkloadType FileFolder
Get-AzRecoveryServicesBackupJob | Changed   the BackupManagementType from MARS to MAB. Functionality remains same, this   is to bring consistency across cmdlets | Get-AzRecoveryServicesBackupJob   -BackupManagementType MARS -VaultId   $vault.ID | Get-AzRecoveryServicesBackupJob   -BackupManagementType MAB -VaultId   $vault.ID



</div>


</body>

</html>

**Comment by hiaga** [comment]
> Looks good. @hiaga Hi, as this is the major release of Az we are going to write a migration guide for customers. Could you fill in a table like this about the breaking changes in RecoveryServices module? Thanks
> 
> cmdlet	breaking change	old usage	new usage

@isra-fel : added above.

**Comment by isra-fel** [comment]
Thanks!

**Pull request merged**
