### PR TITLE
[ARM] New cmdlets for DataBoundaries

### PR DESCRIPTION
**Pull request by skadhiresan**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by skadhiresan** [comment]
I have followed the Development with CodeGen guide and made this draft pr. DataBoundary is under Microsoft.Resources. I understand we are to use the generation branch to generate the cmdlets, so I created a DataBoundary.Autorest folder under Resources, but looking at the precedent for deployment stacks: (https://github.com/Azure/azure-powershell/pull/22019)
, looks like we need to be under Az.Resources but generating the cmdlets in the generation branch under DataBoundary.Autorest leaved the cmdlets to be a part of a new Az.DataBoundary module instead of Az.Resources. Could you help out here with the generated cmdlets to be structured under Microsoft.Resources?

**Comment by skadhiresan** [comment]
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1462 review was accepted

**Review by Nickcandy — APPROVED** [review]

**Comment by isra-fel** [comment]
Force merging because of known issue in ux metadata analyzer

**Pull request merged**
