### PR TITLE
Fixed typos in Resources.resx

### PR DESCRIPTION
**Pull request by petrsvihlik**
fixed typos experienced when trying to resolve http://stackoverflow.com/questions/30123326/cant-get-move-azureresource-working

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@petrsvihlik__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@petrsvihlik Thanks for your contribution! Could u send it to the dev branch?

**Comment by petrsvihlik** [comment]
@ogail I've directly committed the change to the dev

**Comment by ogail** [comment]
@petrsvihlik what is the PR link?

**Comment by markcowl** [comment]
@azuresdkci test this please

**Pull request merged**
