### PR TITLE
Get-AzResourceGroup - fixed issue with not throwing error when wildcard is not found

### LINKED ISSUE #15612: Get-AzResourceGroup returns false positive
## Description
When using unconventional names for the resource group value (URLs), the cmdlet doesn't return anything as result.

## Steps to reproduce
Resource group RG1 exists.
Resource group RG2 does not exists.

```powershell
Get-AzResourceGroup -Name "RG1"
```
Returns the details of the resource group.
```powershell
`Get-AzResourceGroup -Name "RG2"`
```
Fails and says the provided resource group does not exist.
```powershell
`Get-AzResourceGroup -Name "https://RG1?default"`
```
Doesn't return anything, but it also doesn't fail.
In an automation we have, we are validating the resource group name and you can imagine this leads to false positive results (when the cmdlet doesn't fail).
Also, logically, this doesn't have any sense. It should either return the results of the resource group details or fail. How can it be that it has a 3rd option?

## Environment data

```
Name                           Value                                                            
----                           -----                                                            
PSVersion                      5.1.19041.1151                                                   
PSEdition                      Desktop                                                          
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}                                          
BuildVersion                   10.0.19041.1151                                                  
CLRVersion                     4.0.30319.42000                                                  
WSManStackVersion              3.0                                                              
PSRemotingProtocolVersion      2.3                                                              
SerializationVersion           1.1.0.1  
```

## Module versions

```powershell
ModuleType Version    Name                                ExportedCommands                      
---------- -------    ----                                ----------------                      
Script     2.5.2      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext...
Script     4.3.0      Az.Resources                        {Add-AzADGroupMember, Export-AzReso...
Script     0.0        cdsa.azure                          {Add-cdsaAzureNetworkSecurityGroupR...
Script     0.0        cdsa.devops                         {Copy-cdsaAzureDevOpsBaseAppModifie...
Script     1.0.0.0    ISE                                 {Get-IseSnippet, Import-IseSnippet,...
Manifest   3.1.0.0    Microsoft.PowerShell.Management     {Add-Computer, Add-Content, Checkpo...
Manifest   3.0.0.0    Microsoft.PowerShell.Security       {ConvertFrom-SecureString, ConvertT...
Manifest   3.1.0.0    Microsoft.PowerShell.Utility        {Add-Member, Add-Type, Clear-Variab...
Manifest   3.0.0.0    Microsoft.WSMan.Management          {Connect-WSMan, Disable-WSManCredSS...
```

## Debug output

```

```

## Error output

```

```

### PR DESCRIPTION
**Pull request by ArmaanMcleod**
## Description

Fixes #15612.

Added condition to make sure wildcard resource groups throw error when none are found using `Get-AzResourceGroup -Name`.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by isra-fel** [comment]
Thanks for contributing 😀 We'll review it soon.
cc @navba-MSFT would you also be able to reivew this fix to `Get-AzResourceGroup` cmdlet?

**Comment by navba-MSFT** [comment]
> Thanks for contributing 😀 We'll review it soon. cc @navba-MSFT would you also be able to review this fix to `Get-AzResourceGroup` cmdlet?

Adding @jennyhunter-msft and @josephkwchan to review this PR

**Comment by ArmaanMcleod** [comment]
@navba-MSFT Looks like no review has happened for a while, what is the next step?

**Comment by navba-MSFT** [comment]
@jennyhunter-msft and @josephkwchan This PR is open for quite sometime. Could you please loop in the right folks who can review this PR ?

**Pull request closed without merging**
