### PR TITLE
Added new properties NetworkIdentifier and ServiceEndpointConfig in Vnet/Subnet config for setting SNAT/VIP.

### PR DESCRIPTION
**Pull request by bhupeshbhatt1985**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by NoriZC** [comment]
@bhupeshbhatt1985 Could you please add a test case for added parameter?

**Comment by bhupeshbhatt1985** [comment]
> @bhupeshbhatt1985 Could you please add a test case for added parameter?

Added, but the test will fail until SDK updated to 2024-01-01 api version. https://github.com/Azure/azure-powershell/pull/25317 this PR I raised with SDK update and there we have Az.Network passing

**Comment by NoriZC** [comment]
Hi @bhupeshbhatt1985,
 
@abhi7860 is also updating the SDK version in this pr: https://github.com/Azure/azure-powershell/pull/25096

And seems he met with some problem while doing this. We should discuss in which PR to do this.

**Comment by bhupeshbhatt1985** [comment]
> Hi @bhupeshbhatt1985,
> 
> @abhi7860 is also updating the SDK version in this pr: #25096
> 
> And seems he met with some problem while doing this. We should discuss in which PR to do this.

Let me check the PR and connect with NRP team for the correct SDK update.

**Comment by htippanaboya** [comment]
@bhupeshbhatt1985- is this for the current release. We are way past the code freeze date. Please merge it asap

**Comment by bhupeshbhatt1985** [comment]
> @bhupeshbhatt1985- is this for the current release. We are way past the code freeze date. Please merge it asap

Sure, merged code with updated SDK . @NoriZC please review the PR.

**Review by NoriZC — APPROVED** [review]

**Pull request merged**
