### PR TITLE
New cmdlets to create/enter  PSSession in remote container app. New cmdlet for getting container continuous deployment url

### PR DESCRIPTION
**Pull request by exc3eed**
## Description

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/145

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
This looks like it is based on https://github.com/Azure/azure-powershell/pull/7191. Meaning, they have the same history up to a point and then there are additions for the PR. I'll wait until that PR is merged to review this PR appropriately. Most of the file changes currently aren't related to the intent of this PR.

**Comment by MiYanni** [comment]
@panchagnula @Nking92 I believe @exc3eed is OOF. Do you have details on if this was supposed to be part of a preview release for Ignite?

**Comment by panchagnula** [comment]
@jvano can you are someone from you team unblock this PR? thank you.

**Comment by vinisoto** [comment]
@panchagnula @MiYanni @jvano I'm going to look into this. Since I cannot update Ashraf's fork, please expect a new PR from me.

**Pull request closed without merging**
