### PR TITLE
Align IoT hub parameter docs with reality

### PR DESCRIPTION
**Pull request by tomkerkhove**
Signed-off-by: Tom Kerkhove <kerkhove.tom@gmail.com>

## Description

Align command line docs with reality, similar to how it's being tested ([code](https://github.com/Azure/azure-powershell/blob/master/src/DeviceProvisioningServices/DeviceProvisioningServices.Test/ScenarioTests/IotDpsEnrollmentGroupTests.ps1#L93))

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by tomkerkhove** [comment]
I tried updating the docs (based on [guidance](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)) but the parameter info was not updated.

**Comment by VeryEarly** [comment]
> I tried updating the docs (based on [guidance](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)) but the parameter info was not updated - Any guidance?

Hi @tomkerkhove ,
Did you try building Azure-PowerShell in your branch and import Az.DeviceProvisioningServices?

**Comment by tomkerkhove** [comment]
Yes, but when importing it cannot find the DLL while I just followed the guide and everything was fine.

I must be missing something obvious.

**Comment by VeryEarly** [comment]
> Yes, but when importing it cannot find the DLL while I just followed the guide and everything was fine.
> 
> I must be missing something obvious.

Can you please provide some detail of the error so I can take a look?

**Comment by VeryEarly** [comment]
close this PR now, you can reopen it if needed or you have any further questions.

**Pull request closed without merging**
