### PR TITLE
Update api-version

### PR DESCRIPTION
**Pull request by antoniowmsft**
## Description

Update api-version in playback files

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by matthchr** [comment]
This looks good to me. @cormacpayne - are the failing tests disabled? Is it possible we can re-enable them for this PR to make sure they are passing after these changes in CI?

**Comment by cormacpayne** [comment]
@antoniowmsft @matthchr the tests are currently disabled in the `release-6.1.0` branch, which we plan on merging into the `preview` branch tomorrow, but you can still verify the fix in this PR.

Here's the on-demand job for this PR: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/858/

**Comment by matthchr** [comment]
Hmm, it looks like the on-demand job still failed:
```
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.TaskTests.TestTerminateTask [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.TaskTests.TestListAllSubtasks [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.TaskTests.TestTaskCRUD [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.TaskTests.TestCreateTaskCollection [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Pools.cs(217): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.PoolTests.TestResizeAndStopResizePool [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\AzurePowershell.Test.targets(89,3): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.PoolTests.TestPoolCRUD [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Pools.cs(217): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.PoolTests.TestAutoScaleActions [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Pools.cs(217): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.PoolTests.TestChangeOSVersion [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.FileTests.TestGetRemoteDesktopProtocolFile [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.FileTests.TestDeleteNodeFileByTask [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.FileTests.TestGetNodeFileContentByComputeNode [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.FileTests.TestDeleteNodeFileByComputeNode [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.FileTests.TestGetNodeFileContentByTask [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\AzurePowershell.Test.targets(89,3): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchApplicationPackageTests.TestCreatePoolWithApplicationPackage [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Pools.cs(217): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchApplicationPackageTests.TestUpdatePoolWithApplicationPackage [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\AzurePowershell.Test.targets(89,3): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.JobTests.TestJobCRUD [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.JobTests.TestDisableEnableTerminateJob [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.JobTests.IfJobSetsAutoFailure_ItCompletesWhenAnyTaskFails [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\AzurePowershell.Test.targets(89,3): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.CertificateTests.TestCertificateCrudOperations [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Pools.cs(217): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.CertificateTests.TestCancelCertificateDelete [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.JobSchedules.cs(145): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.JobScheduleTests.TestDisableEnableTerminateJobSchedule [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\AzurePowershell.Test.targets(89,3): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.JobScheduleTests.TestJobScheduleCRUD [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeUserTests.TestComputeNodeUserEndToEnd [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeTests.TestDisableAndEnableComputeNodeScheduling [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Pools.cs(217): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeTests.TestRemoveComputeNodes [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeTests.TestGetComputeNodeRemoteLoginSettings [FAIL] [D:\PowerShell-demand\build.proj]
  D:\PowerShell-demand\src\ResourceManager\AzureBatch\Commands.Batch\Models\PSPagedEnumerable.cs(124): error : Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeTests.TestRebootAndReimageComputeNode [FAIL] [D:\PowerShell-demand\build.proj]
```

The error was:
```
        System.Collections.Generic.KeyNotFoundException : Unable to find a matching HTTP request for URL 'DELETE /jobs/listSubtaskJob?api-version=2018-03-01.6.1'. Calling method Item().
        Stack Trace:
             at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
             at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
             at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
             at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
             at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
             at Microsoft.Azure.Batch.Protocol.JobOperations.<DeleteWithHttpMessagesAsync>d__6.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestWithCancellationAsync>d__42.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at Microsoft.Azure.Batch.Protocol.BatchRequestBase`2.<ExecuteRequestAsync>d__40.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at Microsoft.Azure.Batch.ProtocolLayer.<ProcessAndExecuteBatchRequest>d__87`1.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at Microsoft.Azure.Batch.JobOperations.<DeleteJobAsync>d__22.MoveNext()
          --- End of stack trace from previous location where exception was thrown ---
             at System.Runtime.ExceptionServices.ExceptionDispatchInfo.Throw()
             at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
             at Microsoft.Azure.Batch.UtilitiesInternal.WaitAndUnaggregateException(Task task, IEnumerable`1 rootBehaviors, IEnumerable`1 additionalBehaviors)
             at Microsoft.Azure.Batch.JobOperations.DeleteJob(String jobId, IEnumerable`1 additionalBehaviors)
          src\ResourceManager\AzureBatch\Commands.Batch\Models\BatchClient.Jobs.cs(203,0): at Microsoft.Azure.Commands.Batch.Models.BatchClient.DeleteJob(BatchAccountContext context, String jobId, IEnumerable`1 additionBehaviors)
          src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\ScenarioTestHelpers.cs(470,0): at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ScenarioTestHelpers.DeleteJob(BatchController controller, BatchAccountContext context, String jobId)
          src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\TaskTests.cs(120,0): at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.TaskTests.<>c__DisplayClass4_0.<TestListAllSubtasks>b__2()
          src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\BatchController.cs(138,0): at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.BatchController.RunPsTestWorkflow(Func`1 scriptBuilder, Action initialize, Action cleanup, String callingClassType, String mockName)
          src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\TaskTests.cs(108,0): at Microsoft.Azure.Commands.Batch.Test.ScenarioTests.TaskTests.TestListAllSubtasks()
```

I do see this field in the recording files, it may be that we have to actually fully re-record the tests due to it: `EncodedRequestUri`

**Comment by maddieclayton** [comment]
@antoniowmsft assigning back to you to address test failures.

**Comment by maddieclayton** [comment]
on demand job here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/884/

**Comment by maddieclayton** [comment]
@antoniowmsft Ping on the failing tests above - are you having issues rerecording these tests?

**Comment by matthchr** [comment]
We can close this PR, I've rebased this PRs contents onto `preview` and updated to fix the remaining tests (I think), in this PR here: #6405

**Pull request closed without merging**
