### PR TITLE
Bring PowerShell in parity with API for LockLevel

### PR DESCRIPTION
**Pull request by gandhiniraj**
https://github.com/Azure/azure-powershell/issues/384

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gandhiniraj__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by vivsriaus** [comment]
@gandhiniraj Please update help accordingly.

**Comment by TianoMS** [comment]
Looks good to me.

**Comment by ravbhatnagar** [comment]
At some places help needs to be updated as mentioned below -
New-AzureRMResourceLock – 
Description needs to be updated
Remove-AzureRmResourceLock – 
	LockName param missing from syntax and other places
	TenantLevel param shouldn’t be marked as mandatory

**Comment by gandhiniraj** [comment]
@vivsriaus @ravbhatnagar I have updated the help related to this change

**Comment by gandhiniraj** [comment]
Also, fixed a typo in the help

**Comment by ravbhatnagar** [comment]
Looks good.

**Pull request merged**
