### PR TITLE
[CosmosDB] Exposing backup policy migration state

### PR DESCRIPTION
**Pull request by kavskalyan**
## Description
Exposing BackupPolicyMigrationState as a part of Get-AzCosmosDBAccount response. 
This shows the status of a backup policy migration state when an account is being converted from peroidic backup mode to continuous.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — CHANGES_REQUESTED** [review]
Please verify the state in the test in your test case

**Comment by amisi01** [comment]
> Please verify the state in the test in your test case

Hi Jin, this state will be only visible to user during the time of migration and not visible before and after that which makes it harder to add test for it. We have manually validated the state.

**Comment by amisi01** [comment]
> Please verify the state in the test in your test case

Added test for it

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
