### PR TITLE
[Az.RecoveryServices.Backup] Archive preview release 

### PR DESCRIPTION
**Pull request by hiaga**
## Description

Archive public preview release targeted 08th March, 21. This PR is to be merged to preview branch Az.RecoveryServices-preview

## Checklist

- [Yes] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [Yes] The title of the PR is clear and informative
- [Yes] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [Yes] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [N/A] If applicable, the changes made in the PR have proper test coverage
- [Yes] For public API changes to cmdlets:
    - [Yes] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/818
    - [Yes] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Please fix the analysis issue and test issues?

**Comment by hiaga** [comment]
Hi @wyunchi-ms, re-recording the tests and fixing the PR issues.

**Comment by hiaga** [comment]
@wyunchi-ms can you pls check if something is wrong with pipeline. Build is passing in my local machine and was passing in my previous run.

**Comment by isra-fel** [comment]
Looks like SSL issue of myget
```log
C:\Program Files\dotnet\sdk\5.0.103\NuGet.targets(131,5): error : Unable to load the service index for source https://dotnet.myget.org/F/dotnet-core/api/v3/index.json. [D:\a\1\s\tools\StaticAnalysis\StaticAnalysis.Netcore.csproj] [D:\a\1\s\build.proj]
C:\Program Files\dotnet\sdk\5.0.103\NuGet.targets(131,5): error : The SSL connection could not be established, see inner exception. [D:\a\1\s\tools\StaticAnalysis\StaticAnalysis.Netcore.csproj] [D:\a\1\s\build.proj]
C:\Program Files\dotnet\sdk\5.0.103\NuGet.targets(131,5): error : The remote certificate is invalid according to the validation procedure: RemoteCertificateNameMismatch [D:\a\1\s\tools\StaticAnalysis\StaticAnalysis.Netcore.csproj] [D:\a\1\s\build.proj]
```

**Comment by hiaga** [comment]
@isra-fel : created another PR for sync preview branch: https://github.com/Azure/azure-powershell/pull/14462. Pls review

**Comment by hiaga** [comment]
rebasing with https://github.com/Azure/azure-powershell/pull/14462 to sync with master

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
