### PR TITLE
{Iot Hub} Add custom nuget package

### PR DESCRIPTION
**Pull request by anusapan**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @anusapan , tools/LocalFeed/Microsoft.Azure.Devices.Shared.1.20.1.1.nupkg is not need in this PR, please remove it. And why these two sdk is needed? To fix bug?

**Comment by anusapan** [comment]
@wyunchi-ms 
To enable some feature that is available in the latest nupkg of "Microsoft.Azure.Devices" but it is using Newtonsoft v12+ and in PowerShell, the allowed max version of NewtownSoft is 10.0.3. So to resolve this, I have created a local nupkg of "Microsoft.Azure.Devices" and its dependent SDK ("Microsoft.Azure.Devices") with allowable serializer version.

**Comment by wyunchi-ms** [comment]
https://api.nuget.org/v3-flatcontainer/microsoft.azure.management.datafactories/4.13.3/microsoft.azure.management.datafactories.4.13.3.nupkg is not found now.

**Pull request merged**
