### PR TITLE
Added important note: id field for pagination

### PR DESCRIPTION
**Pull request by awsles**
## Description

Added an important detail for paginatin to work properly with the Search-AzGraph cmdlet, namely, that the **id** field MUST be included in the result set. If it is omitted in any project statement, then the pagination will have unexpected behavior.

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Thanks for your contribution @lesterw1 !
Hi @demyanenko could you help review this document update? Thanks

**Comment by chiragg4u** [comment]
Thanks for your contribution @lesterw1. :)
The changes looks good, can you please add the output of the cmdlet; I'll signoff from the product team.

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
I've altered the statement based on Alan Yang's suggestion and updated changelog.
@lesterw1 if you could sign the CLA (by clicking the above link) I would be happy to merge this. Thank you!

**Comment by msJinLei** [comment]
@lesterw1 Can you update the branch

**Comment by isra-fel** [comment]
Can't merge the PR without author signing CLA.
Closing it for now. Please feel free to reopen.

**Pull request closed without merging**
