### PR TITLE
updates to the Get-AzureProviderOperation cmdlet 

### PR DESCRIPTION
**Pull request by surabhi-pandey**
Changed the cmdlet to get operations using the new aggregated ProviderOperations endpoint under PAS RP. The cmdlet was earlier querying each RP separately

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@surabhi-pandey__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by stankovski** [comment]
Started on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/50/
Started MSI job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/386/

**Comment by yugangw-msft** [comment]
start a new ondemand job  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/63/

**Comment by yugangw-msft** [comment]
on-demand job passed. Per mail communication, it is fine to disable "TestNewResourceGroupWithTemplate" and let Vivek follow up in his own PR.
@vivsriaus, this PR will simplify your #665  a lot.

**Pull request merged**
