### PR TITLE
Fix communicator bug when grabbing next page link for Elastic job target executions

### PR DESCRIPTION
**Pull request by johnpaulkee**
## Description

Changes are to job executions communicator, we didn't poll correctly for job target executions especially when target executions payload has more than 100 count potentially as part of response.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ Not needed, no changes ] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by johnpaulkee** [comment]
@markcowl , do you know what's going on with the build?

**Comment by johnpaulkee** [comment]
friendly ping @cormacpayne and/or @markcowl

**Comment by markcowl** [comment]
@johnpaulkee If you are plannign on putting out a new Sql preview, you will need to bring that branch up t date with master first.  If you just intended to fix this in the stable version of Sql, then this PR should go against the master branch.

**Comment by johnpaulkee** [comment]
Acknowledged @markcowl, will sync with master to grab latest changes.
My intention is update the Sql preview.

**Comment by johnpaulkee** [comment]
I'll add the jobs cmdlets over to master and have the fix there.

**Pull request closed without merging**
