### PR TITLE
Updated Batch Account cmdlets to use Tag Conversion Helper

### PR DESCRIPTION
**Pull request by brnleehng**
Fixed scenario tests for Batch Account cmdlets to use proper tag form
Added Batch accounts cmdlet to use tag conversion helper

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brnleehng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@brnleehng Merge conflicts, please update

**Comment by brnleehng** [comment]
@markcowl Updated

**Comment by cormacpayne** [comment]
@brnleehng Please update ChangeLog.md with information about your changes in your PR

**Pull request merged**
