### PR TITLE
rename AzureAuditDataSource to AzureActivityDataSource

### PR DESCRIPTION
**Pull request by haitch**
As azure rename AuditLog to ActivityLog, we also rename our dataSource cmdlets to reflect the change.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@haitch__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (haitch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
@haitch Hey Haitao, do you plan on adding an alias to the old cmdlet name (or leaving the cmdlet name the same and adding an alias to the new cmdlet name)? The way the PR stands now, this will be a breaking change for customers who use New-AzureRmOperationalInsightsAzureAuditDataSource

**Comment by markcowl** [comment]
@haitch You will need to add an alias to the old cmdlet name to avoid breaking cusomers.

**Comment by markcowl** [comment]
@haitch Closing this PR.  Please open a new pr if you decide to remove the cmdlets and add an alias to the old name.

**Pull request closed without merging**
