### PR TITLE
Parameter description looks like reversed. (Phase 1 / 2)

### PR DESCRIPTION
**Pull request by ShuheiUda**
## Description
Parameter description looks like reversed. (Phase 1 / 2)
Could you please check it?

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@MikhailTryakhov Can you verify this fix?

**Comment by maddieclayton** [comment]
@azuresdkci Test this please

**Comment by number213** [comment]
Those descriptions should be updated in C# class too
https://github.com/Azure/azure-powershell/blob/master/src/ResourceManager/Network/Commands.Network/VirtualNetworkGateway/NewAzureRmVpnClientIpsecPolicyCommand.cs

**Comment by number213** [comment]
We should also ask Brooklyn to take a look. Swagger specs have the same descriptions
https://github.com/Azure/azure-rest-api-specs/blob/master/specification/network/resource-manager/Microsoft.Network/stable/2018-10-01/virtualNetworkGateway.json#L2292

**Comment by cormacpayne** [comment]
@Nilambari Hey Nilambari, would you mind taking a look?

**Comment by cormacpayne** [comment]
@Nilambari ping on the above comments

**Comment by Nilambari** [comment]
This is just documentation change so I sign off. Thanks!

**Comment by markcowl** [comment]
@ShuheiUda We would liek to merge this, but looks like there are merge conflicts that can't be resolved in the UI.  I will create a new PR with these changes and close this in favor of the new PR once it is done.

**Comment by markcowl** [comment]
Closing this in favor of #8140

**Pull request closed without merging**
