### PR TITLE
[HDInsight] Update sdk from hyak to swagger, supported capabilities feature, renamed cmdlet related to oms, fixed some github issues

### PR DESCRIPTION
**Pull request by aim-for-better**
This PR is a breaking change:
1. Changed Microsoft.Azure.Management.HDInsight from 2.1.0 to 5.1.0.
2. Removed three cmdlets:Get/Enable/Disable-AzHDInsightOMS.
3. Added three cmdlets Get/Enable/Disable-AzHDInsightMonitoring to replace Get/Enable/Disable-AzHDInsightOMS.
4. Fixed cmdlet Get-AzHDInsightProperties to support get capabilities information of a specific location.
5. Removed two cmdlets: Grant/Revoke-AzHDInsightRdpServicesAccess.
6. Removed parameter sets("Spark1", "Spark2") from Add-AzHDInsightConfigValue.
7. Add examples to cmdlet: Add-AzHDInsightSecurityProfile
8. Changed the Following cmdlets' output type:
    - Changed the output type of Get-AzHDInsightProperties from CapabilitiesResponse to AzureHDInsightCapabilities.
    - Changed the output type of Remove-AzHDInsightCluster from ClusterGetResponse to bool.
    - Changed the output type of Set-AzHDInsightGatewaySettings HttpConnectivitySettings to GatewaySettings.
9. Added Scenario Test Framework and added some scenario test cases.
10. Fix azure-powershell github issue #7009, #5144, #4351, #4218

## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by aim-for-better** [comment]
Hi team, could you please help us review the pr?

**Comment by cormacpayne** [comment]
@aim-for-better sent an email to @idear1203 relating to this PR. Please let me know if you have any questions or concerns.

**Comment by aim-for-better** [comment]
> @aim-for-better sent an email to @idear1203 relating to this PR. Please let me know if you have any questions or concerns.

Hi @cormacpayne We choose option 2) to publish a preview version Az.HDInsight module. I have updated the Az.HDInsight.psd1 file by adding preview flag. Could you please help us review this PR? I

**Comment by cormacpayne** [comment]
Closing this PR in favor of https://github.com/Azure/azure-powershell/pull/9941

**Pull request closed without merging**
