### PR TITLE
Updating versions and release notes for AzureRM 2.4.0 and AzureStack 1.7.0 release

### PR DESCRIPTION
**Pull request by bganapa**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by bganapa** [comment]
ps-sign-esrp - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign-esrp/89/

**Comment by maddieclayton** [comment]
@bganapa @deathly809 Should we merge this in?

**Comment by bganapa** [comment]
@maddieclayton The other PR would result in conflicts with this one. Please merge the other PR
https://github.com/Azure/azure-powershell/pull/8379
I will resolve the conflicts here.

**Comment by maddieclayton** [comment]
@bganapa @deathly809 Is this ready for merge?

**Pull request merged**
