### PR TITLE
Update New-AzureStorageBlobSASToken docs to help with permissions

### PR DESCRIPTION
**Pull request by joandrsn**
Added information on permissions since it is required to be a sting.

## Description

Simply added a small note reading that it must be a string and not `Read`

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by blueww** [comment]
@joandrsn 

Generally I am OK with the change. 2 minor thing:

We already give the sample of permission in the Example of the cmdlet. 
Could you give more background on any special reason that we need to emphasize how to use it again?

Besides that, if that's necessary,  we have many other sas cmdlets with -permission parameter, should we change the help of all of them？

**Comment by joandrsn** [comment]
@blueww I've been using powershell for quite some time. Often paramters use a ValidationSet to help the user to find what parameters are available, but this is a string. Initially I was thinking that it was an array and you had to use the permission parameter like this: `"Read", "Write", "Delete"` and that the `"rwd"` was just a shortcut.
To my surprise the Cmdlet parses this string into a function called [PermissionsFromString][0] and from there uses it. It confused me. 
So in order not to confuse others, I thought it might be a good idea to include a small note.

I haven't thought about other cmdlets. They should be included if my reasoning above is good. I'll probably add them later.



[0]: https://github.com/Azure/azure-storage-net/blob/master/Lib/Common/File/SharedAccessFilePolicy.cs#L104

**Comment by blueww** [comment]
Thanks @joandrsn  for the explain!

BTW, following is the list of cmdlet that has permssion paramter.

New-AzureStorageBlobSASToken (done in this PR)
New-AzureStorageContainerSASToken
New-AzureStorageAccountSASToken
New-AzureStorageFileSASToken
New-AzureStorageQueueSASToken
New-AzureStorageShareSASToken
New-AzureStorageTableSASToken
New-AzureStorageContainerStoredAccessPolicy
New-AzureStorageQueueStoredAccessPolicy
New-AzureStorageShareStoredAccessPolicy
New-AzureStorageTableStoredAccessPolicy
Set-AzureStorageContainerStoredAccessPolicy
Set-AzureStorageQueueStoredAccessPolicy
Set-AzureStorageShareStoredAccessPolicy
Set-AzureStorageTableStoredAccessPolicy

**Comment by maddieclayton** [comment]
@blueww Can you give final signoff on this change?

**Comment by blueww** [comment]
LGTM

**Pull request merged**
