### PR TITLE
Fixed HDI ADL cluster creation and added live test

### PR DESCRIPTION
**Pull request by yoreddy**
Fixed HDI ADL cluster creation and added Live test for the scenario.
Can you please review this and check in?

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by yoreddy** [comment]
Test not related to my change has failed. can you please take a look?

Microsoft.WindowsAzure.Commands.Test.WAPackIaaS.Operations.JobOperationsTests.WaitOnJobCompletesImmediately
Assert.True() Failure\r\nExpected: True\r\nActual:   False
   at Microsoft.WindowsAzure.Commands.Test.WAPackIaaS.Operations.JobOperationsTests.WaitOnJobCompletesImmediately() in d:\workspace\powershell\src\ServiceManagement\Services\Commands.Test\WAPackIaaS\Operations\JobOperationsTests.cs:line 48

**Comment by yoreddy** [comment]
I submitted an on-demand PowerShell job to confirm that build passes with my changes http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/352/ . can someone take a look please?

**Comment by hovsepm** [comment]
Re-targeted to release 1.3.2 in PR #2060

**Pull request closed without merging**
