### PR TITLE
Fix PSNetWorkRuleDefaultActionEnum values

### PR DESCRIPTION
**Pull request by marcan2020**
## Description

Mismatch in the DefaultAction Enum values.
https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.defaultaction?view=azure-dotnet#fields

## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by markcowl** [comment]
@blueww Can you take a look?

**Comment by blueww** [comment]
@markcowl  

This will be a breaking change.
Set default action with 0/1 works in PSH (Although all our official doc don't set it with 0/1, but Allow/Deny) , like：
```powershell
  Update-AzStorageAccountNetworkRuleSet -ResourceGroupName $resourceGroupName -Name $accountName2 -DefaultAction 0
```

@marcan2020 
Could you give the reason for the change?
If user use set DefaultAction with Allow/Deny like the current official doc, they won't meet any issue with current code.

**Comment by marcan2020** [comment]
@blueww You are right, if the user sets the DefaultAction with Allow/Deny, it will be fine. 

It's just a mismatch between models representing the same thing:
- Microsoft.Azure.Commands.Management.Storage.Models.PSNetWorkRuleDefaultActionEnum
- Microsoft.Azure.Management.Storage.Models.DefaultAction

**Comment by blueww** [comment]
@marcan2020 
Is there any special reason that you need to change this? 
Since if user follow the doc to use the powershell cmdlets, there should be no problem.

And since this is a breaking change, generally we won't take it until a major release (2 times a year)

**Comment by marcan2020** [comment]
@blueww I don't really need that change... Like a said, it's just a mismatch between the enums. 

When you look at a raw json of a [PSNetworkRuleSet](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.commands.management.storage.models.psnetworkruleset) object, the DefaultAction value is set to 0 (Deny) or 1(Allow) and it can be confusing since it does not match with the [other enum definition](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.storage.models.defaultaction).

**Comment by blueww** [comment]
@marcan2020 
Although the enum defined in PSH not match the enum defined in rest API, this does not impact customer usage, if they follow the related feature docs to use the cmdlet.

Since this is a breaking change, I can't take it t until a major release (2 times a year). 
Do you mind to close the PR first, and open an issue to track if we can fix it in the next major release.

**Comment by marcan2020** [comment]
@blueww Closed, see https://github.com/Azure/azure-powershell/issues/9880.

**Pull request closed without merging**
