### PR TITLE
[AppServices]: Fix #16646 : Marked `New-AzWebAppContainerPSSession` as obsolete

### LINKED ISSUE #16646: Mark New-AzWebAppContainerPSSession as obsolete
### Description

We are no longer recommending customers to use the Win-RM capability as we added a Web Console in the portal and in the advanced Web Console in the “Advanced Tools” section of the portal which is better and more secure option. We are planning on stop supporting the Win-RM capability in the future.

For more information on the Web Console:
https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-windows#from-the-kudu-console

### Issue script & Debug output

```PowerShell
N/A
```

### Environment data

```PowerShell
N/A
```

### Module versions

```PowerShell
N/A
```

### Error output

```PowerShell
N/A
```

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
#16646 
## Description

We are no longer recommending customers to use the Win-RM capability as we added a Web Console in the portal and in the advanced Web Console in the “Advanced Tools” section of the portal which is better and more secure option. We are planning on stop supporting the Win-RM capability in the future.

For more information on the Web Console:
https://docs.microsoft.com/en-us/azure/app-service/configure-custom-container?pivots=container-windows#from-the-kudu-console

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @Kotasudhakarreddy , could please provide more information about this deprecation to customer?

**Comment by Kotasudhakarreddy** [comment]
> Hi @Kotasudhakarreddy , could please provide more information about this deprecation to customer?

@BethanyZhou - Deprecation happens in the next Breaking change release. We don't have exact `deprecateByVersion` number or `changeInEfectByDate` currently. If you have an idea of next breaking change release please let me know. I can update more details to the customer.

**Comment by BethanyZhou** [comment]
Do you have a page about to demonstrate this deprecation. We can use GenericBreakingChange to provide more information.

image

**Comment by Kotasudhakarreddy** [comment]
> Do you have a page to demonstrate this deprecation. We can use GenericBreakingChange to provide more information.
> 
> image

@panchagnula do we have any such page to demonstrate the deprecation other than the GitHub link.

**Comment by panchagnula** [comment]
> > Do you have a page to demonstrate this deprecation. We can use GenericBreakingChange to provide more information.
> > image
> 
> @panchagnula do we have any such page to demonstrate the deprecation other than the GitHub link.

@jvano is there any public documentation for deprecation news?

**Comment by Kotasudhakarreddy** [comment]
> > > Do you have a page to demonstrate this deprecation. We can use GenericBreakingChange to provide more information.
> > > image
> > 
> > 
> > @panchagnula do we have any such page to demonstrate the deprecation other than the GitHub link.
> 
> @jvano is there any public documentation for deprecation news?

@jvano any such public documentation for deprecation news?

**Comment by jvano** [comment]
@apwestgarth, @Kotasudhakarreddy has some questions about the deprecation of the Win-RM feature for Windows Containers on App Service. Can you help getting his questions answered? The questions are around public notifications and documentation about this change.

**Comment by BethanyZhou** [comment]
Sorry, let me clarify. Public notifications is unnecessary. Just want to let customer know what happens to this cmdlet and what should be done from customer side in next step. a public documentation  would help customer know their situation.

**Comment by apwestgarth** [comment]
Hi @BethanyZhou and @Kotasudhakarreddy we notified customers in September 2020 that the feature would be deprecated as it was removed from the preview functionality before we GA'd Windows Container support on Azure App Service.  The ability to connect to a Windows Container via Win-RM was officially retired on 12th December 2020.  Docs have long since been updated to remove mention of Win-RM connect.

This item is to formally remove the functionality from PowerShell.  

For customers wishing to connect to their windows container they can use the following documentation link - https://docs.microsoft.com/azure/app-service/configure-custom-container?pivots=container-windows#connect-to-the-container or if you prefer a shortlink please use https://aka.ms/appsvcconnecttowincontainer

**Review by isra-fel — APPROVED** [review]
LGTM.
The cmdlet and related code should be removed in the next month.

**Pull request merged**
