### PR TITLE
Update Set-AzureRmLocalNetworkGateway.md

### PR DESCRIPTION
**Pull request by anzaman**
added example

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by anzaman** [comment]
Added example

**Comment by maddieclayton** [comment]
@anzaman Please add an entry to the changelog for this file: https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Network/Commands.Network/ChangeLog.md.  Please also add example output for this example, as well as a header for the example - see example here: https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Aks/Commands.Aks/help/New-AzureRmAks.md#examples.

**Comment by maddieclayton** [comment]
I also changed the target from your patch branch to the preview branch, as I am assuming you want this to be released.

**Comment by maddieclayton** [comment]
@anzaman Please add example output as well as a changelog entry to this PR.

**Pull request closed without merging**
