### PR TITLE
Workaround for the token cache issue in Az.Accounts 2.1.0

### PR DESCRIPTION
**Pull request by dineshreddy007**
## Description

TokenCache.ReadItems() is not working in latest version 2.1.0 of Az.Accounts. As a workaround using AuthFactory.Authenticate() instead of TokenCache.ReadItems().

## Checklist

- [ Yes] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [Yes ] The title of the PR is clear and informative
- [ Yes] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [Yes ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [Yes ] If applicable, the changes made in the PR have proper test coverage
- [ NotApplicable] For public API changes to cmdlets:
    - [NotApplicable ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [NotApplicable] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by dineshreddy007** [comment]
Will send a new iteration with a different workaround as per Yeming's suggestion.

**Review by isra-fel — COMMENTED** [review]
Hi @dineshreddy007  versions are calculated automatically during release process, so I've reverted psd1 and AssemblyInfo.cs.

Have you tested the new work-around? Is it ready for a release?

**Comment by dineshreddy007** [comment]
Hi @isra-fel i have tested the workaround and it is ready for release.

**Comment by dineshreddy007** [comment]
> Hi @dineshreddy007 versions are calculated automatically during release process, so I've reverted psd1 and AssemblyInfo.cs.
> 
> Have you tested the new work-around? Is it ready for a release?

I have tested the workaround and it is ready for release.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
