### PR TITLE
Update Set-AzureRmAnalysisServicesServer.md

### PR DESCRIPTION
**Pull request by DataArdentPrak**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@azuresdkci Add to whitelist

**Comment by maddieclayton** [comment]
@taiwu @athipp Can you confirm that this is the correct behavior, and should be included in the help file?

**Comment by taiwu** [comment]
We do allow user update admins via powershell scripts.

**Comment by maddieclayton** [comment]
@PrakharSaxena-31 Please sign the contributor agreement above so we can merge this PR.  Thanks for your contribution!

**Comment by maddieclayton** [comment]
Closing was we have not gotten the CLA signed and cannot merge. @PrakharSaxena-31 Please accept the CLA and we will reopen and merge.

**Pull request closed without merging**
