### PR TITLE
Add new fields to ER objects

### PR DESCRIPTION
**Pull request by ghost**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vinayada__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (vinayada). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@deepakrajendranmsft @huangpf @hyonholee Can you guys take a look

@vinayada   Where are the tests for whatever new functionality is implemented here?

**Comment by vinayada** [comment]
Vinaya Natarajan will submit a single PR with mine and her changes together

**Pull request closed without merging**
