### PR TITLE
webapp: Migrating an app to another Appservice plan was removing existing tags from the app resource

### PR DESCRIPTION
**Pull request by panchagnula**
Fixes#9981

## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by panchagnula** [comment]
@cormacpayne did not add any tests will go-ahead & do that.

**Comment by panchagnula** [comment]
Added tests

**Comment by meepstei** [comment]
@panchagnula @cormacpayne Is there an update for this issue? I have tested again and the tags are still not being moved over when we change the ASP using PS, thanks.

**Comment by panchagnula** [comment]
you need to wait for the change to hit PROD you can follow the release notes here https://github.com/Azure/azure-powershell/releases

**Pull request merged**
