### PR TITLE
Add TLS 1.3 to MinimalTlsVersion

### PR DESCRIPTION
**Pull request by jha1bhavna**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

CmdLet testing snippet:

PS D:\src\Powershell\azure-powershell> (Get-AzSqlServer -ServerName testmintls -ResourceGroupName bhavnajha-rg).MinimalTlsVersion
1.2
PS D:\src\Powershell\azure-powershell> Set-AzSqlServer -ServerName testmintls -ResourceGroupName bhavnajha-rg -MinimalTlsVersion "1.3"

ResourceGroupName             : bhavnajha-rg
ServerName                    : testmintls
Location                      : eastus2
SqlAdministratorLogin         : CloudSA1a25ac67
SqlAdministratorPassword      :
ServerVersion                 : 12.0
Tags                          : {}
Identity                      :
FullyQualifiedDomainName      : testmintls.database.windows.net
ResourceId                    : /subscriptions/eb951d38-18d9-46d4-9a0c-f694b148c76a/resourceGroups/bhavnajha-rg/providers/Microsoft.Sql/servers/testmintls
MinimalTlsVersion             : 1.3
PublicNetworkAccess           : Disabled
RestrictOutboundNetworkAccess : Disabled
Administrators                : Microsoft.Azure.Management.Sql.Models.ServerExternalAdministrator
PrimaryUserAssignedIdentityId :
KeyId                         :
FederatedClientId             :

PS D:\src\Powershell\azure-powershell> (Get-AzSqlServer -ServerName testmintls -ResourceGroupName bhavnajha-rg).MinimalTlsVersion
1.3

ff

### CODE REVIEW

**Comment by msJinLei** [comment]
Need to update Azure.Core version first

**Comment by jha1bhavna** [comment]
> Need to update Azure.Core version first

Where do we update that? to what?

**Comment by msJinLei** [comment]
> > Need to update Azure.Core version first
> 
> Where do we update that? to what?

The "Azure.ResourceManager.Sql" introduce the dependancy of Azure.Core 1.37, which conflicts with the exiting Azure.Core Azure PowerShell uses.
What you depend on in Azure.ResourceManager.Sql. You should generate it in your generated SDK.

**Comment by jha1bhavna** [comment]
> > > Need to update Azure.Core version first
> > 
> > 
> > Where do we update that? to what?
> 
> The "Azure.ResourceManager.Sql" introduce the dependancy of Azure.Core 1.37, which conflicts with the exiting Azure.Core Azure PowerShell uses. What you depend on in Azure.ResourceManager.Sql. You should generate it in your generated SDK.

Updated the Azure.Core version to 1.38

**Pull request closed without merging**
