### PR TITLE
[Blueprint] Blueprint and artifact folder/file names should be platform agnostic

### PR DESCRIPTION
**Pull request by filizt**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @filizt why do not merge?

**Comment by filizt** [comment]
> Hi @filizt why do not merge?

I pushed another commit. Please feel free to merge any time.

**Comment by VeryEarly** [comment]
Hi @filizt ,

in your code changes, the string "blueprint.json"/"artifacts" were still hard coded, what is the benefit to make these changes?

**Comment by filizt** [comment]
> Hi @filizt ,
> 
> in your code changes, the string "blueprint.json"/"artifacts" were still hard coded, what is the benefit to make these changes?

Yes, they are hard coded since we look for a file named "blueprint" with .json extension and "artifacts" folder (these are specific to export/import cmdlet use and are is explained in the documentation). However these files/folder names can have different letter casing such as "Artifacts" or "Blueprint.json" so the fix is to search for the blueprint file and artifacts folder in a case insensitive way. The case sensitivity in file/folder names is not an issue in Windows however it's a problem on Linux file system where the file/folder names are case sensitive.

**Comment by VeryEarly** [comment]
> > Hi @filizt ,
> > in your code changes, the string "blueprint.json"/"artifacts" were still hard coded, what is the benefit to make these changes?
> 
> Yes, they are hard coded since we look for a file named "blueprint" with .json extension and "artifacts" folder (these are specific to export/import cmdlet use and are explained in the documentation). However these files/folder names can have different letter casing such as "Artifacts" or "Blueprint.json" so the fix is to search for the blueprint file and artifacts folder in a case insensitive way. The case sensitivity in file/folder names is not an issue in Windows however it's a problem on Linux file system where the file/folder names are case sensitive.

Got it, thanks for the response.

**Pull request merged**
