### PR TITLE
[Compute] VM/VMSS reimage

### PR DESCRIPTION
**Pull request by hyonholee**
## Description

* Add Invoke-AzVMReimage cmdlet and add TempDisk parameter to Set-AzVmss

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/200

* Fix the warning message of New-AzVM and add change log.

https://github.com/Azure/azure-powershell/issues/3735

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@hyonholee It looks like the ProvisionAfterExtension cmdlet design review has not yet been closed. Marking as cmdlet review required until that design review is closed.

**Comment by hyonholee** [comment]
@maddieclayton  Shall I divide this PR in to two separate PRs for VM/VMSS reimage and ProvisionAfterExtension, so that we can include VM/VMSS reimage in this release?

**Comment by maddieclayton** [comment]
@hyonholee That sounds perfect.

**Comment by hyonholee** [comment]
@MiYanni @maddieclayton I reverted the part for ProvisionAfterExtension.

**Comment by maddieclayton** [comment]
This looks great except that no new incoming cmdlets should have alias mappings.  I removed that for you and updated the test.  It also looks like this issue wasn't addressed in this PR unless I missed it somehow: https://github.com/Azure/azure-powershell/issues/3735.  I will still merge this PR, but won't close the linked issue.

**Pull request merged**
