### PR TITLE
[SQL] Remove IsAzureADOnlyAuthentication from Set-AzSqlServerActiveDirectoryAdministrator

### PR DESCRIPTION
**Pull request by amolagar5**
[SQL] Remove IsAzureADOnlyAuthentication from Set-AzSqlServerActiveDirectoryAdministrator

This is bein removed from the SQL in next iteration, so it will be useless to have in this cmdlet. 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by amolagar5** [comment]
Looks like static analysis is failing as I am removing a parameter, This parameter is not used by customers as functionality was never publicly released. Design changed now, so  a separate API is being added to release. How do I safely deprecate it.

**Comment by VeryEarly** [comment]
> Looks like static analysis is failing as I am removing a parameter, This parameter is not used by customers as functionality was never publicly released. Design changed now, so a separate API is being added to release. How do I safely deprecate it.

Hi @amolagar ,

These doesn't look like breaking changes, please try suppress messages following https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md

**Comment by amolagar5** [comment]
> > Looks like static analysis is failing as I am removing a parameter, This parameter is not used by customers as functionality was never publicly released. Design changed now, so a separate API is being added to release. How do I safely deprecate it.
> 
> Hi @amolagar ,
> 
> * These doesn't look like breaking changes, please try suppress messages following https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md
> * please also resolve merge conflict

Thanks @VeryEarly , I have added the suppress messages and resolved merged conflicts.

**Pull request merged**
