### PR TITLE
[Bastion] Add support for 'Premium' Sku and 'enableSessionRecording' feature flag

### PR DESCRIPTION
**Pull request by abhi7860**
## Description

Adding support for 'Premium' Sku and 'enableSessionRecording' feature

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

## Relevant Links

*  https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1441

### CODE REVIEW

**Comment by NoriZC** [comment]
Hi @abhi7860, looks like you updated the generated SDK to solve the build issue. But manual edition is not allowed for generated code in our repo to improve the maintanance of modules. 

Could you explain more about the build issue? Do you believe it is due to the incorrect swagger or because of the incorrect autorest behavior?

**Comment by NoriZC** [comment]
And another thing is:

Notified that this PR is targeting the public preview version, could you please confirm [release-network-2024-01-01](https://github.com/Azure/azure-powershell/tree/release-network-2024-01-01) is the correct branch?

**Comment by abhi7860** [comment]
> Hi @abhi7860, looks like you updated the generated SDK to solve the build issue. But manual edition is not allowed for generated code in our repo to improve the maintanance of modules.
> 
> Could you explain more about the build issue? Do you believe it is due to the incorrect swagger or because of the incorrect autorest behavior?

@NoriZC I updated the generated SDK so that I can consume the newer Swagger changes. Here is the PR for that: https://github.com/Azure/azure-rest-api-specs/pull/29127. The build issue is because of Static Analysis failure
`"Az.Network","src/Network/Network.Management.Sdk","1","9090","Generated code for Az.Network is not up to date or you have updated generated Sdk.","You may need to rebase on the latest main, regenerate code accroding to README.md file under src/Network/Network.Management.Sdk, and make sure no more updates based on generated files."`

I followed the readme from Network.Management.Sdk for the refresh. Can the SDK team refresh it so I can consume the newer changes?

And since the swagger changes will be released in 24-01-01 I also want PS changes to go along with the same version.

**Comment by NoriZC** [comment]
Yes what you are intending to do is definitely correct. But in [this commit](https://github.com/Azure/azure-powershell/pull/25096/commits/218487f07ef25b889dbb3d4344c3fc5d5cbd6cdc), seems you updated the generated code manually to fix some build issue.

Our policy is to only accpet code generated by `autorest` under `/Generated` folder.

**Comment by abhi7860** [comment]
@NoriZC I have resolved the issue with manual edits in Network.Management.Sdk - it was a mistake I made while rebasing. Currently, the pipelines are failing due to certain tests whose top level categories are:-

- ApplicationGatewayTests (1)
- CortexTests (4)
- NetworkWatcherAPITests (6)
- RestartNetworkVirtualApplianceTest (1)
for a total of 12 tests. I am not sure if this is because of the Network.Management.Sdk upgrade. How should we proceed with the changes?

**Comment by NoriZC** [comment]
> And another thing is:
> 
> Notified that this PR is targeting the public preview version, could you please confirm [release-network-2024-01-01](https://github.com/Azure/azure-powershell/tree/release-network-2024-01-01) is the correct branch?

@abhi7860 FYI please anwser this

**Comment by NoriZC** [comment]
> @NoriZC I have resolved the issue with manual edits in Network.Management.Sdk - it was a mistake I made while rebasing. Currently, the pipelines are failing due to certain tests whose top level categories are:-
> 
> * ApplicationGatewayTests (1)
> * CortexTests (4)
> * NetworkWatcherAPITests (6)
> * RestartNetworkVirtualApplianceTest (1)
>   for a total of 12 tests. I am not sure if this is because of the Network.Management.Sdk upgrade. How should we proceed with the changes?

In current[ CI result](https://dev.azure.com/azclitools/public/_build/results?buildId=165297&view=logs&jobId=b17395f6-68a3-5682-0476-d3f6f1043109&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0) I only see one error:

Commands.Network.Test.ScenarioTests.RestartNetworkVirtualApplianceTest.TestNetworkVirtualApplianceRestart 

Is this error happening locally? Could you tried re-recording the failed test cases to see whether the issue could be resolved?

**Comment by abhi7860** [comment]
> > And another thing is:
> > Notified that this PR is targeting the public preview version, could you please confirm [release-network-2024-01-01](https://github.com/Azure/azure-powershell/tree/release-network-2024-01-01) is the correct branch?
> 
> @abhi7860 FYI please anwser this

"And since the swagger changes will be released in 24-01-01 I also want PS changes to go along with the same version." I answered it before

**Comment by abhi7860** [comment]
> > @NoriZC I have resolved the issue with manual edits in Network.Management.Sdk - it was a mistake I made while rebasing. Currently, the pipelines are failing due to certain tests whose top level categories are:-
> > 
> > * ApplicationGatewayTests (1)
> > * CortexTests (4)
> > * NetworkWatcherAPITests (6)
> > * RestartNetworkVirtualApplianceTest (1)
> >   for a total of 12 tests. I am not sure if this is because of the Network.Management.Sdk upgrade. How should we proceed with the changes?
> 
> In current[ CI result](https://dev.azure.com/azclitools/public/_build/results?buildId=165297&view=logs&jobId=b17395f6-68a3-5682-0476-d3f6f1043109&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0) I only see one error:
> 
> Commands.Network.Test.ScenarioTests.RestartNetworkVirtualApplianceTest.TestNetworkVirtualApplianceRestart
> 
> Is this error happening locally? Could you tried re-recording the failed test cases to see whether the issue could be resolved?

Upon checking the error from the CI result I ran all tests locally which is where the aforementioned tests are failing. Upon re-run and re-record, 2 succeeded but 10 are still failing. And as mentioned, "TestNetworkVirtualApplianceRestart" continues to fail

**Comment by abhi7860** [comment]
@NoriZC Please lmk when SDK upgrade completes so I can rebase my changes accordingly. Thanks.

**Comment by htippanaboya** [comment]
@abhi7860 - is this for the current release. We are way past the code freeze date. Please merge it asap

**Comment by abhi7860** [comment]
> @abhi7860 - is this for the current release. We are way past the code freeze date. Please merge it asap

Since the SDK refresh was not done, CI was failing due to critical fix not present. I have rebased with latest changes now. Waiting on results

**Review by NoriZC — APPROVED** [review]

**Pull request merged**
