### PR TITLE
Normalize installer build for Web Deployment assembly

### LINKED ISSUE #2301: Identify issues with Microsoft.Web.Deployment and Microsoft.Web.Hosting in installer build
### Description 
Microsoft.Web.* assemblies are copiued in the build on some systems and not on others.  Identify the cause for this and fix so that all appropriate assemblies are included in the cmdlet packages (and in wxi file generation).

### Size: 1

### PR DESCRIPTION
**Pull request by markcowl**
Fixes #2301

### CODE REVIEW

**Comment by markcowl** [comment]
signing job here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/435/

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
signing job here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/437/

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/839/

**Comment by hovsepm** [comment]
LGTM

**Pull request merged**
