### PR TITLE
Refactor common types for authentication and storage

### PR DESCRIPTION
**Pull request by markcowl**
## Description

- Refactor common type for backward compatibility
- Create single abstractions library for types shared across modules
  - Use types designed for extensibility
- Remove ADAL and external authentication library depednencies form all modules
- Remove reliance on static variables for singleton instances
- Refactor base types for concurrency
- Refactor base types for authentication persistence 
---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [x] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [x] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.
- [x] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [x] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [x] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [x] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [x] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [x] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1474/

**Comment by cormacpayne** [comment]
@markcowl LGTM whenever you are ready to merge (will need to re-approve once merge conflict is resolved and Sql tests are fixed)

**Comment by blueww** [comment]
The change generally looks good to me, except the service mode Add-AzureAccount still not work for me for the code of this repro. 

And I have another PR for upgrade XSCL https://github.com/Azure/azure-powershell/pull/3828, there will be some conflict with this PR. Hope can make my PR check in first.

**Comment by markcowl** [comment]
new on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1496/

signing run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/994/

**Comment by hovsepm** [comment]
in method `public void OnImport()` of AddAzureRmAccount.cs there is try and following catch
```
catch
            {
                // This will throw exception for tests, ignore.
            }
```
we should not silently catch everything during general usage of the cmdlets. I think following way should be much better:
```
catch(Exception) when (TestMockSupport.RunningMocked)
            {
                // This will throw exception for tests, ignore.
            }
```
it will swallow exceptions only in Test mode.

**Comment by hovsepm** [comment]
in RMProfileClient.cs at ListAllSubscriptionsForTenant method you do not have try/finally block which disposes subscriptionClient if execution is not in the test mode. Just want to make sure it is not a result of a bad merge.

**Comment by hovsepm** [comment]
in `src\ResourceManager\Profile\Commands.Profile\Subscription\GetAzureRMSubscription.cs` line 50
```
_client = new RMProfileClient(DefaultProfile as AzureRmProfile);
```
Please use explicit cast. In case of error we will get cast exception here immediately instead of Null ref exception somewhere else later.

**Comment by hovsepm** [comment]
one general concern/suggestion.
Why do we have Common inside ResourceManager? I think it is at least not intuitive - hard to spot out in the folder of cmdlets. What if we will just move everything here to the common folder one folder up? and do a slight renaming. I see it like this
```
src\Common
        |
        --->Commands.Common.Authentication.Test
        --->Commands.Common.Authentication.Abstraction
        --->Commands.Common.Authentication
        --->Commands.Common.ResourceManager.Authentication (This is Commands.Common.Authentication.ResourceManager from your PR) 
        --->Commands.Common.ResourceManager.ScenarioTests (this is current Commands.ScenarioTests.ResourceManager.Common)
        --->Commands.Common.ResourceManager (this is current Commands.ResourceManager.Common)
        --->Commands.Common.ScenarioTests (this is current Commands.ScenarioTests.Common)
        --->Commands.Common.Storage
        --->Commands.Common
```  
Even more - do we really need Commands in front of all these projects? I think it could be removed.

**Comment by hovsepm** [comment]
in `src\Common\Commands.Common.Authentication\Authentication\ProtectedFileTokenCache.cs` on line 31
```
Environment.GetFolderPath(Environment.SpecialFolder.ApplicationData),
```

There is no SpecialFolder in Linux. Can we pick any other folder in PowerShell installation folder?

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1532/

**Comment by markcowl** [comment]
@hovsepm Fixed the top 3 comments.  Agree about the next two, but will address in later PRs

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1543/

**Pull request merged**
