### PR TITLE
Deprecating Invoke-AzStorageSyncFileRecall

### PR DESCRIPTION
**Pull request by mtalasila**
## Description

Deleted a doc for a PowerShell cmdlet we are deprecating (Invoke-AzStorageSyncFileRecall)

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @mtalasila , since `Invoke-AzStorageSyncFileRecall` is still in `Az.StorageSync` module. The doc cannot be removed. You need to add deprecating notication at the cmdlet first. Then you can remove it and it's help document in the next `Major Release`.

**Comment by mtalasila** [comment]
Hi @wyunchi-ms, I am getting a 404 error when I try opening the document for breaking changes that you linked above.

**Comment by BethanyZhou** [comment]
Hi @mtalasila , please try following docs

- [breaking-changes-definition](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md) for adding deprecating notifications.
- [Release-a-Breaking-Change](https://github.com/Azure/azure-powershell-pr/wiki/How-to-Release-a-Breaking-Change) for suppressing the analyze error to pass CI.
> I am getting a 404 error when I try opening the document for breaking changes that you linked above.

You need join [Azure group](https://github.com/Azure) to get access to the info in our private repo.

**Pull request closed without merging**
