### PR TITLE
Fix invalid SAS token from New-AzServiceBusAuthorizationRuleSASToken and New-AzEventHubAuthorizationRuleSASToken

### PR DESCRIPTION
**Pull request by fsackur**
## Description

- Fix for issue #12975 : New-AzServiceBusAuthorizationRuleSASToken returns invalid token
- Fix for issue #14534 : New-AzEventHubAuthorizationRuleSASToken returns invalid token when StartTime is provided

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by fsackur** [comment]
I am not a C# dev and I don't offer enough of my time to get up to speed on the build steps. 

In the case of 12975, if the code compiles, it is impossible for me to make the codebase worse, because the cmdlet is utterly broken. I'm pretty sure that no-one has ever successfully used it.

In the case of 14534, this had previously been fixed in the case where StartTime is not supplied; therefore the last three commits might need to be dropped from the PR if my code sucks.

To save the reviewer time, you may do whatever is expedient with the history; if you wish to drop commits, if you wish to rewrite the history in my branch, go ahead. This branch is just me trying to get some activity on a very frustrating and long-standing bug.

**Review by wyunchi-ms — DISMISSED** [review]

**Comment by v-Ajnava** [comment]
LGTM waiting for CIs to be green

**Comment by fsackur** [comment]
Looking at the build errors now, will update

**Comment by fsackur** [comment]
Hi @v-Ajnava , I _think_ I've fixed the syntax errors, it does at least build on my machine. Could you rerun the pipeline?

**Review by wyunchi-ms — APPROVED** [review]

**Comment by wyunchi-ms** [comment]
Merged. Thanks a lot for your contribution! @fsackur

**Comment by v-Ajnava** [comment]
Thanks @fsackur !

**Pull request merged**
