### PR TITLE
[ServiceFabric] New Az Cmdlets for Service fabric Managed app cmdlets (App, AppType, AppTypeVersion, Service)

### PR DESCRIPTION
**Pull request by LukeSlev**
## Description

* Added new cmdlets for managed applications:
    - `New-AzServiceFabricManagedClusterApplication`
    - `Get-AzServiceFabricManagedClusterApplication`
    - `Set-AzServiceFabricManagedClusterApplication`
    - `Remove-AzServiceFabricManagedClusterApplication`
    - `New-AzServiceFabricManagedClusterApplicationType`
    - `Get-AzServiceFabricManagedClusterApplicationType`
    - `Set-AzServiceFabricManagedClusterApplicationType`
    - `Remove-AzServiceFabricManagedClusterApplicationType`
    - `New-AzServiceFabricManagedClusterApplicationTypeVersion`
    - `Get-AzServiceFabricManagedClusterApplicationTypeVersion`
    - `Set-AzServiceFabricManagedClusterApplicationTypeVersion`
    - `Remove-AzServiceFabricManagedClusterApplicationTypeVersion`
    - `New-AzServiceFabricManagedClusterService`
    - `Get-AzServiceFabricManagedClusterService`
    - `Set-AzServiceFabricManagedClusterService`
    - `Remove-AzServiceFabricManagedClusterService`
* Upgraded Managed Cluster commands to use Service Fabric Managed Cluster SDK version `1.0.0-beta.1` which uses service fabric resource provider api-version 2021-01-01-preview.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/845
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
There are a lot of StaticAnalysis issue. Plesse resolve them.

**Comment by a-santamaria** [comment]
@wyunchi-ms the design review is here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/845.
The breaking changes are all related to cmdlets from Service Fabric Managed Clusters which is still in preview (https://docs.microsoft.com/en-us/azure/service-fabric/overview-managed-cluster) so we are adding those to the braking changes exceptions.
Breaking changes for managed clusters :
* namespace change due to SDK package change: The managed clusters SDK was initially in this package: https://www.nuget.org/packages/Microsoft.Azure.Management.ServiceFabric. We moved here: https://www.nuget.org/packages/Microsoft.Azure.Management.ServiceFabricManagedClusters/1.0.0-beta.1 so the namespaces changed.
* Remove properties we don't support:
	UseTestExtension
	ReverseProxyEndpointPort
	ClusterUpgradeMode
	ClusterCertificateThumbprint
	ClusterUpgradeDescription

**Comment by wyunchi-ms** [comment]
Parameter `Tags` of cmdlet `New-AzServiceFabricManagedClusterApplication` and `Set-AzServiceFabricManagedClusterApplication` does not follow the enforced naming convention of using a singular noun for a parameter name.

**Comment by LukeSlev** [comment]
@wyunchi-ms I modified Tags parameter and sent an email to the PowerShell team regarding the breaking changes

**Review by wyunchi-ms — APPROVED** [review]

**Comment by wyunchi-ms** [comment]
Please resolve the conflicts.

**Comment by LukeSlev** [comment]
@wyunchi-ms conflicts resolved

**Review by wyunchi-ms — APPROVED** [review]

**Comment by a-santamaria** [comment]
@wyunchi-ms thanks for approving. is this going to make it to [S184 (2021-03-23) ](https://github.com/Azure/azure-powershell/milestone/119) release?

**Review by wyunchi-ms — APPROVED** [review]

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
