### PR TITLE
Brooklyn: Powershell support Disconnect vpn connection for Virtual network gateway and P2S Vpn gateway.

### PR DESCRIPTION
**Pull request by ninweninwe**
## Description

Disconnect vpn connection for Virtual network gateway and P2S Vpn gateway.

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/414

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by markcowl** [comment]
@number213 What is the correct branch for network for the next sprint (S165)?

**Comment by number213** [comment]
@markcowl it should be `network-january`. I sent an email to azdevxps asking to create it

**Comment by ninweninwe** [comment]
> @markcowl it should be `network-january`. I sent an email to azdevxps asking to create it

@number213 so I need to close this PR and send another PR to the branch network-january?

**Comment by number213** [comment]
Please rebase to https://github.com/Azure/azure-powershell/tree/network-january

**Comment by ninweninwe** [comment]
merge it into network-january

**Pull request closed without merging**
