### PR TITLE
Cortex ergw

### PR DESCRIPTION
**Pull request by vinayada1**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
Corresponding design review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/186

**Comment by cormacpayne** [comment]
@vinayada1 would you mind resolving the merge conflicts?

**Comment by cormacpayne** [comment]
@vinayada1 ping on the above comments

**Comment by markcowl** [comment]
Closing for lack of response - you need to coordinate network changes with @MikhailTryakhov

**Pull request closed without merging**
