### PR TITLE
Fix allow selecting storage from a different resource group

### PR DESCRIPTION
**Pull request by yaakoviyun**
Fix aloow selecting storage from a different resource group

## Description

Fix allow selecting storage from a different resource group

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by yaakoviyun** [comment]
@yoavfr

**Comment by yaakoviyun** [comment]
@MiYanni , can you review this small bug fix.
I would like it to be included in the upcoming release.
Many thanks.

**Comment by cormacpayne** [comment]
@jaredmoo would you mind taking a look at this PR when you have a chance?

**Comment by yaakoviyun** [comment]
@cormacpayne:
1. With regard of adding notes to the log - this is a bug fix for cmdlets that will be shipped in the upcoming release. I don't think that a bug fix note should be added in this case.
Do you agree?

2. With regard to the testing issue - I did many manual tests for this change. An automatic test will be added in a different PR.
Because this is a high priority bug and the deadline for the upcoming release is next Monday and this is weekend in our timezone, I'd rather add the fix now and  send a new PR with tests after.
Does it make sense?

**Comment by cormacpayne** [comment]
@yaakoviyun 

(1) The change log is used as a signal for us to version a module and release it -- if our tool sees there's no update to a module's change log, then we don't release the module. Currently, the Sql change log has an entry in it, so it'll get versioned and released, but we always want to call out changes that are being made so customers are aware.

(2) As long as @jaredmoo is OK with taking this change without test coverage at the moment and you open an issue to track adding test coverage, it will be fine to take this. Note: since there won't be any test coverage, any hot fix that may arise will have to wait until the following release to go out.

**Comment by yaakoviyun** [comment]
Agreed.
Jared, can you approve?

Sent from Outlook
________________________________
מאת: Cormac McCarthy <notifications@github.com>
‏‏נשלח: יום שישי 20 יולי 2018 10:11:19
‏‏אל: Azure/azure-powershell
עותק: Yaakov Iyun; Mention
‏‏נושא: Re: [Azure/azure-powershell] Fix allow selecting storage from a different resource group (#6702)


@yaakoviyun<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fyaakoviyun&data=02%7C01%7Cyaiyun%40microsoft.com%7Ccabb1c3dc068400eb4db08d5ee0ffde0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636676674810810353&sdata=TWxqFU74SZXbbRjQ14jFXE7AJLr3%2FgAwJqDCoehT%2BPk%3D&reserved=0>

(1) The change log is used as a signal for us to version a module and release it -- if our tool sees there's no update to a module's change log, then we don't release the module. Currently, the Sql change log has an entry in it, so it'll get versioned and released, but we always want to call out changes that are being made so customers are aware.

(2) As long as @jaredmoo<https://na01.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fjaredmoo&data=02%7C01%7Cyaiyun%40microsoft.com%7Ccabb1c3dc068400eb4db08d5ee0ffde0%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C636676674810820370&sdata=is4rD5QSYzmOnKfWnhQfLCe%2Fi07%2FIaNEo2Cp4CgkeX0%3D&reserved=0> is OK with taking this change without test coverage at the moment and you open an issue to track adding test coverage, it will be fine to take this. Note: since there won't be any test coverage, any hot fix that may arise will have to wait until the following release to go out.

**Comment by jaredmoo** [comment]
Approved, but if any later checkin causes regression in untested code, it is the responsibility of the original author to fix the regression.

**Pull request merged**
