### PR TITLE
[OperationalInsights] Remove few handcrafted cmdlets and Onboard autogen cmdlets.

### PR DESCRIPTION
**Pull request by BethanyZhou**
…#17635)

* Removed Table handcrafted cmdlets and tests

* Remove Workspace handcrafted cmdlets

* removed Workspace tests

* added breaking change issue file

* removed hadncrafted cmdlets from psd1 file

* removed changes made to breakingchanges csv

* Update BreakingChangeIssues.csv

* Update BreakingChangeIssues.csv

Co-authored-by: Beisi Zhou <zhoubeisi@gmail.com>

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Could you review this PR and add change log for current changes? If any breaking change warning, please suppress them if it would not break the user experience.

**Comment by dabenhamMic** [comment]
> Could you review this PR and add change log for current changes? If any breaking change warning, please suppress them if it would not break the user experience. @dabenhamMic

I'm unable to add any changes to this branch(main fork), without creating an additional PR .
I've reviewed the PR and it seems fine.

**Comment by isra-fel** [comment]
We expect the static analysis pipeline to fail with breaking changes.
Next step: inspect the breaking changes and decide if they can be suppressed or need further attention.

**Comment by isra-fel** [comment]
Hi @dabenhamMic can you take a look at the list of breaking changes detected by static analysis in the log of CI?
We need to make sure there are no breaking changes and the false positive records are all suppressed.

**Comment by dabenhamMic** [comment]
@isra-fel do we need to add all the approved changes to the breakingChange csv file?

**Comment by isra-fel** [comment]
Kindly ping @dabenhamMic

**Comment by dabenhamMic** [comment]
our PMs decided not to move forward with the move to the autotest.
closing this PM

**Pull request closed without merging**
