### PR TITLE
[DO NOT MERGE] Azure Disk Encryption changes

### PR DESCRIPTION
**Pull request by moisesac**
Adding fix to use the default key encryption algorithm if not specified.
Modified getting the encryption status for a VM (andliu).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@moisesac__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (mocar). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by moisesac** [comment]
Please do not merge this yet.
Thanks!

**Comment by markcowl** [comment]
@moisesac  it has been nearly 30 days.  Please update this PR and prepare it for merging, or we will close it on Wednesday.

**Comment by markcowl** [comment]
@moisesac Closing, as discussed.

**Pull request closed without merging**
