### PR TITLE
[OperationalInsights] Partial transition to auto code generation

### PR DESCRIPTION
**Pull request by dabenhamMic**
## Description

OperationalInsights cmdlets update for the following resources:

Workspace
Tables
Operations
once the auto code gen will be approved, we intend to delete the old cmdlets (for the resources specified above) and make a gradual transition to the auto-gen code

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1107
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by dabenhamMic** [comment]
I require some help here.
when using autorest to generate the cmdlets, "Operations"  swagger: https://github.com/Azure/azure-rest-api-specs/blob/main/specification/operationalinsights/resource-manager/Microsoft.OperationalInsights/preview/2021-12-01-preview/Operations.json
created some files but no cmdlet and no documentation file (.md)  were created as far as i saw.

the command that I expected to see is 'Get-AzOperationalInsightsOperationStatus'

**Comment by dabenhamMic** [comment]
@dingmeng-xue , I tried looking at the build failure reason but couldn't understand the root cause for it to fail.

**Comment by wyunchi-ms** [comment]
1. OperationalInsights is already migrated to autorest. Please retarget to `generation` branch.
2. Please follow the same folder structure with generation branch.

**Comment by wyunchi-ms** [comment]
Closing this PR. New PR is #16903

**Pull request closed without merging**
