### PR TITLE
ExpressRoute Authorization APIs 

### PR DESCRIPTION
**Pull request by dihan0604**
Network Express Route Authorization APIs

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dihan0604__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (dihan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
I did not see any usage of the Microsoft.Azure.Management.Network v. 2.0.16 that was sent alongside this PR in the CR. Please make sure you have test that covers new functionality.

**Comment by markcowl** [comment]
@dihan0604 Please respond to review comments

**Comment by dihan0604** [comment]
Things being moved to swagger and auto rest. I am waiting for those PR being merged to test this powershell.

**Comment by dihan0604** [comment]
Have added tests based on comment, please take a look and merge it. Thanks

**Comment by markcowl** [comment]
@dihan0604 This conflicts with a network change in the pipeline - can you guys please coordinate on the changes for this release?

**Comment by markcowl** [comment]
@dihan0604 Closing for now, as I believe this is now part of the network PR.  Please open a new PR if I am incorrect.

**Pull request closed without merging**
