### PR TITLE
fix the bug for Remove-AzureAvailabilitySet

### PR DESCRIPTION
**Pull request by catweisun**
Fix the bug in Remove-AzureAvailabilitySet #2023

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@catweisun__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by huangpf** [comment]
Add @hyonholee to help take a look when he's back from vacation.

**Comment by huangpf** [comment]
@catweisun 
Could you please help share some sample PS scripts as for test cases? Thanks.

**Comment by catweisun** [comment]
I just run the cmdlet like this Get-AzureVM -SerivceName {cs name} -Name {vm name } | Remove-AzureAvailabilitySet|Update-AzureVM 
the VM should have set the availabilityset first before you execute this script. Once the test cmdlets are executed, you can run the Get-AzureVM to check if the availabilityset setting is gone.

**Comment by hyonholee** [comment]
This fix was already included in Azure/dev branch

https://github.com/Azure/azure-powershell/blob/dev/src/ServiceManagement/Compute/Commands.ServiceManagement/IaaS/AvailabilitySets/RemoveAzureAvailabilitySet.cs

**Comment by hovsepm** [comment]
@catweisun Thank you for the contribution. Per @hyonholee comment that fix is already merged to dev branch. It will be available to public in early May Release.

**Pull request closed without merging**
