### PR TITLE
Revert 23H2 Registration blocker 

### PR DESCRIPTION
**Pull request by priyjain358**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by VeryEarly** [comment]
This PR looks like a breaking change, any reason this feature needs to be reverted?

**Comment by bniranjanbhat** [comment]
This change is related to HCI Device deliveries.
Earlier it was decided that the customers would not be allowed to use certain features if they are on newer version of OS. But later because of engineering constraints we had to allow the allow the customers use these features on the newer versions of OS as well.
Hence this change.
I would not call this as a breaking change, since we are loosing down the validation at this point.

**Comment by VeryEarly** [comment]
> This change is related to HCI Device deliveries. Earlier it was decided that the customers would not be allowed to use certain features if they are on newer version of OS. But later because of engineering constraints we had to allow the allow the customers use these features on the newer versions of OS as well. Hence this change. I would not call this as a breaking change, since we are loosing down the validation at this point.

Thanks for the explanation, please provide release note for this change in the description or comments. Something like Allow newer version ... of ... for ...

**Comment by bniranjanbhat** [comment]
Release Notes:  Allow registration for 23H2 and above versions of the device.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
