### PR TITLE
WORK:3527498 Enabled tests & add recorded tests results for Brooklyn NRP Ignite feature.

### PR DESCRIPTION
**Pull request by Nilambari**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Nilambari__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nilamd). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by Nilambari** [comment]
@DeepakRajendranMsft Can you Please do the review? Thanks!

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by Nilambari** [comment]
@markcowl  Can you Please help accept this PR merge Please? Thanks a lot!

**Comment by ogail** [comment]
@Nilambari please send PR to dev branch

**Comment by Nilambari** [comment]
@ogail Hey, This change needs to be included for Upcoming Code Freeze 5/22 and 5/28 Release Date. Should't it be in Master branch?

**Comment by ogail** [comment]
@Nilambari the `dev` branch is the proper one.

**Comment by Nilambari** [comment]
@ogail I see. Will send it to dev branch then. Thanks for the confirmation!

**Pull request closed without merging**
