### PR TITLE
Fix for #193 ConflictError: The extension ID xxx-PaasDiagnostics-Production-Ext-0 is already in use for this deployment

### LINKED ISSUE #193: ConflictError: The extension ID xxx-PaasDiagnostics-Production-Ext-0 is already in use for this deployment
Where "xxx" is the role name. Repro steps:
1. Create a new cloud service.
2. Deploy a web role to Production slot or first deploy to Staging then swap.
3. Enable diagnostics extension using `Set-AzureServiceDiagnosticsExtension` in Production slot.
4. Deploy to Staging slot without enabling diagnostics extension.
5. Swap, notice now the Staging has diagnostics enabled while Production doesn't have it enabled.
6. Now if I use `Set-AzureServiceDiagnosticsExtension` to enable it again in Production slot, I will get the error in title.

Analysis so far:
I believe it is because the cmdlet is using following code to generate the extension id, therefore   it will generate the same id when I enable the extension for Production slot the second time, since the same id is actually now used by Staging slot, thus the conflict:

    public string GetExtensionId(string extensionName, string slot, int index)
    {
        return string.Format(ExtensionIdTemplate, PrefixName, extensionName, slot, index);
    }

### PR DESCRIPTION
**Pull request by PashaPash**
Fixed #193: Conflict error in `Set-AzureServiceDiagnosticsExtension` when executed after a VIP swap.

A code in `ExtensionManager.InstallExtension` is trying to cleanup old unused extension before uploading a new one. It check for extension usage by iterating though pool of predefined names with the following pattern: `Default-PaaSDiagnostics-<slot>-Ext-<num>` where `<slot>` is the target deployment slot. The problem is that extension configuration is persisted during the VIP swap, so `Default-PaaSDiagnostics-Staging-Ext-0` could be bound to active deployment in `Production` slot and vice versa.

Steps to reproduce the issue:
- Upload new Staging deployment
- Enable diagnostics for Staging slot. `Default-PaaSDiagnostics-Staging-Ext-0` name will be assigned to new config for staging.
- Perform VIP swap. 
  Staging will became Production, but retain `Default-PaaSDiagnostics-Staging-Ext-0` as active diagnostics config.
- Upload a new Staging deployment.
- Try to enable diagnostics for Staging slot. 
- `ExtensionManager.InstallExtension` finds no association between current staging and `Default-PaaSDiagnostics-Staging-Ext-0` and tries to delete it.

Deletion fails as `Default-PaaSDiagnostics-Staging-Ext-0` is used by Production Slot.

I changed `ExtensionManager.InstallExtension` to check both Staging and Production for extension usage, so it no longer tries to drop the extension used by another slot. `ExtensionIdLiveCycleCount` increased to 3 to allow one extra extension to be associated with another slot after VIP swap.
Fix is done for `Set-AzureServiceDiagnosticsExtension`, but similat fix should fix the same problem for RDP and AD extensions. 

Existing `AzureServiceDiagnosticsExtensionTest` and related helpers were updated to use `AzureStorageContext` - old code that used storage name only was slightly out of date.

`HelloNoDiag.cspkg` is a minimal cloud service package required by tests that mentions `nodiagpackage.csv`, seems to be missing after initial code import to github.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@PashaPash__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@PashaPash__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by amarzavery** [comment]
@singhkay , @huangpf - Can you please review the PR?

**Comment by huangpf** [comment]
+@hyonholee

**Comment by markcowl** [comment]
@hyonholee @sighkay @huangpf can you please review this PR

@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by baywet** [comment]
This fix doesn't seem to be in the bits of the August release, can anybody tell me in which version this will be included?

**Comment by huangpf** [comment]
@PashaPash @devigned 
Could you please help check it again, and involve the DA team if necessary, as we also got several reports from our side about the DA extension cmdlets? Thanks.

**Comment by PashaPash** [comment]
@huangpf integration test for this PR - VipSwapWithDiagnosticsExtensionTest - passes on v0.9.6-August2015 tag (d67cd343f099882891b26b01bbfbbf89782218e8), so it seems to be different issue. @baywet could you please provide the exact steps to reproduce it?

**Comment by baywet** [comment]
@PashaPash thanks for your reply. I've got my project on visual studio online, used the cloud service deployment model with build 2015 (also commented on the linked issue on the other project).
When I enable the diagnostics on one or more roles I've this error message. I'm using a custom build machine (not the hosted one). It has vs2013 update 5, vs 2015 RTM, WS2012R2 (up to date), both azure sdk's 2.7, azure ps 0.9.6, ms office sdk (latest version) and SharePoint 2010, 2013 bits. I can also try on the hosted build controller if you think that could make a difference.

**Comment by PashaPash** [comment]
@baywet  Could you please provide exact steps to reproduce the issue (some minimum sequence of commands to make it crash)? Or at least the output of Get-AzureServiceDiagnosticsExtension for both slots right after the crash?

**Comment by baywet** [comment]
2015-08-18T23:57:57.9122458Z Executing the powershell script: C:\agent\tasks\AzureCloudPowerShellDeployment\1.0.13\Publish-AzureCloudDeployment.ps1

2 
2015-08-18T23:57:58.3028793Z Looking for Azure PowerShell module at C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ServiceManagement\Azure\Azure.psd1

3 
2015-08-18T23:57:58.6779022Z AzurePSCmdletsVersion= 0.9.6

4 
2015-08-18T23:57:58.6779022Z Get-ServiceEndpoint -Name -Context Microsoft.TeamFoundation.DistributedTask.Agent.Worker.Common.TaskContext

5 
2015-08-18T23:57:58.6779022Z subscription= Azure Subscription: 
6 
2015-08-18T23:57:58.6779022Z Get-X509Certificate -CredentialsXml <xml>

7 
2015-08-18T23:57:58.7091533Z azureSubscriptionId= 

8 
2015-08-18T23:57:58.7091533Z azureSubscriptionName= Azure Subscription: 
9 
2015-08-18T23:57:58.7091533Z azureServiceEndpoint= https://management.core.windows.net/

10 
2015-08-18T23:57:58.7247805Z Set-AzureSubscription -SubscriptionName Azure Subscription:  -SubscriptionId  -Certificate <cert> -CurrentStorageAccountName attribute -Environment AzureCloud

11 
2015-08-18T23:57:58.7247805Z Select-AzureSubscription -SubscriptionId 
12 
2015-08-18T23:57:58.7560224Z ConnectedServiceName= 

13 
2015-08-18T23:57:58.7560224Z ServiceName= attributeworkerroles

14 
2015-08-18T23:57:58.7560224Z ServiceLocation= East US

15 
2015-08-18T23:57:58.7560224Z StorageAccount= attribute

16 
2015-08-18T23:57:58.7560224Z CsPkg= C:\agent\_work\19f2c445\staging\*.cspkg

17 
2015-08-18T23:57:58.7560224Z CsCfg= C:\agent\_work\19f2c445\staging\*.cscfg

18 
2015-08-18T23:57:58.7560224Z Slot= Staging

19 
2015-08-18T23:57:58.7560224Z AllowUpgrade= true

20 
2015-08-18T23:57:58.7716609Z Find-Files -SearchPattern C:\agent\_work\19f2c445\staging\*.cscfg

21 
2015-08-18T23:57:58.7716609Z serviceConfigFile= C:\agent\_work\19f2c445\staging\ServiceConfiguration.CloudStaging.cscfg

22 
2015-08-18T23:57:58.7716609Z Find-Files -SearchPattern C:\agent\_work\19f2c445\staging\*.cspkg

23 
2015-08-18T23:57:58.7716609Z servicePackageFile= C:\agent\_work\19f2c445\staging\AttributeOnline.Azure.cspkg

24 
2015-08-18T23:57:58.7716609Z Get-AzureService -ServiceName attributeworkerroles -ErrorAction SilentlyContinue

25 
2015-08-18T23:58:04.6575482Z Applying any configured diagnostics extensions.

26 
2015-08-18T23:58:08.8695358Z New-AzureServiceDiagnosticsExtensionConfig -Role AttributeOnline.DocumentLibrariesWorker -StorageContext <context> -DiagnosticsConfigurationPath C:\agent\_work\19f2c445\staging\Extensions\PaaSDiagnostics.AttributeOnline.DocumentLibrariesWorker.PubConfig.xml

27 
2015-08-18T23:58:09.7622560Z Get-AzureDeployment -ServiceName attributeworkerroles -Slot Staging -ErrorAction SilentlyContinue

28 
2015-08-18T23:58:12.6918126Z Set-AzureDeployment -Upgrade -ServiceName attributeworkerroles -Package C:\agent\_work\19f2c445\staging\AttributeOnline.Azure.cspkg -Configuration C:\agent\_work\19f2c445\staging\ServiceConfiguration.CloudStaging.cscfg -Slot Staging -ExtensionConfiguration <extensions>

29 
2015-08-18T23:58:15.8383004Z ##[error]BadRequest: The extension ID AttributeOnlineDocumentLibrariesWorker-PaaSDiagnostics-Staging-Ext-0 is invalid.

**Comment by baywet** [comment]
<?xml version="1.0" encoding="utf-8"?>
<PublicConfig xmlns="http://schemas.microsoft.com/ServiceHosting/2010/10/DiagnosticsConfiguration">
  <WadCfg>
    <DiagnosticMonitorConfiguration overallQuotaInMB="4096">
      <DiagnosticInfrastructureLogs scheduledTransferLogLevelFilter="Error" />
      <Directories scheduledTransferPeriod="PT1M">
        <IISLogs containerName="wad-iis-logfiles" />
        <FailedRequestLogs containerName="wad-failedrequestlogs" />
      </Directories>
      <PerformanceCounters scheduledTransferPeriod="PT1M">
        <PerformanceCounterConfiguration counterSpecifier="\Memory\Available MBytes" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\ISAPI Extension Requests/sec" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\Web Service(_Total)\Bytes Total/Sec" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Requests/Sec" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET Applications(__Total__)\Errors Total/Sec" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Queued" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\ASP.NET\Requests Rejected" sampleRate="PT3M" />
        <PerformanceCounterConfiguration counterSpecifier="\Processor(_Total)\% Processor Time" sampleRate="PT3M" />
      </PerformanceCounters>
      <WindowsEventLog scheduledTransferPeriod="PT1M">
        <DataSource name="Application!*" />
      </WindowsEventLog>
      <CrashDumps>
        <CrashDumpConfiguration processName="WaIISHost.exe" />
        <CrashDumpConfiguration processName="WaWorkerHost.exe" />
        <CrashDumpConfiguration processName="w3wp.exe" />
      </CrashDumps>
      <Logs scheduledTransferPeriod="PT1M" scheduledTransferLogLevelFilter="Error" />
    </DiagnosticMonitorConfiguration>
  </WadCfg>
  <StorageAccount>attribute</StorageAccount>
</PublicConfig>

**Pull request merged**
