### PR TITLE
Update build tools for new module defintion

### PR DESCRIPTION
**Pull request by markcowl**
## Comments

---

This checklist is used to make sure that common issues in a pull request are covered by the creator. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270%28v=vs.85%29.aspx).

Below in **Overall Changes**, check off the boxes that apply to your PR. For the categories that you did not check off, you can remove them from this body. Within each of the categories that you did select, make sure that you can check off **all** of the boxes. 

For information on cleaning up the commits in your pull request, click [here](../documentation/cleaning-up-commits.md).
## Overall Changes
- [x] [**MANDATORY** - General changes](#general)
### General
- [x] Title of the PR is clear and informative
- [x] There are a small number of commits that each have an informative message
- [ ] If it applies, references the bug/issue that the PR fixes
- [x] All files have the Microsoft copyright header
- [x] Cmdlets refer to management libraries through nuget references - no dlls are checked in
- [x] The PR does not introduce breaking changes (unless a major version change occurs in the assembly and module)

### CODE REVIEW

**Comment by markcowl** [comment]
signing build:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/608/

on demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1153/

**Comment by markcowl** [comment]
signing build here:http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/610/

on demand build here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1154/

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@markcowl can you describe briefly what this PR includes

**Pull request merged**
