### PR TITLE
VM Sizes merge with Azure/dev

### PR DESCRIPTION
**Pull request by nemanja88**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nemanja88__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@nemanja88__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Pull request merged**
