### PR TITLE
[Compute] Add warning message for upcoming property changes.

### PR DESCRIPTION
**Pull request by hyonholee**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@hyonholee Because this is the last release of AzureRM, and Az will stay in preview for another month, our current policy around deprecation is that, rather than deprecating this release, you should just make the necessary breaking changes next release. Does that sound like a plan to you?

**Comment by maddieclayton** [comment]
This time around, for pre-1.0 Az, we will just worry about the Migration guide rather than adding in deprecation messages.

**Comment by maddieclayton** [comment]
@hyonholee Just discussed with the team, and we decided that even one release notice of breaking changes for Az is better than none.  Can you please add this format around your changes to ensure they just occur in Az:
```
#if NETSTANDARD
code changes here
#endif 
```
Please also use our breaking change model wherever possible: https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-attribute-help.md

**Comment by hyonholee** [comment]
@maddieclayton I updated the PR by using CmdletOutputBreakingChange and adding the condition.

**Comment by maddieclayton** [comment]
@hyonholee Can you look at the build issue? Looks like you forgot to add a using.  You can make sure netstandard is building by opening C:/azure-powershell/Azure.PowerShell.Netcore.sln and building.

**Pull request merged**
