### PR TITLE
Fixed CLU issue with ValidateElement when the object is not a string or enum.

### PR DESCRIPTION
**Pull request by hovsepm**

### CODE REVIEW

**Comment by markcowl** [comment]
@johanste can you take a look?

**Comment by johanste** [comment]
For value types other than enum, we really should pass in the correct (invariant) culture when calling ToString.

Best regards,
Johan

**Comment by hovsepm** [comment]
@johanste addressed feedback. Also added version bump up to this PR (actually done by mistake, but I think it can go along with these changes).

**Comment by hovsepm** [comment]
now have to bring other changes since the Nuget packages were bumped up.

**Pull request merged**
