### PR TITLE
Adding DiskEncryptionSet input for V2A and H2A + Bug fix to get disk capacity in Get-AzRecoveryServicesAsrProtectableItem cmdlet output

### PR DESCRIPTION
**Pull request by vidyadharijami**
## Description
Adding DiskEncryptionSet input for V2A and H2A 
[cmdlet review is done] https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/453
Bug fix to get disk capacity in Get-AzRecoveryServicesAsrProtectableItem cmdlet output

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
@vidyadharijami Please add some test caese for your new optional parameters for new properties in the output.

**Comment by vidyadharijami** [comment]
> @vidyadharijami Please add some test caese for your new optional parameters for new properties in the output.

@msJinLei This is the requirement for JEDI. We need to do this ASAP. Will add this as backlog work item and do it later.

**Comment by msJinLei** [comment]
> > @vidyadharijami Please add some test caese for your new optional parameters for new properties in the output.
> 
> @msJinLei This is the requirement for JEDI. We need to do this ASAP. Will add this as backlog work item and do it later.

As we discussed in email, please add test cases later.

**Pull request merged**
