### PR TITLE
[ConnectedMachine] update the module to use new API

### PR DESCRIPTION
**Pull request by dorothyhu**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Thanks for @isra-fel . Hi @dorothyhu , as @isra-fel  said, please use tranform to tweak the public swagger spec same as your local spec. Here is an example to transform swagger.
image

Could you share your local spec so that we could give more specific suggestion about the way to transform?

**Comment by dorothyhu** [comment]
> Thanks for @isra-fel . Hi @dorothyhu , as @isra-fel said, please use tranform to tweak the public swagger spec same as your local spec. Here is an example to transform swagger. image
> 
> Could you share your local spec so that we could give more specific suggestion about the way to transform spec?

@BethanyZhou 
https://github.com/Azure/azure-rest-api-specs/blob/5a8527b19b71e2e3fcdf038f470915c010ace293/specification/hybridcompute/resource-manager/Microsoft.HybridCompute/stable/2021-05-20/HybridCompute.json#L654 We wanted to add a "200" response below this line

**Comment by BethanyZhou** [comment]
Hi @dorothyhu , good news, I have an exact example for your case. 

```
  - from: swagger-document
    where: $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroups/{containerGroupName}/start"].post.responses
    transform: >-
      return {
          "202": {
            "description": "Started - the container group is starting."
          },
          "204": {
            "description": "No content"
          },
          "default": {
            "description": "Error response describing why the operation failed.",
            "schema": {
              "$ref": "#/definitions/CloudError"
            }
          }
        }
```
Please replace the path and returned content according to your case. The returned content should include previous content plus 200 response. 

Full example is here: https://github.com/Azure/azure-powershell/blob/main/src/ContainerInstance/readme.md. Please let me know if you need further help.

**Comment by dorothyhu** [comment]
> Hi @dorothyhu , good news, I have an exact example for your case.
> 
> ```
>   - from: swagger-document
>     where: $.paths["/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.ContainerInstance/containerGroups/{containerGroupName}/start"].post.responses
>     transform: >-
>       return {
>           "202": {
>             "description": "Started - the container group is starting."
>           },
>           "204": {
>             "description": "No content"
>           },
>           "default": {
>             "description": "Error response describing why the operation failed.",
>             "schema": {
>               "$ref": "#/definitions/CloudError"
>             }
>           }
>         }
> ```
> 
> Please replace the path and returned content according to your case. The returned content should include previous content plus 200 response.
> 
> Full example is here: https://github.com/Azure/azure-powershell/blob/main/src/ContainerInstance/readme.md. Please let me know if you need further help.

@BethanyZhou 
image
image
It complained about cannot find the reference "../../../../../common-types/resource-management/v2/types.json#/definitions/ErrorResponse"

**Comment by BethanyZhou** [comment]
Hi @dorothyhu , please use absolute path to replace the relative path.

**Comment by BethanyZhou** [comment]
Please use https://github.com/Azure/azure-rest-api-specs/blob/3d3c5dda9043e697cbdbb4b3264123b5e39470fd/specification/common-types/resource-management/v2/types.json#/definitions/ErrorResponse

The number inside is the commit id where Microsoft.HybridCompute/stable/2021-05-20/HybridCompute.json has merged. At that commit, stable/2021-05-20/HybridCompute.json and definitions/ErrorResponse exist at the same time.
image

**Comment by dorothyhu** [comment]
@BethanyZhou https://github.com/Azure/azure-powershell/pull/16313 this is the new PR. Pls, close the current one after seeing this message

**Pull request closed without merging**
