### PR TITLE
Enabling Edgenode Customization through SubmitAzureHDInsightScriptAct…

### PR DESCRIPTION
**Pull request by nbikhchandani**
…ionCommand

Editing help.xml

Updating indent

Editing ScriptActionClusterNodeType enum name

Adding comment to define what RuntimeScriptActionClusterNodetype is for

Update comment

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nbikhchandani__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nabikhch). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/818/

**Comment by markcowl** [comment]
LGTM once the on demand build passes.

**Pull request merged**
