### PR TITLE
Update documentation for *-AzureRmNetworkInterface cmdlets

### PR DESCRIPTION
**Pull request by johnmic**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@johnmic__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (johnmic). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@deepakrajendranmsft can you take a look?

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by DeepakRajendranMsft** [comment]
@markcowl LGTM

**Pull request merged**
