### PR TITLE
bug fixes for vnet peering and effective nsg

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by DeepakRajendranMsft** [comment]
could you please retrigger the build. seems like an error from jenkins

**Comment by cormacpayne** [comment]
On-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1132/

**Comment by cormacpayne** [comment]
@DeepakRajendranMsft Hey Deepak, the build failed due to a failing test that we have a fix out for in the dev branch, so if you pull from the current dev branch, the issue will be resolved and we can kick off another on-demand build.

**Comment by markcowl** [comment]
@DeepakRajendranMsft Please pull the latest - there is a test fix you need for this PR.

**Comment by DeepakRajendranMsft** [comment]
@markcowl @cormacpayne  I have pulled from Dev and the CI seems to be good now

**Comment by cormacpayne** [comment]
On-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1142/

**Pull request merged**
