### PR TITLE
Adding help for Disaster Recovery Configuration

### PR DESCRIPTION
**Pull request by franktsa**
Adding help info that was previously excluded for Disaster Recovery Configuration.

At least for me, GitHub diff is interspersing changes. Let me know if there isn't a way to see that these changes are isolated additions.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@franktsa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (franktsa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@franktsa we are just about to create the final installer for build - if you can target this at the release branch in the next 5 minutes, we may be able to take it.

**Comment by hovsepm** [comment]
@franktsa @markcowl I've created a PR to Release branch with this changes. Thanks for contribution!

**Comment by hovsepm** [comment]
Re-targeted to release branch in #2017

**Pull request closed without merging**
