### PR TITLE
Fix for 7693: Get-ResourceName is not the name of a cmdlet

### PR DESCRIPTION
**Pull request by deathly809**
## Description

Fixes #7696

Get-ResourceName -> Get-ResourceNameSuffix

## Checklist

- [X] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by markcowl** [comment]
@bganapa please review

**Comment by bganapa** [comment]
@deathly809 Please update the changelogs.md and azurestack.psd1 as well. I thought you mentioned about specifying the output type for the cmdlet? I don't see that change in this list

**Comment by bganapa** [comment]
@deathly809 Also can you please kick off a ps-sign, see if you can make cleaner commit history(avoiding same commit messages and merges..)

**Comment by deathly809** [comment]
@bganapa What change log?  What is purpose of Ps-Sign job exactly?  Shouldn't the CI job be enough?

**Comment by bganapa** [comment]
This one - https://github.com/Azure/azure-powershell/blob/preview/src/StackAdmin/Azs.Fabric.Admin/Module/Azs.Fabric.Admin/ChangeLog.md

Ps-Sign does the packaging.. that part is not validated thru CI... its not a CI gate per se, since you are touching the module version and azurestack.psd1 , we need to run this to make sure the build is good..

**Comment by bganapa** [comment]
ps-sign https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1499/
Looks good to me otherwise

**Comment by bganapa** [comment]
This is good to merge!

**Pull request merged**
