### PR TITLE
add params for New-AzGalleryApplicationVersion

### PR DESCRIPTION
**Pull request by grizzlytheodore**
## Description
adding two new parameters for New-AzGalleryApplicationVersion 
```
[-PackageFileName <string>] and [-ConfigFileName <string>]
```

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
this feature needs to go in the 7/5. but the code merge date was 6/27. We missed it. Is there anyway this can go in there?

**Comment by grizzlytheodore** [comment]
how do i update the changelog when there isn't one in the generation branch?

**Comment by VeryEarly** [comment]
test cases need to be re-recorded after API version upgrade

**Comment by grizzlytheodore** [comment]
all the tests?

**Comment by grizzlytheodore** [comment]
@VeryEarly 
when I try to run the tests I get this error: 
PS C:\Repositories\ps\src\Compute\Compute.Autorest> .\test-module.ps1 -record get-azgalleryapplication
Creating isolated process...

Creating ResourceGroup RGComputeTestnfr5c0pt
Name                  Location ProvisioningState
----                  -------- -----------------
testpwshellcompute    eastus   Succeeded
RGComputeTestnfr5c0pt eastus   Succeeded
Pester v4.10.1
Executing all tests in 'C:\Repositories\ps\src\Compute\Compute.Autorest\test' matching test name get-azgalleryapplication     

Executing script C:\Repositories\ps\src\Compute\Compute.Autorest\test\Get-AzGalleryApplication.Tests.ps1
Running 'record' mode...
Recording to C:\Repositories\ps\src\Compute\Compute.Autorest\test\Get-AzGalleryApplication.Recording.json

  Describing Get-AzGalleryApplication
    [-] Error occurred in Describe block 0ms
      **FileLoadException: Assembly with same name is already loaded
      CmdletInvocationException: Assembly with same name is already loaded
      CommandNotFoundException: The 'New-AzGallery' command was found in the module 'Az.Compute', but the module could not be loaded. For more information, run 'Import-Module Az.Compute'.**
      at <ScriptBlock>, C:\Repositories\ps\src\Compute\Compute.Autorest\test\Get-AzGalleryApplication.Tests.ps1: line 19      
      at Invoke-Blocks, C:\Repositories\ps\src\Compute\Compute.Autorest\generated\modules\Pester\4.10.1\Functions\SetupTeardown.ps1: line 135
      at Invoke-TestGroupSetupBlocks, C:\Repositories\ps\src\Compute\Compute.Autorest\generated\modules\Pester\4.10.1\Functions\SetupTeardown.ps1: line 121
      at DescribeImpl, C:\Repositories\ps\src\Compute\Compute.Autorest\generated\modules\Pester\4.10.1\Functions\Describe.ps1: line 209


I've tried adding "Import-Module Az.Compute" in the "BeforeAll" block, and also the "It" block, also I've tried importing it in terminal before running the test, but they all fail the same. What do I do here?

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
