### PR TITLE
Update sfmc sdk to 2024_04_01

### PR DESCRIPTION
**Pull request by mwesigwaguma**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by msJinLei** [comment]
@mwesigwaguma byDefault The change in this PR will target to the next major release. Have you submitted a breaking change request? Please refer to the bot about how to do it.

**Comment by NoriZC** [comment]
@mwesigwaguma Seems there are many breaking changesd existed in this PR. For product maintanance, Azure PowerShell Modules only accept breaking changes in Major Releases.

**Comment by mwesigwaguma** [comment]
> @mwesigwaguma Seems there are many breaking changesd existed in this PR. For product maintanance, Azure PowerShell Modules only accept breaking changes in Major Releases. You should firstly raise another pr to announce them before next Major Release (Nov 2024) if you haven't done so.

@NoriZC Do you have an example PR for announcing breaking changes. Is it just updating the changelog.md file with a description of the upcoming changes?

**Comment by NoriZC** [comment]
Please follow [this guidance ](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/devguide/azps/breaking-change/breaking-changes-process#how-to-do-breaking-changes) to introduce breaking changes.

**Comment by mwesigwaguma** [comment]
> Please follow [this guidance ](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/devguide/azps/breaking-change/breaking-changes-process#how-to-do-breaking-changes) to introduce breaking changes.



> Please follow [this guidance ](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/devguide/azps/breaking-change/breaking-changes-process#how-to-do-breaking-changes) to introduce breaking changes.



> Please follow [this guidance ](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/devguide/azps/breaking-change/breaking-changes-process#how-to-do-breaking-changes) to introduce breaking changes.



> @mwesigwaguma Seems there are many breaking changesd existed in this PR. For product maintanance, Azure PowerShell Modules only accept breaking changes in Major Releases. You should firstly raise another pr to announce them before next Major Release (Nov 2024) if you haven't done so.



> @mwesigwaguma Seems there are many breaking changesd existed in this PR. For product maintanance, Azure PowerShell Modules only accept breaking changes in Major Releases. You should firstly raise another pr to announce them before next Major Release (Nov 2024) if you haven't done so.



> @mwesigwaguma Seems there are many breaking changesd existed in this PR. For product maintanance, Azure PowerShell Modules only accept breaking changes in Major Releases. You should firstly raise another pr to announce them before next Major Release (Nov 2024) if you haven't done so.

@NoriZC Is there a way to merge these changes earlier ? We have more updates pending that are dependent on this PR. Waiting until Nov 2024 would put us behind by another 5/6 months since we release a new api-version every month. If I broke this into two seperate Pull requests would the changes be accepted for a public preview version

**Comment by NoriZC** [comment]
@mwesigwaguma Yes. If the updates is splitted into 2 PRs:
- For the one without breaking changes, we can merge it once all CI s passed.
- For the one including breaking changes, we can target the features to a preview release. Please refer to [this doc](https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azps_docs/preview_release_process) to know better about our preview release process.

If you have more concern please feel free to reach out offline if you have more question on the splitting step.

**Pull request closed without merging**
