### PR TITLE
fix issue that user MSI doens't work in Azure Function

### PR DESCRIPTION
**Pull request by erich-wang**
Detail info please check: https://github.com/Azure/azure-powershell/issues/9479

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by erich-wang** [comment]
The updated artifact is at https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/500/artifact/artifacts/

**Comment by eugeneniemand** [comment]
@cormacpayne is this live yet for the general public as I'm still experiencing the issues mentioned in #9479 using a user assigned managed identity. Can someone please update the docs with a working example?

**Comment by eamonoreilly** [comment]
Yes - I validated this on the latest Az module in Azure Functions. You can see an example on https://docs.microsoft.com/en-us/powershell/module/az.accounts/connect-azaccount?view=azps-2.7.0#examples (Example 7).

**Pull request merged**
