### PR TITLE
Add new options to Wait-AzureRmHDInsightJob

### PR DESCRIPTION
**Pull request by pattipaka**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pattipaka__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (supattip). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@pattipaka Your tests are not running as part of check-in, please add your test assembly here:  https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L91  as part of this PR.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/920/

**Comment by markcowl** [comment]
@pattipaka There are merge conflicts, please update

**Comment by markcowl** [comment]
new on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/923/

**Comment by pattipaka** [comment]
The issue seems to be with original branch itself. http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/924/consoleFull

Looks like kore poull requests may be effected due to this?
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/921/consoleFull

**Comment by pattipaka** [comment]
FYI, the changes I made are limited to HDInsight solution and it doesn't effect any other module.

**Pull request merged**
