### PR TITLE
Removed default population of access policies

### PR DESCRIPTION
**Pull request by hansenms**
## Description

Removed the default population of access policies based on the signed in user.

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by wyunchi-ms** [comment]
Hi @hansenms , the modification looks goods to me. But I still have some small doubts. Could you kindly explan them for me?
1. Is this PR to fix some issues?
2. Could you please add a test case for this cmdlet?

**Comment by hansenms** [comment]
@wyunchi-ms thanks for getting back to us.

It is not really a fix as such. We used to populate an access  policy object with the object id of the signed-in powershell user, assigning that user access to the data plane of our service. We have now implemented Azure RBAC for the data plane of our service and thus the access policy object can/should be left empty and users will assign access using Azure RBAC. I understand the knee-jerk, "can we add a test", but I am not sure there is much in terms of a meaningful test that can be added. Users could run the command before with no policies and they still can, we just don't prepopulate things any more as it is no longer needed.

One could actually argue that we should not have prepopulated this in the past (and we don't for Azure CLI), so this change brings the behavior of the PowerShell cmdlets in line with the Azure CLI.

Hope this makes sense.

**Comment by hansenms** [comment]
@wyunchi-ms gentle ping on this.

**Comment by wyunchi-ms** [comment]
Hi @hansenms , sorry for late response. Next time you can change the label to `needs-review` then I can filter it quickly. This make sense to me. I have merged it.

**Comment by hansenms** [comment]
@wyunchi-ms, no worries. Thanks for the hint on the label!

**Pull request merged**
