### PR TITLE
Cognitive Services PowerShell Update to RP Version 2021-10-01

### PR DESCRIPTION
**Pull request by yangyuan**
## Description

Cognitive Services PowerShell Update to RP Version 2021-10-01

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by yangyuan** [comment]
Note, there is one UT not working. Debugging shows the issue is in Network Command. I'm working on it.

**Comment by isra-fel** [comment]
Hey, this branch has conflicts that must be resolved before CI can run.

**Comment by isra-fel** [comment]
Hey @yangyuan for public API changes to cmdlets:
 a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr)

**Comment by yangyuan** [comment]
just an update that the review link is https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1083

**Comment by yangyuan** [comment]
@isra-fel please help to review the PR. Cmdlet review has been completed.

**Comment by isra-fel** [comment]
Great. Jin Lei is going to review this PR as she's the scrum master of Dec release.

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
