### PR TITLE
Switch to SDK use in ResourceGroup Deployments cmdlets

### PR DESCRIPTION
**Pull request by Xynoclafe**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by filizt** [comment]
>     [Cmdlet("Get", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "ResourceGroupDeploymentOperation"), OutputType(typeof(PSObject))]

This needs to be PsDeploymentOperation since we're not returning the generic PS object anymore.

---
Refers to: src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentOperationCmdlet.cs:30 in 603df06. [](commit_id = 603df06022cab31687dd911f50e2c18cf762ee9c, deletion_comment = False)

**Comment by filizt** [comment]
> 

Looks like we don't need this parameter any more. Could you add a deprecation attribute noting that it will be retired?

---
Refers to: src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentOperationCmdlet.cs:47 in 603df06. [](commit_id = 603df06022cab31687dd911f50e2c18cf762ee9c, deletion_comment = False)

**Comment by filizt** [comment]
>     [Cmdlet("Get", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "ResourceGroupDeploymentOperation"), OutputType(typeof(PSObject))]

Is there any test coverage for this cmdlet? If not, it might be good if we add one.

---
Refers to: src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentOperationCmdlet.cs:30 in 603df06. [](commit_id = 603df06022cab31687dd911f50e2c18cf762ee9c, deletion_comment = False)

**Comment by Xynoclafe** [comment]
> > ```
> > [Cmdlet("Get", ResourceManager.Common.AzureRMConstants.AzureRMPrefix + "ResourceGroupDeploymentOperation"), OutputType(typeof(PSObject))]
> > ```
> 
> Is there any test coverage for this cmdlet? If not, it might be good if we add one.
> 
> Refers to: src/Resources/ResourceManager/Implementation/ResourceGroupDeployments/GetAzureResourceGroupDeploymentOperationCmdlet.cs:30 in [603df06](https://github.com/Azure/azure-powershell/commit/603df06022cab31687dd911f50e2c18cf762ee9c). [](commit_id = [603df06](https://github.com/Azure/azure-powershell/commit/603df06022cab31687dd911f50e2c18cf762ee9c), deletion_comment = False)

We already have test coverage for this cmdlet.

**Comment by Xynoclafe** [comment]
> please regenerate help due to output type change

The help file already reflects the new output type

**Comment by Xynoclafe** [comment]
This is not considered a breaking change right?

**Comment by VeryEarly** [comment]
> > please regenerate help due to output type change
> 
> The help file already reflects the new output type

Output type had been changed and is still PSObject in help:
https://github.com/Xynoclafe/azure-powershell/blob/xynoclafe/deploymentsSDKfix/src/Resources/Resources/help/Get-AzResourceGroupDeploymentOperation.md

**Pull request merged**
