### PR TITLE
Task adl fixencodingparameter

### PR DESCRIPTION
**Pull request by rahuldutta90**
## Description

Change FileSystemCmdletProviderEncoding usage to System.Text.Encoding

https://github.com/Azure/azure-powershell/issues/5742

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@rahuldutta90 we're going to close this PR until @MiYanni creates the new branch (some time in the next week) and then we will target this PR at that branch rather than the `preview` branch, which would introduce a breaking change into the desktop cmdlets

**Comment by MiYanni** [comment]
@rahuldutta90 These changes will be in the `dev` branch we are **actually** creating end of this week/start of next week. I just don't want any of these changes to be in the AzureRM codebase. They should strictly be for Az.

**Comment by cormacpayne** [comment]
@rahuldutta90 @MiYanni changed target branch from `preview` to `dev`

**Comment by cormacpayne** [comment]
@rahuldutta90 ping on the above comments

**Comment by rahuldutta90** [comment]
@cormacpayne Apologies for delay. Will take a look at it.

**Comment by MiYanni** [comment]
@rahuldutta90 These changes can be put into your cmdlets now. So, once you have the build working properly, we can add merge this and have the changes in Az. Sorry for the delay.

**Comment by rahuldutta90** [comment]
@MiYanni @cormacpayne Fixed the conflicts, please take a look. Sorry for this delay.

**Pull request merged**
