### PR TITLE
Add parameter reference support for NewAzureResourceGroupDeployment

### PR DESCRIPTION
**Pull request by linweigao**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@linweigao__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jogao). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@vivsriaus Can someone on your team review this PR?  Thanks.

**Comment by vivsriaus** [comment]
@markcowl Spoke to @linweigao He's going to ensure we have test coverage for the changes, and that we haven't regressed.

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/325/

**Comment by linweigao** [comment]
I will send out a different one. The pull request includes some changes from azure/dev. It is wrong.

**Pull request closed without merging**
