### PR TITLE
Az.codesigning - fix regressions

### LINKED ISSUE #26764: Az.Codesigning 0.2.0 Invoke-AzCodeSigningCIPolicySigning Method not found
### Description

The module 0.2.0 of Az.CodeSigning fails, while 0.1.2 works as expected.

it fails on the Method not found: 'System.Threading.Tasks.Task`1<Azure.CodeSigning.CertificateProfileSignOperation>
                 Azure.CodeSigning.CertificateProfileClient.StartSignAsync(System.String, System.String,
                 Azure.CodeSigning.Models.SignRequest, System.String, System.Threading.CancellationToken)'.

Dotnet 8/9 are installed as SDK as well as the latest AZ modules.

### Issue script & Debug output

```PowerShell
Invoke-AzCodeSigningCIPolicySigning -AccountName 'removed' -ProfileName 'removed' -EndpointUrl 'https://weu.codesigning.azure.net' -Path C:\temp\ci\test.bin -Destination c:\temp\ci\signed.bin  -TimeStamperUrl 'http://timestamp.acs.microsoft.com' -Verbose -Debug |clip
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - InvokeCIPolicySigning begin processing with ParameterSet 'ByAccountProfileNameParameterSet'.
DEBUG: 17:30:11 - using account id 'user@domain.ext'...
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplaySecretsWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [EnableErrorRecordsPersistence], Module = [], Cmdlet = []. Returning default value [False].
Invoke-AzCodeSigningCIPolicySigning: One or more errors occurred. (Method not found: 'System.Threading.Tasks.Task`1<Azure.CodeSigning.CertificateProfileSignOperation> Azure.CodeSigning.CertificateProfileClient.StartSignAsync(System.String, System.String, Azure.CodeSigning.Models.SignRequest, System.String, System.Threading.CancellationToken)'.)
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplayBreakingChangeWarning], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [DisplayRegionIdentified], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [CheckForUpgrade], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: AzureQoSEvent:  Module: Az.CodeSigning:0.2.0; CommandName: Invoke-AzCodeSigningCIPolicySigning; PSVersion: 7.4.6; IsSuccess: False; Duration: 00:00:00.1061904; SanitizeDuration: 00:00:00.0000517; Exception: One or more errors occurred. (Method not found: 'System.Threading.Tasks.Task`1<Azure.CodeSigning.CertificateProfileSignOperation> Azure.CodeSigning.CertificateProfileClient.StartSignAsync(System.String, System.String, Azure.CodeSigning.Models.SignRequest, System.String, System.Threading.CancellationToken)'.);
DEBUG: 17:30:11 - [ConfigManager] Got nothing from [EnableDataCollection], Module = [], Cmdlet = []. Returning default value [True].
DEBUG: 17:30:11 - InvokeCIPolicySigning end processing.
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      7.4.6
PSEdition                      Core
GitCommitId                    7.4.6
OS                             Microsoft Windows 10.0.26100
Platform                       Win32NT
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
WSManStackVersion              3.0
```

### Module versions

```PowerShell
ModuleType Version    PreRelease Name                                ExportedCommands
---------- -------    ---------- ----                                ----------------
Script     3.0.4                 Az.Accounts                         {Add-AzEnvironment, Clear-AzConfig, Clear-AzContex...
Script     0.2.0                 Az.CodeSigning                      {Get-AzCodeSigningCertChain, Get-AzCodeSigningCust...
```

### Error output

```PowerShell
Message        : Method not found: 'System.Threading.Tasks.Task`1<Azure.CodeSigning.CertificateProfileSignOperation>
                 Azure.CodeSigning.CertificateProfileClient.StartSignAsync(System.String, System.String,
                 Azure.CodeSigning.Models.SignRequest, System.String, System.Threading.CancellationToken)'.
StackTrace     :    at Azure.CodeSigning.Client.CryptoProvider.AzCodeSignContext.<>c__DisplayClass32_0.<<InitializeChai
                 nAsync>b__0>d.MoveNext()
                    at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[TStateMachine](TStateMachine&
                 stateMachine)
                    at Azure.CodeSigning.Client.CryptoProvider.AzCodeSignContext.<>c__DisplayClass32_0.<InitializeChain
                 Async>b__0()
                    at Polly.AsyncPolicy.<>c__DisplayClass13_0`1.<ExecuteAsync>b__0(Context _, CancellationToken _)
                    at Polly.Retry.AsyncRetryEngine.ImplementationAsync[TResult](Func`3 action, Context context,
                 CancellationToken cancellationToken, ExceptionPredicates shouldRetryExceptionPredicates,
                 ResultPredicates`1 shouldRetryResultPredicates, Func`5 onRetryAsync, Int32 permittedRetryCount,
                 IEnumerable`1 sleepDurationsEnumerable, Func`4 sleepDurationProvider, Boolean
                 continueOnCapturedContext)
                    at Polly.AsyncPolicy.ExecuteAsync[TResult](Func`3 action, Context context, CancellationToken
                 cancellationToken, Boolean continueOnCapturedContext)
                    at
                 Azure.CodeSigning.Client.CryptoProvider.AzCodeSignContext.InitializeChainAsync(CancellationToken
                 cancelToken)
Exception      : System.MissingMethodException
InvocationInfo : {Invoke-AzCodeSigningCIPolicySigning}
Line           : Invoke-AzCodeSigningCIPolicySigning -AccountName 'removed' -ProfileName 'removed' -EndpointUrl
                 'https://weu.codesigning.azure.net/' -Path C:\temp\ci\test.bin -Destination c:\temp\ci\signed.bin
                 -TimeStamperUrl 'http://timestamp.acs.microsoft.com'
Position       : At line:1 char:1
                 + Invoke-AzCodeSigningCIPolicySigning -AccountName 'removed' -ProfileName ' …
                 + ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
HistoryId      : 1
```

### PR DESCRIPTION
**Pull request by Jaxelr**
## Description

This PR fixes #26764. The current Azure.CodeSigning.Client.CryptoProvider  package has been deprecated and rebranded into Azure.Developer.TrustedSigning.CryptoProvider. The functionality is kept, with minor new class names. It also fixes a duplicate error on the Get Eku list.

Tagging @janielMartell for awareness.

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @Jaxelr , did you try to build the project in your local environment? dependencies don't look correct in pipeline build.

**Comment by Jaxelr** [comment]
@VeryEarly so I did, and didnt got this error, but Ill take a look, thanks for the callout.

**Comment by Jaxelr** [comment]
I added back the Polly dependency. That should resolve this issue. Looks like I cant build this pipeline unless I get your intervention? Ill still try.

**Comment by VeryEarly** [comment]
> I added back the Polly dependency. That should resolve this issue. Looks like I cant build this pipeline unless I get your intervention? I'll try though.

please see new error message 
D:\a\_work\1\s\src\CodeSigning\CodeSigning.Test\CodeSigning.Test.csproj : error NU1603: Microsoft.Azure.PowerShell.Cmdlets.CodeSigning depends on Polly (>= 7.2.3.1) but Polly 7.2.3.1 was not found. An approximate best match of Polly 7.2.4 was resolved.

**Comment by Jaxelr** [comment]
Silly me, thank you so much @VeryEarly I'll fix it right now.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
