### PR TITLE
added supported TrafficAnalyticsInterval values in documentation for Set-AzNetworkWatcherConfigFlowLog

### PR DESCRIPTION
**Pull request by MariachiForHire**
## Description

I added the supported values in the documentation for the TrafficAnalyticsInterval parameter in the Set-AzNetworkWatcherConfigFlowLog module.

ErrorCode: InvalidFlowLogTrafficAnalyticsInterval
ErrorMessage: Invalid traffic analytics interval 5. Supported values are 10 and 60 minutes.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Thanks for the contribution : )
@sayghosh could you help review the change or suggest someone else? Thank you!

**Comment by sayghosh** [comment]
The change looks good to me.

**Review by sayghosh — APPROVED** [review]

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
