### PR TITLE
Backup Support for SQL Server in Azure VM

### PR DESCRIPTION
**Pull request by siddharth7**
## Description
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/203

## Checklist

- [X] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [X] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@siddharth7 You have static analysis failures.

**Comment by MiYanni** [comment]
@vladimir-shcherbakov Please reassign to someone else. Thanks.

**Comment by vladimir-shcherbakov** [comment]
@siddharth7 @MiYanni  Could you please point me to the final version of the design review (PowerShell-help style syntax descriptions of all new and changed cmdlets)?

**Comment by siddharth7** [comment]
@vladimir-shcherbakov https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/203

**Comment by vladimir-shcherbakov** [comment]
@siddharth7  
1. I can't find implementation of the Disable-AzRecoveryServicesBackupAutoProtection cmdlet
2. Could you also add test-cases for all new cmdlets including piping scenarios?

**Comment by siddharth7** [comment]
@vladimir-shcherbakov 
1. The implementation of Disable-AutoProtection has a dependency on newer version of SDK which was published yesterday. We need to test the new sdk before updating SDK version in our module.
2. All the new cmdlets do have the tests except Enable-AutoProtection. Writing a test for it requires Disable-AutoProtection too. But the cmdlet has been tested by the team as of now.
3. This is more of a preview release as of now where we want to get basic functionality out. SDK update and piping scenarios will be taken up in the next release.

**Comment by vladimir-shcherbakov** [comment]
signing: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/142/

**Pull request merged**
