### PR TITLE
[Temp PR to test playback. Do not merge] Dropped more skips

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@EvgenyAgafonchikov would you mind taking a look at the build failure? It looks like it's coming from the `TestCortexCRUD` test.

**Comment by EvgenyAgafonchikov** [comment]
@cormacpayne, this is failure that I have in playback mode only. Live mode [works as expected](https://azuresdkci.westus2.cloudapp.azure.com/view/az-ps-network-tests/job/ps-network-test-brooklynft/33/artifact/NetworkTests.htm)
This is just PR to check that it is not local issue on my machine.

Contacted test owners, @Nilambari is working on updating this: https://github.com/Azure/azure-powershell/pull/7378

**Comment by cormacpayne** [comment]
@Nilambari do we need to make the same changes in this PR as we did in https://github.com/Azure/azure-powershell/pull/7388 ?

**Comment by EvgenyAgafonchikov** [comment]
closing as temp for now

**Pull request closed without merging**
