### PR TITLE
Packet Capture for VpnGateway and VpnConnection

### PR DESCRIPTION
**Pull request by jiaczh**
## Description

I add four extra commands for two resources under network - > Vpn Gateway and VPN connection, stop/start packet capture for each resource, 

## Checklist

- [ x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ x] The title of the PR is clear and informative
- [ x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ x] If applicable, the changes made in the PR have proper test coverage
- [ x] For public API changes to cmdlets:
    - [x ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @jiaczh , is there any design issue for this PR?

**Comment by isra-fel** [comment]
Kindly ping @jiaczh

**Comment by jiaczh** [comment]
> Kindly ping @jiaczh

Hi @isra-fel ,

Sorry for the late reply,  When will the SDK be updated here? I saw that my build is failing because of some class is not there(should be there if the june SDK is present)

**Comment by jiaczh** [comment]
> Hi @jiaczh , is there any design issue for this PR? And this CI is failed, please take a look.

Hi @wyunchi-ms , I have finished testing locally for this PR , how ever I don't know why the build is failing, since I build the June SDK locally it does not have build problem on local machine, What is the process of putting the according SDK into this branch? thanks!

**Comment by msJinLei** [comment]
@jiaczh Could you provide the cmdlet review linke for this PR?

**Comment by jiaczh** [comment]
> @jiaczh Could you provide the cmdlet review linke for this PR?

@msJinLei  Hi , here is the link https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/660

**Comment by MikhailTryakhov** [comment]
@jiaczh  code complete date is passed already, please retarget to master

**Pull request closed without merging**
