### PR TITLE
Added make policy consistent parameter

### PR DESCRIPTION
**Pull request by sambitratha**
## Description

Added a parameter in Set-AzRecoveryServicesBackupProtectionPolicy to make it consistent

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by VeryEarly** [comment]
Hi @sambitratha ,

there are test cases failed and signature issue detected during static analysis in CI, please take a look.

**Comment by isra-fel** [comment]
kindly ping @sambitratha

**Comment by isra-fel** [comment]
@sambitratha Closing the issue for now. Please feel free to reopen to continue. Thanks!

**Pull request closed without merging**
