### PR TITLE
Az.DataFactory update to include Global Parameters

### PR DESCRIPTION
**Pull request by Ceespino**
## Description

Added global parameters to Data Factory

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by Ceespino** [comment]
> * Can you help me understand where this "global parameters" comes from?
> * If it's needed, it should be called "GlobalParameter"
> * Please update and check in Set-AzDataFactoryV2.md only

Global Parameters is a new property in the Data Factory entity. It is basically a dictionary that contains global constants that can be referenced and used by its subresources.

I think it should be called "Global Parameters" since that's the name that it is refered to in the SDK, factory entity and in our UI where our customers can author and use them.

I also modified the Get-AzDataFactoryV2 cmdlet, so I will keep the update there as well. Also, I ran the doc tool and it generated all those changes, I thought that maybe they were outdated, despite that, should I only update the Get and Set cmdlets?

**Comment by Ceespino** [comment]
@shawnxzq to review the changes and visibility.

**Comment by VeryEarly** [comment]
> > * Can you help me understand where this "global parameters" comes from?
> > * If it's needed, it should be called "GlobalParameter"
> > * Please update and check in Set-AzDataFactoryV2.md only
> 
> Global Parameters is a new property in the Data Factory entity. It is basically a dictionary that contains global constants that can be referenced and used by its subresources.
> 
> I think it should be called "Global Parameters" since that's the name that it is refered to in the SDK, factory entity and in our UI where our customers can author and use them.
> 
> Ran the tool again to only update the Get and Set AzDataFactoryV2 cmdlet since those are the ones affected.

Please follow powershell convention and use singularity for parameter names 
https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/design-guidelines/parameter-best-practices.md

**Comment by Ceespino** [comment]
> > > * Can you help me understand where this "global parameters" comes from?
> > > * If it's needed, it should be called "GlobalParameter"
> > > * Please update and check in Set-AzDataFactoryV2.md only
> > 
> > 
> > Global Parameters is a new property in the Data Factory entity. It is basically a dictionary that contains global constants that can be referenced and used by its subresources.
> > I think it should be called "Global Parameters" since that's the name that it is refered to in the SDK, factory entity and in our UI where our customers can author and use them.
> > Ran the tool again to only update the Get and Set AzDataFactoryV2 cmdlet since those are the ones affected.
> 
> Please follow powershell convention and use singularity for parameter names
> https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/design-guidelines/parameter-best-practices.md

Updated name to GlobalParameterDefinition

**Comment by Ceespino** [comment]
@VeryEarly Can we include this in the next release please? (7/14)

**Comment by VeryEarly** [comment]
yes we can, merged.

**Comment by shawnxzq** [comment]
Looks good to me, thanks @Ceespino

**Pull request merged**
