### PR TITLE
Fix failing Cortex feature test

### PR DESCRIPTION
**Pull request by Nilambari**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by Nilambari** [comment]
Somehow test fails in Playback but passes when run in record mode, so making test category to LiveOnly.

**Comment by Nilambari** [comment]
@maddieclayton  Can you Please take a look and help generate private module for Network? Thanks!

**Comment by maddieclayton** [comment]
@Nilambari If you mark this test as LiveOnly it will basically never be run, and we need test coverage for those cmdlets.  Please talk further with the owner of this test so we can get a fix.

**Comment by Nilambari** [comment]
Ok. Fixing the test and rerecording.

**Comment by ritwikbasu** [comment]
@maddieclayton - the issue with this playback is that we have a code chunk that calls into Storage APIs to create a storage blob on the fly. This call fails in playback with Storage Blob not found. Apparently, these storage calls only work in "LiveOnly" mode.

There are two options we can use to unblock this:
1. Mark the test "LiveOnly" as Nilambari suggested.
2. Disable the code chunk for the storage calls and check the test in as a check-in test.

Please let us know your thoughts on this.

**Comment by maddieclayton** [comment]
Closing in favor of other PR.

**Pull request closed without merging**
