### PR TITLE
Fix New and Set ResourceLock issue by using Scope level parameter set

### PR DESCRIPTION
**Pull request by gandhiniraj**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@gandhiniraj__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by vivsriaus** [comment]
@gandhiniraj Do we need to update our help accordingly?

**Comment by vivsriaus** [comment]
LGTM

**Comment by gandhiniraj** [comment]
Thanks Vivek 
Re: help - we don't need any help update related to this change

**Pull request merged**
