### PR TITLE
Updated nuget package for officially publushed

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description

Replaced locally built SDKs with officially published one

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @MikhailTryakhov it was due to our recent reorgnization of repo authorization.
I've sent you an invitation to the right team. Please check your email. Thanks

**Comment by MikhailTryakhov** [comment]
Thx, it passed now, @isra-fel can you please review it and approve?

**Comment by MikhailTryakhov** [comment]
BTW, I didn't receive any email :(

**Review by isra-fel — APPROVED** [review]
LGTM.
@MikhailTryakhov I just checked your name is already on the members list so I guess it doesn't need a confirmation ;)

**Pull request merged**
