### PR TITLE
[fixes #103630362] Add version check scripts to Profile module

### PR DESCRIPTION
**Pull request by jianghaolu**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jianghaolu__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@jianghaolu You need to include the recorded mocks

**Comment by jianghaolu** [comment]
@azuresdkci retest this please

**Comment by jianghaolu** [comment]
@azuresdkci retest this please

**Comment by jianghaolu** [comment]
on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/227/

**Pull request merged**
