### PR TITLE
modifying Backup Time header to display UTC

### PR DESCRIPTION
**Pull request by hiaga**
## Description

modify  Get-AzRecoveryServicesBackupProtectionPolicy table output to specifiy Backup time is in UTC

## Checklist

- [Yes] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [Yes] The title of the PR is clear and informative
- [Yes] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [Yes] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [Yes] If applicable, the changes made in the PR have proper test coverage
- [N/A] For public API changes to cmdlets:
    - [N/A] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [N/A] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @hiaga what's the status of this PR?
Are you going to add more or you'd just like to update the table lables?

**Comment by hiaga** [comment]
Hi @isra-fel please do not merge this PR yet, changes aren't working. I just want to update the table labels.

**Comment by isra-fel** [comment]
OK. Let me know when it's ready please

**Comment by hiaga** [comment]
@isra-fel  Please go ahead with this PR. Regards.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
