### PR TITLE
update single pass encryption test to run as a check-in

### PR DESCRIPTION
**Pull request by ejarvi**
## Description

Updates the existing single pass encryption test to run as a check-in test, and updates the name of the key vault provider so that it will be properly loaded in the CI test environment prior to test execution.   

## Checklist

- [X] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [N/A] For public API changes to cmdlets:
    - [N/A] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [N/A] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@ejarvi Hey Eric, the build is failing because the `New-AzureRmKeyVault` was unable to be found. This is because the `ComputeTestController` class is not importing the `AzureRM.KeyVault` module when defining all scripts and modules to load [in this section](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute.Test/Common/ComputeTestController.cs#L150-L163). If you add that module to the list, the test should pass.

**Comment by ejarvi** [comment]
@cormacpayne Thank you for the pointer!  Trying again with this line added.

**Comment by cormacpayne** [comment]
@ejarvi looks like the version of [`Microsoft.Azure.Management.KeyVault`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute.Test/Commands.Compute.Test.csproj#L72-L75) used in the Compute test project wasn't updated to `2.4.1-alpha`. You'll need to update it in that file as well as the [`packages.config`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/Commands.Compute.Test/packages.config#L10) file.

**Comment by cormacpayne** [comment]
@ejarvi Hey Eric, when you get the chance to re-record the failing test, would you also pull in the latest changes from the `preview` branch to resolve the merge conflict?

**Comment by ejarvi** [comment]
Yes, thanks for the heads up.

**Comment by maddieclayton** [comment]
@ejarvi Closing for inactivity - please reopen when you have a change to rerecord the failing test and fix merge conflicts (feel free to ping me with questions or if you have issues reopening the PR).

**Pull request closed without merging**
