### PR TITLE
Add EnableTcpReset property to Load Balancer

### PR DESCRIPTION
**Pull request by dumahesh-msft**
## Description

Added EnableTcpReset property to LoadBalancer.
Also added idle timeout in a couple of places and https protocol for the probe which have existed for sometime but weren't part of powershell.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@dumahesh-msft Please fix merge conflicts and failing network test: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/7011/artifact/src/Publish/TestResults/FailingTests/Microsoft.Azure.Commands.Network.Test.dll.html

**Comment by number213** [comment]
Please rebase and target https://github.com/Azure/azure-powershell/tree/network-september-release

**Comment by number213** [comment]
@dumahesh-msft @maddieclayton I've added those changes to my PR with replacement of LoadBalancer with generated code

**Comment by maddieclayton** [comment]
Closing per @number213 's comment

**Pull request closed without merging**
