### PR TITLE
Add FindResourceGroupCmdlet

### PR DESCRIPTION
**Pull request by chidmdxx**
Adds the Find-ResourceGroup cmdlet, unit test, session recording and updates the xml help file

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by chidmdxx** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
@chidmdxx please address unit test failure

**Comment by markcowl** [comment]
@chidmdxx syntax error in ps1 script is causing the current failures

**Comment by chidmdxx** [comment]
@markcowl thanks, just pushed the changes

**Pull request merged**
