### PR TITLE
SQL VM AKV Integration in Azure SDK Release 0.9.8

### PR DESCRIPTION
**Pull request by OJDUDE**
Retarget pull request 751 to release branch. See pull request details here https://github.com/Azure/azure-powershell/pull/751

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@OJDUDE__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
On demand job is here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/174/

**Comment by OJDUDE** [comment]
Thanks for the update. I don’t have access to the links yet. I am still getting access to them. I will wait for the update results.

**Comment by OJDUDE** [comment]
Resolved failed test. Please schedule the change for test run please.

**Comment by OJDUDE** [comment]
Thanks folks for kicking this test. It all passed. Please let me know when it is merged.

**Comment by OJDUDE** [comment]
Can you please provide an ETA when this be merged?

**Comment by ljhljh235** [comment]
On demand job here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/182/

**Comment by OJDUDE** [comment]
Is this being tested again?

**Comment by OJDUDE** [comment]
I see this is a check-in validation job.

**Comment by OJDUDE** [comment]
Build completed without errors. Please let us know when this is merged.

**Comment by ljhljh235** [comment]
Merging. Thanks!!

**Pull request merged**
