### PR TITLE
[DataFactory]improve documentation for cmdlet New-AzDataFactoryV2LinkedServiceEncryptedCredential

### PR DESCRIPTION
**Pull request by xumou-ms**
## Description

improve documentation for cmdlet New-AzDataFactoryV2LinkedServiceEncryptedCredential

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @xumou-ms did you met any problem in Windows PowerShell or PowerShell below 7.0? Could you submit an issue if you did? Because we are still supporting those platforms.

**Comment by isra-fel** [comment]
@hvermis could you help review the help doc of `New-AzDataFactoryV2LinkedServiceEncryptedCredential`?
Thanks

**Comment by xumou-ms** [comment]
Hello @isra-fel. To meet Azure compliance requirements, we need to remove SSL self-signed cert from Self-Hosted IR. Which causes the underlying implementation isn't supported by .NET Standard 2.0. But .NET Core 3.1 can support that. So, PowerShell 7 is necessary.

**Comment by isra-fel** [comment]
> Hello @isra-fel. To meet Azure compliance requirements, we need to remove SSL self-signed cert from Self-Hosted IR. Which causes the underlying implementation isn't supported by .NET Standard 2.0. But .NET Core 3.1 can support that. So, PowerShell 7 is necessary.

Got it. I suppose it would be better if we could do the check in code as well, so the cmdlet can fall fast.

BTW you could use the snippet `$PSVersionTable.PSVersion -lt "7.0.0"` to tell the version.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
