### PR TITLE
[DO NOT MERGE] PowerShell PR for SiteRecovery (moving to swagger based sdk and deprecating oldmodel cmdlets)

### PR DESCRIPTION
**Pull request by avneeshrai**
Intent is to get early feedback. 

PR reflects:
1)	Changes in SiteRecovery solution to move to corresponding swagger based sdks (not yet public).
2)	Deprecating old-model cmdlets and objects as discussed in the attached thread.
3)	Needed automation and test JSONs.

Please note: Build is RED as development has been done with a private swagger based nuget for SiteRecovery.
(Swagger based nuget for SiteRecovery is not yet public and we are working on it in parallel)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@avneeshrai the build is failing because you are referencing a NuGet package that doesn't seem to exist

`Microsoft.Azure.Management.RecoveryServices.SiteRecovery`

**Comment by avneeshrai** [comment]
@cormacpayne As mentioned in the description of the PR Microsoft.Azure.Management.RecoveryServices.SiteRecovery is swagger based nuget for SiteRecovery that is still not public yet and we are working on that in parallel. Code changes in the PR are done with a private instance of nuget. We are expecting early feedbacks from your end here :)
Would also add you to the corresponding mail thread as well

**Comment by avneeshrai** [comment]
Let me know if there exists is a way to make build green with Private nugets?
Else it should be fine I guess  as our intent is just to have code reviewed for early inputs at this point?

**Comment by markcowl** [comment]
@avneeshrai Given the large number of PRs, if this PR is not intended for this release, please close and we will provide early feedback next week.

**Comment by markcowl** [comment]
@avneeshrai Closing for now.  If this is intended for the build release (code complete 5/1) Please reopen.  Otheriwsie, please reopen after the BUILD release is out.

**Comment by avneeshrai** [comment]
@markcowl sure mark! would reopen after build release as you suggested.

**Comment by avneeshrai** [comment]
@markcowl reopening as you had suggested

**Comment by markcowl** [comment]
@avneeshrai This  has merge conflicts.  Please update the PR and ensure it is passing.

**Comment by avneeshrai** [comment]
@markcowl looks this conflict has come after recent changes to the branch. Would fix and update the PR.

**Comment by avneeshrai** [comment]
Solved merge conflicts. Would be updating examples soon. Till then can we have can we have this reviewed so that we have early feedbacks?

**Comment by avneeshrai** [comment]
@markcowl Closing this PR as of now given we are not allowed to take deprecation at this point of time as discussed during office hours. Would create a fresh PR with the approach that we close on in our further discussions.

**Pull request closed without merging**
