### PR TITLE
remove peering to support peerAddressType property for private peering

### PR DESCRIPTION
**Pull request by kilobyte97**
## Description
PeerAddressType is an optional parameter added for Private Peering as well now.
PrivatePeering property can have ipv4 and ipv6 configs. This will allow cx to remove one peering

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by VeryEarly** [comment]
Hi @number213 ,

Can you please help verify these code changes?

**Comment by VeryEarly** [comment]
> [CLA assistant check](https://cla.opensource.microsoft.com/Azure/azure-powershell?pullRequest=12071)
> Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-powershell?pullRequest=12071) before we can accept your contribution.
> 
> ❌ kilobyte97 [sign now](https://cla.opensource.microsoft.com/Azure/azure-powershell?pullRequest=12071)
> You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-powershell?pullRequest=12071) it.

Hi @kilobyte97 ,

Thanks for your contribution, could you please sign this CLA?

**Comment by kilobyte97** [comment]
@number213 can you review the changes ?

**Comment by number213** [comment]
Please retarget to `network-may` branch

**Comment by kilobyte97** [comment]
@number213  is it fine now? anything else needed for sign off ?

**Comment by number213** [comment]
@kilobyte97 please resolve conflicts

**Comment by VeryEarly** [comment]
Hi @kilobyte97 ,

Can you create a new branch and cherry-pick your commits?
The commit history is messed now. Cannot review the code changes now.

**Comment by number213** [comment]
Please cherry-pick your changes to `network-june`

**Pull request closed without merging**
