### PR TITLE
Fixes:#5711- Updating the help for Remove-AzureRmWebAppSlot, missing …

### PR DESCRIPTION
**Pull request by panchagnula**
#5712 

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#making-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@panchagnula Just to make sure, this is intended to be targeted at the preview branch and not the websites-preview branch, correct?

**Comment by panchagnula** [comment]
@maddieclayton  correct the target is preview. Will do a merge from preview to websites-preview next week - until unless you folks are planning one.

**Comment by maddieclayton** [comment]
@panchagnula I am not sure if we are merging to website-preview soon - you would have to ask Mark.

I will merge this PR as soon as the build finishes.

**Comment by panchagnula** [comment]
@maddieclayton  thank you - i will cherry-pick if needed

**Pull request merged**
