### PR TITLE
Application Gateway Mutual Authentication Cmdlets.

### PR DESCRIPTION
**Pull request by HemantErappa**
## Description
Implements the cmdlets to support application gateway private link feature.

Design Review PR:
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/654

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by HemantErappa** [comment]
@VeryEarly @MikhailTryakhov, I have created this PR with a local SDK as the corresponding swagger (Network-June-Release) is not available yet. However, the PR checks are failing as it is not able to find/load the local SDK:
image
Is there a way to fix this failure? Or do I need to wait for the Swagger/SDK to be released before merging this PR?

**Comment by wyunchi-ms** [comment]
Hi @HemantErappa , please try to put the nuget directly under `LocalFeed` folder not a sub folder.

**Comment by isra-fel** [comment]
Kindly ping  @HemantErappa

**Comment by msJinLei** [comment]
@HemantErappa we are closing this PR since no update for a long time. You can create a new PR if you want to continue your work.

**Pull request closed without merging**
