### PR TITLE
Change confirmation message while deleting er direct resources

### PR DESCRIPTION
**Pull request by rakshithtr**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by vidai-msft** [comment]
@rakshithtr Previously the string was obtained from the resource file. Can you please confirm it is not necessary now? In addition, do you need to update the ChangeLog.md?

**Comment by rakshithtr** [comment]
> @rakshithtr Previously the string was obtained from the resource file. Can you please confirm it is not necessary now? In addition, do you need to update the ChangeLog.md?

This log is going to be used only once and only in this file. So, I don't think it needs to be defined separately in resource file. Why do you think we need to update ChangeLog.md ? This is my first PR in PowerShell changes, apologies I don't know what is ChangeLog

**Comment by vidai-msft** [comment]
> > @rakshithtr
> >             
> >             Rakshith Tumkur Ravi Shankar
> >             FTE Previously the string was obtained from the resource file. Can you please confirm it is not necessary now? In addition, do you need to update the ChangeLog.md?
> 
> This log is going to be used only once and only in this file. So, I don't think it needs to be defined separately in resource file. Why do you think we need to update ChangeLog.md ? This is my first PR in PowerShell changes, apologies I don't know what is ChangeLog

ChangeLog.md under the root folder has a section called `Upcoming Changes` which include all the notes you have updated in the new release. I am not asking you to update the ChangeLog.md. Just wanted to confirm if you need to modify it so that our customers can clearly see what have been updated.

**Comment by rakshithtr** [comment]
> > > @rakshithtr
> > > ```
> > >         Rakshith Tumkur Ravi Shankar
> > >         FTE Previously the string was obtained from the resource file. Can you please confirm it is not necessary now? In addition, do you need to update the ChangeLog.md?
> > > ```
> > 
> > 
> > This log is going to be used only once and only in this file. So, I don't think it needs to be defined separately in resource file. Why do you think we need to update ChangeLog.md ? This is my first PR in PowerShell changes, apologies I don't know what is ChangeLog
> 
> ChangeLog.md under the root folder has a section called `Upcoming Changes` which include all the notes you have updated in the new release. I am not asking you to update the ChangeLog.md. Just wanted to confirm if you need to modify it so that our customers can clearly see what have been updated.

@vidai-msft , I think we can skip this since this is not a behaviour change or changes in parameters to the powershell command

**Review by vidai-msft — APPROVED** [review]
LGTM

**Pull request merged**
