### PR TITLE
add-AzsDirectoryTenant-Remove-and-Set-cmdlets

### PR DESCRIPTION
**Pull request by cblackuk**
## Description

Remove-AzsDirectoryTenant.ps1 and Set-AzsDirectoryTenant.ps1 to the psd1 file to enable them for auto-loading and general use.

Those were already in the module but were not exported:
https://www.powershellgallery.com/packages/Azs.Subscriptions.Admin/0.3.1/Content/Generated.PowerShell.Commands%5CSwaggerPathCommands%5CRemove-AzsDirectoryTenant.ps1

https://www.powershellgallery.com/packages/Azs.Subscriptions.Admin/0.3.1/Content/Generated.PowerShell.Commands%5CSwaggerPathCommands%5CSet-AzsDirectoryTenant.ps1

After speaking to @troettinger he agreed that those can be enabled; therefore, I am making this PR.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by bganapa** [comment]
@cblackuk  Thanks for the PR. I am trying to remember why I didn't want to expose these cmdlets. I will get back to you

**Comment by cblackuk** [comment]
Thanks @bganapa - I cannot really see anything wrong with them to be fair... :-)

**Comment by cormacpayne** [comment]
@bganapa Hey Bala, any update here?

**Comment by bganapa** [comment]
@cblackuk I will take over this PR as I need to update the help files and tests as well. I have not got a chance to discuss why we disable these yet. Hope you are not blocked by this. We are planning to update the powershell modules only by April End.

**Comment by cblackuk** [comment]
Hi @bganapa thanks for having a look. They are not blocking us as such but it would be nice to have those available if possible. Are we talking about full .NET Core integration by end of April or something a little less drastic.

**Comment by bganapa** [comment]
@cblackuk we are not yet ready for .Net core yet, April release will be aligned with 1904 update release.

**Comment by cblackuk** [comment]
@bganapa Thanks for a confirmation at least I know what to prep for :-) Would be nice if we could get those into 1904 though...

**Comment by vladimir-shcherbakov** [comment]
@cblackuk What is the status of the PR? Are you still waiting for the Bala's sign off?

**Comment by bganapa** [comment]
@cblackuk I will close this PR for now and reopen , I am with other tasks now. We will have this PR ready by March end

**Comment by cblackuk** [comment]
Makes me super sad but ok... Will try to remind you and myself towards the end of the March... @bganapa

**Comment by bganapa** [comment]
Hi @cblackuk , just got a chance to look deep in to these. We have wrapper cmdlets for the functionality as explained here https://docs.microsoft.com/en-us/azure/azure-stack/azure-stack-enable-multitenancy . 
Set-AzsDirectoryTenant is not meaningful as you are not likely intending to change any of the properties.
With these i do not see a need expose the Set- and Remove- cmdlets on directoryTenants..  The scripts explained in the above article will eventually part of the AzureStack module in future..

@seyadava @keystroke FYI

**Comment by keystroke** [comment]
Hi @cblackuk,

As mentioned, the multitenancy scripts available in the Azure Stack Tools repo are preferred to be used, though if necessary you can see that we are just using the Remove-AzureRmResource cmdlet to delete these resources in the "unregister" scenario: https://github.com/Azure/AzureStack-Tools/blob/master/Identity/AzureStack.Identity.psm1#L886

We've had a lot of issues with CSP extensions to multitenancy scenarios, hence our reluctance to expose these kinds of tools in an isolated context. However, I am interested more in your scenario in general, because we are actively seeking improvements / redesigns in this space.

**Comment by cblackuk** [comment]
Thanks @bganapa and @keystroke  for getting back to me. My scenario is that I would like to have some working on and off boarding code :-) I do not really need those as we have written our own versions of said tools that we are planning to release very soon :-) It would be nice to have those exposed but like I said... I already have a workaround... ;-)
Thanks for looking into it though :)

**Pull request closed without merging**
