### PR TITLE
 Set-AzSqlServerAdvancedThreatProtectionSettings: Remove the validation of EmailAddresses and the check that EmailAdmin is not false in case EmailAddresses is empty

### PR DESCRIPTION
**Pull request by ayeletshpigelman**
## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@ayeletshpigelman ping on the above comments

**Comment by cormacpayne** [comment]
Closing due to lack of activity. Please feel free to re-open this issue when you have a chance to respond to the above comments.

**Comment by ayeletshpigelman** [comment]
I have fixed ChangeLog.md
failed to record the result of the tests.
how can I run the tests in record mode? getting this error in vs: 
Severity	Code	Description	Project	File	Line	Suppression State
Error		The current .NET SDK does not support targeting .NET Standard 2.0.  Either target .NET Standard 1.6 or lower, or use a version of the .NET SDK that supports .NET Standard 2.0.	OperationalInsights	C:\Program Files (x86)\Microsoft Visual Studio\2017\Enterprise\MSBuild\Sdks\Microsoft.NET.Sdk\build\Microsoft.NET.TargetFrameworkInference.targets	126	

However in developer commands prompt the project compiled successfuly

**Comment by msJinLei** [comment]
- This change refers to the bug that fails to recognize email address as case insensitive (https://github.com/Azure/azure-powershell/issues/5442. However) while the fix is to remove the email validation. And why? What will do with invalid email address?
- No test cases related diff can be found in the files changed.  Are the cases mentioned by rayeletshpigelman already included?

**Comment by ayeletshpigelman** [comment]
The email validation is being done in the RP (server-side), as agreed with Jared Moore at: https://github.com/Azure/azure-powershell/pull/6671

I am working of the tests. will add another commit shortly.

**Comment by ayeletshpigelman** [comment]
I have added tests also

**Comment by cormacpayne** [comment]
Changes LGTM -- @jaredmoo any additional comments or concerns?

**Pull request merged**
