### PR TITLE
Update Microsoft.Azure.Commands.Insights.dll-Help.xml

### PR DESCRIPTION
**Pull request by pcgeek86**
Fixed / added help for Get-AzureResourceProviderLog

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@pcgeek86__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
:+1:  Thank you!

**Comment by pcgeek86** [comment]
@devigned You're welcome! :+1:

**Comment by pcgeek86** [comment]
@devigned Hang on, I fat-fingered the first line of the XML file, making it invalid. Going to add some more doc fixes and will resolve the bug I created.

**Comment by pcgeek86** [comment]
@devigned Nevermind, I just fixed the question mark bug. I can't do much else without REST API docs for ARM. Do you have a link to ARM docs for this "insights" interface? Seemed to be missing from the ARM reference on MSDN (dated April 2015).

**Comment by devigned** [comment]
Hmm... let me see if I can get my hands on them.

**Comment by ogail** [comment]
@pcgeek86 is this PR ready to merge?

**Comment by pcgeek86** [comment]
@ogail I'll submit more PRs once I get the docs I need. Thanks for the quick merge.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Pull request merged**
