### PR TITLE
[HDInsight] Check in track-1 source code and add a new feature.

### PR DESCRIPTION
**Pull request by yuc-Li**
## Description

* Check in track-1 source code.
* Add a new feature: Enable Secure Channel while create a new cluster.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by VeryEarly — DISMISSED** [review]

**Comment by yuc-Li** [comment]
Hi @VeryEarly , we still need some time to update test session records, please do not merge yet. Thanks.

**Comment by yuc-Li** [comment]
Hi @VeryEarly , I have updated some scenario tests and session records. Please review and help complete this PR. Thanks.

**Comment by dolauli** [comment]
@yuc-Li You have completed step#1 in https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azps_docs/process-track1-sdk-migration#check-in-sdk-source-code-into-azure-powershell-and-release-module-based-on-it. Please complete step as well to replace track 1 SDK with the SDK generated by autorest.powershell

**Comment by yuc-Li** [comment]
> @yuc-Li You have completed step#1 in https://eng.ms/docs/cloud-ai-platform/azure-core/azure-management-and-platforms/control-plane-bburns/azure-cli-tools-azure-cli-powershell-and-terraform/azure-cli-tools/teams_docs/azps_docs/process-track1-sdk-migration#check-in-sdk-source-code-into-azure-powershell-and-release-module-based-on-it. Please complete step#2 as well to replace track 1 SDK with the SDK generated by autorest.powershell

Hi @dolauli ，I have completed replace track 1 SDK with the SDK generated by autorest.powershell in this PR #23726 , please help review and merge.

**Comment by dolauli** [comment]
@yuc-Li why did you close the issue?

**Comment by yuc-Li** [comment]
> @yuc-Li why did you close the issue?

Completed in another PR, does this also need to be retained?

**Pull request closed without merging**
