### PR TITLE
Enable internet security feature for VirtualWan P2SVpnGateway client connections and expose Reset operations for VirtualWan P2SVpnGateway & VpnGateway resources.

### PR DESCRIPTION
**Pull request by Nilambari**
## Description

1. Enable internet security feature for VirtualWan P2SVpnGateway client connections and 
2. Expose Reset operations for VirtualWan P2SVpnGateway & VpnGateway resources.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by Nilambari** [comment]
Related approved cmdlet design review :- https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/665

**Comment by wyunchi-ms** [comment]
Please add generated help file for `Reset-AzP2sVpnGateway` and `Reset-AzVpnGateway`. @Nilambari

**Comment by Nilambari** [comment]
> Please add generated help file for `Reset-AzP2sVpnGateway` and `Reset-AzVpnGateway`. @Nilambari

@wyunchi-ms Done. Please take a look. Thanks!

**Comment by Nilambari** [comment]
> > Please add generated help file for `Reset-AzP2sVpnGateway` and `Reset-AzVpnGateway`. @Nilambari
> 
> @wyunchi-ms Done. Please take a look. Thanks!
Gentle reminder.

**Comment by Nilambari** [comment]
> > > Please add generated help file for `Reset-AzP2sVpnGateway` and `Reset-AzVpnGateway`. @Nilambari
> > 
> > 
> > @wyunchi-ms Done. Please take a look. Thanks!
> > Gentle reminder.

**Comment by Nilambari** [comment]
@wyunchi-ms Can you Please take a look. Thanks!

**Comment by wyunchi-ms** [comment]
> @wyunchi-ms Can you Please take a look. Thanks!

The error log of test is too large to open it. I'm trying to download it.

**Comment by wyunchi-ms** [comment]
Hi @Nilambari , you need to change all the network sdk version in all the test.csproj. And please also commit the `symbols.nupkg`.

**Comment by Nilambari** [comment]
@wyunchi-ms  will incorporate review comments. Thanks!

**Comment by Nilambari** [comment]
> @wyunchi-ms Incorporated review comments. Please take a look. Thanks!

Can you help with the review Please?

**Comment by msJinLei** [comment]
@Nilambari  You can download the log https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/506546/logs/52 to review the failed test here.

**Comment by Nilambari** [comment]
@msJinLei @wyunchi-ms  I have added test recording. Can you Please help take a look and merge this PR?
From build, I see **unrelated** test failure:- Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests.TestAzureRmSignalRUpdateNetworkAcl [FAIL]
So, this is not related to my changes.

**Comment by Nilambari** [comment]
@Y-Sindo your feature test:- Microsoft.Azure.Commands.SignalR.Test.ScenarioTests.AzureRmSignalRTests.TestAzureRmSignalRUpdateNetworkAcl  is failing after importing latest network sdk. As its blocking the merge, skipped the test. Please rerecord the test, include latest test recording and enable that test back in Master branch. Thanks!

**Comment by Nilambari** [comment]
@wyunchi-ms I have skipped the failing test which is not related to my changes. That test owner will take care of rerecording it and enabling it back. Can you Please help approve my PR? Thanks a  lot!

**Pull request merged**
