### PR TITLE
Remove unusable NextLink parameter and parameter set from Get-AzVM

### PR DESCRIPTION
**Pull request by Sandido**
## Description

As per https://github.com/Azure/azure-powershell/pull/21444/files, we are removing the unused and unusable NextLink parameterset. 

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by Sandido** [comment]
@msJinLei , how do I input a breaking change suppression? This is for the breaking change release.

**Comment by msJinLei** [comment]
> @msJinLei , how do I input a breaking change suppression? This is for the breaking change release.

Suppress the breaking change errors in "tools/StaticAnalysis/Exceptions/${ModuleName}/BreakingChangeIssues.csv"
```
"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
"Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzFirewallPolicyNatRuleCommand","New-AzFirewallPolicyNatRule","0","1050","The parameter set '__AllParameterSets' for cmdlet 'New-AzFirewallPolicyNatRule' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'New-AzFirewallPolicyNatRule'."
```

**Comment by Sandido** [comment]
@msJinLei , apologies, I misunderstood when code freeze was. Please consider this for the release if that is still possible.

**Review by msJinLei — APPROVED** [review]

**Comment by msJinLei** [comment]
> @msJinLei , apologies, I misunderstood when code freeze was. Please consider this for the release if that is still possible.

@Sandido We set code freeze date is not to block our partners. We have a lot of work to do after code freeze so that We cannot ensure to get PRs reviewed after code freeze. Your PR looks good except not removing the breaking change notification. I just remove it. And so don't worry, your PR will be included into this release. 
Thank you for understanding!

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
