### PR TITLE
Create Az projects for Security and StorageSync

### PR DESCRIPTION
**Pull request by MiYanni**
## Description

Fixes: https://github.com/Azure/azure-powershell/issues/7702

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@maddieclayton I'll make sure that I cover StorageSync as part of https://github.com/Azure/azure-powershell/issues/6792
I'll be creating a bunch of issues soon of a similar nature. So, I'm just trying to collect that to see if I notice any patterns.
But, I also have a similar concern about StorageSync working on Linux. They are currently only in preview, so I'm less concerned about it than the core modules.

**Comment by maddieclayton** [comment]
@MiYanni Sounds good.  Have you published these packages to the gallery? Will merge this PR as soon as that's done.

**Comment by MiYanni** [comment]
@maddieclayton I haven't published them yet. I can do that tomorrow. I'll mark Do Not Merge until that's done.

**Comment by MiYanni** [comment]
ps-sign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1526/
psnetsign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/295/

**Pull request merged**
