### PR TITLE
[ProviderHub] New PS Cmdlets for ProviderHub

### PR DESCRIPTION
**Pull request by wwendyc**
## Description

Onboarding ProviderHub to Powershell commands.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/875
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @wwendyc, I guess your pr is ready for review.

**Comment by wwendyc** [comment]
@BethanyZhou yes, would you be able to review it? Or where do I request for reviewers for the PR?

**Comment by wwendyc** [comment]
@BethanyZhou yes, marked it as ready for review now. Please take a look when you get a chance

**Comment by BethanyZhou** [comment]
Hi @wwendyc , it seems like the module was generated based on swagger. Your target branch should be generation and please do not sync your generated codes to master. We will trigger a pipeline for this job.

**Comment by wwendyc** [comment]
Created a new PR from the generation branch: https://github.com/Azure/azure-powershell/pull/14646

**Comment by BethanyZhou** [comment]
@wwendyc , thank you for your coordination, @dolauli will take care of the review of generated module.

**Comment by wwendyc** [comment]
@BethanyZhou Really appreciate your help, thanks so much🙂

**Pull request closed without merging**
