### PR TITLE
[Batch] Fix error when setting null values in job CommonEnvironmentSettings property

### PR DESCRIPTION
**Pull request by dpwatrous**
## Description

This fixes a customer-reported issue where setting a null value inside the CommonEnvironmentSettings dictionary results in a 'Object reference not set to an instance of an object' error.

Also updated the test JSON sanitizers to include Batch account keys.

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [X] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by wiboris — APPROVED** [review]

**Review by VeryEarly — APPROVED** [review]

**Comment by VeryEarly** [comment]
Hi @dpwatrous ,
please manually change password in these 2 lines to [Sanitized]:
https://github.com/dpwatrous/azure-powershell/blob/dpwatrous/batch-null-dictionary-values/src/Batch/Batch.Test/SessionRecords/Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeUserTests/TestComputeNodeUserEndToEnd.json#L1002
https://github.com/dpwatrous/azure-powershell/blob/dpwatrous/batch-null-dictionary-values/src/Batch/Batch.Test/SessionRecords/Microsoft.Azure.Commands.Batch.Test.ScenarioTests.ComputeNodeUserTests/TestComputeNodeUserEndToEnd.json#L1066

**Comment by dpwatrous** [comment]
@VeryEarly Rather than manually update the JSON recordings every time, I updated the sanitizers to strip the 'password' field from the JSON. Does that work for you? I squashed that change into the commit where I updated the sanitizers for Batch account keys, reran the node user tests, and squashed the updated recording into the 2nd commit.

**Comment by VeryEarly** [comment]
> @VeryEarly Rather than manually update the JSON recordings every time, I updated the sanitizers to strip the 'password' field from the JSON. Does that work for you? I squashed that change into the commit where I updated the sanitizers for Batch account keys, reran the node user tests, and squashed the updated recording into the 2nd commit.

Hi @dpwatrous , thanks for investigating this. The 'password' is probably OK but I have a concern that pattern of 'primary' and 'secondary' could be too general. Do you mind removing these two?

**Comment by dpwatrous** [comment]
@VeryEarly I was wondering about those too. I agree they seem too broad. Is there a better way to target the sanitizers specifically for Batch API calls? I looked around but wasn't finding anything obvious. I'd really like us to have an automated solution here rather than a manual search and replace in .json files.

**Comment by dpwatrous** [comment]
I went ahead an removed those lines just so this hotfix isn't blocked, but I'd love to find a better solution either in this PR or a subsequent one if you have any recommendations.

**Comment by dpwatrous** [comment]
@VeryEarly can we merge this just to get the hotfix in the next release, and tackle the question of sanitizing account keys separately?

**Pull request merged**
