### PR TITLE
Updated Get-AllCommands script that allows for JSON based reporting. …

### PR DESCRIPTION
**Pull request by jongeller**
…(Attempt 2)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jongeller__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by devigned** [comment]
@jongeller please normalize the indentation of the script. If you view the raw version (https://github.com/jongeller/azure-powershell/blob/dev/tools/Docs/Get-AllCommands/Get-AllCommands.ps1), you'll see that the indentation is not consistent within functions and other scopes. Ping me if I can be of service.

**Comment by stankovski** [comment]
Cortana test this please

**Comment by markcowl** [comment]
@azursdkci retest this please

**Comment by stankovski** [comment]
Closing for https://github.com/Azure/azure-powershell/pull/1023

**Pull request closed without merging**
