### PR TITLE
Update versions for Az 0.2.0

### PR DESCRIPTION
**Pull request by markcowl**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by markcowl** [comment]
netsign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/188/

**Comment by markcowl** [comment]
https://azuresdkci.westus2.cloudapp.azure.com/job/psnetsign/189/

**Comment by markcowl** [comment]
on demand run here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/1100/

signing here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/192/

**Comment by markcowl** [comment]
on demand: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/1104/
signing: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1337/
netsign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/196/

**Comment by markcowl** [comment]
sign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1338/

**Comment by maddieclayton** [comment]
Looks like this doesn't include the service bus update, so created a new PR here with a corresponding sign job: https://github.com/Azure/azure-powershell/pull/7266.  Let me know if that looks good to you.

**Comment by v-shresh** [comment]
Hi All

Please stop marking me in this email. I have got almost 2185 emails and my email account has been clogged now.

Thanks
Shreya

**Comment by markcowl** [comment]
@maddieclayton as it happens, there was an encoding issue with one of the psd1 updates, so I just took your changes in here.

**Comment by markcowl** [comment]
sign job (all changes): https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1342/

**Pull request merged**
