### PR TITLE
updated AzureRM.Resources dependency for the release AzureStack 1.7.1

### PR DESCRIPTION
**Pull request by seyadava**
## Description

Updated following modules version due to the change of AzureRM.Resources version:
- AzureBridge
- Commerce
- Gallery
- Infrastructureinsights
- Keyvault
- Network
- Storage
- Subscriptions.Admin
- Subscriptions
- Update

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by seyadava** [comment]
@bganapa

**Comment by bganapa** [comment]
ps-sign https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign-esrp/116/console

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by seyadava** [comment]
ps-sign https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign-esrp/117/

**Comment by bganapa** [comment]
@markcowl how do we rekick the jenkins validation again here? It is stuck at some checks havent completed yet..

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Pull request merged**
