### PR TITLE
Remove range for Priority, handle empty name and remove by subnet/ip

### PR DESCRIPTION
**Pull request by madsd**
## Description

This PR will fix an issue where Priority Range was limited to 100-65000. There is no range limit in the backend.

It also addresses rule entries with empty names. To support this, changes had to be made to Add and Remove - specifically remove now contains optional IpAddress and Subnet/vNet parameters and logic to remove based on this input when supplied.

Help files has been updated to reflect this.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by markcowl** [comment]
@panchagnula can you please review and sign off on this change as aprpopriate?

**Comment by panchagnula** [comment]
@madsd while you are looking at this can you fix this issue as well - I believe this is coming from the validation check https://github.com/Azure/azure-powershell/issues/10794

**Comment by msJinLei** [comment]
@madsd Could you resolve the conflicts? Thanks

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by madsd** [comment]
@msJinLei Conflicts has been resolved

**Pull request merged**
