### PR TITLE
Adding Rm to cmdlet name

### PR DESCRIPTION
**Pull request by shefaliv**

### CODE REVIEW

**Comment by hovsepm** [comment]
@shefaliv Please add documentation to dll-help.xml file for this cmdlet.

**Comment by markcowl** [comment]
@shefaliv Specifically, please change the name of the cmdlet in the dll help

**Comment by shefaliv** [comment]
manually added documentation since the tool doesn't work. If one of you could glance over for a sanity check that'd be great, since it wasn't auto-generated. Thanks!

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Pull request merged**
