### PR TITLE
Add support for multiple-secondary failover groups in New and Set cmdlets

### PR DESCRIPTION
**Pull request by alecbain**
## Description

This changeset modifies New-AzSqlDatabaseFailoverGroup and Set-AzSqlDatabaseFailoverGroup with optional parameters to accommodate the new multiple-secondary failover group feature. 

When passing in the new parameters, there is a separate code path that will use the newest client, which on the backend has support for the feature. 

If not using any new parameters, the commands will function as they did before and throw exceptions if the failover group has more than one secondary.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by VeryEarly** [comment]
test case failed at:
https://github.com/Azure/azure-powershell/blob/76bd9c0974b3bb14fd6d976931697c2378b309cb/src/Sql/Sql.Test/ScenarioTests/FailoverGroupTests.ps1#L42

```
 Caught Exception: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Value cannot be null. (Parameter 'source')
      at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke()
      at Microsoft.Azure.Commands.TestFx.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in D:\a\_work\1\s\tools\TestFx\EnvironmentSetupHelper.cs:line 531
   Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Value cannot be null. (Parameter 'source')
EXEC : PowerShell error Record: Value cannot be null. (Parameter 'source') [D:\a\_work\1\s\build.proj]
  Exception:System.ArgumentNullException: Value cannot be null. (Parameter 'source')
      at System.Linq.ThrowHelper.ThrowArgumentNullException(ExceptionArgument argument)
      at System.Linq.Enumerable.Count[TSource](IEnumerable`1 source)
      at Microsoft.Azure.Commands.Sql.FailoverGroup.Cmdlet.NewAzureSqlFailoverGroup.PersistChanges(IEnumerable`1 entity) in D:\a\_work\1\s\src\Sql\Sql\Failover Group\Cmdlet\NewAzureSqlFailoverGroup.cs:line 210
      at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.<>c__DisplayClass16_0.<ExecuteCmdlet>b__0() in D:\a\_work\1\s\src\Sql\Sql\Common\AzureSqlCmdletBase.cs:line 127
      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ConfirmAction(String processMessage, String target, Action action)
      at Microsoft.Azure.Commands.Sql.Common.AzureSqlCmdletBase`2.ExecuteCmdlet() in D:\a\_work\1\s\src\Sql\Sql\Common\AzureSqlCmdletBase.cs:line 125
      at Microsoft.WindowsAzure.Commands.Utilities.Common.AzurePSCmdlet.ProcessRecord()
  Details:
  Script Stack Trace: at <ScriptBlock>, D:\a\_work\1\s\src\Sql\Sql.Test\bin\Debug\net6.0\ScenarioTests\FailoverGroupTests.ps1: line 42
   at Handle-FailoverGroupTest, D:\a\_work\1\s\src\Sql\Sql.Test\bin\Debug\net6.0\ScenarioTests\FailoverGroupTests.ps1: line 25
   at Handle-FailoverGroupTestWithFailoverGroup, D:\a\_work\1\s\src\Sql\Sql.Test\bin\Debug\net6.0\ScenarioTests\FailoverGroupTests.ps1: line 38
   at Test-SetFailoverGroup-AutomaticWithGracePeriodReadOnlyFailover, D:\a\_work\1\s\src\Sql\Sql.Test\bin\Debug\net6.0\ScenarioTests\FailoverGroupTests.ps1: line 288
   at <ScriptBlock>, <No file>: line 1

```

**Comment by alecbain** [comment]
There was a regression in the backend code that is causing all update FoG powershell calls to throw an exception. Fix is already merged and waiting to deploy. 

Once deployed, test cases should succeed on re-run.

**Comment by VeryEarly** [comment]
> There was a regression in the backend code that is causing all update FoG powershell calls to throw an exception. Fix is already merged and waiting to deploy.
> 
> Once deployed, test cases should succeed on re-run.

sounds like test cases need to be re-recorded once service deployed

**Comment by alecbain** [comment]
Pushed update now that the backend fix is deployed WW. Re-ran tests locally with all passing (committed all the new logs in the update)

Looks like automated checks are all passed, so now just outstanding reviewer approval.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
