### PR TITLE
Fix for not setting apirevisiondescription

### PR DESCRIPTION
**Pull request by solankisamir**
## Description

* Fix for issue ApiRevisionDescription not being set when creating new api revision
https://github.com/Azure/azure-powershell/issues/9752

* Fixed typo in model `PsApiManagementOAuth2AuthorizationServer` to `PsApiManagementOAuth2AuthorizationServer`

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by solankisamir** [comment]
@cormacpayne can you take a look?

**Comment by erwinkramer** [comment]
I have an issue where the `ApiRevisionDescription` is not being set while using the 2019-01-01 ARM template, is that included in the fix as well?

**Comment by solankisamir** [comment]
@erwinkramer no. This is fix only in PowerShell

**Pull request merged**
