### PR TITLE
appgw: validate cert only if certificateFile is specified in set ssl cert command

### PR DESCRIPTION
**Pull request by akshaysngupta**
## Description
This PR majorly is to fix https://github.com/Azure/azure-powershell/issues/9488

But as a part of this PR, we add a test in Network project using a KeyVault dataplane cmdlets. To make these cmdlets work, I am have made additional changes to Network Test Runner and KeyVault project. These changes help to mock the keyvault client in the Network project.

This code change was also reviewed in another PR: https://github.com/Azure/azure-powershell/pull/10991 which was closed due to major rebase on the `master` branch.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@akshaysngupta Please fix test failure

**Comment by akshaysngupta** [comment]
@msJinLei a build related to macos failed. can you please help with that ?

**Comment by akshaysngupta** [comment]
@msJinLei CI is green!

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
