### PR TITLE
[Synapse] - fix signature issues

### PR DESCRIPTION
**Pull request by idear1203**
## Description

This PR aims to fix signature issues for Synapse service. Before this change, we have 30 issues in total. Most of them are claiming about default parameter set. After this change, we only have 3 issues.

This PR does the following things to fix those issues:
1. Added default parameter set for all cmdlets that have multiple parameter set.
2. Added output type for the following cmdlets:
    - `Test-AzSynapseWorkspace`
    - `Test-AzSynapseSparkPool`
    - `Test-AzSynapseSqlPool`
3. Change some parameter names to singular nouns. Including:
    - Parameter `DisallowAllConnections` of cmdlet `New-AzSynapseWorkspace` changes to `DisallowAllConnection`
    - Parameter `CommandLineArguments` of cmdlet `Submit-AzSynapseSparkJob` changes to `CommandLineArgument`
    - Parameter `ReferenceFiles` of cmdlet `Submit-AzSynapseSparkJob` changes to `ReferenceFile`
    - Parameter `ReferenceFiles` of cmdlet `Start-AzSynapseSparkSession` changes to `ReferenceFile`
4. Updated the help documents
5. Re-run the static analysis tool and updated `tools/StaticAnalysis/Exceptions/Az.Synapse/SignatureIssues.csv`

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by idear1203** [comment]
Please DO NOT merge the PR. I am doing static analysis testing and discussing a few issues with some Azure PowerShell team members.

**Comment by wyunchi-ms** [comment]
We changed some StaticAnalysis rules. Please sync the latest changes from master and rerun the CI.

**Comment by idear1203** [comment]
> We changed some StaticAnalysis rules. Please sync the latest changes from master and rerun the CI.

@wyunchi-ms , thanks for the guide! I have synced the master branch and rerun the CI.

**Pull request merged**
