### PR TITLE
Release

### PR DESCRIPTION
**Pull request by bganapa**
csproj and packages changes, setup changes for azurestack storage

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bganapa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bganapa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/job/powershell-demand/461/

**Comment by bganapa** [comment]
powersehl-sign http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/
on demand - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/

**Comment by hovsepm** [comment]
sign: http://azuresdkci.cloudapp.net/job/powershell-sign/231/

**Comment by bganapa** [comment]
sign: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/232/

**Pull request merged**
