### PR TITLE
Authorization: Add role assignment paging for list calls

### PR DESCRIPTION
**Pull request by namratab**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@namratab__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nbaliga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/258/

**Comment by markcowl** [comment]
@namratab please pull the latest from the dev branch to make the on-demand run succeed

**Comment by namratab** [comment]
Done, thanks !

**Comment by namratab** [comment]
@markcowl I have kicked off an on-demand http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/  
Looks like there is a long queue for both Powershell and on-demand jobs.

**Comment by hovsepm** [comment]
On-Demand job - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/275/

**Pull request merged**
