### PR TITLE
[AzureRT] Storage Migration cmdlets

### PR DESCRIPTION
**Pull request by hyonholee**
Also, update Add-AzureCertificate

(This PR updates ASM Storage library version to 6.0.0)

### CODE REVIEW

**Comment by markcowl** [comment]
@hyonholee Why are you updateing storage management everywhere?  The entire idea of the storage infrastructure is that cmdlets can independently use different versions of storage using different adapters.  Please update storage and update the adapter only for those cmdlets you need to change.

**Comment by hovsepm** [comment]
@hyonholee please fix build breaks.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/845/

**Comment by markcowl** [comment]
@hyonholee you will need to fix helkp and assembly version conflicts

**Comment by markcowl** [comment]
On demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/851/
signing run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/440/

**Pull request merged**
