### PR TITLE
Silence a deprecation warning regarding SendingRequest2.

### PR DESCRIPTION
**Pull request by rhencke**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rhencke__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by stankovski** [comment]
@akromm please review

**Comment by akromm** [comment]
looks good to me.

**Pull request merged**
