### PR TITLE
[CosmosDB] NoTimeStamp Based Restore Fixes for GA PowerShell commands for InAccount Restore of Deleted Database/ Containers feature for SQL/Mongo/Table/Gremlinowershell stable

### PR DESCRIPTION
**Pull request by AgarwalVivek**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by AgarwalVivek** [comment]
@dolauli I see you helped with the merge of https://github.com/Azure/azure-powershell/pull/23666/files/8fbbeb8ba4eb39c87e795a28c3e0687494253ba8#diff-9957bb3df372fd6fc76050b6f6a9b4cadff4b3712f9b617e387962914b6d4952

There is a bug that we are trying to fix in immediate next release :2024-03-05 and this change is crucial to go in.

I am trying to get some reviews. Can you help. Thanks in advance!

**Comment by msJinLei** [comment]
@AgarwalVivek Please fix the failed test cases. Please add the test to cover your changes.

**Comment by AgarwalVivek** [comment]
> @AgarwalVivek Please fix the failed test cases. Please add the test to cover your changes.

Thanks for taking a look. @msJinLei Can you please point me to the location where i can access the logs from pipeline:
 https://dev.azure.com/azclitools/public/_build/results?buildId=132460&view=logs&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0&l=35259

**Comment by AgarwalVivek** [comment]
> /azp run azure-powershell - security-tools

@msJinLei what about it ? please suggest.

**Comment by AgarwalVivek** [comment]
@msJinLei can you please share the azure-cli version that customer would see this fix in?

**Comment by msJinLei** [comment]
> @msJinLei can you please share the azure-powershell version that customer would see this fix in?

@AgarwalVivek Az.CosmosDB 1.14.1

**Pull request merged**
