### PR TITLE
Azure Deployment Manager is being decommissioned. Deleting the Rest API Specs related to ADM.

### PR DESCRIPTION
**Pull request by rohantagaru**
…PI Specs related to ADM.

## Description

Azure Deployment Manager is being decommissioned. Deleting the Rest API Specs related to ADM.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by BethanyZhou** [comment]
@rohantagaru , do you mean you want to remove module Az.DeploymentManager from Az PowerShell as its service is decommissioning?

**Comment by rohantagaru** [comment]
@BethanyZhou yes that is correct. We are currently already deprecated and not receiving any traffic. Now we would like to go ahead decommission it.

**Comment by BethanyZhou** [comment]
Hi @rohantagaru , it's a sudden news for us. Generally, if we want to deprecate a module, we need pre-announce the message to customer with 2 sprints ahead. As you claims service side are currently already deprecated and not receiving any traffic, I need discuss with our PM. Will go back to you if we requires other processes for this case.

**Comment by BethanyZhou** [comment]
@rohantagaru tested one of cmdlets in Az.DeploymentManager, seems it still works (will work) for a while. From our telemetry, still have few traffic from Az.DeploymentManager. Seems like we still have enough time to go through Azure retirement process. 
image

Azure PowerShell allows breaking change twice per year, next timeline is October (available on15th November for customer).
Let us announce it in our upcoming breaking change in current month first. Could you share a notification link announced from your team?

Let's announce this message to in current sprint, and remove this module in ignite (15th Novemeber)

**Comment by NoriZC** [comment]
Hi @rohantagaru, converting this PR to draft due to inactivity. Please feel free to mark it as ready if you are still working on it. If you do not want to work on it any more, please close it or we will close it for you next time. :)

**Comment by wyunchi-ms** [comment]
Closing this PR because it need to merge: https://github.com/Azure/azure-powershell/pull/23128 first

**Pull request closed without merging**
