### PR TITLE
RouteNextHopTypeFix

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
On demand run kicked off here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/26/

**Comment by DeepakRajendranMsft** [comment]
The on-demand run succeeded but the CI failed with a test issue.
"D:\workspace\powershell\build.proj" (Full target) (1) ->
(TimeoutErrorHandler target) -> 
  D:\workspace\powershell\AzurePowershell.test.targets(98,5): error : XUnit tests in assembly "Microsoft.Azure.Commands.AzureBackup.Test.dll" failed or timed out. Ensure that all tests in a project pass and collectively take less than 1 minute to run. [D:\workspace\powershell\build.proj]

    110 Warning(s)
    2 Error(s)

**Comment by stankovski** [comment]
Retest this please

**Pull request merged**
