### PR TITLE
fixes of obvious code mistakes

### PR DESCRIPTION
**Pull request by DamirAinullin**
Some fixes of obvious code mistakes or warnings

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DamirAinullin__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@DamirAinullin Thank you for the contribution. Please sign the CLA so we can take in your contribution.

**Comment by azurecla** [comment]
__@DamirAinullin__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by DamirAinullin** [comment]
@hovsepm, Done.

**Comment by markcowl** [comment]
@DamirAinullin This is awesome, thank you!  Since we are now throwing some (obviously intended but not thrown before) exceptions, I will execute a complete test run before merging. 

on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/911/

**Pull request merged**
