### PR TITLE
Enable Get-AzVM piping to Get-AzVMExtension cmdlet

### PR DESCRIPTION
**Pull request by Sandido**
Work for https://msazure.visualstudio.com/One/_workitems/edit/9110354 

PS issue: https://github.com/Azure/azure-powershell/issues/11557

PS Design spec: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/826

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@Sandido  Please submit a cmdlet review first https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues

**Comment by Sandido** [comment]
> @Sandido Please submit a cmdlet review first https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues

Submitted here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/826

**Comment by grizzlytheodore** [comment]
LGTM

**Comment by msJinLei** [comment]
> > @Sandido Please submit a cmdlet review first https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues
> 
> @msJinLei , Submitted here: [Azure/azure-powershell-cmdlet-review-pr#826](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/826)

@Sandido  Please refer to my comments in cmdlet review

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
