### PR TITLE
Upgrade artifacts version to 1.0.0-preview.14

### PR DESCRIPTION
**Pull request by yanjungao718**
## Description

Upgrade artifacts version to 1.0.0-preview.14

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by wonner — APPROVED** [review]

**Review by BethanyZhou — DISMISSED** [review]

**Comment by BethanyZhou** [comment]
A breaking change is detected:

 "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.Synapse","Microsoft.Azure.Commands.Synapse.GetAzureSynapseTriggerRun","Get-AzSynapseTriggerRun","0","3010","The property 'Inprogress' of type 'Azure.Analytics.Synapse.Artifacts.Models.TriggerRunStatus' has been removed.","Add the property 'Inprogress' back to type 'Azure.Analytics.Synapse.Artifacts.Models.TriggerRunStatus'."
  


Any change to workaround?

**Comment by BethanyZhou** [comment]
I'm not sure whether this change will break users' scripts. Could you confirm? Otherwise, we may need wait for major release (possible next month or next two month).

**Comment by yanjungao718** [comment]
Hi @BethanyZhou, I've confirmed that the change would not effect user's script, so we don't need to wait for major release.

**Review by BethanyZhou — APPROVED** [review]

**Pull request merged**
