### PR TITLE
Add Id to deployment cmdlets

### PR DESCRIPTION
**Pull request by vivsriaus**
1. Add -Id parameter to deployment cmdlets
2. Add a test for deployment
3. Update help
4. Remove Test-AzureResource and Test-AzureResourceGroup cmdlets

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivsriaus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (visriniv). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@vivsriaus resolve conflicts

**Comment by vivsriaus** [comment]
@ogail Done.

**Comment by markcowl** [comment]
on demand run here:http://azuresdkci.cloudapp.net/job/powershell-on-demand/215/

**Comment by vivsriaus** [comment]
@markcowl @ogail one of the profile tests is failing. Is someone fixing it?

**Comment by stankovski** [comment]
@vivsriaus please sync with upstream. The fix should be there

**Comment by markcowl** [comment]
@vivsriaus Yes, the fix is there - the failing tests aremarked as runtype=Liveonly (not AcceptanceType=LiveOnly) in upstream

**Comment by vivsriaus** [comment]
@markcowl @stankovski Done. I've sync'ed with upstream and kicked off the on-demand job here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/217/

I'll let you know as soon as I see them succeed.

**Comment by vivsriaus** [comment]
@markcowl @stankovski The on demand job succeeded. Can you please merge this?

**Pull request merged**
