### PR TITLE
[AzureFirewall] NAT and FQDN Tags

### PR DESCRIPTION
**Pull request by fanymanea**
### NAT Rule Collection

- A new type of Azure Firewall rule collection which allows users to perform DNAT on their packets.
- Each collection contains a list of NatRules, each rule specifying its own criteria for DNAT

### FQDN Tag

- A way for users to specify services (e.g. AzureBackup, WindowsUpdate) which are allowed/denied through the firewall (instead of specifying a list of FQDNs - which they may not even know)
- FqdnTags cannot be used in the same rule with TargetFqdns

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by fanymanea** [comment]
[Live tests results](https://azuresdkci.westus2.cloudapp.azure.com/view/az-ps-network-tests/job/ps-network-test-firewall/6/)

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by praries880** [comment]
Retrying CI because of test failure in the last one that do not seem related to the PT at all.

**Comment by praries880** [comment]
@fanymanea Kindly take care of merge conflicts

**Comment by praries880** [comment]
@azuresdkci add to whitelist

**Comment by maddieclayton** [comment]
Will need to retarget this at release-2018-09-17 as soon as Mikhail's PR gets merged there.

**Pull request merged**
