### PR TITLE
Added storage account information to Get-AzureHDInsightCluster's response

### PR DESCRIPTION
**Pull request by nityasharma**
Get-AzureHDInsightCluster response does not include storage information like Default storage account and container.This is necessary to support the scenario of getting Job output files.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nityasharma__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by azurecla** [comment]
__@nityasharma__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by stankovski** [comment]
@shefaliv please review this PR

**Comment by shefaliv** [comment]
Approved!

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by shefaliv** [comment]
@markcowl This is an Azure Compute test failing and has nothing to do with this changeset. Can you please rerun the build?

**Comment by nityasharma** [comment]
@markcowl I was going through the build failure report and by mistake hit the retry button. I don't see any option for cancelling the build now.

**Pull request merged**
