### PR TITLE
Adding Reset Vpn Client Shared Key cmdlet

### PR DESCRIPTION
**Pull request by henry416**
## Description

Added a Reset VPN Client Shared Key cmdlet
VPN Client shared key is managed internally by the gateway resource, only a RESET operation is exposed.
Shared key is currently only used by OpenVPN and is non-functional for other P2S cases, updated OpenVPN test case accordingly.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@henry416 Hey Henry, would you mind filing a design review for the change being made in this PR: https://github.com/Azure/azure-powershell-cmdlet-review-pr

We require a design review to be completed for any public API change is made to the cmdlets in Azure PowerShell.

**Comment by praries880** [comment]
@henry416 
Few points:
* This PR needs to target the [network-october-releas](https://github.com/Azure/azure-powershell/tree/network-october-release)
* As Cormac mentioned, you need to create a design review for the changes in the PR.

@MikhailTryakhov @chandrasekarsrinivasan can you guys help @henry416  with the various steps needed to get this PR approved?

**Comment by MikhailTryakhov** [comment]
@henry416 we ask you for months to follow our process and read our docs where should contribution go,,,
Please read it and it'll save you and us from extra-steps need to be done

**Comment by praries880** [comment]
@henry416 can you work with @MikhailTryakhov to open a design review for the new cmdlet being added here. The PR neds to target the october branch for network instead of preview.

Once the design review is done, you need to fix all the CI issues.

**Comment by henry416** [comment]
Sorry for the late reply.
I will submit a design review and retarget

**Pull request closed without merging**
