### PR TITLE
[StorageSync] OOB release

### PR DESCRIPTION
**Pull request by VeryEarly**
Will merge the version upgrade after PR validation and MSI been verified.

---------

## Description

**AFS Features**
 
- 2022-09-01 Api version bump
- Managed Identity
- Fast DR v2 protocol changes
- Synchronize Interop library from XSync dev to Az powershell repo
- Re-record all existing tests
 
**Az Powershell infrastructure issue**
 
- AFS Track1 is obsolete and hence we have to dump the code here in az powershell. Afs Track2 can be used with az powershell auto generation only.
- Support Subscription as string and Guid Latest track1 sdk generation causes error due to this bug.
- Az Storage Account creation hides bypass=AzureServices. This cause issues while creating Cloudendpoint in Managed Identity Mode
- Tenant Id issue of passing mocked guid instead of Recorded tenant guid
- Migrate from Charp autorest to Powershell autorest 
- Update Authorization package as existing package was not working.
 
**Create Cmdlets**
 
- Set-StorageSyncServiceIdentity : Migration procedure contains multiple steps. Cluster Name Server needs to be handled due the fact that ServerEndpoint has Cluster Name Resource Id in it.
- Set-AzStorageSyncCloudEndpointPermission : Ensuring RBAC permission for CloudEndpoint which is for StorageSyncService.Identity -> (File share , storage account)
- Set-AzStorageSyncServerEndpointPermission : Ensuring RBAC permissions on Server Endpoint which is for Server-> File share. In ServerEndpoint, It contains Cluster Name ResourceId and hence we have to get all cluster node servers and then apply rbac who has ApplicationId in it. Similar logic elsewhere.
- Set-AzStorageSyncServer : PAtching a server to enable Server Identity
 
**Update Cmdlets**
 
- Add/Delete RBAC permissions in CEP/SEP flows
- Managed Identity Tests
- Create endpoints and then migrate
- Migrate and then create Endpoints
 
**Test bugs**
 
- Getting storage account tenant id was using Get-AzTenant which may return multiple. Use Get-AzContext instead.
image
image
image

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by ankushbindlish2** [comment]
**AFS Features**

- 2022-09-01 Api version bump
- Managed Identity
- Fast DR v2 protocol changes
- Synchronize Interop library from XSync dev to Az powershell repo
- Re-record all existing tests

**Az Powershell infrastructure issue**

- AFS Track1 is obsolete and hence we have to dump the code here in az powershell. Afs Track2 can be used with az powershell auto generation only.
- Support Subscription as string and Guid Latest track1 sdk generation causes error due to this bug.
- Az Storage Account creation hides bypass=AzureServices. This cause issues while creating Cloudendpoint in Managed Identity Mode
- Tenant Id issue of passing mocked guid instead of Recorded tenant guid
- Migrate from Charp autorest to Powershell autorest 
- Update Authorization package as existing package was not working.

**Create Cmdlets**

- Set-StorageSyncServiceIdentity : Migration procedure contains multiple steps. Cluster Name Server needs to be handled due the fact that ServerEndpoint has Cluster Name Resource Id in it.
- Set-AzStorageSyncCloudEndpointPermission : Ensuring RBAC permission for CloudEndpoint which is for StorageSyncService.Identity -> (File share , storage account)
- Set-AzStorageSyncServerEndpointPermission : Ensuring RBAC permissions on Server Endpoint which is for Server-> File share. In ServerEndpoint, It contains Cluster Name ResourceId and hence we have to get all cluster node servers and then apply rbac who has ApplicationId in it. Similar logic elsewhere.
- Set-AzStorageSyncServer : PAtching a server to enable Server Identity

**Update Cmdlets**

- Add/Delete RBAC permissions in CEP/SEP flows
- Managed Identity Tests
- Create endpoints and then migrate
- Migrate and then create Endpoints

**Test bugs**

- Getting storage account tenant id was using Get-AzTenant which may return multiple. Use Get-AzContext instead.
image
image
image

**Review by NoriZC — APPROVED** [review]

**Pull request merged**
