### PR TITLE
[Get-AzMetric.md]fix: don't worked example 4

### PR DESCRIPTION
**Pull request by sakkuntyo**
fix: don't worked example 4

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by Nickcandy — APPROVED** [review]

**Review by Nickcandy — DISMISSED** [review]

**Comment by sakkuntyo** [comment]
Sorry, there were also errors in the corrected script. I will specify the corrections later.

**Comment by Nickcandy** [comment]
Just a friendly reminder: our code freeze deadline is at 6 PM PST on April 22nd. If your code is intended for this release, please ensure it is completed as soon as possible.

**Comment by YanaXu** [comment]
Hi @sakkuntyo , I feel the update is not correct. I'll convert it to draft. If you test it, could you provide your test logs or screenshot amd change it to be ready again?

**Comment by sakkuntyo** [comment]
I apologize for the delay. I have corrected my incorrect modification. The left side was the incorrect modification, and the right side is the correct one.

https://github.com/Azure/azure-powershell/pull/24653/commits/4f6819f44be4d1e2bcb2e6784f80468f6c74be5f

incorrect fix:
There were errors in the designation and output of the red line section.
image

correct fix:
image

**Review by YanaXu — APPROVED** [review]

**Pull request merged**
