### PR TITLE
Add IsCloudRecoveryReady in existing BackupInfo

### PR DESCRIPTION
**Pull request by caoyihua**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by caoyihua** [comment]
Added a new Boolean property called ‘IsCloudRecoveryReady’ for the BackupInfo returned from Get-AzsBackup, with this property, customer can check whether the backup can be used for cloud recovery scenario or not.

**Comment by caoyihua** [comment]
The default build failed due to "There is not enough space on the disk.", could somebody from build team take a look?

**Comment by caoyihua** [comment]
@markcowl, do you know who can help on default build failure "There is not enough space on the disk." ? Will that block the merge?

**Comment by bganapa** [comment]
@msJinLei Could you please help with this PR as well ?

**Comment by bganapa** [comment]
@markcowl This is also failing with There is not enough space on the disk. [c:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\Commands.Compute.Test.csproj]

Could you pls look at this?

**Pull request merged**
