### PR TITLE
Dev: Azure Automation cmdlet changes

### PR DESCRIPTION
**Pull request by safeermohammed**
Azure Automation cmdlet changes
bug fixes and updates

### CODE REVIEW

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/380/

**Comment by hovsepm** [comment]
please add tests.

**Comment by jianghaolu** [comment]
@safeermohammed Please update your test to an Xunit test and make sure it's annotated with `[Trait(Category.AcceptanceType, Category.CheckIn)]`.

Please update this PR asap otherwise it will not be included in 1.1.0 release.

**Comment by safeermohammed** [comment]
These are unit tests, do you still want them to be using Xunit?

**Comment by jianghaolu** [comment]
Yes that's the requirement.

**Comment by jianghaolu** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/401/

**Pull request merged**
