### PR TITLE
Add support for forced tunneling/management subnet and management IP configuration

### PR DESCRIPTION
**Pull request by iatodoro**
## Description

To support "forced tunneling" scenarios we need to be able to assign a separate subnet and public IP address to Azure Firewall that it will use for control plane traffic. This PR introduces changes to support this functionality.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by iatodoro** [comment]
Cmdlet review PR: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/444

**Comment by VeryEarly** [comment]
Hi @iatodoro ,

Please fix CI failures

**Comment by VeryEarly** [comment]
Hi @iatodoro ,
 record json for TestAzureFirewallCRUDwithManagementIpConfig is still missing

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by KpaBap** [comment]
Though the test recording is included and it passes locally, it seems to be failing because the Azure SDK version used in the build pipeline does not have the new property being added. We basically need the Network-December version of the SDK. How can this be pulled in?

**Comment by KpaBap** [comment]
This looks like it's failing because we need to pull in the December release of Azure SDK for NET. How can this be done? I don't see an official December release yet on the SDK repo.

**Comment by isra-fel** [comment]
Kindly ping @iatodoro

**Comment by KpaBap** [comment]
@isra-fel This is currently blocked on the latest Networking SDK nuget package being available.

**Comment by iatodoro** [comment]
@isra-fel This is currently blocked on the latest Networking SDK nuget package being available.

**Comment by iatodoro** [comment]
@isra-fel Can we re-trigger the tests please? The new SDK package is now out.

**Comment by iatodoro** [comment]
Abandoning this PR because it's against an old branch. Opened new PR here: https://github.com/Azure/azure-powershell/pull/10933

**Pull request closed without merging**
