### PR TITLE
Normalize ShouldProcess/ShouldContinue benavior, and change Tag Type from Hashtable[] to Hashtable

### PR DESCRIPTION
**Pull request by blueww**
The change include:
1. Normalize ShouldProcess/ShouldContinue benavior, the currently behavior is aligned with the design we have talked in mail.
2. Change Tag Type from Hashtable[] to Hashtable
3. Change the Help and change log 
4. Change 2 unit test since the way ShouldContinue/Shouldprocess change, The remove queue/table always pass since ShouldContinue always return true with the way run unit test.

What test we have done:
1. We have done target test for all changed cmdlets and reviewed the related help.
2. Regression test has passed.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@blueww__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by blueww** [comment]
The on-demand test is in http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1025/

**Comment by hovsepm** [comment]
@blueww please pull from upstream and resolve merge conflicts.

**Comment by blueww** [comment]
@hovsepm The conflict is resolved.

**Comment by blueww** [comment]
The on demand test passed in http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1027/

**Pull request merged**
