### PR TITLE
Changes to Support Accelerated Virtual Network Datapath for ExpressRoute

### PR DESCRIPTION
**Pull request by pashukl**
Description of Changes:
- Added a switch ExpressRouteGatewayBypass to the Virtual Network
  Gateway Connection Command.
- Added a Test Case with the switch ExpressRouteGatewayBypass

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by pashukl** [comment]
@maddieclayton :  The SignatureIssues.csv is showing following error:
""AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
"c:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand","New-AzureRmVirtualNetworkGatewayConnection","1","8410","Parameter ExpressRouteGatewayBypass of cmdlet New-AzureRmVirtualNetworkGatewayConnection does not follow the enforced naming convention of using a singular noun for a parameter name.","Consider using a singular noun for the parameter name."

What exactly is expected of this ?  The flag ExpressRouteGatewayBypass looks ok to me.

**Comment by maddieclayton** [comment]
@pashukl Yes, your parameter name is fine.  Please follow the instructions linked in doc: https://github.com/Azure/azure-powershell/blob/preview/documentation/Debugging-StaticAnalysis-Errors.md

**Comment by pashukl** [comment]
@maddieclayton : Can you please review and approve this change.  The build seems fine now :https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/6861/

**Comment by pashukl** [comment]
@markcowl , @maddieclayton , @cormacpayne :  Can one of you please review this !

**Pull request merged**
