### PR TITLE
Renamed 'IdentifyTopFatFlow' parameter to `EnableFatFlowLogging` on AzureFirewall

### PR DESCRIPTION
**Pull request by Gizachew-Eshetie**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by vidai-msft** [comment]
@Gizachew-Eshetie renaming a PowerShell parameter name is considered as breaking change which is not allowed to be released in the current sprint. You have 2 options:
1. The next sprint (2022 Sept) is for breaking-change release. So you can raise the PR again in the next month if still necessary.
2. Make the original parameter name as an alias of the new one so that the existing PS code from the customer side won't break. And then we can roll out the change in this sprint.

Let me know if you have any questions.

**Comment by Gizachew-Eshetie** [comment]
> @Gizachew-Eshetie renaming a PowerShell parameter name is considered as breaking change which is not allowed to be released in the current sprint. You have 2 options:
> 
> 1. The next sprint (2022 Sept) is for breaking-change release. So you can raise the PR again in the next month if still necessary.
> 2. Make the original parameter name as an alias of the new one so that the existing PS code from the customer side won't break. And then we can roll out the change in this sprint.
> 
> Let me know if you have any questions.

@vidai-msft , option 2 is fine and added the old parameter name as an alias.

**Comment by vidai-msft** [comment]
@Gizachew-Eshetie you also need to suppress the breaking change static analysis error based on the guidance https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes.

**Comment by Gizachew-Eshetie** [comment]
> @Gizachew-Eshetie you also need to suppress the breaking change static analysis error based on the guidance https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes.

@vidai-msft Done.

**Comment by vidai-msft** [comment]
@Gizachew-Eshetie I just noticed you changed the property name IdentifyTopFatFlow for the object PSAzureFirewall. This is also a breaking change for the output object and is not allowed in this sprint. You can create a new property but have to keep the old one as it is for now. You need to do the following things:
1. Undo the breaking change suppression
2. Add the property IdentifyTopFatFlow back in the PSAzureFirewall class and make it like a dup of the new one EnableFatFlowLogging so that the code won't be broken for those customers who have already used the old property in their scripts.
3. Re-generate the help docs of the cmdlets New-AzFirewall and Set-AzFirewall per https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md

In the next sprint, which as mentioned is for breaking change release, you can remove the dup property IdentifyTopFatFlow.

**Comment by Gizachew-Eshetie** [comment]
> @Gizachew-Eshetie I just noticed you changed the property name IdentifyTopFatFlow for the object PSAzureFirewall. This is also a breaking change for the output object and is not allowed in this sprint. You can create a new property but have to keep the old one as it is for now. You need to do the following things:
> 
> 1. Undo the breaking change suppression
> 2. Add the property IdentifyTopFatFlow back in the PSAzureFirewall class and make it like a dup of the new one EnableFatFlowLogging so that the code won't be broken for those customers who have already used the old property in their scripts.
> 3. Re-generate the help docs of the cmdlets New-AzFirewall and Set-AzFirewall per https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md
> 
> In the next sprint, which as mentioned is for breaking change release, you can remove the dup property IdentifyTopFatFlow.

@vidai-msft when this sprint ends and when the next sprint starts? To avoid rework, can we keep this PR for the next sprint?

**Comment by vidai-msft** [comment]
> > @Gizachew-Eshetie I just noticed you changed the property name IdentifyTopFatFlow for the object PSAzureFirewall. This is also a breaking change for the output object and is not allowed in this sprint. You can create a new property but have to keep the old one as it is for now. You need to do the following things:
> > 
> > 1. Undo the breaking change suppression
> > 2. Add the property IdentifyTopFatFlow back in the PSAzureFirewall class and make it like a dup of the new one EnableFatFlowLogging so that the code won't be broken for those customers who have already used the old property in their scripts.
> > 3. Re-generate the help docs of the cmdlets New-AzFirewall and Set-AzFirewall per https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md
> > 
> > In the next sprint, which as mentioned is for breaking change release, you can remove the dup property IdentifyTopFatFlow.
> 
> @vidai-msft when this sprint ends and when the next sprint starts? To avoid rework, can we keep this PR for the next sprint?

@Gizachew-Eshetie this sprint will finish by the end of this month () and the next sprint start on Sep

> > @Gizachew-Eshetie I just noticed you changed the property name IdentifyTopFatFlow for the object PSAzureFirewall. This is also a breaking change for the output object and is not allowed in this sprint. You can create a new property but have to keep the old one as it is for now. You need to do the following things:
> > 
> > 1. Undo the breaking change suppression
> > 2. Add the property IdentifyTopFatFlow back in the PSAzureFirewall class and make it like a dup of the new one EnableFatFlowLogging so that the code won't be broken for those customers who have already used the old property in their scripts.
> > 3. Re-generate the help docs of the cmdlets New-AzFirewall and Set-AzFirewall per https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/help-generation.md
> > 
> > In the next sprint, which as mentioned is for breaking change release, you can remove the dup property IdentifyTopFatFlow.
> 
> @vidai-msft when this sprint ends and when the next sprint starts? To avoid rework, can we keep this PR for the next sprint?

@Gizachew-Eshetie you can take a look at our scheduled milestones at https://github.com/Azure/azure-powershell/milestones. 
You can keep this PR here. However, since you plan to release code with breaking changes, better if you can raise a PR with breaking change attribute to notify our customers that some property would break in the upcoming release. You can refer to the doc https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-attribute-help.md

Let me know if you have any questions.

**Comment by Gizachew-Eshetie** [comment]
@vidai-msft reverted back commit created to replace breaking changes attribute with alias attribute.

**Comment by Gizachew-Eshetie** [comment]
Added [this PR](https://github.com/Azure/azure-powershell/pull/19363) so we can preannounce in September release since the breaking change release is in October.

**Comment by wyunchi-ms** [comment]
Hi @Gizachew-Eshetie , please resolve the conflicts. Thanks

**Comment by wyunchi-ms** [comment]
Please rebase the branch. There are too many commits

**Comment by Gizachew-Eshetie** [comment]
> Please rebase the branch. There are too many commits

@wyunchi-ms Done.

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
