### PR TITLE
Organizational Unit in Azure RemoteApp RDFE cmdlets now accepts Unicode characters.

### PR DESCRIPTION
**Pull request by zaevans**
Organizational Unit in Azure RemoteApp cmdlets now accepts Unicode characters.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@zaevans__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (zaevans). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@zaevans please update the title for something more meaningful and send a Code Review request once you are done with this feature.

**Comment by hovsepm** [comment]
@zaevans Please add your fixed in the ChangeLog.md under 2016.02.02 version 1.1.1 (you will need to pull from upstream first).

**Pull request merged**
