### PR TITLE
Added subnet property to new-AzLoadBalancerBackendAddressConfig cmdlet. Fixed piping in Set/Remove-AzLoadBalancerBackendAddressPool

### PR DESCRIPTION
**Pull request by irrogozh**
…t. Fixed piping in Set/Remove-AzLoadBalancerBacknedAddressPool cmdlets.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by isra-fel — COMMENTED** [review]
Hi @irrogozh Why did you raise 2 PRs? #15496

**Comment by irrogozh** [comment]
@isra-fel , I hoped that if it's possible to merge pr to main branch - to release it faster. Changes are not coupled with API version - it's mostly fixing bugs and adding missing property.

**Comment by isra-fel** [comment]
@irrogozh yes it's OK to submit PR to main branch. However in that case, according to our [PR strategies for network branch](https://github.com/Azure/azure-powershell-pr/wiki/PR-strategies-for-network-branch#when-to-raise-prs-against-main-branch), instead of submitting an identical PR to network branch, the correct way is to
1. Submit PR to main, get it merged
2. Submit a second PR to sync main to network branch

Now that #15496 has already been merged to `network-march` (as I was not aware of this PR when reviewing that one), I'm planning to revert that merge and merge this PR, and you'll need to sync main to network branch after our August release. Does it sound OK to you?

**Comment by irrogozh** [comment]
@isra-fel , sounds great! please do it:)

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
@irrogozh so this PR was merged and `network-march` was reset. As plan I will notify you to sync main to network branch after next official release, which is early August.
Thanks :)

**Pull request merged**
