### PR TITLE
Update help file for AzureRmResourceGroup cmdlets

### PR DESCRIPTION
**Pull request by chidmdxx**
Updates the help file for the AzureRmResourceGroup cmdlets

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/223/

**Comment by stankovski** [comment]
Re-running on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/226/

**Comment by chidmdxx** [comment]
merged with upstream to fix the on demand failures

**Comment by hovsepm** [comment]
re-running on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/228/

**Pull request merged**
