### PR TITLE
Fix remove autoscale command

### PR DESCRIPTION
**Pull request by russsantos**
## Description

The Remove-AzApplicationGatewayAutoscaleConfiguration PS command was failing due to SslPolicy being passed as a parameter, rather than AutoscaleConfiguration. Small fix for this issue and updated a failing test that executes the remove autoscale configuration command. Verified the fix through the following:
1. Remove SslPolicy from the test (remove autoscale would not throw an exception if ssl policy exists because SslPolicy is being passed as a target to the remove command)
2. Verify that the test fails
3. Apply the fix
4. Verify that the test passes

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by vidai-msft** [comment]
@russsantos can you please update the ChangeLog.md?

**Comment by russsantos** [comment]
> @russsantos can you please update the ChangeLog.md?

Updated ChangeLog.md with snippet about the change

**Comment by vidai-msft** [comment]
@russsantos The cmdlet `Remove-AzApplicationGatewayAutoscaleConfiguration` appears in 4 test cases. `TestApplicationGatewayCRUDRewriteRuleSet`, `TestApplicationGatewayCRUDRewriteRuleSetWithConditions`, `TestApplicationGatewayCRUD3` (Skipped) and `TestApplicationGatewayCRUDSubItems`. Since this command always failed previously, can you please re-record the others? `TestApplicationGatewayCRUD3` is skipped so you can ignore. Thanks!

**Comment by russsantos** [comment]
> @russsantos The cmdlet `Remove-AzApplicationGatewayAutoscaleConfiguration` appears in 4 test cases. `TestApplicationGatewayCRUDRewriteRuleSet`, `TestApplicationGatewayCRUDRewriteRuleSetWithConditions`, `TestApplicationGatewayCRUD3` (Skipped) and `TestApplicationGatewayCRUDSubItems`. Since this command always failed previously, can you please re-record the others? `TestApplicationGatewayCRUD3` is skipped so you can ignore. Thanks!

Updated and recorded the other tests that used the remove auto scale config command

**Review by vidai-msft — APPROVED** [review]
LGTM

**Pull request merged**
