### PR TITLE
[Do Not Merge] Added daemon and secret-key option in ChefExtension for ASM and ARM commands.

### PR DESCRIPTION
**Pull request by Aliasgar16**
In-progress.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Aliasgar16__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
@Aliasgar16 please resolve the merge conflicts

**Comment by Aliasgar16** [comment]
@cormacpayne I will resolve all the conflicts once I am done adding test cases for the functionality.

**Comment by Aliasgar16** [comment]
Cherry-picked the commits and created another [PR](https://github.com/Azure/azure-powershell/pull/3387) as it was impossible to re-base this one.

**Pull request closed without merging**
