### PR TITLE
Fix StorageMb parameter

### PR DESCRIPTION
**Pull request by hungmai-msft**
Ignore user input for elastic pool's StorageMB and recalculate based on Dtu and coefficient of the edition

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hungmai-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hungmai). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hungmai-msft** [comment]
Per Mark's request, this is similar to PR #715

**Comment by markcowl** [comment]
post check-in build here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/138/

**Comment by hungmai-msft** [comment]
My bad, I haven't rebased on the release-0.9.7 branch.

New build is triggered at: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/140/

**Comment by hungmai-msft** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/429/

**Pull request merged**
