### PR TITLE
[AzureRT] Sprint 58 update

### PR DESCRIPTION
**Pull request by hyonholee**
- Disable-AzureRmVMDiskEncryption cmdlet
- Fix piping issue of New-AzureRmVM cmdlet
- Fix forceRerun parameter to accept any string in Set-AzureRmVMExtension cmdlet
- Add "EA" permission to Set-AzurePlatformVMImage cmdlets
- Update the default version of BGInfo and VMAccess extension to 2.*

### CODE REVIEW

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/612/

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
new on demand run: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/621/

**Comment by markcowl** [comment]
new on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/622/

**Comment by hovsepm** [comment]
last on demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/629/

**Pull request merged**
