### PR TITLE
Keep Networking-AzureFirewall branch up to date

### PR DESCRIPTION
**Pull request by fanymanea**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by praries880** [comment]
@fanymanea 
Seems the library referenced for networking SDK is missing a few firewall related definitions, the netcore and desktop builds are broken.

https://travis-ci.org/Azure/azure-powershell/builds/418934490#L1603
https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/6804/artifact/src/Publish/TestResults/FailingTests/Microsoft.Azure.Commands.KeyVault.Test.dll.html

Can you make sure that the included network SDK does indeed have the firewall related definitions?

**Comment by fanymanea** [comment]
@praries880 
I have no idea how to handle this build failure. I created [a signed build of my own](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1083/), and it just passes. Any advice?

**Comment by praries880** [comment]
@fanymanea  I have started an on demand build : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/1055.
This will help us see if the changes  are good to go or not (in addition to the CI stuff).

**Comment by praries880** [comment]
on demand : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/

**Comment by praries880** [comment]
[on demand](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/1057/) succeeded.. merging request

**Pull request merged**
