### PR TITLE
[PostgreSQL] Change api-version to 2022-01-20-preview

### PR DESCRIPTION
**Pull request by alanenriqueo**
## Description
- Changed api-version from `2021-06-01` to `2022-01-20-preview`
- Added Backups operations for flexible server: Get and List
- Added `SameZone` as a new possible value for `HaEnabled`

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @alanenriqueo can you take a look at the breaking changes in build log and let us know if they are intended?

**Comment by alanenriqueo** [comment]
Hi @isra-fel, yes, all the breaking changes are because of the change of the api version from 2021-06-01 to 2022-01-20-preview.

**Comment by isra-fel** [comment]
I understand they are caused by API version update, but breaking changes are generally considered bad user experience, so we'd like to mitigate them as much as possible.
For those inevitable breaking changes,
(1) they can't be checked in to regular releases. The next major release is in October so this PR cannot be merged until next month.
(2) You need to preannounce the breaking changes by [using special directives](https://github.com/Azure/azure-powershell/blob/main/documentation/development-docs/breakingchange-for-autogen-module.md) that add warning messages when user runs your commands. Please submit a PR to do it in this release.

**Comment by alanenriqueo** [comment]
I'll keep this PR on hold until this PR merges: https://github.com/Azure/azure-rest-api-specs/pull/20212

**Comment by isra-fel** [comment]
OK @alanenriqueo  I've marked this PR as draft for bookkeeping reason. Please click the "Ready for review" button once it's ready. Thanks.

**Comment by wyunchi-ms** [comment]
Hi, this PR is not active more than one year and contains a lot of conflicts. I'm closing this. Please feel free to reopen it when you want to pick up it again.

**Pull request closed without merging**
