### PR TITLE
Cplat capacity reservation feature

### PR DESCRIPTION
**Pull request by grizzlytheodore**
## Description
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/957
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/967

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
waiting for https://github.com/Azure/azure-powershell/pull/15511 to be merged first. which this branch is based onto.

**Comment by isra-fel** [comment]
Now that 15511 was merged, please sync your branch and resolve the comflicts. Thanks

**Comment by isra-fel** [comment]
I assume the design review for this PR is https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/967 correct?
Next time I suggest put that in PR description so we can easily find it. Thank you

**Review by isra-fel — APPROVED** [review]
Looks good!

**Comment by grizzlytheodore** [comment]
@isra-fel  hello, this PR is complete now. Please review and merge thank you!

**Pull request merged**
