### PR TITLE
Consume new SDK and add support to relative path in Import-, Export- and New-

### PR DESCRIPTION
**Pull request by NonStatic2014**
Consume new SDK and add support to relative path in Import-, Export- and New-

### CODE REVIEW

**Comment by NonStatic2014** [comment]
On demand build: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/903

**Comment by NonStatic2014** [comment]
On demand build passed.

**Comment by markcowl** [comment]
@NonStatic2014 No test updates for the cmdlet change?

**Comment by NonStatic2014** [comment]
no test update is needed in this change.

**Comment by NonStatic2014** [comment]
This issue is tracking the work of adding UT for Import- and Export- cmdlet. Currently I'm blocked on how to set the correct SessionState.Path.CurrentFileSystemLocation.Path in the UT.

https://github.com/Azure/azure-powershell/issues/2474

**Pull request merged**
