### PR TITLE
Automation cmdlets for next powershell release

### PR DESCRIPTION
**Pull request by safeermohammed**
Has following cmdlets
Webhooks
Paging fixes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@safeermohammed__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (safeerm). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by safeermohammed** [comment]
I am getting below build failures after I took the latest from 
https://github.com/Azure/azure-powershell  dev branch, Any Idea why that would happen?

Unable to find version '12.2.0-preview' of package 'Microsoft.WindowsAzure.Management.Compute'.
  Unable to find version '7.0.0' of package 'Microsoft.WindowsAzure.Management.Network'.
  Unable to find version '1.0.3' of package 'Microsoft.WindowsAzure.Management.Automation'.
  Unable to find version '0.26.0-prerelease' of package 'Microsoft.Azure.Management.Sql'.
  Unable to find version '0.15.10-preview' of package 'Microsoft.Azure.Management.DataFactories'.
  Unable to find version '1.5.0-preview' of package 'Microsoft.DataTransfer.Gateway.Encryption'.
  Unable to find version '0.9.1-preview' of package 'Microsoft.Azure.Management.KeyVault'.
  Unable to find version '1.2.1-preview' of package 'Microsoft.Azure.Management.Dns'.
  Unable to find version '1.4.1' of package 'Microsoft.Azure.Management.StreamAnalytics'.
  Unable to find version '2.0.0' of package 'Microsoft.WindowsAzure.Management.RemoteApp'.
  Unable to find version '2.0.3-preview' of package 'Microsoft.Azure.Management.Network'.

**Comment by safeermohammed** [comment]
Build was fine before taking latest

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Pull request merged**
