### PR TITLE
Updated ApiVersion from 2020-07-01 to 2020-11-01

### PR DESCRIPTION
**Pull request by v-shhatt**
Updated ApiVersion from 2020-07-01 to 2020-11-01

## Description

Updated ApiVersion from 2020-07-01 to 2020-11-01

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @v-shhatt ,
1. What's the reason to update api version? I don't see the update of SDK.
2. Please don't just replace the api version in URL, you need to rerecord these test cases.

**Comment by BethanyZhou** [comment]
Hi @v-shhatt , please update change log if you want to the API version change available in next release.

**Comment by v-shhatt** [comment]
> Hi @v-shhatt ,
> 
> 1. What's the reason to update api version? I don't see the update of SDK.
> 2. Please don't just replace the api version in URL, you need to rerecord these test cases.

Have updated change with the release notes.

**Comment by v-shhatt** [comment]
> Hi @v-shhatt , please update change log if you want to the API version change available in next release.

Have updated change log with version release notes

**Comment by BethanyZhou** [comment]
Hi @v-shhatt , 

- please add the description for your change under upcoming release section and **do not** remove other's information in change log. Here is the guidance may help you: https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/azure-powershell-developer-guide.md#change-log

- As @wyunchi-ms metioned,  you need re-record all test cases which may have been affected by this api version change rather than simply replace "2020-07-01" to "2020-11-01".

**Pull request closed without merging**
