### PR TITLE
[AppGW] Adding probe, multisite and URl routing support

### PR DESCRIPTION
**Pull request by kagamsft**

### CODE REVIEW

**Comment by jianghaolu** [comment]
@azuresdkci retest this please

**Comment by kagamsft** [comment]
All tests are passing on local machine in playback mode but build fails because of test failure.
Re-recording the test. Also, restarted the build.

**Comment by kagamsft** [comment]
Build is failing with below error. I am able to record the test successfully, also tests run fine in playback mode. I have added ApplicationGatewayPathRule as part of my changes so it is definitely related to my changes.

Could someone please suggest how to debug further?


Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineTests.TestVirtualMachinePlan [FAIL]
        System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not load type 'Microsoft.Azure.Management.Network.Models.ApplicationGatewayPathRule' from assembly 'Microsoft.Azure.Management.Network, Version=3.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35'.

**Comment by jianghaolu** [comment]
@kagamsft 
Compute tests are failing because the tests are referencing your older .NET library - you will need to update the network .NET library version everywhere in the ResourceManager uber solution.

**Comment by jianghaolu** [comment]
@kagamsft 
Could you send another pull request targeting branch 'release-1.1.0' with your fix?
Thanks

**Pull request closed without merging**
