### PR TITLE
Reservations RP 2018-06-01: Add CosmosDb in reserved resource enum type. Add name property in PatchProperties

### PR DESCRIPTION
**Pull request by luluRagdoll**
## Description

Add CosmosDb in reserved resource enum type. 
Add name property in PatchProperties

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by luluRagdoll** [comment]
Working on resolving the CI failure

**Comment by deathly809** [comment]
@luluRagdoll Why did you add me and Bala as reviewers?  Is this in Azure Stack?

**Comment by luluRagdoll** [comment]
You two were suggested as the reviewers in the PR reviewer section after I submitted this PR.

**Comment by deathly809** [comment]
@luluRagdoll  We only review for Azure Stack.  I removed us, you should add @maddieclayton/ @cormacpayne/@MiYanni

**Comment by maddieclayton** [comment]
@luluRagdoll Not sure how, but looks like you picked up a bunch of changes from Stack.  Can you rebase so only your changes are added?

**Comment by maddieclayton** [comment]
@luluRagdoll please link your cmdlet design review from here: https://github.com/Azure/azure-powershell-cmdlet-review-pr

**Comment by maddieclayton** [comment]
Closing in favor of: https://github.com/Azure/azure-powershell/pull/7164

**Pull request closed without merging**
