### PR TITLE
Added operation parameters and operation steps in MI operations PS cmdlet

### PR DESCRIPTION
**Pull request by toki95**
Added operation parameters and operation steps in MI operations PS cmdlet

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by toki95** [comment]
The build is failing because nugget package 1.44 hasn't been deployed yet. Waiting for that.

**Comment by toki95** [comment]
Waiting for https://www.nuget.org/packages/Microsoft.Azure.Management.Sql to show new 1.44.4 version.

**Comment by wyunchi-ms** [comment]
When will the sdk be ready?

**Comment by toki95** [comment]
> When will the sdk be ready?

I was hoping soon,m but due to no-fly zones, it will be delayed.

**Comment by isra-fel** [comment]
Kindly ping @toki95

**Comment by toki95** [comment]
> Kindly ping @toki95

Sorry, there is nothing I can do until version 1.44 gets deployed.

**Comment by msJinLei** [comment]
> > Kindly ping @toki95
> 
> Sorry, there is nothing I can do until version 1.44 gets deployed.

@toki95 Can we close this PR now since long time no update. You can re-submit a new one when the feature is ready.

**Comment by toki95** [comment]
@msJinLei sorry for the delay, there were some issues with 1.44 client I am working on this again.

**Comment by toki95** [comment]
waiting for https://github.com/Azure/azure-powershell/pull/12802 to be merged.
There we huge changes related to 1.44 nugget version and because of that I am dependant on this.

**Comment by toki95** [comment]
Validation has passed.
We are ready for merge.

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
