### PR TITLE
Added configuration name validation and improved error handling for Import-AzAutomationDscConfiguration

### PR DESCRIPTION
**Pull request by lwajswaj**
Added configuration name validation when running Import-AzAutomationDscConfiguration to solve issue #7738 and #6899.
Also, improved error handling to show the actual returned error instead of a BadResponse message.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by vrdmr** [comment]
@avkaur Could you please take a look. 

FYI/ @Azure/azureautomation

**Comment by mgreenegit** [comment]
Tagging issue
https://github.com/Azure/azure-powershell/issues/6899

**Comment by lwajswaj** [comment]
Any reason why both referenced issues are not closed yet?

**Comment by mgreenegit** [comment]
@lwajswaj sounds good, I will comment back to each.

THANK YOU!!!  Your work on this is very much appreciated.

**Pull request merged**
