### PR TITLE
Implemented bootstrap option for chef extension

### PR DESCRIPTION
**Pull request by siddheshwar-more**
Added changes to support -BootstrapOptions  option for chef extension to send bootstrap config in JSON format.

EX: -BootstrapOptions '{"chef_node_name":"mynode", . . .}'

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@siddheshwar-more__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by siddheshwar-more** [comment]
@stankovski Could you please merge this PR?
Thank you!

**Comment by markcowl** [comment]
@siddheshwar-more We are currently working on a release for //BUILD which is using our private repository, so we will not be releasing code out of this repo until late May.  Would you prefer that I move this change into the private repo for the current release?

**Comment by siddheshwar-more** [comment]
@markcowl 
Yes. If possible, you can include this changes in next release as we already published chef extension which has bootstrap options support.

**Comment by markcowl** [comment]
@siddheshwar-more This didn't make it in to the private release for build, but we cna take it for our late May release.  We are merging private changes today and will take this up after that work is complete.

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Pull request merged**
