### PR TITLE
Brooklyn Feature:- Set AAD authentication configuration for VpnClient on Gateway resource.

### PR DESCRIPTION
**Pull request by Nilambari**
## Description

Brooklyn Feature:- Set AAD authentication configuration for VpnClient on Gateway resource.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by Nilambari** [comment]
Related PowerShell cmdlet review :- https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/309

**Comment by number213** [comment]
@MiYanni please take a look

**Comment by MiYanni** [comment]
@number213 Awaiting design review acceptance: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/309

**Comment by MiYanni** [comment]
@Nilambari Multiple test failures with `A parameter cannot be found that matches parameter name` and then names a parameter. Any ideas?

**Comment by Nilambari** [comment]
> @Nilambari Multiple test failures with A parameter cannot be found that matches parameter name and then names a parameter. Any ideas?

Can you point me to the logs? I can take a look. Thanks!

**Comment by Nilambari** [comment]
Now build is passing but I see more files changed, even though those changes are already there in Azure/network-april branch. Can you take a look and let me know. Thanks!

**Comment by MikhailTryakhov** [comment]
passed. can we finally merge it?

**Comment by Nilambari** [comment]
> passed. can we finally merge it?

Fine with me. I was just wondering, in Files changed, its showing more files changes but seems those changes are already there in network-april branch then not sure why its showing under Files changed.

**Comment by number213** [comment]
Rebased commits to remove unwanted file changes. Everything's green, @MiYanni, @cormacpayne, please take a look

**Comment by Nilambari** [comment]
Thank you so much!

**Pull request merged**
