### PR TITLE
Changed Default Values Azure File Share Backup Policy

### PR DESCRIPTION
**Pull request by sambitratha**
## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Please add an entry to `ChangeLog.md` as the PR template says.

**Comment by isra-fel** [comment]
@sambitratha the "do not merge" tag is still there. Do you want me to review this PR?

**Comment by sambitratha** [comment]
Hi @isra-fel please review this, we're yet to take a final call on whether to release this feature or not. Will finalize and let you know in a day or two. Thanks

**Comment by sambitratha** [comment]
Hi @isra-fel  resolved your comments.  Adding @pvrk  for FYI.

**Pull request closed without merging**
