### PR TITLE
Powershell change for VNG multipool

### PR DESCRIPTION
**Pull request by jiaczh**
## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from the scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** change version of module in pull request

### CODE REVIEW

**Comment by jiaczh** [comment]
Hi @isra-fel @Nickcandy ,

I was haveing issue with the pipeline task:  "Install latest modules"

"x LocalRepo/InstallModule.ps1
. : The term 'Az-Cmdlets-latest/InstallModule.ps1' is not recognized as a name of a cmdlet, function, script file, or executable program"

How to resolve the above error? 

Thanks!

**Comment by jiaczh** [comment]
Hi @isra-fel @Nickcandy 

I think I found the reason why this pipeline is not running: 
image
you can see from the pipeline that the extraction has a one extrafolder: "LocalRepo", I would sugess modify the file like the one I did above

**Comment by jiaczh** [comment]
Hi @isra-fel  @Nickcandy 

I don't think I have changed anything that cause below static analysis:
rk -**Subnet** $subnet is a null-valued parameter value.","-Subnet","Assign value for $subnet."
  "Network","New-AzVirtualNetworkGateway","3","8","Unassigned_Variable","5110","2","New-AzVpnClientRootCertificate -Name $**clientRootCertName** is a null-valued parameter value.","-Name","Assign value for $clientRootCertName."
  "Network","New-AzVirtualNetworkGateway","3","8","Unassigned_Variable","5110","2","New-AzVpnClientRootCertificate -PublicCertData $samplePublicCertData is a null-valued parameter value.","-PublicCertData","Assign value for $**samplePublicCertData**."
  "Network","New-AzVirtualNetworkGateway","4","5","Unassigned_Variable","5110","2","New-AzVirtualNetwork -Subnet $subnet is a null-valued parameter value.","-Subnet","Assign value for $subnet."
  "Network","Set-AzVirtualNetworkGateway","4","66","Unassigned_Variable","5110","2","Set-AzVirtualNetworkGateway -VpnClientRootCertificates $rootCert is a null-valued parameter value.","-VpnClientRootCertificates","Assign value for $rootCert."
  "Network","Set-**AzVirtualNetworkGateway**","6","5","Mismatched_Parameter_Value_Type","5111","2","Set-AzVirtualNetworkGateway -NatRule $vngNatRules.NatRules is not an expected parameter value type.","-NatRule","Use correct parameter value type. Expected Type is Microsoft.Azure.Commands.Network.Models.PSVirtualNetworkGatewayNatRule. Now the type is .(Command)."
  
Can we proceed with merge? thank you!

**Comment by jiaczh** [comment]
Hi @wyunchi-ms , the pipe is still not running

**Comment by jiaczh** [comment]
Hi @wyunchi-ms , thanks a lot for running the pipeline , everything is passing, and can you help approve the pr? thanks again

**Comment by wyunchi-ms** [comment]
I will merge this PR after the release branch merge back to main.

**Review by wyunchi-ms — APPROVED** [review]

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
