### PR TITLE
[DataBoxEdge] Adding cmdlets for the first time to Azure Powershell module

### PR DESCRIPTION
**Pull request by raviten**
## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/391) (_Microsoft internal only_)
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/373) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
@raviten  Do you have a cmdlet review for the PR?

**Comment by raviten** [comment]
This is a wrong format of Code, moved to this
https://github.com/Azure/azure-powershell/pull/10279

Yes, I do have a CMD LET PR
- https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/391
- https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/373

**Comment by msJinLei** [comment]
close since duplicate with #10279

**Pull request closed without merging**
