### PR TITLE
Update Az.Tools.Predictor release notes

### PR DESCRIPTION
**Pull request by dcaro**
## Description

Update the release notes for Az.Tools.Predictor

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by kceiw** [comment]
Can you add to the change log too? https://github.com/dcaro/azure-powershell/blob/aztools-relnotes/tools/Az.Tools.Predictor/Az.Tools.Predictor/ChangeLog.md

**Review by kceiw — DISMISSED** [review]

**Review by BethanyZhou — COMMENTED** [review]
I saw the version in change log is 1.0.0, should we upgrade the version of Az.Tools.Predictor.psd1 to 1.0.0 as well?
https://github.com/Azure/azure-powershell/blob/8db3f2ecec12fe823ca8be5c6b216c7856c8bb4f/tools/Az.Tools.Predictor/Az.Tools.Predictor/Az.Tools.Predictor.psd1#L14

**Comment by dcaro** [comment]
We are targeting v1.0.0 for this release. I have updated psd1 and build.props files accordingly.

**Review by BethanyZhou — APPROVED** [review]

**Comment by BethanyZhou** [comment]
Looks good to me.

**Pull request merged**
