### PR TITLE
Generation

### PR DESCRIPTION
**Pull request by Goxu92**
## Description

Adding the testing for new swagger changes to be respected in the Azure Powershell for Desktop Virtualization module.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @Goxu92 
1. May I know the reason of updating the api version? We just update the api version days ago.
1. Tou need to rerecord the test cases if you want to update the api version. But not just replace the api version in record.json.

**Comment by Goxu92** [comment]
> * May I know the reason of updating the api version? We just update the api version days ago.
> * Tou need to rerecord the test cases if you want to update the api version. But not just replace the api version in record.json.

Hey @wyunchi-ms 
For the update new api has the changes required the new field we are using in hostpool "StartVMOnConnect".
I believe I re-recorded the test cases are they not look rerecorded ? the changes would only effect hostpool since only difference between the two api's is a hostpool object field change which swagger team asks us to update the api version when there is such changes.
Please let me know if these are not enough of a explanation :) 
Thanks !

**Comment by Goxu92** [comment]
@wyunchi-ms any update required on your end ?

**Comment by wyunchi-ms** [comment]
@Goxu92 , for the second question, when you record the test case, the resource group name and resource name should be random generated every time. But the diff of your record files are only api version. For the reliability of test case, I think you need to rerecord them.

**Comment by Goxu92** [comment]
> @Goxu92 , for the second question, when you record the test case, the resource group name and resource name should be random generated every time. But the diff of your record files are only api version. For the reliability of test case, I think you need to rerecord them.

@wyunchi-ms we have been recording against our existing test account I believe that is why you are not seeing random generations. Is this against the policy because our old prs followed the similar principle.

**Comment by Goxu92** [comment]
@wyunchi-ms can you see my last comment we would like to proceed. Please let me know if the current pr doesn't fit the criteria from previous prs related with the DesktopVirtualization module. We have been recording the tests running them against our test subscription that is why data you see is not randomly generated.

**Comment by wyunchi-ms** [comment]
Got it. The resourceGroupName is hardcoded in test cases. It's fine for the recording files.

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
