### PR TITLE
Select-AzureRmSubscription: support tab-complete on subscription ID and tenant ID

### PR DESCRIPTION
**Pull request by iouri-s**
It is always a hassle to select a subscription because all we can remember is a few characters from the beginning of the GUID. Auto-complete solves this issue.
Now a user can press <Tab> to cycle through the subscriptions available to them.
Auto-complete for SubscriptionName would also be nice, but it's out of scope for this commit.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@iouri-s__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (iouris). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by pcgeek86** [comment]
@iouri-s Check out the Azure PowerShell Extensions. It supports auto-completion for a bunch of different things, although subscriptions isn't there just yet. Because of the module's framework, it will be very easy to add this. 

http://www.powershellgallery.com/packages/azureext

https://trevorsullivan.net/2016/04/23/azure-powershell-extensions-updates/

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by iouri-s** [comment]
@pcgeek86 - thanks for the pointer, I'll check out the extensions. In this case, Login-AzureRmAccount already retrieves the list of user's subscription IDs. The change I made caches it for further use in the account property that already existed for that purpose and reuses it in Select-AzureRmSubscription.

**Comment by hovsepm** [comment]
@iouri-s please resolve merge conflicts.

**Comment by iouri-s** [comment]
Resolved merge conflicts.

**Comment by pcgeek86** [comment]
@iouri-s Good deal, that's useful! Thanks

**Pull request merged**
