### PR TITLE
Get-AzureRmLogicApp with optional Name parameter

### PR DESCRIPTION
**Pull request by abbgrade**
## Description

As suggested in #7860, i changed Get-AzureRmLogicApp Name parameter to be optional and the cmdlet to return all ressources if Name is not set.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)
... i cannot find the help directory to update.

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by abbgrade** [comment]
Does anybody have an idea why there is the following error?

> Unable to find a matching HTTP request for URL 'GET /subscriptions/5250dd92-b580-46be-b327-e6596c8de196/resourceGroups/onesdk9897/providers/Microsoft.Logic/workflows?api-version=2016-06-01'

But according to the [docs](https://docs.microsoft.com/en-us/rest/api/logic/workflows/listbyresourcegroup) there is:

> GET https://management.azure.com/subscriptions/{subscriptionId}/resourceGroups/{resourceGroupName}/providers/Microsoft.Logic/workflows?api-version=2016-06-01

**Comment by cormacpayne** [comment]
@abbgrade Hey Steffen, this error is occurring because our testing framework uses recordings of previous executions of tests to mock the requests and responses from cmdlets so that our tests don't have to make live calls on our CI (which would balloon our test time). Because of this, anytime a new cmdlet is added to a test (or when a new test is added), the test will need to be re-recorded to include the new request(s) and response(s). The recording for `Test-CreateAndGetLogicAppUsingDefinitionWithActions` will need to be updated to include the new call that you added, so we will have someone from our side take care of re-recording this test and updating the corresponding JSON file.

**Comment by cormacpayne** [comment]
@abbgrade Hey Steffen, I was able to re-record the test that you updated, but I'm still seeing some build failures. I'll need to do some investigating as to what's happening on the Travis build, so I'll shoot to get this fix into the 2018-12-18 release of `Az`.

**Comment by maddieclayton** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/pull/8224

**Pull request closed without merging**
