### PR TITLE
fix http bugs

### PR DESCRIPTION
**Pull request by chenhao2020**
## Description

Webscout has flagged some URLs for having explicit http links. 

## Checklist

Change the insecure http to https

### CODE REVIEW

**Comment by VeryEarly** [comment]
the link will redirect to https based url automatically

**Comment by VeryEarly** [comment]
this link will redirect to a https based url, is this change necessary?

**Comment by chenhao2020** [comment]
I think yes. Here is the [guide](https://review.docs.microsoft.com/en-us/help/contribute/validation-ref/insecure-link?branch=master) @VeryEarly

**Comment by isra-fel** [comment]
Putting the PR on hold as the auther suggested they'll need some time to figure out next steps.

**Comment by KarenYin01** [comment]
@chenhao2020 @VeryEarly I closed this PR and let's follow up via the email thread. Thank you. :-)

**Pull request closed without merging**
