### PR TITLE
Add ComputerGroups support to Azure.OperationalInsights cmdlets

### PR DESCRIPTION
**Pull request by lwang2016**
Add ComputerGroups support to Azure.OperationalInsights cmdlets.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lwang2016__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (lewang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@lwang2016 The PR is failing due to no cmdlet help for the new cmdlet.  Please add cmdlet help.

**Comment by lwang2016** [comment]
Added cmdlet help. Thanks!

**Comment by hovsepm** [comment]
@lwang2016 please pull from upstream and resolve conflicts

**Comment by lwang2016** [comment]
Pulled from upstream and resolved conflicts. All checks passed.
Thanks for the help.

**Comment by hovsepm** [comment]
:shipit:

**Comment by lwang2016** [comment]
Thanks!

**Pull request merged**
