### PR TITLE
Exposing two  read-only properties of Application Gateway client certificate

### PR DESCRIPTION
**Pull request by 3quanfeng**
## Description

Exposing two read-only properties of Application Gateway Client Certificate for supportability.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        -  https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/916
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by VeryEarly — CHANGES_REQUESTED** [review]
- please fix test cases

**Comment by 3quanfeng** [comment]
> * please fix test cases

Thanks @VeryEarly , does the build pipeline itself depends on master branch of https://github.com/Azure/azure-rest-api-specs? the test case in this PR depends on network February branch

**Comment by VeryEarly** [comment]
> > * please fix test cases
> 
> Thanks @VeryEarly , does the build pipeline itself depends on master branch of https://github.com/Azure/azure-rest-api-specs? the test case in this PR depends on network February branch

test case failed at line: https://github.com/Azure/azure-powershell/blob/500ef236d6499b9aed352a18a75c5d5c398f092f/src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1#L3350

**Comment by 3quanfeng** [comment]
> > > * please fix test cases
> > 
> > 
> > Thanks @VeryEarly , does the build pipeline itself depends on master branch of https://github.com/Azure/azure-rest-api-specs? the test case in this PR depends on network February branch
> 
> test case failed at line:
> 
> https://github.com/Azure/azure-powershell/blob/500ef236d6499b9aed352a18a75c5d5c398f092f/src/Network/Network.Test/ScenarioTests/ApplicationGatewayTests.ps1#L3350

Yes, the updated part of the test case tests the two new properties which are only available in swagger network-february-release branch(https://github.com/Azure/azure-rest-api-specs/pull/13989), I am guessing the pipeline only uses the SDK from swagger master branch and that's why build here is failed, is it correct? the test case I updated in this PR is PASS when I did local testing with unsigned net SDK package built from swagger network-february-branch.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
