### PR TITLE
[Do not Squash] Merge main branch to Az.Storage-preview branch

### PR DESCRIPTION
**Pull request by blueww**
## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by BethanyZhou — DISMISSED** [review]
There are example issues remaining because we force-merge some changes about MDs into main branch. Ignore them as https://github.com/Azure/azure-powershell/pull/20916 did. They are out-of-scope for storage team.

**Comment by BethanyZhou** [comment]
@blueww please stop retriggering pipelines, and wait for all pipelines finish so that we can ensure there is no other issues reported except these known example issues.

**Comment by blueww** [comment]
@BethanyZhou 

Thanks for the info! However, besides that static analysis failure, there's also a test case failure, which looks not related to my change. 

> 2023-02-17T03:42:38.4841268Z   [xUnit.net 00:10:35.04]     Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DistributedAvailabilityGroupTests.TestManagedInstanceLink [FAIL]
> 2023-02-17T03:42:38.4847321Z     X Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DistributedAvailabilityGroupTests.TestManagedInstanceLink [3s 2ms]
> 2023-02-17T03:42:38.4903338Z EXEC : error Message:  [D:\a\_work\1\s\build.proj]
> 2023-02-17T03:42:38.4911620Z      System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: The requested resource of type 'Microsoft.Sql/managedInstances/distributedAvailabilityGroups' with name 'TestDAG' was not found.
> 2023-02-17T03:42:38.4913217Z     Stack Trace:
> 2023-02-17T03:42:38.4914039Z        at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
> 2023-02-17T03:42:38.4915115Z      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
> 2023-02-17T03:42:38.4916350Z      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
> 2023-02-17T03:42:38.4917665Z      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
> 2023-02-17T03:42:38.4919065Z      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
> 2023-02-17T03:42:38.4920311Z      at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
> 2023-02-17T03:42:38.4921928Z      at Microsoft.Azure.Commands.TestFx.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in D:\a\_work\1\s\tools\TestFx\EnvironmentSetupHelper.cs:line 531
> 2023-02-17T03:42:38.4923493Z      at Microsoft.Azure.Commands.TestFx.TestManager.RunTestScriptCore(Action setUp, Action`1 contextAction, Action tearDown, String[] scripts) in D:\a\_work\1\s\tools\TestFx\TestManager.cs:line 255
> 2023-02-17T03:42:38.4924986Z      at Microsoft.Azure.Commands.TestFx.TestManager.RunTestScript(String[] scripts) in D:\a\_work\1\s\tools\TestFx\TestManager.cs:line 221
> 2023-02-17T03:42:38.4926504Z      at Microsoft.Azure.Commands.Sql.Test.ScenarioTests.DistributedAvailabilityGroupTests.TestManagedInstanceLink() in D:\a\_work\1\s\src\Sql\Sql.Test\ScenarioTests\DistributedAvailabilityGroupTests.cs:line 32

**Comment by BethanyZhou** [comment]
Yes, please I tested it by another PR. It should work after sync latest main

**Comment by BethanyZhou** [comment]
See https://github.com/Azure/azure-powershell/pull/20954

**Comment by blueww** [comment]
@BethanyZhou 

The CI failed since build fail with following reason. It looks caused by the PR has too many commits:

> Exception Caught when trying to detect file changes with PS script: Octokit.RateLimitExceededException: API rate limit exceeded for 20.168.251.216. (But here's the good news: Authenticated requests get a higher rate limit. Check out the documentation for more details.)

**Comment by BethanyZhou** [comment]
Our IP may be detected. Let's reopen and have another try/

**Comment by BethanyZhou** [comment]
Reopen in https://github.com/Azure/azure-powershell/pull/20956

**Pull request closed without merging**
