### PR TITLE
Fixes: #14884: `Set-AzWebAppSlot` to set FtpsState, #14998:`Set-AzWebAppto set the AppSettings, #15005:Set-AzAppServicePlan` to keep existing Tags when adding new Tags

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
Fixes: #14884, #14998, #15005

## Description

*updated `Set-AzAppServicePlan` to keep existing Tags when adding new Tags
*Fixed `Set-AzWebApp` to set the AppSettings
*updated `Set-AzWebAppSlot` to set FtpsState

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by wyunchi-ms — DISMISSED** [review]

**Review by wyunchi-ms — APPROVED** [review]

**Comment by 9klakshmi** [comment]
Hi @Kotasudhakarreddy,

For the issue #14998 fix you checked in recently, I tried updating latest version of AZ (using Install-Module -Name Az & Update-Module -Name Az) but the App setting changes are not updating. Is there a different way to pull your fix to this issue?

Thanks,
Kiran

**Comment by Kotasudhakarreddy** [comment]
@9klakshmi the fix is yet to released for the customers. Release to customers is on 05/25/2021. Please check the milestone for more details.

**Comment by 9klakshmi** [comment]
Thank you @Kotasudhakarreddy...

**Pull request merged**
