### PR TITLE
Az fw backwards incompatible changes

### PR DESCRIPTION
**Pull request by fanymanea**
## Description

This PR moved AzureFirewall from 2018-04-01 to 2018-08-01 and introduces the following backwards incompatible changes:
- Remove ICMP from the supported network protocols values
- Rename InternalPublicIp to PublicIp
- Rename TargetUrls to TargetFqdns

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by praries880** [comment]
@fanymanea  Tests failed for the netcore build : https://travis-ci.org/Azure/azure-powershell/builds/425027115#L1608

**Comment by fanymanea** [comment]
@praries880, we do not plan to release preview versions anymore. We hope to merge to the Ignite release branch in time.

**Comment by praries880** [comment]
@fanymanea  MORE TESTS TO RE-RECORD : https://travis-ci.org/Azure/azure-powershell/builds/425047548#L1612

Given that thr API version changed you might have to rerecord most of the NW tests

**Comment by fanymanea** [comment]
We will create a new Pull Request for merging Azure Firewall changes to network-september-release branch.

**Pull request closed without merging**
