### PR TITLE
update latest VMAccessAgent version to 2.4 instead of 2.0

### PR DESCRIPTION
**Pull request by axelgMS**
IcM 163809520
version 2.0 is pretty old and users should use 2.4 instead
so  I'm modifying the sample here to ensure they're using latest version.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by dingmeng-xue** [comment]
@axelgMS Please update src/Compute/Compute/ChangeLog.md 

_A snippet outlining the changes made in the PR is added under the ### Upcoming Release header in the module's ChangeLog.md file_

**Comment by axelgMS** [comment]
@dingmeng-xue  thanks, I modified changelog.md

Note that there was no ### upcoming release  header - so I created one at the top of the changelog.md file

**Comment by isra-fel** [comment]
Test failed due to a case in data lake store. Will merge anyway.
Job: https://dev.azure.com/azure-sdk/public/_build/results?buildId=231953
Log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=231953&view=logs&j=ad07b744-5a1a-5d54-7693-fcb02e666633&t=b0841cae-a6b1-5a5c-4ebd-3cc6b3d3163d&l=704

**Comment by axelgMS** [comment]
also related to [12687](https://github.com/Azure/azure-cli/pull/12687)

**Pull request merged**
