### PR TITLE
New Kusto Client - 2020-06-14

### PR DESCRIPTION
**Pull request by astauben**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
This is converted into a draft for PR management purpose.
Please feel free to click "Ready for review" when your development is done. Thanks!

**Comment by isra-fel** [comment]
Hi @astauben , to update a generated module, your work needs to be based on `generation` branch instead of master.
I can't just simply do that for you because otherwise there would be too many commits to review.

Besides, you need to firstly submit a cmdlet design review, see: https://github.com/Azure/azure-powershell/wiki/How-to-On-Board-New-RP-with-Azure-PowerShell-Generator#design-review

**Comment by astauben** [comment]
> Hi @astauben , to update a generated module, your work needs to be based on `generation` branch instead of master.
> I can't just simply do that for you because otherwise there would be too many commits to review.
> 
> Besides, you need to firstly submit a cmdlet design review, see: https://github.com/Azure/azure-powershell/wiki/How-to-On-Board-New-RP-with-Azure-PowerShell-Generator#design-review

Hi @isra-fel, Thanks for the update. 
 I opened a design review here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/685

**Comment by astauben** [comment]
> Hi @astauben , to update a generated module, your work needs to be based on `generation` branch instead of master.
> I can't just simply do that for you because otherwise there would be too many commits to review.
> 
> Besides, you need to firstly submit a cmdlet design review, see: https://github.com/Azure/azure-powershell/wiki/How-to-On-Board-New-RP-with-Azure-PowerShell-Generator#design-review

I've opened PR based on (and to) the generation branch here:
https://github.com/Azure/azure-powershell/pull/12501

**Comment by isra-fel** [comment]
Cool. Closing this PR.

**Pull request closed without merging**
