### PR TITLE
Merge Preview into Storage Preview

### PR DESCRIPTION
**Pull request by blueww**
## Description

Pull the Azure/Preview, and merge it to storage preview branch, to update storage preview branch to latest.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by blueww** [comment]
On Demand: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/975/

sign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/823/

**Comment by blueww** [comment]
@praries880 , @cormacpayne 

The build failed for following error (but on-demand pass).
This seems not related with my code change. Any idea?

> 01:36:57 c:\workspace\powershell\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Profile.Test.ArgumentCompleterTests.TestResourceIdCompleter [FAIL] [c:\workspace\powershell\build.proj]
> 01:36:57         System.Management.Automation.RuntimeException : Assertion failed because expected '' does not match actual '/subscriptions/c9cbd920-c00c-427c-852b-8aaf38badaeb/resourceGroups/shch/providers/Microsoft.Storage/storageAccounts/shch /subscriptions/c9cbd920-c00c-427c-852b-8aaf38badaeb/resourceGroups/shch1/providers/Microsoft.Storage/storageAccounts/shch1'

**Comment by praries880** [comment]
@blueww your base branch needs changes in the Azure:AzureRM.Storage.location branch merged in...
Sine you are not going to be online noew, I have created another PR to merge Azure:Preview into Azure:AzureRm.Storage.Location : https://github.com/Azure/azure-powershell/pull/6574

**Comment by cormacpayne** [comment]
Closing this PR as @praries880 PR was merged

**Pull request merged**
