### PR TITLE
Integret Akamai to Azure Cdn

### PR DESCRIPTION
**Pull request by csmengwan**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@csmengwan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (qinwa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/800/

**Comment by csmengwan** [comment]
@markcowl, I did not touch anything in AzureBatch. Are those test being unstable recently? Can we rerun the demand run?

**Comment by csmengwan** [comment]
@markcowl Looks like same issue appeared in other build as well. http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/799/
Can you contact the batch team and make it through?

**Comment by markcowl** [comment]
@csmengwan I think this may be a merge issue - if you pull the latest from dev into your branch and update the PR, this should resolve the issue

**Comment by csmengwan** [comment]
@markcowl success build: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/807/

**Pull request merged**
