### PR TITLE
Add operator "Any" in New-AzApplicationGatewayFirewallCondition

### PR DESCRIPTION
**Pull request by AdishreeM**
## Description

Add operator "Any" in New-AzApplicationGatewayFirewallCondition

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by AdishreeM** [comment]
I tried running Scenario tests, but for some reason the solution is not picking up the latest sdk built with swagger changes and the latest NRP version. Tried building, cleaning, restoring nupkg through VS, msbuild cli and dotnet cli.

It's showing the following error:

> "Specified api-version '2021-08-01' does not support property 'Any' in context 'properties.customRules[0]'. Use at least api-version '2021-12-01' or remove property 'Any' from the request body."


The commands work successfully when built and ran through powershell in ubuntu using the same sdk. Logs:
```
amazumder@LAPTOP:~/Projects/azure-powershell$ pwsh
PowerShell 7.2.4
Copyright (c) Microsoft Corporation.

https://aka.ms/powershell
Type 'help' to get help.

PS /home/amazumder/Projects/azure-powershell> Import-Module -Name ".\artifacts\Debug\Az.Accounts\Az.Accounts.psd1"
PS /home/amazumder/Projects/azure-powershell> Import-Module -name ".\artifacts\Debug\Az.Network\Az.Network.psd1"
PS /home/amazumder/Projects/azure-powershell> $variable2 = New-AzApplicationGatewayFirewallMatchVariable -VariableName RequestHeaders -Selector Malicious-Header
PS /home/amazumder/Projects/azure-powershell> $condition2 =  New-AzApplicationGatewayFirewallCondition -MatchVariable $variable2 -Operator Any -NegationCondition $False
PS /home/amazumder/Projects/azure-powershell> $rule = New-AzApplicationGatewayFirewallCustomRule -Name example -Priority 5 -RuleType MatchRule -MatchCondition $condition2 -Action Block
PS /home/amazumder/Projects/azure-powershell> $policy = Get-AzApplicationGatewayFirewallPolicy -Name "sample-waf-policy" -ResourceGroupName <redacted>
PS /home/amazumder/Projects/azure-powershell> $policy.CustomRules.Add($rule)
PS /home/amazumder/Projects/azure-powershell> Set-AzApplicationGatewayFirewallPolicy -InputObject $policy

CustomRules       : {example, example, example}
PolicySettings    : Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayFirewallPolicySettings
ManagedRules      : Microsoft.Azure.Commands.Network.Models.PSApplicationGatewayFirewallPolicyManagedRules
ResourceGroupName : check-waf-exclusion-bug
Location          : eastus
ResourceGuid      :
Type              : Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies
Tag               : {}
TagsTable         :
Name              : sample-waf-policy
Etag              : W/"11d459aa-2ca1-4f73-8c8e-037c02bbb6e1"
Id                : /subscriptions/<redacted>/resourceGroups/<redacted>/provider
                    s/Microsoft.Network/ApplicationGatewayWebApplicationFirewallPolicies/sample-waf-policy
```

**Comment by VeryEarly** [comment]
please fix failed test case: ApplicationGatewayTests.ps1: line 2450

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
