### PR TITLE
Update management change to support Dyanic group, Prepost and Reboot …

### PR DESCRIPTION
**Pull request by jemex**
…setting features

## Description

Azure automation update management change to support the following new features 
 - Dynamic grouping

- Pre-Post script

- Reboot Setting 

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@MiYanni would you mind taking a look at this when you get the chance? I can also take a look if you aren't able to, just re-assign this to me.

**Comment by MiYanni** [comment]
@jemex Can you link to the design review for this change?

**Comment by jemex** [comment]
@MiYanni , we have already done a design review when we added the cmdlet. 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/58 
This change is to add new parameters for the cmdlet that was reviewed in the above link and already published.  Do we need to do design review when we add a parameter to existing cmdlet?

**Comment by MiYanni** [comment]
@jemex Anything that changes the surface of the cmdlets needs a design review. It is in that section above when you created the PR, `For public API changes to cmdlets:`. If you only changed the SDK version and added tests, that would not need a design review. Also, this PR should not target the Automation branch unless you want these changes as a separate preview module release.

**Comment by markcowl** [comment]
@jemex we will close this PR at the end of the week for lack of response - please respond with a cmdlet review doc.

**Comment by markcowl** [comment]
Per above discussion, closing for lack of activity.  Please reopen when you are actively developing thsi feature, and please start with a cmdlet review

**Pull request closed without merging**
