### PR TITLE
remove preview tag for managmentpartner

### PR DESCRIPTION
**Pull request by jeffrey-ACE-zz**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@jeffrey-ACE is the management partner service GA, and is it expected that it ships with the stable `AzureRM` module?

**Comment by jeffrey-ACE** [comment]
@cormacpayne Yes, management partner service is GA now, it is expected to ship with stable AzureRM module.

**Comment by markcowl** [comment]
@jeffrey-ACE Unfortunately, I don't think we can include this module in the AzureRM roll-up.  We can make the change to stable, but this module will be an add-on install over AzureRM (or by itself)

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/444/

**Pull request merged**
