### PR TITLE
[Storage] Integrate XSCL v12 to Storage module, to support new storage features

### PR DESCRIPTION
**Pull request by blueww**
## Description

Reopen on new storage preview branch as https://github.com/Azure/azure-powershell/pull/11177 is closed.

There are no syntax changes, so no review docs raised in https://github.com/Azure/azure-powershell-cmdlet-review-pr

But I have raised a design doc, Erich has helped to review it. https://microsoft.sharepoint.com/:w:/t/XClientShanghai/EVNIP90Ijg1KsZT0VFEA6pgB33mx1WbdypGOXWTkLvgTHA?e=7SjutU

#### For Oauth:
For the oauth token, I implement my own class "AzureSessionCredential", I can switch to the common one provided by Powershell team (prototype： https://github.com/erich-wang/azure-powershell/commit/2b3791333) when it's merged to master.

#### Commits:
This PR include many changes from master, which is not already on storage branch. 
Only the last commit is for this feature change.
When https://github.com/Azure/azure-powershell/pull/11161 is merged, should only left the last commit.

#### For test:
I have tested it works on  

- Powershell 5.1
- Powershell 6.2.4

With authentication:
1. Key
2. SAS
3. Oauth
4. Anonymous

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
@erich-wang Hi Erich, could you review this PR cause it's related to track 2 SDK? Thanks

BTW @blueww  I'm not sure but it could be that the static analysis error was caused by wrong format of L59-60 in https://github.com/Azure/azure-powershell/blob/Az.Storage-preview/tools/StaticAnalysis/Exceptions/Az.Storage/SignatureIssues.csv#L59

**Comment by blueww** [comment]
@isra-fel 

@erich-wang  has a fix for the static analysis issue in https://github.com/Azure/azure-powershell/tree/erich/storage-track2-analysis
But the fix is still not finalized, and still need discuss with Mark.

**Comment by blueww** [comment]
Close as the change is included in https://github.com/Azure/azure-powershell/pull/11402

**Pull request closed without merging**
