### PR TITLE
Updated client_rb code to copy newline character as it is in extension config file.

### PR DESCRIPTION
**Pull request by Aliasgar16**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Aliasgar16__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by NimishaS** [comment]
@hovsepm , any updates on merging this?

**Comment by hovsepm** [comment]
@NimishaS, I've contacted the owner team. They should approve this PR so I can merge it.

**Comment by andrewelizondo** [comment]
LGTM :+1:

**Pull request merged**
