### PR TITLE
fix for issue #6356

### PR DESCRIPTION
**Pull request by praries880**
fix for issue #6356

### CODE REVIEW

**Comment by vladimir-shcherbakov** [comment]
@praries880  travis ci-build failed.

**Comment by praries880** [comment]
on demand : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/971/

sign job : https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/820/

**Comment by praries880** [comment]
on demand :https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/
sign job : https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/822

**Comment by praries880** [comment]
New on demand : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/977/
New sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/825/

**Comment by praries880** [comment]
new on demand : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/979/
new sign job : https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/826/

**Comment by praries880** [comment]
@cormacpayne need your review :)

**Pull request merged**
