### PR TITLE
Authorization: Changes to the Get-AzureRoleAssignment commandlet to also display classic admins and perform group expansion for users

### PR DESCRIPTION
**Pull request by namratab**
Authorization: Changes to the Get-AzureRoleAssignment commandlet to also display classic admins and perform group expansion for users

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@namratab__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nbaliga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ljhljh235** [comment]
Re ran it a few times and still failing.

**Comment by namratab** [comment]
I'm working on fixing the failed tests - these are tests in Commands.Network mostly which start to fail due to update in Authorization API version.

**Comment by ljhljh235** [comment]
@namratab But we are cutting the MSI today. If this is not necessary for this release / can't be fixed very soon, we will have to move on.

**Comment by namratab** [comment]
@ljhljh235 Yes, that's ok. We initially though we can make it this release, hence I sent a PR against the release branch. But this was an unexpected test issue we encountered last minute - so we'll be targeting the next release for this change. I will close this PR and update the one I sent against the dev branch once the tests are fixed.

**Pull request closed without merging**
