### PR TITLE
Added support to specify the Curve for Certificate Policies

### PR DESCRIPTION
**Pull request by ksaaf**
## Description

Added support to specify the Curve for Certificate Policies [[Issue: 9241](https://github.com/Azure/azure-powershell/issues/9241)]

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by kashifm-msft** [comment]
@VeryEarly 
I see this PR (https://github.com/Azure/azure-powershell/pull/10612) is merged to master. I also see another PR (https://github.com/Azure/azure-powershell/pull/10617) for reverting this merge. 

What's the reason for the other PR?

Thanks!

**Comment by VeryEarly** [comment]
> @VeryEarly
> I see this PR (#10612) is merged to master. I also see another PR (#10617) for reverting this merge.
> 
> What's the reason for the other PR?
> 
> Thanks!

I was thinking someone from key vault team should also take a look at your pr because I'm not that familiar with this module, kept this revert pr as backup if someone from key vault team reject it

**Comment by kashifm-msft** [comment]
> > @VeryEarly
> > I see this PR (#10612) is merged to master. I also see another PR (#10617) for reverting this merge.
> > What's the reason for the other PR?
> > Thanks!
> 
> I was thinking someone from key vault team should also take a look at your pr because I'm not that familiar with this module, kept this revert pr as backup.

@VeryEarly
I am from the Azure Key Vault team. Do you need any additional sign off?

**Comment by VeryEarly** [comment]
> > > @VeryEarly
> > > I see this PR (#10612) is merged to master. I also see another PR (#10617) for reverting this merge.
> > > What's the reason for the other PR?
> > > Thanks!
> > 
> > 
> > I was thinking someone from key vault team should also take a look at your pr because I'm not that familiar with this module, kept this revert pr as backup.
> 
> @VeryEarly
> I am from the Azure Key Vault team. Do you need any additional sign off?

Hi @kashifm-msft ,

We're good now. Thanks.

**Pull request merged**
