### PR TITLE
Check in basic managed Cassandra cmdlets

### PR DESCRIPTION
**Pull request by frrossms**
## Description

Teja built our basic powershell cmdlets for managed Cassandra before leaving the company, but they hadn't gotten checked in. This PR checks them in before we update them for the GA of managed Cassandra.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Since the November release is done. I'm changing the base branch to main.

**Comment by frrossms** [comment]
> Looks like this one: [Azure/azure-powershell-cmdlet-review-pr#949](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/949) may your design doc. Could you help to confirm?

Yes, this is our design doc.

**Comment by frrossms** [comment]
@BethanyZhou I've rerecorded all the tests, so I think we should be ready to be reviewed for going in the next release.

**Review by isra-fel — CHANGES_REQUESTED** [review]
Generally LGTM.
Please sync with main branch because `ChangeLog.md` has diverged. Make sure your PR doesn't change any old versions.
Another thing is about cmdlet names -- basically cmdlets are named after their module name, for example `Get-Az*CosmosDB*Location`. Why did you not name these new cmdlets that way? I mean for example `New-AzCosmosDBManagedCassandraCluster`

**Comment by frrossms** [comment]
> Generally LGTM. Please sync with main branch because `ChangeLog.md` has diverged. Make sure your PR doesn't change any old versions. 

Okay, I'll do that today and get it repushed.

> Another thing is about cmdlet names -- basically cmdlets are named after their module name, for example `Get-Az*CosmosDB*Location`. Why did you not name these new cmdlets that way? I mean for example `New-AzCosmosDBManagedCassandraCluster`

Because Managed Cassandra is a separate product. All our docs and branding don't mention CosmosDB. It is a technical/organizational detail that we share their control plane and SDK/CLI modules.

**Review by isra-fel — APPROVED** [review]
I sync main branch and updated change log.

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
