### PR TITLE
[Az.DataProtection] Added support for resourceGuard, protection related cmdlets

### PR DESCRIPTION
**Pull request by hiaga**
## Description
1) Added support for CRUD of resource guard resource. 
2) Added support for protection related commands with swagger refresh
             Resume-AzDataProtectionBackupInstanceProtection
             Stop-AzDataProtectionBackupInstanceProtection
             Suspend-AzDataProtectionBackupInstanceBackup
             Sync-AzDataProtectionBackupInstance

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
- {[https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1209](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1209)}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by hiaga** [comment]
Hi @VeryEarly, pls review this PR

**Comment by VeryEarly** [comment]
please check your PR carefully and resolve conflicts

**Comment by hiaga** [comment]
> please check your PR carefully and resolve conflicts

@VeryEarly:  working on resolving the conflicts!

**Comment by hiaga** [comment]
> please check your PR carefully and resolve conflicts

@VeryEarly : CI is green now, Pls check

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
