### PR TITLE
Update Invoke-AzStorageSyncChangeDetection.md

### PR DESCRIPTION
**Pull request by jeffpatt24**
Updated limitations and usage examples

## Description

Updated cmdlet limitations, examples, and description of -Name parameter.

## Checklist

- [X ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X ] The title of the PR is clear and informative
- [X ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X ] If applicable, the changes made in the PR have proper test coverage
- [X ] For public API changes to cmdlets:
    - [X ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [X ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by jeffpatt24** [comment]
#sign-off

**Comment by jeffpatt24** [comment]
@isre-fel Have you had a chance to review this PR?

**Review by isra-fel — APPROVED** [review]
Sorry for late response @jeffpatt24 our team are just back from holiday. Your changes LGTM!

**Comment by isra-fel** [comment]
Force merge the PR as it's only updating docunments

**Comment by jeffpatt24** [comment]
@isra-fel Thanks!

**Pull request merged**
