### PR TITLE
Update code structure of Storage management SDK

### PR DESCRIPTION
**Pull request by yifanz0**
## Description
Update code structure to follow Azure PowerShell convention.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by dingmeng-xue — APPROVED** [review]

**Review by blueww — APPROVED** [review]
LGTM

**Comment by yifanz0** [comment]
@wyunchi-ms Could you help take a look at the static analysis failure here please? The error says 
 ```"D:\a\1\s\artifacts/Debug\Az.Storage","Newtonsoft.Json","13.0.0.0","10.0.0.0","Microsoft.Azure.PowerShell.Storage.Management.Sdk","1","1010","Assembly Newtonsoft.Json version 13.0.0.0 referenced from Microsoft.Azure.PowerShell.Storage.Management.Sdk.dll does not match assembly version on disk: 10.0.0.0","Update any references to version 10.0.0.0 of assembly Newtonsoft.Json"
  
  Unhandled exception. System.InvalidOperationException: One or more errors occurred in validation. See the analysis reports at D:\a\1\s\artifacts//StaticAnalysisResults for details
     at StaticAnalysis.IssueChecker.IssueChecker.Analyze(IEnumerable`1 scopes, IEnumerable`1 modulesToAnalyze) in D:\a\1\s\tools\StaticAnalysis\IssueChecker\IssueChecker.cs:line 94
     at StaticAnalysis.IssueChecker.IssueChecker.Analyze(IEnumerable`1 scopes) in D:\a\1\s\tools\StaticAnalysis\IssueChecker\IssueChecker.cs:line 56
     at StaticAnalysis.Program.Main(String[] args) in D:\a\1\s\tools\StaticAnalysis\Program.cs:line 185
D:\a\1\s\build.proj(277,5): error MSB3073: The command "dotnet D:\a\1\s\artifacts/StaticAnalysis/StaticAnalysis.Netcore.dll -p D:\a\1\s\artifacts/Debug -r D:\a\1\s\artifacts//StaticAnalysisResults --analyzers check-error" exited with code -532462766.
```

However there doesn't seem to be a change for Newtonsoft.Json version in this PR's changes.

**Pull request merged**
