### PR TITLE
September Azure networking release (Ignite)

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description
Merged all PRs with preview branch, ready to release

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by maddieclayton** [comment]
@azuresdkci Add to whitelist

**Comment by maddieclayton** [comment]
@MikhailTryakhov We have to leave the office for a move in 15 minutes, so I will wait until I'm home to look over this.

**Comment by maddieclayton** [comment]
@MikhailTryakhov Fixed a merge conflict and an issue with the test csproj, now looks good to me.  Will merge as soon as CI passes.

**Comment by MikhailTryakhov** [comment]
@maddieclayton please meeeerge :)

**Comment by markcowl** [comment]
@MikhailTryakhov @praries880  yeaaaaaaaaaahhhh!!!!

**Pull request merged**
