### PR TITLE
[Azure Stack] Update Azs.Fabric.Admin module for Drive and Volume changes

### PR DESCRIPTION
**Pull request by zyxyoshine**
## Description

Update Azs.Fabric.Admin module to new version:
Changes for Drive and Volume resources with API version 2019-05-01: 
    * The value of Id, Name, HealthStatus and OperationalStatus have been changed.
    * We have supported new properties FirmwareVersion, IsIndicationEnabled, Manufacturer and StoragePool for Drive resources.
    * The properties CanPool and CannotPoolReason of Drive resources have been deprecated, please use OperationalStatus instead.
## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by zyxyoshine** [comment]
@bganapa Please help review.

**Comment by bganapa** [comment]
ps-sign - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign-esrp/142/

**Comment by bganapa** [comment]
looks good, lets wait for the ps-sign

**Comment by markcowl** [comment]
@bganapa Please comment when you have checked the sign build.

**Comment by bganapa** [comment]
@zyxyoshine Can you please validate the bits from here for your changes?
https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign-esrp/142/artifact/src/Stack/

**Comment by zyxyoshine** [comment]
@bganapa Thank you very much, the test results for my changes are green.

**Comment by bganapa** [comment]
@markcowl This is good to be merged Thanks @zyxyoshine for validating the ps sign bits

**Pull request merged**
