### PR TITLE
Network june

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description

Finally azure networking functionality release!!! 

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@MikhailTryakhov Please fix the test failure

**Comment by MikhailTryakhov** [comment]
@msJinLei  I'm a bit confused there...
Test Run Successful.
  Total tests: 22
       Passed: 22
   Total time: 11.7885 Seconds
/home/vsts/work/1/s/artifacts/after.Azure.PowerShell.sln.targets(4,5): error MSB4181: The "MSBuild" task returned false but did not log an error. [/home/vsts/work/1/s/artifacts/Azure.PowerShell.sln] [/home/vsts/work/1/s/build.proj]
/home/vsts/work/1/s/build.proj(269,5): error MSB3073: The command "dotnet test /home/vsts/work/1/s/artifacts/Azure.PowerShell.sln --filter "AcceptanceType=CheckIn&RunType!=DesktopOnly" --configuration Debug --framework netcoreapp2.1 --logger trx --results-directory "/home/vsts/work/1/s/artifacts//TestResults"" exited with code 1.
/home/vsts/work/1/s/build.proj(289,5): error : Test failures occurred, check the files in artifacts/TestResults
##[error]Error: The process '/opt/hostedtoolcache/dotnet/dotnet' failed with exit code 1
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : 
Finishing: Test

Where is it from? how is it possible to have all tests ran successfully and have a magic failure after that? Can you please help me to investigate?

**Comment by MikhailTryakhov** [comment]
Fixed version in dependant project, please review?

**Comment by msJinLei** [comment]
@MikhailTryakhov  Please resolve conflicts

**Comment by msJinLei** [comment]
> @msJinLei solved

Please fix the failed test case.

**Comment by MikhailTryakhov** [comment]
Guys, Again completely the same for the 2nd weeks in a row @msJinLei 
I don't understand what is an issue AFTER successful running of the tests...
Can you please help to merge it or to finally figure out what's happened?

**Comment by VeryEarly** [comment]
/azp run

> Guys, Again completely the same for the 2nd weeks in a row @msJinLei
> I don't understand what is an issue AFTER successful running of the tests...
> Can you please help to merge it or to finally figure out what's happened?

Those test failures are caused by network module referenced by scenario tests in other modules, skip API version check in those modules could be the fix.

**Comment by MikhailTryakhov** [comment]
As per contact with Yabo Hu, it's definitely time to merge it! Please let's do it!

**Comment by msJinLei** [comment]
> Guys, Again completely the same for the 2nd weeks in a row @msJinLei
> I don't understand what is an issue AFTER successful running of the tests...
> Can you please help to merge it or to finally figure out what's happened?

Your patch contains feature code changes of Compute and KeyVault.
Could you rebase/merge the latest master to have them removed from change list?
 I try to merge the latest master and unnecessary changes are removed https://github.com/Azure/azure-powershell/pull/12857/files.

**Comment by MikhailTryakhov** [comment]
@msJinLei can you please finallly merge it and that's all?

**Comment by msJinLei** [comment]
> @msJinLei can you please finallly merge it and that's all?

Your patch contains the feature code changes of Compute and KeyVault. It is because you don't merge the latest master.
Please rebase/merge the latest master to have them removed from change list.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
