### PR TITLE
Updating supported chars range for file names

### PR DESCRIPTION
**Pull request by surendernitj**
((0x1F <= CodePoint && CodePoint <= 0xD7FF) ||
            (0xE000 <= CodePoint && CodePoint <= 0xF8FF) ||
            (0xF900 <= CodePoint && CodePoint <= 0xFDCF) ||  // FDD0 not supported
            (0xFDD1 <= CodePoint && CodePoint <= 0xFDDC) ||  // FDDD not supported
            (0xFDDE <= CodePoint && CodePoint <= 0xFFFD) ||
            (0x10000 <= CodePoint && CodePoint <= 0x4FFFD) ||
            (0x50000 <= CodePoint && CodePoint <= 0x8FFFD) ||
            (0x90000 <= CodePoint && CodePoint <= 0xCFFFD) ||
            (0xD0000 <= CodePoint && CodePoint <= 0x10FFFD))

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@surendernitj 
Can you join the Azure orig in github?
Please describe your change in ChangeLog.md under StorageSync

**Comment by surendernitj** [comment]
> Can you join the Azure orig in github?

Could you please add me to the org? Or is there any other way to join?

**Comment by msJinLei** [comment]
> > Can you join the Azure orig in github?
> 
> Could you please add me to the org? Or is there any other way to join?

Please join https://github.com/Azure

**Comment by isra-fel** [comment]
Closing the PR for lack of activity. Feel free to reopen to continue working on it. Thanks.

BTW join Azure Github via https://aka.ms/AzureGithub

**Pull request closed without merging**
