### PR TITLE
[Storage] Upgrade Azure.Storage.Queues to 12.5.0

### PR DESCRIPTION
**Pull request by blueww**
## Description

Azure.Storage.Queues to 12.5.0 has a new dependency "System.Memory.Data" 1.0.0

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
Hi @blueww, there is a signature issue reported
```
  D:\a\1\s\artifacts//StaticAnalysisResults\MissingAssemblies.csv:
  "Directory","Assembly Name","Assembly Version","Referencing Assembly","Severity","ProblemId","Description","Remediation"
  "D:\a\1\s\artifacts/Debug\Az.Storage","System.Memory.Data","1.0.0.0","Azure.Storage.Queues","0","3000","Missing assembly System.Memory.Data referenced from Azure.Storage.Queues","Ensure that the assembly is included in the Wix file or directory"
 
```

**Comment by blueww** [comment]
@erich-wang 
I have added a new dll "System.Memory.Data" to 
src/Accounts/Authentication/Utilities/CustomAssemblyResolver.cs
src/lib/NetCorePreloadAssemblies/System.Memory.Data.dll
src/lib/NetFxPreloadAssemblies/System.Memory.Data.dll 

But still meet analysis failure. Do I still need to add it to package reference? Is there any sample?

**Comment by blueww** [comment]
@wyunchi-ms 
Would you please help to see why the test fail?
It seems not related with my change. Let me know if any action I need to take.

The test failed in 2 test cases：

```
2020-12-07T06:15:19.4780170Z     ! Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SparkJobTests.TestSynapseSparkJob [1ms]
2020-12-07T06:15:21.3440900Z   [xUnit.net 00:00:11.54]     Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests.TestSynapseSqlPoolSecurity [FAIL]
2020-12-07T06:15:22.5422590Z     X Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SqlPoolTests.TestSynapseSqlPoolSecurity [604ms]
2020-12-07T06:15:22.5427060Z EXEC : error Message:  [/Users/runner/work/1/s/build.proj]
2020-12-07T06:15:22.5429240Z      System.Management.Automation.CommandNotFoundException : The term 'Update-AzSynapseSqlPoolAdvancedThreatProtectionSetting' is not recognized as the name of a cmdlet, function, script file, or operable program.
2020-12-07T06:15:22.5430610Z   Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

```
2020-12-07T06:15:18.9905890Z   [xUnit.net 00:00:09.20]     Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests.TestSynapseWorkspaceSecurity [FAIL]
2020-12-07T06:15:19.0688520Z   [xUnit.net 00:00:09.24]     Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.SparkJobTests.TestSynapseSparkJob [SKIP]
2020-12-07T06:15:19.4281140Z     ! Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests.TestSynapseWorkspaceActiveDirectoryAdministrator [1ms]
2020-12-07T06:15:19.4283060Z     X Microsoft.Azure.Commands.Synapse.Test.ScenarioTests.WorkspaceTests.TestSynapseWorkspaceSecurity [946ms]
2020-12-07T06:15:19.4374620Z EXEC : error Message:  [/Users/runner/work/1/s/build.proj]
2020-12-07T06:15:19.4377220Z      System.Management.Automation.CommandNotFoundException : The term 'Enable-AzSynapseSqlAdvancedDataSecurity' is not recognized as the name of a cmdlet, function, script file, or operable program.
2020-12-07T06:15:19.4379090Z   Check the spelling of the name, or if a path was included, verify that the path is correct and try again.
```

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
