### PR TITLE
Adding ResourceGroupName in output of Get-AzureRMBackupVault

### PR DESCRIPTION
**Pull request by swatimadhukar**
[Azure Backup] Bug Fix to display ResourceGroupName in Get-AzureRMBackupVault cmdlet

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@swatimadhukar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by dragonfly91** [comment]
Adding a few more bug fixes

**Comment by pcgeek86** [comment]
Thanks for proactively fixing this bug. Very useful to have ResourceGroupName on all emitted ARM resources.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by ogail** [comment]
@swatimadhukar why adding `Microsoft.Azure.Management.BackupServicesManagement.dll`? Please remove it and use NuGet package instead.

**Comment by dragonfly91** [comment]
1. Removed the DLL and taken dependency on nuget pkg. 
2. Some bug fixes

**Pull request merged**
