### PR TITLE
Brooklyn Feature:- Custom routes set on Gateway.

### PR DESCRIPTION
**Pull request by Nilambari**
## Description

These are command lets changes for setting custom routes specified by customer on Virtual network gateway. This can be done while creating new gateway or updating an existing gateway,

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by markcowl** [comment]
@MikhailTryakhov Is this PR meant to be part of this release, or the next one?

**Comment by markcowl** [comment]
@Nilambari If there was a previous cmdlet review for this, please link it in the description

**Comment by MikhailTryakhov** [comment]
@markcowl that's a question for @Nilambari 
if you need to merge it today, please retarget to ```master``` because ```network-matrch``` is on release stage https://github.com/Azure/azure-powershell/pull/9090

**Comment by MikhailTryakhov** [comment]
@Nilambari  please merge with master to resolve all these commits not related ot your changes

**Comment by Nilambari** [comment]
PowerShell cmdlet review is approved :- https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/285

**Comment by markcowl** [comment]
@Nilambari   Marking as 'Do Not Merge' until the network PR is merged, you will then need to pull from master, and then we will take a look.

**Comment by Nilambari** [comment]
Closing this PR. opened new PR: https://github.com/Azure/azure-powershell/pull/9093 against master branch.

**Pull request closed without merging**
