### PR TITLE
Update Register-AzAutomationDscNode.md

### PR DESCRIPTION
**Pull request by doctorscripto**
The example provided does not work.  It appears this cmdlet requires the VM location to be provided to work correctly or it will produce a Write error.

The above re-written example will work properly based upon a provided VM object

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by wyunchi-ms — APPROVED** [review]

**Comment by isra-fel** [comment]
@jaspkaur28 hi Jaspreet , @doctorscripto here said they cannot `Register-AzAutomationDscNode` without `-AzureVMLocation`, could you double confirm that? We might need to consider make the parameter mandatory if so. Thanks!

**Comment by isra-fel** [comment]
I [read about](https://stackoverflow.com/a/42143043/2593588) VM location is only required when it's different from that of the automation account.

@dcaro hi Damien could you help double check with service team so we can proceed with this PR? Thanks in advance.

**Comment by msJinLei** [comment]
@doctorscripto Thanks for the contribution. Please refer to the comments from @isra-fel for the reason we don't accept the change. But you are welcomed submit a new PR if you have better ideas.

**Pull request closed without merging**
