### PR TITLE
Merge Adls data plane to preview

### PR DESCRIPTION
**Pull request by rahuldutta90**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by ro-joowan** [comment]
@rahuldutta90 I see that you updated the help files -- please confirm

**Comment by rahuldutta90** [comment]
@ro-joowan I have updated the help files.

**Comment by rahuldutta90** [comment]
@markcowl @cormacpayne Are we waiting for anything for this PR to merge? Let me know if you have any concerns/questions.

**Comment by cormacpayne** [comment]
Closing this PR in favor of https://github.com/Azure/azure-powershell/pull/5860

**Pull request closed without merging**
