### PR TITLE
[Az.Resources] Fix template parameter name conflict issue for deployment cmdlets

### PR DESCRIPTION
**Pull request by shenglol**
## Description

This PR fixes a bug described in #2278, where template deployment fails to read a template parameter if its name conflicts with some built-in parameter name.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by shenglol** [comment]
> Hi @shenglol , there should be a test case to cover the scenario with conflicting names, right?

@isra-fel Yes, there are two test cases already there to cover the scenario.

**Comment by isra-fel** [comment]
@shenglol one tip on writing release notes (change log): they are read by customers so we would like to avoid using words like "fix issue XXX", but to choose more meaningful ones like "fix (what is the problem)".
There were merging conflicts so I resolved them and updated the changelog as well. Will merge if CI passes. Let me know if you have any problems. Thanks

**Comment by shenglol** [comment]
> @shenglol one tip on writing release notes (change log): they will be read by customers so we would like to avoid using words like "fix issue XXX", but to choose more meaningful ones like "fix (what is the problem)".
> There were merging conflicts so I resolved them and updated the changelog as well. Will merge if CI passes. Let me know if you have any problems. Thanks

@Thanks for the advice. Will follow the convention in the future.

**Pull request merged**
