### PR TITLE
RemoteApp: RestartVm tenant admin cmdlet

### PR DESCRIPTION
**Pull request by xamarsinx**
Requires new version of RemoteApp management, WindowsAzure.Management.RemoteApp.2.0.1
Will not build as package isn't available yet

Sending for early feedback as this need to make 8/12 release

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amarsi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (amarsin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@amarsi This is not early feedback, code complete for the 8/12 release was Friday.  IUf your PR is not passing by Monday morning, it will not make the release.

**Comment by amarsi** [comment]
It came in very late for us and customer needs it desperately.
I had my changed integrated into azure-sdk-for-net on Friday evening. The new package isn't available yet.
Do I need to request somewhere for new package?

**Comment by stankovski** [comment]
Started on-demaind builds:
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/112/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/416/

**Comment by stankovski** [comment]
@amarsi please pull from "upstream dev" and update your fork

**Comment by stankovski** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/117/

**Comment by amarsi** [comment]
I have found a bug, need to fix that. Also the MSI build is failing because the WindowsAzure.Management.RemoteApp.2.0.1 isn't signed. Need to publish the signed package.

**Comment by markcowl** [comment]
@amarsi You need to fix the remote app library that the cmdlets are consuming so that is is signed - you will need to update azure-sdk-for-net, and republish with a new version, then update the version here

**Comment by amarsi** [comment]
Have updated the RemoteApp package and fixe the bug as well.
The build is successful after push.

**Comment by amarsi** [comment]
retrying on-demand builds:
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/421/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/125/

**Comment by markcowl** [comment]
redoing on demand run: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/134/

**Comment by markcowl** [comment]
@amarsi Hi Amar, please resubmit this PR aginst the release branch (release-0.9.7).  We will take it if you can have it submitted (and passing) today

**Comment by amarsi** [comment]
Submitted PR against release-0.9.7 branch
https://github.com/Azure/azure-powershell/pull/741
The build is successful.

**Comment by markcowl** [comment]
@amarsi closing in favor of the merged PR in release-0.9.7 - we will merge that back to the dev branch at the end of the release.

**Pull request closed without merging**
