### PR TITLE
[Smoketest]Add try 3 times with 30s sleeping time

### PR DESCRIPTION
**Pull request by lijinpei2008**
## Description
Add try 3 times with 30s sleeping time between each try.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Have you tested it?

**Comment by lijinpei2008** [comment]
> Have you tested it?

Yes, passed the test locally whether it's PowerShell or Windows Powershell.

**Comment by isra-fel** [comment]
How about the negative case: you deliberately make a test case fail and check:
1. if the error message contains meaningful info (like exception message and stack trace)
2. if the case is retried

**Comment by lijinpei2008** [comment]
> How about the negative case: you deliberately make a test case fail and check:
> 
> 1. if the error message contains meaningful info (like exception message and stack trace)
> 2. if the case is retried

Yes, change the value of the environment variable "$ErrorActionPreference" to "Continue" when the command runs incorrectly and retry.
If it succeeds, it skips. If the error continues, and the error message is printed on the screen. This behavior will continue 2 times.
For example, when I provide a wrong parameter, I can see an explicit error message telling me that the parameter "Names" does not exist.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
