### PR TITLE
CosmosDB - New Restore Parameter

### PR DESCRIPTION
**Pull request by mayankkatwal**
## Description

This is a very small change to allow users to pass in a flag (PublicNetworkAccess) to the restore powershell command. This flag will get propagated to the restore workflow and will restore the database account with either public network access as enabled or disabled. This new parameter has existed for some time as the provision database account ps command leverages the same. Therefore, no changes to any sdk is needed, thus making this a minor change.

This exact change has been a part of the cosmos db preview branch and opened to private customers for about 5 months. Since we want to open this to public, we are making changes to main. 

Here is the preview change PR: https://github.com/Azure/azure-powershell/pull/21464

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by YanaXu** [comment]
Hi @mayankkatwal , the CI checks are not successfully triggered. Could you push a new commit (edit a line or something else)? Let's see if it fixes the CI triggers.

**Comment by mayankkatwal** [comment]
> Hi @mayankkatwal , the CI checks are not successfully triggered. Could you push a new commit (edit a line or something else)? Let's see if it fixes the CI triggers.

I have made a minor change to the PR and have removed a failing test file. Could you please review the PR as is, and i will subsequently add the test changes.

**Comment by YanaXu** [comment]
Hi @mayankkatwal， the PR is clear now. Should I merge it or wait for your tests?

**Comment by mayankkatwal** [comment]
> 

Lets wait for the tests. I can even test it manually before merging

**Comment by mayankkatwal** [comment]
@YanaXu, the test is uploaded with the recording. if the PR is good to be merged, you can do so.

**Review by YanaXu — APPROVED** [review]

**Pull request merged**
