### PR TITLE
Added bootstrap_version option

### PR DESCRIPTION
**Pull request by NimishaS**
In progress

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@NimishaS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by NimishaS** [comment]
Done

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@singhkay @huangpf @hyonholee  Can one of you please take a look?

**Comment by huangpf** [comment]
LGTM

**Comment by singhkay** [comment]
LGTM @hyonholee Can you check if the help file being edited is the latest one we checked in last release?

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@singhkay There is a parallel PR for the ARM changes

**Comment by NimishaS** [comment]
@singhkay , @markcowl yes we are porting `Set-AzureVMChefExtension`  command to ARM. But https://github.com/Azure/azure-powershell/pull/1504 is in progress currently.

This one is tested.

**Pull request merged**
