### PR TITLE
Support file share paths for Cmdlet parameters. 

### PR DESCRIPTION
**Pull request by TianoMS**
1. Fix https://github.com/Azure/azure-powershell/issues/373: support file share paths for parameters. 
2. Write a waiting message for New-AzureRmResourceGroupDeployment when we wait for the next query operation.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TianoMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tiano). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by TianoMS** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/786/

**Comment by markcowl** [comment]
@TianoMS Can you add a test of the new capability?

**Comment by vivsriaus** [comment]
LGTM

**Comment by TianoMS** [comment]
Rerun on demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/795/

**Comment by markcowl** [comment]
@TianoMS Please respond to feedback, or this will not be merged.  If there is some reason this change cannot be tested, please explain why.

**Comment by TianoMS** [comment]
@markcowl The change is a about loading a template file from a network shared path (something like: \\tiano-desktop\mytemplates\azuredeploy.json). Right now we don’t have a good way to test this in our automation test framework. 

I did test the new behaviors manually, on all the impacted cmdlets.

**Comment by markcowl** [comment]
@TianoMS Please add an issue in the next sprint to add test automation for this.  If all else fails,w e can add this to the installer automation tests in Tools\InstallationTests.  We don't want to regress this for lack of automation.

**Comment by TianoMS** [comment]
@markcowl I'll double check on that.

**Pull request merged**
