### PR TITLE
Removed storage depedency when inferring storageBlobContainerName

### PR DESCRIPTION
**Pull request by yaakoviyun**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by yaakoviyun** [comment]
@yoavfr  @markcowl

**Comment by maddieclayton** [comment]
@yaakoviyun Please add test coverage for this change.

**Comment by yaakoviyun** [comment]
@maddieclayton - there is a test coverage but it is disabled as:
#if NETSTANDARD

        [Fact(Skip = "Storage version difference: Awaiting Storage.Common usage in Sql")]

        [Trait(Category.RunType, Category.DesktopOnly)]

#else

see in:
https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Sql/Commands.Sql.Test/ScenarioTests/VulnerabilityAssessmentTests.cs

**Comment by maddieclayton** [comment]
@yaakoviyun It looks like this is just disabled on Netstandard, but not desktop - can we add the additional testing for Desktop now and worry about rerecording Netstandard once the Storage version is updated?

**Comment by MiYanni** [comment]
@maddieclayton It isn't the Storage version... it is this PR (that you got assigned to as of yesterday 😉 ): https://github.com/Azure/azure-powershell/issues/5365

**Pull request merged**
