### PR TITLE
StackHCIVm Module Creation

### PR DESCRIPTION
**Pull request by hvedati**
## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by vidai-msft** [comment]
@hvedati if you want to have a submodule inside StackHCI, the folder structure should look like below. Otherwise, it won't work. Let me know if you have any questions.
- StackHCI
  - StackHCI.AutoRest
  - StackHCIVM.AutoRest

**Comment by vidai-msft** [comment]
@hvedati  can you please refer to the folder structure like the Purview module https://github.com/Azure/azure-powershell/tree/main/src/Purview? We highly recommend that you raise PR directly to main branch first to make sure everything can work as expected and then sync to generation branch. It would save lots of time. Let me know if you have any questions.

**Comment by hvedati** [comment]
@vidai-msft Hi Vincent, I though the process was to create a PR in the generation branch? https://github.com/Azure/azure-powershell/wiki/How-to-On-Board-New-RP-with-Azure-PowerShell-Generator#code-review

**Comment by vidai-msft** [comment]
> @vidai-msft Vincent Dai FTE Hi Vincent, I though the process was to create a PR in the generation branch? https://github.com/Azure/azure-powershell/wiki/How-to-On-Board-New-RP-with-Azure-PowerShell-Generator#code-review

@hvedati Yes, the normal process is to submit a PR to the generation branch. However, since you plan to add a sub module which involves updating the folder structure, it would be convenient to do it reversely (main branch first and then generation).

**Comment by vidai-msft** [comment]
@hvedati The code freeze for this sprint is PST 6PM 6/26. If you want to have the change released on July 4, please make this PR ready before that. Let me know if you have any questions. Thanks!

**Comment by YanaXu** [comment]
Hi @hvedati , this PR has been idle for more than 1 month. Please update it according to the comments. Or we'll close it a week later. You can create a new PR when your code is ready. Thanks.

**Comment by YanaXu** [comment]
Hi @hvedati , I've converted this PR to a draft one. Please click "Ready for review" on this page when it's ready.

**Comment by BethanyZhou** [comment]
@hvedati , please add example for cmdlets in stackhcivm.autorest

**Pull request closed without merging**
