### PR TITLE
Update to allow a user to not specify a secret name

### PR DESCRIPTION
**Pull request by begoldsm**
This was behavior we had in hyak, but lost due to limitations in
AutoRest. Adding it back.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@begoldsm__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/727/

**Comment by markcowl** [comment]
@begoldsm merge conflicts, please update

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by begoldsm** [comment]
on demand run: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/735/

signing run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/402/

**Pull request merged**
