### PR TITLE
FIX AzureRmVirtualNetworkGatewayConnection uint mapping errors 

### PR DESCRIPTION
**Pull request by takekazuomi**
Fixed a difference in data type between PowerShell model class and SDK model. It was the same as SDK model.

## Description
Property types of EgressBytesTransferred and IngressBytesTransferred are different in SDK model class (Microsoft.Azure.Management.Network.Models.VirtualNetworkGatewayConnection) and Azure PowerShell model class (Microsoft.Azure.Commands.Network.Models.PSVirtualNetworkGatewayConnection).
As a result, it becomes "AzureRmVirtualNetworkGateway Connection uint mapping errors".

```
Get-AzureRmVirtualNetworkGatewayConnection: Missing type map configuration or unsupported mapping.
Mapping types:
Int64 -> UInt 64
System.Int64 -> System.UInt64
Destination path:
PSVirtualNetworkGatewayConnection.EgressBytesTransferred.EgressBytesTransferred
Source value:
2374563
```

Reference
#2873 

This change will solve the problem.
---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [ ] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [ ] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.
- [ ] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [ ] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [ ] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [ ] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [ ] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [ ] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by cormacpayne** [comment]
@takekazuomi Hey Takekazu, thanks for taking the time to send out a fix for this issue; based on the number of responses to https://github.com/Azure/azure-powershell/issues/2873 , this will help a lot of people unblocked 😄 

I have contacted the Network team to have this PR reviewed. ( @DeepakRajendranMsft @markjbrown @Nilambari @bridgetdMSFT for reference)

**Comment by cormacpayne** [comment]
@takekazuomi the build is currently failing because Static Analysis is flagging the changes you made to the property types as a breaking change, which is not true in this case.

To suppress these warnings, you can append the below lines to the end of  `tools/StaticAnalysis/Exceptions/BreakingChangeIssues.csv`

```
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand","Get-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'EgressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'EgressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.GetAzureVirtualNetworkGatewayConnectionCommand","Get-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'IngressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'IngressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand","New-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'EgressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'EgressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.NewAzureVirtualNetworkGatewayConnectionCommand","New-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'IngressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'IngressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayConnectionCommand","Set-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'EgressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'EgressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayConnectionCommand","Set-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'IngressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'IngressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayConnectionCommand","Set-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'EgressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'EgressBytesTransferred' back to 'System.UInt64'."
"D:\workspace\powershell\src\Package\Debug\ResourceManager\AzureResourceManager\AzureRM.Network\Microsoft.Azure.Commands.Network.dll","Microsoft.Azure.Commands.Network.SetAzureVirtualNetworkGatewayConnectionCommand","Set-AzureRmVirtualNetworkGatewayConnection","0","3000","The type of property 'IngressBytesTransferred' of type 'PSVirtualNetworkGatewayConnection' has changed from 'System.UInt64' to 'System.Int64'.","Change the type of property 'IngressBytesTransferred' back to 'System.UInt64'."
```

**Comment by takekazuomi** [comment]
@cormacpayne Thank you.  I append  suppress these warnings line in BreakingChangeIssues.csv.

**Comment by Nilambari** [comment]
I have 3.3.0 Azure module and I do not see this issue :- 

PS C:\SD\PS> Get-AzureRmVirtualNetworkGatewayConnection -Name vnetConnection0To1  -ResourceGroupName NRPVnetToVnetGatewayUpgradeDowntimeTest


Name                    : vnetConnection0To1
ResourceGroupName       : NRPVnetToVnetGatewayUpgradeDowntimeTest
Location                : westus
Id                      : /subscriptions/05f401ac-885f-4ba4-b2d6-7c5444596230/resourceGroups/NRPVnetToVnetGatewayUpgradeDowntimeTest/providers/Microsoft.Network/connections/vnetConnection0To1
Etag                    : W/"f6b73ba4-dcbf-466e-8552-096060525673"
ResourceGuid            : 3e6f5e9e-da5f-4119-9f74-aaf206157637
ProvisioningState       : Succeeded
Tags                    :
AuthorizationKey        :
VirtualNetworkGateway1  : "/subscriptions/05f401ac-885f-4ba4-b2d6-7c5444596230/resourceGroups/NRPVnetToVnetGatewayUpgradeDowntimeTest/providers/Microsoft.Network/virtualNetworkGateways/testvnet0vnetgateway"
VirtualNetworkGateway2  : "/subscriptions/05f401ac-885f-4ba4-b2d6-7c5444596230/resourceGroups/NRPVnetToVnetGatewayUpgradeDowntimeTest/providers/Microsoft.Network/virtualNetworkGateways/testvnet1vnetgateway"
LocalNetworkGateway2    :
Peer                    :
RoutingWeight           : 5
SharedKey               : chocolate
ConnectionStatus        : Connected
**EgressBytesTransferred  : 3568466
IngressBytesTransferred : 13591084**
TunnelConnectionStatus  : []

**Comment by Nilambari** [comment]
Also, SDK model has those vars as UInt 64 / long? only. 
Check @ https://github.com/Azure/azure-sdk-for-net/blob/AutoRest/src/ResourceManagement/Network/Microsoft.Azure.Management.Network/Generated/Models/VirtualNetworkGatewayConnection.cs

**Comment by shahabhijeet** [comment]
@takekazuomi I would need approval from someone in Network. Added appropriate folks who can approve this change.
I see there is difference of opinion, so please make sure you have an approval for this change.

Also if you go ahead with this change, you will have to bump up major version number due to this breaking change.
Also can't this be as simple as making the change in Automapper? Rather than actually changing the datatype?

**Comment by takekazuomi** [comment]
@Nilambari @shahabhijeet I confirmed. This problem is not reproduced in all environments.
I am triaging. It will take some time.

**Comment by markcowl** [comment]
@takekazuomi Please remove the 'do not merge' label and add a 'needs review' label when you have completed looking at this.

**Comment by takekazuomi** [comment]
@Nilambari @shahabhijeet This correction is not fundamental. I wrote the cause on the Issue side. 
https://github.com/Azure/azure-powershell/issues/2873#issuecomment-290903640

**Pull request closed without merging**
