### PR TITLE
Add SQL Server Active Directory administrator Cmdlets. 

### PR DESCRIPTION
**Pull request by j82w**
Adding Get-AzureSqlServerActiveDirectoryAdministrator, Set-AzureSqlServerActiveDirectoryAdministrator, Remove-AzureSqlServerActiveDirectoryAdministrator.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@j82w__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jawilley). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@j82w please pull from dev branch and resolve conflicts

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by ogail** [comment]
@j82w please pull from upstream and resolve coflicts

**Comment by j82w** [comment]
Switching to the release-0.9.7 branch

**Pull request closed without merging**
