### PR TITLE
Making change in SQL MI tests to delegate subnet to SQL MI service

### PR DESCRIPTION
**Pull request by stefbomdcs**
## Description

Making change in SQL MI create related tests to have subnet delegated to SQL MI service as this will be forced by SQL MI and all create requests for non-delegated subnets will fail.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by VeryEarly** [comment]
Hi @petrajkogit ,

since the change is on Common.ps1, can you please verify whether it has impact on other test cases

**Comment by stefbomdcs** [comment]
> Hi @petrajkogit ,
> 
> since the change is on Common.ps1, can you please verify whether it has impact on other test cases

I've run one of the tests which is using the changed method. Is it required to run all the tests?

**Comment by stefbomdcs** [comment]
@VeryEarly 
Do you maybe know why it takes this long for these checks to complete?

**Comment by VeryEarly** [comment]
> @VeryEarly
> Do you maybe know why it takes this long for these checks to complete?

It looks like the CI was not triggered

**Comment by stefbomdcs** [comment]
@VeryEarly 
Thanks for starting this. Am I missing some permission as it looks like that Merging is blocked?

**Comment by VeryEarly** [comment]
@stefbomdcs @petrajkogit ,

It looks to me the function `CreateAndGetVirtualNetworkForManagedInstance`
was been used by not just one test case.

Please also re-record test cases that referenced this function.

**Comment by stefbomdcs** [comment]
@VeryEarly 
Yes, this function is referenced in all MI related test cases.
The tests which are creating MI are very expensive and creation of MI lasts about 4h. 
I've tested the change thoroughly for all possible scenarios as it is scoped to adding delegation and NSG object to subnet.
Running all the tests will be very painful and time consuming.

**Pull request merged**
