### PR TITLE
ADL PowerShell Updates

### PR DESCRIPTION
**Pull request by begoldsm**
1. Update to latest SDK
2. Enable File and Folder performant download support
3. Add a full path property to ADLS items returned with GET and LIST
4. Update the help for new properties/property documentation changes
5. Add default values for Upload and download for threading and number of files to download/upload at once during a folder upload/download
6. Set the max connections for the ADLS client during client creation to 1000. This ensures the connection limit is high enough before any other ADLS calls are made, enabling upload/download to open sufficient connections.
7. Remove tracing from file/folder copy until issue: https://github.com/Azure/azure-powershell/issues/2499 is resolved.

### CODE REVIEW

**Comment by markcowl** [comment]
@begoldsm Please enable your tests here: https://github.com/Azure/azure-powershell/blob/dev/AzurePowershell.Test.targets#L94

**Comment by markcowl** [comment]
LGTM once the on-demand run passes

**Comment by markcowl** [comment]
On demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/964/

**Comment by begoldsm** [comment]
@markcowl great, thanks Mark! I will keep an eye on it and post here once on demand passes.

**Comment by begoldsm** [comment]
@markcowl on demand has passed!

**Pull request merged**
