### PR TITLE
Support Login Hint

### PR DESCRIPTION
**Pull request by msJinLei**
1. AccountId is passed to Azure.Identity as LoginHint when interactively
login
2. LoginHint will be serialized to Context.json but not used
3. LoginHint can be found in the following request
   - GET https://login.microsoftonline.com/organizations/oauth2/v2.0/authorize?scope=https%3A%2F%2Fmanagement.core.windows.net%2F%2F.default+openid+profile+offline_access&response_type=code&client_id=1950a258-227b-4e31-a9cf-717495945fc2&redirect_uri=http%3A%2F%2Flocalhost%3A8400%2F&claims=%7B%22access_token%22%3A%7B%22xms_cc%22%3A%7B%22values%22%3A%5B%22CP1%22%5D%7D%7D%7D&login_hint=leijin%40microsoft.com&client-request-id=161db891-d34f-4eb6-a0e2-c9f3998211f2&x-client-SKU=MSAL.NetCore&x-client-Ver=4.30.1.0&x-client-CPU=x64&x-client-OS=Microsoft+Windows+10.0.19043&code_challenge=xxxxxxxxxxx&code_challenge_method=S256&state=b2ccf0cc-8216-4a25-97d4-136c8c0fc4030d6bd724-b75b-49ba-a7c3-665682eaeeda HTTP/1.1

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please regenerate help and add an example.
Please also update the version of Azure.Core in `src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs`

**Comment by msJinLei** [comment]
> Please regenerate help and add an example. Please also update the version of Azure.Core in `src/Accounts/AuthenticationAssemblyLoadContext/AzAssemblyLoadContextInitializer.cs`

Done

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
