### PR TITLE
add UseBasicParsing

### PR DESCRIPTION
**Pull request by cblackuk**
## Description

It is needed to address breaking changes in AzureStack module 1.7.2 which can be reviewed here:

https://docs.microsoft.com/en-us/azure-stack/operator/azure-stack-powershell-install#install-azure-stack-powershell

For Azure Stack 1904 or later:
```powershell

# Install the AzureRM.BootStrapper module. Select Yes when prompted to install NuGet
Install-Module -Name AzureRM.BootStrapper

# Install and import the API Version Profile required by Azure Stack into the current PowerShell session.
Get-AzureRMProfile -Update
Use-AzureRmProfile -Profile 2019-03-01-hybrid -Force
Install-Module -Name AzureStack -RequiredVersion 1.7.2
```

It fixes the issue:
https://github.com/Azure/azure-powershell/issues/6358

## Actual issue:
```powershell
PS C:\> Install-Module -Name AzureRM.BootStrapper -Verbose
VERBOSE: Using the provider 'PowerShellGet' for searching packages.
VERBOSE: The -Repository parameter was not specified.  PowerShellGet will use all of the registered repositories.
VERBOSE: Getting the provider object for the PackageManagement Provider 'NuGet'.
VERBOSE: The specified Location is 'https://www.powershellgallery.com/api/v2' and PackageManagementProvider is 'NuGet'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.BootStrapper'' for ''.
VERBOSE: Total package yield:'1' for the specified package 'AzureRM.BootStrapper'.
VERBOSE: Performing the operation "Install-Module" on target "Version '0.4.0' of module 'AzureRM.BootStrapper'".
VERBOSE: The installation scope is specified to be 'AllUsers'.
VERBOSE: The specified module will be installed in 'C:\Program Files\WindowsPowerShell\Modules'.
VERBOSE: The specified Location is 'NuGet' and PackageManagementProvider is 'NuGet'.
VERBOSE: Downloading module 'AzureRM.BootStrapper' with version '0.4.0' from the repository 'https://www.powershellgallery.com/api/v2'.
VERBOSE: Searching repository 'https://www.powershellgallery.com/api/v2/FindPackagesById()?id='AzureRM.BootStrapper'' for ''.
VERBOSE: InstallPackage' - name='AzureRM.BootStrapper', version='0.4.0',destination='C:\Users\ContainerAdministrator\AppData\Local\Temp\1066483481'
VERBOSE: DownloadPackage' - name='AzureRM.BootStrapper', version='0.4.0',destination='C:\Users\ContainerAdministrator\AppData\Local\Temp\1066483481\AzureRM.BootStrapper\AzureRM.BootStrapper.nupkg',
uri='https://www.powershellgallery.com/api/v2/package/AzureRM.BootStrapper/0.4.0'
VERBOSE: Downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.BootStrapper/0.4.0'.
VERBOSE: Completed downloading 'https://www.powershellgallery.com/api/v2/package/AzureRM.BootStrapper/0.4.0'.
VERBOSE: Completed downloading 'AzureRM.BootStrapper'.
VERBOSE: Hash for package 'AzureRM.BootStrapper' does not match hash provided from the server.
VERBOSE: InstallPackageLocal' - name='AzureRM.BootStrapper', version='0.4.0',destination='C:\Users\ContainerAdministrator\AppData\Local\Temp\1066483481'
VERBOSE: Catalog file 'AzureRM.BootStrapper.cat' is not found in the contents of the module 'AzureRM.BootStrapper' being installed.
VERBOSE: Module 'AzureRM.BootStrapper' was installed successfully to path 'C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0'.
PS C:\> Get-AzureRmProfile -Update -Verbose
VERBOSE: Updating profiles
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
Invoke-CommandWithRetry : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try
again.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:94 char:18
+   $WebResponse = Invoke-CommandWithRetry -ScriptBlock $ScriptBlock
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-CommandWithRetry], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Invoke-CommandWithRetry

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:108 char:3
+   $OnlineProfileMapETag = $WebResponse.Headers["ETag"]
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:162 char:38
+   $OnlineProfileMap = $WebResponse | ConvertFrom-Json
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

VERBOSE: Getting profiles installed on the machine and available for import
Get-ProfilesInstalled : Cannot bind argument to parameter 'ProfileMap' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:950 char:62
+ ... ilesInstalled = Get-ProfilesInstalled -ProfileMap $ProfileMap ([REF]$ ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ProfilesInstalled], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-ProfilesInstalled

PS C:\> Use-AzureRmProfile -Profile 2019-03-01-hybrid -Force -Verbose
Use-AzureRmProfile : Cannot validate argument on parameter 'Profile'. The argument "2019-03-01-hybrid" does not belong to the set "2017-03-09-profile,2018-03-01-hybrid,latest" specified by the ValidateSet attribute. Supply an argument
that is in the set and then try the command again.
At line:1 char:29
+ Use-AzureRmProfile -Profile 2019-03-01-hybrid -Force -Verbose
+                             ~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Use-AzureRmProfile], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationError,Use-AzureRmProfile
```

Unless this module is fixed and republished to PowerShell gallery here:

https://www.powershellgallery.com/packages/AzureRM.BootStrapper

We cannot use 1.7.2 modules as we cannot install them in Windows Core systems...

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by bganapa** [comment]
@cblackuk Thanks for the PR. The issue happens only when Internet Explorer first launch configuration is not done. We earlier had a PR to fix this and decided not to release another version of BootStrapper module.. @viananth

**Comment by bganapa** [comment]
@cblackuk This is the PR https://github.com/Azure/azure-powershell/pull/8040 that we deferred not to take it. AzureRm.BootStrapper module is on the way out... Can you please clarify how this is blocking you if at all?

**Comment by cblackuk** [comment]
@bganapa yes I can, I am using on-boarding and off-boarding and other automation on Windows Core Docker container that cannot now import AzureStack modules because bootstrapper cannot pull the latest profile - see my issue above... of the error message...

**Comment by bganapa** [comment]
@cblackuk Can you please try adding the following registry key? This should disable the FirstTime IE configuration and should unblock you

[HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main]
DisableFirstRunCustomize = dword:00000001

**Comment by cblackuk** [comment]
@bganapa 

```powershell
PS HKLM:\SOFTWARE> Get-ChildItem "HKLM:\SOFTWARE\Policies\Microsoft\"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft


Name                           Property
----                           --------
Cryptography
PeerDist
SystemCertificates
TPM                            OSManagedAuthLevel : 2
Windows
Windows NT


PS HKLM:\SOFTWARE> New-Item HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main
New-Item : A positional parameter cannot be found that accepts argument 'Explorer\Main'.
At line:1 char:1
+ New-Item HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [New-Item], ParameterBindingException
    + FullyQualifiedErrorId : PositionalParameterNotFound,Microsoft.PowerShell.Commands.NewItemCommand

PS HKLM:\SOFTWARE> New-Item HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main"
PS HKLM:\SOFTWARE> New-Item "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main"
New-Item : The registry key at the specified path does not exist.
At line:1 char:1
+ New-Item "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main"
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (HKEY_LOCAL_MACH...ternet Explorer:String) [New-Item], ArgumentException
    + FullyQualifiedErrorId : System.ArgumentException,Microsoft.PowerShell.Commands.NewItemCommand

PS HKLM:\SOFTWARE> New-Item "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft


Name                           Property
----                           --------
Internet Explorer


PS HKLM:\SOFTWARE> New-Item "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main"


    Hive: HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer


Name                           Property
----                           --------
Main


PS HKLM:\SOFTWARE>  New-ItemProperty -Path "HKLM:\SOFTWARE\Policies\Microsoft\Internet Explorer\Main" -Name DisableFirstRunCustomize -PropertyType DWord -Value '1'


DisableFirstRunCustomize : 1
PSPath                   : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer\Main
PSParentPath             : Microsoft.PowerShell.Core\Registry::HKEY_LOCAL_MACHINE\SOFTWARE\Policies\Microsoft\Internet Explorer
PSChildName              : Main
PSDrive                  : HKLM
PSProvider               : Microsoft.PowerShell.Core\Registry



PS HKLM:\SOFTWARE> Get-AzureRmProfile -Update -Verbose
VERBOSE: Updating profiles
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
Invoke-CommandWithRetry : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the UseBasicParsing parameter and try
again.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:94 char:18
+   $WebResponse = Invoke-CommandWithRetry -ScriptBlock $ScriptBlock
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-CommandWithRetry], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Invoke-CommandWithRetry

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:108 char:3
+   $OnlineProfileMapETag = $WebResponse.Headers["ETag"]
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:162 char:38
+   $OnlineProfileMap = $WebResponse | ConvertFrom-Json
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

VERBOSE: Getting profiles installed on the machine and available for import
Get-ProfilesInstalled : Cannot bind argument to parameter 'ProfileMap' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:950 char:62
+ ... ilesInstalled = Get-ProfilesInstalled -ProfileMap $ProfileMap ([REF]$ ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ProfilesInstalled], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-ProfilesInstalled

PS HKLM:\SOFTWARE>






```

**Comment by cblackuk** [comment]
@bganapa  The problem is that Windows Core does not ship with Internet Explorer, nor can it be installed AFAIK :)

**Comment by bganapa** [comment]
@cblackuk 
Try this to unblock yourself, Add the following line before you call bootstrapper module
$PSDefaultParameterValues=@{"Invoke-WebRequest:UseBasicParsing"=$true}

**Comment by cblackuk** [comment]
@bganapa Thanks for trying to help.

Sadly no dice:

```powershell
PS HKLM:\SOFTWARE> $PSDefaultParameterValues=@{"Invoke-WebRequest:UseBasicParsing"=$true}
PS HKLM:\SOFTWARE> Get-AzureRmProfile -Update -Verbose
VERBOSE: Updating profiles
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
Invoke-CommandWithRetry : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the
UseBasicParsing parameter and try again.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:94 char:18
+   $WebResponse = Invoke-CommandWithRetry -ScriptBlock $ScriptBlock
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-CommandWithRetry], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Invoke-CommandWithRetry

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:108 char:3
+   $OnlineProfileMapETag = $WebResponse.Headers["ETag"]
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:162 char:38
+   $OnlineProfileMap = $WebResponse | ConvertFrom-Json
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

VERBOSE: Getting profiles installed on the machine and available for import
Get-ProfilesInstalled : Cannot bind argument to parameter 'ProfileMap' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:950 char:62
+ ... ilesInstalled = Get-ProfilesInstalled -ProfileMap $ProfileMap ([REF]$ ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ProfilesInstalled], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-ProfilesInstalled
```

**Comment by viananth** [comment]
@cblackuk Sorry about the issue. Can you please retry setting it as a Global variable?

`$Global:PSDefaultParameterValues=@{"Invoke-WebRequest:UseBasicParsing"=$true}`

**Comment by cblackuk** [comment]
@viananth Thanks for looking into it.

Sadly does not work either:

```powershell
PS HKLM:\SOFTWARE> $Global:PSDefaultParameterValues=@{"Invoke-WebRequest:UseBasicParsing"=$true}
PS HKLM:\SOFTWARE> Get-AzureRmProfile -Update -Verbose
VERBOSE: Updating profiles
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
VERBOSE: Waiting 3 second(s) before attempting again
VERBOSE: GET https://azureprofile.azureedge.net/powershell/profilemap.json with 0-byte payload
VERBOSE: received 4224-byte response of content type application/json
Invoke-CommandWithRetry : The response content cannot be parsed because the Internet Explorer engine is not available, or Internet Explorer's first-launch configuration is not complete. Specify the
UseBasicParsing parameter and try again.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:94 char:18
+   $WebResponse = Invoke-CommandWithRetry -ScriptBlock $ScriptBlock
+                  ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : NotImplemented: (:) [Invoke-CommandWithRetry], NotSupportedException
    + FullyQualifiedErrorId : WebCmdletIEDomNotSupportedException,Invoke-CommandWithRetry

Cannot index into a null array.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:108 char:3
+   $OnlineProfileMapETag = $WebResponse.Headers["ETag"]
+   ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidOperation: (:) [], RuntimeException
    + FullyQualifiedErrorId : NullArray

ConvertFrom-Json : Cannot bind argument to parameter 'InputObject' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:162 char:38
+   $OnlineProfileMap = $WebResponse | ConvertFrom-Json
+                                      ~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [ConvertFrom-Json], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Microsoft.PowerShell.Commands.ConvertFromJsonCommand

VERBOSE: Getting profiles installed on the machine and available for import
Get-ProfilesInstalled : Cannot bind argument to parameter 'ProfileMap' because it is null.
At C:\Program Files\WindowsPowerShell\Modules\AzureRM.BootStrapper\0.4.0\AzureRM.BootStrapper.psm1:950 char:62
+ ... ilesInstalled = Get-ProfilesInstalled -ProfileMap $ProfileMap ([REF]$ ...
+                                                       ~~~~~~~~~~~
    + CategoryInfo          : InvalidData: (:) [Get-ProfilesInstalled], ParameterBindingValidationException
    + FullyQualifiedErrorId : ParameterArgumentValidationErrorNullNotAllowed,Get-ProfilesInstalled

```

**Comment by cblackuk** [comment]
I am suggesting a really small change and you can then republish this as a package under 4.0.1 BootStrapper which would take like 20 min end-to-end and the world is saved and all is fixed... why cannot we do that?

**Comment by bganapa** [comment]
@cblackuk we are trying to unblock you before we could get a new module out

**Comment by cblackuk** [comment]
@bganapa Appreciate that :-)

What is the ETA on the new module then? :)

**Comment by cblackuk** [comment]
Any update on this please? @bganapa @viananth

**Comment by viananth** [comment]
We are working on getting this fixed and publish a release for the bootstrapper module. Will update with ETA soon.

**Comment by cblackuk** [comment]
Thank you so much! @viananth

**Comment by bganapa** [comment]
https://github.com/Azure/azure-powershell/pull/9226 - PR

**Comment by cblackuk** [comment]
@bganapa @viananth I can see that the PR is merged, any idea when new module will be published to PS Gallery? :-) Also, massive thanks for doing that 9226 PR :-) Really appreciate it!

**Comment by viananth** [comment]
@cblackuk Hi Chris, we are in the process of publishing the module to PSGallery. Thank you for your patience!

**Comment by viananth** [comment]
Bootstrapper module is now published to psgallery.

**Comment by cblackuk** [comment]
https://www.powershellgallery.com/packages/AzureRM.BootStrapper/0.5.0 released! - Tested and I can now load AzureStack modules on Windows Core!

I am humbled, amazed, overjoyed, and thankful! What an effort from multiple people from Microsoft to get it over the line and fix a MASSIVE issue for Azure Stack.

THANK YOU ALL!!!

**Comment by cblackuk** [comment]
It has been fixed in -> https://github.com/Azure/azure-powershell/pull/9226

Closing

**Pull request closed without merging**
