### PR TITLE
Adding AKV support to sqlvm powershell

### PR DESCRIPTION
**Pull request by tlao33**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@tlao33__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@tlao33__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@tlao33 you are missing help:

Help missing for cmdlet New-AzureVMSqlServerKeyVaultCredentialConfig implemented by class Microsoft.Azure.Commands.Compute.NewAzureVMSqlServerKeyVaultCredentialConfigCommand

**Comment by hovsepm** [comment]
@tlao33 please add tests.

**Comment by markcowl** [comment]
@tlao33 Not sure what happened, but the repository source is not showing up.  Please rebase this PRon the dev branch.  Closing, as a PR with over 7000 file changes cannot be accepted.

**Comment by tlao33** [comment]
Sorry about that. I thought I have already delete this pull request. It seems that I have made three pull requests. Only the last one is the correct with #2448
Date: Mon, 13 Jun 2016 15:07:39 -0700

**Pull request closed without merging**
