### PR TITLE
Display detailed error messages when template deployment fails

### PR DESCRIPTION
**Pull request by vivsriaus**
This will address issue: https://github.com/Azure/azure-powershell/issues/598

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivsriaus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (visriniv). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@vivsriaus please pull from "upstream dev" and update your fork

**Comment by markcowl** [comment]
@vivsriaus If you want this PR in the current release, please rtarget at the release branch (release-0.9.7)

**Comment by vivsriaus** [comment]
@markcowl This can go in the next train. @stankovski Sorry I missed the note. I've fixed the failing test now.

**Comment by ogail** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@vivsriaus Test failure - looks like a mistyped cmdlet or function anme in a test script?

**Comment by vivsriaus** [comment]
@markcowl It looks like the CI job is flaky. I kicked off another build and the failure is now on the compute tests? http://azuresdkci.cloudapp.net/job/powershell/2274/artifact/src/Publish/TestResults/Microsoft.Azure.Commands.Compute.Test.html

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by vivsriaus** [comment]
@markcowl can you please take a look at this?

**Comment by vivsriaus** [comment]
@markcowl @stankovski Have you had a chance to look at this yet?

**Comment by ogail** [comment]
@vivsriaus please pull from dev and reopen PR

**Pull request closed without merging**
