### PR TITLE
[Storage] Support rounting preferences

### PR DESCRIPTION
**Pull request by blueww**
## Description

target 2/9 release.

Design pass review: Azure/azure-powershell-cmdlet-review-pr#494
The feature has been released in Az.Storage preview with PR https://github.com/Azure/azure-powershell/pull/11778 target to preview branch 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@blueww Please resolve the conflicts

**Comment by blueww** [comment]
@msJinLei 
Conflict resolved.

**Comment by msJinLei** [comment]
> @msJinLei
> Conflict resolved.

hello @blueww 
Please check the following breaking change
```
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Microsoft.Azure.PowerShell.Cmdlets.ResourceManager.dll","Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.GetAzureManagementGroupDeploymentCmdlet","Get-AzManagementGroupDeployment","0","3010","The property 'QueryString' of type 'Microsoft.Azure.Management.ResourceManager.Models.TemplateLink' has been removed.","Add the property 'QueryString' back to type 'Microsoft.Azure.Management.ResourceManager.Models.TemplateLink'."
 ```

**Comment by blueww** [comment]
@msJinLei

The breaking change is on ResourceManager. but I don't do any change to it. 
All my code are within storage module. 
Do you have any idea why the breaking happen?

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
