### PR TITLE
Move CheckIfInteractive from AzurePSCmdlet to accounts and upgrade common version

### PR DESCRIPTION
**Pull request by VeryEarly**
## Description

- Move checkifinteractive from common to sendazfeedback cmdlet
- Remove checkinteractive from common

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by BethanyZhou — COMMENTED** [review]
No sure whether we need update change log for this PR. Besides, two Tests are failed. Please have a look

**Comment by VeryEarly** [comment]
> No sure whether we need update change log for this PR. Besides, two Tests are failed. Please have a look

No changelog needed for this PR, test cases will be fixed soon.

**Comment by dingmeng-xue** [comment]
Changelog should be added.

Removed Interactive mode check in common lib
Added endpoint of OperationalInsights to environment AzureChinaCloud [#15305]

**Review by BethanyZhou — APPROVED** [review]

**Comment by jiaxaiol** [comment]
Hi Engineer, we met the same issue with (https://github.com/Azure/azure-powershell/issues/15305), may I know if it is fixed or not? And how can we fix it? Thanks.

**Comment by dingmeng-xue** [comment]
You need to use the latest version of Az.Accounts.

**Pull request merged**
