### PR TITLE
Storage 1.13.4-preview

### PR DESCRIPTION
**Pull request by dingmeng-xue**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by blueww** [comment]
Please  don't merge the 2 json files in the PR.

**Comment by dingmeng-xue** [comment]
> The 2 json files should not be merged on preview branch.

Can they be merged? Is there any risk? I hope to minimize manual work.

**Comment by blueww** [comment]
They can't be merged since:
1. They will take so many conflicts when merge master change back to preview branch
2. They are for breaking change tracking, and we don't need to track breaking change on preview branch.

**Comment by dingmeng-xue** [comment]
> They can't be merged since:
> 
> 1. They will take so many conflicts when merge master change back to preview branch
> 2. They are for breaking change tracking, and we don't need to track breaking change on preview branch.

Got it. What I am thinking is on preview branch you can ignore those 2 files in code review. If so, 1 and 2 both won't be impact if you don't care about them. I'm learning the practice. Let's discuss again when PR is ready for review.

**Comment by blueww** [comment]
Actually, #1 will take a lot of trouble when I try to merge the latest change from master to preview branch.
And #2 will also has trouble when there's breaking change on preview branch, we need to add unnecessary  static analysis exception,

**Pull request merged**
