### PR TITLE
Monthly release of Azure Networking

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description

Monthly release of Azure Networking

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@BethanyZhou could you double confirm the change of src/Accounts/Accounts/AzureRmAlias/Mappings.json

**Comment by MikhailTryakhov** [comment]
Hey @msJinLei  looks like breaking change caused our required job failure... Due to it was approved previously so looks like that can be ignored? 
Can you please help to summarize any issues we need to work on? Or... merge? :)

**Comment by msJinLei** [comment]
You can suppress the breaking change issues by adding following lines to tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
```
D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv Errors
"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
"Az.Network","Microsoft.Azure.Commands.Network.AddAzureRmLoadBalancerRuleConfigCommand","Add-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Add-AzLoadBalancerRuleConfig' no longer supports the type 'System.String' for parameter 'BackendAddressPoolId'.","Change the type for parameter 'BackendAddressPoolId' back to 'System.String'."
"Az.Network","Microsoft.Azure.Commands.Network.AddAzureRmLoadBalancerRuleConfigCommand","Add-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Add-AzLoadBalancerRuleConfig' no longer supports the type 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool' for parameter 'BackendAddressPool'.","Change the type for parameter 'BackendAddressPool' back to 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool'."
"Az.Network","Microsoft.Azure.Commands.Network.NewAzureRmLoadBalancerRuleConfigCommand","New-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'New-AzLoadBalancerRuleConfig' no longer supports the type 'System.String' for parameter 'BackendAddressPoolId'.","Change the type for parameter 'BackendAddressPoolId' back to 'System.String'."
"Az.Network","Microsoft.Azure.Commands.Network.NewAzureRmLoadBalancerRuleConfigCommand","New-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'New-AzLoadBalancerRuleConfig' no longer supports the type 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool' for parameter 'BackendAddressPool'.","Change the type for parameter 'BackendAddressPool' back to 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool'."
"Az.Network","Microsoft.Azure.Commands.Network.SetAzureRmLoadBalancerRuleConfigCommand","Set-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Set-AzLoadBalancerRuleConfig' no longer supports the type 'System.String' for parameter 'BackendAddressPoolId'.","Change the type for parameter 'BackendAddressPoolId' back to 'System.String'."
"Az.Network","Microsoft.Azure.Commands.Network.SetAzureRmLoadBalancerRuleConfigCommand","Set-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Set-AzLoadBalancerRuleConfig' no longer supports the type 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool' for parameter 'BackendAddressPool'.","Change the type for parameter 'BackendAddressPool' back to 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool'."
```

**Comment by msJinLei** [comment]
> Hey @msJinLei looks like breaking change caused our required job failure... Due to it was approved previously so looks like that can be ignored?
> Can you please help to summarize any issues we need to work on? Or... merge? :)

You can suppress the breaking change issues by adding following lines to tools/StaticAnalysis/Exceptions/Az.Network/BreakingChangeIssues.csv
```
D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv Errors
"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
"Az.Network","Microsoft.Azure.Commands.Network.AddAzureRmLoadBalancerRuleConfigCommand","Add-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Add-AzLoadBalancerRuleConfig' no longer supports the type 'System.String' for parameter 'BackendAddressPoolId'.","Change the type for parameter 'BackendAddressPoolId' back to 'System.String'."
"Az.Network","Microsoft.Azure.Commands.Network.AddAzureRmLoadBalancerRuleConfigCommand","Add-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Add-AzLoadBalancerRuleConfig' no longer supports the type 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool' for parameter 'BackendAddressPool'.","Change the type for parameter 'BackendAddressPool' back to 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool'."
"Az.Network","Microsoft.Azure.Commands.Network.NewAzureRmLoadBalancerRuleConfigCommand","New-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'New-AzLoadBalancerRuleConfig' no longer supports the type 'System.String' for parameter 'BackendAddressPoolId'.","Change the type for parameter 'BackendAddressPoolId' back to 'System.String'."
"Az.Network","Microsoft.Azure.Commands.Network.NewAzureRmLoadBalancerRuleConfigCommand","New-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'New-AzLoadBalancerRuleConfig' no longer supports the type 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool' for parameter 'BackendAddressPool'.","Change the type for parameter 'BackendAddressPool' back to 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool'."
"Az.Network","Microsoft.Azure.Commands.Network.SetAzureRmLoadBalancerRuleConfigCommand","Set-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Set-AzLoadBalancerRuleConfig' no longer supports the type 'System.String' for parameter 'BackendAddressPoolId'.","Change the type for parameter 'BackendAddressPoolId' back to 'System.String'."
"Az.Network","Microsoft.Azure.Commands.Network.SetAzureRmLoadBalancerRuleConfigCommand","Set-AzLoadBalancerRuleConfig","0","2020","The cmdlet 'Set-AzLoadBalancerRuleConfig' no longer supports the type 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool' for parameter 'BackendAddressPool'.","Change the type for parameter 'BackendAddressPool' back to 'Microsoft.Azure.Commands.Network.Models.PSBackendAddressPool'."
```

**Comment by msJinLei** [comment]
all changes move to https://github.com/Azure/azure-powershell/pull/15207

**Comment by MikhailTryakhov** [comment]
@msJinLei  can you please review/merge it?

**Comment by msJinLei** [comment]
> @msJinLei can you please review/merge it?

@dingmeng-xue has created another PR #15207 to merge Network-February to master and it is merged. 
We are closing this PR now.

**Comment by MikhailTryakhov** [comment]
thank you! nice to hear that! CLosing in this case

**Pull request closed without merging**
