### PR TITLE
Merging Azure.Stack.05.2018 in to preview

### PR DESCRIPTION
**Pull request by bganapa**
## Description
Azurestack release branch merge in to preview

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)
@

### CODE REVIEW

**Comment by deathly809** [comment]
LGTM!

**Comment by bganapa** [comment]
ondemand is successful - https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/894/console
ps-sign has a signing failure 
https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/679/console

18:59:20   C:\workspace\powershell-sign\build.proj(401,5): error : The assembly "C:\workspace\powershell-sign\src\Package\Release\ResourceManager\AzureResourceManager\AzureRM.Profile\Microsoft.Azure.Commands.Common.KeyVault.dll" has not been strong named signed.
18:59:20   C:\workspace\powershell-sign\build.proj(401,5): error : C:\workspace\powershell-sign

**Comment by MiYanni** [comment]
@bganapa You have merge conflicts that need to be resolved.

**Comment by markcowl** [comment]
on-demand: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/940/
signing: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/761/
stack-sign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/

**Comment by markcowl** [comment]
Closing in favor of #6487

**Pull request closed without merging**
