### PR TITLE
Fix tags usage in ARM cmdlets. 

### PR DESCRIPTION
**Pull request by TianoMS**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TianoMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by TianoMS** [comment]
On demand job here. http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1017/. We have four failures. I'll look into them first.

**Comment by TianoMS** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1020/

**Comment by vivsriaus** [comment]
@TianoMS great work getting this out in such short time! Thanks.

**Comment by TianoMS** [comment]
Created another PR to merge to dev branch: https://github.com/Azure/azure-powershell/pull/2640.

**Pull request closed without merging**
