### PR TITLE
[App Service]: Added support to use Id for Restore-AzDeletedWebApp.

### LINKED ISSUE #11862: Missing feature parity with Azure CLI for Restore-AzDeletedWebApp
## Description

The Restore-AzDeletedWebApp should have feature parity with the Azure CLI (az webapp deleted restore).

## Background

The following article described the feature for restoring a deleted app in App Service:
https://docs.microsoft.com/en-us/azure/app-service/app-service-undelete
 
The relevant documentation for performing the task with the Azure CLI:
https://docs.microsoft.com/en-us/cli/azure/webapp/deleted?view=azure-cli-latest
 
As well as Azure PowerShell:
https://docs.microsoft.com/en-us/powershell/module/az.websites/restore-azdeletedwebapp?view=azps-3.8.0
 
To get the collection of deleted apps, I used Get-AzDeletedWebApp:
 
Name                             DeletionTime        ResourceGroupName        Location
----                             ------------        -----------------        --------
MyApp                05.05.2020 12:33:58 App-Rg        West Europe
MyApp                08.05.2020 18:21:02 App-Rg        West Europe
 
In this case, I want to restore the one from 05.05.2020, as the one from 08.05.2020 was created as a Windows app, while the one from 05.05.2020 is a Linux app.
App 'MyApp' of kind 'app,linux' incompatible with app 'MyAPp' of kind 'app'
 
Hence the one from 08.05.2020 was deleted.
However, when running Restore-AzDeletedWebApp, it doesn`t allow to specify which timestamp to restore from – and it always seem to be restoring the latest one:
WARNING: Found multiple matching deleted apps. Restoring the most recently deleted app, deleted at 05/08/2020 18:21:02
 
I can`t seem to find any way to specify which version/timestamp of the web app to restore using  Azure PowerShell.

However, the Azure the CLI has a –deleted-id parameter for specifying the site id corresponding to the timestamp one would want to restore from:
az webapp deleted restore --deleted-id /subscriptions/00000000-0000-0000-0000-000000000000/providers/Microsoft.Web/deletedSites/1234 --name MySite --resource-group MyResourceGroup --subscription MySubscription
 
As this parameter is not available in the corresponding Azure PowerShell command, there seems to be some incomplete feature parity – so I will suggest a similar parameter is added to the Restore-AzDeletedWebApp Azure PowerShell command.

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
## Description
Fix #11862 

The Restore-AzDeletedWebApp should have feature parity with the Azure CLI (az webapp deleted restore).

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by Kotasudhakarreddy** [comment]
@VeryEarly - can you please help me to figure out the cause of build failed. [Here](https://dev.azure.com/azure-sdk/29ec6040-b234-4e31-b139-33dc4287b756/_apis/build/builds/438232/logs/10) is the link for error Log.

**Pull request merged**
