### PR TITLE
Add support for the SetParameters.xml file to override package configuration when publishing a webdeploy package to an azure website.

### PR DESCRIPTION
**Pull request by naeemkhedarun**
I've added support for specifying a parameters file when publishing a package to an azure website.

For example:

```
 Publish-AzureWebsiteProject -Name nymtest -Package .\App.Api.zip -SetParametersFile .\App.Api.SetParameters.xml
```

Any help getting this merged will be very appreciated! Thanks for the fantastic cmdlets.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@naeemkhedarun__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@naeemkhedarun__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by naeemkhedarun** [comment]
@markcowl Hey Mark, if I can help to get this merged or you want any changes made please get in touch!

**Comment by naeemkhedarun** [comment]
@markcowl Hey Mark it has been a few weeks, would you like me to reintegrate this PR with the latest commits?

**Comment by markcowl** [comment]
@naeemkhedarun Sorry for the delay,  We are merging in some private changes today, and we will retun and take a look at the issues once that is complete

**Comment by markcowl** [comment]
@naeemkhedarun looks like this makes the publish-azurewebsites tests fail.  Can you take a look?

**Comment by naeemkhedarun** [comment]
Thanks @markcowl I'll get this sorted!

**Comment by markcowl** [comment]
@naeemkhedarun Code complete is today.  Can you please update this?

**Comment by naeemkhedarun** [comment]
@markcowl working on it now!

**Comment by naeemkhedarun** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@NaveenGoli Can you review this PR please?

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Comment by NaveenGoli** [comment]
revierwed

**Pull request merged**
