### PR TITLE
new property MaxCapacity for ApplicationGatewayAutoscaleConfiguration

### PR DESCRIPTION
**Pull request by KaiChiLin**
## Description

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/221
add a new property MaxCapacity for ApplicationGatewayAutoscaleConfiguration

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by number213** [comment]
@KaiChiLin since you've update SDK to use 2018-11-01, all recordings need to be updated, not just AppGw. We already have PR for that (https://github.com/Azure/azure-powershell/pull/8313), so once it's goes it, you would need to update your branch

**Comment by number213** [comment]
@KaiChiLin since we've published 19.8.0 with API version `2018-11-10` a couple days back, to make sure your package in local feed doesn't break existing functionality, I rebuilt it basing on 19.8.0 code and adding your change for max capacity

**Comment by number213** [comment]
@cormacpayne resolved conflicts, please take a look

**Comment by MikhailTryakhov** [comment]
@KaiChiLin  please remove nuget packages and use oficially published version ```19.8.0``` now to be merged 
https://www.nuget.org/packages/Microsoft.Azure.Management.Network/19.8.0-preview

**Comment by KaiChiLin** [comment]
> @KaiChiLin please remove nuget packages and use oficially published version `19.8.0` now to be merged
> https://www.nuget.org/packages/Microsoft.Azure.Management.Network/19.8.0-preview

Hi Mikhail,
should I also remove all the refs of "<PackageReference Include="Microsoft.Azure.Management.Network" Version="19.8.1-preview" />" from csproj files?

**Comment by MikhailTryakhov** [comment]
we need 19.8.0 everywhere, right

**Comment by MikhailTryakhov** [comment]
LGTM

**Pull request merged**
