### PR TITLE
Fixed bug "Get-AzureRmSubscription does not work correctly"

### PR DESCRIPTION
**Pull request by hovsepm**
fix for #1665

### CODE REVIEW

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/781/

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/782/

**Comment by hovsepm** [comment]
sign: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/424/

**Comment by markcowl** [comment]
@hovsepm are we ready to merge this?

**Comment by hovsepm** [comment]
@markcowl not yet. Still in progress...

**Pull request closed without merging**
