### PR TITLE
[Storage Dataplane] - Remove Validation Set and move to track2 SDK for accesstier

### PR DESCRIPTION
**Pull request by blueww**
This PR target 2/7 PSH release. Please help to review and merge it after 1/10 release.

Remove the validation Set and move the code to track2 SDK for Standard Access tier, so we can adapt the coming access tier change.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by blueww** [comment]
@isra-fel 

Feel free to let me know if anything need change for this PR before it's merged.

**Comment by isra-fel** [comment]
Hi, the implementation looks good. I wonder if accesstier is covered by existing test cases or not.

**Comment by blueww** [comment]
Yes, it's covered in storage dataplane test case like https://github.com/Azure/azure-powershell/blob/4f9d6180204b921aca42127b152533df8ca44d65/src/Storage/Storage.Management.Test/ScenarioTests/StorageDataPlaneTests.ps1#L204

However, the dataplane test case can only run on live site currently.

**Comment by blueww** [comment]
Add breaking change exception, for add `[ValidateNotNullOrEmpty]` on the parameter `StandardBlobTier`.
This is not breaking, since: there's validation set before, so null or empty value are also not allowed before.

**Review by isra-fel — APPROVED** [review]
LGTM. Let me know if you want this to be merged now or later. Thanks.

**Pull request merged**
