### PR TITLE
[Storage] Upgrade to Storage SRP SDK 14.1.0

### PR DESCRIPTION
**Pull request by blueww**
## Description

And upgrade API version to 2019-06-01
Update Unit test accordingly. (Server has some behavior change, so change test case to align with it.)

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @blueww ,

there are test cases failed and breaking change issue in CI, can you take a look?

**Comment by blueww** [comment]
@VeryEarly 
Thanks for the remind!
I have raised a fix for it.
Let's see if it can pass build with the fix.

**Comment by VeryEarly** [comment]
> @VeryEarly
> Thanks for the remind!
> I have raised a fix for it.
> Let's see if it can pass build with the fix.

Hi @blueww 

there are conflicts in your pr, can you try fix them?

**Comment by blueww** [comment]
@VeryEarly
I have updated the PR:
1. rebase the code change to fix the conflict
2. Add a new type PSSku to replace the Sku Type from SDK, since the Sku type from SDK removed some properties (these properties should not be add, since server won't return them). 
3. Add some breaking change exception since sku type change. Anyway, this is not real breaking. As I confirmed with Mark before, when the type change, but the content of the type not change, it's not breaking. See https://github.com/Azure/azure-powershell/pull/9005

**Comment by blueww** [comment]
@VeryEarly 
Thanks for the review and merge!

**Pull request merged**
