### PR TITLE
[KubernetesExtension] Create kubernetes extension cmdlets [Another branch]

### PR DESCRIPTION
**Pull request by lijinpei2008**
Create Kubernetes Extension cmdlets:
• Get-AzKubernetesExtension / Get-AzK8sExtension
• New- AzKubernetesExtension / New-AzK8sExtension
• Remove- AzKubernetesExtension / Remove-AzK8sExtension
• Update- AzKubernetesExtension / Update-AzK8sExtension
• Get-AzKubernetesConfiguration / Get-AzK8sConfiguration
• New- AzKubernetesConfiguration / New- AzK8sConfiguration
• Remove- AzKubernetesConfiguration / Remove- AzK8sConfiguration

Design doc: Azure/azure-powershell-cmdlet-review-pr#1047

### CODE REVIEW

**Comment by isra-fel** [comment]
Let me move the pull request to draft state. Please feel free to mark it "Ready for review" when you feel comfortable. Thanks

**Comment by BethanyZhou** [comment]
Hi @isra-fel , this PR is kept to check the CI issue. Another same PR was merged.

**Comment by isra-fel** [comment]
OK, it can remain open.

**Comment by isra-fel** [comment]
Closing the PR as the issue was gone

**Pull request closed without merging**
