### PR TITLE
Move Migrate to master

### PR DESCRIPTION
**Pull request by dolauli**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @prsadhu-ms-idc could you update src/Migrate/Changelog.md on `codegen/Migrate` branch? This is a necessary step of release process. Thanks

**Comment by prsadhu-ms-idc** [comment]
Hi @isra-fel , As part of Az.Migrate using autorest, we write code only for Az.Migrate and raise PR to generation branch. Also we check in only 5 items : custom, docs, test, examples and readme.md. Rest are all auto generated. I don't understand what I have to change in changelog file. Please elaborate.

**Comment by isra-fel** [comment]
Short story: before releasing a new version of the module, we need something to put in changelog
Long story: currently the development of generated modules is divided by 2 steps:

1. Service team (you) push code to `generation` branch
2. Azure PowerShell team (us) generate code based on `generation` branch and check it in to master, which is what this PR is actually doing.

The reason for step 2 is we can therefore use one unified release process for both generated and non-generated modules, and that process requires every module to update their changelog.

**Comment by isra-fel** [comment]
You can simply put changelog here in the comments and I'll be happy to update the file for you :)

**Comment by prsadhu-ms-idc** [comment]
Hi @isra-fel , Thank you for the detailed explanation. I will paste the changelog here. 
-----------------------------------------------------------------------------------------------------------------------------

## Upcoming Release

## Version 0.1.0
* First preview release for module Az.Migrate. The cmdlets to support common scenarios of Migrate like enable replication, update replication item, get migration items, migrate, test migrate and clean up have been exposed. 
 ## Version 0.1.1
* Bug fixed in enable replication, to make default user scenario migrate all disks by default. Earlier the cmdlet was only migrating the OS disk, which was a bug.
## Version 0.1.2
* Bug fixed in update replication migration item to pass all properties (changed/unchanged) to service, and not just the changed ones.
* Bug fixed in enable migrate to pick correct run as account id for VMware Cbt provider.
* Added new parameter (MachineName) in get replication migration item, to get replication migration item by friendly name.
* Bug fixed in enable migrate to stop passing Target Boot Diagnostic Storage Account if it is in a different subscription id than the target VM.
* Fix to in online URLs of existing code doc.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
