### PR TITLE
Fix a few typos in Get-AzMarketplaceTerms.md

### PR DESCRIPTION
**Pull request by OneAndOnlySeabass**
## Description

Fixed a few typos in the documentation of the Get-AzMarketplaceTerms cmdlet.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by vidai-msft** [comment]
@OneAndOnlySeabass please update the doc based on https://github.com/Azure/azure-powershell/blob/generation/src/MarketplaceOrdering/docs/Get-AzMarketplaceTerms.md?plain=1 and then we will take care of the remaining. Thanks for your contribution!

**Comment by vidai-msft** [comment]
@OneAndOnlySeabass gentle ping on this request.

**Comment by OneAndOnlySeabass** [comment]
@vidai-msft Sorry for the delay. I have also updated the file you linked, I had to make a separate PR for that (#21945) as I could not find the file in the patch-1 branch of my fork. Please let me know if this is okay or if I should restructure the PR(s).

**Comment by vidai-msft** [comment]
@OneAndOnlySeabass MarketplaceOrdering is a generated module. So you need to update the doc file from generation branch instead of main. In addition, I just noticed the typo is from the example. So change from the examples is also needed. (I have already submitted a commit to help resolve it). You can close this PR now. Thanks again for your contribution!

**Comment by OneAndOnlySeabass** [comment]
Thanks for your help @vidai-msft, I hereby close this PR.

**Pull request closed without merging**
