### PR TITLE
Introducing Az.Security AdaptiveNetworkHardening cmdlets

### PR DESCRIPTION
**Pull request by ariklin**
## Description

Adaptive Network Hardenings are automatically calculated by Azure Security Center, use this cmdlet to get a list of Adaptive Network Hardenings resources in scope of an extended resource

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

Design review: 

https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/653

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by wyunchi-ms** [comment]
Hi @ariklin , there are some issue of static analysis [here](https://dev.azure.com/azure-sdk/public/_build/results?buildId=465796&view=logs&jobId=2f7369d1-fb97-5262-a571-f4e9c996b7d1&j=e1b7b984-9f58-529f-7c5a-f15f8e35cfa6&t=e8689ae8-b216-55f7-b207-4831f84ff98a), please resolve them.

**Comment by ariklin** [comment]
@wyunchi-ms, please advise, what is wrong? will appreciate some further guidance here.

**Comment by wyunchi-ms** [comment]
First of all, I think you need a design issue for this PR. You can craete a issue [here](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues).

Some suggestions:
1. `Add-AzSecurityAdaptiveNetworkHardening` Does not support ShouldProcess but the cmdlet verb Add indicates that it should.
1. Parameter `Rules` of cmdlet `Add-AzSecurityAdaptiveNetworkHardening` does not follow the enforced naming convention of using a singular noun for a parameter name.
1. Parameter `NetworkSecurityGroups` of cmdlet `Add-AzSecurityAdaptiveNetworkHardening` does not follow the enforced naming convention of using a singular noun for a parameter name.
1. For the verb `Add` it means that `Adds a resource to a container, or attaches an item to another item`. If you want to create a resource, please use `New`.

**Comment by ariklin** [comment]
@wyunchi-ms, please consider my last commit.

**Comment by wyunchi-ms** [comment]
> @wyunchi-ms, please consider my last commit.

Where is the design issue?

**Comment by ariklin** [comment]
@wyunchi-ms,please note, it is embedded in the description section. https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/653

**Comment by wyunchi-ms** [comment]
Hi @ariklin , please update the help files and remove the unnecessary help files.

**Comment by ariklin** [comment]
@wyunchi-ms - removed the unnecessary help files, thanks.

**Pull request merged**
