### PR TITLE
Merge preview into AzureRM.Storage.Location

### PR DESCRIPTION
**Pull request by maddieclayton**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@azuresdkci  Test this please

**Comment by maddieclayton** [comment]
@azuresdkci test this please

**Comment by blueww** [comment]
@maddieclayton , @cormacpayne @markcowl 

I see the netcore build error is caused by some Unit test (from other features) can't find XSCL 9.2.

I have upgraded XSCL to 9.2 for Oauth feature on the storage branch, but I don't change other feature's code. And as I agreed  with Mark before, change XSCL in storage project should not impact other projects. 

Since I am not familiar with the netcore PowerShell project, would your team please help to investigate the issue, and make sure change XSCL in storage project won't impact other feature.


Please note, we will have 3 feature to release around 6/27in Powershell. Hope we have this fixed ASAP to make sure we don't miss the release.

**Comment by vladimir-shcherbakov** [comment]
@maddieclayton 
Is it possible for you to help fixing the net core ci-build?

**Comment by blueww** [comment]
@maddieclayton , @cormacpayne @markcowl

I have tried to fix the build failure by:
1.	Upgrade XSCL to 9.2.0 for all related net core projects (I don’t think this is right. Since in .net we can only upgrade storage projects.)
2.	Fix the netcore script by adding all new cmdlets name.

But there’s still one failure, which I don’t know how to fix:

> Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests.TestAzureStorageAccountManagementPolicy [FAIL]
> Failed Microsoft.Azure.Commands.Management.Storage.Test.ScenarioTests.StorageAccountTests.TestAzureStorageAccountManagementPolicy
> Error Message:
> System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Could not find any resources appropriate for the specified culture or the neutral culture. Make sure "Microsoft.Azure.Commands.Management.Storage.Resources.resources" was correctly embedded or linked into assembly "Microsoft.Azure.Commands.Management.Storage" at compile time, or that all the satellite assemblies required are loadable and fully signed.

Could you help on the fix?
If we can’t fix it in recently several days, can we make it not block the storage module release?
We might can disable netcore Test on branch “AzureRM.Storage.Location” temperately, and file an issue to follow up it. Since:
It should be safe for the storage module release as we only release .net storage module from this branch

**Comment by maddieclayton** [comment]
I can't approved my own PR, but the fix looks good to me! Once approved by someone I will merge.

**Comment by praries880** [comment]
@maddieclayton  approved

**Comment by praries880** [comment]
On demand : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/952/

**Comment by praries880** [comment]
@maddieclayton There are a bunch of vmss and vm test failures in the on [demand job](https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/952/)... can you look at them?


```
08:43:23 (InvokeXUnitAll target) -> 
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests.TestSimpleNewVmssWithSystemAssignedUserAssignedIdentity [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVmssTests.TestSimpleNewVmss [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestSimpleNewVmWithDefaultDomainName2 [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestSimpleNewVmImageName [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestNewVmWin10 [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestSimpleNewVmImageNameMicrosoftSqlUbuntu [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestSimpleNewVm [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestSimpleNewVmWithAvailabilitySet2 [FAIL] [D:\PowerShell-demand\build.proj]
08:43:23   D:\PowerShell-demand\src\ResourceManager\Common\Commands.ScenarioTests.ResourceManager.Common\EnvironmentSetupHelper.cs(643): error : Microsoft.Azure.Commands.Compute.Test.ScenarioTests.StrategiesVirtualMachineTests.TestSimpleNewVmWithSystemAssignedAndUserAssignedIdentity [FAIL] [D:\PowerShell-demand\build.proj]
```

**Comment by maddieclayton** [comment]
on demand here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/955/

**Comment by maddieclayton** [comment]
sign job here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/790/

**Comment by maddieclayton** [comment]
new on demand: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/957/

**Comment by maddieclayton** [comment]
sign job: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/792/

**Comment by vladimir-shcherbakov** [comment]
Both on demand and sign builds failed.

**Comment by maddieclayton** [comment]
on demand here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/960/

**Comment by maddieclayton** [comment]
new sign job: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/797/

**Comment by blueww** [comment]
@maddieclayton ， @cormacpayne 

I see the new signed job still fail:https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/797/
Would you please help to look?

> Remove-Item : Cannot find path 
> 19:42:53   'C:\workspace\powershell-sign\src\Package\AzureRM.Profile\5.3.0' because it 
> 19:42:53   does not exist.
> 19:42:53   At C:\workspace\powershell-sign\tools\PublishModules.ps1:686 char:13
> 19:42:53   +             Remove-Item $TempRepoPath/$moduleName/$($ModuleMetadata.M ...
> 19:42:53   +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
> 19:42:53       + CategoryInfo          : ObjectNotFound: (C:\workspace\po...M.Profile\5.3 
> 19:42:53      .0:String) [Remove-Item], ItemNotFoundException
> 19:42:53       + FullyQualifiedErrorId : PathNotFound,Microsoft.PowerShell.Commands.Remov 
> 19:42:53      eItemCommand
> 19:42:53    
> 19:42:53   C:\workspace\powershell-sign\tools\PublishModules.ps1 : Publish-Module : The 
> 19:42:53   module 'AzureRM.Profile' with version '5.3.0' cannot be 
> 19:42:53   published as the current version '5.3.0' is already available in the 
> 19:42:53   repository 'C:\workspace\powershell-sign\src\Package'.
>

**Comment by blueww** [comment]
@maddieclayton , @cormacpayne 
The signed build pass https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/800/

I have validated the “AzureRM.Storage.5.0.3-preview.nupkg” in https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/800/artifact/src/Package/ 

All test Pass, only the version is not correct.
Since our last release is “AzureRm.Storage.5.0.3-preview”, we should use version “AzureRm. Storage.5.0.4-preview” for this release.

 I have send a commit to update the version to 5.0.4-preview.
And the signed build is running in https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/801/ 

If the build pass, we only need to do a sanity check for this package, and then can release the signed package.

**Comment by blueww** [comment]
The signed build #801 has passed with my commit to upgrade version to “AzureRm. Storage.5.0.4-preview”.

I have sanity check the AzureRM.Storage.5.0.4-preview.nupkg, and all works well.

We can release this AzureRM.Storage.5.0.4-preview.nupkg, like the before release.
I have scheduled a meeting to track the release tomorrow. 

Please help to update me when this is released. I need to do a sanity check after release.

And we can also merge this PR now, as all build pass.

**Pull request merged**
