### PR TITLE
Azure Firewall DNS Proxy support

### PR DESCRIPTION
**Pull request by tejasshah7**
## Description

These changes are to add support for DNS Proxy options to Azure Firewall

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Hi @tejasshah7 , our master branch was force pushed a few weeks ago. It seemed your branch was created before that so there are lots of conflicts, making it impossible to review.
Could you cherry-pick your commits in another PR? Thanks

**Comment by tejasshah7** [comment]
Hi Yeming,

I actually need this change in network-april branch. I rebased the branch to that. Do I still need to do anything?

Thanks,
Tejas

**Comment by isra-fel** [comment]
There are still many conflicts. Here's my suggestion:

- pull network-april
- create a new branch based on network-april and cherry-pick all your commits on tejasshah7:tesha/AzureFirewallDNSProxy
- create a new PR

Sorry for the inconvenience & thanks

**Comment by tejasshah7** [comment]
Against master instead of network-april so closing this.

**Pull request closed without merging**
