### PR TITLE
Add support for ultrassd and SIG to simple param sets for New-AzVm(ss) cmdlets

### PR DESCRIPTION
**Pull request by praries880**
issue : https://github.com/Azure/azure-powershell/issues/6499

related design review :  https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/182

### CODE REVIEW

**Comment by praries880** [comment]
@azuresdkci test this please

**Comment by praries880** [comment]
@hyonholee @maddieclayton can you guys review the PR?

**Comment by maddieclayton** [comment]
@praries880 Please update the help files for the two cmdlets changed.  Other than that this looks good to me once @hyonholee signs off.

**Comment by praries880** [comment]
@maddieclayton updated help files

**Comment by hyonholee** [comment]
Just minor comments and help file description comment.  Other than that, it looks okay.  Thanks.

**Pull request merged**
