### PR TITLE
[Data Share] Updated reference to use latest nuget package

### PR DESCRIPTION
**Pull request by dadihe**
## Description

Update references to use latest nuget package for data share 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @dadihe , the build is failed. Please check the change of SDK.

**Comment by dadihe** [comment]
> Hi @dadihe , the build is failed. Please check the change of SDK.

Hi there, I'd like to use the latest version of [ datashare 1.0.1.](https://www.nuget.org/packages/Microsoft.Azure.Management.DataShare/1.0.1) . What are the changes need to be included other than this in datashare.csproj? thanks~

**Comment by sarajang** [comment]
@wyunchi-ms I am trying to run the scenario tests to regenerate the test json files. However, the calls are failing with the error message below -

```
Message: System.Management.Automation.RuntimeException : Assertion failed because expected 'East US 2' does not match actual 'eastus2'
---- System.Management.Automation.RuntimeException : Assertion failed because expected 'East US 2' does not match actual 'eastus2'
```

I checked the fiddler trace of the outgoing call, the location on the PUT Microsoft.DataShare/accounts is indeed eastus2. However the test framework is expecting it to return 'East US 2'. How can I workaround this issue?

**Comment by sarajang** [comment]
> @wyunchi-ms I am trying to run the scenario tests to regenerate the test json files. However, the calls are failing with the error message below -
> 
> ```
> Message: System.Management.Automation.RuntimeException : Assertion failed because expected 'East US 2' does not match actual 'eastus2'
> ---- System.Management.Automation.RuntimeException : Assertion failed because expected 'East US 2' does not match actual 'eastus2'
> ```
> 
> I checked the fiddler trace of the outgoing call, the location on the PUT Microsoft.DataShare/accounts is indeed eastus2. However the test framework is expecting it to return 'East US 2'. How can I workaround this issue?

This is now resolved.

**Comment by sarajang** [comment]
> Hi @dadihe , the build is failed. Please check the change of SDK.

@wyunchi-ms Can you please review this PR? I updated the PR for build break and tests.

**Pull request merged**
