### PR TITLE
[Az.Security] Add Cmdlets for Security Automations API

### PR DESCRIPTION
**Pull request by surashed**
## Description

`Adding implementation of PS commands for Security Automation API`

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        -  https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1163
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hey @surashed sorry I missed a point in the design review - to differenciate those `New-` cmdlets who create in-memory objects from those who actually create resources on Azure, we name the former cmdlets with a `Object` suffix by convention, for example `New-AzSecurityAutomationRuleObject`.

The second thing is about static analysis. There's a rule that requires all `New-` cmdlets to support ShouldProcess. However, the in-memory cmdlets is an exception. So after renaming them, please [follow this doc to suppress those rule violations.](https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md)

**Comment by surashed** [comment]
> Hey @surashed sorry I missed a point in the design review - to differenciate those `New-` cmdlets who create in-memory objects from those who actually create resources on Azure, we name the former cmdlets with a `Object` suffix by convention, for example `New-AzSecurityAutomationRuleObject`.
> 
> The second thing is about static analysis. There's a rule that requires all `New-` cmdlets to support ShouldProcess. However, the in-memory cmdlets is an exception. So after renaming them, please [follow this doc to suppress those rule violations.](https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md)

Fixed, appreciate your re-review/approval

**Review by isra-fel — APPROVED** [review]
LGTM!

**Pull request merged**
