### PR TITLE
Refactoring RecoveryServices for module merge.

### PR DESCRIPTION
**Pull request by dragonfly91**
## Description

We're proposing the module merge in 3 stages:
1. Refactor the RecoveryServices module for facilitating the merge
2. Move the RecoveryServices.Backup module's contents to the RecoveryServices module
3. Move the RecoveryServices.SiteRecovery module's contents to the RecoveryServices module

This PR implements the stage 1 of the above module merge plan. We have created separate folders for Backup and SiteRecovery related code.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@dragonfly91 you will need to remove the reference to `Microsoft.Azure.Commands.RecoveryServices.Backup.Test.dll` from the following lines in `TestMappings.json`:
- https://github.com/MabOneSdk/azure-powershell/blob/d4d5924e05284b9986dc812889e32d4c8e2f4ca7/TestMappings.json#L48
- https://github.com/MabOneSdk/azure-powershell/blob/d4d5924e05284b9986dc812889e32d4c8e2f4ca7/TestMappings.json#L122

**Comment by cormacpayne** [comment]
@dragonfly91 Jenkins build is passing after removing the lines mentioned above -- would you be able to take a look at the merge conflicts?

**Comment by cormacpayne** [comment]
@dragonfly91 would you mind taking a look at the build failures?

**Comment by dragonfly91** [comment]
I am planning to open a new PR for these changes.

**Pull request closed without merging**
