### PR TITLE
Disk encryption feature

### PR DESCRIPTION
**Pull request by AzureRT**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@AzureRT__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@AzureRT @hyonholee  @huangpf One addition: Please update the AssemblyInfo.cs for Microsoft.Azure.Commands.Compute so the assembly and file versions are '1.1.0'.  You can simply use a string here.

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/322/console

**Comment by markcowl** [comment]
LGTM once the on-demand build passes.

**Pull request merged**
