### PR TITLE
Fix HDI-ADL cluster creation via powershell- Fetching the token from graph endpoint

### PR DESCRIPTION
**Pull request by anthyaga**
can you please review this and check in.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@anthyaga__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (anthyaga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
Tests, please

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by anthyaga** [comment]
+Yogendra

Sent from my Windows Phone
________________________________

**Comment by anthyaga** [comment]
Yogendra(yoreddy@microsoft.com) created a new pull request with test. Closing this.

**Pull request closed without merging**
