### PR TITLE
[AzureLoadTesting] New Module, commands for Azure Load Testing

### PR DESCRIPTION
**Pull request by venkatr21**
## Description

New RP onboarding to Azure PowerShell
Module: Az.LoadTesting
Command:
- New-AzLoad
- Get-AzLoad
- Update-AzLoad
- Remove-AzLoad

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

## Open questions
- Our service GA date is on end of Jan 2023, we would like to release the PowerShell module only around the GA date (mid to end Jan) and not anytime soon, but we would like to wrap up with the review and be ready for the release then. 

- We would need guidance on the tabular format output of the commands. Currently we show only 4 properties as mentioned below. We would like to know if we can show more properties on the tabular output, since we see that most RPs show only minimal essential fields on the tabular output.
```output
Name       Resource group Location DataPlane URL
----       -------------- -------- -------------
sampleres  sample-rg      eastus   00000000-0000-0000-0000-000000000000.eastus.cnt-prod.loadtesting.azure.com
sampleres1 sample-rg      eastus   00000000-0000-0000-0000-000000000001.eastus.cnt-prod.loadtesting.azure.com
```

### CODE REVIEW

**Comment by msJinLei** [comment]
```
2022-12-07T07:34:45.4058831Z Executing script D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\Get-AzLoad.Tests.ps1
2022-12-07T07:34:45.4674279Z Running 'playback' mode...
2022-12-07T07:34:45.4686210Z Recording file 'D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\Get-AzLoad.Recording.json' is not present. Tests expecting recorded responses will fail
2022-12-07T07:34:45.4729611Z 
2022-12-07T07:34:45.4736878Z   Describing Get-AzLoad
2022-12-07T07:34:45.4882206Z     [!] List, is skipped 0ms
2022-12-07T07:34:45.4915221Z     [!] Get, is skipped 0ms
2022-12-07T07:34:45.4947513Z     [!] List1, is skipped 0ms
2022-12-07T07:34:45.5134263Z 
2022-12-07T07:34:45.5139825Z Executing script D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\New-AzLoad.Tests.ps1
2022-12-07T07:34:45.5744634Z Running 'playback' mode...
2022-12-07T07:34:45.5754669Z Recording file 'D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\New-AzLoad.Recording.json' is not present. Tests expecting recorded responses will fail
2022-12-07T07:34:45.5795710Z 
2022-12-07T07:34:45.5802059Z   Describing New-AzLoad
2022-12-07T07:34:45.6171896Z     [!] CreateExpanded, is skipped 0ms
2022-12-07T07:34:45.6427570Z 
2022-12-07T07:34:45.6433677Z Executing script D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\Remove-AzLoad.Tests.ps1
2022-12-07T07:34:45.7044141Z Running 'playback' mode...
2022-12-07T07:34:45.7055394Z Recording file 'D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\Remove-AzLoad.Recording.json' is not present. Tests expecting recorded responses will fail
2022-12-07T07:34:45.7111795Z 
2022-12-07T07:34:45.7112819Z   Describing Remove-AzLoad
2022-12-07T07:34:45.7203483Z     [!] Delete, is skipped 0ms
2022-12-07T07:34:45.7425249Z 
2022-12-07T07:34:45.7430724Z Executing script D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\Update-AzLoad.Tests.ps1
2022-12-07T07:34:45.8366249Z Running 'playback' mode...
2022-12-07T07:34:45.8377644Z Recording file 'D:\a\_work\1\s\artifacts\Debug\Az.LoadTesting\test\Update-AzLoad.Recording.json' is not present. Tests expecting recorded responses will fail
2022-12-07T07:34:45.8422458Z 
```
You should record json for your tests

**Comment by venkatr21** [comment]
@msJinLei the entire test suite is in Az.LoadTesting.Tests.ps1 file
We would want to execute all the tests in a sequential manner like a resource lifecycle, something like Create -> Get -> Update -> Get -> Delete
Should i delete the other test files (empty ones) if they are not getting used?

**Comment by msJinLei** [comment]
> @msJinLei the entire test suite is in Az.LoadTesting.Tests.ps1 file We would want to execute all the tests in a sequential manner like a resource lifecycle, something like Create -> Get -> Update -> Get -> Delete Should i delete the other test files (empty ones) if they are not getting used? They tests which are not recorded are empty ones, which are skipped by the [Skip] parameter


Yes, please remove them

**Comment by msJinLei** [comment]
@venkatr21 If your PR is ready, please remove the `Do Not Merge` tag

**Comment by venkatr21** [comment]
@msJinLei Our service GA date is on end of Jan 2023, we would like to release the PowerShell module only around the GA date (mid to end Jan) and not anytime soon, but we would like to wrap up with the review and be ready for the release then.

Please let us know if merging the PR automatically releases the PowerShell module for our service (if yes, we would like to merge this PR only around our GA date, else if merging the PR does not release the PowerShell module, we would like to merge this now)

**Comment by msJinLei** [comment]
@venkatr21 I will set the target release date

**Comment by venkatr21** [comment]
@msJinLei I have removed the do not merge label

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
