### PR TITLE
Add Microsoft.CLU and clurun to the powershell repo

### PR DESCRIPTION
**Pull request by johanste**
Mostly adding the Microsoft.CLU bits from the private repo.

Changes to existing code: 
- Remove azure.bat from command packages as that is no longer needed
- Update name of the Microsoft.CLU command package to avoid conflicts between the nugget package projects are supposed to reference when building commandlet based command packages and the (name kept as Microsoft.CLU) and the runtime command package intended to be installed by clurun and used to execute commandlet based packages (which is now called Microsoft.CLU.Commands). 
- Minor tweak to build script to special case the build of Microsoft.CLU.Commands package as that is the only package that shouldn't include an azure.lx file (it doesn't expose commands for azure)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@johanste__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (johanste). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@johanste Ithis is too large to review in GitHub, so, I will pull down locally, make sure the packages still build and run, and merge if no issues.

**Comment by markcowl** [comment]
@johanste One issue: in Microsoft.CLU.Run\project.json - the references to NuGet.Commands does not work unless you change the version to 3.3.0.  Please make this change or update nugget config to take in the appropriate feed to get 3.3.0-local

**Pull request merged**
