### PR TITLE
Add solution filter to build

### PR DESCRIPTION
**Pull request by cormacpayne**
## Description

- Fix for https://github.com/Azure/azure-powershell/issues/6232
- Add a `SolutionsMapping.json` file that builds specific solutions based on files changed in a pull request.
- Add missing projects to some solutions to ensure that all solutions can be built on their own from a clean state
- Add `Common.sln` that includes all common code projects and `Commands.Profile` that gets built first during `msbuild` to allow us to remove all of these projects from service teams' solution files

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@cormacpayne You have merge conflicts that need to be resolved.

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/732/

**Comment by maddieclayton** [comment]
Can you please fix the merge conflict? We have moved ChangeLog/psd1 files from src/ResourceManager/{Module} to src/ResourceManager/{Module}/Commands.{Module}, so you will need to move your changelog/psd1 updates there.

**Comment by cormacpayne** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/pull/6469

**Pull request closed without merging**
