### PR TITLE
Fix access error when subscripiton has no Tags property

### PR DESCRIPTION
**Pull request by msJinLei**
## Description
- Fix access error when subscripiton has no Tags property
- Add related test cases
- Related issue: #15425

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by isra-fel — COMMENTED** [review]
LGTM. After replacing local feeds we can merge it.
I'm OK with no changelog because last hotfix version already has it.

**Comment by dingmeng-xue** [comment]
Please add one test case to https://github.com/Azure/azure-powershell/blob/main/tools/Test/SmokeTest/RmCoreSmokeTests.ps1

**Comment by msJinLei** [comment]
> Please add one test case to https://github.com/Azure/azure-powershell/blob/main/tools/Test/SmokeTest/RmCoreSmokeTests.ps1

Added

**Review by isra-fel — APPROVED** [review]
LGTM

**Review by dingmeng-xue — APPROVED** [review]

**Pull request merged**
