### PR TITLE
[Compute] Adding Set-AzVmUefi, Set-AzVmssUefi, Set-AzVmSecurityType, Set-AzVmssSecurityType to support Trusted Launch

### PR DESCRIPTION
**Pull request by sf-76**
## Description

Adding 4 new cmdlets to Az.Compute

Set-AzVmSecurityType
Set-AzVmUefi
Set-AzVmssSecurityType
Set-AzVmssUefi

These four cmdlets will enable customers to enable Trusted Launch on their VMs and VMSS.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/867
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/866
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/735
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/695
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by sirfamelin** [comment]
@wyunchi-ms, I seem to be running into some issues with the Static Analysis portion of the pipeline, I'm not sure where it is going wrong. I've added the 4 cmdlets to the SignatureIssues.csv like I did for the PRs in the Azure-PowerShell-Pr repo but it seems like it is unable to parse the whole .csv file.

**Comment by wyunchi-ms** [comment]
You are missing the double quotes `"`

**Comment by sirfamelin** [comment]
> You are missing the double quotes `"`.
> And I think `ShouldProcess` is necessary. Could you please support it?

In my older PR in the private repo, Isra-fel said that in-memory cmdlets do not support ShouldProcess. https://github.com/Azure/azure-powershell-pr/pull/576#discussion_r502749568

**Comment by sirfamelin** [comment]
@wyunchi-ms looks like the az pipelines pass now after fixing the SignaturesIssues.csv. Is there any chance this PR can still be included in the 3/23 release?

**Comment by wyunchi-ms** [comment]
> > You are missing the double quotes `"`.
> > And I think `ShouldProcess` is necessary. Could you please support it?
> 
> In my older PR in the private repo, Isra-fel said that in-memory cmdlets do not support ShouldProcess. [Azure/azure-powershell-pr#576 (comment)](https://github.com/Azure/azure-powershell-pr/pull/576#discussion_r502749568)
> 
> The cmdlets that config a VM that support ShouldProcess are the Remove-cmdlets
> image

It's OK for in-memory cmdlet.

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
