### PR TITLE
application gateway NRP command-lets

### PR DESCRIPTION
**Pull request by kagamsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kagamsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kaga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@kagamsft Lookjs like you're referencing a version of the network library that is not yet published you will need to publish it first.

**Comment by hovsepm** [comment]
@kagamsft Please reopen PR against dev branch.

**Pull request closed without merging**
