### PR TITLE
Fix to missing OS Version in Get-AzureRole

### PR DESCRIPTION
**Pull request by takekazuomi**
Add OSVersion property. 
#1637

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@takekazuomi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <p>The agreement was validated by Microsoft and real humans are currently evaluating your PR.</p>

TTYL, AZPRBOT;

**Comment by Vijayaraghavanl** [comment]
I also can't see the OS Version!! Also, when this starts working would this work for both ASM and ARM?

**Comment by takekazuomi** [comment]
@Vijayaraghavanl It works only ASM mode. Cloud Service(WebRole and WorkerRole) only available in classics resource and  supported by powershell ASM mode only.

**Comment by stankovski** [comment]
@azuresdkci  add to whitelist

**Pull request merged**
