### PR TITLE
Add parameters for BGP with VPN gateways

### PR DESCRIPTION
**Pull request by lamchester**
Update cmdlets for virtual network gateway, local network gateway, and virtual network gateway connection with additional parameters needed for BGP over IPsec tunnels.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lamchester__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (chelam). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
LGTM

**Comment by huangpf** [comment]
LGTM

**Comment by DeepakRajendranMsft** [comment]
LGTM.
@hovsepm could you please tag me in future Network CRs

**Pull request merged**
