### PR TITLE
[Do not Squash] Merge main branch to Az.Storage-preview branch

### PR DESCRIPTION
**Pull request by blueww**
## Description

File a new PR since https://github.com/Azure/azure-powershell/pull/20956 can't pass PR check.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by blueww** [comment]
@BethanyZhou 

Would you please help to look how to resolve the staticanalysis failure: https://dev.azure.com/azclitools/public/_build/results?buildId=35351&view=logs&j=b9afb22f-0837-5d02-bc24-6c30aee08bcf&t=990f6f37-4a21-5927-092a-220f38a460e9

the cmdlets for the failure are not owned by me.

**Comment by BethanyZhou** [comment]
There are some conflicts need to be fixed. Please have a look.

**Comment by blueww** [comment]
> There are some conflicts need to be fixed. Please have a look.

conflict fixed.

**Comment by blueww** [comment]
@BethanyZhou

Would you please help to look how to resolve the staticanalysis failure:
https://dev.azure.com/azclitools/public/_build/results?buildId=35435&view=logs&j=b9afb22f-0837-5d02-bc24-6c30aee08bcf&t=990f6f37-4a21-5927-092a-220f38a460e9

**Review by BethanyZhou — APPROVED** [review]
Looks  good to me. We ignore examples issues below this time, because they don't belong to storage team
```
 D:\a\_work\1\s\artifacts//StaticAnalysisResults\ExampleIssues.csv Errors
  "Module","Cmdlet","Example","Line","RuleName","ProblemId","Severity","Description","Extent","Remediation"
  "Az.MachineLearningServices","New-AzMLWorkspaceKubernetesObject","1","0","MissingExampleOutput","5045","1","Output of the example is missing.","D:\a\_work\1\s\src\MachineLearningServices\help\New-AzMLWorkspaceKubernetesObject.md","Add output for the example. Remove any placeholders."
  "Az.MachineLearningServices","New-AzMLWorkspaceTritonModelJobInputObject","2","0","MissingExampleTitle","5043","1","Title of the example is missing.","D:\a\_work\1\s\src\MachineLearningServices\help\New-AzMLWorkspaceTritonModelJobInputObject.md","Add title for the example. Remove any placeholders."
  "Az.MachineLearningServices","New-AzMLWorkspaceTritonModelJobInputObject","2","0","MissingExampleCode","5044","1","Code of the example is missing.","D:\a\_work\1\s\src\MachineLearningServices\help\New-AzMLWorkspaceTritonModelJobInputObject.md","Add code for the example. Remove any placeholders."
  "Az.MachineLearningServices","New-AzMLWorkspaceTritonModelJobInputObject","2","0","MissingExampleOutput","5045","1","Output of the example is missing.","D:\a\_work\1\s\src\MachineLearningServices\help\New-AzMLWorkspaceTritonModelJobInputObject.md","Add output for the example. Remove any placeholders."
  "Az.MachineLearningServices","New-AzMLWorkspaceTritonModelJobInputObject","2","0","MissingExampleDescription","5046","1","Description of the example is missing.","D:\a\_work\1\s\src\MachineLearningServices\help\New-AzMLWorkspaceTritonModelJobInputObject.md","Add description for the example. Remove any placeholders."
  "Az.CosmosDB","New-AzCosmosDBAccount","2","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -SourceRestorableDatabaseAccountId is not a valid parameter name.","-SourceRestorableDatabaseAccountId","Check validity of the parameter -SourceRestorableDatabaseAccountId."
  "Az.CosmosDB","New-AzCosmosDBAccount","2","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -RestoreTimesampInUtc is not a valid parameter name.","-RestoreTimesampInUtc","Check validity of the parameter -RestoreTimesampInUtc."
  "Az.CosmosDB","New-AzCosmosDBAccount","3","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -SourceDatabaseAccountName is not a valid parameter name.","-SourceDatabaseAccountName","Check validity of the parameter -SourceDatabaseAccountName."
  "Az.CosmosDB","New-AzCosmosDBAccount","3","1","Invalid_Parameter_Name","5011","1","New-AzCosmosDBAccount -RestoreTimesampInUtc is not a valid parameter name.","-RestoreTimesampInUtc","Check validity of the parameter -RestoreTimesampInUtc."
  "Az.EventGrid","Get-AzEventGridSystemTopic","3","3","Unbinded_Expression","5014","1","Get-AzEventGridSystemTopic $result.NextLink is not explicitly assigned to a parameter.","$result.NextLink","Assign $result.NextLink explicitly to the parameter."
  "Az.EventGrid","Get-AzEventGridSystemTopic","5","3","Unbinded_Expression","5014","1","Get-AzEventGridSystemTopic $result.NextLink is not explicitly assigned to a parameter.","$result.NextLink","Assign $result.NextLink explicitly to the parameter."
  "Az.EventGrid","Get-AzEventGridSystemTopicEventSubscription","4","2","Invalid_Parameter_Name","5011","1","Get-AzEventGridSystemTopicEventSubscription -TopicName is not a valid parameter name.","-TopicName","Check validity of the parameter -TopicName."
  "Az.EventGrid","Get-AzEventGridSystemTopicEventSubscription","4","3","Invalid_Parameter_Name","5011","1","Get-AzEventGridSystemTopicEventSubscription -TopicName is not a valid parameter name.","-TopicName","Check validity of the parameter -TopicName."
  "Az.EventGrid","Get-AzEventGridSystemTopicEventSubscription","4","3","Unbinded_Expression","5014","1","Get-AzEventGridSystemTopicEventSubscription $result.NextLink is not explicitly assigned to a parameter.","$result.NextLink","Assign $result.NextLink explicitly to the parameter."
  "Az.EventGrid","New-AzEventGridSystemTopicEventSubscription","1","1","Invalid_Parameter_Name","5011","1","New-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.EventGrid","New-AzEventGridSystemTopicEventSubscription","2","3","Invalid_Parameter_Name","5011","1","New-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.EventGrid","New-AzEventGridSystemTopicEventSubscription","3","1","Invalid_Parameter_Name","5011","1","New-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.EventGrid","Remove-AzEventGridSystemTopicEventSubscription","1","1","Invalid_Parameter_Name","5011","1","Remove-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.EventGrid","Update-AzEventGridSystemTopicEventSubscription","1","1","Invalid_Parameter_Name","5011","1","Update-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.EventGrid","Update-AzEventGridSystemTopicEventSubscription","2","2","Invalid_Parameter_Name","5011","1","Update-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.EventGrid","Update-AzEventGridSystemTopicEventSubscription","3","1","Invalid_Parameter_Name","5011","1","Update-AzEventGridSystemTopicEventSubscription -ResourceGroup is not a valid parameter name.","-ResourceGroup","Check validity of the parameter -ResourceGroup."
  "Az.MachineLearningServices","Remove-AzMLWorkspaceConnection","1","1","Invalid_Parameter_Name","5011","1","Remove-AzMLWorkspaceConnection -ConnectionName is not a valid parameter name.","-ConnectionName","Check validity of the parameter -ConnectionName."
  "Az.MachineLearningServices","Remove-AzMLWorkspaceConnection","2","1","Invalid_Parameter_Name","5011","1","Get-AzMLWorkspaceConnection -ConnectionName is not a valid parameter name.","-ConnectionName","Check validity of the parameter -ConnectionName."
  "Az.Security","Set-AzSecurityAutomation","1","1","Invalid_Parameter_Name","5011","1","Set-AzSecurityAutomation -Scopes is not a valid parameter name.","-Scopes","Check validity of the parameter -Scopes."
  "Az.Security","Set-AzSecurityAutomation","1","1","Invalid_Parameter_Name","5011","1","Set-AzSecurityAutomation -Sources is not a valid parameter name.","-Sources","Check validity of the parameter -Sources."
  "Az.Security","Set-AzSecurityAutomation","1","1","Invalid_Parameter_Name","5011","1","Set-AzSecurityAutomation -Actions is not a valid parameter name.","-Actions","Check validity of the parameter -Actions."```

**Comment by BethanyZhou** [comment]
@isra-fel could you help force-merge this PR. Please pay attention to 'Do not Squash'.

**Pull request merged**
