### PR TITLE
Added iaas support and tests based on swagger for Azure Batch

### PR DESCRIPTION
**Pull request by brnleehng**
Fixed all the scenario tests and unit tests that were using hyak code generator

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brnleehng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brhoan). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by brnleehng** [comment]
The test that failed was the ProfileModuleTests.WarningOnIncompatibleVersions. I did a diff with my profile module and dev. It looks identical. The only changes I made were in the batch module. How should I go about fixing this? Thanks!

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/665/

**Comment by hovsepm** [comment]
sign job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/353/

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/677/

**Comment by hovsepm** [comment]
sign job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/354/

**Comment by hovsepm** [comment]
new on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/679/
new sign: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/358/

**Comment by hovsepm** [comment]
LGTM.

**Pull request merged**
