### PR TITLE
Updated to use latest Commerce.Usage package

### PR DESCRIPTION
**Pull request by Matt-Westphal**
Just package updates

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Matt-Westphal__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by Matt-Westphal** [comment]
took a few swings to get everything from Azure/dev into my branch and working correctly.  Got it all fixed now

**Comment by Matt-Westphal** [comment]
Updated branch and verified the builds are working.  Is there anything else missing?

**Comment by Matt-Westphal** [comment]
closing this and stating another one.  My branch is super messed up

**Pull request closed without merging**
