### PR TITLE
Improve test (cover *Base); Drop unreachable code

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by EvgenyAgafonchikov** [comment]
@akshaysngupta, FYI, I dropped [some code](https://github.com/Azure/azure-powershell/pull/7773/files#diff-4a3c35681f1bc720c3e7a17c5973e369L81) from RedirectConfigurations.
It is unreachable due to presence of ParameterSets in the cmdlet. I.e. it would fail before with "cannot resolve parameter set" in case one of these parameters combination specified

**Comment by maddieclayton** [comment]
Looks good to me.  @EvgenyAgafonchikov do you want to wait on any approvals from your team or should I merge?

**Comment by EvgenyAgafonchikov** [comment]
@maddieclayton, currently I waiting for @akshaysngupta approval, the change touches resource that is not owned by or team. Pinged by email.

**Comment by akshaysngupta** [comment]
Thanks Evgeny, Changes look good.

**Pull request merged**
