### PR TITLE
Support a new parameter called -ActionGroupId in the Add-AzMetricAlertRuleV2 command in Az.Monitor

### PR DESCRIPTION
**Pull request by sivanguetta**
## Description

Support a new parameter called -ActionGroupId in the Add-AzMetricAlertRuleV2 command in Az.Monitor.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
if I run: 
```
Add-AzMetricAlertRuleV2 -Name $Name -ResourceGroupName $rg -WindowSize $Size -Frequency $Frequency -TargetResourceScope $ResourceScope -TargetResourceType $ResourceType -TargetResourceRegion $ResourceRegion -Condition $Condition -Severity $Severity
```
without providing "ActionGroup" or "ActionGroupId",

How powershell tell which parameter set to use?
Can you try test this scenario?

**Comment by sivanguetta** [comment]
> if I run:
> 
> ```
> Add-AzMetricAlertRuleV2 -Name $Name -ResourceGroupName $rg -WindowSize $Size -Frequency $Frequency -TargetResourceScope $ResourceScope -TargetResourceType $ResourceType -TargetResourceRegion $ResourceRegion -Condition $Condition -Severity $Severity
> ```
> 
> without providing "ActionGroup" or "ActionGroupId",
> 
> How powershell tell which parameter set to use?
> Can you try test this scenario?

@VeryEarly 
Thanks, good catch.
I added 2 parameters sets CreateAlertByResourceId and CreateAlertByScopes, these parameters set will cover the cases that action group was not provided.
In addition I added scenario tests on this case.

**Comment by VeryEarly** [comment]
> > if I run:
> > ```
> > Add-AzMetricAlertRuleV2 -Name $Name -ResourceGroupName $rg -WindowSize $Size -Frequency $Frequency -TargetResourceScope $ResourceScope -TargetResourceType $ResourceType -TargetResourceRegion $ResourceRegion -Condition $Condition -Severity $Severity
> > ```
> > 
> > 
> > without providing "ActionGroup" or "ActionGroupId",
> > How powershell tell which parameter set to use?
> > Can you try test this scenario?
> 
> @VeryEarly
> Thanks, good catch.
> I added 2 parameters sets CreateAlertByResourceId and CreateAlertByScopes, these parameters set will cover the cases that action group was not provided.
> In addition I added scenario tests on this case.
> 
> BTW, are you familiar with a better practice to resolve this parameters combinations?

I think what you did is recommended.

There are static analysis messages you need to suppress (because you used variables for parameter set names which were String before)

Also, for the new parameter sets you added, they should be in the help markdown file.

**Comment by sivanguetta** [comment]
> please also update the help markdown file for new added parameter sets

Done

**Comment by sivanguetta** [comment]
> /azp run azure-powershell - powershell-core

@VeryEarly 
This is my first PR on this solution, I'm not familiar with this command.
Can you please elaborate or refer me to documentation about it?

**Comment by VeryEarly** [comment]
> > /azp run azure-powershell - powershell-core
> 
> @VeryEarly
> This is my first PR on this solution, I'm not familiar with this command.
> Can you please elaborate or refer me to documentation about it?

sorry for the confusion, this command is for triggering the CI job azure-powershell - powershell-core

**Comment by sivanguetta** [comment]
> > > /azp run azure-powershell - powershell-core
> > 
> > 
> > @VeryEarly
> > This is my first PR on this solution, I'm not familiar with this command.
> > Can you please elaborate or refer me to documentation about it?
> 
> sorry for the confusion, this command is for triggering the CI job "azure-powershell - powershell-core"

How can I run it? I tried to run it from PowerShell and PS-VSPrompt but it didn't work?

**Comment by sivanguetta** [comment]
@VeryEarly
Thank you for the review:-)
I see that all checks have passed but I can't merge the pull request because I'm not authorized.
How can I merge the PR? what is missing?

**Comment by VeryEarly** [comment]
> > > > /azp run azure-powershell - powershell-core
> > > 
> > > 
> > > @VeryEarly
> > > This is my first PR on this solution, I'm not familiar with this command.
> > > Can you please elaborate or refer me to documentation about it?
> > 
> > 
> > sorry for the confusion, this command is for triggering the CI job "azure-powershell - powershell-core"
> 
> How can I run it? I tried to run it from PowerShell and PS-VSPrompt but it didn't work?

You can run it on github like I did.

**Comment by VeryEarly** [comment]
> @VeryEarly
> Thank you for the review:-)
> I see that all checks have passed but I can't merge the pull request because I'm not authorized.
> How can I merge the PR? what is missing?

Once your PR was passed all checks and was approved, azure-powershell team will merge it for you.

**Pull request merged**
