### PR TITLE
Fix Role definition name null pointer issue

### PR DESCRIPTION
**Pull request by darshanhs90**
## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by darshanhs90** [comment]
@cormacpayne After running the tests in record mode and getting them passing, when i run the same in playback mode,they are erroring out with some random url not being found. any idea on how to go about that?

**Comment by cormacpayne** [comment]
@darshanhs90 taking a look at the first test failure (`RaGetByUPNWithExpandPrincipalGroups`), the initial call to `Get-AzADUser` fails because it can't find a request in the recording that uses the URI `/395544B0-BF41-429D-921F-E1CA2252FCF4/users` -- in the recording itself, there is a request for `/1273adef-00a3-4086-a51a-dbcce1857d36/users`, so I'm not sure why the tenant ids are different in this case. I'll need to pull this branch down locally and see where we're getting the value of the tenant id that we're instantiating the graph client with.

**Comment by erich-wang** [comment]
@darshanhs90 , please fix test error as suggested:

> @darshanhs90 This is where you can change the tenantId by setting HttpMockServer variables: https://github.com/Azure/azure-powershell/blob/master/tools/TestFx/TestManager.cs#L288

**Comment by erich-wang** [comment]
@darshanhs90, please  fix test error as suggested. We'll close this PR if we don't hear from you five days later.

**Comment by markcowl** [comment]
@darshanhs90 Closing this PR for lack of activity.  Please open a new PR when you are prepared to make this change.  The comments in this PR indicate hpow to fix your current PR issues

**Pull request closed without merging**
