### PR TITLE
add IDns to New-Nic

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**
Update network package
dnssettings -> networkinterfaceDnsSettings
enable Idns on networkinterface
Test location had to be hardcoded because Idns is enabled only 1 region. have an RDbug to change in the future

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
Please address Ogail's comments:

"Network mocked tests are taking ~23 sec to execute and as you know these are just mocked tests which should be executed in microsecs, could u please try to reduce the time? Here are some hints:
- Verify no hard coded timeouts in the code/test script
- Verify that MAML client's property DefaultLongRunningOperationTimeout and RetryTimeout are set to 0

Cheers,
Ogail
"

**Comment by DeepakRajendranMsft** [comment]
working on it.

**Comment by DeepakRajendranMsft** [comment]
I looked at this, and we dont have any hard coded timeouts in the tests. The tests take similar time for compute.tests as well. 
Regarding the client, the MAML tests seem to be quicker (meaning the default configuration should be fine right?). I am not changing the configuration of the client in the PS tests.

For example:https://github.com/Azure/hydra-specs-pr/blob/master/Network2/Microsoft.Azure.Management.Network.Specification/NetworkResourceProvider/PublicIpAddress/PublicIpAddressOperations.Put.cs

[LongRunningOperation("BeginCreateOrUpdating", typeof(Models.OperationStatus), 30, 15,
                DerivedInitialDelayInSeconds = "{$beginResponse.RetryAfter}",
                DerivedRetryDelayInSeconds = "{$result.RetryAfter}", RequestIdName = "AzureAsyncOperation",
                ThrowOnError = true, OperationStatusName = "GetLongRunningOperationStatus")]

is there anything wrong with this configuration. 

The network tests make multiple calls to service (each PUT in itself has 3 calls Get, Put and Get). I am wondering if the sheer size of the mocked json files is affecting the time taken.

I also tried profiling the tests but it only tells me that powershell.Invoke is the major consumer. 

Could  we deal with the time taken for compute and network tests offline?

**Comment by ogail** [comment]
@DeepakRajendranMsft have u tried to change `LongRunningOperationDefaultTimeout` to 0?

**Comment by DeepakRajendranMsft** [comment]
@ogail where do we set this property "LongRunningOperationDefaultTimeout"? 

I can only see 
public LongRunningOperation(string operation, Type operationStatusType, int initialDelayInSeconds, int retryDelayInSeconds);

I couldnt find it in any of the hydra specs either

**Comment by DeepakRajendranMsft** [comment]
@ogail  ping...

Ogail, since this is not a regression, could we work on improving the timing after the release?

**Pull request merged**
