### PR TITLE
ADF - Bump SDK version to 3.0.0 (API version 2015-09-01)

### PR DESCRIPTION
**Pull request by bgold09**
- Impose size limits for all Data Factory resources.
- Stop accepting and returning various copy-related properties.
- Remove properties from TeradataLinkedService which are not supported
  by the service.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bgold09__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brgold). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
on-demand run:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/162/

**Comment by markcowl** [comment]
@bgold09 Can you add these changes to the changelog, please?

**Comment by bgold09** [comment]
@markcowl Sure, should I squash it as part of this commit after the on-demand build passes?

**Comment by markcowl** [comment]
@bgold09 You can add it to this one, or in a separate commit

**Pull request merged**
