### PR TITLE
Add built-in environment for AzureGermanCloud and remove unused source

### PR DESCRIPTION
**Pull request by markcowl**
Resolves issue #2138

### CODE REVIEW

**Comment by markcowl** [comment]
Performing live tests before merge

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/697/

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/718/

**Comment by hovsepm** [comment]
@markcowl LGTM.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/723/

**Comment by markcowl** [comment]
signing run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/400/

**Pull request merged**
