### PR TITLE
Adding support for ConnectionMode for Virtual Network Gateway Connections

### PR DESCRIPTION
**Pull request by abhi7860**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - [Azure/azure-powershell-cmdlet-review-pr](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/769)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
LGTM

**Comment by msJinLei** [comment]
will retry pipe line when devops not so busy

**Comment by VeryEarly** [comment]
Hi @abhi7860 ,

Scenario test TestVirtualNetworkGatewayConnectionwithIpsecPoliciesCRUD had failed:
"Unable to deserialize the response"

Please check if swagger match the actual response.

**Comment by msJinLei** [comment]
Kindly ping @abhi7860. Rerun pipeline for error log is lost

**Comment by msJinLei** [comment]
> Kindly ping @abhi7860. Rerun pipeline for error log is lost

Please fix the following test case
```
  [xUnit.net 00:00:56.13]     Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests.TestVirtualNetworkGatewayConnectionwithIpsecPoliciesCRUD [FAIL]
    X Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests.TestVirtualNetworkGatewayConnectionwithIpsecPoliciesCRUD [1s 930ms]
EXEC : error Message:  [/home/vsts/work/1/s/build.proj]
     System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to deserialize the response.
    Stack Trace:
       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
     at System.Management.Automation.Runspaces.Pipeline.Invoke()
     at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
     at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
     at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
     at System.Management.Automation.PowerShell.Invoke()
     at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 573
     at Microsoft.Azure.Commands.TestFx.TestManager.RunTestScript(String[] scripts) in /home/vsts/work/1/s/tools/TestFx/TestManager.cs:line 227
     at Commands.Network.Test.ScenarioTests.VirtualNetworkGatewayConnectionTests.TestVirtualNetworkGatewayConnectionwithIpsecPoliciesCRUD() in /home/vsts/work/1/s/src/Network/Network.Test/ScenarioTests/VirtualNetworkGatewayConnectionTests.cs:line 65
    Standard Output Messages:
   Test-VirtualNetworkGatewayConnectionWithIpsecPoliciesCRUD
   Caught Exception: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to deserialize the response.
      at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
      at System.Management.Automation.Runspaces.Pipeline.Invoke()
      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
      at System.Management.Automation.PowerShell.Invoke()
      at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in /home/vsts/work/1/s/tools/ScenarioTest.ResourceManager/EnvironmentSetupHelper.cs:line 573
   Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to deserialize the response.
EXEC : PowerShell error Record: Unable to deserialize the response. [/home/vsts/work/1/s/build.proj]
   Exception:Microsoft.Rest.SerializationException: Unable to deserialize the response. ---> Newtonsoft.Json.JsonReaderException: After parsing a value an unexpected character was encountered: ". Path 'properties.dpdTimeoutSeconds', line 41, position 4.
      at Newtonsoft.Json.JsonTextReader.ParsePostValue(Boolean ignoreComments)
      at Newtonsoft.Json.JsonTextReader.Read()
      at Newtonsoft.Json.Linq.JContainer.ReadContentFrom(JsonReader r, JsonLoadSettings settings)
      at Newtonsoft.Json.Linq.JContainer.ReadTokenFrom(JsonReader reader, JsonLoadSettings options)
      at Newtonsoft.Json.Linq.JObject.Load(JsonReader reader, JsonLoadSettings settings)
      at Microsoft.Rest.Serialization.TransformationJsonConverter.ReadJson(JsonReader reader, Type objectType, Object existingValue, JsonSerializer serializer)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.DeserializeConvertable(JsonConverter converter, JsonReader reader, Type objectType, Object existingValue)
      at Newtonsoft.Json.Serialization.JsonSerializerInternalReader.Deserialize(JsonReader reader, Type objectType, Boolean checkAdditionalContent)
      at Newtonsoft.Json.JsonSerializer.DeserializeInternal(JsonReader reader, Type objectType)
```

**Comment by VeryEarly** [comment]
as you can see the history was messed up, it's impossible to review this PR now,
please rebase your branch or create a new PR  (cherry-pick these commits)

**Comment by abhi7860** [comment]
@VeryEarly Please find the new PR link: https://github.com/Azure/azure-powershell/pull/13670

**Pull request closed without merging**
