### PR TITLE
Update *psd1 for every module to use relative path, fix tooling issue in tools/CheckAssemblies.ps1

### PR DESCRIPTION
**Pull request by VeryEarly**
## Checklist

- [ ] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by markcowl** [comment]
@VeryEarly, let's create a signed build based on your branch to test with for this.

**Comment by VeryEarly** [comment]
> Now let's come up with a plan with how we do validation, and we can target this PR for next release.

I'll fix the CI and run smoke test against this build.

**Comment by VeryEarly** [comment]
smoke test passed (except machine learning compute which was deprecated)

**Comment by isra-fel** [comment]
why are there 77 psd1 changed but only 74 change log?

**Comment by VeryEarly** [comment]
> why are there 77 psd1 changed but only 74 change log?

add changelog.md for datafactory and kusto, maintenance was not released yet so should not have change log

**Pull request merged**
