### PR TITLE
Updated Set-AzVirtualNetworkSubnetConfig to allow NSG and Route Table to be removed from subnet

### PR DESCRIPTION
**Pull request by CloudPlatformer**
## Description

Set NSG and Route Table properties of subnet to null if explicitly set in parameters.

Resolves https://github.com/Azure/azure-powershell/issues/1548
Resolves https://github.com/Azure/azure-powershell/issues/9718

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by wyunchi-ms** [comment]
Hi @jack-education , thanks a lot for your contribution! But this may make  [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md). for our customers.

**Comment by wyunchi-ms** [comment]
Hi @jack-education , thanks again for contribution! But this will canse breaking change to the users who didn't set `RouteTableId` or `NetworkSecurityGroupId` in their scripts, this will clear their `RouteTable` or `NetworkSecurityGroup`.
What I suggest for this is:
1. Set `RouteTableId`, `RouteTable`, `NetworkSecurityGroupId`, `NetworkSecurityGroup` to `AllowNull`. So the users can set the value explicitly.

FYI, @number213 what's your suggestion?

**Comment by jack-education** [comment]
Thanks for the feedback @wyunchi-ms , I've updated so the NSG and route table properties are only set to null if it is explicitly set in the parameters.

To remove the NSG / route table from the subnet: RouteTableId, RouteTable, NetworkSecurityGroupId, NetworkSecurityGroup can be set to null and RouteTableId, NetworkSecurityGroupId can be set as empty strings.

Could you please review again?

**Review by msJinLei — CHANGES_REQUESTED** [review]
@jack-education Please add test for you changed cmdlet.

**Comment by msJinLei** [comment]
> @msJinLei Please see the added tests.
> 
> How can I gain access to https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ linked on https://github.com/Azure/azure-powershell/tree/master/src/Network#running-tests so I can create the SessionRecords for the newly added tests and place in this folder https://github.com/Azure/azure-powershell/tree/master/src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests?
> 
> I get an Access Denied page with the message 'jack-education is missing the Overall/Read permission'.
> 
> Thanks

Are you a member of microsoft? Can you join the  https://github.com/orgs/Azure/dashboard?
 https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/  Link is out of date. 
After you join the Azure organization and you will have the access to CI on this page. I can see the test result.

**Comment by jack-education** [comment]
> > @msJinLei Please see the added tests.
> > How can I gain access to https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ linked on https://github.com/Azure/azure-powershell/tree/master/src/Network#running-tests so I can create the SessionRecords for the newly added tests and place in this folder https://github.com/Azure/azure-powershell/tree/master/src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests?
> > I get an Access Denied page with the message 'jack-education is missing the Overall/Read permission'.
> > Thanks
> 
> Are you a member of microsoft? Can you join the https://github.com/orgs/Azure/dashboard?
> https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ Link is out of date.
> After you join the Azure organization and you will have the access to CI on this page. I can see the test result.
> 
> Please also commit the recorded json file in the current PR.

@msJinLei  I'm not a member of microsoft and I can't access https://github.com/orgs/Azure/dashboard

Can none microsoft members join https://github.com/Azure? If they can't, could you please add the recorded json file to the PR?

**Comment by msJinLei** [comment]
> > > @msJinLei Please see the added tests.
> > > How can I gain access to https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ linked on https://github.com/Azure/azure-powershell/tree/master/src/Network#running-tests so I can create the SessionRecords for the newly added tests and place in this folder https://github.com/Azure/azure-powershell/tree/master/src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests?
> > > I get an Access Denied page with the message 'jack-education is missing the Overall/Read permission'.
> > > Thanks
> > 
> > 
> > Are you a member of microsoft? Can you join the https://github.com/orgs/Azure/dashboard?
> > https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ Link is out of date.
> > After you join the Azure organization and you will have the access to CI on this page. I can see the test result.
> > Please also commit the recorded json file in the current PR.
> 
> @msJinLei I'm not a member of microsoft and I can't access https://github.com/orgs/Azure/dashboard
> 
> Can none microsoft members join https://github.com/Azure? If they can't, could you please add the recorded json files to the PR?

If you cannot join the organization, you can still commit .json. The only thing different is you cannot start CI in this PR.

Please commit your recorded json into https://github.com/Azure/azure-powershell/tree/07bf6f679c4d67f5cf2505e3d86c9578f8ff77fb/src/Network/Network.Test/SessionRecords as new added file in this PR.

**Comment by jack-education** [comment]
> > > > @msJinLei Please see the added tests.
> > > > How can I gain access to https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ linked on https://github.com/Azure/azure-powershell/tree/master/src/Network#running-tests so I can create the SessionRecords for the newly added tests and place in this folder https://github.com/Azure/azure-powershell/tree/master/src/Network/Network.Test/SessionRecords/Commands.Network.Test.ScenarioTests.VirtualNetworkTests?
> > > > I get an Access Denied page with the message 'jack-education is missing the Overall/Read permission'.
> > > > Thanks
> > > 
> > > 
> > > Are you a member of microsoft? Can you join the https://github.com/orgs/Azure/dashboard?
> > > https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-network-test/ Link is out of date.
> > > After you join the Azure organization and you will have the access to CI on this page. I can see the test result.
> > > Please also commit the recorded json file in the current PR.
> > 
> > 
> > @msJinLei I'm not a member of microsoft and I can't access https://github.com/orgs/Azure/dashboard
> > Can none microsoft members join https://github.com/Azure? If they can't, could you please add the recorded json files to the PR?
> 
> If you cannot join the organization, you can still commit .json. The only thing different is you cannot start CI in this PR.
> 
> Please commit your recorded json into https://github.com/Azure/azure-powershell/tree/07bf6f679c4d67f5cf2505e3d86c9578f8ff77fb/src/Network/Network.Test/SessionRecords as new added file in this PR and I will start CI.

@msJinLei Could you please provide some guidance how I can create the .json if https://github.com/Azure/azure-powershell/tree/master/src/Network#running-tests is out of date?

**Comment by msJinLei** [comment]
> @msJinLei Could you please provide some guidance how I can create the .json if https://github.com/Azure/azure-powershell/tree/master/src/Network#running-tests is out of date?

Please refer to the https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/azure-powershell-developer-guide.md#recordingrunning-tests for how to add and record scenario test.

Record your new added test and json file will be generated.

**Comment by jack-education** [comment]
@msJinLei I've added the recorded json, could you please review/start CI?

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
