### PR TITLE
Adding API Management SMAPI cmdlets

### PR DESCRIPTION
**Pull request by ailn**
Adding API Management SMAPI cmdlets: https://microsoft.sharepoint.com/teams/apimanagement/Shared%20Documents/Design/ApiManagement%20SMAPI%20PowerShell%20specification.docx

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ailn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ailn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by pcgeek86** [comment]
Thanks for continuing to support the Service Management API. It is what most customers are using until ARM is fully baked.

Cheers,
Trevor Sullivan
Microsoft MVP: PowerShell

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by ogail** [comment]
@ailn please fix CI failures and resolve conflicts

**Pull request merged**
