### PR TITLE
Update Test Deployments to allow the user to specify a deployment name

### LINKED ISSUE #11497: PowerShell Test-AzDeplyoment is missing a name parameter
## Description of the new feature
When you run a PowerShell New-AzDeplyoment on Azure and you don’t specify a deployment name, the deployment will be named after the file, like “deploy” if you use a “deploy.json”. What is happening in the background is, that this deployment name for that tenant gets linked to the deployment region. This link is not changeable. So if you deploy the same file to a different region without a custom deployment name, it will fail. As you can change the name in New-AzDeployment with the name parameter, this limitation is easily to overcome. Unfortunately, when you want to test your deployment with Test-AzDeployment, you cannot specify the deployment name, which means it uses internally the file name. The test will fail in that case, that this file was already deployed in another region. The only workaround is to rename the file. 
## Proposed implementation details (optional)
Add the "name" parameter to the Test-AzDeployment commandlet

### PR DESCRIPTION
**Pull request by jontreynes**
## Description
This is an attempt to resolve #11497.  The changes should allow the user to specify a deployment name during Test-Az* commands.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by jontreynes** [comment]
@vidyadharijami and @Xynoclafe

I'm attempting a draft to resolve #11497 . May you please show me how test this draft? I'm not familiar with this code base. Thank you

**Comment by jontreynes** [comment]
@Xynoclafe - there is no .\src\Resources\ResourceManager\ChangeLog.md, do you need this PR to create it from scratch?

**Comment by Xynoclafe** [comment]
> @Xynoclafe Gokul Premraj FTE - there is no .\src\Resources\ResourceManager\ChangeLog.md, do you need this PR to create it from scratch?

The changelog file would be - .\src\Resources\Resources\ChangeLog.md

**Comment by jontreynes** [comment]
I tested Test-AzSubscriptionDeployment locally on my machine using powershell 7.1.0. I don't have access to see the azure-pipeline runs so hoping it checks out just fine. 

I ran the Update-MarkdownHelpModule as per the documentation and it updated a couple other command helper messages other than the Test-* commands

**Comment by jontreynes** [comment]
@Xynoclafe - when I did the Update-MarkdownHelpModule, there was no Test-AzSubscriptionDeployment command to update.

I noticed that all the "Alias" CommandTypes do not show in the help folder specifically these ones
```
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Alias           Get-AzADServicePrincipalCredential                 3.5.0      Az.Resources
Alias           Get-AzResourceProviderAction                       3.5.0      Az.Resources
Alias           Get-AzSubscriptionDeployment                       3.5.0      Az.Resources
Alias           Get-AzSubscriptionDeploymentOperation              3.5.0      Az.Resources
Alias           Get-AzSubscriptionDeploymentWhatIfResult           3.5.0      Az.Resources
Alias           New-AzADServicePrincipalCredential                 3.5.0      Az.Resources
Alias           New-AzSubscriptionDeployment                       3.5.0      Az.Resources
Alias           Remove-AzADServicePrincipalCredential              3.5.0      Az.Resources
Alias           Remove-AzSubscriptionDeployment                    3.5.0      Az.Resources
Alias           Save-AzSubscriptionDeploymentTemplate              3.5.0      Az.Resources
Alias           Set-AzADApplication                                3.5.0      Az.Resources
Alias           Set-AzADServicePrincipal                           3.5.0      Az.Resources
Alias           Set-AzADUser                                       3.5.0      Az.Resources
Alias           Stop-AzSubscriptionDeployment                      3.5.0      Az.Resources
Alias           Test-AzSubscriptionDeployment                      3.5.0      Az.Resources
```

**Comment by jontreynes** [comment]
@msJinLei thanks for running that bot. I see all checks have passed. Let me know if you need anything else included in the PR

**Comment by msJinLei** [comment]
> @msJinLei thanks for running that bot. I see all checks have passed. Let me know if you need anything else included in the PR

Code is LGTM.

Could you resolve the merge conflicts?

**Comment by jontreynes** [comment]
On it @msJinLei 

I put the changelog comment under upcoming releases. Looks like we just missed the 4.1.0 release

**Comment by jontreynes** [comment]
> Commenter does not have sufficient privileges for PR 15082 in repo Azure/azure-powershell

@msJinLei may you help me out here. Thank you!

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
