### PR TITLE
Updating NewAzurePublicIpPrefixCommand.cs to make location mandatory

### PR DESCRIPTION
**Pull request by brianlehr**
## Description

Updating NewAzurePublicIpPrefixCommand.cs to make location mandatory, as it is always required

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by brianlehr** [comment]
@MikhailTryakhov Could you please review this change?

**Comment by brianlehr** [comment]
#sign-off

**Comment by msJinLei** [comment]
@brianlehr 
You cannot change a optional parameter to mandatory in a non-major release since it is a [breaking change](https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md)

**Comment by brianlehr** [comment]
> @brianlehr
> 
> * You cannot change a optional parameter to mandatory in a non-major release since it is a [breaking change](https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md)
> * For you patch, you should
>   
>   * Describe your change in the changelog.md
>   * Regenerate help doc to include the update

The problem is that it is not a non-optional parameter now.  There is no case where a Public IP Prefix can be created without a location parameter.  So all this is doing is fixing an error.

**Comment by msJinLei** [comment]
> > @brianlehr
> > 
> > * You cannot change a optional parameter to mandatory in a non-major release since it is a [breaking change](https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md)
> > * For you patch, you should
> >   
> >   * Describe your change in the changelog.md
> >   * Regenerate help doc to include the update
> 
> @msJinLei The problem is that it is not a non-optional parameter now. There is no case where a Public IP Prefix can be created without a location parameter. So all this is doing is fixing an error.

What will happen If the user doesn't create a IP prefix without a location for now?

**Comment by brianlehr** [comment]
> > > @brianlehr
> > > 
> > > * You cannot change a optional parameter to mandatory in a non-major release since it is a [breaking change](https://github.com/Azure/azure-powershell/blob/main/documentation/breaking-changes/breaking-changes-definition.md)
> > > * For you patch, you should
> > >   
> > >   * Describe your change in the changelog.md
> > >   * Regenerate help doc to include the update
> > 
> > 
> > @msJinLei The problem is that it is not a non-optional parameter now. There is no case where a Public IP Prefix can be created without a location parameter. So all this is doing is fixing an error.
> 
> What will happen If the user doesn't create a IP prefix without a location for now?

It fails.  Example below:

PS /home/brian> New-AzPublicIpPrefix -Name testprefix -ResourceGroupName planning -PrefixLength 31
WARNING: Upcoming breaking changes in the cmdlet 'New-AzPublicIpPrefix' :
Default behaviour of Zone will be changed
Cmdlet invocation changes :
    Old Way : Sku = Standard means the Standard PublicIpPrefix is zone-redundant.
    New Way : Sku = Standard and Zone = {} means the Standard PublicIpPrefix has no zones. If you want to create a zone-redundant PublicIpPrefix, please specify all the zones in the region. For example, Zone = ['1', '2', '3'].
Note : Go to https://aka.ms/azps-changewarnings for steps to suppress this breaking change warning, and other information on breaking changes in Azure PowerShell.
New-AzPublicIpPrefix: The location property is required for this definition.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: LocationRequired
**ErrorMessage: The location property is required for this definition.**
OperationID : 86e59b16-825d-412f-a5c4-9c97008c2489

**Comment by msJinLei** [comment]
> * For you patch, you should
>   
>   * Describe your change in the changelog.md
>   * Regenerate help doc to include the update

In addition, please refer to https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes to suppress the breaking change

**Comment by brianlehr** [comment]
> 
@msJinLei 

The help doc has already been updated.  See https://github.com/Azure/azure-powershell/pull/19692.

Could you point me to the changelog.md?

**Comment by msJinLei** [comment]
@brianlehr please merge the changes in https://github.com/Azure/azure-powershell/pull/20007 and https://github.com/Azure/azure-powershell/pull/20008

**Comment by msJinLei** [comment]
> > 
> 
> @msJinLei
> 
> The help doc has already been updated. See #19692.
> 
> Could you point me to the changelog.md?

https://github.com/Azure/azure-powershell/blob/b08f41af96795d90926a948d8dcf377cdd6f0d0d/src/Network/Network/ChangeLog.md

**Comment by msJinLei** [comment]
> @brianlehr please merge the changes in #20007 and #20008

Please include all the logical related changes into one PR.

**Comment by brianlehr** [comment]
> > @brianlehr please merge the changes in #20007 and #20008
> 
> Please include all the logical related changes into one PR.

Hi again @msJinLei 

- Any help on how to merge the changes?
- Should I add it to the 5.1.0 changelog?

**Comment by msJinLei** [comment]
> > > @brianlehr please merge the changes in #20007 and #20008
> > 
> > 
> > Please include all the logical related changes into one PR.
> 
> Hi again @msJinLei
> 
> * Any help on how to merge the changes?
> * Should I add it to the 5.1.0 changelog?

You are not required to merge these 2 PRs but recommended.
Firstly, you should fix the static analysis error by suppressing the breaking change error

> > * For you patch, you should
> >   
> >   * Describe your change in the changelog.md
> >   * Regenerate help doc to include the update
> 
> In addition, please refer to https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes to suppress the breaking change

**Comment by isra-fel** [comment]
Kindly ping @brianlehr
Please follow the instructions in the above link to suppress the warnings of breaking changes to unblock the failed checks.

**Comment by msJinLei** [comment]
@MikhailTryakhov Please take a look at the PR and see whether the PR is required for the upcoming release, thanks

**Comment by msJinLei** [comment]
duplicate with https://github.com/Azure/azure-powershell/pull/20008

**Comment by brianlehr** [comment]
@msjinlei

> duplicate with #20008

This is not a duplicate.  This change is for PublicIpPrefix, the other is for PublicIpAddress.

**Comment by msJinLei** [comment]
@brianlehr To switch an optional parameter to mandatory is a break change. We can accept it only if the cmdlet always fails without the parameter. Is that true?

>**Please response as soon as possible for we will freeze code next Monday. Thank you for your understanding and cooperation.**

**Comment by brianlehr** [comment]
> @brianlehr To switch an optional parameter to mandatory is a break change. We can accept it only if the cmdlet always fails without the parameter. Is that true?
> 
> > **Could you response as soon as possible for we will freeze code next Monday? Thank you for your understanding and cooperation.**

@msJinLei This field is already mandatory, and yes it always fails without parameter.

**Comment by msJinLei** [comment]
Please fix the static analysis error refer to the following example.

```
Suppress the breaking change errors in "tools/StaticAnalysis/Exceptions/${ModuleName}/BreakingChangeIssues.csv"
"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
"Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzFirewallPolicyNatRuleCommand","New-AzFirewallPolicyNatRule","0","1050","The parameter set '__AllParameterSets' for cmdlet 'New-AzFirewallPolicyNatRule' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'New-AzFirewallPolicyNatRule'."
```

**Comment by wyunchi-ms** [comment]
This is fixed in https://github.com/Azure/azure-powershell/pull/22909

**Pull request closed without merging**
