### PR TITLE
Replace tests for LoadBalancer's OutboundRules with generated ones

### PR DESCRIPTION
**Pull request by anton-evseev**
## Description

Due to time contraints for Ignite, I had to manually edit generated tests for OutboundRules to make them work. This PR replaces those tests with the ones that are generated correctly.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by number213** [comment]
Unrelated test fails
```
Failed   Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests.TestRestoreDeletedWebAppToNew
Error Message:
 System.Management.Automation.RuntimeException : Assertion failed because expected 'Completed' does not match actual ''
```

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
@number213 Hey Anton, a fix for this was merged into the `preview` branch. If you're not able to merge the latest from `preview` into this branch, here are the lines that you'll need to change:

https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Websites/Commands.Websites.Test/ScenarioTests/WebAppBackupRestoreTests.cs#L133-L138

**Comment by number213** [comment]
Open PR to sync NRP branch with `preview`, will update this PR after the other one gets merged
https://github.com/Azure/azure-powershell/pull/7502

**Comment by cormacpayne** [comment]
@number213 that PR has been merged -- you should be good to pull those changes into this PR

**Comment by cormacpayne** [comment]
@number213 the changes being in this PR LGTM, so once the latest changes are merged into this PR, we should be good to merge

**Comment by number213** [comment]
@cormacpayne done

**Comment by praries880** [comment]
@cormacpayne ping

**Pull request merged**
