### PR TITLE
Cmdlets for Azure RM Backup/Restore

### PR DESCRIPTION
**Pull request by hchungmsft**
- Implements the following:
  - Get-AzureRmSqlDatabaseGeoBackup
  - Get-AzureRmSqlDeletedDatabaseBackup
  - Restore-AzureRmSqlDatabase
    - This cmdlet accepts as pipelined input the result of one of the first two cmdlets (or Get-AzureRmSqlDatabase if restoring a live DB to a point-in-time)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hchungmsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuuresdkci add to whitelist

**Comment by markcowl** [comment]
@hchungmsft Please add help content and update the changelog for these changes.

**Comment by hovsepm** [comment]
@hchungmsft please fix build issues.

**Comment by hchungmsft** [comment]
Needs Nuget package from azure-sdk-for-net first.  Working on fixing a build issue in that PR.

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/550/

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
new on demand run:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/550/

**Pull request merged**
