### PR TITLE
[Synapse] Fix deserialization issue for creating Pipeline/Dataset/Trigger

### PR DESCRIPTION
**Pull request by wonner**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Could you please offer the diff of these data models such as `DataFlow` as `PSDataFlow`.

**Comment by wonner** [comment]
> Could you please offer the diff of these data models such as `DataFlow` as `PSDataFlow`.

**Comment by wonner** [comment]
> Could you please offer the diff of these data models such as `DataFlow` as `PSDataFlow`.

`DataFlow` is a model in SDK, it has some subclasses such as `MappingDataFlow`. In the previous code, we only return the wrapper class `PSDataFlow`, it will miss the properties in subclass. So we keep align with ADF here, just provided the real data flow sub type. (In ADF, the link is: [DataFlow Class (Microsoft.Azure.Management.DataFactory.Models) - Azure for .NET Developers | Microsoft Docs](https://docs.microsoft.com/en-us/dotnet/api/microsoft.azure.management.datafactory.models.dataflow?view=azure-dotnet))

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
