### PR TITLE
[Storage] Merge lastest change on master to storage branch

### PR DESCRIPTION
**Pull request by blueww**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by blueww** [comment]
@msJinLei 
Would you please help to look at the "Test macOS" fail. It seems the failure is not cuase by my change, but it fails before the build finish:


> /Users/runner/.dotnet/sdk/2.2.105/NuGet.targets(499,5): error : Could not find a part of the path '/var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/NuGetScratch/49b01f22-830d-483d-af3a-742d99b7ae72'. [/Users/runner/runners/2.163.1/work/1/s/tools/ScenarioTest.ResourceManager/ScenarioTest.ResourceManager.csproj] [/Users/runner/runners/2.163.1/work/1/s/build.proj]


> /Users/runner/runners/2.163.1/work/1/s/build.proj(246,5): error MSB3073: The command "dotnet test /Users/runner/runners/2.163.1/work/1/s/artifacts/Azure.PowerShell.sln --filter "AcceptanceType=CheckIn&RunType!=DesktopOnly" --configuration Debug --framework netcoreapp2.2 --logger trx --results-directory "/Users/runner/runners/2.163.1/work/1/s/artifacts//TestResults"" exited with code 1.
> 
> /Users/runner/runners/2.163.1/work/1/s/build.proj(266,5): error : Test failures occurred, check the files in artifacts/TestResults

**Comment by msJinLei** [comment]
@blueww You can sync with the latest master if you want

**Comment by blueww** [comment]
@msJinLei 
I have Sync the lastest code from master branch, and revert the commit of revert the preview change, to add back the features on preview module of Az.Storage.
I have run storage regression locally, and it works well.

One Left question, How should I handle "tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Storage.dll.json"?
Currently, I use the file from master branch in this PR. 
How can I validate if it's correct? and how can I make it correct?

**Comment by msJinLei** [comment]
> @msJinLei
> I have Sync the lastest code from master branch, and revert the commit of revert the preview change, to add back the features on preview module of Az.Storage.
> I have run storage regression locally, and it works well.
> 
> One Left question, How should I handle "tools/Tools.Common/SerializedCmdlets/Microsoft.Azure.PowerShell.Cmdlets.Storage.dll.json"?
> Currently, I use the file from master branch in this PR.
> How can I validate if it's correct? and how can I make it correct?

When you merge back to master,  just make ensure no change it all the *.dll.jsons. That should be OK.
For your branch ,use the dll.json* from master.

**Comment by blueww** [comment]
@msJinLei 
Thanks for the quick review and merge!
> When you merge back to master, just make ensure no change it all the .dll.jsons.
Actually, this won't be merge back to master. When need move the features on preview to master, I will write another commit, and PR.

**Pull request merged**
