### PR TITLE
[CosmosDB] Migration support for throughput

### PR DESCRIPTION
**Pull request by MehaKaushik**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by MehaKaushik** [comment]
@dingmeng-xue can you recommend a Powershell approved verb in place of "Migrate". "Move" is not appropriate here because we are not moving the resource to any location. 

The operation here changes the policy of the pricing of the throughput resource. It can be manual i.e user-chosen throughput or autoscale, where the system chooses throughput for the user. In both cases, the resource looks the same and the location remains the same.

**Review by msJinLei — CHANGES_REQUESTED** [review]
@MehaKaushik Please fix the generating help error and test failure.

**Comment by MehaKaushik** [comment]
@msJinLei please review whenever you get a chance.

**Comment by msJinLei** [comment]
> @msJinLei please review whenever you get a chance.

Could you provide the link to the design review?

**Comment by MehaKaushik** [comment]
@msJinLei  I had not started a design review for these, since it was a small change. 
But since you insist, I have created it now https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/738 

I was hoping to get this PR checked in S175, this is a very high priority customer ASK. Can we please work towards checking this in by s175.

**Comment by msJinLei** [comment]
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/738

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
