### PR TITLE
Initial version of Azure NetApp Files Powershell cmdlets

### PR DESCRIPTION
**Pull request by leonardbf**
Internal NFSAAS-1707.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cormacpayne** [comment]
@leonardbf Hey Leonard, for any new modules, cmdlets, features, etc., we require that the changes go through a design review, which is held [here](https://github.com/Azure/azure-powershell-cmdlet-review-pr). You can file an issue and follow the provided template -- usually this involves providing the corresponding `.md` files for each cmdlet you are introducing, as well as any additional documentation that our team would need to get a better understanding of your service. Once this design review has been completed, we can begin reviewing this PR. Please let me know if you have any questions!

**Comment by leonardbf** [comment]
Ok. Design review issue created 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/255

**Comment by maddieclayton** [comment]
@azuresdkci Add to whitelist

**Comment by cormacpayne** [comment]
Closing this PR in favor of https://github.com/Azure/azure-powershell/pull/8773

**Pull request closed without merging**
