### PR TITLE
[Az.Functions] Remove preview from the PowerShell 7.0 stack on Linux

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
## Description

Resolves https://github.com/Azure/azure-powershell/issues/16587

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
Hello @msJinLei -- Could you please run `/azp run` ? I've tried, but I dot have permission to perform this operation.

**Comment by msJinLei** [comment]
@Francisco-Gamino is a new version of Az.Functions called for this change?

**Comment by Francisco-Gamino** [comment]
> @Francisco-Gamino is a new version of Az.Functions called for this change?

@msJinLei -- Yes, we should release a new version of Az.Functions for this change. The current version is 4.0.0, and for this change we should do a minor version update.

**Comment by Francisco-Gamino** [comment]
Hello @msJinLei -- Please let me know if you need anything else from my side. I will be OOF after Friday 12/17. Thanks!

**Comment by msJinLei** [comment]
> Hello @msJinLei -- Please let me know if you need anything else from my side. I will be OOF after Friday 12/17. Thanks!

If yes, please add description to ChangeLog.md of Az.Functions

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
