### PR TITLE
[Azure Site Recovery] Making name non mandatory in NewAzureRMSiteRecoveryNetworkMapping and NewAzureRmSiteRecoveryStorageClassificationMapping.

### PR DESCRIPTION
**Pull request by avneeshrai**
Making name non mandatory in NewAzureRMSiteRecoveryNetworkMapping and NewAzureRmSiteRecoveryStorageClassificationMapping

### CODE REVIEW

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by sphibbs** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
http://azuresdkci.cloudapp.net/job/powershell/6499/

**Comment by cormacpayne** [comment]
LGTM

**Comment by cormacpayne** [comment]
@azuresdkci retest this please

**Pull request merged**
