### PR TITLE
Add new parameter to redis cache cmdlet.

### PR DESCRIPTION
**Pull request by Priya91**
## Description

Add a new parameter 'Port' to cmdlet 'Reset-AzRedisCache.'

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

Review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/730

### CODE REVIEW

**Comment by Priya91** [comment]
The PR windows-powershell ci is failing because the build machines don't have the .net core 2.2 installed. How do i fix this issue? This is not related to changes made in this PR.

**Comment by msJinLei** [comment]
> The PR windows-powershell ci is failing because the build machines don't have the .net core 2.2 installed. How do i fix this issue? This is not related to changes made in this PR.
@Priya91
We have the issue fixed in the master.
Can you merge from master and check whether the file https://github.com/Azure/azure-powershell/blob/master/.azure-pipelines/windows-powershell.yml contains the latest change?

**Comment by Priya91** [comment]
cc @mechandr

**Comment by msJinLei** [comment]
We are going to close the PR since no update for a long time. You can submit a new pull request when needed.

**Pull request closed without merging**
