### PR TITLE
fix wording to be more clear per docs request

### PR DESCRIPTION
**Pull request by xyh1**
see issue https://github.com/MicrosoftDocs/azure-docs/issues/31203

## Description

Changed text descriptions to be more clear that is is for removing unlocked immutability policies

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by niander** [comment]
@xyh1 Hi. Could you add a changelog entry?

**Comment by niander** [comment]
@xyh1 The changelog entry was in the wrong place. I moved it for you. I will approve the PR. Should we wait for @blueww approval as well?

**Comment by xyh1** [comment]
@niander Thanks for the help! You can just push without another review from Wei.

**Pull request merged**
