### PR TITLE
{WebApp} fix the not recognized as a valid DateTime error

### PR DESCRIPTION
**Pull request by navba-MSFT**
This conversion to localtime should fix the conversion issue due to localization format

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
    
    More Info:
    ===============
    When running the cmdlet with non en-US (at least, in pl-PL culture) the cmdlet fails with example error:
String '01/24/2022 22:52:39' was not recognized as a valid DateTime.
Output of:
[system.threading.thread]::CurrentThread.CurrentCulture
LCID Name DisplayName
1045 pl-PL Polish (Poland)

**Steps to reproduce:**
1. Run the below command in your Powershell:
[system.threading.thread]::CurrentThread.CurrentCulture = [System.Globalization.CultureInfo]::GetCultureInfo("pl-PL")
Get-AzWebAppSnapshot -ResourceGroupName $SourceRG -Name $WebAppName

This fails with the error: String '01/24/2022 22:52:39' was not recognized as a valid DateTime.

2. When changing CurrentThread.CurrentCulture to en-US it works OK.

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @navba-MSFT, have you figure where this command transfer from `01/24/2022 22:52:39` to local time in error scenario?

**Comment by BethanyZhou** [comment]
Hi @navba-MSFT , a test case is failed, please have a look.

  [xUnit.net 00:01:00.29]     Microsoft.Azure.Commands.Websites.Test.ScenarioTests.CertificatesTests.TestNewAzWebAppCertificateForSlot [FAIL]

**Review by BethanyZhou — APPROVED** [review]
LGTM

**Review by BethanyZhou — APPROVED** [review]

**Comment by navba-MSFT** [comment]
@BethanyZhou Thanks for reviewing this. Could you merge this once you get a chance ?

**Comment by BethanyZhou** [comment]
Sure, I will merge it when the CI passed. @navba-MSFT

**Pull request merged**
