### PR TITLE
Merging StackAdmin-1.5.0 to preview

### PR DESCRIPTION
**Pull request by bganapa**
## Description

Merging StackAdmin-1.5.0 to preview

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by bganapa** [comment]
ps-sign - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1384/
psnetsign - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/216/

**Comment by bganapa** [comment]
ps-sign failing with 
11:26:39 C:\workspace\ps-sign\build.proj(287,5): error MSB3073: The command ""C:\Windows\System32\WindowsPowerShell\v1.0\powershell.exe" -NonInteractive -NoLogo -NoProfile -Command " . C:\workspace\ps-sign\tools\NewHelpIndex.ps1 -OutputFile C:\workspace\ps-sign\src\Package\index.json -BuildConfig Release "" exited with code 1.


 Exception calling "Add" with "2" argument(s): "Item has already been added. 
11:26:38   Key in dictionary: 'AzureRM.Profile'  Key being added: 'AzureRM.Profile'"
11:26:38   At C:\workspace\ps-sign\tools\NewHelpIndex.ps1:141 char:31
11:26:38   +         $outputModules.Add("$($_.BaseName)", @{"module" = @{"sourceUr ...
11:26:38   +                               ~~~~~~~~~~~
11:26:38       + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
11:26:38       + FullyQualifiedErrorId : ArgumentException

**Comment by cormacpayne** [comment]
@bganapa please pull in the latest changes from the `preview` branch -- a fix for the above issue has been merged

**Comment by bganapa** [comment]
@cormacpayne Thanks. New ps-sign - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1391/

**Comment by bganapa** [comment]
This should be good to merge.. ps sign is successful

**Pull request merged**
