### PR TITLE
[EventHub]: Deprecating MSI properties for breaking change release

### PR DESCRIPTION
**Pull request by damodaravadhani**
## Description

Deprecating older MSI properties from Set-AzEventHubNamespace and New-AzEventHubNamespace. 

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1190
    - [X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Please fix the breaking change exceptions.

**Comment by damodaravadhani** [comment]
Do you mean suppress the exceptions ? because we want these breaking changes in.

**Comment by wyunchi-ms** [comment]
> Do you mean suppress the exceptions ? because we want these breaking changes in.

Yes, and please resolve the conflicts.

**Comment by wyunchi-ms** [comment]
Yes, you can append the exceptions throwed from static analysis to the `BreakingChange.csv` to pass the CI check.

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
