### PR TITLE
Build powershell off 2021-07-12 stable

### PR DESCRIPTION
**Pull request by datr93**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @datr93 , please sync your branch with generation branch to have CI fixed

**Comment by datr93** [comment]
@VeryEarly  can you please take another look. its now failing on some static analysis and the error is related to az.accounts

https://dev.azure.com/azure-sdk/public/_build/results?buildId=1062636&view=logs&j=e1b7b984-9f58-529f-7c5a-f15f8e35cfa6&t=e8689ae8-b216-55f7-b207-4831f84ff98a

**Comment by VeryEarly** [comment]
> @VeryEarly can you please take another look. its now failing on some static analysis and the error is related to az.accounts
> 
> https://dev.azure.com/azure-sdk/public/_build/results?buildId=1062636&view=logs&j=e1b7b984-9f58-529f-7c5a-f15f8e35cfa6&t=e8689ae8-b216-55f7-b207-4831f84ff98a

these are not related to az.accounts, please suppress breaking change issues detected by static analysis to:
https://github.com/datr93/azure-powershell/tree/generation/tools/StaticAnalysis/Exceptions/Az.DesktopVirtualization/BreakingChangeIssues.csv

**Comment by datr93** [comment]
@VeryEarly I post on the team channel. How do I suppress breaking change warnings?

I bump the api version from 2021-02-01-preview to 2021-07-12 stable, and rebuilt the PS. The ./test-modules.ps1 passes but CI build is failing on static analysis.
 
steps:
update readme to point to stable swagger.
run: autorest
run: ./build-modules.ps1
bump test versions to 2021-07-12
run: ./test-modules.ps1 (passes)
checkin/pr
 
The error message is telling me to revert back from Api20210712 to Api20210201Preview. But im trying to use Api20210712.
 
pr: https://github.com/Azure/azure-powershell/pull/15732
error: https://dev.azure.com/azure-sdk/public/_build/results?buildId=1063361&view=logs&j=99d77eec-fdb1-5e11-3259-110c26331ac6&t=d24a834f-31ee-5ffa-ba54-b348410dd76a

`"AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.DesktopVirtualization","Expand-AzWvdMsixImage","Expand-AzWvdMsixImage","0","2020","The cmdlet 'Expand-AzWvdMsixImage' no longer supports the type 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IMsixImageUri' for parameter 'MsixImageUri'.","Change the type for parameter 'MsixImageUri' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IMsixImageUri'."
  "Az.DesktopVirtualization","New-AzWvdMsixPackage","New-AzWvdMsixPackage","0","2110","The element type for parameter 'PackageApplication' has been changed from 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IMsixPackageApplications' to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210712.IMsixPackageApplications'.","Change the element type for parameter 'PackageApplication' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IMsixPackageApplications'."
  "Az.DesktopVirtualization","New-AzWvdMsixPackage","New-AzWvdMsixPackage","0","2110","The element type for parameter 'PackageDependency' has been changed from 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IMsixPackageDependencies' to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210712.IMsixPackageDependencies'.","Change the element type for parameter 'PackageDependency' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IMsixPackageDependencies'."
  "Az.DesktopVirtualization","New-AzWvdScalingPlan","New-AzWvdScalingPlan","0","2110","The element type for parameter 'HostPoolReference' has been changed from 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingHostPoolReference' to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210712.IScalingHostPoolReference'.","Change the element type for parameter 'HostPoolReference' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingHostPoolReference'."
  "Az.DesktopVirtualization","New-AzWvdScalingPlan","New-AzWvdScalingPlan","0","2110","The element type for parameter 'Schedule' has been changed from 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingSchedule' to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210712.IScalingSchedule'.","Change the element type for parameter 'Schedule' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingSchedule'."
  "Az.DesktopVirtualization","Update-AzWvdScalingPlan","Update-AzWvdScalingPlan","0","2110","The element type for parameter 'HostPoolReference' has been changed from 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingHostPoolReference' to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210712.IScalingHostPoolReference'.","Change the element type for parameter 'HostPoolReference' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingHostPoolReference'."
  "Az.DesktopVirtualization","Update-AzWvdScalingPlan","Update-AzWvdScalingPlan","0","2110","The element type for parameter 'Schedule' has been changed from 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingSchedule' to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210712.IScalingSchedule'.","Change the element type for parameter 'Schedule' back to 'Microsoft.Azure.PowerShell.Cmdlets.DesktopVirtualization.Models.Api20210201Preview.IScalingSchedule'."`

**Pull request merged**
