### PR TITLE
Adding Remote Support cmdlets for Stack HCI

### PR DESCRIPTION
**Pull request by swashtek**
## Description

Adding Remote Support cmdlet for install, remove, enable, disable, get access and get session history to Stack HCI script

- Install-AzStackHCIRemoteSupport
- Remove-AzStackHCIRemoteSupport
- Enable-AzStackHCIRemoteSupport
- Disable-AzStackHCIRemoteSupport
- Get-AzStackHCIRemoteSupportAccess
- Get-AzStackHCIRemoteSupportSessionHistory

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Please resolve the signature issues and add help document.

**Comment by swashtek** [comment]
> Please resolve the signature issues and add help document.
I've revised the PR with help document and resolved the signature issues. Please review and let us know if any questions.

**Comment by swashtek** [comment]
> > Please resolve the signature issues and add help document.
> > @wyunchi-ms  I've revised the PR with help document and resolved the signature issues. Please review and let us know if any questions.

@wyunchi-ms There is some issue with static analysis tool, can you please take a look? 
I've addressed other signature issues regarding stack HCI changes. Please let us know if anything is missing. Thanks.

**Comment by wyunchi-ms** [comment]
Only Linux and MacOS fails. Usually it's caused by case sensitive of file path. Please verify content in `Microsoft.AzureStack.Deployment.RemoteSupport.psm1`

**Comment by muthus-msft** [comment]
> Only Linux and MacOS fails. Usually it's caused by case sensitive of file path. Please verify content in `Microsoft.AzureStack.Deployment.RemoteSupport.psm1`

did you mean a different file?

image

**Comment by swashtek** [comment]
> Only Linux and MacOS fails. Usually it's caused by case sensitive of file path. Please verify content in `Microsoft.AzureStack.Deployment.RemoteSupport.psm1`

@wyunchi-ms Please review, We've moved some variables inside the respective functions. It should help to clear the macos and linux checks. Thanks.

**Review by bnichms — DISMISSED** [review]

**Review by trivikso — DISMISSED** [review]

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
