### PR TITLE
Examples for virtual network and virtual network subnet cmdlets

### PR DESCRIPTION
**Pull request by FrankSiegemund**
This contains examples for virtual network and virtual network subnet cmdlets. @deepakrajendranmsft @johnmic, can you please take a look?

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@FrankSiegemund__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (franksie). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@FrankSiegemund Merge conflicts, please update

**Comment by DeepakRajendranMsft** [comment]
@markcowl , you can close this. I will do the merge and send a new PR with all documentation changes

**Pull request closed without merging**
