### PR TITLE
Network february

### PR DESCRIPTION
**Pull request by raraveen**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by number213** [comment]
CI is failing due to missing test recordings for PrivateDns. This PR would fix that: https://github.com/Azure/azure-powershell/pull/8769

**Comment by vladimir-shcherbakov** [comment]
@raraveen Ping on the comments above.

**Comment by MikhailTryakhov** [comment]
@raraven deadline for monthly branch is EOD, please use 19.10.0 SDK version
still CI errors

**Comment by vladimir-shcherbakov** [comment]
@raraveen travis-ci build is failing with the error: https://travis-ci.org/Azure/azure-powershell/jobs/508114170#L1491

**Comment by raraveen** [comment]
Pushed out another commit to fix the CI error.

**Comment by vladimir-shcherbakov** [comment]
@raraveen Here is another travis-ci build error: https://travis-ci.org/Azure/azure-powershell/jobs/508121563#L1491
You may want to build it locally first. Please let me know if you have any questions.

**Comment by raraveen** [comment]
Added missing using statement.

**Comment by MikhailTryakhov** [comment]
feature is not deployed on the server, closing PR. Please retarget to the monthly branch when feature is deployed.
Please add test mentioned and recording by @number213  when feature improvement would be added to the api version

**Pull request closed without merging**
