### PR TITLE
Fix issues on Get-AzADUser

### LINKED ISSUE #10497: Get-AzADUser missing properties
## Description of the new feature
I'm attempting to get our team to use azure cloud shell and when attempting to query userinformation we've found get-azaduser to be a fairly worthless command as it doesn't appear to return any information about the user (like department, usage location, office info, or basically any properties on the user). 

Hopefully I'm just missing something super obvious, but how are admins supposed to use these new modules if they don't return valuable information or the ability to manage users or is this just completely out of scope for cloudshell?  

Thanks!

### LINKED ISSUE #10526: Get-AzADUser (BlockCredential)
The Get-AzADUser command does NOT have an attribute to show the 'BlockCredential' status.

EG:
Get-AzADUser -UserPrincipalName fred@here.com
UserPrincipalName : fred@here.com
ObjectType        : User
DisplayName       : Andrew AZURE
Id                : 8xxxxxx7-axxx-4xxx-8xxx-exxx7xxxac
Type              :

This data is available from MsolUser
EG:
Foreach ($User in (Get-MsolUser -All))
{
If ($User.BlockCredential -eq $true)
    {
    Write-Host $User.UserPrincipalName "is disabled" -ForegroundColor Red
    }
}

This data is also visible in portal.azure.com AAD/User Profile: 
Block Sign in = Yes/No

### LINKED ISSUE #11981: Get-AzADUser -Mail option does not work, is there another way to do it. Same issue by using AAD client directly when filter set to mail
From additional debugging, filter applied is UPN, should be mail.

I tried using AAD client directly by setting filter in it to mail, still same issue.

Also, type is always null, I thought it will be guest
```
Get-AzADUser -Mail "mireks.pm@xxxxxx.com" -Debug
DEBUG: 4:46:20 PM - GetAzureADUserCommand begin processing with ParameterSet 'MailParameterSet'.

HTTP Method:
GET
Absolute Uri:
https://graph.windows.net/dbef1e29-488c-4b64-90ac-287b977faaa3/users?$filter=userPrincipalName eq
'mireks.pm@xxxxxxx.com'&api-version=1.6

Body:
{
  "odata.metadata": "https://graph.windows.net/dbef1e29-488c-4b64-90ac-287b977faaa3/$metadata#directoryObjects",
  "value": []
}
```
When I give my full UPN it works.
```
Get-AzADUser -Mail "mireks.pm_xxxxxx.com#EXT#@xxxxxxx.onmicrosoft.com"
UserPrincipalName : mireks.pm_xxxxxxx.com#EXT#@xxxxx.onmicrosoft.com
ObjectType        : User
DisplayName       : mireks xxxxx
Id                : 40146d24-4b42-498c-b4c1-d6a1c223d21e
Type              :
```

### PR DESCRIPTION
**Pull request by dingmeng-xue**
## Description

Fix #10526,  Add property `AccountEnabled`
Fix #10497, Add property `UsageLocation`, `GivenName`, `Surname`, `MailNickname`, `Mail`
Fix #11981,  `-Mail` parameter doesn't work

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cobdev** [comment]
Requesting that this be re-opened?

There continues to be a lack of properties returned when comparing "Get-AzureADUser" vs. "Get-AzADUser" (using Az v5.0.0):

image

**Comment by cobdev** [comment]
> Requesting an update on this issue?
> 
> There continues to be a lack of properties returned when comparing "Get-AzureADUser" vs. "Get-AzADUser" (using Az v5.0.0):
> 
> image

NUDGE

**Comment by mpriem** [comment]
Any update? Given the growing popularity of PowerShell support in Azure Functions, this is a must have for anyone wanting to administer and query AAD.

**Comment by Dvnoten** [comment]
Update please? Like @mpriem is saying. With the support of PowerShell in Azure Functions this is becoming an urgent topic. The current cmdlet is useless in comparison with the original one.

**Comment by dingmeng-xue** [comment]
Hi All, could you log asks as Github issue? It will be easily ignored if just talking in a closed PR.

**Comment by ehmiiz** [comment]
When using this cmdlet for larger stuff (15,000+ users in the same variable), azure automation sandbox caps out on memory (400 Mb). My ps7 host process is using 3gb ram when storing the users in a variable, since I'm unable to filter out unwanted props.

Would be awesome with a -filter / -properties param

**Pull request merged**
