### PR TITLE
[CosmosDB] Changing the warning message for AnalyticalStorageSchemaType

### PR DESCRIPTION
**Pull request by toswedlu**
Changing the warning message for AnalyticalStorageSchemaType to only display when a value has been explicitly provided.

## Checklist

- [x ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x ] The title of the PR is clear and informative
- x[ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x ] If applicable, the changes made in the PR have proper test coverage
- x[ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @toswedlu , please update changelog as well

**Review by VeryEarly — DISMISSED** [review]

**Comment by VeryEarly** [comment]
hi @toswedlu ,

Please sign license/cla, otherwise PR cannot be merged.

**Review by mkmibrahim — APPROVED** [review]

**Comment by isra-fel** [comment]
Let me rebase the commit tomorrow to avoid issues in change log

**Review by isra-fel — APPROVED** [review]
LGTM. Thanks for the contribution :)

**Comment by toswedlu** [comment]
Hi @isra-fel,  I see that this has been merged, but is not assigned to any milestone.  Does this need to be assigned to a milestone to be released?

Thanks!,
Tom

**Comment by isra-fel** [comment]
Hey Tom @toswedlu judging from the date this was merged, it should have already been in the latest release (2021-12-07). If not please let me know.

**Pull request merged**
