### PR TITLE
Add support for forced tunneling/management subnet and management IP configuration

### PR DESCRIPTION
**Pull request by iatodoro**
## Description

To support "forced tunneling" scenarios we need to be able to assign a separate subnet and public IP address to Azure Firewall that it will use for control plane traffic. This PR introduces changes to support this functionality.

Original PR: https://github.com/Azure/azure-powershell/pull/10644
Reopened PR against master branch instead of December branch

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by iatodoro** [comment]
@isra-fel I need your assistance here - this change requires the Networking SDK v19.18 - however once I bump the version, almost all tests in the Networking folder are failing because they're recorded against an older API version. This is unrelated to any of my changes but will block me from merging and we need to get this change into S164. Any assistance you can provide would be appreciated.

**Comment by isra-fel** [comment]
@number213 Hello Anton, could you help coordinate this? Thanks

**Comment by number213** [comment]
I don't get it too
@iatodoro if you want to make 2/4 PowerShell release, please rebase to `release-2020-02-04`. Otherwise this PR would go into the next release cycle.

**Comment by iatodoro** [comment]
> @number213 Hello Anton, could you help coordinate this? Thanks
> Also @iatodoro why's the PR against master, not network-december?

The merge against network-december was continuously failing due to old recordings in the entire Networking folder. I thought rebasing on master would resolve this. Anyway, I've rebased onto release-2020-02-04

**Comment by iatodoro** [comment]
@isra-fel or @number213 everything is passing now - please approve.

**Pull request merged**
