### PR TITLE
Expose new SKUs for zone-redundant VirtualNetworkGateways

### PR DESCRIPTION
**Pull request by ritwikbasu**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by ritwikbasu** [comment]
This is a retake from https://github.com/Azure/azure-powershell/pull/6277 which was dependent on SDK version update for Network

**Comment by MikhailTryakhov** [comment]
@ritwikbasu  please cover these properties by unit tests

**Comment by ritwikbasu** [comment]
@MikhailTryakhov - Since these are new values added to existing enums, the existing scenario tests already present still hold. There is no change in any business logic or commandlet design.

**Comment by MikhailTryakhov** [comment]
LGTM, @praries880  could you please help to merge?

**Comment by praries880** [comment]
@ritwikbasu kindly take care of the merge conflicts

**Comment by praries880** [comment]
@ritwikbasu  the changes look good to me, just take care of the merge conflicts n we'r good to go

**Comment by ritwikbasu** [comment]
@praries880 - I have resolved the merge conflicts. Please let me know if everything looks good.

**Comment by praries880** [comment]
on demand : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/966/

**Comment by MikhailTryakhov** [comment]
@praries880  can we merge it?

**Pull request merged**
