### PR TITLE
Az.storage module version 2.6.2 - Changing default value from StorageV2 to Storage for Kind Parameter

### PR DESCRIPTION
**Pull request by bganapa**
## Description

Azure Stack does not support StorageV2 yet, The default value of Kind from Storage to StorageV2 is a breaking change for the customers.

Since this is a breaking change, we want to ship a new version of storage module with default value of Storage for the Kind paramteter

The 2.6.0 module code was copied as such and modified only for the default value in this PR

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by abbhar — APPROVED** [review]

**Comment by blueww** [comment]
Could you give some backgroup for this PR?
Why we do these change? will they impact the code in master branch?
Why change default kind  from storagev2 to storage? This is breaking, and the suggested kind from storage team, is storageV2 now.

**Comment by msJinLei** [comment]
Will check why pipe fails later.

**Comment by bganapa** [comment]
@msJinLei  Could you please hwlp to look at why the pipeline fails here?

**Comment by msJinLei** [comment]
> @msJinLei Could you please hwlp to look at why the pipeline fails here?

I am investigating the issue. It is caused by assembly file loading error. I will try to find out the root cause.

**Comment by msJinLei** [comment]
@bganapa Could you add the missing assembly?

```
  /home/vsts/work/1/s/artifacts//StaticAnalysisResults/MissingAssemblies.csv:
  "Directory","Assembly Name","Assembly Version","Referencing Assembly","Severity","ProblemId","Description","Remediation"
  "/home/vsts/work/1/s/artifacts/Debug/Az.Storage","System.Text.Encodings.Web","4.0.4.0","System.Text.Json","0","3000","Missing assembly System.Text.Encodings.Web referenced from System.Text.Json","Ensure that the assembly is included in the Wix file or directory"
  "/home/vsts/work/1/s/artifacts/Debug/Az.Storage","System.Runtime.CompilerServices.Unsafe","4.0.5.0","System.Text.Json","0","3000","Missing assembly System.Runtime.CompilerServices.Unsafe referenced from System.Text.Json","Ensure that the assembly is included in the Wix file or directory"
  
```

**Comment by bganapa** [comment]
Taking a look

**Comment by bganapa** [comment]
@msJinLei 1. We do not ship MSI for the azurestack version, so the missing assemblies issue can be ignored.  2. The breaking changes are misleading as well as we are consuming a whole new version here

**Pull request merged**
