### PR TITLE
Updates for 2018-08-01 features and tests

### PR DESCRIPTION
**Pull request by EvgenyAgafonchikov**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by praries880** [comment]
@EvgenyAgafonchikov  need to fix the failure ion the dns tests : https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/7377/artifact/src/Publish/TestResults/FailingTests/Microsoft.Azure.Commands.Dns.Test.dll.html

Seems the tests need to be re-recorded

**Comment by praries880** [comment]
@EvgenyAgafonchikov 
Keyvault tests are failing on netcore: https://travis-ci.org/Azure/azure-powershell/builds/427240317#L2917

**Comment by praries880** [comment]
Also, since the swagger is out, can you update the PR by deleting the network pkg from the localfeed : tools/LocalFeed/Microsoft.Azure.Management.Network.20.0.0-preview.nupkg

**Comment by markcowl** [comment]
@EvgenyAgafonchikov Also, DNS tests are failing on desktop

**Pull request closed without merging**
