### PR TITLE
AzureRT S53 PR - Data Collection Opt-In/Out

### PR DESCRIPTION
**Pull request by huangpf**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@huangpf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (phuang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ljhljh235** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/180

**Comment by ljhljh235** [comment]
Please run jobs
- http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/build?delay=0sec
- http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/build?delay=0sec

after you've finalized your pull request.

Thanks!

**Comment by huangpf** [comment]
@ljhljh235 OK. Thanks!

**Comment by huangpf** [comment]
@ljhljh235 @markcowl Could you please help review the PR?

I did update the PR with a minor test update, so I guess the current on-demand tests are still effective in terms of validation. Anyhow, I would try to re-run the tests using the links you provide, once everything is finalized. Thanks.

**Comment by huangpf** [comment]
@ljhljh235 On-demand tests passed: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/184/

**Pull request merged**
