### PR TITLE
Add New status to valid values

### PR DESCRIPTION
**Pull request by jameswelle**
## New Status
`Get-AzureRmAutomationDscCompilationJob` can return a `Status` of `New` which is not reflected in this documentation.

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [ ] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md).**
- [ ] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/preview/documentation/help-generation.md).**
- [ ] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/preview/documentation/cleaning-up-commits.md).
- [ ] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.
- [ ] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [ ] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://github.com/Azure/azure-powershell/wiki/PowerShell-Cmdlet-Design-Guidelines#supportsshouldprocess).
- [ ] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [ ] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [ ] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [ ] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by jameswelle** [comment]
I don't see `New` in the valid set [here](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Automation/Commands.Automation/Cmdlet/GetAzureAutomationDscCompilationJob.cs#L50).

However, I am seeing this value in practice:

```ps
ResourceGroupName      : Articulate
AutomationAccountName  : Automation
Id                     : f068f586-ccb9-492c-81d6-ca820ffcba63
CreationTime           : 9/12/2017 1:33:57 PM -06:00
Status                 : New
StatusDetails          : None
StartTime              :
EndTime                :
Exception              :
LastModifiedTime       : 9/12/2017 1:33:57 PM -06:00
LastStatusModifiedTime : 9/12/2017 1:33:57 PM -06:00
JobParameters          : {UserName, ComputerName, ResourceGroupName, Password}
ConfigurationName      : TestAgent
```

```ps
Get-Module -ListAvailable -Name AzureRM.Automation -Refresh


    Directory: C:\Program Files\WindowsPowerShell\Modules


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Script     3.3.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomationDscConfiguration...}
Script     3.1.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomationDscConfiguration...}
Script     3.0.1      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomationDscConfiguration...}


    Directory: C:\Program Files (x86)\Microsoft SDKs\Azure\PowerShell\ResourceManager\AzureResourceManager


ModuleType Version    Name                                ExportedCommands
---------- -------    ----                                ----------------
Manifest   2.4.0      AzureRM.Automation                  {Get-AzureRMAutomationHybridWorkerGroup, Get-AzureRmAutomationJobOutputRecord, Import-AzureRmAutomationDscNodeConfiguration, Export-AzureRmAutomationDscConfiguration...}
```

**Comment by markcowl** [comment]
@vrdmr can you take a look at this?  If this is indeed a valid value we should add it to the ValidateSet as well as the documentation

**Comment by jameswelle** [comment]
Sure @vrdmr @markcowl.

Here, should these statuses be organized alphabetically or chronologically or should we leave them as-is?

**Comment by cormacpayne** [comment]
@vrdmr ping

**Comment by vrdmr** [comment]
@jameswelle - For the time being, could you leave them as-is. I'll consolidate then once I am back in the office. The validate set should also include the "New" status flag. Could you please add that as well and I'll finish the review.

@cormacpayne - I am OOF for couple of weeks, thus I might not get a chance to get the PR in. I have added @safeermohammed, @weijiel, @balukambala to the review as well so that they could sign off on the changes. I have validated that with the "New" flag, the status does return correctly for a newly created job.

**Comment by jameswelle** [comment]
@vrdmr @cormacpayne I added New to the ValidateSet as well

**Comment by cormacpayne** [comment]
@balukambala @safeermohammed @weijiel this looks good from our side, would one of you be able to sign-off from your side? Thanks in advance.

**Pull request merged**
