### PR TITLE
Update changelog for ADF cmdlets

### PR DESCRIPTION
**Pull request by bgold09**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bgold09__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (brgold). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bgold09** [comment]
@markcowl This is the update to the changelog from the code changes in PR #816.

**Comment by ljhljh235** [comment]
On demand job kicked off: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/170/

**Comment by ljhljh235** [comment]
Please target release-0.9.8 branch and resolve conflicts. Thanks!

**Comment by bgold09** [comment]
@ljhljh235 Will do.

**Pull request closed without merging**
