### PR TITLE
Report Image Download Progress 

### PR DESCRIPTION
**Pull request by hvedati**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by msJinLei** [comment]
@hvedati The StackHCIVM is not able to build even without your commit https://github.com/Azure/azure-powershell/pull/24217
StackHCIVM  is out of sync in generation branch. We will look into the issue

**Comment by msJinLei** [comment]
@hvedati Please fix the failed test cases
```
Describing AzStackHCIVMImageNew
    [-] Create Image  432ms
      ArgumentException: Missing Request 'AzStackHCIVMImageNew+[NoContext]+Create Image +$PUT+[https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages/testImage1127-2?api-version=2023-09-01-preview+1'](https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages/testImage1127-2?api-version=2023-09-01-preview+1%27) in recording file (Parameter 'rqKey')
      at New-AzStackHCIVMGalleryImage<Process>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\internal\ProxyCmdletDefinitions.ps1: line 1918
      at New-AzStackHCIVMImage, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\custom\New-AzStackHCIVMImage.ps1: line 383
      at New-AzStackHCIVMImage<End>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\exports\ProxyCmdletDefinitions.ps1: line 2822
      at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 19
    [-] Create MarketplaceImage   56ms
      WriteErrorException: Missing Request 'AzStackHCIVMImageNew+[NoContext]+Create MarketplaceImage  +$PUT+[https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/marketplaceGalleryImages/testMkpImage1127?api-version=2023-09-01-preview+1'](https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/marketplaceGalleryImages/testMkpImage1127?api-version=2023-09-01-preview+1%27) in recording file (Parameter 'rqKey')
      at New-AzStackHCIVMImage, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\custom\New-AzStackHCIVMImage.ps1: line 330
      at New-AzStackHCIVMImage<End>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\exports\ProxyCmdletDefinitions.ps1: line 2822
      at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 23
    [-] List 103ms
      Expected no exception to be thrown, but an exception "Missing Request 'AzStackHCIVMImageNew+[NoContext]+List+$GET+[https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages?api-version=2023-09-01-preview+1'](https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages?api-version=2023-09-01-preview+1%27) in recording file (Parameter 'rqKey')" was thrown from D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\custom\Get-AzStackHCIVmImage.ps1:179 char:13
          +             $galImages = Az.StackHCIVM.internal\Get-AzStackHCIVMGalle …
          +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
      34:         } | Should -Not -Throw
      at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 31
    [-] Get 42ms
      Expected no exception to be thrown, but an exception "An Image with name: testImage1127-2 does not exist in Resource Group: mkclus0824-rg" was thrown from D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1:39 char:13
          +             $config = Get-AzStackHCIVMImage -Name  $env.imageName -Re …
          +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
      41:         } | Should -Not -Throw
      at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 38
```

**Comment by hvedati** [comment]
> @hvedati Please fix the failed test cases
> 
> ```
> Describing AzStackHCIVMImageNew
>     [-] Create Image  432ms
>       ArgumentException: Missing Request 'AzStackHCIVMImageNew+[NoContext]+Create Image +$PUT+[https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages/testImage1127-2?api-version=2023-09-01-preview+1'](https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages/testImage1127-2?api-version=2023-09-01-preview+1%27) in recording file (Parameter 'rqKey')
>       at New-AzStackHCIVMGalleryImage<Process>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\internal\ProxyCmdletDefinitions.ps1: line 1918
>       at New-AzStackHCIVMImage, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\custom\New-AzStackHCIVMImage.ps1: line 383
>       at New-AzStackHCIVMImage<End>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\exports\ProxyCmdletDefinitions.ps1: line 2822
>       at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 19
>     [-] Create MarketplaceImage   56ms
>       WriteErrorException: Missing Request 'AzStackHCIVMImageNew+[NoContext]+Create MarketplaceImage  +$PUT+[https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/marketplaceGalleryImages/testMkpImage1127?api-version=2023-09-01-preview+1'](https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/marketplaceGalleryImages/testMkpImage1127?api-version=2023-09-01-preview+1%27) in recording file (Parameter 'rqKey')
>       at New-AzStackHCIVMImage, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\custom\New-AzStackHCIVMImage.ps1: line 330
>       at New-AzStackHCIVMImage<End>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\exports\ProxyCmdletDefinitions.ps1: line 2822
>       at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 23
>     [-] List 103ms
>       Expected no exception to be thrown, but an exception "Missing Request 'AzStackHCIVMImageNew+[NoContext]+List+$GET+[https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages?api-version=2023-09-01-preview+1'](https://management.azure.com/subscriptions/0709bd7a-8383-4e1d-98c8-f81d1b3443fc/resourceGroups/mkclus0824-rg/providers/Microsoft.AzureStackHCI/galleryImages?api-version=2023-09-01-preview+1%27) in recording file (Parameter 'rqKey')" was thrown from D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\custom\Get-AzStackHCIVmImage.ps1:179 char:13
>           +             $galImages = Az.StackHCIVM.internal\Get-AzStackHCIVMGalle …
>           +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
>       34:         } | Should -Not -Throw
>       at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 31
>     [-] Get 42ms
>       Expected no exception to be thrown, but an exception "An Image with name: testImage1127-2 does not exist in Resource Group: mkclus0824-rg" was thrown from D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1:39 char:13
>           +             $config = Get-AzStackHCIVMImage -Name  $env.imageName -Re …
>           +             ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~.
>       41:         } | Should -Not -Throw
>       at <ScriptBlock>, D:\a\_work\1\s\artifacts\Debug\Az.StackHCIVM\StackHCIVM.Autorest\test\AzStackHCIVMImageNew.Tests.ps1: line 38
> ```

Hi @msJinLei! When I run the tests in playback mode, I see that the image tests passed? 
image

**Comment by msJinLei** [comment]
@hvedati Do you upload the latest recording file?

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
