### PR TITLE
Enable short policy names for mi mw

### PR DESCRIPTION
**Pull request by kukislav**
## Description

Allowing short policy names to be passed as an argument for SQL MI parameter -MaintenanceConfigurationId

Example, instead of

`/subscriptions/a295933f-f7f5-4994-a109-8fa51241a5d6/providers/Microsoft.Maintenance/publicMaintenanceConfigurations/SQL_WestEurope_MI_1`

 you can pass 

`SQL_WestEurope_MI_1`

and the big argumet gets created by cmdlet and passed properly.

For reference see #13926

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@kukislav please join the https://github.com/Azure
And describe your change in the https://github.com/Azure/azure-powershell/blob/2462c901d8714620aaba310a21c8a95ceedbc784/src/Sql/Sql/ChangeLog.md

**Comment by kukislav** [comment]
> @kukislav please join the https://github.com/Azure
> And describe your change in the https://github.com/Azure/azure-powershell/blob/2462c901d8714620aaba310a21c8a95ceedbc784/src/Sql/Sql/ChangeLog.md

Done.

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
