### PR TITLE
Update version of Microsoft.Azure.Management.Sql to 1.37.0-preview in Sql and Sql.Test solution.

### PR DESCRIPTION
**Pull request by SanjaMalesevic**
## Description

Operations Get/Delete/CreateOrUpdate from ManagedInstanceAdministrators have updated signature in new version of .NET client. Parameter administratorName is omitted.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by VeryEarly** [comment]
Hi @SanjaMalesevic ,

please fix the pipeline check

**Comment by SanjaMalesevic** [comment]
Hi @VeryEarly, I dismissed last time that new version of .NET client doesn't contain only my changes. There is also changes related to: "Added support for failover databases readable secondary" (Powershell design review is currently in progress). Because of that, 16 test were failing and I need to record them again. After re-recording, 12/16 tests become successful and I included new json files into the last commit.
And for the other 4 tests, they need to be fixed and there are not related to my changes with active directory admin. I will appreciate if someone can assist with this, I could paste here the names of failed tests and exceptions.
Thanks,
Sanja

**Comment by VeryEarly** [comment]
> Hi @VeryEarly, I dismissed last time that new version of .NET client doesn't contain only my changes. There is also changes related to: "Added support for failover databases readable secondary" (Powershell design review is currently in progress). Because of that, 16 test were failing and I need to record them again. After re-recording, 12/16 tests become successful and I included new json files into the last commit.
> And for the other 4 tests, they need to be fixed and there are not related to my changes with active directory admin. I will appreciate if someone can assist with this, I could paste here the names of failed tests and exceptions.
> Thanks,
> Sanja

Can you provide detail of failed test cases

**Comment by SanjaMalesevic** [comment]
Details:

1. TestBasicDataClassificationOnSqlManagedDatabase

Message: System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Long running operation failed with status 'Failed'. 
Additional Info:'Create Managed Instance failed. Provided virtual network subnet is located in westcentralus, which is a different region than the one you are provisioning Managed Instance in (northeurope). 
To create a VNET-joined Managed Instance, the instance and the virtual network have to be located in the same region.'

2. ManagedDeletedDatabaseShortTermRetentionPolicy

Message: System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
The requested resource of type 'Microsoft.Sql/managedInstances/restorableDroppedDatabases/backupShortTermRetentionPolicies' with name 'Microsoft.SqlServer.Management.Service.Workflows.Interfaces.RestorableDroppedDatabaseResourceIdentifier' was not found.

3. TestGeoRestoreManagedDatabase

Message: System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: 
Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.

4. VulnerabilityAssessmentManagedDatabaseBaselineTest

Message: System.Management.Automation.RuntimeException : Assertion failed because expected 'Principal3 db_ddladmin SQL_USER None' does not match actual 'Principal3;db_ddladmin;SQL_USER;None'
---- System.Management.Automation.RuntimeException : Assertion failed because expected 'Principal3 db_ddladmin SQL_USER None' does not match actual 'Principal3;db_ddladmin;SQL_USER;None'

**Comment by VeryEarly** [comment]
> Details:
> 
> 1. TestBasicDataClassificationOnSqlManagedDatabase
> 
> Message: System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Long running operation failed with status 'Failed'.
> Additional Info:'Create Managed Instance failed. Provided virtual network subnet is located in westcentralus, which is a different region than the one you are provisioning Managed Instance in (northeurope).
> To create a VNET-joined Managed Instance, the instance and the virtual network have to be located in the same region.'
> 
> 1. ManagedDeletedDatabaseShortTermRetentionPolicy
> 
> Message: System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:
> The requested resource of type 'Microsoft.Sql/managedInstances/restorableDroppedDatabases/backupShortTermRetentionPolicies' with name 'Microsoft.SqlServer.Management.Service.Workflows.Interfaces.RestorableDroppedDatabaseResourceIdentifier' was not found.
> 
> 1. TestGeoRestoreManagedDatabase
> 
> Message: System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop:
> Cannot validate argument on parameter 'InputObject'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again.
> 
> 1. VulnerabilityAssessmentManagedDatabaseBaselineTest
> 
> Message: System.Management.Automation.RuntimeException : Assertion failed because expected 'Principal3 db_ddladmin SQL_USER None' does not match actual 'Principal3;db_ddladmin;SQL_USER;None'
> ---- System.Management.Automation.RuntimeException : Assertion failed because expected 'Principal3 db_ddladmin SQL_USER None' does not match actual 'Principal3;db_ddladmin;SQL_USER;None'

Hi @SanjaMalesevic ,

It seems like records for these test cases also need to be updated, can you run record mode in your local one more time to get the up-to-date records for them?

**Comment by SanjaMalesevic** [comment]
I've run again these 4 tests in Record mode, and state is the same. They are failing again with same errors.

**Comment by VeryEarly** [comment]
> I've run again these 4 tests in Record mode, they are failing again with same errors. From my point of view, it looks like that test cases need to be updated.

Hi @SanjaMalesevic ,

At do not have knowledge for this fix at this moment, would you mind send email to our team channel "azdevxps" with link of this pr and detail provided?

**Comment by SanjaMalesevic** [comment]
> azdevxps

Hi, could you please send me mail address for your team? I didn't find team channel...

**Pull request merged**
