### PR TITLE
[SqlLoginMigration] Upgrade console app automatically

### PR DESCRIPTION
**Pull request by Bhavikshah123**
Description
Background:
Currently, SQL Login migration PS backend is uses SqlLoginMigration console app, which is stored in storage account blob. When customers run the PS first time, the SqlLoginMigration console app will be downloaded from the storage account. But if newer console app is released (uploaded to the storage account blob), it cannot be downloaded automatically when customers run login migration PS. If customers want to use the latest console app, they have to delete the downloaded one manually.

Fix:
Upload a version file that keeps the same version number to the latest version of released console app to the storage account blob. Every time, release a new version console app, update the version number in the file to make it same to the released console app. When running the PS, if the console app already exists, check the Login.Console.exe version first and compare it to the version file. If existing one is old, remove it and download the latest one from the storage account blob.

Local testing

image

### CODE REVIEW

**Comment by siyao-Siyang** [comment]
You need to check out the generation branch and work on that branch.

**Comment by siyao-Siyang** [comment]
The changes look good to me. Please follow the wiki I shared.

**Comment by wyunchi-ms** [comment]
Please follow siyao's guide. Changes should be commited into generation branch first.

**Comment by Bhavikshah123** [comment]
Closing this PR and have created the new PR following the wiki.

**Pull request closed without merging**
