### PR TITLE
Set Configuration and Version of service extension optional parameter

### PR DESCRIPTION
**Pull request by hyonholee**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#making-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@hyonholee Two comments:

Please update the markdown files: https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md
Please update the changelog: https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Compute/ChangeLog.md

**Comment by hyonholee** [comment]
@maddieclayton this PR contains only the update from ServiceManagement\Compute.  Servicemanagement does not use markdown help files.  So I only updated changelog from ServiceManagement\Services\Commands.Utilities\ChangeLog.md

**Comment by maddieclayton** [comment]
@hyonholee Why are you making changes to ServiceManagement? It is necessary? We generally do not accept changes to ServiceManagement at this point.

**Comment by maddieclayton** [comment]
@hyonholee Ping on the comment above.

**Comment by markcowl** [comment]
@hyonholee Closing as there has been no response.  Please ask us to re-open if you would still like to make this change.

**Pull request closed without merging**
