### PR TITLE
depricate DnsProxyNotRequiredForNetworkRule switch parameter for New-…

### PR DESCRIPTION
**Pull request by b564518128**
## Description

Depricate `-DnsProxyNotRequiredForNetworkRule` switch parameter for `New-AzFirewall`
Depricate `-ProxyNotRequiredForNetworkRule` switch parameter for `New-AzFirewallPolicyDnsSetting`

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by b564518128** [comment]
align with #13129 

@isra-fel  The backend service change has already been done, it will be released in early November. It will continue accepting the flag but will not have any effect. We are planning to remove this flag completely in the next PS release. Could you please tell me the version of the next release so that I can put it in the parameter deprecation text.

**Comment by isra-fel** [comment]
> We are planning to remove this flag completely in the next PS release

This is not possible because next PS release (11/17) is a regular release which does not allow breaking change.
The next release that allows breaking changes will be next May. If you don't remove these parameters in this milestone you'll need to wait half an year. Please make your choice.

**Comment by wyunchi-ms** [comment]
Hi @b564518128 , as we only release breaking changes in the breaking change releases which is April and October every year. And I think this breakings cannot catch this breaking change release in October. Maybe you need to wait for the next breaking change release which will be in April 2021.

**Comment by b564518128** [comment]
@isra-fel @wyunchi-ms Thanks a lot for the information. We do want to make it to be a breaking change and have parameter completely removed in this release. I will make it straight as soon as I can.

**Review by isra-fel — APPROVED** [review]
LGTM

**Pull request merged**
