### PR TITLE
[EventHub]: Removing cmdlets to be deprecated from EventHubs and Servicebus

### PR DESCRIPTION
**Pull request by damodaravadhani**
## Description

We had decided to deprecate a few cmdlets during the last breaking change release. Hence, we are removing the code for the same. https://learn.microsoft.com/en-gb/powershell/azure/migrate-az-9.0.0-eventhub?view=azps-8.3.0#deprecation-announcements.

The namespace cmdlet is removed here and would be replaced by autorest cmdlets in a soon to come PR. 

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by msJinLei** [comment]
Removed eventhub cmdlets cause the test cases of other modules to fail

**Comment by damodaravadhani** [comment]
@msJinLei, what should be my next action item here ? How do ensure parity with other modules testcases ?

**Comment by msJinLei** [comment]
@damodaravadhani Please skip the failed test cases which are affected by your PR

**Comment by msJinLei** [comment]
Could you provide the migration guide of EventHub for this major release? 

Please fill in the following table 
|cmdlet|breaking change|old usage|new usage| 
|-|-|-|-| 

Thanks

**Comment by damodaravadhani** [comment]
> Could you provide the migration guide of EventHub for this major release?
> 
> Please fill in the following table
> 
> cmdlet	breaking change	old usage	new usage
> Thanks

Hello @msJinLei, I have suppressed breaking changes. Here is a migration guide.

1) New-AzEventHubNamespace would be alias cmdlets with New-AzEventHubNamespaceV2. In other words, from this release New-AzEventHubNamespace would be configured to behave like New-AzEventHubNamespaceV2 and have the same parameters and return type. (I would be raising a PR for this in the generation branch tomorrow).
2) Removed cmdlets that we committed to deprecate last year in https://learn.microsoft.com/en-us/powershell/azure/migrate-az-9.0.0-eventhub?view=azps-8.3.0#deprecation-announcements
3) `-MessageRetentionInDays` would be replaced by `-RetentionTimeInHours` for New-AzEventHub and Set-AzEventHub cmdlets. Please refer https://github.com/Azure/azure-powershell/pull/21585 for the changes.

**Comment by msJinLei** [comment]
@damodaravadhani Please review the latest change

**Pull request merged**
