### PR TITLE
[Azure CDN] Fixed mandatory parameters issue in Get-AzCdnEndpointResourceUsage cmdlet

### PR DESCRIPTION
**Pull request by t-bzhan**
Fixed mandatory parameters issue in Get-AzCdnEndpointResourceUsage cmdlet

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
   - The PR has made the EndpointName  parameter mandatory, it looks like a breaking change, but the command will not work if EndpointName is not specified as described in the issue: https://github.com/Azure/azure-powershell/issues/15690, it is by design to have this parameter as mandatory. The old design is wrong.
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by t-bzhan** [comment]
It should fix this [issue](https://github.com/Azure/azure-powershell/issues/15690).

**Comment by VeryEarly** [comment]
please make breaking changes only at major release.

**Comment by t-bzhan** [comment]
> please make breaking changes only at major release.

@VeryEarly , I agree that the restriction sound useful in most of cases, however in this case, the old command is fundamentally broken. Is it really necessary to let the customer wait for another 2 or 3 months just because we do not want to make breaking change to a broken command, :)

**Comment by VeryEarly** [comment]
> > please make breaking changes only at major release.
> 
> @VeryEarly , I agree that the restriction sound useful in most of cases, however in this case, the old command is fundamentally broken. Is it really necessary to let the customer wait for another 2 or 3 months just because we do not want to make breaking change to a broken command, :)

Hi @t-bzhan , please send email to azdevxps@microsoft.com to request for adding breaking changes.

**Pull request merged**
