### PR TITLE
Change int to long in Operational Insights search

### PR DESCRIPTION
**Pull request by chfunk**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chfunk__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by chfunk** [comment]
Could someone please look at this?  A customer is awaiting the fix to unblock them.  Thanks!

**Comment by hovsepm** [comment]
@chfunk please rebase your PR and squash commits into one. We do not want to have so many 	"Merge remote" commits in the history.

**Pull request closed without merging**
