### PR TITLE
Add support for V12 SQL Database in Start-AzureSqlDatabaseExport

### PR DESCRIPTION
**Pull request by ivanz**
Remove the hardcoded use of pre-v12 context type in StartAzureSqlDatabaseExport:
- Use a new ISqlCredentialsDataServiceContext implemented by pre-v12 and v12 data contexts in the command
- Enable 'SqlAuthenticationCredentials' to be instantiated with a plain-text password for when the consumer doesn't have PSCredentials. Creates SecureString internally.

Fixes https://github.com/Azure/azure-sdk-tools/issues/3086 and also https://github.com/Azure/azure-powershell/issues/136

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ivanz__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ivanz** [comment]
Please have a look at this pull request and let me know if there is any feedback. I will sort out the CLA shortly. Thanks.

**Comment by amarzavery** [comment]
@azuresdkci add to whitelist

**Comment by amarzavery** [comment]
@ivanz we do not accept PR in Master branch. Please rebase it to the dev branch

**Comment by ivanz** [comment]
Ahhh. That's unfortunate to find out at this point in the game, because as it turns out that you guys have fixed the problem in pretty much the same way as me. Anyway - you may consider closing the issues I referenced, because they are resolved in the dev branch.

**Comment by amarzavery** [comment]
@ivanz - We cut a release branch from the dev branch. Once everything looks good in the release branch then as a part of end of release activities we merge from release->master->dev. That is the general process. So things in dev will be in master in few days as we are in the process of releasing the next version of PS.

**Comment by CloudIRE** [comment]
Is the version of PowerShell released that solves this issue yet @amarzavery?

**Pull request closed without merging**
