### PR TITLE
Fixed pipelining issue with Get-AzureRmStorageAccountKey

### PR DESCRIPTION
**Pull request by lfshr**
## Description
Partial fix for issue #3719 
Currently Get-AzureRmStorageAccountKey returns a List<StorageAccountKey> object, which is passed down the pipeline (as a List) which was not handled correctly. The following command will not work:
```
Get-AzureRmStorageAccountKey -ResourceGroupName <ResourceGroupName> -Name <StorageAccountName> | ? KeyName -eq 'Key1'
```
The List object gets passed through the pipeline instead of the StorageAccountKey objects, so this query would return null. The current work around is to create 2 pipelines:
```
(Get-AzureRmStorageAccountKey -ResourceGroupName <ResourceGroupName> -Name <StorageAccountName>) | ? KeyName -eq 'Key1'
```

This PR strips out the List and writes the objects directly to the pipeline.

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [x] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [x] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.
- [x] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [x] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [x] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [x] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [x] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [x] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by markcowl** [comment]
@lfshr why not just set enumerate = true on the WriteObject call?

**Comment by lfshr** [comment]
@markcowl worked a charm! Thanks 😄

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

@lfshr I like this, but we will need to get signoff from the storage team, and we will also need to move this to the preview branch

@blueww can you take a look, I think we want to take this

**Comment by blueww** [comment]
My only concern for this change is the output type is changed for List to Array, will that be a breaking change?
I have verfied, Get Key with $key[0].Value, and $key[1].Value still work, so it the function still work well.
@markcowl If the Ourput Type change is OK, I think we can accept it.

**Comment by lfshr** [comment]
@markcowl thanks very much!  I'll keep an eye out for any other cmdlet returning Lists to the pipeline. 😄 

@blueww In my opinion, this is the way all Cmdlets should work. A single object should be written directly to the output stream as soon as it becomes available, otherwise the pipeline becomes a little pointless. The only time I feel an array/list should go into the pipeline is if there's an array of arrays/lists and the use-case makes sense.
You are right though, this is potentially a breaking change. If a user is using any of the List methods that aren't contained in an array, there scripts won't work. But I feel the affected users will be minimal, and it's a change that is necessary for usability and consistency.

**Comment by markcowl** [comment]
@blueww Thanks for taking a look - the output for the cmdlet is still correct, enumerating collections should be the standard

**Comment by markcowl** [comment]
@lfshr  I have duplicated your fix here, since the dev branch is not open for check-ins.  This will make it in for the next release : https://github.com/Azure/azure-powershell/pull/3767

Meanwhile, closing this one

**Pull request closed without merging**
