### PR TITLE
Sobaner/wildcardlistener

### PR DESCRIPTION
**Pull request by sobaner-zz**
## Description

Adding Support for HostNames in Application Gateway Http Listener Class

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by sobaner** [comment]
Swagger: https://github.com/Azure/azure-rest-api-specs/pull/7453
PowerShell Design PR: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/463

**Comment by isra-fel** [comment]
> "Parameter HostNames of cmdlet Add-AzApplicationGatewayHttpListener does not follow the enforced naming convention of using a singular noun for a parameter name."
Please consider renaming to "HostName" or "HostNameList"

**Comment by sobaner** [comment]
> "Parameter HostNames of cmdlet Add-AzApplicationGatewayHttpListener does not follow the enforced naming convention of using a singular noun for a parameter name."
> 
> Please consider renaming to "HostName" or "HostNameList"

The NRP and swagger for this name has already been in field and there are private preview customers onboarded on the property called HostNames. If I call it HostNames in Swagger and call it HostNameList in PS, doesn't that conflict? I would request you to let me go ahead with this name. Discussed it with program management team as well on the naming convention.

**Comment by isra-fel** [comment]
> > "P> The NRP and swagger for this name has already been in field and there are private preview customers onboarded on the property called HostNames. If I call it HostNames in Swagger and call it HostNameList in PS, doesn't that conflict? I would request you to let me go ahead with this name. Discussed it with program management team as well on the naming convention.

It's not just our team's recommendation, but also PowerShell (the language) team's [strongly encouraged development guideline(https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/strongly-encouraged-development-guidelines?view=powershell-7#use-singular-parameter-names) to use singular parameter names.
I understand your need to make it consistent everywhere, but we need to follow the conventions in each environments as well.

**Comment by isra-fel** [comment]
Hi @sobaner , thanks for the detailed explanation of the scenario, that is helpful.
Now let's just think about powershell cmdlet interface, not the swagger. Here's my proposal:

- Do not use `HostNames`
- Change the type of `string HostName` to `string[] HostName`

Here's why:

1. The API surface would be simple. User doesn't need to think about using which of `HostName` or `HostNames`
1. The implementation is simple too
1. Parameter naming conforms with powershell naming convention

And you needn't worry -- this is not a breaking change in powershell, as array parameters *can* take a single object.
How do you like the idea?

**Comment by isra-fel** [comment]
More details on parameter naming convention: we only accept 2 types of plural names:
- Units, e.g. `-TimeInMinutes`
- The argument can never be single, in which way the cmdlet should check and warn the user if a single object is supplied

As of the counter examples you gave, they were probably checked in due to some historic information.

**Comment by sobaner** [comment]
@number213  - I have corrected the staticAnalyzer errors for my PR, but seems like something else from vpn is failing the PR - https://dev.azure.com/azure-sdk/public/_build/results?buildId=238898&view=logs&j=e1b7b984-9f58-529f-7c5a-f15f8e35cfa6&t=e8689ae8-b216-55f7-b207-4831f84ff98a&l=98

Is there a successful build in network-december branch ?

**Pull request merged**
