### PR TITLE
Added virtual network support for Batch cmdlets

### PR DESCRIPTION
**Pull request by brnleehng**
- Updated Changelog.md with Batch virtual network support
- Updated recordings to use Batch service api version
- Updated documentation for New-AzureBatchPool
- Added parameter to New-AzureBatchPool
- Added unit test for virtual network support
- Added new models from Batch version 5.0 to Batch Object Model generator

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@brnleehng__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@brnleehng There are credential scanner issues, please remove or add exceptions in tools\GlobalFilters.xml

**Comment by brnleehng** [comment]
@markcowl We've added it as an exception in the GlobalFilters.xml. The certificates are not used for authentication. These certificates are used for verifying Batch certificate management powershell cmdlets being called properly.

**Comment by markcowl** [comment]
@brnleehng You will need to retarget this pull reuest at release-2.0.0

**Comment by brnleehng** [comment]
Retargeted. Thanks

**Pull request closed without merging**
