### PR TITLE
[ADO pipeline] check signature for scripts

### LINKED ISSUE #9396: Update Signing process for Az
## Description
Current Pipeline is [here](https://dev.azure.com/azure-sdk/internal/_build?definitionId=217&_a=summary)
- [x] Install Wix on the worker [wix website](https://wixtoolset.org/
 - [x] Add steps to build, sign, and publish installer
- [x] Update the signing process to get up to speed with the latest security guidelines this includes:
  - [x] Authenticode Signing for PSD1 files using existing Sha-2 signing certs
  - [x] Authenticode signing for 3rd-party dll dependencies using the 3rd party signing cert (Newtonsoft.json, automapper, yaml.dotnet) description: https://liquid.microsoft.com/Web/Object/Read/ms.security/Requirements/Microsoft.Security.Cryptography.37010
- [x] Update post-build signing validation to include the new file types
- [x] Validate against last signed build (\\aaptfile01\adxsdk\PowerShell\2019_07_30_PowerShell or https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/466/)
- [ ] Replicate signing pipeline for private repo

Jenkins Job: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/

## Cost : 10

### PR DESCRIPTION
**Pull request by isra-fel**
## Description

This fixes #9396 

1. Scripts named `Az*` are checked for authenticode signature
1. `.psd1` files are checked
    - Because all the `.psd1` were not signed in the Jenkins [job](https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign-esrp/), so the PR would break it 🤔

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
    - Not sure if this is big enough change to put into change log
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by markcowl** [comment]
@isra-fel Looks good, need to run a current sign job with this change to verify before completing

**Comment by isra-fel** [comment]
@markcowl I compared the artifacts of the ADO job and Jenkins job. The only differences are:
1. The `.dll`, `.ps1`... files that we sign
1. The `*.deps.json` files have several [differences](https://user-images.githubusercontent.com/11371776/62432916-b69f0c00-b764-11e9-9cf0-cd648b8b6620.png) on the version of system libs, which I believe was caused by environment configuration and was not important. Please correct me if I'm wrong.

Detailed report: [folder comparison.pdf](https://github.com/Azure/azure-powershell/files/3465597/folder.comparison.pdf)

**Comment by markcowl** [comment]
@isra-fel from the latest couple of runs, it looks like we may need to update the branch to include mapping fro some new cmdlets.

**Comment by markcowl** [comment]
@isra-fel Do we have a readout of the dependencies in each run, we can use the static analysis tools to check the dependencies.

The deps file changes are possibly of concern, depending on what they are, but the dependencies of the dlls will actually tell us.

**Pull request merged**
