### PR TITLE
[NetAppFiles] Anf 447 powershell for 2019 10 01 - Includes replication operations 

### PR DESCRIPTION
**Pull request by audunn**
## Description

Includes replication operations
- Approve
- Suspend
- Get
- Remove
- Resume

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Hi @audunn , let us know when this is ready please.

**Comment by audunn** [comment]
Can you have a look at this please.

**Comment by msJinLei** [comment]
@audunn Please try to resolve the conflict.

**Comment by audunn** [comment]
@msJinLei note I did not close this my self, I am trying to resolve conflicts and they were huge so I updated to sync with master. 
The changes to netApp modules are still pending. Will create another pr for that when tests run successfully.   

For that I am having issues with  `Set-TestEnvironment` , even after running `Import-Module .\Repo-Tasks.psd1`   I get `Set-TestEnvironment: The term 'Set-TestEnvironment' is not recognized as the name of a cmdlet, function, script file, or operable program.`
Any hints or resources to solve that issue?

**Comment by isra-fel** [comment]
@audunn did you see any error or warning when importing `.\Repo-Tasks.psd1`?
You can try with windows powershell (isntead of powershell core) as well

**Comment by audunn** [comment]
> 
> 
> @audunn did you see any error or warning when importing `.\Repo-Tasks.psd1`?
> You can try with windows powershell (isntead of powershell core) as well

I tried both powershell core and windows powershell.  Initiall there was an error importing repo-Tasks 
`❯ Import-Module .\Repo-Tasks.psd1
Import-Module : The required module 'Az.Resources' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Users\audunn\source\rep
os\audunn\azure-powershell\tools\Modules\TestFx-Tasks.psd1'.`
but it worked after the second attempt.

**Comment by isra-fel** [comment]
> > @audunn did you see any error or warning when importing `.\Repo-Tasks.psd1`?
> > You can try with windows powershell (isntead of powershell core) as well
> 
> I tried both powershell core and windows powershell. Initiall there was an error importing repo-Tasks
> `❯ Import-Module .\Repo-Tasks.psd1 Import-Module : The required module 'Az.Resources' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Users\audunn\source\rep os\audunn\azure-powershell\tools\Modules\TestFx-Tasks.psd1'.`
> but it worked after the second attempt but Set-TestEnvironment still does not.

I think the second attempt didn't really succeed, and as the error suggests, you need to install Az.Resources first:
```
install-module az.resources -repository psgallery
```

**Comment by audunn** [comment]
> 
> 
> > > @audunn did you see any error or warning when importing `.\Repo-Tasks.psd1`?
> > > You can try with windows powershell (isntead of powershell core) as well
> > 
> > 
> > I tried both powershell core and windows powershell. Initiall there was an error importing repo-Tasks
> > `❯ Import-Module .\Repo-Tasks.psd1 Import-Module : The required module 'Az.Resources' is not loaded. Load the module or remove the module from 'RequiredModules' in the file 'C:\Users\audunn\source\rep os\audunn\azure-powershell\tools\Modules\TestFx-Tasks.psd1'.`
> > but it worked after the second attempt but Set-TestEnvironment still does not.
> 
> I think the second attempt didn't really succeed, and as the error suggests, you need to install Az.Resources first:
> 
> ```
> install-module az.resources -repository psgallery
> ```

Yes, thank you. Had noticed that and I already did install Az.Resources but probably the environment was messed up in the mean time. So I did it again and it is working for me locally now.  
Since this PR was closed I am now working on https://github.com/Azure/azure-powershell/pull/11616

**Pull request closed without merging**
