### PR TITLE
Application Gateway ARM command-lets

### PR DESCRIPTION
**Pull request by kagamsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@kagamsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (kaga). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
Please pull from upstream and resolve the conflicts.

**Comment by kagamsft** [comment]
@hovsepm: Are you trying to merge my PR in "release-0.9.4"? OR Are you asking me to get ready for next release?

**Comment by hovsepm** [comment]
release 0.9.4 is out. Release branch is now merged to dev. You will have to work for next release in dev branch.

**Comment by ogail** [comment]
@kagamsft PR is too old please resubmit the PR after resolving merge conflicts

**Pull request closed without merging**
