### PR TITLE
Support to get collection get

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by hovsepm** [comment]
@vivsriaus please pull from upstream dev. The failure is fixed in dev branch.

**Comment by hovsepm** [comment]
@vivsriaus also please add link to on-demand job.

**Comment by vivsriaus** [comment]
On demand here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/537/

**Comment by hovsepm** [comment]
last on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/539/

**Comment by vivsriaus** [comment]
@hovsepm Trying to squeeze in one other minor change in my last commit, so the updated on demand job is here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/542/

**Pull request merged**
