### PR TITLE
Az.Batch: bump Microsoft.Azure.Batch SDK version to 16.0.0

### PR DESCRIPTION
**Pull request by wanghoppe**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by wanghoppe** [comment]
Hi team, I know this PR contains breaking change, I'd like to know if we can make it an exception and include it in the next release. 

The breaking changes contain two cmdlets removal, and the underlying SDK methods and Rest API endpoints have been removed, users calling the API endpoint now will receive an error anyway. Can we proceed with releasing the new feature introduced by this PR without waiting for the next breaking change release cycle?

**Comment by wanghoppe** [comment]
Hi @vidai-msft, could you help to take a look at this PR?

**Comment by vidai-msft** [comment]
cc @Nickcandy

**Comment by vidai-msft** [comment]
@wanghoppe if the backend APIs have been removed, then it won't be considered as breaking change from Azure PowerShell perspective. You can remove these affected cmdlets and we can roll out in the next release.

**Comment by Nickcandy** [comment]
@wanghoppe Hi, I would help to review this pr. Could you help resolve the conflicts first in this pr?

**Comment by wanghoppe** [comment]
> @wanghoppe Hi, I would help to review this pr. Could you help resolve the conflicts first in this pr?

Hi @Nickcandy, sorry for missing the conflict, I already resolved them.

**Comment by Nickcandy** [comment]
@wanghoppe  Hi, I want double check with you if these two apis are decrypted in all API version or are decrypted just in the lastest version?

**Comment by wanghoppe** [comment]
> @wanghoppe Hi, I want double check with you if these two apis are decrypted in all API version or are decrypted just in the lastest version?

They are deprecated in all API versions

**Review by Nickcandy — APPROVED** [review]

**Pull request merged**
