### PR TITLE
Expose new SKUs for VMSS Vpn gateways

### PR DESCRIPTION
**Pull request by ritwikbasu**
Expose new SKUs for VMSS Vpn gateways

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@ritwikbasu You will need to rerecord the Network tests, and bump the network version for all dependent modules (see [here](https://github.com/Azure/azure-powershell/pull/5993) for an example and [here](https://github.com/Azure/azure-powershell/tree/preview/src/ResourceManager/Network) for the instructions on how to rerecord all tests).

**Comment by maddieclayton** [comment]
@ritwikbasu Please resolve merge conflicts.

**Comment by ritwikbasu** [comment]
Waiting on NRP104 manifest update to happen before merging this change.

@maddieclayton - Please do not close this PR. I will update this when NRP has completely rolled out. This has the same issue has https://github.com/Azure/azure-powershell/pull/6317

**Comment by maddieclayton** [comment]
@ritwikbasu I will close this PR, as the merge conflicts are building and the Network api has not yet been updated.  It will be easier to get more eyes on this review by opening a new PR when it is ready to go, rather than just updating the current PR.  Let me know if you have issues opening a new PR.

**Pull request closed without merging**
