### PR TITLE
Fix: Use the extension type instead of the name when disabling vmss disk encryption

### LINKED ISSUE #5038: Disable-AzureRmVmssDiskEncryption fails if there is any other extension other than ‘AzureDiskEncryption’ extension on VMSS
### Cmdlet(s)

`Disable-AzureRmVmssDiskEncryption`

### PowerShell Version

Instructions: to get PowerShell version, type `$PSVersionTable` and look for the value associated with `PSVersion`

```
PSVersion            - 5.1.16299.15
```

### OS Version

```
BuildVersion         - 10.0.16299.15  
```

### Description

Disable-AzureRmVmssDiskEncryption fails if there is any other extension other than ‘AzureDiskEncryption’ extension on VMSS (Windows OS)

### Debug Output

Instructions: to get Debug Output, set `$DebugPreference="Continue"` and then execute the cmdlet or script causing the issue
Also debug log file attached here. 
[DisableVMSSDELogs.txt](https://github.com/Azure/azure-powershell/files/1509355/DisableVMSSDELogs.txt)

```
PS D:\>>> Disable-AzureRmVmssDiskEncryption -ResourceGroupName 'VMMSEnableDETestRG' -VMScaleSetName 'nt1vm' -Debug -Verbose *>&1 | foreach-object {$_.ToString()} | Out-File 'DisableDELogs.txt' 
Disable-AzureRmVmssDiskEncryption : Extension, AzureDiskEncryption,  is not installed in the VM Scale Set.
At line:1 char:1
+ Disable-AzureRmVmssDiskEncryption -ResourceGroupName 'VMMSEnableDETes ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
    + CategoryInfo          : InvalidArgument: (:) [Disable-AzureRmVmssDiskEncryption], ArgumentException
    + FullyQualifiedErrorId : InvalidArgument,Microsoft.Azure.Commands.Compute.Extension.AzureDiskEncryption.RemoveAzureVmssDiskEncryptionCommand
```

### Script/Steps for Reproduction
1. Deploy Windows Cluster to Azure
2. Enable VMSS Disk Encryiption using Set-AzureRmVmssDiskEncryptionExtension
3. Wait for completion
4. Verify if disk encryption enables for OS volume
5. Now to try disable disk  encryption using Disable-AzureRmVmssDiskEncryption
it says - Disable-AzureRmVmssDiskEncryption : Extension, AzureDiskEncryption,  is not installed in the VM Scale Set.
It seems it didn't work if there is any other extension other than ‘AzureDiskEncryption’ extension on VMSS.

### PR DESCRIPTION
**Pull request by danwkennedy**
## Description
Fixes #5038 . Since the extension name attribute can be set by the user, look for the extension by its type in the list of VMSS extensions.

## Checklist
- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cormacpayne** [comment]
@danwkennedy Hey Daniel, thanks for the contribution. Before we can do anything with this PR, we'll need you to sign the CLA. Please see the comment above by the @msftclas bot for more information.

**Comment by danwkennedy** [comment]
@cormacpayne  Linked my MS and GH accounts so the CLA should be good to go.

**Comment by cormacpayne** [comment]
@hyonholee @ejarvi would you mind signing-off on the changes in this PR?

**Pull request merged**
