### PR TITLE
Example was missing Update-AzVM cmdlet

### PR DESCRIPTION
**Pull request by michawets**
When running the example, the diagnostics settings were not applied to the VM, only to the variable stored in the Powershell windows at that moment. No real update was done on the VM.
For the diagnostics to be applied, the cmdlet Update-AzVM still needs to be executed

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
looks like the updated vm need to be passed to Update-AzVM, please check my commit and confirm.

**Comment by michawets** [comment]
> looks like the updated vm need to be passed to Update-AzVM, please check my commit and confirm.

Hi @VeryEarly , there are multiple ways to do it 😊.

I double checked my commit, and that will work. I didn't want to change to much on the example, and keep the $VM variable as a single variable

**Comment by VeryEarly** [comment]
> > looks like the updated vm need to be passed to Update-AzVM, please check my commit and confirm.
> 
> Hi @VeryEarly , there are multiple ways to do it 😊.
> 
> I double checked my commit, and that will work. I didn't want to change to much on the example, and keep the $VM variable as a single variable
> 
> So the $updatedVM variable is actually not needed 😊

You're right,I'll revert my commit.

**Pull request merged**
