### PR TITLE
Refine error messages for Move-AzureRmResource

### PR DESCRIPTION
**Pull request by TianoMS**
Fix issue: https://github.com/Azure/azure-powershell/issues/1886

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TianoMS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tiano). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/831/

**Comment by markcowl** [comment]
LGTM once the build passes.

**Comment by TianoMS** [comment]
@markcowl I have a on demand run for this PR here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/826/.

**Pull request merged**
