### PR TITLE
Versioning changes to prepare the preview module.

### PR DESCRIPTION
**Pull request by praries880**
Added changes to release the preview module.

### CODE REVIEW

**Comment by praries880** [comment]
@cormacpayne  can you have a look at the PR?

**Comment by praries880** [comment]
sign job : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1363/

**Comment by praries880** [comment]
new sign job : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1365/

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1367/

**Comment by praries880** [comment]
sign job : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/

**Comment by cormacpayne** [comment]
@praries880 please replace the current dll that's in `LocalFeed` with one that has been signed by the CI servers

**Comment by praries880** [comment]
sign job : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1373/

**Comment by praries880** [comment]
@cormacpayne  can you take a look at the PR?

**Pull request merged**
