### PR TITLE
Update to latest stuff in preview

### PR DESCRIPTION
**Pull request by praries880**

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by praries880** [comment]
@cormacpayne  review this please.. this OR just u[dates the branch with the latest stuff in preview.

@deveshguha FYI

**Comment by praries880** [comment]
on demand : https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/1106/

**Comment by praries880** [comment]
@azuresdkci add to whitelist

**Comment by praries880** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
I'm not sure why, but Travis is targeting a different PR for the build associated with this PR. A successful Travis build for this PR can be found here: 

https://travis-ci.org/Azure/azure-powershell/builds/429804213

**Pull request merged**
