### PR TITLE
Get-AzureRmVirtualNetworkGatewayConnection

### PR DESCRIPTION
**Pull request by anzaman**
Added details about the default behaviour of
Get-AzureRmVirtualNetworkGatewayConnection

### CODE REVIEW

**Comment by vladimir-shcherbakov** [comment]
@anzaman Ping on the conflicts resolving?

**Comment by anzaman** [comment]
I don't have write access to resolve conflicts
@vladimir-shcherbakov

**Comment by cormacpayne** [comment]
@anzaman it looks like your branch is based off of the old `preview` branch, which contains all of the `AzureRM` documentation. I opened a new PR that makes your change to the `Az` documentation, which we currently ship: https://github.com/Azure/azure-powershell/pull/8478

I'm going to close this PR in favor of the one mentioned above. Please let us know if you have any questions or concerns!

**Comment by anzaman** [comment]
@cormacpayne - Thank you

**Pull request closed without merging**
