### PR TITLE
Update Network SDK to use API version 2019-07-01

### PR DESCRIPTION
**Pull request by anton-evseev**
## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by number213** [comment]
`azure-powershell - windows-powershell (Test)` is failing beucase tests can't load Network's nupkg

`System.IO.FileLoadException : Could not load file or assembly 'Microsoft.Azure.Management.Network, Version=20.0.0.0, Culture=neutral, PublicKeyToken=31bf3856ad364e35' or one of its dependencies. Strong name validation failed. (Exception from HRESULT: 0x8013141A)`

This error doesn't occur `azure-powershell - powershell-core` and I don't remember it occuring the last few times we used local nupkg for SDK.

**Comment by number213** [comment]
Re-generating & packaging SDK on another machine didn't help. I'm not sure why there are errors when previously CI passed for unsigned locally-built nupkgs.
@markcowl @erich-wang could you please take a look?

**Comment by erich-wang** [comment]
@number213 , is there any special reason that not using signed package?

**Comment by number213** [comment]
@erich-wang since we release Network SDK a few days before we need to merge Network branch into PowerShell's master, we need to rely on local packages until then. Everyone can build unsigned package and we encourage people in Network to build their own to start PowerShell development even before we release Swagger/SDK. Once Network SDK is published, we remove local package and use the one from NuGet. Unsigned nupkg doesn't get to the customer.
Getting a signed one is difficult and time consuming: ask for a branch, open PR into that branch, get reviewed and merged, start CI job. There was Jenkins job for building signed packages that could target other people's fork but the one on ADO can only target main repo.
If giving ability to built signed package from a fork is difficult/unwanted, maybe setting up a bot like Go/Python/Java SDK's (so it would create a branch with generated code from each PR) is feasible? That way we could open PR, get a branch with our changes and build signed package based on that branch.

**Comment by number213** [comment]
All green, please take a look @erich-wang 
I didn't update ChangeLog.md since this is a temporary change and by the time we merge back into master, we'll use Network SDK from NuGet

**Pull request merged**
