### PR TITLE
Update logic app sdk version

### PR DESCRIPTION
**Pull request by refortie**
## Description

* Updated the SDK for Logic Apps to version 4.0.0
* Added a 2 new integration account artifacts
* Fixed breaking tests and the like
* Updated help files

This has been broken into 3 main commits. The 1st updates the SDK and the code. The 2nd updates the generated SessionRecords and the 3rd updates the help files.

This includes the fix for #7759, #6261, #2539 and #5233

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by maddieclayton** [comment]
@azuresdkci Add to whitelist

**Comment by maddieclayton** [comment]
@refortie Please fill out a design review here: https://github.com/Azure/azure-powershell-cmdlet-review-pr, or link your design review if it is already completed.

**Comment by maddieclayton** [comment]
@refortie Ping

**Comment by refortie** [comment]
Just submitted the review: [Cmdlet Review](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/205)

**Comment by cormacpayne** [comment]
@refortie I re-targeted this PR at the new default branch, `master`, so you'll need to pull from that branch rather than `preview` to resolve the above merge conflicts whenever you are able to get back to this PR.

**Comment by refortie** [comment]
@cormacpayne I should just be regenerating only the help? I think all our cmdlets use the AzureRm prefix won't they not match up?

**Comment by cormacpayne** [comment]
@refortie all cmdlets _should_ be using the prefix `ResourceManager.Common.AzureRMConstants.AzureRMPrefix`, which will swap between `AzureRm` and `Az` depending on the framework it's built against, so you shouldn't need to change anything with your code regarding that. For the merge conflict, you'll just want to make sure that your `Az` cmdlet help has been updated based on your changes since we removed all `AzureRM` cmdlet help.

**Comment by refortie** [comment]
I see you need to use the .NET core project to get the "Az" you might want to add to the documentation that you'll need to build the "Commands.Profile.Netcore" project as well since it doesn't seem to get auto added (or at least it wasn't for me) to the folder like "AzureRM.Profile" was

**Comment by markcowl** [comment]
@refortie Closing until the cmdlet review is settled.  You can open a new PR or re-open this one after that is settled

**Pull request closed without merging**
