### PR TITLE
[App Service]: #12010- upgrade NuGet Microsoft.Azure.Management.Websites to latest v…

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
…ersion (3.0)

updated the NuGet **Microsoft.Azure.Management.Websites** to use latest version(3.0)
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by Kotasudhakarreddy** [comment]
@panchagnula , @ThejaChoudary - FYI

**Comment by VeryEarly** [comment]
Hi @Kotasudhakarreddy ,

There are test cases need to be re-recorded due to API upgrade.

**Comment by Kotasudhakarreddy** [comment]
> Hi @Kotasudhakarreddy ,
> 
> There are test cases need to be re-recorded due to API upgrade.

@VeryEarly - I have done re-recording the tests. This is failing by **StaticAnalysis** , because of breaking changes from previous version to current version. I did faced this issue in my local as well  but resolved by following the instructions from [here](https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes). Not sure on what to do here. Any help is appreciated.

**Comment by VeryEarly** [comment]
> > Hi @Kotasudhakarreddy ,
> > There are test cases need to be re-recorded due to API upgrade.
> 
> @VeryEarly - I have done re-recording the tests. This is failing by **StaticAnalysis** , because of breaking changes from previous version to current version. I did faced this issue in my local as well but resolved by following the instructions from this [link](https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md#breaking-changes). Not sure on what to do here. Any help is appreciated.

- failed test cases:
https://dev.azure.com/azure-sdk/public/_build/results?buildId=404802&view=logs&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0&l=98

- Breaking changes are not allowed in none-breaking change release, one work around could be to refactor "PSSite" class to not inherit from "Site", create exactly same data structure as "Site" and have PSManagementIdentityService class to be initialized with "string".

It won't be considered as breaking change in this way though the output type has modification.

**Comment by VeryEarly** [comment]
@Kotasudhakarreddy ,

Also, removal of `GetAzureWebAppSlotMetrics.cs` is breaking change, please wait for the next major release.

**Comment by panchagnula** [comment]
> @Kotasudhakarreddy ,
> 
> Also, removal of `GetAzureWebAppSlotMetrics.cs` is breaking change, please wait for the next major release.

@VeryEarly , when is the next breaking change release? Given we need the new SDK change to go out to support new feature what are the options we have? Any specific guidance here would be greatly appreciated. Thanks!

**Comment by VeryEarly** [comment]
> > @Kotasudhakarreddy ,
> > Also, removal of `GetAzureWebAppSlotMetrics.cs` is breaking change, please wait for the next major release.
> 
> @VeryEarly , when is the next breaking change release? Given we need the new SDK change to go out to support new feature what are the options we have? Any specific guidance here would be greatly appreciated. Thanks!

Your change was supposed to go with [Build ](https://github.com/Azure/azure-powershell/milestone/102) release, next breaking change release will be this October.

For breaking changes,

- do not remove cmdlet `GetAzureWebAppSlotMetrics.cs` until next breaking change release

- follow the instruction provided above about PSSite

**Comment by panchagnula** [comment]
> @Kotasudhakarreddy ,
> 
> Also, removal of `GetAzureWebAppSlotMetrics.cs` is breaking change, please wait for the next major release.

@VeryEarly when is the next breaking change release scheduled? How can we discover this information ourselves, so that we plan our SDK/breaking release changes accordingly. Thanks!

**Comment by VeryEarly** [comment]
> > @Kotasudhakarreddy ,
> > Also, removal of `GetAzureWebAppSlotMetrics.cs` is breaking change, please wait for the next major release.
> 
> @VeryEarly when is the next breaking change release scheduled? How can we discover this information ourselves, so that we plan our SDK/breaking release changes accordingly. Thanks!

Hi @panchagnula ,

We do not have the exact date yet either, should be this September o later.

**Comment by isra-fel** [comment]
Hi @panchagnula @Kotasudhakarreddy

Next breaking change release will be [S177](https://github.com/Azure/azure-powershell/milestones).
For now we suggest add [breaking change attributes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md) to notify our customers in advance.

**Comment by isra-fel** [comment]
@panchagnula @Kotasudhakarreddy
Closing the PR for lack of activity. Feel free to reopen to continue working on it. Thanks.

**Pull request closed without merging**
