### PR TITLE
Update example 2 with correct command.

### PR DESCRIPTION
**Pull request by DavidMMaxwell**
Updated example 2 to use Get-AzSqlInstanceDatabase instead of Get-AzSqlDatabase.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Thank you for the contribution!
@jaredmoo can you help review the example? Thanks

**Comment by isra-fel** [comment]
Hello @dealaus could you help review this community contribution to docs? Thanks

**Comment by DavidMMaxwell** [comment]
Thanks for the help, everyone. 😊

Thanks,
-David.
____________________________________________________
David M Maxwell
Premier Field Engineer, Microsoft Services: Data & AI
Mobile: 614-719-2581
Office Hours: 8:00 AM – 5:00 PM US Eastern
david.maxwell@microsoft.com<mailto:david.maxwell@microsoft.com>
I will have limited or no availability on:
No travel or PTO planned at this time.

[Microsoft]
﻿If you have any feedback about me or my work, please let me know or contact my manager Shaun Beane at sbeane@microsoft.com<mailto:sbeane@microsoft.com>.

**Pull request merged**
