### PR TITLE
Adding Routing preference for VpnGateway and P2SVpnGateway

### PR DESCRIPTION
**Pull request by Khushboo-Baheti**
## Description
Customer can enable Routing Preference Internet on VpnGateway and P2SVpnGateway. Adding new optional parameter EnableRoutingPreferenceInternetFlag in New-AzVpnGateway and New-AzP2sVpnGateway commandlets.
 
## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/758
    - [X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by Khushboo-Baheti** [comment]
azure-powershell-cmdlet-review-pr - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/758

**Review by wyunchi-ms — APPROVED** [review]

**Comment by wyunchi-ms** [comment]
Could you please update your branch with master branch? @Khushboo-Baheti

**Comment by Khushboo-Baheti** [comment]
> Could you please update your branch with master branch? @Khushboo-Baheti

I have created my branch from Azure:network-august branch and it is up to date. Still do you want me to merge with master.

**Comment by wyunchi-ms** [comment]
Or you can cherry pick the commit: f0d7e8b44568b666dd9b86e54e4f159e2ad71823. @Khushboo-Baheti

**Comment by MikhailTryakhov** [comment]
@isra-fel  Can you please help to solve merge conflict?

**Comment by isra-fel** [comment]
It's not just merge conflict. It's behind network-august for long and needs to sync with it, after #13929 is merged

**Comment by isra-fel** [comment]
Hi @Khushboo-Baheti as @MikhailTryakhov 's PR #13927 already merged `network-august` branch to `master`, `network-august` branch became stale. Any later PR (including this one) merged into `network-august` won't be included in this release.
Please re-submit your PR to `release-2021-01-19` if you wish to catch this release

**Comment by Khushboo-Baheti** [comment]
@isra-fel I have created this new PR on release-2021-01-19. Can you please help me to merge this -https://github.com/Azure/azure-powershell/pull/13940

**Pull request merged**
