### PR TITLE
Dependency fix for sql and compute

### PR DESCRIPTION
**Pull request by praries880**
Fix for issue #5365

Movind the dependencies of SQL and Compute into common.

### CODE REVIEW

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/608/

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/611

**Comment by praries880** [comment]
@jaredmoo you can use the changes in the PR now to record SQL tests. It has the latest preview branch changes in it.

**Comment by MiYanni** [comment]
@praries880 You have merge conflicts that need to be resolved.

**Comment by cormacpayne** [comment]
@praries880 gentle ping 😀

**Comment by cormacpayne** [comment]
Can you please fix the merge conflict? We have moved ChangeLog/psd1 files from `src/ResourceManager/` to `src/ResourceManager/{{service}}/Commands.{{service}}`, so you will need to move your ChangeLog/psd1 updates there.

**Comment by cormacpayne** [comment]
@praries880 closing this PR until you have a chance to get to it 😀

**Pull request closed without merging**
