### PR TITLE
Properly suppress CredScan for RedisEnterpriseCache JSON files

### PR DESCRIPTION
**Pull request by greenms**
## Description

Properly suppress CredScan for RedisEnterpriseCache JSON files

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - Azure/azure-powershell-cmdlet-review-pr#767
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by greenms** [comment]
@dolauli it doesn't appear to be using tools/CredScanSuppressions.json.  What should I do?

**Comment by wyunchi-ms** [comment]
Please resolve the comment problem in Recording.json. Json doesn't support comment. @greenms

**Comment by greenms** [comment]
@wyunchi-ms There are no comments in Recording.json.  The problem is the CredScan is not using my suppression from tools/CredScanSuppressions.json.

**Comment by dolauli** [comment]
@greenms My bad. You need to change this one https://github.com/Azure/azure-powershell/blob/generation/tools/SecurityTools/CredScanSuppressions.json

**Pull request merged**
