### PR TITLE
Fixes 14021 - Updated contribution guide

### LINKED ISSUE #14021: Update readme and contributing guide
## Description

We should refresh the content of the readme and contribution guide.

### PR DESCRIPTION
**Pull request by mikefrobbins**
## Description

Fixes #14021 - Updated contribution guide

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by dcaro** [comment]
Thanks for this change, I suggest that we add some content about the type of contribution can be made so that everyone feel that they can contribute regardless of their level. It can be a typo to fix to providing new examples to adding parameters / cmdlets.
I recommend that we add a page on how to contribute to the reference docs (including examples).

**Review by dcaro — COMMENTED** [review]
Thanks for this change, I suggest that we add some content about the type of contribution can be made so that everyone feel that they can contribute regardless of their level. It can be a typo to fix to providing new examples to adding parameters / cmdlets.
I recommend that we add a page on how to contribute to the reference docs (including examples).
@dingmeng-xue do we still want to point to those articles? Because we are now looking more at generation code, I would like to see how to contribute to modules generated.

**Comment by mikefrobbins** [comment]
@dcaro, Please merge these changes and we'll iterate from there. The existing documentation is completely outdated pointing to issues template that no longer exist and referencing the master branch instead of main.

I'll revisit and submit the types of contributions that can be made. Contributing to the reference docs should be a contribution guide in the azure-docs-powershell repo. We can add a link in this guide pointing to it once it's been created.

**Review by dcaro — APPROVED** [review]
Let's merge and review later

**Pull request merged**
