### PR TITLE
[AzureRM] Update all modules' changelog.md

### PR DESCRIPTION
**Pull request by BethanyZhou**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by dingmeng-xue** [comment]
We need to use aka.ms link

**Comment by dcaro** [comment]
Please use the following links:
https://docs.microsoft.com/powershell/azure/migrate-from-azurerm-to-az -> https://aka.ms/azpsmigrate 
https://docs.microsoft.com/powershell/azure/quickstart-migrate-azurerm-to-az-automatically -> https://aka.ms/azpsmigratequick

**Comment by BethanyZhou** [comment]
Hi @dcaro, I think AzureRM.MachineLearningCompute supposes to map to Az.MachineLearningCompute rather than Az.MachineLearning, could you verify it?

**Review by dcaro — APPROVED** [review]
Thanks, looks good to me, the exceptions are correctly mapped.

**Pull request merged**
