### PR TITLE
Support multi Ipconfiguration on the network interface, rerecord tests with 5.0.1 version of SDK

### PR DESCRIPTION
**Pull request by skomarag**
HI,

Here are the changes:
1. Added a new field called Primary for NetworkinterfaceIpconfiguration
2. Using the primary in related commandlets
3. Wrote tests but disabled them as NRP code is not ready yet
This PR also contains Deepak's changes which are
1. Rerecord all tests as the NRP version is changed to 5.0.1
2. Change the version for management.network.dll everywhere to 5.0.1
3. Edited the name from "Virtualnetwork" to "VirtualNetwork"
4. All tests passed locally and also on the build

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@skomarag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@hovsepm needs a review

**Comment by DeepakRajendranMsft** [comment]
LGTM

**Comment by hovsepm** [comment]
src\ResourceManager\Common\Commands.ResourceManager.Common\packages.config - there is no version 4.6 of network. You should use https://www.nuget.org/packages/Microsoft.Azure.Management.Network/5.0.1-preview

**Comment by hovsepm** [comment]
in AzureRM.Network.psd1 file revert module version back to
```
ModuleVersion = '1.0.11'
```

**Comment by DeepakRajendranMsft** [comment]
@hovsepm , got a successful build. we should be good for the merge.

**Comment by hovsepm** [comment]
@skomarag Microsoft.Azure.Management.Network.4.6.0.nupkg file needs to be removed from tools\ Localfeed folder.

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/984/

**Comment by DeepakRajendranMsft** [comment]
the changes are now part of https://github.com/Azure/azure-powershell/pull/2556. this can be closed

**Pull request closed without merging**
