### PR TITLE
Fix for -PassThru parameter description

### PR DESCRIPTION
**Pull request by navba-MSFT**
Fix for -PassThru parameter description. Fixes Azure/azure-powershell#17390

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @navba-MSFT , please add description as help message  in code as well. 
https://github.com/Azure/azure-powershell/blob/81bb462093da3ed8bf6073e0a6233dd03a15a473/src/ServiceFabric/ServiceFabric/Commands/RemoveAzServiceFabricApplication.cs#L60-L67

**Comment by BethanyZhou** [comment]
Please update other PR as well.

**Comment by navba-MSFT** [comment]
> Please update other PR as well.

@BethanyZhou done. Here is the list of the PR for the updates to the code:
https://github.com/Azure/azure-powershell/pull/17402
https://github.com/Azure/azure-powershell/pull/17401
https://github.com/Azure/azure-powershell/pull/17400

**Review by BethanyZhou — APPROVED** [review]

**Pull request merged**
