### PR TITLE
IoT Hub SDK upgrade and test updates

### PR DESCRIPTION
**Pull request by c-ryan-k**
## Description

Updates IoT Hub Management SDK to new 3.0.0 version (api-version 2020-03-01)

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @c-ryan-k , the test phase fails. You may need to rerecord them.

**Comment by c-ryan-k** [comment]
@wyunchi-ms I'll start debugging on my end and try again. The new test files were all recorded today, so I'm not sure what's going on there.

**Comment by c-ryan-k** [comment]
Ok, it looks like a bunch of the failing tests are from Device Provisioning (separate module which depends on IoTHub for tests), which is still using the older 2.10.0-preview IoTHub version. I'll try and update that package and see if that helps fix the tests.

**Comment by c-ryan-k** [comment]
@wyunchi-ms Ok, think I finally figured it out 😄 

Just so I can update a customer waiting for this fix, what's the schedule for the next release once this is approved and merged?

Or can we ad-hoc release just the Az.IoTHub module?

**Review by wyunchi-ms — APPROVED** [review]

**Comment by c-ryan-k** [comment]
> @wyunchi-ms Ok, think I finally figured it out 😄
> 
> Just so I can update a customer waiting for this fix, what's the schedule for the next release once this is approved and merged?
> 
> Or can we ad-hoc release just the Az.IoTHub module?

Hey @wyunchi-ms - sorry to bother again but could you provide an ETA for release of the Az.IoTHub module to the powershell gallery?

**Pull request merged**
