### PR TITLE
Revert "adding cmdlets for edge storage account and edge storage container"

### PR DESCRIPTION
**Pull request by msJinLei**
Reverts Azure/azure-powershell#10763

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
Just for record
https://github.com/Azure/azure-powershell/pull/10702
https://github.com/Azure/azure-powershell/pull/10675

**Comment by msJinLei** [comment]
Breaking change in #10763 is fixed by https://github.com/Azure/azure-powershell/pull/10807

**Pull request closed without merging**
