### PR TITLE
[Storage] Upgrade Storage SRP SDK to 8.2.0

### PR DESCRIPTION
**Pull request by blueww**
## Description

Just to upgrade SRP SDK to 8.2.0 to support a new endpoint (web) that will return when list account.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@blueww it appears that the version is correct in the [`packages.config`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Storage/Commands.Management.Storage/packages.config#L4) and [`.csproj`](https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Storage/Commands.Management.Storage/Commands.Management.Storage.csproj#L66-L69) files in the `preview` branch. The `AzureRM.Storage.Location` branch may be out of date and need to be updated with the latest from the `preview` branch.

**Comment by blueww** [comment]
I have filed a new PR https://github.com/Azure/azure-powershell/pull/6454 to merge the latest change from preview to storage branch.

But this should not block the PR review and merge of this branch.

**Comment by blueww** [comment]
@maddieclayton ， @cormacpayne 
The feature will be release soon. Could you please update me when can we get this PR merged?
And let me know if any change needed from me.

**Comment by maddieclayton** [comment]
@blueww Apologies for the delay, I've been having a lot of trouble getting the merge to build properly: https://github.com/Azure/azure-powershell/pull/6459.  If you would like to try, please feel free (only the netcore build is failing now).

**Comment by blueww** [comment]
@maddieclayton 

For #6459 , I have added a comment to the PR. 


But for this PR, I think it doesn't depends on  #6459, not sure if we can merge first?

**Comment by vladimir-shcherbakov** [comment]
@maddieclayton  
Could you please take a look?

**Comment by maddieclayton** [comment]
@blueww Sure, we'll merge this PR.  We just cannot release until preview is merged over to the storage branch.

**Comment by maddieclayton** [comment]
Also, @blueww you will need to publish the SDK and remove the LocalFeed files before the PowerShell module can be released.

**Comment by blueww** [comment]
@maddieclayton 
As we discussed with Mark before, for the preview module release (only release preview storage module), we can use signed private SDK package. And this release is preview module release.

Since we target to release the SDK and PowerShell on same day, we can't use the public SDK in this Powershell preview module release.

**Pull request merged**
