### PR TITLE
`New-AzAutomationSchedule` provide ability to define the start time with offsets

### PR DESCRIPTION
**Pull request by jagpreetstamber**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hey @jagpreetstamber please update the `ChangeLog.md` in your module.

**Comment by isra-fel** [comment]
Hey @jagpreetstamber we have just cut of the branch `release-2021-12-07` for the upcoming release. Since the PR is created so close to code complete date, it will not be in the upcoming release, but it will be in the next one.
Or if this must be in, please update the target branch from `main` to `release-2021-12-07` and milestone to `Nov 2021`.

**Comment by jagpreetstamber** [comment]
> Hey @jagpreetstamber please update the `ChangeLog.md` in your module.

We can take it in next release, what is the timeline for next release.

**Comment by jagpreetstamber** [comment]
> Hey @jagpreetstamber we have just cut of the branch `release-2021-12-07` for the upcoming release. Since the PR is created so close to code complete date, it will not be in the upcoming release, but it will be in the next one. Or if this must be in, please update the target branch from `main` to `release-2021-12-07` and milestone to `Nov 2021`.

@isra-fel We can go with next release, what is the timeline for next release?

**Comment by isra-fel** [comment]
> @isra-fel We can go with next release, what is the timeline for next release?

Jan 4th. You may check out all future milestones here: https://github.com/Azure/azure-powershell/milestones

**Review by plutonly — APPROVED** [review]

**Review by isra-fel — APPROVED** [review]
Looks good

**Pull request merged**
