### PR TITLE
Network November release

### PR DESCRIPTION
**Pull request by anton-evseev**
## Description

I can't merge in `network-november-release` to resolve conflicts, so I had to use my own fork. This is `network-november-release` plus three extra commits:
* https://github.com/Azure/azure-powershell/pull/7951/commits/9fdd50a97830fa71af16f83511610794615097a6 - update Network SDK to use published package instead of local feed and code changes to resolve conflicts
* https://github.com/Azure/azure-powershell/pull/7951/commits/dacfce52aaeb1b97d4aaaf88e089502825a281d2 - resolve merge conflicts through Github
* https://github.com/Azure/azure-powershell/pull/7951/commits/99d64d1d5a2c587aced6fd335d809e0f37ce7c7c - update Network SDK version in missed file

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by number213** [comment]
I've tried to also edit code to resolve merge conflicts from https://github.com/Azure/azure-powershell/pull/7950, but even though I still get them, conflicts can be resolved by using code from this PR

**Comment by number213** [comment]
I can't merge in `network-november-release` to resolve conflicts, so I had to use my fork. This is `network-november-release` plus two extra commits:
* https://github.com/Azure/azure-powershell/pull/7951/commits/9fdd50a97830fa71af16f83511610794615097a6 - update Network SDK to use published package instead of local feed and code changes to resolve conflicts
* https://github.com/Azure/azure-powershell/pull/7951/commits/dacfce52aaeb1b97d4aaaf88e089502825a281d2 - resolve merge conflicts through Github

**Comment by cormacpayne** [comment]
@number213 I re-targeted this PR at the new default branch, `master`, so you will need to pull from that branch to resolve the merge conflicts.

_Note_: since the next release is the GA of the `Az` module, we have removed all reference docs to `AzureRM` cmdlets, so you will need to regenerate your help based on the `Az` cmdlets.

CC:  @EvgenyAgafonchikov @MikhailTryakhov

**Comment by number213** [comment]
@cormacpayne done

**Comment by cormacpayne** [comment]
@number213 I've merged [one additional PR](https://github.com/Azure/azure-powershell/pull/7996) into the `network-november-release` branch, would you mind pulling it into your branch?

**Pull request merged**
