### PR TITLE
Fix issue with extension id containing dot

### LINKED ISSUE #72: Calling Set-AzureServiceDiagnosticsExtension with Role parameter fails
I'm trying to set Azure diagnostics on a deployed cloud service using v0.8.11 Azure Powershell cmdlets and the Set-AzureServiceDiagnosticsExtension command:

    Set-AzureServiceDiagnosticsExtension -StorageContext $storageContext -DiagnosticsConfigurationPath $diagnosticsConfiguration.FullName -ServiceName $serviceName -Slot Production -Role "MyService.Web"-Verbose

Doing so I get the following error

    Exception: Microsoft.WindowsAzure.CloudException: BadRequest: The extension ID
    MyService.Web-PaaSDiagnostics-Production-Ext-0 is invalid.
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task
    task)
       at Microsoft.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccess(Task
    task)
       at Microsoft.WindowsAzure.HostedServiceOperationsExtensions.AddExtension(IHo
    stedServiceOperations operations, String serviceName,
    HostedServiceAddExtensionParameters parameters)
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.ExtensionMan
    ager.AddExtension(HostedServiceAddExtensionParameters extensionInput)
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.ExtensionMan
    ager.InstallExtension(ExtensionConfigurationInput context, String slot,
    ExtensionConfiguration extConfig)
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.SetAzureServ
    iceDiagnosticsExtensionCommand.ExecuteCommand()
       at Microsoft.WindowsAzure.Commands.ServiceManagement.Extensions.SetAzureServ
    iceDiagnosticsExtensionCommand.OnProcessRecord()
       at Microsoft.WindowsAzure.Commands.Utilities.Common.CloudBaseCmdlet`1.Proces
    sRecord()
       at System.Management.Automation.Cmdlet.DoProcessRecord()
       at System.Management.Automation.CommandProcessor.ProcessRecord()
        + CategoryInfo          : NotSpecified: (:) [Write-Error], WriteErrorExcep
       tion
        + FullyQualifiedErrorId : Microsoft.PowerShell.Commands.WriteErrorExceptio
       n,UpdateDiagnosticsBuildStep.ps1

It works when I don't use the "-Role" parameter but then I have to call Remove-AzureServiceDiagnosticsExtension for each role prior to calling the Set command which adds 2-3 minutes per role to the script execution time.

The Role parameter matches my role name in the Azure Cloud Service. Am I doing something wrong or is this a bug?

### PR DESCRIPTION
**Pull request by arsnyder16**
fixes #72

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arsnyder16__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        This seems like a small (but important) contribution, so no contribution license agreement is required at this point. Real humans will now evaluate your PR.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@arsnyder16 we are not working on the public repo for the moment

**Comment by markcowl** [comment]
@arsnyder16 Changes for sprint 47 and sprint 48 are going agsint the private repo

**Comment by markcowl** [comment]
@arsnyder16  Apologies, I thought you had access to the private repo.  Will open this PR against the private repo for you and have the team review it - this will ensure the fix goes out in the earliest possible release.

**Comment by rajinders** [comment]
I was wondering when this fix will be tested and released soon. We have two clients that are using SDK 2.5 and both of them have cloud service names with . in them. We use continuous integration so applying diagnostics extension is critical for us.

Thanks

**Comment by huangpf** [comment]
@rajinders Can you try the latest release 0.9.0? @markcowl already patched the code there.

Thanks.

**Comment by rajinders** [comment]
@huangpf  @markcowl     Thank you so much for fixing this issue in 0.9.0
I have tested it and it is working.
I had debugging turned on while running the cmdlets but I found the script ran slow. I had 3 roles types in my project. I tested updating diagonstics extension for each of them. Here is how i tested:
1. remove the old extension
2. updated the cloud service deployment
3. sequentially applied diagnostics extension.

everything worked but it took more than 20 minutes. I was in Central US.
This seems a bit slow.
Is there is a better way to update diagnostics extension?
Should I be using Async(start job) in PowerShell?
Will I run into any type of locking issues if I try to run the diagnostics updates to different roles at the same time?

I have two different applications that will implement this to get ready for testing on Monday so any suggestion you have will be much appreciated.

**Pull request closed without merging**
