### PR TITLE
[#2306] AzureResourceManager.psd1 is included in several PS packages 

### PR DESCRIPTION
**Pull request by hovsepm**
fix for #2306

### CODE REVIEW

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/930/

**Comment by hovsepm** [comment]
sign: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/516/

**Comment by markcowl** [comment]
LGTM once the on-demand build passes

**Pull request merged**
