### PR TITLE
Fix bug causing Docker Password to be removed from appsettings in Set-AzWebApp(Slot)

### PR DESCRIPTION
**Pull request by Willem-J-an**
## Description
Fix for issue: https://github.com/Azure/azure-powershell/issues/13865

Streamlined actions for docker password with the actions for other docker related app settings, so:
1. Check if the parameter is provided
2. Remove the existing app setting
3. Set the new app setting to the parameter value

This should cause the app setting not to be removed when the parameter is not provided.

Unfortunately I have been unable to build the project locally:
 Assets file '\azure-powershell\src\Websites\Websites.Test\obj\project.asses\Websites.Test\obj\project.assets.json' doesn't have a target for 'netcoreapp2.2'. Ensure that restore has run and that you have included 'netcoreapp2.2' in the TargetFrameworks for your project. [C:\hell\src\Websites\Websites.Test\azure-powershell\src\Websites\Websites.Test\Websites.Test.csproj] [\azure-powershell\build.proj].
I installed dotnet 5 and dotnet 2.2, but no luck. I have therefore not been able to run tests for these changes.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by Willem-J-an** [comment]
First build failed due to SecureString being compared to a string, pushed a fix for this
```
ContainerRegistryPassword.ConvertToString() != string.Empty

**Comment by isra-fel** [comment]
Thanks @Willem-J-an  , this code is related to pull request #12107 by @vinisoto .
Hi Vini, could you review this one? Thank you!

**Review by vinisoto — APPROVED** [review]
Looks good to me. Thank you for fixing this.

Adding @panchagnula as FYI

**Comment by Willem-J-an** [comment]
Rebased to resolve conflict on the changelog

**Review by vinisoto — DISMISSED** [review]

**Review by isra-fel — APPROVED** [review]
LGTM. Thanks!

**Pull request merged**
