### PR TITLE
[Do not Squash] Merge master change to storage preview branch

### PR DESCRIPTION
**Pull request by blueww**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — CHANGES_REQUESTED** [review]
Please ignore storage api version in synapse scenario test

**Comment by blueww** [comment]
@msJinLei 
Please share how to : ignore storage api version in synapse scenario test ？
Which code should we change to get it?

**Comment by msJinLei** [comment]
> @msJinLei
> Please share how to : ignore storage api version in synapse scenario test ？
> Which code should we change to get it?

Please try the code snippet

```
--- a/src/Synapse/Synapse.Test/ScenarioTests/SynapseTestBase.cs
+++ b/src/Synapse/Synapse.Test/ScenarioTests/SynapseTestBase.cs
@@ -90,7 +90,8 @@ namespace Microsoft.Azure.Commands.Synapse.Test.ScenarioTests
             {
                 {"Microsoft.Resources", null},
                 {"Microsoft.Features", null},
-                {"Microsoft.Authorization", null}
+                {"Microsoft.Authorization", null},
+                {"Microsoft.Storage", null }
             };
             var providersToIgnore = new Dictionary<string, string>
             {
```

**Comment by blueww** [comment]
@msJinLei 
Thanks for the guild!
I have updated the PR accordingly, and local test work fine.
Let's wait for the CI result.

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
