### PR TITLE
Delete Get-AzureRmLocation

### PR DESCRIPTION
**Pull request by chidmdxx**
Deletes the Get-AzureRmLocation and modifies all the uses of the cmdlet to Get-AzureRmResourceProvider

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@chidmdxx resolve conflicts

**Comment by chidmdxx** [comment]
@ogail done

**Comment by markcowl** [comment]
on demand run here:http://azuresdkci.cloudapp.net/job/powershell-on-demand/216/

**Comment by stankovski** [comment]
@chidmdxx please update from upstream. This should resolve the failed test in the on-demand job

**Comment by chidmdxx** [comment]
@Stankovski just updated from upstream

**Comment by stankovski** [comment]
On demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/219/

**Pull request merged**
