### PR TITLE
[Datafactory] Updating ADF SDK to GA version and updating the cmdlets to support new functionality

### PR DESCRIPTION
**Pull request by hvermis**
## Description

This PR contains the Powershell update for ADF GA. It has our new SDK, 1 new cmdlet to set the repo on factories, and 2 cmdlet updates for set factory and set integration runtime. 

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by hvermis** [comment]
We have our new SDK in LocalFeed for now. I will generate the public nuget next week and update the PR.
@zhangyd2015 is updating the Integration Runtime tests.
The design review links:
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/106
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/105
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/73

**Comment by zhangyd2015** [comment]
The integration runtime scenario tests have been re-recorded.

**Comment by maddieclayton** [comment]
@hvermis Can you please squash the commits down to a more reasonable number?

**Comment by hvermis** [comment]
Starting new PR without repo configuration support.:
https://github.com/Azure/azure-powershell/pull/6688

**Pull request closed without merging**
