### PR TITLE
Update New-AzApplicationInsightsWebTest.md

### PR DESCRIPTION
**Pull request by darrengiles**
added example of creating a test in a disabled state through powershell

## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by vidai-msft** [comment]
@darrengiles This is an autorest module. The changes are supposed to happen in the `generation` branch instead of main. You need to update the files under the `Examples` folder on that branch. Thanks!

**Comment by vidai-msft** [comment]
@darrengiles Please kindly note the cut off date of development for this sprint is by EOD next Monday. Let me know if you have any questions regarding this PR.

**Comment by darrengiles** [comment]
@vidai-msft Hello, I don't quite understand what needs to be done for this PR. You mentioned the changes need to be made in another branch, correct? I'm don't think I know how to access this separate branch. Could you share more instructions please?

**Comment by vidai-msft** [comment]
I have updated with PR [#24508]

**Comment by vidai-msft** [comment]
Merged into main branch with #24510. Closing this PR.

**Pull request closed without merging**
