### PR TITLE
Adding cmdlets for Azure Template Specs (Preview) with deployment support

### PR DESCRIPTION
**Pull request by stuartko**
## Description

Adds new cmdlets for managing Template Specs:
  * `Get-AzTemplateSpec`
  * `New-AzTemplateSpec`
  * `Set-AzTemplateSpec`
  * `Export-AzTemplateSpec`
  * `Remove-AzTemplateSpec`

Also adds support for deploying Template Specs via the existing deployment cmdlets. Cmdlets underwent extensive design reviews and discussions, and have been used by customers for the past ~2 months under a private preview release.

The Template Specs service remains in private preview but will enter Public Preview in October.

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - PR is "Adding Cmdlets for Template Specs (Private Preview) # 635"
    - [X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by VeryEarly — CHANGES_REQUESTED** [review]
please add supportshould process to export cmdlet

**Comment by VeryEarly** [comment]
is there API version changes involved in this SDK upgrade? If so, please re-record test cases

**Comment by stuartko** [comment]
> please add supportshould process to export cmdlet

shouldprocess has now been added to all applicable cmdlets.

> is there API version changes involved in this SDK upgrade? If so, please re-record test cases

Not outside of the newly introduced cmdlets/template specs client. We should be good here.


FYI: I see that some tests are failing, but they look to be completely unrelated to these changes. I presume these are failing across the latest master?

**Comment by stuartko** [comment]
@VeryEarly : Are there any further actions needed before this is merged?

**Comment by VeryEarly** [comment]
> @VeryEarly : Are there any further actions needed before this is merged?

those failed test cases have referenced get-azresource which has API upgrade.

This unnecessary reference was caused by bad test implementation, need help from peering team do the fix.

**Comment by stuartko** [comment]
> This unnecessary reference was caused by bad test implementation, need help from peering team do the fix.

Will this block the merge until it is fixed? Who is responsible for following up? Do we need to do anything further from our side?

**Comment by VeryEarly** [comment]
> > This unnecessary reference was caused by bad test implementation, need help from peering team do the fix.
> 
> Will this block the merge until it is fixed? Who is responsible for following up? Do we need to do anything further from our side?

We have some work around if developer from peering team was not managed to fix this issue. Let's wait for their response first.
Meanwhile please resolve merge conflicts.

**Comment by VeryEarly** [comment]
Hi @stuartko ,

Please take latest changes from master branch, thanks.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
