### PR TITLE
New, Set should return resource object

### PR DESCRIPTION
**Pull request by vivsriaus**
New, Set should return resource object

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivsriaus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (visriniv). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
Please update reduce the test execution time to be under 5 seconds. Right now its taking around 2 mins

**Comment by vivsriaus** [comment]
@ogail I'll send the update to reduce the test execution time as a separate PR. I'm still working on it and don't want this PR to be blocked from merging because of it. Thanks

**Comment by markcowl** [comment]
@vivsriaus Please fix the test run time and add comments to changelog.txt.

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Pull request merged**
