### PR TITLE
[Network] Add Cmdlets for BYOIP Feature

### PR DESCRIPTION
**Pull request by dexiang-ms**
## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by dexiang-ms** [comment]
This PR is simply an a re-do of PR: https://github.com/Azure/azure-powershell/pull/12666

@isra-fel recommended that I change the base branch and re-submit the PR

**Comment by msJinLei** [comment]
> This PR is simply an a re-do of PR: #12666
> 
> @isra-fel recommended that I change the base branch and re-submit the PR

Please fix the broken CI. You module has build error now.

**Comment by dexiang-ms** [comment]
> > This PR is simply an a re-do of PR: #12666
> > @isra-fel recommended that I change the base branch and re-submit the PR
> 
> Please fix the broken CI. You module has build error now.

Yup, was just waiting for the updated sdk to get released

**Comment by dexiang-ms** [comment]
Hi Powershell team, in the build errors for Test, I see a lot of references to "Microsoft.Azure.Management.Network, Version=20.0.3.0" but this nuget package doesn't exist. I've updated the Network csproj files to the correct version (20.1.0) and it builds just fine locally. Do you guys know where this "20.0.3.0" version is coming from?

**Comment by msJinLei** [comment]
> Hi Powershell team, in the build errors for Test, I see a lot of references to "Microsoft.Azure.Management.Network, Version=20.0.3.0" but this nuget package doesn't exist. I've updated the Network csproj files to the correct version (20.1.0) and it builds just fine locally. Do you guys know where this "20.0.3.0" version is coming from? Seems like all the tests that are failing are from the DNS code section, not from Network.

It seems build error is fixed.
Please fix broken failed test cases then

**Pull request merged**
