### PR TITLE
Extend the parameter set in Set-AzDiagnosticSetting for separation of Logs and Metrics enablement

### PR DESCRIPTION
**Pull request by ShachafGoldstein**
## Description
Implementation of #12482

Added 2 new parameters to allow the separation of settings between logs and categories.
## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by wyunchi-ms** [comment]
Hi @ShachafGoldstein 
1. As the [powershell guideline](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/design-guidelines/parameter-best-practices.md#singularity) suggests to use singularity instead of plural. Please rename `EnableLogs` to `EnableLog`
1. Supress the exception of `EnableMetrics`. https://dev.azure.com/azure-sdk/public/_build/results?buildId=473126&view=logs&j=e1b7b984-9f58-529f-7c5a-f15f8e35cfa6&t=e8689ae8-b216-55f7-b207-4831f84ff98a&l=52
1. Please rerecord the failed test cases.

**Comment by ShachafGoldstein** [comment]
Failed to actually update the MD help file - is it done by the CI/Build? or should I figure it out?

**Comment by wyunchi-ms** [comment]
You need to update the document by yourself. [Here](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md) is a guideline for updating help files.

**Comment by ShachafGoldstein** [comment]
> You need to update the document by yourself. [Here](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md) is a guideline for updating help files.

Tried to but keep getting - `Import-Module: Could not load file or assembly 'Microsoft.Azure.Management.Monitor, Culture=neutral, PublicKeyToken=null'. The system cannot find the file specified.`

**Comment by ShachafGoldstein** [comment]
Please let me know if anything else is missing.

**Pull request merged**
