### PR TITLE
Update directory for profile and context setting files

### PR DESCRIPTION
**Pull request by cormacpayne**
## Description

Fix for https://github.com/Azure/azure-powershell/issues/6000

Uses signed common packages from PR https://github.com/Azure/azure-powershell-common/pull/13 (will remove these packages once build has been validated)

Also includes change to clear NuGet cache at the beginning of the `Clean` target to ensure that old packages are removed and not pulled in.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
Travis build is failing since the `.nupkg` files contain changes that introduce `Enable-AzureRmAlias` in the common code

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/ps-sign/1242/
.NET Core sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/psnetsign/183/

**Comment by markcowl** [comment]
@cormacpayne Need to discuss how to coordinate the common code changes

**Comment by cormacpayne** [comment]
Closing as this change will be included in one of @markcowl's PRs

**Pull request closed without merging**
