### PR TITLE
[Release 1.3.0] Co-existence API 

### PR DESCRIPTION
**Pull request by dihan0604**

### CODE REVIEW

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/640/

**Comment by dihan0604** [comment]
Comment addressed

**Comment by dihan0604** [comment]
waiting for on demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/642/

**Pull request merged**
