### PR TITLE
Added UninstallChefClient option  in Set-AzureVMChefExtension for ASM

### PR DESCRIPTION
**Pull request by Vasu1105**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@Vasu1105__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@Vasu1105 Please sign the CLA so we can accept your code changes.

**Comment by azurecla** [comment]
__@Vasu1105__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by Vasu1105** [comment]
@hovsepm We signed the CLA. Please review this PR .

**Comment by hovsepm** [comment]
@Vasu1105 I've asked the owner team to review your contribution.

**Comment by adamedx** [comment]
@hovespm, any updates? Looks like this passes all the tests.

**Comment by andrewelizondo** [comment]
LGTM :+1:

**Pull request merged**
