### PR TITLE
Adding ExpressRouteGatewayBypass parameter to New-AzExpressRouteConnection and Set-AzExpressRouteConnection cmdlet

### PR DESCRIPTION
**Pull request by sachethegde**
## Description

1. Design review PR https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/747
2. FastPath to vWan Firewall Hub - Adding `ExpressRouteGatewayBypass` flag parameter to `New-AzExpressRouteConnection` and `Set-AzExpressRouteConnection` cmdlet

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/Network/Network/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
your feature doesn't look rely on API 2020-07, please retarget your PR to master branch.
The network-july branch is currently for features related to API 2020-07 only.

Thanks

**Comment by sachethegde** [comment]
@VeryEarly I am planning to make this feature part of 2020-07. Corresponding Swagger and PS design doc are here. 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/747
https://github.com/Azure/azure-rest-api-specs/pull/10963
Please let me know if I am missing something.

**Comment by VeryEarly** [comment]
close as backend implementation was not complete.

**Pull request closed without merging**
