### PR TITLE
[DO NOT SQUASH] [Az.RecoveryServices.Backup] syncing Az.RecoveryServices-preview branch with master

### PR DESCRIPTION
**Pull request by hiaga**
## Description

syncing Az.RecoveryServices-preview branch with master

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — CHANGES_REQUESTED** [review]
You still have a lot of conflicts.
I create a sample commit https://github.com/Azure/azure-powershell/pull/15141
Please firstly ensure that local recovery services branch and master are both update-to-date
```git merge master```
Resolve conflicts (mostly are from recovery services folder, for Az.psd1, please keep the master's version.
```git merge --continue```

**Comment by msJinLei** [comment]
> You still have a lot of conflicts.
> I create a sample commit #15141
> Please firstly ensure that local recovery services branch and master are both update-to-date
> 
> ```
> git merge master
> ```
> 
> Resolve conflicts (mostly are from recovery services folder, for Az.psd1, please keep the master's version).
> 
> ```
> git merge --continue
> ```

InkedCapture_LI (2)_Moment_Moment

I compare you develop branch with master and find the better way to sync with the master to cherry-pick

The target commit you need do cherry-pick is the one in red cycle. You may also be required to apply the commit in blue cycle to resolve some errors.
Here is the example of what your PR looks like

**Comment by hiaga** [comment]
> > You still have a lot of conflicts.
> > I create a sample commit #15141
> > Please firstly ensure that local recovery services branch and master are both update-to-date
> > ```
> > git merge master
> > ```
> > 
> > 
> >     
> >       
> >     
> > 
> >       
> >     
> > 
> >     
> >   
> > Resolve conflicts (mostly are from recovery services folder, for Az.psd1, please keep the master's version).
> > ```
> > git merge --continue
> > ```
> 
> InkedCapture_LI (2)_Moment_Moment
> 
> I compare you develop branch with master and find the better way to sync with the master to cherry-pick
> 
> The target commit you need do cherry-pick is the one in red cycle. You may also be required to apply the commit in blue cycle to resolve some errors.
> Here is the example of what your PR looks like

@msJinLei: I'm confused. I already have taken my preview and did a git merge and resolved conflicts. won't this be enough to merge this commit ?

**Comment by hiaga** [comment]
@msJinLei could you now see if the commits look fine ? I've rebased to master, cherry-picked Archive and resolved merge conflicts

**Comment by msJinLei** [comment]
> 
> @msJinLei: I'm confused. I already have taken my preview branch and did a git merge and resolved conflicts. won't this be enough to merge this PR?

To answer you question, I check the commit logs yesterday and find some commits that we don't want them to be merged to master. If you use cherry-pick/rebase, we can squash these commits when your branch merge back to master.

**Review by msJinLei — CHANGES_REQUESTED** [review]
Please re-record failed test cases

```
2021-06-01T03:21:18.3650248Z   [xUnit.net 00:00:11.36]     Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests.TestAzureVMWaitJob [FAIL]
2021-06-01T03:21:19.2027474Z     X Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests.TestAzureVMWaitJob [9s 5ms]
2021-06-01T03:21:19.2036708Z EXEC : error Message:  [D:\a\1\s\build.proj]
2021-06-01T03:21:19.2045722Z      System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find a matching HTTP request for URL 'GET /subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/PSTestRG080f34a5/providers/Microsoft.RecoveryServices/vaults/PSTestRSV080f34a5/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/protectedItems/VM%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/recoveryPoints?api-version=2021-03-01'. Calling method Item().
2021-06-01T03:21:19.2056270Z     Stack Trace:
2021-06-01T03:21:19.2065181Z        at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2021-06-01T03:21:19.2072024Z      at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2021-06-01T03:21:19.2081397Z      at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2021-06-01T03:21:19.2213298Z      at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2021-06-01T03:21:19.2295462Z      at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2021-06-01T03:21:19.2316069Z      at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2021-06-01T03:21:19.2327417Z      at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2021-06-01T03:21:19.2346971Z      at System.Management.Automation.PowerShell.Invoke()
2021-06-01T03:21:19.2348344Z      at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in D:\a\1\s\tools\ScenarioTest.ResourceManager\EnvironmentSetupHelper.cs:line 573
2021-06-01T03:21:19.2356718Z      at Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.TestController.RunPsTestWorkflow(PsBackupProviderTypes providerType, Func`1 scriptBuilder, Action cleanup, String callingClassType, String mockName) in D:\a\1\s\src\RecoveryServices\RecoveryServices.Backup.Test\ScenarioTests\TestsBase.cs:line 167
2021-06-01T03:21:19.2361598Z      at Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.TestController.RunPsTest(XunitTracingInterceptor logger, PsBackupProviderTypes providerType, String[] scripts) in D:\a\1\s\src\RecoveryServices\RecoveryServices.Backup.Test\ScenarioTests\TestsBase.cs:line 100
2021-06-01T03:21:19.2363782Z      at Microsoft.Azure.Commands.RecoveryServices.Backup.Test.ScenarioTests.JobTests.TestAzureVMWaitJob() in D:\a\1\s\src\RecoveryServices\RecoveryServices.Backup.Test\ScenarioTests\IaasVm\JobTests.cs:line 57
2021-06-01T03:21:19.2460059Z     Standard Output Messages:
2021-06-01T03:21:19.2461134Z    Test-AzureVMWaitJob
2021-06-01T03:21:19.2463010Z    Caught Exception: System.Management.Automation.ActionPreferenceStopException: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find a matching HTTP request for URL 'GET /subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/PSTestRG080f34a5/providers/Microsoft.RecoveryServices/vaults/PSTestRSV080f34a5/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/protectedItems/VM%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/recoveryPoints?api-version=2021-03-01'. Calling method Item().
2021-06-01T03:21:19.2465946Z       at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
2021-06-01T03:21:19.2466907Z       at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
2021-06-01T03:21:19.2468264Z       at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
2021-06-01T03:21:19.2469364Z       at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2021-06-01T03:21:19.2470519Z       at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
2021-06-01T03:21:19.2471630Z       at System.Management.Automation.PowerShell.CoreInvoke[TOutput](IEnumerable input, PSDataCollection`1 output, PSInvocationSettings settings)
2021-06-01T03:21:19.2472636Z       at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
2021-06-01T03:21:19.2473795Z       at System.Management.Automation.PowerShell.Invoke()
2021-06-01T03:21:19.2474904Z       at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in D:\a\1\s\tools\ScenarioTest.ResourceManager\EnvironmentSetupHelper.cs:line 573
2021-06-01T03:21:19.2476896Z    Message: The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Unable to find a matching HTTP request for URL 'GET /subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/PSTestRG080f34a5/providers/Microsoft.RecoveryServices/vaults/PSTestRSV080f34a5/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/protectedItems/VM%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/recoveryPoints?api-version=2021-03-01'. Calling method Item().
2021-06-01T03:21:19.2479417Z EXEC : PowerShell error Record: Unable to find a matching HTTP request for URL 'GET /subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/PSTestRG080f34a5/providers/Microsoft.RecoveryServices/vaults/PSTestRSV080f34a5/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/protectedItems/VM%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/recoveryPoints?api-version=2021-03-01'. Calling method Item(). [D:\a\1\s\build.proj]
2021-06-01T03:21:19.2482084Z   Exception:System.Collections.Generic.KeyNotFoundException: Unable to find a matching HTTP request for URL 'GET /subscriptions/da364f0f-307b-41c9-9d47-b7413ec45535/resourceGroups/PSTestRG080f34a5/providers/Microsoft.RecoveryServices/vaults/PSTestRSV080f34a5/backupFabrics/Azure/protectionContainers/IaasVMContainer%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/protectedItems/VM%3Biaasvmcontainerv2%3Bpstestrg080f34a5%3Bpstestvm080f30/recoveryPoints?api-version=2021-03-01'. Calling method Item().
2021-06-01T03:21:19.2483687Z       at Microsoft.Azure.Test.HttpRecorder.Records.get_Item(String key)
2021-06-01T03:21:19.2484674Z       at Microsoft.Azure.Test.HttpRecorder.HttpMockServer.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-01T03:21:19.2485701Z       at System.Net.Http.HttpMessageInvoker.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-01T03:21:19.2486864Z       at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, HttpCompletionOption completionOption, CancellationToken cancellationToken)
2021-06-01T03:21:19.2487984Z       at System.Net.Http.HttpClient.SendAsync(HttpRequestMessage request, CancellationToken cancellationToken)
2021-06-01T03:21:19.2489415Z       at Microsoft.Azure.Management.RecoveryServices.Backup.RecoveryPointsOperations.ListWithHttpMessagesAsync(String vaultName, String resourceGroupName, String fabricName, String containerName, String protectedItemName, ODataQuery`1 odataQuery, Dictionary`2 customHeaders, CancellationToken cancellationToken)
2021-06-01T03:21:19.2491235Z   Details:
2021-06-01T03:21:19.2492364Z   Script Stack Trace: at Delete-Vault, D:\a\1\s\src\RecoveryServices\RecoveryServices.Backup.Test\bin\Debug\netcoreapp2.1\ScenarioTests\IaasVm\Common.ps1: line 227
2021-06-01T03:21:19.2493544Z    at Cleanup-ResourceGroup, D:\a\1\s\src\RecoveryServices\RecoveryServices.Backup.Test\bin\Debug\netcoreapp2.1\ScenarioTests\IaasVm\Common.ps1: line 206
2021-06-01T03:21:19.2494767Z    at Test-AzureVMWaitJob, D:\a\1\s\src\RecoveryServices\RecoveryServices.Backup.Test\bin\Debug\netcoreapp2.1\ScenarioTests\IaasVm\JobTests.ps1: line 192
2021-06-01T03:21:19.2495743Z    at <ScriptBlock>, <No file>: line 1
2021-06-01T03:21:19.2496364Z   : Target: 
```

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
