### PR TITLE
Powershell module for Test Base

### PR DESCRIPTION
**Pull request by v-zhifufeng**
## Description

https://www.microsoft.com/en-us/testbase is one Azure Service, plan go to GA around November, so want to start PLR tasks.
I submitted the md files for  syntax review.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @v-zhifufeng ,

Please raise issue for design review instead: 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues

**Comment by isra-fel** [comment]
Let me move the pull request to draft state. Please feel free to mark it "Ready for review" when you feel comfortable. Thanks

**Comment by isra-fel** [comment]
Hey @v-zhifufeng any updates on the PR?

**Comment by msJinLei** [comment]
We are closing the PR since no update for a long time. You can submit a new one if you want to continue your job.

**Pull request closed without merging**
