### PR TITLE
multica

### PR DESCRIPTION
**Pull request by skomarag**
Getting Avijit's changes

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@skomarag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@skomarag You need to link your account to the azure org.  http://aka.ms/azuregithub ALso, please rebase these commits on the dev branch.

**Comment by markcowl** [comment]
@deepakrajendranmsft can you review?

**Comment by markcowl** [comment]
@skomarag Please update the pull request title to be more descriptive.

**Comment by markcowl** [comment]
@skomarag you will need to pull these changes into your fork of the repo and update.  Closing this PR.

**Pull request closed without merging**
