### PR TITLE
ARM cmdlets for SQLVM extension supporting auto-patching and auto-backup

### PR DESCRIPTION
**Pull request by sethusrinivasan**
1) ARM cmdlets for SQLVM extension added ( followed DSC's ARM cmdlet pattern )
2) supports configuring auto patching in ARM mode
3) supports configuring auto backup in ARM mode
4) Get sqlvm extension status in ARM mode
5) remove sqlvm extension in ARM mode

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sethusrinivasan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (seths). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@sethusrinivasan Please add these changes to the changelog

**Comment by sethusrinivasan** [comment]
Thanks for feedback. I am working on merging changes and updating changelog.md

**Comment by sethusrinivasan** [comment]
Need to work on few additional changes, closing this request - Please don't merge. I shall send another update

**Pull request closed without merging**
