### PR TITLE
Create .editorconfig

### PR DESCRIPTION
**Pull request by JanuszNowak**
Create .editorconfig for applying code formatting  add basic rule trim_trailing_whitespace = true

## Checklist

- [x ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @JanuszNowak , what's the config used for what code editor? BTW, why you intent to merge your code into preview branch?

**Comment by JanuszNowak** [comment]
@BethanyZhou I used editorconfig.org with is integrating with multiple editors GUI and CLI's, my mistake to merge to preview, with branch I suppose to merge ?

**Comment by BethanyZhou** [comment]
Hi @JanuszNowak , sorry for late response. Target your PR to main branch.

**Comment by wyunchi-ms** [comment]
Hi @JanuszNowak , there are too many commits here. Do you mind rebase your branch? Thanks!

**Comment by msJinLei** [comment]
@JanuszNowak Thanks for the contribution. However, since your PR branch is too far behind the main branch, please cherry pick it above the latest main and submit a new PR.

**Pull request closed without merging**
