### PR TITLE
Update Microsoft.Authorization api version for Get-RoleDefinition 6

### PR DESCRIPTION
**Pull request by mumoryan**
## Description

Update Microsoft.Authorization api version for Get-RoleDefinition

## Checklist

- **Mandatory**: please state whether this PR targets a [**general** release](../blob/main/CONTRIBUTING.md#target-release-types) / [**public preview**](../blob/main/CONTRIBUTING.md#target-release-types) / [**private preview**]((../blob/main/CONTRIBUTING.md#target-release-types)) / [**engineering build**](../blob/main/CONTRIBUTING.md#target-release-types) of Azure PowerShell?
    - General release
- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by dolauli** [comment]
@mumoryan Please fix the CI failures.

**Comment by mumoryan** [comment]
> @mumoryan Please fix the CI failures.

Fixed, but got a few warnings. Seems like the only one related to my change and is actionable is to modify the change log. Is this needed for a partial api-version update for role definitions?

**Comment by mumoryan** [comment]
Followed up on what I discussed with @dolauli . In the latest commit [Update Microsoft.Authorization api version for Get-RoleDefinition 6 by mumoryan · Pull Request #23646 · Azure/azure-powershell (github.com)](https://github.com/Azure/azure-powershell/pull/23646/commits/7333d508e7b2c466f801ae38e4efe71e33aea715)

1. Modified README with changes in step 2
2. updated generated sdk with autorest.powershell
3. No auto-mapper changes
4. No build failures
5. Breaking changes command reported no breaking changes

**Comment by mumoryan** [comment]
Closing old prs. Merged one in https://github.com/Azure/azure-powershell/pull/23797

**Pull request closed without merging**
