### PR TITLE
Strategy library refactoring

### PR DESCRIPTION
**Pull request by sergey-shandar**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
Can you please fix the merge conflict? We have moved ChangeLog/psd1 files from `src/ResourceManager/` to `src/ResourceManager/{{service}}/Commands.{{service}}`, so you will need to move your ChangeLog/psd1 updates there.

**Comment by cormacpayne** [comment]
Closing this PR for now until @markcowl is back

**Comment by MiYanni** [comment]
Many of these changes will need to be retargeted to the azure-powershell-common repo.

**Comment by maddieclayton** [comment]
@sergey-shandar Please let me know when the build is passing for this PR and you are ready for one of us to take a look.

**Comment by maddieclayton** [comment]
@sergey-shandar Closing this for now as we are doing the azure-powershell-common split now and this will be easier to merge once that is complete.  This PR should target this repo: https://github.com/Azure/azure-powershell-common

**Pull request closed without merging**
