### PR TITLE
PR for SQL Database Replication Cmdlets

### PR DESCRIPTION
**Pull request by dominiqa**
Three new cmdlets for Geo Replication:
New-AzureSqlDatabaseSecondary
Get-AzureSqlDatabaseReplicationLink
Remove-AzureSqlDatabaseSecondary

And New-AzureSqlDatabaseCopy for one time database copies.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@dominiqa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/86/

**Comment by stankovski** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/110/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/414/

**Comment by stankovski** [comment]
@dominiqa please pull from "upstream dev" and update your fork

**Comment by dominiqa** [comment]
Fork updated.  -Dom

**Comment by stankovski** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/113/

**Pull request merged**
