### PR TITLE
New packet capture Cmdlet for Network Module:  VpnConnection and VpnGateway Resource 

### PR DESCRIPTION
**Pull request by jiaczh**
## Description

this PR add 4 extra command : Start-AzVpnConnectionPacketCapture, Stop-AzVpnConnectionPacektCapture,Start-AzVpnGatewayPacketCapture,  Stop-AzVpnGatewayPacketCapture,  under Network Module
CmdLet review link: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/660
## Checklist

- [ X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ X] The title of the PR is clear and informative
- [ X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ X] If applicable, the changes made in the PR have proper test coverage
- [ X] For public API changes to cmdlets:
    - [ X] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — APPROVED** [review]

**Comment by jiaczh** [comment]
hi @msJinLei , thanks for the review, I am currently waiting for https://github.com/Azure/azure-powershell/pull/12751 this PR to merge to update the SDK version, then the checks should get passed, is it possible to merge in without passing the checks?

**Review by msJinLei — CHANGES_REQUESTED** [review]
@jiaczh Please fix the building error

```
2020-08-31T02:01:47.7268541Z Cortex\VpnConnection\StartAzVpnConnectionPacketCaptureCommand.cs(126,13): error CS0246: The type or namespace name 'VpnConnectionPacketCaptureStartParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7270361Z Cortex\VpnConnection\StartAzVpnConnectionPacketCaptureCommand.cs(126,72): error CS0246: The type or namespace name 'VpnConnectionPacketCaptureStartParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7271778Z Cortex\VpnGateway\StopAzVpnGatewayPacketCaptureCommand.cs(86,13): error CS0246: The type or namespace name 'VpnGatewayPacketCaptureStopParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7273280Z Cortex\VpnGateway\StopAzVpnGatewayPacketCaptureCommand.cs(86,68): error CS0246: The type or namespace name 'VpnGatewayPacketCaptureStopParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7274782Z Cortex\VpnGateway\StartAzVpnGatewayPacketCaptureCommand.cs(86,13): error CS0246: The type or namespace name 'VpnGatewayPacketCaptureStartParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7276054Z Cortex\VpnGateway\StartAzVpnGatewayPacketCaptureCommand.cs(86,69): error CS0246: The type or namespace name 'VpnGatewayPacketCaptureStartParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7277360Z Cortex\VpnConnection\StopAzVpnConnectionPacketCaptureCommand.cs(120,13): error CS0246: The type or namespace name 'VpnConnectionPacketCaptureStopParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
2020-08-31T02:01:47.7278846Z Cortex\VpnConnection\StopAzVpnConnectionPacketCaptureCommand.cs(120,71): error CS0246: The type or namespace name 'VpnConnectionPacketCaptureStopParameters' could not be found (are you missing a using directive or an assembly reference?) [D:\a\1\s\src\Network\Network\Network.csproj] [D:\a\1\s\build.proj]
```

**Comment by jiaczh** [comment]
this PR https://github.com/Azure/azure-powershell/pull/12809 is good and already checked in,  so this one will be closed

**Pull request closed without merging**
