### PR TITLE
Provide tenant admin support for deleting and migrating UVHD

### PR DESCRIPTION
**Pull request by arcadiahlyy**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@arcadiahlyy__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hele). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@arcadiahlyy The build is failing because it can't find your package, did you publish it?  Unable to find version '2.0.6' of package 'Microsoft.WindowsAzure.Management.RemoteApp'

**Comment by markcowl** [comment]
@arcadiahlyy This PR now has merge conflicts as well.  Code complete is past, if you'd like to include this PR in the release, you must update and retarget at the release branch.

**Comment by hovsepm** [comment]
@arcadiahlyy please add test coverage for new cmdlets.

**Comment by arcadiahlyy** [comment]
I will close this PR and open a new one.

**Pull request closed without merging**
