### PR TITLE
Sync DataContract with latest WAP settings

### PR DESCRIPTION
**Pull request by sanjkum**
Fix for the bug #4639382 (http://vstfrd:8080/Azure/RD/_workitems#_a=edit&id=4639382). As part of this the Data Contract is updated to be in syn with Tenant API of WAP

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sanjkum__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@sanjkum__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci retest this please number 2

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/job/powershell-demand/

**Pull request merged**
