### PR TITLE
NSP api version update

### PR DESCRIPTION
**Pull request by kaushal087**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] N/A

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by kaushal087** [comment]
Everything is okay and PR is ready for review.

**Comment by dolauli** [comment]
@kaushal087 I have enabled the CI for your preview branch. And I have made some changes in your code to migrate to autorest.powershell v4. And there are still issues in your PR. Please do following things.

1. Sync your branch with [generation-network-preview](https://github.com/Azure/azure-powershell/tree/generation-network-preview)
2. Fixed the test failures
3. Add examples for new cmdlets

**Comment by kaushal087** [comment]
@dolauli , I have synced with [generation-network-preview](https://github.com/Azure/azure-powershell/tree/generation-network-preview). And wrote test cases . Please help with the merge.

**Comment by dolauli** [comment]
@kaushal087 There are some example issues detected by the CI. Please fix them

**Review by dolauli — APPROVED** [review]

**Pull request merged**
