### PR TITLE
Revert the change for PSSwaggerUtility.psm1 and psd1

### PR DESCRIPTION
**Pull request by wenjlu-lgy**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wenjlu-lgy** [comment]
@bganapa Could you help to review it?

**Comment by wyunchi-ms** [comment]
Hi @wenjlu-lgy , could you please give more info about this PR? Which commit do you want to revert to and why?

**Comment by bganapa** [comment]
@wyunchi-ms This is going against AuzreRM branch for AzureStack. I will mail you the details

**Comment by isra-fel** [comment]
Hi Bala, any updates?

**Comment by wyunchi-ms** [comment]
Hi @bganapa , any updates?

**Comment by bganapa** [comment]
@wyunchi-ms we are still working to get the jenkins node up as this is going against AzureRM. Thanks for the follwo up!

**Comment by isra-fel** [comment]
Kindly ping

**Comment by bganapa** [comment]
@isra-fel we dont need this PR anymore as we have moved the content in to Azurestack-powershell repo

**Pull request closed without merging**
