### PR TITLE
Fixed typo for Set-CscAzureDataLakeStoreACL documentation

### PR DESCRIPTION
**Pull request by GlueCoder**
## Description

Fixed typo for Set-CscAzureDataLakeStoreACL documentation.  In the documentation examples, the cmdlet `Get-AzureRmDataLakeStoreItemAcl` was listed, but does not exist.

## Checklist

- [X] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [X] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by maddieclayton** [comment]
@azuresdkci Add to whitelist

**Comment by maddieclayton** [comment]
@GlueCoder Thank you for your contribution!  I will merge as soon as the build finishes.

**Comment by maddieclayton** [comment]
@GlueCoder Please sign the CLA in order for the checks to pass.

**Pull request merged**
