### PR TITLE
Added framework for service tasks

### PR DESCRIPTION
**Pull request by vchske**
- Added OCI driver service tasks

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
@vchske Could you link your cmdlet review here? I cannot find it.

**Comment by vchske** [comment]
@msJinLei Can you tell me what you mean by cmdlet review? Our cmdlets have been in production for over a year so not sure what review needs to happen?

**Comment by vchske** [comment]
@msJinLei Also, can you help me understand why the tests are failing due to the module not loading?

**Comment by msJinLei** [comment]
> @msJinLei Also, can you help me understand why the tests are failing due to the module not loading?

Because you don't export new added cmdlet "New-AzDataMigrationService"

**Comment by msJinLei** [comment]
> @msJinLei Also, can you help me understand why the tests are failing due to the module not loading?

To add new cmdlets or make breaking changes to the existing cmdlets, you need to submit a cmdlet review firstly. Refer to the link [azure-powershell-cmdlet-review-pr](https://github.com/Azure/azure-powershell-cmdlet-review-pr)

**Comment by isra-fel** [comment]
Kindly ping @vchske , please submit an issue for design review here: Azure/azure-powershell-cmdlet-review-pr

**Comment by msJinLei** [comment]
@vchske, we are closing this PR since no update for a long time. You can reopen or submit a new PR if needed.

**Pull request closed without merging**
