### PR TITLE
Add Automation webhook, module and asset tests

### PR DESCRIPTION
**Pull request by thomasyip-msft**
## Description

- Add Automation webhook, module and asset tests
- merge latest and standardize test naming

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@thomasyip-msft You have a test failure:
```powershell
0.2258657s ✘  Commands.Automation.Test.CertificateTests.TestE2ECertificates
System.Management.Automation.ActionPreferenceStopException : The running command stopped because the preference variable "ErrorActionPreference" or common parameter is set to Stop: Cannot find path 'C:\workspace\powershell\src\ResourceManager\Automation\Commands.Automation.Test\bin\Debug\ScenarioTests\sdkTestCert.cer' because it does not exist.
   at System.Management.Automation.Runspaces.PipelineBase.Invoke(IEnumerable input)
   at System.Management.Automation.PowerShell.Worker.ConstructPipelineAndDoWork(Runspace rs, Boolean performSyncInvoke)
   at System.Management.Automation.PowerShell.Worker.CreateRunspaceIfNeededAndDoWork(Runspace rsToUse, Boolean isSync)
   at System.Management.Automation.PowerShell.CoreInvokeHelper[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.CoreInvoke[TInput,TOutput](PSDataCollection`1 input, PSDataCollection`1 output, PSInvocationSettings settings)
   at System.Management.Automation.PowerShell.Invoke(IEnumerable input, PSInvocationSettings settings)
   at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts)
   at Microsoft.Azure.Commands.Automation.Test.AutomationScenarioTestsBase.RunPowerShellTest(XunitTracingInterceptor logger, String[] scripts) in c:\workspace\powershell\src\ResourceManager\Automation\Commands.Automation.Test\ScenarioTests\AutomationScenarioTestsBase.cs:line 68
   at Commands.Automation.Test.CertificateTests.TestE2ECertificates() in c:\workspace\powershell\src\ResourceManager\Automation\Commands.Automation.Test\ScenarioTests\CertificateTests.cs:line 43
Traits:
Service	Automation
RunType	LiveOnly
AcceptanceType	CheckIn
AcceptanceType	BVT
```

**Comment by cormacpayne** [comment]
@thomasyip-msft a few lines were flagged by cred scanner as having passwords/keys/secrets: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/9073/artifact/src/Package/CredentialScannerOutput/CredScanIssues.csv

If these passwords/keys/secrets are false positives, or have been deleted since the test was recorded, please follow the instructions for suppressing the exceptions in this document: https://github.com/Azure/adx-documentation-pr/blob/master/engineering/credscan-ps.md

**Comment by MiYanni** [comment]
@azuresdkci Retest this please

**Comment by MiYanni** [comment]
@thomasyip-msft Can you collapse your commits? 56 is just too many.

**Pull request merged**
