### PR TITLE
Added test cases for DiskEncryptionSet input for V2A and H2A

### PR DESCRIPTION
**Pull request by vidyadharijami**
## Description

Added test cases for DiskEncryptionSet input for V2A and H2A
Reference PR: https://github.com/Azure/azure-powershell/pull/10764

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@vidyadharijami Please fix the test error
````
Unable to find a matching HTTP request for URL 'GET /subscriptions/7c943c1b-5122-4097-90c8-861411bdd574/resourceGroups/canaryexproute/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01'. Calling method Item().
````

**Comment by vidyadharijami** [comment]
> @vidyadharijami Please fix the test error
> Unable to find a matching HTTP request for URL 'GET /subscriptions/7c943c1b-5122-4097-90c8-861411bdd574/resourceGroups/canaryexproute/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01'. Calling method Item().




> @vidyadharijami Please fix the test error
> Unable to find a matching HTTP request for URL 'GET /subscriptions/7c943c1b-5122-4097-90c8-861411bdd574/resourceGroups/canaryexproute/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01'. Calling method Item().

@msJinLei 

I have run the test cases whichever are added in this commit and added the json session recordings. The test environment I have used is different from the test environment used by existing test cases. And also I haven't updated the vault credentials file.

Can you tell me where did you get the error specified above?

**Comment by msJinLei** [comment]
> > @vidyadharijami Please fix the test error
> > Unable to find a matching HTTP request for URL 'GET /subscriptions/7c943c1b-5122-4097-90c8-861411bdd574/resourceGroups/canaryexproute/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01'. Calling method Item().
> 
> > @vidyadharijami Please fix the test error
> > Unable to find a matching HTTP request for URL 'GET /subscriptions/7c943c1b-5122-4097-90c8-861411bdd574/resourceGroups/canaryexproute/providers/Microsoft.RecoveryServices/vaults?api-version=2016-06-01'. Calling method Item().
> 
> @msJinLei
> 
> I have run the test cases whichever are added in this commit and added the json session recordings. The test environment I have used is different from the test environment used by existing test cases. And also I haven't updated the vault credentials file.
> 
> Can you tell me where did you get the error specified above?

Hi @vidyadharijami,
to reproduce the error, please use playback mode to run the test. (Set RecordMode to playback when run Set-TestEnvironment)

I check the error log.
The error occurs in 
````
                this.RecoveryServicesClient.ValidateVaultSettings(
                    asrVaultCreds.ResourceName,
                    asrVaultCreds.ResourceGroupName);
````
of ImportAzureRmRecoveryServicesAsrVaultSettingsFile.cs.
Please take a look at it.

**Comment by vidyadharijami** [comment]
@msJinLei

Fixed test cases. Can you please take a look into it.

**Comment by vidyadharijami** [comment]
@msJinLei 

Can you please take a look into this PR.

**Pull request merged**
