### PR TITLE
Update Batch cmdlets to use general availability API

### PR DESCRIPTION
**Pull request by jasper-schneider**
The Batch service went GA with an updated REST API that involved some reorganization and renaming of service entities.  
The Batch cmdlets have been updated to reflect these changes.  The tests have been rerecorded, the help xml has been updated, and the changelog has also been updated.
Because of the API changes, I unfortunately had to touch just about every Batch cmdlet and its associated tests, but most of the changes are just renames (Name -> Id, workitem -> job schedule, vm -> compute node).

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jasper-schneider__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaschnei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
Running post-checkin tests since PR is too large to review: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-pr-on-demand/82/

**Comment by stankovski** [comment]
Running MSI build since PR is too large to review: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/351/

**Comment by stankovski** [comment]
Test http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/29/ failed:
```
 CSC : error CS1577: Assembly generation failed -- Referenced assembly 'Microsoft.Azure.Batch' does not have a strong name [D:\workspace\powershell-on-demand\src\ResourceManager\Batch\Commands.Batch\Commands.Batch.csproj]
```

**Comment by jasper-schneider** [comment]
Yup, we had a problem in our signing process for one of our NuGet dependencies, in the process of resolving.

**Comment by jasper-schneider** [comment]
Submitted a fix, I hit restart on the Jenkins build: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/376/

**Comment by jasper-schneider** [comment]
The Jenkins build has passed.

**Comment by jasper-schneider** [comment]
Ah, didn't see that there were 2 Jenkins builds.  Restarting the "on demand" build here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/41/

**Pull request merged**
