### PR TITLE
Add NetworkManager Service

### PR DESCRIPTION
**Pull request by yanfa317**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @yanfa317 , please submit a cmdlet review for your changes here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues. After that, we will start to review your PR.

**Comment by yanfa317** [comment]
@BethanyZhou , Here is the Design doc, and I believe it has been reviewed. Thanks!

**Comment by yanfa317** [comment]
@BethanyZhou , Can you help us review it? If there are any issues ,please comment them. If everything is OK, can you not merge it in for now? Since we are doing internal tests, and maybe there will be some small changes coming. But I will finalize it as soon as possible. thanks!

**Comment by BethanyZhou** [comment]
Hi @yanfa317 , left a comment on your design doc.

**Comment by yanfa317** [comment]
@BethanyZhou  I resolved staticanalysis error, please review again. Thanks!

**Pull request merged**
