### PR TITLE
[Test Controller] New test controller applied to KeyVault

### PR DESCRIPTION
**Pull request by vladimir-shcherbakov**
* Private methods they had that directly called the Graph client, and the calls to those methods in each of the tests are deleted. 
* Skip messages saying what calls need to be added to the .ps1 function for the corresponding test are updated and the issue #8295 is opened. 
* All skipped test cases didn't work in playback mode before the update.

### CODE REVIEW

**Comment by vladimir-shcherbakov** [comment]
As the old test controller required manual library clients creation during initialization phase - it was natural to use the clients for building test infrastructure (resource groups, storage accounts, etc). The new test controller creates the library clients automatically during runtime phase.  To make testing experience consistent across services - we encourage people to build test infrastructure with powershell cmdlets right in the powershell test script.    
Since their entire test recording infrastructure was build based on our old test controller  
1. All tests that pass - keep passing on the new test controller.
2. The tests that used library clients for building test infrastructure 
    * have skip attribute
    * didn't work if the skip attribute was commented out
    
    For these tests I updated the method body and changed the skip message accordingly

**Comment by vladimir-shcherbakov** [comment]
@RandalliLama We are applying a new test controller for scenario tests. Could you take a look at the PR?

**Comment by MiYanni** [comment]
@vladimir-shcherbakov Are you able to address Mark's comments?

**Comment by cormacpayne** [comment]
Temporarily closing this PR -- @vladimir-shcherbakov when you re-open this PR, make sure to pull in the latest from the `master` branch to get the ADO changes.

**Pull request closed without merging**
