### PR TITLE
Express Route Gateway and Express Route Connection cmdlets

### PR DESCRIPTION
**Pull request by vinayada1**
## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@vinayada1 should this be targeting `preview` or `network-october-release`?

**Comment by vinayada1** [comment]
> @vinayada1 should this be targeting `preview` or `network-october-release`?

We need to GA this by Dec. Please suggest which branch I should target.

**Comment by cormacpayne** [comment]
@MikhailTryakhov Hey Mikhail, if this feature needs to be in by December, should be target this for the `network-november-release` branch whenever it's created?

**Comment by MikhailTryakhov** [comment]
@vinayada1 in which API version this feature supported?

**Comment by vinayada1** [comment]
> @vinayada1 in which API version this feature supported?

2018-08-01

**Comment by praries880** [comment]
@vinayada1 changing the target branch to network-october-branch

**Comment by praries880** [comment]
design review : https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/186

@vinayada1 Are these cmdlets expected to be released in december (as per the design review)?

**Comment by vinayada1** [comment]
I have updated the review

**Pull request closed without merging**
