### PR TITLE
release-2023-02-07

### PR DESCRIPTION
**Pull request by isra-fel**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by BethanyZhou — APPROVED** [review]
LGTM

**Comment by isra-fel** [comment]
Force merging this PR because the security-tools is failing because out of memory.
```log
2023-02-06T06:05:11.3093869Z ##[section]Starting: Run CredScan
2023-02-06T06:05:11.3333376Z ==============================================================================
2023-02-06T06:05:11.3333625Z Task         : CredScan
2023-02-06T06:05:11.3333754Z Description  : Scan source code for committed credentials
2023-02-06T06:05:11.3333909Z Version      : 2.358.0
2023-02-06T06:05:11.3334018Z Author       : Microsoft Corporation
2023-02-06T06:05:11.3334155Z Help         : [CredScan Docs](https://aka.ms/CredScan)<br/>[SecDevTools Extension Docs](https://aka.ms/SDT-AzDevOps)
2023-02-06T06:05:11.3334411Z ==============================================================================
2023-02-06T06:05:30.7270513Z ******************************************************************************
2023-02-06T06:05:30.7279473Z *
2023-02-06T06:05:30.7288983Z * Please upgrade the version of this build task in your build to major version: 3
2023-02-06T06:05:30.7297029Z * Secure Development Tools (Guardian v1) is on the path to deprecation.
2023-02-06T06:05:30.7305164Z * Based on usage telemetry, this message will increase in build severity in the near future.
2023-02-06T06:05:30.7313074Z *
2023-02-06T06:05:30.7327466Z * For more information, please see: https://aka.ms/gdn-v1-deprecation
2023-02-06T06:05:30.7335502Z *
2023-02-06T06:05:30.7344437Z ******************************************************************************
2023-02-06T06:05:30.7353030Z Enabling TLS 1.2...
2023-02-06T06:05:30.9039336Z Locking M365 package version to 0.6.0
2023-02-06T06:05:31.3192959Z Initializing analysis environment...
2023-02-06T06:05:31.4594646Z Downloaded nuget.exe: D:\a\_work\_sdt\nuget.exe
2023-02-06T06:05:31.6526700Z ##[command]"D:\a\_work\_sdt\nuget.exe" install Microsoft.Security.CredScan.Client -Source https://pkgs.dev.azure.com/securitytools/_packaging/SecureDevelopmentTools/nuget/v3/index.json -ConfigFile D:\a\_work\_sdt\dt.nuget.config -NonInteractive
2023-02-06T06:05:33.4678650Z Feeds used:
2023-02-06T06:05:33.4680142Z   https://pkgs.dev.azure.com/securitytools/_packaging/SecureDevelopmentTools/nuget/v3/index.json
2023-02-06T06:05:33.4680742Z 
2023-02-06T06:05:33.4700412Z Installing package 'Microsoft.Security.CredScan.Client' to 'D:\a\_work\_sdt'.
2023-02-06T06:05:33.7992805Z   GET https://pkgs.dev.azure.com/SecurityTools/_packaging/4d3937b9-e0c2-4312-bb00-d439441e6c71/nuget/v3/registrations2-semver2/microsoft.security.credscan.client/index.json
2023-02-06T06:05:33.8434124Z   OK https://pkgs.dev.azure.com/SecurityTools/_packaging/4d3937b9-e0c2-4312-bb00-d439441e6c71/nuget/v3/registrations2-semver2/microsoft.security.credscan.client/index.json 44ms
2023-02-06T06:05:33.9093924Z 
2023-02-06T06:05:33.9095083Z 
2023-02-06T06:05:33.9111431Z Attempting to gather dependency information for package 'Microsoft.Security.CredScan.Client.2.2.7.8' with respect to project 'D:\a\_work\_sdt', targeting 'Any,Version=v0.0'
2023-02-06T06:05:33.9594099Z Gathering dependency information took 34.54 ms
2023-02-06T06:05:33.9692870Z Attempting to resolve dependencies for package 'Microsoft.Security.CredScan.Client.2.2.7.8' with DependencyBehavior 'Lowest'
2023-02-06T06:05:34.0103837Z Resolving dependency information took 0 ms
2023-02-06T06:05:34.0105171Z Resolving actions to install package 'Microsoft.Security.CredScan.Client.2.2.7.8'
2023-02-06T06:05:34.0121957Z Resolved actions to install package 'Microsoft.Security.CredScan.Client.2.2.7.8'
2023-02-06T06:05:34.0385918Z Retrieving package 'Microsoft.Security.CredScan.Client 2.2.7.8' from 'SecureDevelopmentTools'.
2023-02-06T06:05:34.1595737Z   GET https://pkgs.dev.azure.com/SecurityTools/_packaging/4d3937b9-e0c2-4312-bb00-d439441e6c71/nuget/v3/flat2/microsoft.security.credscan.client/2.2.7.8/microsoft.security.credscan.client.2.2.7.8.nupkg
2023-02-06T06:05:34.2208966Z   OK https://pkgs.dev.azure.com/SecurityTools/_packaging/4d3937b9-e0c2-4312-bb00-d439441e6c71/nuget/v3/flat2/microsoft.security.credscan.client/2.2.7.8/microsoft.security.credscan.client.2.2.7.8.nupkg 61ms
2023-02-06T06:05:34.2411928Z Installing Microsoft.Security.CredScan.Client 2.2.7.8.
2023-02-06T06:05:55.7174892Z Adding package 'Microsoft.Security.CredScan.Client.2.2.7.8' to folder 'D:\a\_work\_sdt'
2023-02-06T06:05:56.5564216Z Added package 'Microsoft.Security.CredScan.Client.2.2.7.8' to folder 'D:\a\_work\_sdt'
2023-02-06T06:05:56.5590853Z Successfully installed 'Microsoft.Security.CredScan.Client 2.2.7.8' to D:\a\_work\_sdt
2023-02-06T06:05:56.5605952Z Executing nuget actions took 22.53 sec
2023-02-06T06:05:56.6973504Z Running CredScan...
2023-02-06T06:05:56.9867122Z ##[command]"D:\a\_work\_sdt\Microsoft.Security.CredScan.Client.2.2.7.8\lib\net461\CredentialScanner.exe" D:\a\_work\1\s\SecurityTmp D:\a\_work\_sdt\Microsoft.Security.CredScan.Client.2.2.7.8\lib\net461\ConfigFiles\FileSystemProvider.json D:\a\_work\1\_sdt\logs\CredentialScanner\CredentialScanner sarif -Sp D:\a\_work\1\s\tools\SecurityTools\CredScanSuppressions.json
2023-02-06T06:06:00.4579934Z Start credential scanner
2023-02-06T06:06:00.4581096Z Initializing...
2023-02-06T06:06:07.0344799Z Initialization completed.
2023-02-06T06:06:07.0346026Z Start file scanning...
2023-02-06T06:13:34.9485200Z Detected 2 issue(s) in D:\a\_work\1\s\SecurityTmp\src\Sql\Sql.Test\ScenarioTests\Common.ps1
2023-02-06T06:13:39.5481970Z Detected 1 issue(s) in D:\a\_work\1\s\SecurityTmp\src\Sql\Sql.Test\SessionRecords\Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceDtcScenarioTests\TestGetAndSetManagedInstanceDtc.json
2023-02-06T06:13:42.8972186Z Detected 1 issue(s) in D:\a\_work\1\s\SecurityTmp\src\Sql\Sql.Test\SessionRecords\Microsoft.Azure.Commands.Sql.Test.ScenarioTests.ManagedInstanceDtcScenarioTests\TestManagedInstanceDtcPipingScenarios.json
2023-02-06T06:14:39.5887828Z Detected 2 issue(s) in D:\a\_work\1\s\SecurityTmp\src\RecoveryServices\RecoveryServices.SiteRecovery.Test\SessionRecords\RecoveryServices.SiteRecovery.Test.AsrA2ATests\A2ANewAsrReplicationProtectedItem.json
2023-02-06T06:15:53.2137906Z Detected 2 issue(s) in D:\a\_work\1\s\SecurityTmp\src\RecoveryServices\RecoveryServices.SiteRecovery.Test\SessionRecords\RecoveryServices.SiteRecovery.Test.AsrA2ATests\A2ANewAsrReplicationProtectedItemDisk.json
2023-02-06T06:17:00.2894708Z [WARNING] Asset D:\a\_work\1\s\SecurityTmp\src\Compute\Compute.Test\SessionRecords\Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests\TestAEMExtensionAdvancedLinuxMD_ESeries.json failed to get process
2023-02-06T06:17:00.6957007Z Timeout in 600 sec.
2023-02-06T06:17:01.4938631Z 
2023-02-06T06:20:34.4199621Z [EXCEPTION] Failed to scan D:\a\_work\1\s\SecurityTmp\tools\Tools.Common\SerializedCmdlets\Az.Network.json
2023-02-06T06:20:34.8256457Z One or more errors occurred.
2023-02-06T06:20:35.0298199Z [Inner Exception] One or more errors occurred.
2023-02-06T06:20:35.4399477Z [Inner Exception] Exception of type 'System.OutOfMemoryException' was thrown.
2023-02-06T06:20:35.8462231Z 
2023-02-06T06:22:46.1105634Z [EXCEPTION] Failed to scan D:\a\_work\1\s\SecurityTmp\src\Compute\Compute.Test\SessionRecords\Microsoft.Azure.Commands.Compute.Test.ScenarioTests.AEMExtensionTests\TestAEMExtensionAdvancedLinuxMD_ESeries.json
2023-02-06T06:22:46.7194794Z One or more errors occurred.
2023-02-06T06:22:46.9231505Z [Inner Exception] One or more errors occurred.
2023-02-06T06:22:47.3292873Z [Inner Exception] Exception of type 'System.OutOfMemoryException' was thrown.
2023-02-06T06:22:47.7356212Z 
2023-02-06T06:31:38.8369514Z NumberOfAsset : 1407
2023-02-06T06:31:38.8371085Z NumberOfAssetScanned : 1368
2023-02-06T06:31:38.8371845Z NumberOfAssetBytes : 516,170,371
2023-02-06T06:31:38.8372607Z NumberOfAssetBytesScanned : 515,850,070
2023-02-06T06:31:38.8373353Z NumberOfScanResult: 29
2023-02-06T06:31:38.8374027Z NumberOfRankedResult : 29
2023-02-06T06:31:38.8374711Z NumberOfCredentialRecord: 55
2023-02-06T06:31:38.8375421Z NumberOfSuppressedRecord: 47
2023-02-06T06:31:38.8376098Z NumberOfScanError: 1
2023-02-06T06:31:38.8377668Z 
2023-02-06T06:31:40.8463972Z Scan completed in 1540.54 seconds
2023-02-06T06:31:41.1262022Z ##[error]Unexpected exit code 7 returned from tool CredentialScanner.exe. Partial scan completed with application warnings, suppressed warnings, and credential matches. Please refer to https://microsoft.sharepoint.com/teams/CESecEngineering/CredScan/CredScan%20Wiki/Home.aspx for more info.
2023-02-06T06:31:42.6663342Z ##[error]Unexpected exit code 7 returned from tool CredentialScanner.exe
2023-02-06T06:31:42.7175875Z ##[section]Finishing: Run CredScan
```

**Pull request merged**
