### PR TITLE
Alecb/desktop virtualization 2023 10 04 preview

### PR DESCRIPTION
**Pull request by alec-baird**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by charleskorb** [comment]
Reviewers, how can we add a custom cmdlet to an existing autogenerated cmdlet without a breaking change? We get "The parameter set '__AllParameterSets' for cmdlet 'Update-AzWvdApplication' has been removed." but we did not remove any parameter sets, only add a new one, which should not be a breaking change.

**Review by VeryEarly — CHANGES_REQUESTED** [review]
please add folder
src/DesktopVirtualization/UX/Microsoft.DesktopVirtualization back

**Comment by VeryEarly** [comment]
please suppress the breaking change warning

**Comment by ryanosh** [comment]
@VeryEarly I just pushed changes to resolve both of your requests. Let us know if there is anything else you need

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
