### PR TITLE
Add support for Rules Engine feature and Private Link feature to Az.FrontDoor module

### PR DESCRIPTION
**Pull request by jessicl-ms**
## Description
See https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/554 for detailed description and example usage of the new/modified cmdlets.

### Changed Cmdlets
For Private Link
https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorBackendObject.md

For Rules Engine
https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorRoutingRuleObject.md

### New Cmdlets
For Rules Engine
https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorRulesEngine.md

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/Get-AzFrontDoorRulesEngine.md

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/Set-AzFrontDoorRulesEngine.md

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/Remove-AzFrontDoorRulesEngine.md

These cmdlets are for constructing PS objects that are eventually passed in as inputs to Rules Engine cmdlets. These cmdlets do not make web requests.

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorHeaderActionObject.md

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorRulesEngineActionObject.md

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorRulesEngineMatchConditionObject.md

https://github.com/jessicl-ms/azure-powershell/blob/jessicl/update-afd-ps-module/src/FrontDoor/FrontDoor/help/New-AzFrontDoorRulesEngineRuleObject.md

### Sample of end-to-end usage

CRUD operations on Rules Engine
```
PS C:\> $headerAction1 = New-AzFrontDoorHeaderActionObject -HeaderName "headeraction1" -HeaderActionType Overwrite
PS C:\> $headerAction2 = New-AzFrontDoorHeaderActionObject -HeaderName headeraction2 -HeaderActionType Append
PS C:\> $headerActions = $headerAction1, $headerAction2
PS C:\> $rulesEngineAction = New-AzFrontDoorRulesEngineActionObject -RequestHeaderAction $headerActions -ForwardingProtocol HttpsOnly -BackendPoolName mybackendpool -ResourceGroupName myResourceGroup -FrontDoorName myFrontDoor -QueryParameterStripDirective StripNone -DynamicCompression Disabled -EnableCaching $true
PS C:\> $rulesEngineAction

RequestHeaderActions           ResponseHeaderActions RouteConfigurationOverride
--------------------           --------------------- --------------------------
{headeraction1, headeraction2} {}                    Microsoft.Azure.Commands.FrontDoor.Models.PSForwardingConfigurati…

PS C:\> $rulesEngineAction.RequestHeaderAction

HeaderName    HeaderActionType Value
----------    ---------------- -----
headeraction1        Overwrite
headeraction2           Append

PS C:\> $rulesEngineAction.ResponseHeaderAction
PS C:\> $rulesEngineAction.RouteConfigurationOverride

CustomForwardingPath         :
ForwardingProtocol           : HttpsOnly
BackendPoolId                : /subscriptions/<subscriptionId>/resourceGroups/myResourceGroup/provi
                               ders/Microsoft.Network/frontDoors/myFrontDoor/BackendPools/mybackendpool
QueryParameterStripDirective : StripNone
DynamicCompression           : Disabled
EnableCaching                : True

PS C:\> $rulesEngineMatchCondition = New-AzFrontDoorRulesEngineMatchConditionObject -MatchVariable RequestHeader -Operator Equal -MatchValue allowoverride -Transform "LowerCase", "UpperCase"-Selector Rules-Engine-Route-Forward -NegateCondition $false
PS C:\> $rulesEngineMatchCondition

RulesEngineMatchVariable : RequestHeader
RulesEngineMatchValue    : {allowoverride}
Selector                 : Rules-Engine-Route-Forward
RulesEngineOperator      : Equal
NegateCondition          : False
Transform                : {Lowercase, Uppercase}

PS C:\> $rulesEngineRule1 = New-AzFrontDoorRulesEngineRuleObject -Name rules1 -Priority 0 -Action $rulesEngineAction -MatchProcessingBehavior Stop -MatchCondition $rulesEngineMatchCondition
PS C:\> $rulesEngineRule1

Name                    : rules1
Priority                : 0
MatchProcessingBehavior : Stop
MatchConditions         : {Microsoft.Azure.Commands.FrontDoor.Models.PSRulesEngineMatchCondition}
Action                  : Microsoft.Azure.Commands.FrontDoor.Models.PSRulesEngineAction


PS C:\> $rulesEngineRule1.Action

RequestHeaderActions           ResponseHeaderActions RouteConfigurationOverride
--------------------           --------------------- --------------------------
{headeraction1, headeraction2} {}                    Microsoft.Azure.Commands.FrontDoor.Models.PSForwardingConfigurati…

PS C:\> $rulesEngineRule1.MatchConditions[0]

RulesEngineMatchVariable : RequestHeader
RulesEngineMatchValue    : {allowoverride}
Selector                 : Rules-Engine-Route-Forward
RulesEngineOperator      : Equal
NegateCondition          : False
Transform                : {Lowercase, Uppercase}

PS C:\> New-AzFrontDoorRulesEngine -ResourceGroupName myResourceGroup -FrontDoorName myFrontDoor -Name rulesEngine3 -Rule $rulesEngineRule1

Name         RulesEngineRules
----         ----------------
rulesEngine3 {rules1}

PS C:\> $rulesEngine3 = Get-AzFrontDoorRulesEngine -ResourceGroupName myResourceGroup -FrontDoorName myFrontDoor -Name rulesengine3
PS C:\> $rulesEngine3

Name         RulesEngineRules
----         ----------------
rulesEngine3 {rules1}

PS C:\> Get-AzFrontDoorRulesEngine -ResourceGroupName myResourceGroup -FrontDoorName myFrontDoor

Name         RulesEngineRules
----         ----------------
rulesEngine1 {Rule1}
rulesEngine2 {Rule1}
rulesEngine3 {rules1}

PS C:\> $rulesEngineRule2 = New-AzFrontDoorRulesEngineRuleObject -Name rules2 -Priority 3 -Action $rulesEngineAction
PS C:\> Set-AzFrontDoorRulesEngine -ResourceGroupName myResourceGroup -FrontDoor myFrontDoor -Name rulesEngine3 -Rule $rulesEngineRule1, $rulesEngineRule2

Name         RulesEngineRules
----         ----------------
rulesEngine3 {rules1, rules2}

PS C:\> $rulesEngine3 = Get-AzFrontDoorRulesEngine -ResourceGroupName myResourceGroup -FrontDoorName myFrontDoor -Name rulesengine3
PS C:\> Remove-AzFrontDoorRulesEngine -ResourceGroupName myResourceGroup -FrontDoorName myFrontDoor -Name $rulesEngine3.Name -PassThru
True
```

Adding rules engine configuration to routing rule. There is no change to how to update a front door's routing rules.
```
New-AzFrontDoorRoutingRuleObject -ResourceGroupName myResourceGroup -FrontDoorName myfrontdoor -Name routingrule2 -FrontendEndpointName myfrontendendpoint -ForwardingProtocol HttpsOnly -BackendPoolName mybackendpool -AcceptedProtocol Https -RulesEngineName rulesEngine2

FrontendEndpointIds : {/subscriptions/<subscriptionId>/resourceGroups/myResourceGroup/providers/Microsoft.Network/frontD
                      oors/myfrontdoor/FrontendEndpoints/myfrontendendpoint}
AcceptedProtocols   : {Https}
PatternsToMatch     : {/*}
HealthProbeSettings :
RouteConfiguration  : Microsoft.Azure.Commands.FrontDoor.Models.PSForwardingConfiguration
EnabledState        : Enabled
ResourceState       :
RulesEngineId       : /subscriptions/<subscriptionId>/resourceGroups/myResourceGroup/providers/Microsoft.Network/frontDo
                      ors/myfrontdoor/BackendPools/rulesEngine2
Id                  :
Name                : routingrule2
Type                :
```

Adding private link configuration to backend object. There is no change to how to update a front door's backends.
```
PS C:\> New-AzFrontDoorBackendObject -Address <address> -PrivateLinkAlias privatelinkalias -PrivateLinkApprovalMessage "Please approve me to use this private link"

Address                    : <address>
HttpPort                   : 80
HttpsPort                  : 443
Priority                   : 1
Weight                     : 50
BackendHostHeader          : <hostheader>
EnabledState               : Enabled
PrivateLinkAlias           : privatelinkalias
PrivateEndpointStatus      :
PrivateLinkApprovalMessage : Please approve me to use this private link
```
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by wyunchi-ms** [comment]
Hi @jessicl-ms , the CI failed. Please rerecord the test cases.

**Comment by jessicl-ms** [comment]
@wyunchi-ms I see that the Analyze linux/macOS/windows checks are failing with the below error, but am not sure how to resolve it. What is the issue the error is referring to?

```
WARNING : error encountered: Schema exception. This can occur when there are multiple code blocks in one example. /Users/runner/runners/2.166.3/work/1/s/artifacts/Debug/Az.FrontDoor/help/Get-AzFrontDoorRulesEngine.md:41:(227) '```powershell [/Users/runner/runners/2.166.3/work/1/s/build.proj]
PS C:\> Get-AzFrontDoorRulesEngine ...'
   Expect Heading
  ForEach-Object: /Users/runner/.local/share/powershell/Modules/platyPS/0.14.0/platyPS.psm1:1564
 Line |
  1564 |      $markdownFiles | ForEach-Object {
       |                       ~~~~~~~~~~~~~~~~
       | Exception calling "NodeModelToMamlModel" with "1" argument(s): "/Users/runner/runners/2.166.3/work/1/s/artifacts/Debug/Az.FrontDoor/help/Get-AzFrontDoorRulesEngine.md:41:(227) '```powershell PS C:\> Get-AzFrontDoorRulesEngine ...'  Expect Heading"
  
/Users/runner/runners/2.166.3/work/1/s/build.proj(207,5): error MSB3073: The command "pwsh -NonInteractive -NoLogo -NoProfile -Command "Set-Variable -Name ProgressPreference -Value 'SilentlyContinue';. /Users/runner/runners/2.166.3/work/1/s/tools//GenerateHelp.ps1 -ValidateMarkdownHelp -GenerateMamlHelp -BuildConfig Debug"" exited with code 1.
##[error]Error: The process '/usr/local/bin/dotnet' failed with exit code 1
Info: Azure Pipelines hosted agents have been updated to contain .Net Core 3.x (3.0 and 3.1) SDK/Runtime along with 2.1. Unless you have locked down a SDK version for your project(s), 3.x SDK might be picked up which might have breaking behavior as compared to previous versions. 
Some commonly encountered changes are: 
If you're using `Publish` command with -o or --Output argument, you will see that the output folder is now being created at root directory rather than Project File's directory. To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : 
Finishing: Generate Help
```

**Comment by jessicl-ms** [comment]
The https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md doc describes how to deal BreakingChangeIssues.csv, SignatureIssues.csv, and/or HelpIssues.csv  but the issues I seem to be having are ExtraAssemblies.csv, SharedAssemblyConflict.csv, and DependencyMap.csv. Is there a doc that explains how to resolve these kind of issues?

**Comment by jessicl-ms** [comment]
> The https://github.com/Azure/azure-powershell/blob/master/documentation/Debugging-StaticAnalysis-Errors.md doc describes how to deal BreakingChangeIssues.csv, SignatureIssues.csv, and/or HelpIssues.csv but the issues I seem to be having are ExtraAssemblies.csv, SharedAssemblyConflict.csv, and DependencyMap.csv. Is there a doc that explains how to resolve these kind of issues?

Figured it out the issue.

**Comment by wyunchi-ms** [comment]
Hi @jessicl-ms , we add some StatisAnalysis rules and the CI failed. Could you please take a look at the exceptions. And make some modification for your PR? Sorry for this.

**Pull request merged**
