### PR TITLE
Generate powershell cmdlets from latest swagger + add support for customer disk job creation

### PR DESCRIPTION
**Pull request by vaishnavi-janardhan**
## Description

Add support for customer disk import and export job creation

## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by msJinLei** [comment]
Please fix the following issues
```
  D:\a\_work\1\s\artifacts//StaticAnalysisResults\SignatureIssues.csv Errors
  "Module","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.DataBox","New-AzDataBoxCustomerDiskJobDetailsObject","New-AzDataBoxCustomerDiskJobDetailsObject","1","8100","New-AzDataBoxCustomerDiskJobDetailsObject Does not support ShouldProcess but the cmdlet verb New indicates that it should.","Determine if the cmdlet should implement ShouldProcess and if so determine if it should implement Force / ShouldContinue"


  "Az.DataBox","Update-AzDataBoxJob","1","5","Invalid_Cmdlet","5000","1","KekType is not a valid command name.","KekType         KekUrl                                           KekVaultResourceId","Check the spell of KekType."
  "Az.DataBox","Update-AzDataBoxJob","1","7","Invalid_Cmdlet","5000","1","CustomerManaged is not a valid command name.","CustomerManaged keyIdentifier /subscriptions/SubscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.KeyVault/vaults/keyVaultName","Check the spell of CustomerManaged."
  "Az.DataBox","Update-AzDataBoxJob","1","22","Invalid_Cmdlet","5000","1","Name is not a valid command name.","Name         Location Status        TransferType  SkuName IdentityType DeliveryType Detail","Check the spell of Name."
  "Az.DataBox","Update-AzDataBoxJob","1","24","Invalid_Cmdlet","5000","1","Powershell10 is not a valid command name.","Powershell10 WestUS   DeviceOrdered ImportToAzure DataBox UserAssigned NonScheduled Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.DataBoxJobDetails","Check the spell of Powershell10."
  "Az.DataBox","Update-AzDataBoxJob","2","5","Invalid_Cmdlet","5000","1","PrincipalId is not a valid command name.","PrincipalId                          TenantId                             Type","Check the spell of PrincipalId."
  "Az.DataBox","Update-AzDataBoxJob","2","7","Invalid_Cmdlet","5000","1","920850f5-9b6b-4017-a81a-3dcafe348be7 is not a valid command name.","920850f5-9b6b-4017-a81a-3dcafe348be7 72f988bf-86f1-41af-91ab-2d7cd011db47 SystemAssigned","Check the spell of 920850f5-9b6b-4017-a81a-3dcafe348be7."
  "Az.DataBox","Update-AzDataBoxJob","2","15","Invalid_Cmdlet","5000","1","PrincipalId is not a valid command name.","PrincipalId                          TenantId                             Type","Check the spell of PrincipalId."
  "Az.DataBox","Update-AzDataBoxJob","2","17","Invalid_Cmdlet","5000","1","920850f5-9b6b-4017-a81a-3dcafe348be7 is not a valid command name.","920850f5-9b6b-4017-a81a-3dcafe348be7 72f988bf-86f1-41af-91ab-2d7cd011db47 SystemAssigned","Check the spell of 920850f5-9b6b-4017-a81a-3dcafe348be7."
  "Az.DataBox","Update-AzDataBoxJob","2","21","Invalid_Cmdlet","5000","1","KekType is not a valid command name.","KekType         KekUrl                                           KekVaultResourceId","Check the spell of KekType."
  "Az.DataBox","Update-AzDataBoxJob","2","23","Invalid_Cmdlet","5000","1","CustomerManaged is not a valid command name.","CustomerManaged keyIdentifier /subscriptions/SubscriptionId/resourceGroups/resourceGroupName/providers/Microsoft.KeyVault/vaults/keyVaultName","Check the spell of CustomerManaged."

  Describing Get-AzDataBoxJob
    [-] Get 187ms
      ArgumentException: Missing Request 'Get-AzDataBoxJob+[NoContext]+Get+$GET+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellRandomm32r?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at Get-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 363
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Get-AzDataBoxJob.Tests.ps1: line 16

  Describing New-AzDataBoxJob
    [-] Import Job Test 67ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Import Job Test+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellnsgk?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 24
    [-] Import Job with managed disk 39ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Import Job with managed disk+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/managedDiskoykg?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 38
    [-] Export Job Test 47ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Export Job Test+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellExport81o9?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 54
    [-] Import Job UAI Test 51ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Import Job UAI Test+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellUAIlsr5?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 73
    [-] Schedule Job Test 20ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Schedule Job Test+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellScheduleeq1n?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 90
    [-] Create databox heavy order 14ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Create databox heavy order+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/PwshHeavyl1zu?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 107
    [-] Create disk order 26ms
      ArgumentException: Missing Request 'New-AzDataBoxJob+[NoContext]+Create disk order+$PUT+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/PwshDiskc2sx?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at New-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 785
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/New-AzDataBoxJob.Tests.ps1: line 121

  Describing Remove-AzDataBoxJob
    [-] Delete 24ms
      ArgumentException: Missing Request 'Remove-AzDataBoxJob+[NoContext]+Delete+$DELETE+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellnsgk?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at Remove-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 967
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Remove-AzDataBoxJob.Tests.ps1: line 16

Executing script /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Stop-AzDataBoxJob.Tests.ps1
Running 'playback' mode...
Using recording /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Stop-AzDataBoxJob.Recording.json

  Describing Stop-AzDataBoxJob
    [-] CancelExpanded 22ms
      ArgumentException: Missing Request 'Stop-AzDataBoxJob+[NoContext]+CancelExpanded+$POST+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellScheduleeq1n/cancel?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at Stop-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 1144
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Stop-AzDataBoxJob.Tests.ps1: line 16

  Describing Update-AzDataBoxJob
    [-] Microsoft managed to customer managed system assigned 30ms
      ArgumentException: Missing Request 'Update-AzDataBoxJob+[NoContext]+Microsoft managed to customer managed system assigned+$PATCH+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellRandomm32r?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at Update-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 1563
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Update-AzDataBoxJob.Tests.ps1: line 18
    [-] System assigned to user assigned 8ms
      ArgumentException: Missing Request 'Update-AzDataBoxJob+[NoContext]+System assigned to user assigned+$PATCH+https://management.azure.com/subscriptions/fa68082f-8ff7-4a25-95c7-ce9da541242f/resourceGroups/databox-pwsh-rg-7h/providers/Microsoft.DataBox/jobs/powershellRandomm32r?api-version=2022-12-01+1' in recording file (Parameter 'rqKey')
      at Update-AzDataBoxJob<Process>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/exports/ProxyCmdletDefinitions.ps1: line 1563
      at <ScriptBlock>, /mnt/vss/_work/1/s/artifacts/Debug/Az.DataBox/test/Update-AzDataBoxJob.Tests.ps1: line 25
```

**Comment by vaishnavi-janardhan** [comment]
@msJinLei, I have fixed the above mentioned issues. Can you please review the changes?

**Comment by msJinLei** [comment]
Please fix the example issue
```
  "Az.DataBox","New-AzDataBoxJob","1","32","Invalid_Cmdlet","5000","1","DataImportDetail is not a valid command name.","DataImportDetail           : {Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.DataImportDetails}","Check the spell of DataImportDetail."
  "Az.DataBox","New-AzDataBoxJob","1","33","Invalid_Cmdlet","5000","1","DeliveryPackage is not a valid command name.","DeliveryPackage            : Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.PackageShippingDetails","Check the spell of DeliveryPackage."
  "Az.DataBox","New-AzDataBoxJob","1","34","Invalid_Cmdlet","5000","1","DevicePassword is not a valid command name.","DevicePassword             :","Check the spell of DevicePassword."
  "Az.DataBox","New-AzDataBoxJob","1","35","Invalid_Cmdlet","5000","1","ExpectedDataSizeInTeraByte is not a valid command name.","ExpectedDataSizeInTeraByte : 0","Check the spell of ExpectedDataSizeInTeraByte."
  "Az.DataBox","New-AzDataBoxJob","1","36","Invalid_Cmdlet","5000","1","JobStage is not a valid command name.","JobStage                   :","Check the spell of JobStage."
  "Az.DataBox","New-AzDataBoxJob","1","37","Invalid_Cmdlet","5000","1","KeyEncryptionKey is not a valid command name.","KeyEncryptionKey           : Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.KeyEncryptionKey","Check the spell of KeyEncryptionKey."
  "Az.DataBox","New-AzDataBoxJob","1","38","Invalid_Cmdlet","5000","1","LastMitigationActionOnJob is not a valid command name.","LastMitigationActionOnJob  : Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.LastMitigationActionOnJob","Check the spell of LastMitigationActionOnJob."
  "Az.DataBox","New-AzDataBoxJob","1","39","Invalid_Cmdlet","5000","1","Preference is not a valid command name.","Preference                 : Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.Preferences","Check the spell of Preference."
  "Az.DataBox","New-AzDataBoxJob","1","40","Invalid_Cmdlet","5000","1","ReturnPackage is not a valid command name.","ReturnPackage              : Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.PackageShippingDetails","Check the spell of ReturnPackage."
  "Az.DataBox","New-AzDataBoxJob","1","41","Invalid_Cmdlet","5000","1","ReverseShipmentLabelSasKey is not a valid command name.","ReverseShipmentLabelSasKey :","Check the spell of ReverseShipmentLabelSasKey."
  "Az.DataBox","New-AzDataBoxJob","1","42","Invalid_Cmdlet","5000","1","ShippingAddress is not a valid command name.","ShippingAddress            : Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.ShippingAddress","Check the spell of ShippingAddress."
  "Az.DataBox","New-AzDataBoxJob","1","47","Invalid_Cmdlet","5000","1","AddressType is not a valid command name.","AddressType City          CompanyName Country PostalCode StateOrProvince StreetAddress1  StreetAddress2 StreetAddress3 ZipExtendedCode","Check the spell of AddressType."
  "Az.DataBox","New-AzDataBoxJob","1","49","Invalid_Cmdlet","5000","1","Commercial is not a valid command name.","Commercial  San Francisco             US      94107      CA              101 TOWNSEND ST","Check the spell of Commercial."
  "Az.DataBox","New-AzDataBoxJob","1","43","Unbinded_Expression","5014","1","Type DataBox is not explicitly assigned to a parameter.","DataBox","Assign DataBox explicitly to the parameter."
  "Az.DataBox","New-AzDataBoxJob","1","32","Invalid_Cmdlet","5000","1","Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.DataImportDetails is not a valid command name.","Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.DataImportDetails","Check the spell of Microsoft.Azure.PowerShell.Cmdlets.DataBox.Models.Api20210301.DataImportDetails."
```

**Review by msJinLei — CHANGES_REQUESTED** [review]
PreferenceStorageAccountAccessTierPreference

The following parameter is inconvenient for use. Can you improve.
- PreferenceStorageAccountAccessTierPreference
- ReverseShippingDetailShippingAddress
- ReverseTransportPreferencePreferredShipmentType
- TransportPreferencePreferredShipmentType

**Review by msJinLei — APPROVED** [review]

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
