### PR TITLE
update the help.xml via content development

### LINKED ISSUE #1136: Updated help.xml for ARM 1.0 Preview / AzureRM.Tags
@Azure/adx-sdk-team  - The newly authored and updated help.xml for the AzureRM.Tags is available here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_Tags\2015-10-20.09_38_28\OutPut\OnBox

Can you please add this to the code as it's the latest and greatest authored help file:

capture

### LINKED ISSUE #1160: Updated help.xml for ARM 1.0 Preview / AzureRM.UsageAggregates
A new fully-authored help.xml is available for this module.  Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_UsageAggregat\Latest\2015-10-23.10_34_18\OutPut\OnBox

capture

### LINKED ISSUE #1184: New help.xml for ARM 1.0 Preview / Azure Data Lake Analytics Module - AzureRM.DataLakeAnalytics
Hi @Azure/adx-sdk-team -

A help.xml is now available for the new Azure Data Lake Analytics module for ARM 1.0 Preview(Microsoft.Azure.Commands.DataLakeAnalytics.dll).  This is a brand new module, so no existing help.xml to diff against.

Since I'm unable to attach xmls, you can find the update file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_DataLkAnalyti\2015-10-27.15_42_48\OutPut\OnBox

capture

### LINKED ISSUE #1192: Updated help.xml for ARM 1.0 Preview / AzureRM.Profile
@Azure/adx-sdk-team  - A new fully-authored help.xml is available for the ARM 1.0 Preview profile module (.\Microsoft.Azure.Commands.Profile.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_Profile\Latest\2015-10-28.09_51_57\OutPut\OnBox

One important note:  Disable-AzureRmDataCollection  and Enable-AzureRmDataCollection are missing descriptions for what the cmdlets do.  This means that these areas are blank on MSDN and live:

https://msdn.microsoft.com/en-us/library/azure/mt619248.aspx

capture

Let me know if you have any questions.

### LINKED ISSUE #1201: Updated help.xml for ARM 1.0 Preview / AzureRM.Websites
@Azure/adx-sdk-team  - A new fully-authored help.xml is available for the Azure Websites module (.\Microsoft.Azure.Commands.Websites.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_Websites\Latest\2015-10-29.12_27_47\OutPut\OnBox

capture

Please let me know if you have any questions!

Thanks!

Tara

Please let me know if you have any questions!

### LINKED ISSUE #1202: New help.xml for ARM 1.0 Preview / Azure Api Management Module - AzureRM.ApiManagement
@Azure/adx-sdk-team  - A new fully-authored help.xml is available for the Azure Websites module (.\Microsoft.Azure.Commands.Websites.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_ApiManagement\Latest\2015-10-29.12_32_50\OutPut\OnBox

capture

Please let me know if you have any questions!

### LINKED ISSUE #1229: New help.xml for ARM 1.0 Preview / Azure Back up Module - AzureRM.Backup Module
@Azure/adx-sdk-team - A new fully-authored help.xml is available for the Azure Backup module (.\Microsoft.Azure.Commands.AzureBackup.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_AzureBackup\Latest\2015-11-02.14_50_28\OutPut\OnBox:

capture

Please let me know if you have any questions!

~Tara

### LINKED ISSUE #1240: New help.xml for ARM 1.0 Preview / Azure Operational Insights- AzureRM.OperationalInsights
@Azure/adx-sdk-team - A new fully-authored help.xml is available for the Azure Operational Insights module (.\Microsoft.Azure.Commands.OperationalInsights.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_OpsInsights\Latest\2015-11-05.14_21_27\OutPut\OnBox

capture

Thank you!

Tara

### LINKED ISSUE #1263: New help.xml for ARM 1.0 / Azure Automation Cmdlets - AzureRM.Automation
@Azure/adx-sdk-team - A new fully-authored help.xml is available for the Azure Automation module (.\Microsoft.Azure.Commands.ResourceManager.Automation.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\Azure_Auto_Resource\2015-11-09.12_47_49\OutPut\OnBox

capture

Thank you!

Tara

### LINKED ISSUE #1284: New help.xml for ARM 1.0 / Azure DNS / AzureRM.Dns
@Azure/adx-sdk-team - A new fully-authored help.xml is available for the Azure DNS module (.\Microsoft.Azure.Commands.Dns.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\Azure_DNS_Cmdlets\Latest\2015-11-12.10_51_44\OutPut\OnBox

capture

Thank you!

Tara

### LINKED ISSUE #1298: New help.xml for ARM 1.0 / Azure Traffic Manager - AzureRM.TrafficManager
@Azure/adx-sdk-team  - A new fully-authored help.xml is available for the Azure Traffic Manager module (.\Microsoft.Azure.Commands.TrafficManager.dll). Since I am unable to attach file because I do not have write permissions, you can find the help file here:

capture

\\wpshelpserver\cabs\AutomatedCabs\DxPowerShellBlue\1033\RMAzure_TrafficMgr\Latest\2015-11-16.10_35_31\OutPut\OnBox

Please let me know if you have questions!

Thanks!

Tara

### PR DESCRIPTION
**Pull request by devigned**
- resolve #1136 
- resolve #1160 
- resolve #1184 
- resolve #1192 
- resolve #1201 
- resolve #1202 
- resolve #1229 
- resolve #1240 
- resolve #1263 
- resolve #1284 
- resolve #1298

### CODE REVIEW

**Comment by markcowl** [comment]
@devigned Please fix merge conflicts

**Comment by markcowl** [comment]
@devigned still merge conflicts

**Comment by devigned** [comment]
@markcowl it should be good after the build passes. Please pull in at your leisure.

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/386/

**Comment by hovsepm** [comment]
sign: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/190/

**Pull request merged**
