### PR TITLE
Updating description of -DisableAutoregenerateKey

### PR DESCRIPTION
**Pull request by rahulamlekar**
Updating the description of -DisableAutoregenerateKey.

## Description

Updating the description of -DisableAutoregenerateKey.

## Checklist

- [ ] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cormacpayne** [comment]
@rahulamlekar Hey Rahul, before this PR can be merged, you will need to sign the Microsoft CLA. Please see the comment above from the CLA bot for more information on how to do so.

**Comment by erich-wang** [comment]
@rahulamlekar , 

[CLA assistant check](https://cla.opensource.microsoft.com/Azure/azure-powershell?pullRequest=9962) <br/>Thank you for your submission, we really appreciate it. Like many open source projects, we ask that you sign our [Contributor License Agreement](https://cla.opensource.microsoft.com/Azure/azure-powershell?pullRequest=9962) before we can accept your contribution.<br/><br/>:x: rahulamlekar [sign now](https://cla.opensource.microsoft.com/Azure/azure-powershell?pullRequest=9962)<br/><sub>You have signed the CLA already but the status is still pending? Let us [recheck](https://cla.opensource.microsoft.com/check/Azure/azure-powershell?pullRequest=9962) it.</sub>

**Comment by markcowl** [comment]
@rahulamlekar We will have to close this pull request without considering it if you do not sign the CLA

**Comment by erich-wang** [comment]
@rahulamlekar , close this PR since there is no response from you for 12 days.

**Pull request closed without merging**
