### PR TITLE
Az.Websites - Improvements for disaster recovery scenario cmdlets

### PR DESCRIPTION
**Pull request by nking-1**
## Description
This change adds some additional bug fixes and feature completeness for disaster recovery in Web Apps.

The Get-AzWebAppSnapshot has a new parameter to request for disaster recovery snapshots. Internally this just means that the request gets routed to a slightly different API.

The Restore-AzWebAppSnapshot cmdlet implementation has been modified to remove a dependency on the GetSite API. In our last disaster recovery drill, the cmdlet failed because of that dependency.

## Checklist

- [X] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [X] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by markcowl** [comment]
@Nking92 Can you please update this PR?  Let us know if you need any help with the failures

**Comment by Nking92** [comment]
@MiYanni I added the UseDisasterRecovery parameter to a test case for Get-AzWebAppSnapshot. I'm not sure why some of the checks are failing, but I'm looking into it.

**Comment by MiYanni** [comment]
@Nking92 You have a credscan match and a test failures:
```
Microsoft.Azure.Commands.Websites.Test.ScenarioTests.WebAppBackupRestoreTests.TestGetDeletedWebApp [FAIL]
        System.Management.Automation.RuntimeException : Assertion failed because the object is null: 
```

**Pull request merged**
