### PR TITLE
Updated ConnectionMonitorEndpoint cmdlet

### PR DESCRIPTION
**Pull request by irrogozh**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)

**Link on design spec: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/733**

    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@irrogozh 
Have already submit a cmdlet review [here](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues)?
Your PR contains a lot of breaking change, which cannot merge to master now. 
```
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.GetAzureNetworkWatcherConnectionMonitorCommand","Get-AzNetworkWatcherConnectionMonitor","0","3010","The property 'Filter' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'Filter' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.GetAzureNetworkWatcherConnectionMonitorCommand","Get-AzNetworkWatcherConnectionMonitor","0","3010","The property 'FilterText' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'FilterText' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointFilterItemObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject","0","1000","The cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject' has been removed and no alias was found for the original cmdlet name.","Add the cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject' back to the module, or add an alias to the original cmdlet name."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","3010","The property 'Filter' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'Filter' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","3010","The property 'FilterText' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'FilterText' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","2000","The cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' no longer supports the parameter 'FilterType' and no alias was found for the original parameter name.","Add the parameter 'FilterType' back to the cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject', or add an alias to the original parameter name."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","2000","The cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' no longer supports the parameter 'FilterItem' and no alias was found for the original parameter name.","Add the parameter 'FilterItem' back to the cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject', or add an alias to the original parameter name."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","1050","The parameter set '__AllParameterSets' for cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","1050","The parameter set 'SetByResourceId' for cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add parameter set 'SetByResourceId' back to cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","1050","The parameter set 'SetByAddress' for cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add parameter set 'SetByAddress' back to cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject'."
  
  
  D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv:
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.GetAzureNetworkWatcherConnectionMonitorCommand","Get-AzNetworkWatcherConnectionMonitor","0","3010","The property 'Filter' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'Filter' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.GetAzureNetworkWatcherConnectionMonitorCommand","Get-AzNetworkWatcherConnectionMonitor","0","3010","The property 'FilterText' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'FilterText' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointFilterItemObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject","0","1000","The cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject' has been removed and no alias was found for the original cmdlet name.","Add the cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointFilterItemObject' back to the module, or add an alias to the original cmdlet name."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","3010","The property 'Filter' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'Filter' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","3010","The property 'FilterText' of type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add the property 'FilterText' back to type 'Microsoft.Azure.Commands.Network.Models.PSNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","2000","The cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' no longer supports the parameter 'FilterType' and no alias was found for the original parameter name.","Add the parameter 'FilterType' back to the cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject', or add an alias to the original parameter name."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","2000","The cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' no longer supports the parameter 'FilterItem' and no alias was found for the original parameter name.","Add the parameter 'FilterItem' back to the cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject', or add an alias to the original parameter name."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","1050","The parameter set '__AllParameterSets' for cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","1050","The parameter set 'SetByResourceId' for cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add parameter set 'SetByResourceId' back to cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject'."
  "Microsoft.Azure.PowerShell.Cmdlets.Network.dll","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherConnectionMonitorEndpointObjectCommand","New-AzNetworkWatcherConnectionMonitorEndpointObject","0","1050","The parameter set 'SetByAddress' for cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject' has been removed.","Add parameter set 'SetByAddress' back to cmdlet 'New-AzNetworkWatcherConnectionMonitorEndpointObject'."
 ```
Let's do the cmdlet review first.

**Comment by irrogozh** [comment]
@msJinLei, I've already submitted design spec for updated cmdlets here: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/733
And you even reviewed it

**Comment by msJinLei** [comment]
https://github.com/Azure/azure-powershell/pull/12852

**Comment by msJinLei** [comment]
> @msJinLei, I've already submitted design spec for updated cmdlets here: [Azure/azure-powershell-cmdlet-review-pr#733](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/733)
> And you even reviewed it

Sorry not to remember it as review to many thing every day.

**Comment by msJinLei** [comment]
@irrogozh The PR is targeting to master branch, in which breaking change is not allowed. 
- If you want to release these breaking change feature. we can only release it with a OOB release rather than next regular release. You need to create a preview branch (or with an existing branch) to include this PR and request for a OOB release after next regular release.
- If you want to merge these commits to master, you need wait for the major release.

**Comment by msJinLei** [comment]
@irrogozh As @MikhailTryakhov asks to delete the network-june branch and create the branch of network-july, can you re-target this PR to network-july or close it?

**Comment by msJinLei** [comment]
closed since duplicate with https://github.com/Azure/azure-powershell/pull/12943

**Pull request closed without merging**
