### PR TITLE
Pass name of VM as ComputerName

### PR DESCRIPTION
**Pull request by demonix**
## Description

New-WAPackVM and New-WAPackQuickVM cmdlets don't pass computer name to WAP, and it is randomly generated. I'm not shure, if this was by design, but I've changed this to ComputerName = VmName. I think, this should not introduce any breaking changes in existing deployment scripts for WAP.

---
This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [x] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [x] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [ ] Title of the pull request is clear and informative.
- [ ] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [ ] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [ ] Pull request includes test coverage for the included changes.
- [ ] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [ ] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [ ] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [ ] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [ ] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [ ] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@demonix__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@demonix__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@demonix  Unfortunately, I don't believe there are any covering tests for these old APIs.  Looping in some members of the on premise team to validate.

**Comment by shahabhijeet** [comment]
@demonix this PR will be closed due to inactivity. Please reopen once you address the feedback.

**Comment by demonix** [comment]
Hi! What kind of feedback you are expecting from me? Mark wanted to talk with somebody about this PR. I thought we are waiting for him...
As for me, this change validated in my environment, and works well. 
I also think, that if sombody use scripts to change computer name automaticaly after vm deployment, than he still can do this without changing any scripts.

**Comment by cormacpayne** [comment]
@demonix Hey Dmitry, Mark has contacted the necessary people to try and get more information on who owns these cmdlets and who should be responsible for reviewing them, but he has gotten no response from the appropriate party. Mark will ping the group again and see if we can get any movement on this PR.

It looks like this PR was closed accidentally, so I will reopen.

**Comment by azurecla** [comment]
Hi __@demonix__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@demonix Here is a response from the WAPack team:  The VM Name is taken as computerName with ###, so that we can have VM with same name but different computer name. For example:
 
1.       VMName: testvm , computerName will be : testvm001
2.       VMName: testvm , computerName will be : testvm002
And so on.
 
This is taken care by WAP and hence WAPackcmdlet does not need to pass this explicitly. There is an option in the WAP plan which allows you to give computer Name which is different from VMName###. In any ways the change mentioned is not doing the above scenario.
 
If VM is created from template then, VM template defines the computer Name, and need not be passed explicitly.
 
Looking at the change it is not required as per the current WAP design. Could you please explain the scenario which needs this change ?

**Comment by markcowl** [comment]
@demonix Does this resolve your concerns and the need for this PR?  Otherwise, please elaborate on the scenario that this allows.

**Comment by sanjkum** [comment]
The VM Name is taken as computerName with ###, so that we can have VM with same name but different computer name. For example:
 
1.       VMName: testvm , computerName will be : testvm001
2.       VMName: testvm , computerName will be : testvm002
And so on.
 
This is taken care by WAP and hence WAPackcmdlet does not need to pass this explicitly. There is an option in the WAP plan which allows you to give computer Name which is different from VMName###. In any ways the change mentioned is not doing the above scenario.
 
If VM is created from template then, VM template defines the computer Name, and need not be passed explicitly.
 
Looking at the change it is not required as per the current WAP design. Could you please explain the scenario which needs this change ?

**Comment by demonix** [comment]
Hi, Mark! Thanks for digging into this.

The problems is that powershell api is not consistent with tenant web portal. While in portal we can see behaviour described above, in powershell computer name is taken from VM template (where we have asterisk, so it is always randomly generated).
I've looked at HTTP request to API endpoint and spotted, that ComputerName passed as null. I thought that was the issue, but I understand now it is somewhere deeper.

Looks like WAP tenant portal itself has some logic around computer naming, but api endpoint passes requests directly to SPF without any modifications.

I see now, this PR shouldn't be merged as is, because my change could break something, that relies on computer name specified in VM template. I've tried to find how to get plan settings, to emulate web portal behaviour, but can't find how to get them.

**Comment by markcowl** [comment]
@demonix Can you please file an issue here:  https://github.com/azure/azure-powershell/issues and we can ask the WAPack team about your request.

Closing for now, since the PR cannot be accepted.

**Pull request closed without merging**
