### PR TITLE
Updating the warning message to match that of portal UI

### PR DESCRIPTION
**Pull request by bganapa**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by deathly809** [comment]
@jacobb42 For review as well.

**Comment by deathly809** [comment]
@bganapa We need to update release notes to say "Only supported on 1810"

**Comment by bganapa** [comment]
@deathly809 ,@jacobb42 updated the message and release notes

**Comment by bganapa** [comment]
@mattbriggs Q raises another issue that there is no 1810 update release for azurestack, we are merging with 1811.. the release note should mention 1811 instead of 1810

**Comment by mattbriggs** [comment]
#sign-off

**Comment by bganapa** [comment]
ps-sign https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1521/

**Pull request merged**
