### PR TITLE
Update Network sdk version

### PR DESCRIPTION
**Pull request by sachethegde**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — CHANGES_REQUESTED** [review]
Please add the description item to Network's ChangeLog.md since there's nothing under upcoming release for now

**Comment by VeryEarly** [comment]
Hi @sachethegde ,

the current active branch for network PRs is network-august, could you please retarget or create a new PR against https://github.com/Azure/azure-powershell/tree/network-august?

**Comment by isra-fel** [comment]
Kindly ping @sachethegde

**Comment by msJinLei** [comment]
@sachethegde Since the network sdk version is updated to 20.3, we closes this PR. You can submit a new one if you want to continue your work.

**Pull request closed without merging**
