### PR TITLE
[Breaking change][Preview] New api version 20180710

### PR DESCRIPTION
**Pull request by viverm**
## New feature support for Azure Site Recovery.
Merge  Master to Az.RecoveryServices to avoid review for unnecessary changes

Preview Changes 
Cmdlet Review :: 
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/300#issuecomment-491092895

**Changes** 
* Azure Site Recovery Support to write to managed disk for vMWare to Azure. 
* Azure Site Recovery Support to NIC reduction for vMWare to Azure. 
* Azure Site Recovery Support to accelerated networking for Azure to Azure. 
* Azure Site Recovery Support to agent auto update for Azure to Azure. 
* Azure Site Recovery Support to Standard SSD for Azure to Azure. 
* Azure Site Recovery Support to Azure Disk Encryption two pass for Azure to Azure. 
* Azure Site Recovery Support to protect newly added disk for Azure to Azure.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@viverm What is the status on this PR? There hasn't been activity for over a week.

**Comment by markcowl** [comment]
@viverm Please make changes here, or we will close on 5/23

**Comment by cormacpayne** [comment]
Temporarily closing this PR. Feel free to re-open this PR when you're able to resolve the build issues.

**Comment by viverm** [comment]
https://github.com/Azure/azure-powershell/pull/9304

**Pull request closed without merging**
