### PR TITLE
Update functions module

### PR DESCRIPTION
**Pull request by markcowl**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by markcowl** [comment]
actual run is here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=178680&view=results

**Comment by markcowl** [comment]
actual run is here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=178704&view=results

**Comment by markcowl** [comment]
actual run is here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=178829&view=results

**Comment by markcowl** [comment]
actual run is here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=179882&view=results

**Comment by markcowl** [comment]
signed run is here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=180040&view=results

**Comment by markcowl** [comment]
New functions build is here: https://dev.azure.com/azure-sdk/internal/_build/results?buildId=182493&view=results

**Comment by brettmillerb** [comment]
@markcowl This release appears to have added a wildcard to the CmdletsToExport as part of the module manifest upon build which means i get all private functions exported.

```powershell
CommandType     Name                                               Version    Source
-----------     ----                                               -------    ------
Function        AddFunctionAppPlanWorkerType                       0.0.1      az.functions
Function        AddFunctionAppSettings                             0.0.1      az.functions
Function        CreateObjectFromPipeline                           0.0.1      az.functions
Function        Get-AzFunctionApp                                  0.0.1      az.functions
Function        Get-AzFunctionAppAvailableLocation                 0.0.1      az.functions
Function        Get-AzFunctionAppPlan                              0.0.1      az.functions
Function        GetApplicationInsightsProject                      0.0.1      az.functions
Function        GetConnectionString                                0.0.1      az.functions
Function        GetErrorMessage                                    0.0.1      az.functions
Function        GetFunctionAppPlans                                0.0.1      az.functions
Function        GetFunctionApps                                    0.0.1      az.functions
Function        GetLinuxFxVersion                                  0.0.1      az.functions
Function        GetRuntimeName                                     0.0.1      az.functions
Function        GetRuntimeVersion                                  0.0.1      az.functions
Function        GetServicePlan                                     0.0.1      az.functions
Function        GetSkuName                                         0.0.1      az.functions
Function        GetStorageAccount                                  0.0.1      az.functions
Function        New-AzFunctionApp                                  0.0.1      az.functions
Function        New-AzFunctionAppPlan                              0.0.1      az.functions
Function        NewAppSetting                                      0.0.1      az.functions
Function        NormalizeSku                                       0.0.1      az.functions
Function        Remove-AzFunctionApp                               0.0.1      az.functions
Function        Remove-AzFunctionAppPlan                           0.0.1      az.functions
Function        Restart-AzFunctionApp                              0.0.1      az.functions
Function        Start-AzFunctionApp                                0.0.1      az.functions
Function        Stop-AzFunctionApp                                 0.0.1      az.functions
Function        Test-Az                                            0.0.1      az.functions
Function        ThrowTerminatingError                              0.0.1      az.functions
Function        ValidateConsumptionPlanLocation                    0.0.1      az.functions
Function        ValidateFunctionName                               0.0.1      az.functions
Function        ValidateLocation                                   0.0.1      az.functions
Function        ValidateRuntime                                    0.0.1      az.functions
```
I cant see the wildcard in the PR or the source code from the artifacts on the release page either so not sure when this is added 🤷‍♂ 
```
  CmdletsToExport = 'Get-AzFunctionApp', 'Get-AzFunctionAppAvailableLocation', 'Get-AzFunctionAppPlan', 'New-AzFunctionApp', 'New-AzFunctionAppPlan', 'Remove-AzFunctionApp', 'Remove-AzFunctionAppPlan', 'Restart-AzFunctionApp', 'Start-AzFunctionApp', 'Stop-AzFunctionApp', '*'
```

**Pull request merged**
