### PR TITLE
[Network] New-AzNetworkWatcherPacketCapture - TotalBytesPerSession with incorrect data type

### PR DESCRIPTION
**Pull request by v-sapanchal**
## Description

 https://github.com/Azure/azure-powershell/issues/16061

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by msJinLei** [comment]
@v-sapanchal it is a breaking change to change the range of the input parameter
```
  "Module","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Az.Network","Microsoft.Azure.Commands.Network.GetAzureNetworkWatcherPacketCaptureCommand","Get-AzNetworkWatcherPacketCapture","0","3030","The generic type for 'property TotalBytesPerSession' has been changed from 'System.Nullable`1[System.Int32]' to 'System.Nullable`1[System.UInt32]'. ","Change the generic type for 'property TotalBytesPerSession' back to 'System.Nullable`1[System.Int32]'."
  "Az.Network","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherPacketCaptureCommand","New-AzNetworkWatcherPacketCapture","0","3030","The generic type for 'property TotalBytesPerSession' has been changed from 'System.Nullable`1[System.Int32]' to 'System.Nullable`1[System.UInt32]'. ","Change the generic type for 'property TotalBytesPerSession' back to 'System.Nullable`1[System.Int32]'."
  "Az.Network","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherPacketCaptureCommand","New-AzNetworkWatcherPacketCapture","0","3030","The generic type for 'parameter TotalBytesPerSession' has been changed from 'System.Nullable`1[System.Int32]' to 'System.Nullable`1[System.UInt32]'. ","Change the generic type for 'parameter TotalBytesPerSession' back to 'System.Nullable`1[System.Int32]'."
  "Az.Network","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherPacketCaptureCommandV2","New-AzNetworkWatcherPacketCaptureV2","0","3030","The generic type for 'property TotalBytesPerSession' has been changed from 'System.Nullable`1[System.Int32]' to 'System.Nullable`1[System.UInt32]'. ","Change the generic type for 'property TotalBytesPerSession' back to 'System.Nullable`1[System.Int32]'."
  "Az.Network","Microsoft.Azure.Commands.Network.NewAzureNetworkWatcherPacketCaptureCommandV2","New-AzNetworkWatcherPacketCaptureV2","0","3030","The generic type for 'parameter TotalBytesPerSession' has been changed from 'System.Nullable`1[System.Int32]' to 'System.Nullable`1[System.UInt32]'. ","Change the generic type for 'parameter TotalBytesPerSession' back to 'System.Nullable`1[System.Int32]'."
```

**Comment by isra-fel** [comment]
As we discussed it's an exception to introduce a breaking change to fix a broken behavior, so please follow [Debugging-StaticAnalysis-Errors.md](https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md) and suppress the warning messages of the breaking change analyzer.

**Comment by isra-fel** [comment]
Kindly ping @v-sapanchal

**Comment by v-sapanchal** [comment]
I am just following this [Debugging-StaticAnalysis-Errors.md](https://github.com/Azure/azure-powershell/blob/main/documentation/Debugging-StaticAnalysis-Errors.md) to suppress these warnings.

**Review by msJinLei — APPROVED** [review]

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
