### PR TITLE
Polish changelog

### PR DESCRIPTION
**Pull request by dingmeng-xue**
## Description
Polish changelog for upcoming release

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Dingmeng, I'm thinking about now that we've set some rules to write changelog, we can list them in

1. PR template
1. the header of each changelog.md e.g. https://raw.githubusercontent.com/Azure/azure-powershell/7b601cbcf3a2727e8903d0b3a0418ec7413f132d/src/Accounts/Accounts/ChangeLog.md

**Comment by dingmeng-xue** [comment]
Excellent suggestion. You know what, I’m not good expert in writing examples in English. So, hesitate how to start it.

Thanks,
Dingmeng

**Pull request merged**
