### PR TITLE
[Redis] Add support for `2022-06-01` API version

### PR DESCRIPTION
**Pull request by austintolani**
## Description

This PR adds supports for a new API version for Azure Cache for Redis (2022-06-01). Specifically, these changes include:
- Upgrading `Microsoft.Azure.Management.Redis` package to new version `9.0.0`, which updates all requests to use the new `2022-06-01` API version. Notably this package is updated to use a private NuGet feed, since this is a Track 1 SDK and is no longer being updated publicly. 
- `Import-AzRedisCache` and `Export-AzRedisCache` has a new optional parameter `PreferredDataArchiveAuthMethod`. 
- Linked server deletion (`Remove-AzRedisCacheLink`) is now a long running operation, so its implementation now calls `BeginDelete()` instead of `Delete()`. 
- Updating a cache (`Set-AzRedisCache`) is now a long running operation so its implementation now calls `BeginUpdate()` instead of `Update()`.
- `Get-AzRedisCacheLink` and `New-AzRedisCacheLink` will show 4 additional properties for a geo replication link: `PrimaryHostName`, `GeoReplicatedPrimaryHostName`, `ServerRole` and `LinkedRedisCacheLocation`. 
- Relevant updates to help documentation
- Relevant updates to tests
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by austintolani** [comment]
@msJinLei I have been trying to get the pipelines to pass but am facing issues. The tests are passing on my local machine but it seems like there is some environment issue causing differing behavior between my local environment and the pipelines. 

We would like for these changes to go out in the [Jan release](https://github.com/Azure/azure-powershell/milestone/142). Would it be possible for you to review this PR while I continue to try to solve the pipeline issues so that when they pass we will able to merge it in in time for the Jan release?

**Comment by austintolani** [comment]
@msJinLei All pipelines are now passing. As mentioned in previous comment, we would like for these changes to go out in the [Jan release](https://github.com/Azure/azure-powershell/milestone/142). Please let me know if there are any additional steps I can take on my end with this PR. Thanks!

**Review by dingmeng-xue — APPROVED** [review]

**Review by dingmeng-xue — APPROVED** [review]

**Pull request merged**
