### PR TITLE
Ignore user input for elastic pool's StorageMB and recalculate

### PR DESCRIPTION
**Pull request by hungmai-msft**
Ignore user input for elastic pool's StorageMB and recalculate based on Dtu and coefficient of the edition

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hungmai-msft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hungmai). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/88/

**Comment by stankovski** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/111/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/415/

**Comment by stankovski** [comment]
@hungmai-msft please pull from "upstream dev" and update your fork

**Comment by hungmai-msft** [comment]
@stankovski I will do it later today. Is it possible to have this in the next release on 8/12? This is a hotfix for the release last week.

**Comment by hungmai-msft** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/118/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/417/

**Comment by markcowl** [comment]
rerun of on-demand run:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/135/

**Comment by markcowl** [comment]
@hungmai-msft Hi Hung Mai, please resubmit this PR against the release branch (release-0.9.7).  We will take the PR, we just6 needed to put out a release candidate for partner testing.

**Comment by markcowl** [comment]
@hungmai-msft Closing in favor of the new PR #749

**Pull request closed without merging**
