### PR TITLE
Upgrade storage client library to 6.1

### PR DESCRIPTION
**Pull request by EmmaZhu**
1. Upgrade storage client library to 6.1.0 from 6.0.0
2. Change DMLib library according to the XSCL upgrade.
3. Change help for Get-AzureStorageFile according to cmdlet behavior change.

### CODE REVIEW

**Comment by markcowl** [comment]
@EmmaZhu Looks like you will need to update the assembly version for all consumers of commands.common.storage

**Comment by hovsepm** [comment]
@EmmaZhu , There are also older versions of Storage client that are used in other projects. Please update them as well. Here is the list - https://github.com/hovsepm/azure-powershell/commit/119d5de49021bcc5f5ca387d6bd1867d7d3fda82

**Comment by EmmaZhu** [comment]
These projects don't depend on Commands.Common.Storage, and HDInsight team used to claim that it has hard dependency on 4.3 version of WindowsAzure.Storage client library. Could you confirm whether I really need to upgrade them?

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/445/

**Comment by hovsepm** [comment]
msi: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/216/

**Comment by hovsepm** [comment]
new on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/447/

**Pull request merged**
