### PR TITLE
Fixes Docker image being out-of-date

### PR DESCRIPTION
**Pull request by MiYanni**
## Description

Fixes: https://github.com/Azure/azure-powershell/issues/7286

I believe the Docker image name used to be `microsoft/powershell`. But, according to their [docker page](https://hub.docker.com/r/microsoft/powershell/), it is now `mcr.microsoft.com/powershell`. Hopefully, this fixes our Docker image.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
Tested. It fixes the issue with the container being wrong. However, there is another issue where the module seems to be missing our ADAL dll. That can be addressed in a separate issue. Here's what I ran:

```powershell
docker pull azuresdk/azure-powershell-core:dockerimage-fix
docker run -it azuresdk/azure-powershell-core:dockerimage-fix pwsh


PS /usr/local/share/powershell/Modules/Az.Profile> ls
Az.Profile.psd1                                 Microsoft.Azure.Commands.Profile.types.ps1xml                  Microsoft.Azure.PowerShell.Common.dll           Microsoft.Azure.PowerShell.Storage.Management.dll      Microsoft.WindowsAzure.Storage.dll
Az.Profile.psm1                                 Microsoft.Azure.Common.dll                                     Microsoft.Azure.PowerShell.Compute.dll          Microsoft.Azure.PowerShell.Strategies.dll              NetCoreAssemblies
Hyak.Common.dll                                 Microsoft.Azure.PowerShell.Aks.dll                             Microsoft.Azure.PowerShell.Graph.Rbac.dll       Microsoft.Azure.PowerShell.Websites.dll                PreloadAssemblies
Microsoft.ApplicationInsights.dll               Microsoft.Azure.PowerShell.Authentication.Abstractions.dll     Microsoft.Azure.PowerShell.KeyVault.dll         Microsoft.Rest.ClientRuntime.Azure.Authentication.dll
Microsoft.Azure.Commands.Profile.deps.json      Microsoft.Azure.PowerShell.Authentication.dll                  Microsoft.Azure.PowerShell.Network.dll          Microsoft.Rest.ClientRuntime.Azure.dll
Microsoft.Azure.Commands.Profile.dll            Microsoft.Azure.PowerShell.Authentication.ResourceManager.dll  Microsoft.Azure.PowerShell.ResourceManager.dll  Microsoft.Rest.ClientRuntime.dll
Microsoft.Azure.Commands.Profile.format.ps1xml  Microsoft.Azure.PowerShell.Authorization.dll                   Microsoft.Azure.PowerShell.Storage.dll          Microsoft.WindowsAzure.Storage.DataMovement.dll
PS /usr/local/share/powershell/Modules/Az.Profile> Import-Module Az.Profile
Import-Module : Could not load file or assembly 'Microsoft.IdentityModel.Clients.ActiveDirectory, Version=3.14.0.8, Culture=neutral, PublicKeyToken=31bf3856ad364e35'. The system cannot find the file specified.
At line:1 char:1
+ Import-Module Az.Profile
+ ~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : NotSpecified: (:) [Import-Module], FileNotFoundException
+ FullyQualifiedErrorId : System.IO.FileNotFoundException,Microsoft.PowerShell.Commands.ImportModuleCommand
```

**Comment by alexandair** [comment]
@MiYanni 
azuresdk/azure-powershell-core:latest still wants to run pwsh-preview at start. so the container hangs if you don't specify pwsh with docker run.

**Comment by MiYanni** [comment]
@alexandair 
The term `pwsh-preview` doesn't exist in this codebase. So, it isn't any kind of configuration from our side. Have you tried `mcr.microsoft.com/powershell` to see if the issue occurs there?

**Comment by alexandair** [comment]
I just know that I've just pulled the newer image with the "latest" tag and that image doesn't work by default. It wants to run "pwsh-preview" because this is what we did with the RC version of PowerShell Core. Now, that image uses the stable version, but somewhere in the Dockerfile used to build the image, CMD line still says pwsh-preview. I don't have another explanation why it behaves like that.

**Comment by MiYanni** [comment]
@alexandair 
Does `mcr.microsoft.com/powershell` map to `mcr.microsoft.com/powershell:latest`? That's the only way that this shouldn't work correctly. Our entire Dockerfile is:
https://github.com/Azure/azure-powershell/blob/7336b4310813755142f317ff40a63a3d9d78873a/Dockerfile#L1-L6

I could try updating it to `mcr.microsoft.com/powershell:latest` instead. But, my understanding is that the `:latest` shouldn't be required.

**Pull request merged**
