### PR TITLE
Add readable secondary parameter to Invoke-AzureSqlDatabaseFailover

### PR DESCRIPTION
**Pull request by emgu-ms**
## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [X] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by emgu-ms** [comment]
Build errors are due to:
InstanceActiveDirectoryAdministrator/Services/AzureSqlInstanceActiveDirectoryAdministratorCommunicator.cs(72,20): error CS1929: 'IManagedInstanceAdministratorsOperations' does not contain a definition for 'Get' and the best extension method overload 'DatabasesOperationsExtensions.Get(IDatabasesOperations, string, string, string)' requires a receiver of type 'IDatabasesOperations' [/Users/runner/runners/2.163.1/work/1/s/src/Sql/Sql/Sql.csproj] [/Users/runner/runners/2.163.1/work/1/s/build.proj]
InstanceActiveDirectoryAdministrator/Services/AzureSqlInstanceActiveDirectoryAdministratorCommunicator.cs(88,20): error CS1929: 'IManagedInstanceAdministratorsOperations' does not contain a definition for 'CreateOrUpdate' and the best extension method overload 'DatabasesOperationsExtensions.CreateOrUpdate(IDatabasesOperations, string, string, string, Database)' requires a receiver of type 'IDatabasesOperations' [/Users/runner/runners/2.163.1/work/1/s/src/Sql/Sql/Sql.csproj] [/Users/runner/runners/2.163.1/work/1/s/build.proj]
InstanceActiveDirectoryAdministrator/Services/AzureSqlInstanceActiveDirectoryAdministratorCommunicator.cs(96,13): error CS1929: 'IManagedInstanceAdministratorsOperations' does not contain a definition for 'Delete' and the best extension method overload 'DatabasesOperationsExtensions.Delete(IDatabasesOperations, string, string, string)' requires a receiver of type 'IDatabasesOperations' [/Users/runner/runners/2.163.1/work/1/s/src/Sql/Sql/Sql.csproj] [/Users/runner/runners/2.163.1/work/1/s/build.proj]

Powershell AzureSqlInstanceActiveDirectoryAdministratorCommunicator.cs is trying to access methods that don't exist in IManagedInstanceAdministratorsOperations.  Seems to be due to the change in Sql.csproj where i'm going from 1.36.0-preview to 1.37.0-preview.  @SanjaMalesevic to see if maybe she knows.

**Comment by emgu-ms** [comment]
Talked to @SanjaMalesevic offline.  She has a changeset to fix this already but it needs a some security additions before it can be merged into master.  I will follow up on this PR after the changeset has gone into master

**Comment by isra-fel** [comment]
@emgu-ms let us know when this PR is ready for review please.
P.S. there's a merge conflict

**Comment by isra-fel** [comment]
@emgu-ms feel free to reopen when you get back to work. Thanks

**Comment by emgu-ms** [comment]
@isra-fel l These changes are ready to be merged :)

**Pull request merged**
