### PR TITLE
Create Unregister-AzResourceProvider Cmdlet

### PR DESCRIPTION
**Pull request by diwudd**
Create Unregister-AzResourceProvider Cmdlet

### CODE REVIEW

**Comment by diwudd** [comment]
Thank you for the review. Addressed the comments, can you please take another look?

Thanks,

Di

**Comment by diwudd** [comment]
Thank you. Updated the help markdown.

Thanks,

Di

**Comment by VeryEarly** [comment]
Hi @diwudd ,

Please check this log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=442786&view=logs&jobId=b17395f6-68a3-5682-0476-d3f6f1043109&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0

those failed test cases need to be re-recorded due to the SDK upgrade.

**Comment by diwudd** [comment]
> Hi @diwudd ,
> 
> Please check this log: https://dev.azure.com/azure-sdk/public/_build/results?buildId=442786&view=logs&jobId=b17395f6-68a3-5682-0476-d3f6f1043109&j=b17395f6-68a3-5682-0476-d3f6f1043109&t=67f633ab-4360-5839-af42-f446e0c847f0
> 
> those failed test cases need to be re-recorded due to the SDK upgrade.

Thank you. Re-recorded the failed tests.

**Pull request merged**
