### PR TITLE
PeerAddressType functionality for Private Peering and IgnoreCase

### PR DESCRIPTION
**Pull request by kilobyte97**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by kilobyte97** [comment]
can I resolve the merge

**Comment by VeryEarly** [comment]
Hi @number213 ,

Can please you help verify this PR?

**Comment by kilobyte97** [comment]
any update ? is anything needed on my end ?

**Comment by VeryEarly** [comment]
> any update ? is anything needed on my end ?

What is your release plan? This branch is targeting at August release.

**Comment by kilobyte97** [comment]
I would prefer it in the earliest possible release. I believe that I could onboard these onto june-release. Let me know

**Comment by VeryEarly** [comment]
> I would prefer it in the earliest possible release. I believe that I could onboard these onto june-release. Let me know

earliest release would be 2020-07-14, if you want to go with this release, please target PR to master branch

**Comment by kilobyte97** [comment]
is it possible to do that here or do I have to raise a new pull request ?
I didn't find the option to change the target branch. hence raised another PR.

**Pull request closed without merging**
