### PR TITLE
When turning off Advanced Threat Protection, delete Vulnerability Assessment policy

### PR DESCRIPTION
**Pull request by talhers**
## Description

When turning off Advanced Threat Protection, Vulnerability Assessment policy is deleted. Vulnerability Assessment is a part of the Advanced Threat Protection (ATP) package, and thus needs to be deleted when ATP is turned off.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
@jaredmoo @yaakoviyun Hey guys, would one of you mind taking a look at this PR?

**Comment by jaredmoo** [comment]
Is azure:master the correct branch to merge into?

**Comment by cormacpayne** [comment]
@jaredmoo if this is intended to go into the `Az` module, then yes. We changed the default development branch in our repository to `master` on Friday 😀

**Comment by talhers** [comment]
> Why does this logic need to exist in PowerShell? If automatically deleting VA policy should happen in general, then that should be implemented on the server side. If automatic deleting should not happen, then why is PowerShell UX different?

You are right. But we're in an interim situation where atp and threat detection on flags are conflated. We want to fix this (ie, atp will have its own on/off switch), but until we do that we're enforcing this in UI and cmdlets only (So as not to disable VA when threat detection is disabled).
We have a task to fix this.

**Pull request closed without merging**
