### PR TITLE
SQL VM IaaS Extension fixes and AKV Support

### PR DESCRIPTION
**Pull request by OJDUDE**
1. The AutoBackup feature includes private settings in the public
   settings section.  The fix was to add a public settings class that is
   used to manage the AutoBackup settings in the set and get command.
   The change does not impact the cmdlet interface or the objects used to
   configure AutoBackup. The change is internal to the feature
   implementation.The AutoBackup syntax command is still the same. 2. SQL VM Azure key Vault Integration
   This is a new feature is added to configure SQL Connector to access
   Azure Key Vault on a SQL IaaS VM. The feature is only available for SQL
   Server 2012 and higher version. A new set of classes is added to manage
   Collecting the Azure Key Vault settings and new SQL credential settings.
   The user would provide the key vault url, principal name and secret and
   the SQL credential name. The user can enable \ disable the feature
   Using the Enable switch option. By default the feature is disabled. Get-AzureVM -ServiceName $serviceName -Name $vmName |
   Set-AzureVMSqlServerExtension -KeyVaultCredentialSettings $akvs |
   Update-AzureVM

The change also update the extension status. The status output now
includes the KeyVaultSettings object
Get-AzureVM -ServiceName $serviceName -Name $vmName |
Get-AzureVMSqlServerExtension

The following is a sample output of the get command
ExtensionName              : SqlIaaSAgent
Publisher                  : Microsoft.SqlServer.Management
Version                    : 1.*
State                      : Enable
RoleName                   : afexttest
AutoPatchingSettings       :
Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.Extensions.AutoPatchingSettings
AutoBackupSettings         :
Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.Extensions.AutoBackupSettings
KeyVaultCredentialSettings :
Microsoft.WindowsAzure.Commands.ServiceManagement.IaaS.Extensions.KeyVaultCredentialSettings

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@OJDUDE__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@OJDUDE please pull from upstream and resolve conflicts

**Comment by OJDUDE** [comment]
This is now update and all conflicts resolved

**Comment by ogail** [comment]
@azuresdkci add to whitelist

**Comment by OJDUDE** [comment]
Thanks for the update

**Comment by markcowl** [comment]
@OJDUDE This has merge conflicts - can you please update?

**Comment by markcowl** [comment]
@OJDUDE If you are an ms employee, please add yopurself to the organization.  If you are not, please sign the CLA

**Comment by azurecla** [comment]
__@OJDUDE__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by markcowl** [comment]
@OJDUDE Are you plannign to update this PR< or should I close it?

**Comment by OJDUDE** [comment]
Why are you planning to close it. The Azure CLA process is the reason I got delayed not me. I will be updating. We need this for the September release. Don't close it.

**Comment by OJDUDE** [comment]
Why are you planning to close it. The Azure CLA process is the reason I got delayed not me. I will be updating. We need this for the September release. Don't close it.

**Comment by OJDUDE** [comment]
I have just updated due a single conflict in the setup files. This always happens and auto merge fails on it. Can you please merge the change.

**Comment by OJDUDE** [comment]
The PR is updated. If you could please merge it.

Thanks,
Omar

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by OJDUDE** [comment]
Thanks Mark for following up on this on your day off.

**Comment by OJDUDE** [comment]
Could you please test and merge this change please.

**Comment by OJDUDE** [comment]
Branch is updated. This is a comment to trigger the test.

**Pull request merged**
