### PR TITLE
Update *Resource, *ResourceGroupDeployment and *Lock parameters to support piping

### PR DESCRIPTION
**Pull request by ravbhatnagar**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ravbhatnagar__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci  test this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Pull request merged**
