### PR TITLE
Removing flags which are not supported by azure-chef-extension now

### PR DESCRIPTION
**Pull request by NimishaS**
Following flags are not supported now: `AutoUpdateChefClient`, `DeleteChefConfig` and `UninstallChefClient`

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@NimishaS__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by NimishaS** [comment]
Sanity testing is done. Need to do some more testing.

**Comment by NimishaS** [comment]
Done with testing.

**Comment by markcowl** [comment]
@Nimishas would you make sure to verify that this cmdlet is actually shipping with the Comute module, when we push out the installer.  It was excluded at some poitn in the past.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/967/

**Pull request merged**
