### PR TITLE
Update WAF Sdk to support RequestBodyCheck and JSON exclussions

### PR DESCRIPTION
**Pull request by digavino**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@digavino please fix the compilation error

```
D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
      0 Warning(s)
      2 Error(s)

```

**Comment by digavino** [comment]
> @digavino please fix the compilation error
> 
> ```
> D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
>       0 Warning(s)
>       2 Error(s)
> ```

I know, I'm waiting to get signed off in the SDK change so the package will exist outside my local repository. Will post again as soon as that is done. This is the PR for that (just fyi) - https://github.com/Azure/azure-sdk-for-net/pull/18150

**Comment by msJinLei** [comment]
> > @digavino please fix the compilation error
> > ```
> > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> >       0 Warning(s)
> >       2 Error(s)
> > ```
> 
> I know, I'm waiting to get signed off in the SDK change so the package will exist outside my local repository. Will post again as soon as that is done. This is the PR for that (just fyi) - [Azure/azure-sdk-for-net#18150](https://github.com/Azure/azure-sdk-for-net/pull/18150)

Next time, you can create the PR as draft initially and set it ready to review then the sdk is ready.

**Comment by digavino** [comment]
> > > @digavino please fix the compilation error
> > > ```
> > > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor\FrontDoor.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: Unable to find package Microsoft.Azure.Management.FrontDoor with version (>= 4.0.0) [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 9 version(s) in nuget.org [ Nearest version: 3.0.0 ] [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in Microsoft Visual Studio Offline Packages [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in local-feed [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in dotnet-core [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > > D:\a\1\s\src\FrontDoor\FrontDoor.Test\FrontDoor.Test.csproj : error NU1102: - Found 0 version(s) in myget-azure-powershell [D:\a\1\s\artifacts\Azure.PowerShell.sln] [D:\a\1\s\build.proj]
> > >       0 Warning(s)
> > >       2 Error(s)
> > > ```
> > 
> > 
> > I know, I'm waiting to get signed off in the SDK change so the package will exist outside my local repository. Will post again as soon as that is done. This is the PR for that (just fyi) - [Azure/azure-sdk-for-net#18150](https://github.com/Azure/azure-sdk-for-net/pull/18150)
> 
> Next time, you can create the PR as draft initially and set it ready to review then the sdk is ready.

Sorry about that. The error is now fixed (the new DLL is published by now).

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
