### PR TITLE
Update to USGovernmentActiveDirectoryEndpoint

### PR DESCRIPTION
**Pull request by BernieEllis**
## Description

Updated the USGovernmentActiveDirectoryEndpoint from login-us.microsoftonline.com to login.microsoftonline.us in AzureEnvironmentConstants.

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [ Yes] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md).**
- [N/A ] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/preview/documentation/help-generation.md).**
- [N/A] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#general-guidelines)
- [Yes] Title of the pull request is clear and informative.
- [Yes] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/preview/documentation/cleaning-up-commits.md).
- [No breaking changes] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#testing-guidelines)
- [N/A] Pull request includes test coverage for the included changes.
- [N/A] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [N/A] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://github.com/Azure/azure-powershell/wiki/PowerShell-Cmdlet-Design-Guidelines#supportsshouldprocess).
- [N/A] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [N/A] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [N/A] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [N/A] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by cormacpayne** [comment]
@azuresdkci test this please

**Comment by cormacpayne** [comment]
@bernie-msft thanks for the PR, Bernarldo. This looks good to me, we just need to do some light validation on our side to ensure both endpoints work.

As a note to myself, the URL has changed, but the old one will continue to be supported moving forward, according to [this article](https://docs.microsoft.com/en-us/azure/azure-government/documentation-government-developer-guide):

_The Active Directory Authority for Azure Government has changed from https://login-us.microsoftonline.com to https://login.microsoftonline.us. The original URL will continue to work but all applications should be updated to the new authority URL._

**Comment by markcowl** [comment]
optimistic on-demand run here: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/151/

**Comment by bernie-msft** [comment]
Thanks Mark,

#sign-off

**Comment by bernie-msft** [comment]
Hi, I signed off on this. Was it ever merged?

**Comment by cormacpayne** [comment]
@bernie-msft I was able to log-in and run a few cmdlets in the `AzureUSGovernment` cloud with the new AD endpoint. This should be good to merge.

**Comment by cormacpayne** [comment]
@bernie-msft before we merge this, our team is discussing how we want to do versioning around this change (since it touches common code used by all of the modules we ship). Once we figure that out, we will merge this.

**Comment by bernie-msft** [comment]
Thanks Cormac,

I fear that some service teams may be using the USGov endpoints returned by Get-AzureRMEnvironment to influence what endpoints  to use as they deploy instances within the AzureGov boundary. Do you anticipate when the approach will be decided?

Thanks,
Bernarldo

**Comment by cormacpayne** [comment]
On-demand: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/209/

**Comment by cormacpayne** [comment]
@bernie-msft our upcoming release is next Friday (12/8), so it will be available then

**Comment by bernie-msft** [comment]
Great, thank you!

**Pull request merged**
