### PR TITLE
Add Opt-out for DSC Extension DataCollection

### PR DESCRIPTION
**Pull request by TravisEz13**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@TravisEz13__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (tplunk). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@TravisEz13 There are merge conflicts, please update the PR

**Comment by markcowl** [comment]
@TravisEz13 Should I close this PR?  It cannot be merged until merge conflicts are fixed

**Comment by markcowl** [comment]
@TravisEz13 Closing due to lack of response.  Please open a new PR if you would like these changes to be considered.

**Pull request closed without merging**
