### PR TITLE
Ericdai

### PR DESCRIPTION
**Pull request by bganapa**
Adding AzureStack Storage Admin cmdlets.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bganapa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bganapa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by bganapa** [comment]
on demand : http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/460/

**Comment by bganapa** [comment]
powershell sign : http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/226/

**Comment by hovsepm** [comment]
@bganapa please reopen against release-1.2.0 branch

**Pull request closed without merging**
