### PR TITLE
VPN NAT for Virtual WAN feature changes

### PR DESCRIPTION
**Pull request by Nilambari**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - { https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/790 }
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by Nilambari** [comment]
Incorporated all review comments from old PR:-https://github.com/Azure/azure-powershell/pull/13768 (this was against Azure:network-august branch which is merged to master yesterday.) So, opened the new PR against Azure:master branch.

**Comment by Nilambari** [comment]
@VeryEarly I have incorporated all your review comments from past PR:https://github.com/Azure/azure-powershell/pull/13768 and opened this new PR against Azure:master branch. Can you Please take a look. Thanks!

**Comment by isra-fel** [comment]
As we passed code complete and a `release-2021-01-19` branch was cut off, which should be your target branch.
I retargeted your PR and there were some conflicts. Please resolve them. Thanks

**Comment by Nilambari** [comment]
@isra-fel Fixed the merge conflicts. Thanks!

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
