### PR TITLE
Update description for Set-AzureSubscription

### PR DESCRIPTION
**Pull request by sphibbs**
Hlep content update

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@sphibbs__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (scottph). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by cormacpayne** [comment]
@azuresdkci retest this please

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@azuresdkci retest this please

**Comment by cormacpayne** [comment]
LGTM

**Pull request merged**
