### PR TITLE
Remove ValidateNotNullOrEmpty validation conditions for SubjectBeginsWith/SubjectEndsWith in Update-AzureRmEventGridSubscription cmdlet to allow changing these parameters to empty string if needed

### LINKED ISSUE #6331: Update-AzureRmEventGridSubscription doesn't allow updating subjectBeginsWith/subjectEndsWith to empty strings.
### Description

Update-AzureRmEventGridSubscription doesn't allow updating subjectBeginsWith/subjectEndsWith to empty strings.

### Script/Steps for Reproduction

[From customer]
When value is not null or empty then it works fine. But when it needs to be set to '' it throws
"Cannot validate argument on parameter 'SubjectBeginsWith'. The argument is null or empty. Provide an argument that is not null or empty, and then try the command again"

```powershell
Update-AzureRmEventGridSubscription -ResourceGroup $ResourceGroupName -TopicName $EventGridTopicName -EventSubscriptionName $Subscription.name -SubjectEndsWith $Subscription.subjectEndsWith
```

### PR DESCRIPTION
**Pull request by ahamad-MS**
## Description

This PR fixes #6331. In this issue, customer has a need to update parameters (SubjectBeginsWith) or (SubjectEndsWith) in Update-AzureRmEventGridSubscription cmdlet with empty string. ValidateNotNullOrEmpty validation on these parameters disallows this operation and needs to be removed as they are preventing legitimate operation.

## Checklist

- [X ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ X] The title of the PR is clear and informative
- [X ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ X] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [X ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@ahamad-MS Do we want to remove this empty check on New-AzureRmEventGridSubscription as well?

**Comment by ahamad-MS** [comment]
@maddieclayton .. the check for nullandempty is still needed for the New-AzureRmEventGridSubscription cmdlet only the update command needs to be changed to allow user to update this parameter. Hence no change in the New- cmdlet.

**Comment by maddieclayton** [comment]
Sounds good.

**Comment by maddieclayton** [comment]
on demand here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/921/

**Pull request merged**
