### PR TITLE
Add missing test projects to checkin test library

### PR DESCRIPTION
**Pull request by markcowl**

### CODE REVIEW

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
:shipit:

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/916/

**Pull request merged**
