### PR TITLE
Move resource group cmdlets to new project

### PR DESCRIPTION
**Pull request by vivsriaus**
1) Remove existing resource group cmdlets from Commands.Resources
2) Add New-AzureResourceGroup, Get-AzureResourceGroup, Set-AzureResourceGroup and Remove-AzureResourceGroup under Commands.ResourceManager.Cmdlets project
3) Update scenario tests for resource group tests
4) Remove existing unit level resource group tests
5) Update help files accordingly

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivsriaus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (visriniv). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by vivsriaus** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
@vivsriaus Should we close this one?  Still merge conflicts

**Comment by ogail** [comment]
@vivsriaus please resolve conflicts and resubmit PR appropriately.

**Pull request closed without merging**
