### PR TITLE
AzFunctions: Add additional app settings for Consumption apps, allow empty app settings, and add suffix to connection strings in app settings

### PR DESCRIPTION
**Pull request by Francisco-Gamino**
## Description
Resolves:

Function app creation -- add two additional app settings (WEBSITE_CONTENTSHARE and WEBSITE_CONTENTAZUREFILECONNECTIONSTRING) for Linux Consumption apps 
https://github.com/Azure/azure-powershell/issues/15124

Bug with New-AzFunctionApp when created on Azure Gov 
https://github.com/Azure/azure-powershell/issues/13379

Az.Functions cmdlets need to support creating and copying app settings with empty values
https://github.com/Azure/azure-powershell/issues/14511

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by Francisco-Gamino** [comment]
cc: @AnatoliB @stefanushinardi

**Review by BethanyZhou — APPROVED** [review]

**Comment by Francisco-Gamino** [comment]
Hello @BethanyZhou -- I am trying to get these changes in for the current release (https://github.com/Azure/azure-powershell/milestone/124), which will be available on Friday. 

Could you please make sure this PR gets in? Please let me know if you need anything else from my side. Thank you!

cc: @dingmeng-xue

**Comment by wyunchi-ms** [comment]
Please sync with `generation` branch and add `[Microsoft.Azure.PowerShell.Cmdlets.Functions.DoNotExportAttribute()]` for the functions in `HelperFunctions.ps1`.

**Comment by Francisco-Gamino** [comment]
> Please sync with `generation` branch and add `[Microsoft.Azure.PowerShell.Cmdlets.Functions.DoNotExportAttribute()]` for the functions in `HelperFunctions.ps1`.

Hello @wyunchi-ms -- Do I need to add this `[Microsoft.Azure.PowerShell.Cmdlets.Functions.DoNotExportAttribute()]` attribute to every single function in `HelperFunctions.ps1`?

**Comment by wyunchi-ms** [comment]
> > Please sync with `generation` branch and add `[Microsoft.Azure.PowerShell.Cmdlets.Functions.DoNotExportAttribute()]` for the functions in `HelperFunctions.ps1`.
> 
> Hello @wyunchi-ms -- Do I need to add this `[Microsoft.Azure.PowerShell.Cmdlets.Functions.DoNotExportAttribute()]` attribute to every single function in `HelperFunctions.ps1`?

Yes.

**Comment by Francisco-Gamino** [comment]
Thank you @wyunchi-ms -- When I pulled the latest version of the branch, it looks like you have already added this attribute to some of the functions already. Is there a reason why you did not add it to all the functions? Thanks. 

image

**Review by wyunchi-ms — APPROVED** [review]

**Comment by DiscoveringWorld** [comment]
Hello,

I tried today in Azure Cloud Shell but same result.

Does this is the new version ?

Az.Functions 3.0.0 /usr/local/share/powershell/Modules/Az.Functions/3.0.0/Az.Functions.psd1

**Comment by dingmeng-xue** [comment]
New verison is Az.Functions 3.1.0. It will be available on July 6. CloudShell deploys new release gradually within 10 days.

**Pull request merged**
