### PR TITLE
Support for onlink routing

### PR DESCRIPTION
**Pull request by arganapathy**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
The build fails. You may need to update the SDK

**Comment by arganapathy** [comment]
@wyunchi-ms i do not think the CI pipeline has the latest Microsoft.Azure.Management.Network package. It does not contain latest changes from 2022-05-01 branch. I built this locally for my testing. The changes I'm referring to specifically is the StaticRoutesConfig struct which causes these failures. 
https://github.com/Azure/azure-rest-api-specs/blob/23051523abd6e0fc850517aa6b5c6c3c42fd3251/specification/network/resource-manager/Microsoft.Network/stable/2022-05-01/virtualWan.json#L8830

In my local build this is present.
image

**Comment by arganapathy** [comment]
@wyunchi-ms my checks seem to be passing now. could you please trigger the security tools check?

**Review by wyunchi-ms — APPROVED** [review]

**Comment by arganapathy** [comment]
Hi @wyunchi-ms  seeing some kind of error in security-tools. Looks like an internal error of some kind. Would it be possible to restart the check?
Current directory:    [D:\a\1\s]
ServiceHelper.ReadClientServiceGuidFromCredentialManager() License not found in Credential Manager. Continuing based on override state.
##[error]Exception caught: [Error when getting language list: The type initializer for 'PolicheckService.PolicheckService' threw an exception.]
Policheck.ErrorHandling.ServiceExceptions.PolicheckServiceException: Error when getting language list: The type initializer for 'PolicheckService.PolicheckService' threw an exception. ---> System.ServiceModel.FaultException`1[System.ServiceModel.ExceptionDetail]: The type initializer for 'PolicheckService.PolicheckService' threw an exception.

**Comment by arganapathy** [comment]
@wyunchi-ms i think the merge introduced some errors, but doesnt seem related to my changes. Would it be possible to redo the merge validation?

**Pull request merged**
