### PR TITLE
Update Set-AzSynapseSqlPoolAuditSetting.md

### PR DESCRIPTION
**Pull request by sravanisaluru**
updating the audit action groups that we support for synapse

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by sravanisaluru** [comment]
#sign-off

**Comment by sravanisaluru** [comment]
#sign-off

**Comment by VeryEarly** [comment]
please also update this string:
https://github.com/Azure/azure-powershell/blob/main/src/Synapse/Synapse/Common/HelpMessages.cs#L244
otherwise your change will be overwrite next time doc was generated

**Comment by sravanisaluru** [comment]
Hi Yabo ,

could you please help me with this ,

regards
sravani

**Review by Rupp29 — APPROVED** [review]
Reviewed. The enum changes make this update complicated. Not sure how to proceed.

**Comment by sravanisaluru** [comment]
yes sure , thank you

**Comment by dcaro** [comment]
@sravanisaluru have the accepted values already been changed on the API?
What happens today if `DATABASE_LOGOUT_GROUP` value is passed?

**Comment by sravanisaluru** [comment]
This enum is it applicable for all like azure database azure synapse ? , for azure synapse today we support only 3 action groups so in the accepted values we cannot specify other action groups. but if this used across other services then it can break things. let me know how to proceed. 

customer cannot pass other action groups as its not supported for synapse

**Comment by sravanisaluru** [comment]
this change is applicable only for synapse and it will fail if
database_logout_group is passed as a parameter. i assume this update will
not change anything for azuresql or MI.
let me know if it can be updated only for synapse or will effect other
services like azure sql or MI

**Review by isra-fel — APPROVED** [review]
Sorry for the late response @sravanisaluru 
If the service only accepts 3 values, it makes sense to update the document. This is not a breaking change.
However I think this only solves part of the problem, as the parameter is sharing a enum definition with others, so it's still possible to pass in a value that is invalid.

I will merge this PR. Your next step should be to update the code to limit the options, either by defining a new enum with the three values, or validaing the input value using `ValidateSetAttribute`.

**Pull request merged**
