### PR TITLE
Update resource management dll to include Complete deployment mode (have merge conflicts)

### PR DESCRIPTION
**Pull request by vivsriaus**
…dd Mode pararmeter for New-AzureResourceGroupDeployment

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@vivsriaus__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (visriniv). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
Post check-in tests running here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/30/

**Comment by markcowl** [comment]
msi job will run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/352/

**Comment by vivsriaus** [comment]
@markcowl Here is the post check-in job running successfully after my latest commit: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/34/

**Pull request closed without merging**
