### PR TITLE
Update connectedmachine to 2020-08-02

### PR DESCRIPTION
**Pull request by TylerLeonhardt**
## Description

This updates the API version used for the ConnectedMachine cmdlets to 2020-08-02 which has no functional difference between the previous API version.

Note that there are some parameters that are being removed, this is because the spec made these properties as readonly which is good because the parameters were no-ops anyway. This will be less confusing for the end user.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by TylerLeonhardt** [comment]
@dcaro @dingmeng-xue this is the updated module for `ConnectedMachine` based on the stable version. We are waiting on the full rollout of the ARM manifest to hit all regions. When that happens, I'll make this PR ready for review.

2020-08-02 is available in some regions so I modified my /etc/hosts to run the tests and everything works just fine.

**Comment by TylerLeonhardt** [comment]
not sure why MariaDb and MySql failed but they shouldn't be affected by my changes

**Comment by TylerLeonhardt** [comment]
This is ready to review. 2020-08-02 is live!

**Review by dolauli — APPROVED** [review]

**Review by dolauli — APPROVED** [review]

**Pull request merged**
