### PR TITLE
Network february release

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description

Monthly Azure Networking progress merge

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by vladimir-shcherbakov** [comment]
@MiYanni if it goes to the current release - please switch branch but do not merge yet.

**Comment by MikhailTryakhov** [comment]
@vladimir-shcherbakov  where should I retarget it? Shouldn't we merge in master too?

**Comment by vladimir-shcherbakov** [comment]
@MikhailTryakhov if it goes to the current release it should target the `release-2019-03-26` branch. We'll merge it back to master after the release if done.

**Comment by MikhailTryakhov** [comment]
Thanks @MiYanni @vladimir-shcherbakov can you please merge it?

**Pull request merged**
