### PR TITLE
Location parameter required for Az Powershell 5.9

### PR DESCRIPTION
**Pull request by KaishM**
The following details prove that Location is required parameter.

```
PS C:\management> Get-InstalledModule -Name Az -AllVersions

Version    Name                                Repository           Description
-------    ----                                ----------           -----------
5.9.0      Az                                  PSGallery            Microsoft Azure PowerShell - Cmdlets to manage resources in Azure. This module is compatible with WindowsPowerSh...
```

Command:: 
```
$publicIpPrefix = New-AzPublicIpPrefix -Name $prefixName -ResourceGroupName $rgName -PrefixLength 30
```

Exception::
```
New-AzPublicIpPrefix : The location property is required for this definition.
StatusCode: 400
ReasonPhrase: Bad Request
ErrorCode: LocationRequired
ErrorMessage: The location property is required for this definition.
```

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)

- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @KaishM , thanks for your contribution! I think this is an issue that we need to fix in code. Because our help document is generated but not hand wrote. It will be updated after the issue is fixed.

**Comment by wyunchi-ms** [comment]
I have loged an [issue](https://github.com/Azure/azure-powershell/issues/14959) to track this. Thanks for your contribution again!

**Comment by wyunchi-ms** [comment]
I will close this PR in several days, please feel free to reopen it if you have any question.

**Comment by isra-fel** [comment]
As Yunchi said, we are tracking the problem with an _issue_ . I'll close the pull request. Thanks again!

**Pull request closed without merging**
