### PR TITLE
adding Invoke-AzVmAssessPatch cmdlet. 

### PR DESCRIPTION
**Pull request by grizzlytheodore**
## Description
adding Invoke-AzVmAssessPatch cmdlet. 

And also updated computecommontest to not have space in the location return for Get-ComputeVmLocation
and added a function that will return an available sku for given subscription, location, and resourcetype. 

Design: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/634

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by grizzlytheodore** [comment]
+Mayank, Jemal.

What do you think of the suggestion below?

**Comment by grizzlytheodore** [comment]
+@Mike Richmond<mailto:Michael.Richmond@microsoft.com> and @Najam Shahid<mailto:najams@microsoft.com>

The current name Invoke-AzVmAssessPatch is the right cmdlet name that our team agreed up on and also align with its functionality. What cmdlet  does when it run is that it assess if there is available patch in the VM.

Thanks
Jemal
From: Theodore Chang <Theodore.Chang@microsoft.com>
Sent: Monday, August 10, 2020 8:19 PM
To: Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>
Cc: Mention <mention@noreply.github.com>; Mayank Nayar <manayar@microsoft.com>; Jemal Abdulkadir <jeabdu@microsoft.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

+Mayank, Jemal.

What do you think of the suggestion below?

**Comment by grizzlytheodore** [comment]
Invoke-AzVmPatchAssessment could work as the name. It isn't too far of an intellectual leap from "AssessPatches" to "PatchAssessment." The cmdlet name already differs from the API name since we had to drop the "es' due to the PowerShell singularity name requirement and "PatchAssessment" feels a little less awkward than "AssessPatch."

@Mayank Nayar<mailto:manayar@microsoft.com> - what are your thoughts?

From: Jemal Abdulkadir <jeabdu@microsoft.com>
Sent: Monday, August 10, 2020 8:29 PM
To: Theodore Chang <Theodore.Chang@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Mike Richmond <Michael.Richmond@microsoft.com>; Najam Shahid <najams@microsoft.com>
Cc: Mention <mention@noreply.github.com>; Mayank Nayar <manayar@microsoft.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

+@Mike Richmond<mailto:Michael.Richmond@microsoft.com> and @Najam Shahid<mailto:najams@microsoft.com>

The current name Invoke-AzVmAssessPatch is the right cmdlet name that our team agreed up on and also align with its functionality. What cmdlet  does when it run is that it assess if there is available patch in the VM.

Thanks
Jemal
From: Theodore Chang <Theodore.Chang@microsoft.com<mailto:Theodore.Chang@microsoft.com>>
Sent: Monday, August 10, 2020 8:19 PM
To: Azure/azure-powershell <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mayank Nayar <manayar@microsoft.com<mailto:manayar@microsoft.com>>; Jemal Abdulkadir <jeabdu@microsoft.com<mailto:jeabdu@microsoft.com>>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

+Mayank, Jemal.

What do you think of the suggestion below?

**Comment by grizzlytheodore** [comment]
Hi Mike, Jemal

I think Invoke-AzVmPatchAssessment will work well in this context. I read the cmdlet as invoking a patch assessment, which is the same as assess patches. We can use this option.

Best regards
Mayank Nayar

From: Mike Richmond <Michael.Richmond@microsoft.com>
Sent: Monday, August 10, 2020 8:53 PM
To: Jemal Abdulkadir <jeabdu@microsoft.com>; Theodore Chang <Theodore.Chang@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Najam Shahid <najams@microsoft.com>; Mayank Nayar <manayar@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

Invoke-AzVmPatchAssessment could work as the name. It isn't too far of an intellectual leap from "AssessPatches" to "PatchAssessment." The cmdlet name already differs from the API name since we had to drop the "es' due to the PowerShell singularity name requirement and "PatchAssessment" feels a little less awkward than "AssessPatch."

@Mayank Nayar<mailto:manayar@microsoft.com> - what are your thoughts?

From: Jemal Abdulkadir <jeabdu@microsoft.com<mailto:jeabdu@microsoft.com>>
Sent: Monday, August 10, 2020 8:29 PM
To: Theodore Chang <Theodore.Chang@microsoft.com<mailto:Theodore.Chang@microsoft.com>>; Azure/azure-powershell <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>; Mike Richmond <Michael.Richmond@microsoft.com<mailto:Michael.Richmond@microsoft.com>>; Najam Shahid <najams@microsoft.com<mailto:najams@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mayank Nayar <manayar@microsoft.com<mailto:manayar@microsoft.com>>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

+@Mike Richmond<mailto:Michael.Richmond@microsoft.com> and @Najam Shahid<mailto:najams@microsoft.com>

The current name Invoke-AzVmAssessPatch is the right cmdlet name that our team agreed up on and also align with its functionality. What cmdlet  does when it run is that it assess if there is available patch in the VM.

Thanks
Jemal
From: Theodore Chang <Theodore.Chang@microsoft.com<mailto:Theodore.Chang@microsoft.com>>
Sent: Monday, August 10, 2020 8:19 PM
To: Azure/azure-powershell <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mayank Nayar <manayar@microsoft.com<mailto:manayar@microsoft.com>>; Jemal Abdulkadir <jeabdu@microsoft.com<mailto:jeabdu@microsoft.com>>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

+Mayank, Jemal.

What do you think of the suggestion below?

**Comment by grizzlytheodore** [comment]
@Mayank Nayar<mailto:manayar@microsoft.com> what would be the corresponding cmdlet for installPatches api?

Thanks,
Najam

Get Outlook for Android<https://aka.ms/ghei36>

________________________________
From: Mayank Nayar <manayar@microsoft.com>
Sent: Monday, August 10, 2020 11:11:46 PM
To: Mike Richmond <Michael.Richmond@microsoft.com>; Jemal Abdulkadir <jeabdu@microsoft.com>; Theodore Chang <Theodore.Chang@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Najam Shahid <najams@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)


Hi Mike, Jemal



I think Invoke-AzVmPatchAssessment will work well in this context. I read the cmdlet as invoking a patch assessment, which is the same as assess patches. We can use this option.



Best regards

Mayank Nayar



From: Mike Richmond <Michael.Richmond@microsoft.com>
Sent: Monday, August 10, 2020 8:53 PM
To: Jemal Abdulkadir <jeabdu@microsoft.com>; Theodore Chang <Theodore.Chang@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>; Najam Shahid <najams@microsoft.com>; Mayank Nayar <manayar@microsoft.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)



Invoke-AzVmPatchAssessment could work as the name. It isn’t too far of an intellectual leap from “AssessPatches” to “PatchAssessment.” The cmdlet name already differs from the API name since we had to drop the “es’ due to the PowerShell singularity name requirement and “PatchAssessment” feels a little less awkward than “AssessPatch.”



@Mayank Nayar<mailto:manayar@microsoft.com> – what are your thoughts?



From: Jemal Abdulkadir <jeabdu@microsoft.com<mailto:jeabdu@microsoft.com>>
Sent: Monday, August 10, 2020 8:29 PM
To: Theodore Chang <Theodore.Chang@microsoft.com<mailto:Theodore.Chang@microsoft.com>>; Azure/azure-powershell <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>; Mike Richmond <Michael.Richmond@microsoft.com<mailto:Michael.Richmond@microsoft.com>>; Najam Shahid <najams@microsoft.com<mailto:najams@microsoft.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mayank Nayar <manayar@microsoft.com<mailto:manayar@microsoft.com>>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)



+@Mike Richmond<mailto:Michael.Richmond@microsoft.com> and @Najam Shahid<mailto:najams@microsoft.com>



The current name Invoke-AzVmAssessPatch is the right cmdlet name that our team agreed up on and also align with its functionality. What cmdlet  does when it run is that it assess if there is available patch in the VM.



Thanks

Jemal

From: Theodore Chang <Theodore.Chang@microsoft.com<mailto:Theodore.Chang@microsoft.com>>
Sent: Monday, August 10, 2020 8:19 PM
To: Azure/azure-powershell <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>; Mayank Nayar <manayar@microsoft.com<mailto:manayar@microsoft.com>>; Jemal Abdulkadir <jeabdu@microsoft.com<mailto:jeabdu@microsoft.com>>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)



+Mayank, Jemal.



What do you think of the suggestion below?

**Comment by grizzlytheodore** [comment]
Going with the same terminology the install cmdlet can be Invoke-AzVmPatchInstallation or Invoke-AzVmPatchInstall

Best regards
Mayank Nayar

**Comment by grizzlytheodore** [comment]
I was thinking of Invoke-AzVmPatchInstallation which will also be consistent with Invoke-AzVmPatchAssessment. Quick question for my own learning (sorry if I’ve misses cmdlet review doc☹): why is the verb “invoke” instead of “assess” or “install”? Is it to make it async cmdlet and then some other cmdlet to invoke for the progress?

Thanks,
Najam

From: Mayank Nayar <manayar@microsoft.com>
Sent: Tuesday, August 11, 2020 10:53 AM
To: Najam Shahid <najams@microsoft.com>; Mike Richmond <Michael.Richmond@microsoft.com>; Jemal Abdulkadir <jeabdu@microsoft.com>; Theodore Chang <Theodore.Chang@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

Going with the same terminology the install cmdlet can be Invoke-AzVmPatchInstallation or Invoke-AzVmPatchInstall

Best regards
Mayank Nayar

**Comment by grizzlytheodore** [comment]
There is a list of approved verbs for PowerShell Commands<https://docs.microsoft.com/en-us/powershell/scripting/developer/cmdlet/approved-verbs-for-windows-powershell-commands?view=powershell-7> and ‘assess’ is not one of them.

‘Install’ is however an approved verb, so if you want to use it for patch installation command, you can.

From: Najam Shahid <najams@microsoft.com>
Sent: Tuesday, August 11, 2020 2:01 PM
To: Mayank Nayar <manayar@microsoft.com>; Mike Richmond <Michael.Richmond@microsoft.com>; Jemal Abdulkadir <jeabdu@microsoft.com>; Theodore Chang <Theodore.Chang@microsoft.com>; Azure/azure-powershell <reply@reply.github.com>; Azure/azure-powershell <azure-powershell@noreply.github.com>
Cc: Mention <mention@noreply.github.com>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

I was thinking of Invoke-AzVmPatchInstallation which will also be consistent with Invoke-AzVmPatchAssessment. Quick question for my own learning (sorry if I’ve misses cmdlet review doc☹): why is the verb “invoke” instead of “assess” or “install”? Is it to make it async cmdlet and then some other cmdlet to invoke for the progress?

Thanks,
Najam

From: Mayank Nayar <manayar@microsoft.com<mailto:manayar@microsoft.com>>
Sent: Tuesday, August 11, 2020 10:53 AM
To: Najam Shahid <najams@microsoft.com<mailto:najams@microsoft.com>>; Mike Richmond <Michael.Richmond@microsoft.com<mailto:Michael.Richmond@microsoft.com>>; Jemal Abdulkadir <jeabdu@microsoft.com<mailto:jeabdu@microsoft.com>>; Theodore Chang <Theodore.Chang@microsoft.com<mailto:Theodore.Chang@microsoft.com>>; Azure/azure-powershell <reply@reply.github.com<mailto:reply@reply.github.com>>; Azure/azure-powershell <azure-powershell@noreply.github.com<mailto:azure-powershell@noreply.github.com>>
Cc: Mention <mention@noreply.github.com<mailto:mention@noreply.github.com>>
Subject: RE: [Azure/azure-powershell] adding Invoke-AzVmAssessPatch cmdlet. (#12608)

Going with the same terminology the install cmdlet can be Invoke-AzVmPatchInstallation or Invoke-AzVmPatchInstall

Best regards
Mayank Nayar

**Comment by grizzlytheodore** [comment]
moved to https://github.com/Azure/azure-powershell/pull/12658

**Pull request closed without merging**
