### PR TITLE
Order of Operations for OVPN test

### PR DESCRIPTION
**Pull request by henry416**
## Description

Fix for ovpn test to go in proper order of operations as expected by preview instructions

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by henry416** [comment]
Wrong target

**Comment by maddieclayton** [comment]
Looks like the test is still failing: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/7349/artifact/src/Publish/TestResults/FailingTests/Microsoft.Azure.Commands.Network.Test.dll.html

**Comment by henry416** [comment]
@maddieclayton looks like run with wrong API version, I will correct this

**Comment by henry416** [comment]
Failure doesn't seem related to test

**Comment by cormacpayne** [comment]
@panchagnula Hey Sisira, the build is failing after CredScan flagged a few files for containing potential passwords, secrets, keys, etc. You can find the results here: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/7369/artifact/src/Package/CredentialScannerOutput/CredScanIssues.csv

Would you mind taking a look at the files that were flagged and ensure that these are values that anyone else can use? (_i.e._, they are dummy values or have been deleted since the recording) If it turns out this is the case, we can suppress these exceptions (using the method outlined [here](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/credscan-ps.md)).

**Comment by cormacpayne** [comment]
@henry416 Hey Henry, the build is failing after CredScan flagged a few files for containing potential passwords, secrets, keys, etc. You can find the results here: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/7369/artifact/src/Package/CredentialScannerOutput/CredScanIssues.csv

Would you mind taking a look at the files that were flagged and ensure that these are values that anyone else can use? (_i.e._, they are dummy values or have been deleted since the recording) If it turns out this is the case, we can suppress these exceptions (using the method outlined [here](https://github.com/Azure/adx-documentation-pr/blob/master/engineering/credscan-ps.md)).

**Comment by henry416** [comment]
@cormacpayne This is a false positive cred, I have updated the file to try to suppress it.

**Comment by henry416** [comment]
On request of @MikhailTryakhov, updated the route API test record as well

**Pull request merged**
