### PR TITLE
support query Load Balancer inbound nat rule port mapping lists for backend addresses

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description

Add new cmdlet to query port mapping and update existing inboundNatRule cmdlets (https://github.com/Azure/azure-powershell/pull/16743)

update inboundNatRule cmds, update inboundNatRule, backendAddres PSObject, create queryPortMapping cmd

add UTs and create new PSNatRulePortMapping for backendAddress

fixed UTs

update inboundNatRule md files

add md file for query port mapping

update changelog.md

Small change to resolve comment

update json file

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by MikhailTryakhov** [comment]
Ready for merge

**Comment by MikhailTryakhov** [comment]
@isra-fel @HemantErappa @dingmeng-xue can you please review and help to merge it finally? :)

**Comment by VeryEarly** [comment]
Hi @MikhailTryakhov 
The SDK version is 21.0.0: 
https://github.com/Azure/azure-powershell/blob/mitryakh/network-june/src/Network/Network/Network.csproj#L17
which uses API version 2021-05-01:
image

Is there API version upgrade needed?

**Comment by MikhailTryakhov** [comment]
@VeryEarly  no, we'll leave same api version for current release

**Comment by MikhailTryakhov** [comment]
@veryearly can you please help to merge it?

**Comment by MikhailTryakhov** [comment]
@isra-fel @HemantErappa @dingmeng-xue can you please help?

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
