### PR TITLE
update latest VMAccessAgent version to 2.4 instead of 2.0

### PR DESCRIPTION
**Pull request by axelgMS**
same as #10755 - but for **_Set-AzureRmVMAccessExtension_**

version 2.0 is pretty old and users should use 2.4 instead
so I'm modifying the sample here to ensure they're using latest version.

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @axelgMS ,

This is preview branch and the example had been [fixed](https://github.com/Azure/azure-powershell/blob/master/src/Compute/Compute/help/Set-AzVMAccessExtension.md) already.

Will close this PR if there are no particular reason to make these changes.

**Comment by axelgMS** [comment]
@VeryEarly Thanks - but we need to modify this page https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0 too.
It's the one for **_Set-AzureRmVMAccessExtension_**, while the other page is for **_Set_AzVMAccessExtension_**

**Comment by VeryEarly** [comment]
> @VeryEarly Thanks - but we need to modify this page https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0 too.
> It's the one for **_Set-AzureRmVMAccessExtension_**, while the other page is for **_Set_AzVMAccessExtension_**

Hi @axelgMS ,

AzureRM was not been supported, we won't release new version for it anymore.

**Comment by axelgMS** [comment]
> > @VeryEarly Thanks - but we need to modify this page https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0 too.
> > It's the one for **_Set-AzureRmVMAccessExtension_**, while the other page is for **_Set_AzVMAccessExtension_**
> 
> Hi @axelgMS ,
> 
> AzureRM was not been supported, we won't release new version for it anymore.

I get this - and I'm not asking for a change in the cmdlet. I'm asking for a documentation change in the sample using it.

I'm still using **_Set-AzureRmVMAccessExtension_** from time to time, as well as some customers.
We had cases where customers were strictly following that doc, and it was failing as VMAccess 2.0 should be replaced with 2.4.
So my goal is to avoid further cases by giving users a correct syntax.

and by the way, where is it written that **_set-azurermvmaccessextension_** is not supported? I don't see anything in https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0

**Comment by VeryEarly** [comment]
> > > @VeryEarly Thanks - but we need to modify this page https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0 too.
> > > It's the one for **_Set-AzureRmVMAccessExtension_**, while the other page is for **_Set_AzVMAccessExtension_**
> > 
> > 
> > Hi @axelgMS ,
> > AzureRM was not been supported, we won't release new version for it anymore.
> 
> I get this - and I'm not asking for a change in the cmdlet. I'm asking for a documentation change in the sample using it.
> 
> I'm still using **_Set-AzureRmVMAccessExtension_** from time to time, as well as some customers.
> We had cases where customers were strictly following that doc, and it was failing as VMAccess 2.0 should be replaced with 2.4.
> So my goal is to avoid further cases by giving users a correct syntax.
> 
> and by the way, where is it written that **_set-azurermvmaccessextension_** is not supported? I don't see anything in https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0

Hi @axelgMS ,

"It's not supported" means we won't release new version for it, any fix made here won't be published.
For your requirement I suggest raise a PR here: https://github.com/MicrosoftDocs/azure-docs-powershell/tree/master/azurermps-6.13.0

Thanks

**Comment by axelgMS** [comment]
OK I get it now. I thought I was modifying the DOC page, but I was under Azure  / azure-powershell, modifying
src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMAccessExtension.md

and you’re suggesting me to directly modify in MicrosoftDocs / azure-docs-powershell
azurermps-6.13.0/AzureRM.Compute/Set-AzureRmVMAccessExtension.md

what’s the difference between the HELP, and the DOC file? They look identical to me

**Comment by axelgMS** [comment]
closing here - I opened update latest VMAccessAgent version to 2.4 instead of 2.0 #[1452](https://github.com/MicrosoftDocs/azure-docs-powershell/pull/1452) in the MS Docs

**Comment by VeryEarly** [comment]
> OK I get it now. I thought I was modifying the DOC page, but I was under Azure / azure-powershell, modifying src/ResourceManager/Compute/Commands.Compute/help/Set-AzureRmVMAccessExtension.md and you’re suggesting me to directly modify in MicrosoftDocs / azure-docs-powershell azurermps-6.13.0/AzureRM.Compute/Set-AzureRmVMAccessExtension.md what’s the difference between the HELP, and the DOC file? They look identical to me From: Yabo Hu <notifications@github.com> Sent: Monday, June 29, 2020 8:16 AM To: Azure/azure-powershell <azure-powershell@noreply.github.com> Cc: Axel Guerrier <Axel.Guerrier@microsoft.com>; Mention <mention@noreply.github.com> Subject: Re: [Azure/azure-powershell] update latest VMAccessAgent version to 2.4 instead of 2.0 (#12243) @VeryEarly<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FVeryEarly&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435528139&sdata=SSQxNTj27%2BwOSlXYf%2BX8g03jzYgAvayzahwUmOy%2FUa8%3D&reserved=0> Thanks - but we need to modify this page https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Fazurerm.compute%2Fset-azurermvmaccessextension%3Fview%3Dazurermps-6.13.0&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435528139&sdata=l7GZs6rm4IqYgW7PJc3PGBf9MStdvwrLIwu4d2fyVZ8%3D&reserved=0> too. It's the one for Set-AzureRmVMAccessExtension, while the other page is for Set_AzVMAccessExtension Hi @axelgMS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FaxelgMS&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435528139&sdata=DS%2B6%2FeVxSoXCZwJ%2F7JqQUa%2FmGwlVqJ9mro2ZUrEC%2B7s%3D&reserved=0> , AzureRM was not been supported, we won't release new version for it anymore. I get this - and I'm not asking for a change in the cmdlet. I'm asking for a documentation change in the sample using it. I'm still using Set-AzureRmVMAccessExtension from time to time, as well as some customers. We had cases where customers were strictly following that doc, and it was failing as VMAccess 2.0 should be replaced with 2.4. So my goal is to avoid further cases by giving users a correct syntax. and by the way, where is it written that set-azurermvmaccessextension is not supported? I don't see anything in https://docs.microsoft.com/en-us/powershell/module/azurerm.compute/set-azurermvmaccessextension?view=azurermps-6.13.0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fdocs.microsoft.com%2Fen-us%2Fpowershell%2Fmodule%2Fazurerm.compute%2Fset-azurermvmaccessextension%3Fview%3Dazurermps-6.13.0&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435538134&sdata=IOUaJG7p3O4dbZDbgDhPPrctvcinwc4wEGD6qGsiJq4%3D&reserved=0> Hi @axelgMS<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FaxelgMS&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435538134&sdata=F5Uaf9HIyMZTS2JBN4zs7yCBskScLzYTpG3HeRj%2BfAY%3D&reserved=0> , "It's not supported" means we won't release new version for it, any fix made here won't be published. For your requirement I suggest raise a PR here: https://github.com/MicrosoftDocs/azure-docs-powershell/tree/master/azurermps-6.13.0<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FMicrosoftDocs%2Fazure-docs-powershell%2Ftree%2Fmaster%2Fazurermps-6.13.0&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435548129&sdata=hvu9A9aBeBGqCptTryyYol76M0lHiW2R%2FfPJ7uhRS3A%3D&reserved=0> Thanks — You are receiving this because you were mentioned. Reply to this email directly, view it on GitHub<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2FAzure%2Fazure-powershell%2Fpull%2F12243%23issuecomment-650944756&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435548129&sdata=PVb2J8ktf8UodhGtChM%2Bi4oMXeuRTMLhVuDifVJ3GH8%3D&reserved=0>, or unsubscribe<https://nam06.safelinks.protection.outlook.com/?url=https%3A%2F%2Fgithub.com%2Fnotifications%2Funsubscribe-auth%2FACPXLYCEKILQSKVHLIBJJ63RZAWQZANCNFSM4OFNPQ5A&data=02%7C01%7CAxel.Guerrier%40microsoft.com%7C4387fb6a23eb4e04757208d81bf3d982%7C72f988bf86f141af91ab2d7cd011db47%7C1%7C0%7C637290081435558124&sdata=IMqdWFhdau77oTmcXQ041PeC1HRexyg9%2FgTFEe6m73w%3D&reserved=0>.

this repo is for official Az release, historical docs are maintained in the repo I sent.

**Pull request closed without merging**
