### PR TITLE
cherry picking KV fixes for Blocking BVT scenarios in Azure stack

### PR DESCRIPTION
**Pull request by bganapa**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@bganapa__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (bganapa). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@bganapa There are merge conflicts, please pull the latest

**Comment by bganapa** [comment]
@markcowl  merged the latest changes

**Comment by markcowl** [comment]
@bganapa apparently not

**Comment by bganapa** [comment]
@markcowl  merged again for credscan fixes :)

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/943/

**Comment by hovsepm** [comment]
This branch is out-of-date with the base branch
Merge the latest changes from release-1.2.4 into this branch.

**Comment by markcowl** [comment]
@bganapa out of date - the compute fix may conflict

**Comment by bganapa** [comment]
@markcowl merged the upstream again

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/966/

**Pull request merged**
