### PR TITLE
Changes for customer-reported Remove-AzPolicyAssignment behavior

### PR DESCRIPTION
**Pull request by mentat9**
## Description

Changes for IcM: https://portal.microsofticm.com/imp/v5/incidents/details/546429959/summary

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [X] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by mentat9** [comment]
Went through the logs, but didn't recognize anything about the errors. Can someone from Powershell take a look?

**Review by calecarter — APPROVED** [review]
:shipit:

**Review by calecarter — APPROVED** [review]

**Comment by mentat9** [comment]
@msJinLei - Any idea how to fix these checks? I tried rerecording all tests, but the checks are still failing in the same place. Everything including playback tests looks good locally.

**Review by Nickcandy — APPROVED** [review]

**Pull request merged**
