### PR TITLE
Update sql server AAD Admin to use 2019-06-01-preview API

### PR DESCRIPTION
**Pull request by amolagar5**
## Description

Update sql server AAD Admin to use 2019-06-01-preview API

Pending: help and md files. 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @amolagar5, if youo need any help about `generate help file`. Please ask us as you wish.

**Comment by amolagar5** [comment]
Help files have been added and swagger\.NET checked in.

**Comment by wyunchi-ms** [comment]
Hi @amolagar5 could you please take a look at the CI? The build is failed.

**Comment by amolagar5** [comment]
> Hi @amolagar5 could you please take a look at the CI? The build is failed.
@wyunchi-ms sure. waiting for .NET sdk build to get published. there are some ARM APIs not released and thus preventing us from publishing the SDK publicly.

**Comment by wyunchi-ms** [comment]
> > Hi @amolagar5 could you please take a look at the CI? The build is failed.
> > @wyunchi-ms sure. waiting for .NET sdk build to get published. there are some ARM APIs not released and thus preventing us from publishing the SDK publicly.

Please tell me when the .NET sdk is ready. Then we can merge this pr. Thanks!

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by amolagar5** [comment]
@wyunchi-ms , Build succeeds after publishing the .NET sdk nuget package, save-build fails however, can you please take a look.

**Pull request merged**
