### PR TITLE
Merge Az.Batch-preview to master

### PR DESCRIPTION
**Pull request by matthchr**
## Description

This brings the long outstanding breaking changes in the Az.Batch module into `master`

## Checklist

- [x] I have read the [_Submitting Changes_](../CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by matthchr** [comment]
## Note for reviewers

1. This _does_ include breaking changes. These changes have been in `Az.Batch-preview` for a while, and we are now targeting the [Nov 4 Milestone](https://github.com/Azure/azure-powershell/milestone/89) for releasing these changes as part of the standard `Az.Batch` module.
2. The PRs merged into `Az.Batch-preview` already went through review. You can see them here:
    - #8612
    - #10001
3. Because some new cmdlets were added, we did design reviews for those. You can see those reviews either in the PR links above, or duplicated here:
    - The new `New-AzBatchResourceFile` cmdlet was reviewed [here](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/235)
    - The `Get-AzBatchSupportedImages` cmdlet was reviewed [here](Azure/azure-powershell-cmdlet-review-pr#371)

This resolves issue: #10137 

There were a few conflicts in the merge which I had to fix (which is why the merge is originating from a branch and not `Az.Batch-preview` directly.
The conflicting files were:
  - src/Batch/Batch/Az.Batch.psd1
  - src/Batch/Batch/BatchAccounts/GetBatchAccountSupportedImagesCommand.cs
  - src/Batch/Batch/ChangeLog.md
  - src/Batch/Batch/Properties/AssemblyInfo.cs

**Please ensure that the changelog and module versions look right**, as this _was_ published as a preview, so it's already moved to `2.0.0-preview`, and the code in this PR should be shipped as `2.0.0`.

**Comment by matthchr** [comment]
@erich-wang @markcowl - please let me know if you need anything from me for this PR to be merged.

**Comment by erich-wang** [comment]
@matthchr, I'm reviewing this PR, it may take some time since it is big, should be done in next couple days.

**Comment by matthchr** [comment]
@erich-wang - just checking on this - I don't want this PR to miss the cutoff for release.

**Pull request merged**
