### PR TITLE
[Storage] Support Track2 SDK for File and Queue

### PR DESCRIPTION
**Pull request by blueww**
## Description

Add Track2 Object to AzureStorageQueue.
Change the File cmdlets output from Track1 SDK object to PS wrappered object AzureStorageFile/AzureStorageShare/AzureStorageFileDirectory, and add both Track1 and Track2 SDK object as memeber of PSH wrapped object.

Since the change  is mostly on change the output of, And add some parameter alias to make the pipe line still work, so syntax has almost no change, so not raise the design doc.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by blueww** [comment]
@wyunchi-ms 

This change is a little big. As It's breaking, if you think it's too risky to merge to this release, we can consider to put it to preview module first, then release in next major release.
Anyway, if we have to make it in next major release, it means we can't release any new file features in PSH stable release before next major PSH release.

**Comment by wyunchi-ms** [comment]
Please resolve the conflicts @blueww

**Comment by blueww** [comment]
@wyunchi-ms 
Conflict is resolved.

**Comment by blueww** [comment]
The test on mac OS actually passed, the failure happen on save test result, it seems a CI framework issue:
> No LastRequestResponse on exception ArtifactExistsException: Artifact test-macOS already exists for build 385552. Microsoft.TeamFoundation.Build.WebApi.ArtifactExistsException: Artifact test-macOS already exists for build 385552.

**Pull request merged**
