### PR TITLE
Changes to Examples for commandlets

### PR DESCRIPTION
**Pull request by rahulpandit85**
Please review the file to update the examples for the commandlets

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@rahulpandit85__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (rapandit). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@rahulpandit85 Thanks for the contribution, the service team is looking at the change

**Comment by markcowl** [comment]
@huangpf @hyonholee @singhkay Can you guys sign off on this PR?

**Comment by markcowl** [comment]
@rahulpandit85 Closing this PR.  Please coordinate with the compute team and then open a new PR with these changes.

**Pull request closed without merging**
