### PR TITLE
Add algorithm types to threat detection DetectionType enum

### PR DESCRIPTION
**Pull request by t-arrinb**
Add Data_Exfiltration and  to Unsafe_Action threat detection DetectionType enum

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@jaredmoo Can you verify this change?

@t-arrinb Please update the changelog (src/ResourceManager/Sql/Commands.Sql/Changelog.md) and add a test for your change.

**Comment by maddieclayton** [comment]
@azuresdkci Add to whitelist

**Comment by t-arrinb** [comment]
Currently we'll stay with DetectionType[]. Opened task 294227 to move to string[] with auto complete.

**Comment by t-arrinb** [comment]
> @jaredmoo Can you verify this change?
> 
> @t-arrinb Please update the changelog (src/ResourceManager/Sql/Commands.Sql/Changelog.md) and add a test for your change.

I've updated changelong.

Our current tests pass and hold for this scenario. The task above will add logic to the test for excluding the new types (this is no logic alteration, just addition of types).

**Comment by t-arrinb** [comment]
@maddieclayton The new changes need review.

**Comment by maddieclayton** [comment]
@t-arrinb Please add a test for your change.

**Comment by maddieclayton** [comment]
@t-arrinb Ping on the comment above.

**Comment by maddieclayton** [comment]
Closing for inactivity. Please reopen when you have time to add the required test.

**Pull request closed without merging**
