### PR TITLE
ADF PowerShell change for sprint 47

### PR DESCRIPTION
**Pull request by jackmagic313**
1. Bump up nuget version to latest (0.15.7)
2. Remove some E2E test cases in order to reduce build/test time of PowerShell (we have already added two LongRunningOperationtimeout properties in Hydra)

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jackmagic313__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jikma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jackmagic313** [comment]
Temporarily closed to investigate issues in Jenkins build

**Comment by azurecla** [comment]
Hi __@jackmagic313__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jikma). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by jackmagic313** [comment]
It seems that most of errors happened due to "no enough disk space"...reopen it to have a try

**Comment by markcowl** [comment]
@jackmagic313 Sprint 47 is using the //build branch of the private repo.  Please submit your PR there.  Closing

**Pull request closed without merging**
