### PR TITLE
Az.StackHCI | Selectively enable ARC

### PR DESCRIPTION
**Pull request by prateekprshr-nith**
## Description
- Added changes to selectively enable ARC
- ARC will not be enabled incase the registration has been triggered from cloud. In that case:
   - The nodes will already be onboarded to ARC
   - All other necessary plumbing like role assignment, existence of resource group etc. will be already complete
   - Helpful error messages will be thrown if any of the assertions and assumptions are broken

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by IndraneelPal — APPROVED** [review]

**Comment by NoriZC** [comment]
Could you provide more details about selectively enable ARC in PR description? Like:
- Why when Cloud deplyment is enabled, we should skip ARC. 
- When Cloud deployment is enabled:
  - in which cases should we directly throw an error?
  - in which cases should the process been skiipped?

**Comment by IndraneelPal** [comment]
Adding @Prateek ***@***.***> and @Niranjan ***@***.***>
Thanks

**Comment by prateekprshr-nith** [comment]
> Could you provide more details about selectively enable ARC in PR description? Like:
> 
> * Why when Cloud deplyment is enabled, we should skip ARC.
> * When Cloud deployment is enabled:
>   
>   * in which cases should we directly throw an error?
>   * in which cases should the process been skipped?

@NoriZC, I've updated the description with more details. Please let me know if that looks or you want me to elaborate more.

**Review by NoriZC — APPROVED** [review]
LGTM

**Pull request merged**
