### PR TITLE
Format BreakingChange Output Messages

### PR DESCRIPTION
**Pull request by BethanyZhou**
## Description
Our current BreakingChange messages show some format problems, such as unnecessary blank lines and indents, inconsistent words, etc.

display
display1

I formatted them, then it looks like below now.

display1
display2

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by BethanyZhou** [comment]
Hi @msJinLei , could you please help to review this PR? The PR in common repo need be reviewed first: https://github.com/Azure/azure-powershell-common/pull/210, thanks!

**Comment by isra-fel** [comment]
Looping in @mikefrobbins and @dcaro to review the format change of breaking change messages. Thanks

**Comment by dcaro** [comment]
@BethanyZhou thanks for this initiative!
The proposed changes look much better but it seems that the "WARNING"on each line gets in the way of readability.
I'd suggest a line at the top with the warning message then the breaking changes details. For example: 

"WARNING: Upcoming breaking changes in cmdlet 'Set-AzKeyVaultSecret' : 
   - The output type ....
   - The following properties ....
   Note: The change is expected to take effect ... 
   Note: Go to https://aka.ms/azps-changewarnings  .... 
"
We could add some emphasis like "**WARNING**".

**Comment by BethanyZhou** [comment]
Hi @dcaro, thanks for your feedback. 
Removing "Warning" makes sense, but these "Warning"s are inserted by output method `WriteWarning`.
I'm afraid of affecting other unrelated and unknown warning messages if we change the output method.

**Comment by BethanyZhou** [comment]
@dcaro New format pictures have been updated in description section . 
Warning style is controlled by method `WriteWarning`. Has no plan to redesign it to '**WARNING**' currently. Thanks!

**Comment by dcaro** [comment]
This is really nice now!
Looks good to me.

**Review by isra-fel — CHANGES_REQUESTED** [review]
Please update the changelog of Az.Accounts - that's where we put change logs of common code

**Review by msJinLei — DISMISSED** [review]

**Review by msJinLei — APPROVED** [review]

**Comment by BethanyZhou** [comment]
@isra-fel Updated!

**Review by isra-fel — APPROVED** [review]
LGTM. Thanks

**Pull request merged**
