### PR TITLE
Enable build filtering for CI

### PR DESCRIPTION
**Pull request by cormacpayne**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by cormacpayne** [comment]
Results from testing:

```
Common.Netcore.Dependencies.targets
    Jenkins: 40:07 (ADXWorker27s)
    Travis:  33:55

CONTRIBUTING.md
    Jenkins: 8:38 (ADXWorker27s)
    Travis:  6:07

Billing
    Jenkins: 14:26 (ADXWorker44s)
    Travis:  10:13

Billing, Media
    Jenkins: 8:28 (ADXWorker27s)
    Travis:  14:53

Billing, Compute, Media
    Jenkins: 13:38 (ADXWorker27s)
    Travis:  12:48

Compute
    Jenkins: 13:00 (ADXWorker27s)
    Travis:  34:41 (rate limit exceeded)

Network
    Jenkins: 19:08 (ADXWorker27s)
    Travis:  16:41

Profile
    Jenkins: 33:09 (ADXWorker58s)
    Travis:  37:19

Sql
    Jenkins: 9:37 (ADXWorker27s)
    Travis:  35:02 (rate limit exceeded)
```

**Comment by markcowl** [comment]
@cormacpayne Please verify with a sign build

**Comment by cormacpayne** [comment]
Sign job: https://azuresdkci.westus2.cloudapp.azure.com/job/psnetsign-esrp/50/

**Comment by MiYanni** [comment]
@cormacpayne Any chance we could work this into my ADO PR? https://github.com/Azure/azure-powershell/pull/8323 Otherwise, we're going to have big conflicts with each other in `build.proj`.

**Comment by cormacpayne** [comment]
@MiYanni I'll wait until the ADO PR goes in and update this PR accordingly -- I don't want to hold up any ADO work on the changes that would need to be made to bring these changes into that PR

**Comment by cormacpayne** [comment]
Closing PR until the ADO changes have been merged.

**Pull request closed without merging**
