### PR TITLE
Updated .NET SDK 2022-11-01 for PowerShell

### PR DESCRIPTION
**Pull request by MikhailTryakhov**
## Description
Updated .NET SDK for PowerShell... Solved merge conflicts with main branch

To highlight: like we did in main, I've removed src/Network/Network/Network.format.ps1xml file.

## Checklist

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by msJinLei** [comment]
@MikhailTryakhov Please use meaingful title of the PR and check whether the revised title is appropriate

**Comment by msJinLei** [comment]
Please fix the compilation error.

**Comment by MikhailTryakhov** [comment]
@msJinLei what don't you like in the title? 
I've generated new version of .NET SDK and in the description shown that I've solved merge conflicts with main due to we're close to release that branch

**Comment by MikhailTryakhov** [comment]
@msJinLei - the failures fixed

**Comment by msJinLei** [comment]
> @msJinLei what don't you like in the title? I've generated new version of .NET SDK and in the description shown that I've solved merge conflicts with main due to we're close to release that branch

I modify the title. But not sure whether it is OK for you. If no more comments, I will merge the PR.

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
