### PR TITLE
[Storage] Support new Storage Account Kinds and Property FileAADIntegration

### PR DESCRIPTION
**Pull request by blueww**
## Description

The PR is to support new storage Kind BlockBlobStorage/FileStorage, and new property FileAADIntegration.
The design passed review in Azure/azure-powershell-cmdlet-review-pr#44

Since Get Global Usage rest api is removed from 2018-07-01 api version (as get Location usage supported), Parameter "Location" of Get-AzureRmStorageUsage change from optional to required. This is a breaking change.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by blueww** [comment]
@markcowl , @praries880 
Would you please help to review the PR?
The feature target to release as preview module AzureRm.Storage in Ignite (9/24).

**Comment by blueww** [comment]
On-Demand: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/1107/ 
PreSign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1349/
psnetsign: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/198/

**Comment by markcowl** [comment]
@blueww Created a PR here that fixes the build problem for NetCore: #7285

**Comment by blueww** [comment]
@markcowl 
The build pass for this PR.
As we discussed today, you will merge the PR and upgrade AzureRm.storage version to 6.0.0, and build the RC. I will test the RC tomorrow.
Thanks for your help!

**Comment by blueww** [comment]
On-Demand (Pass): https://azuresdkci.westus2.cloudapp.azure.com/job/powershell-demand/1108/
psnetsign (Pass): https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/200/
PreSign (Fail): https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1353/

PreSign failure, @markcowl , would you please help to look?

> 0:57:53   Publish-PSArtifactUtility : PowerShellGet cannot resolve the module dependency 
> 20:57:53   'Azure.Storage' of the module 'Azure' on the repository 
> 20:57:53   '6beba64b-7a19-49ff-86fb-388e17d550ab'. Verify that the dependent module 
> 20:57:53   'Azure.Storage' is available in the repository 
> 20:57:53   '6beba64b-7a19-49ff-86fb-388e17d550ab'. If this dependent module 
> 20:57:53   'Azure.Storage' is managed externally, add it to the 
> 20:57:53   ExternalModuleDependencies entry in the PSData section of the module manifest.

**Comment by markcowl** [comment]
@blueww  This is because the 'Azure' module takes a dependency on Azure.Storage 4.6.0, which does not exist (you cannot take a dependency on 4.6.0-preview).  I will fix in the version update PR to update this to 6.0.0

**Pull request merged**
