### PR TITLE
Revert the non-terminating error message for vm cmdlets to a warning message.

### PR DESCRIPTION
**Pull request by hyonholee**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hyonholee__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hylee). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by pcgeek86** [comment]
@hyonholee Why are you reverting this fix? Need more information. Please engage @devigned and @singhkay before moving forward. @markcowl 

Cheers,
**Trevor Sullivan**
Microsoft MVP PowerShell
http://trevorsullivan.net
http://twitter.com/pcgeek86

**Comment by ljhljh235** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/172/

**Comment by pcgeek86** [comment]
@ljhljh235 I don't have access to see that link. Can you be more specific?

**Comment by ljhljh235** [comment]
@pcgeek86 The on demand job is a 1.5 hr long CI job with better coverage. We run it for every pull request right before release. It may not be accessible externally, but we make sure it passes before we merge.
And I believe this revert happens because the original change breaks `New-AzureVM` and `New-AzureQuickVM` when `$ErrorActionPreference` is set to "Stop".

**Pull request merged**
