### PR TITLE
initial update to folder structure

### PR DESCRIPTION
**Pull request by hvedati**
## Checklist

- [ ] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by BethanyZhou** [comment]
Hi @hvedati , could you provide justification why you need to adjust the folder structure?

**Comment by hvedati** [comment]
> Hi @hvedati , could you provide justification why you need to adjust the folder structure?

@BethanyZhou  This is related to this PR - https://github.com/Azure/azure-powershell/pull/21865#issuecomment-1685856759. We are introducing a new submodule StackHCIVm which will be used for all VM resource operations. I was told in the previous PR to open PR against main. I thought it would be easier to just open a new PR.

**Comment by BethanyZhou** [comment]
Hi @hvedati , if you want to add a submodule as https://github.com/Azure/azure-powershell/pull/21865 descripted. Please raise a PR to generation branch instead of main branch.

**Comment by hvedati** [comment]
> Hi @hvedati , if you want to add a submodule as #21865 descripted. Please raise a PR to generation branch instead of main branch.

hi, We keep going back and forth here. I was told in my previous PR to open against PR ( that PR had been opened against generation branch already). Can I please get confirmation  pleaae?

**Comment by wyunchi-ms** [comment]
This is done by https://github.com/Azure/azure-powershell/pull/23230 and https://github.com/Azure/azure-powershell/pull/23154. This PR can be closed.

**Pull request closed without merging**
