### PR TITLE
[DataBox] Move DataBox to main

### PR DESCRIPTION
**Pull request by VeryEarly**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by VeryEarly** [comment]
Hi @dhawal777 ,
please write release notes: https://github.com/Azure/azure-powershell/blob/codegen/DataBox/src/DataBox/Changelog.md
under upcoming release section

**Comment by dhawal777** [comment]
Hey @VeryEarly, One issue and one clarification needed, kindly address whenever you get time

* There is one small issue I saw with one of the command so want to make small change in generation branch, Can I raise a minor PR there. 

* Confirming one thing that this will be override to old preview version right?, like we can't make it 0.1.1, if not then no update is needed to changelog, let it go as "initial preview release only", if we can make 0.1.1 then I will add what additional support we are providing to customer.

**Comment by VeryEarly** [comment]
> Hey @VeryEarly, One issue and one clarification needed, kindly address whenever you get time
> 
> * There is one small issue I saw with one of the command so want to make small change in generation branch, Can I raise a minor PR there.
> * Confirming one thing that this will be override to old preview version right?, like we can't make it 0.1.1, if not then no update is needed to changelog, let it go as "initial preview release only", if we can make 0.1.1 then I will add what additional support we are providing to customer.

o need to worry about the version, we'll handle it at release, you can simply raise PR to generation branch and that's it.
Please add release notes in the comment section along with previous changes, I'll migrate them to main branch.

**Comment by dhawal777** [comment]
Thanks @VeryEarly . Kindly review this https://github.com/Azure/azure-powershell/pull/15686 and in comments placed release notes

**Comment by VeryEarly** [comment]
close this PR, will create new one based on latest generation branch.

**Comment by dhawal777** [comment]
> close this PR, will create new one based on latest generation branch.

Sure Thanks @VeryEarly  Just one call out, I will be OOF from 20 to 24, anything from service side required now for upcoming release.

**Pull request closed without merging**
