### PR TITLE
Fix -Tags in create secondary

### PR DESCRIPTION
**Pull request by dalibormesaric**
## Description
This PR fixes assigning tags in create secondary as per https://github.com/Azure/azure-powershell/issues/6049#issuecomment-384483443.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/ResourceManager/Sql/Commands.Sql/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @dalibormesaric could you please add a test case for this?

**Comment by wyunchi-ms** [comment]
Hi @dalibormesaric could you please take a look at the CI? Do you want to merge your code into `Azure:preview`? I don't think this is a right branch for you.

**Comment by dalibormesaric** [comment]
Hi @wyunchi-ms I just did the same thing as the last time in #7531. Please let me know if I should adjust my PR. Also I started looking into writing test for this, but I still need to find time for that.

**Comment by wyunchi-ms** [comment]
Oh that's one year ago, I think `Azure:preview` was used to preview the module for all the service team. But now every team have its own preview branch.
I suggest two ways for your PR:
1. If you want a signed preview package. You can merge this into the `Azure:Az.sql-preview`. But you need to remember submit another PR to merge to `Azure:master` which we used to do RC release.
1. If you don't need a signed preview package, you can just merge it to `Azure:master`.
Both these depends on the accomplishment of test case.

**Comment by isra-fel** [comment]
> Hi @wyunchi-ms I just did the same thing as the last time in #7531. Please let me know if I should adjust my PR. Also I started looking into writing test for this, but I still need to find time for that.

Hi @dalibormesaric `preview` branch is for `AzureRM`, which was deprecated by `Az`, and will not receive update unless for significant security fixes.
So if the problem you are trying to fix persists in the current `Az` release (aka master branch), please file the PR against master.

Thanks!

**Comment by dalibormesaric** [comment]
Ok, I will do as you instructed. Thanks!

**Pull request closed without merging**
