### PR TITLE
BGP over IPsec ServiceManagement PS cmdlets

### PR DESCRIPTION
**Pull request by lamchester**
Powershell cmdlets for managing BGP over IPsec

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@lamchester__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (chelam). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@lamchester please add test coverage.

**Comment by lamchester** [comment]
Issue #1955 created to track test coverage

**Pull request merged**
