### PR TITLE
changed description for -ManagementGroupName

### PR DESCRIPTION
**Pull request by floschmsft**
changed from "the name of the management group of the new policy definition."
to"the id of the management group of the new policy definition."

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by markcowl** [comment]
@floschmsft I don't believe this change is accurate - if this requires a full id, then the managementgroup example also needs to be changed.  Closing.  Please re-open if you think the example is wrong and would like to fix.

**Comment by liamjvs** [comment]
I've just run into this issue as well. Using the name of the management group results in a policy created somewhere not in the desired management group. The definition is not visible on the Portal nor PowerShell

Using the ID of the management group, the policy is created successfully and visible.

You can also create policies for management groups that don't exist:
```powershell
$policydefinitions = "https://raw.githubusercontent.com/Azure/azure-policy/master/samples/PolicyInitiatives/skus-for-multiple-types/azurepolicyset.definitions.json"
$policysetparameters = "https://raw.githubusercontent.com/Azure/azure-policy/master/samples/PolicyInitiatives/skus-for-multiple-types/azurepolicyset.parameters.json"
New-AzPolicySetDefinition -Name "skus-for-multiple-types-2" -DisplayName "Allowed SKUs for Storage Accounts and Virtual Machines 2" -Description "This policy allows you to speficy what skus are allowed for storage accounts and virtual machines" -PolicyDefinition $policydefinitions -Parameter $policysetparameters -ManagementGroupName "My Fake MG"
```

**Comment by mentat9** [comment]
Just verified correct behavior on current cmdlets. MG name works fine when it's a real MG and fails when it's a fake MG as below console log shows. Please reactivate this issue and provide more details if you still have a repro.

```
[C:\]-> $policydefinitions = "https://raw.githubusercontent.com/Azure/azure-policy/master/samples/PolicyInitiatives/skus-for-multiple-types/azurepolicyset.definitions.json"
[C:\]-> $policysetparameters = "https://raw.githubusercontent.com/Azure/azure-policy/master/samples/PolicyInitiatives/skus-for-multiple-types/azurepolicyset.parameters.json"
[C:\]-> New-AzPolicySetDefinition -Name "skus-for-multiple-types-2" -DisplayName "Allowed SKUs for Storage Accounts and Virtual Machines 2" -Description "This policy allows you to speficy what skus are allowed for storage accounts and virtual machines" -PolicyDefinition $policydefinitions -Parameter $policysetparameters -ManagementGroupName "My Fake MG"
New-AzPolicySetDefinition : AuthorizationFailed : The client 'xxxxxx@ntdev.microsoft.com' with object id '11111111-1111-1111-1111-111111111111' does not have authorization to perform action 'Microsoft.Authorization/policysetdefinitions/write' over scope '/providers/Microsoft.Management/managementgroups/My Fake MG/providers/Microsoft.Authorization/policysetdefinitions/skus-for-multiple-types-2' or the scope is invalid. If access was recently granted, please refresh your credentials.
At line:1 char:1
+ New-AzPolicySetDefinition -Name "skus-for-multiple-types-2" -DisplayN ...
+ ~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~~
+ CategoryInfo          : CloseError: (:) [New-AzPolicySetDefinition], ErrorResponseMessageException
+ FullyQualifiedErrorId : Microsoft.Azure.Commands.ResourceManager.Cmdlets.Implementation.NewAzurePolicySetDefinitionCmdlet

[C:\]->
```

**Comment by liamjvs** [comment]
Back in June, it was a bug and was fixed under ticket number 119062824000582 and IcM 132419863.

Working as expected now.

**Pull request closed without merging**
