### PR TITLE
Alecb generation 2024 01 16 preview

### PR DESCRIPTION
**Pull request by alec-baird**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [ ] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [x] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by alec-baird** [comment]
There seems to be a pipeline build issue that is unrelated to this PR? https://dev.azure.com/azclitools/public/_build/results?buildId=158503&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=8aac088c-bc37-5d41-cf85-af8ebfb740e5&l=1502

**Comment by NoriZC** [comment]
> There seems to be a pipeline build issue that is unrelated to this PR? https://dev.azure.com/azclitools/public/_build/results?buildId=158503&view=logs&j=ca395085-040a-526b-2ce8-bdc85f692774&t=8aac088c-bc37-5d41-cf85-af8ebfb740e5&l=1502

Yes I am confirming with my teammates about the issue. Meanwhile you can try merging generation branch and see whether the issue resolved.

**Comment by NoriZC** [comment]
Hi @alec-baird Yes you need you merge the latest generation branch to fix the issue.

**Comment by alec-baird** [comment]
> Hi @alec-baird Yes you need you merge the latest generation branch to fix the issue.

Done.

**Comment by alec-baird** [comment]
@NoriZC , @isra-fel , All of my tests passed locally but there seem to be a few failing your CI, is there a bug in CI still?

**Review by NoriZC — DISMISSED** [review]

**Comment by NoriZC** [comment]
The new pr: https://github.com/Azure/azure-powershell/pull/25035

**Pull request closed without merging**
