### PR TITLE
Check device type for Remote Support cmdlets between HCIv2 and AzureEdge

### PR DESCRIPTION
**Pull request by swashtek**
## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by swashtek** [comment]
> please create a new branch from https://github.com/Azure/azure-powershell/tree/generation and migrate your changes there and raise a new PR against https://github.com/Azure/azure-powershell/tree/generation
> 
> please also update docs in your new PR

It seems I don't have access to create branch from generation branch, I can only create of main branch. 
Can you please share how can I create branch from generation branch? Thanks.

**Comment by swashtek** [comment]
> please create a new branch from https://github.com/Azure/azure-powershell/tree/generation and migrate your changes there and raise a new PR against https://github.com/Azure/azure-powershell/tree/generation
> 
> please also update docs in your new PR

Hi, I am unable to push the changes to my branch created from generation branch. 
I cloned azure-powershell:main branch and switched to generation branch and create another branch of generation, ported the changes and pushing changes upstream failed. Can you please share more info if I need to request any access to perform operations? Thanks. 

Exception:
 azure-powershell  git push --set-upstream origin <username>/generation
remote: Permission to Azure/azure-powershell.git denied to <username>.
fatal: unable to access 'https://github.com/Azure/azure-powershell.git/': The requested URL returned error: 403

**Comment by VeryEarly** [comment]
> > please create a new branch from https://github.com/Azure/azure-powershell/tree/generation and migrate your changes there and raise a new PR against https://github.com/Azure/azure-powershell/tree/generation
> > please also update docs in your new PR
> 
> Hi, I am unable to push the changes to my branch created from generation branch. I cloned azure-powershell:main branch and switched to generation branch and created a branch of generation, ported the changes and then pushing changes upstream failed. Can you please share more info if I need to request any access to perform operations? Thanks.
> 
> Exception: azure-powershell  git push --set-upstream origin /generation remote: Permission to Azure/azure-powershell.git denied to . fatal: unable to access 'https://github.com/Azure/azure-powershell.git/': The requested URL returned error: 403

Hi please do not push changes to upstream, you should push changes to your new created branch and create PR from it targeting Azure/generation
please share complete git steps so I can see where went wrong.

**Comment by swashtek** [comment]
> > > please create a new branch from https://github.com/Azure/azure-powershell/tree/generation and migrate your changes there and raise a new PR against https://github.com/Azure/azure-powershell/tree/generation
> > > please also update docs in your new PR
> > 
> > 
> > Hi, I am unable to push the changes to my branch created from generation branch. I cloned azure-powershell:main branch and switched to generation branch and created a branch of generation, ported the changes and then pushing changes upstream failed. Can you please share more info if I need to request any access to perform operations? Thanks.
> > Exception: azure-powershell  git push --set-upstream origin /generation remote: Permission to Azure/azure-powershell.git denied to . fatal: unable to access 'https://github.com/Azure/azure-powershell.git/': The requested URL returned error: 403
> 
> Hi please do not push changes to upstream, you should push changes to your new created branch and create PR from it targeting Azure/generation please share complete git steps so I can see where went wrong.

Thanks for reply. 
Steps: 

1. C:\Repos\pwshl> git clone https://github.com/Azure/azure-powershell.git
2. C:\Repos\pwshl\azure-powershell [main ≡]> git checkout generation
3. C:\Repos\pwshl\azure-powershell [generation ≡]> git checkout -b user/<user_name>/generation
4.  git add .
5. git commit -m "Message"
6. git push --set-upstream origin user/<user_name>/generation

Please let me know if you need more info. Thanks.

**Comment by VeryEarly** [comment]
> > > > please create a new branch from https://github.com/Azure/azure-powershell/tree/generation and migrate your changes there and raise a new PR against https://github.com/Azure/azure-powershell/tree/generation
> > > > please also update docs in your new PR
> > > 
> > > 
> > > Hi, I am unable to push the changes to my branch created from generation branch. I cloned azure-powershell:main branch and switched to generation branch and created a branch of generation, ported the changes and then pushing changes upstream failed. Can you please share more info if I need to request any access to perform operations? Thanks.
> > > Exception: azure-powershell  git push --set-upstream origin /generation remote: Permission to Azure/azure-powershell.git denied to . fatal: unable to access 'https://github.com/Azure/azure-powershell.git/': The requested URL returned error: 403
> > 
> > 
> > Hi please do not push changes to upstream, you should push changes to your new created branch and create PR from it targeting Azure/generation please share complete git steps so I can see where went wrong.
> 
> Thanks for reply. Steps:
> 
> 1. C:\Repos\pwshl> git clone https://github.com/Azure/azure-powershell.git
> 2. C:\Repos\pwshl\azure-powershell [main ≡]> git checkout generation
> 3. C:\Repos\pwshl\azure-powershell [generation ≡]> git checkout -b user/<user_name>/generation
> 4. git add .
> 5. git commit -m "Message"
> 6. git push --set-upstream origin user/<user_name>/generation
> 
> I'm attempting to create a branch from generation using below instructions but I don't see any options to create branch
> 
> https://docs.github.com/en/pull-requests/collaborating-with-pull-requests/proposing-changes-to-your-work-with-pull-requests/creating-and-deleting-branches-within-your-repository
> 
> Please let me know if you need more info. Thanks.

after commit, do git push origin head, you will create branch user/<user_name>/generation, and please raise new PR from this branch to generation

**Comment by VeryEarly** [comment]
close, please see #19948

**Pull request closed without merging**
