### PR TITLE
Ipv6 changes

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**
Add NetworkInterfaceIPConfiguration cmdlets
Fix bugs in LB scenarios
 Fix : https://github.com/Azure/azure-powershell/issues/2133

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
@DeepakRajendranMsft please resolve merge conflicts

**Comment by DeepakRajendranMsft** [comment]
@hovsepm conflicts have been resolved and CI succeeds. ready for merge

**Pull request merged**
