### PR TITLE
Application Gateway WAF top level resource and Custom Rules

### PR DESCRIPTION
**Pull request by azhao155**
## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by azhao155** [comment]
https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/253

**Comment by number213** [comment]
I don't think we can merge PR until Swagger specs have been merged in master and SDK with them released (local SDK package is for development process, since it's unsigned, CI won't pass). @MikhailTryakhov to confirm
Also, please take a look at help errors: https://azuresdkci.westus2.cloudapp.azure.com/job/powershell/11156/artifact/artifacts/ValidateHelpIssues.csv/*view*/

**Comment by azhao155** [comment]
@number213 I have pushed the fix for the help files. The swagger pr is already reviewed, it should be merged soon, and i don't think we need to wait for the sdk release to merge powershell change, i have done that last time with local sdk, Please check this pr: 
https://github.com/Azure/azure-powershell/pull/7425

**Comment by azhao155** [comment]
@number213 for the travis: it has bunch of not related errors:
EXEC : PowerShell error Record: Unable to find a matching HTTP request for URL 'GET /subscriptions/947d47b4-7883-4bb9-9d85-c5e8e2f572ce/resourceGroups/ps9073/providers/Microsoft.Network/expressRouteCircuits/ps7348?api-version=2018-12-01'. Calling method Item(). [/home/travis/build/Azure/azure-powershell/build.proj]

and for the build, although i updated all the .csproj file, it still can't find the nugget package, does that mean i need to update the package.config?

**Comment by cormacpayne** [comment]
@azhao155 the `network-january-release` branch was just merged back into the `master` branch -- please pull the latest from the `master` branch and resolve the above merge conflicts

**Comment by azhao155** [comment]
@cormacpayne I have resolved the conflict, the swagger change is based on network-february-release and generate the local sdk for the pr, is that ok?

**Comment by number213** [comment]
@azhao155 the issue with CI right now is that there is a new RP PrivateDns, it's tests use an older Network SDK version, and that somehow causes issues on CI when it tries to load a newer SDK instead.
I've set PrivateDns to use the same SDK version Network uses, that fixed the error, but now DNS' test recordings are outdated due to API version change.
I tried re-recording them but tests are failing for me. I'll reach out to the last person who worked on PrivateDns and ask them to record tests for us.

**Comment by azhao155** [comment]
@number213 for the swagger pr, i have some change, could you help to generate the local sdk once it's merged and i will run the new recording test for it, Thanks a lot!

**Comment by vladimir-shcherbakov** [comment]
@azhao155  Please resolve the merge conflict.

**Comment by azhao155** [comment]
@number213 https://github.com/Azure/azure-rest-api-specs/pull/5341 have swagger merged

**Comment by number213** [comment]
@azhao155 Re-generated SDK, please take a look

**Comment by azhao155** [comment]
@vladimir-shcherbakov resolved the conflict.,

**Comment by azhao155** [comment]
@MikhailTryakhov now the validation passed also we have swagger merged, could you approve this request? also @asridharan for review

**Comment by azhao155** [comment]
@number213 Thanks for helping fix the validation issue!

**Comment by maddieclayton** [comment]
@number213 @MikhailTryakhov @azhao155 Is this intended to be targeted at the master branch or should this be pointing to the network branch?

**Comment by azhao155** [comment]
it should be target for network-february. i will rebase.

**Comment by maddieclayton** [comment]
Closing in favor of https://github.com/Azure/azure-powershell/pull/8776/files

**Pull request closed without merging**
