### PR TITLE
Fixing bugs in restore and get\list recoverypoint cmdlet for enrcyptedVM

### PR DESCRIPTION
**Pull request by mkherani**

### CODE REVIEW

**Comment by mkherani** [comment]
Squash the 2 commits into one and recreated PR. Please review.

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@mkherani  This change still contains 24 commits, including merge commits.  Please rebase this to reduce the number fo commits, and remove unnecessary commits.

**Comment by mkherani** [comment]
Closing this PR. Created a new PR with another branch. https://github.com/Azure/azure-powershell/pull/2823

**Pull request closed without merging**
