### PR TITLE
[Release.1.3.2] Change api-version for policy and locks

### PR DESCRIPTION
**Pull request by vivsriaus**
- Change api version for policy and locks
- Fix resource lock cmdlets to use LockId as ResourceId

### CODE REVIEW

**Comment by vivsriaus** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
on-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/668/

**Comment by vivsriaus** [comment]
@azuresdkci test this please

**Comment by vivsriaus** [comment]
new on-demand: http://azuresdkci.cloudapp.net/job/powershell-demand/673/

**Pull request merged**
