### PR TITLE
Batch September release: Jobauto-complete, Reactivate tasks, APR on tasks and hotfix

### PR DESCRIPTION
**Pull request by matthew-rollitt**
## This PR contains a few features: Job can now terminate if a tasks fails with the right exit conditions, Application Package can now be referenced on cloud tasks and job manager task, task that fails can now be reactivated and changed UpdateAndActivate changed to UploadAndActivate

This checklist is used to make sure that common issues in a pull request are covered by the creator. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270%28v=vs.85%29.aspx).

Below in **Overall Changes**, check off the boxes that apply to your PR. For the categories that you did not check off, you can remove them from this body. Within each of the categories that you did select, make sure that you can check off **all** of the boxes. 

For information on cleaning up the commits in your pull request, click [here](../documentation/cleaning-up-commits.md).
## Overall Changes
- [x] [**MANDATORY** - General changes](#general)
- [x] [**MANDATORY** - Add/remove/edit test(s)](#tests)
- [x] [Add/remove/edit cmdlet(s)](#cmdlet-signature)
- [x] [Add/remove/edit parameter(s)](#parameters)
- [ ] [Edit pipeline parameters](#parameters-and-the-pipeline)
### General
- [x] Title of the PR is clear and informative
- [ ] There are a small number of commits that each have an informative message
- [ ] If it applies, references the bug/issue that the PR fixes
- [x] All files have the Microsoft copyright header
- [x] Cmdlets refer to management libraries through nuget references - no dlls are checked in
- [x] The PR does not introduce breaking changes (unless a major version change occurs in the assembly and module)
### Tests
- [x] PR includes test coverage for the included changes
- [x] Tests must use xunit, and should either use Moq to mock management client calls, or use the scenario test framework
- [x] PowerShell scripts used in tests must not use hard-coded values for location
- [x] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for existing resources
- [ ] Tests should not use App.config files for settings
- [ ] Tests should use the built-in PowerShell functions for generating random names when unique names are necessary - this will store names in the test recording
- [x] Tests should use Start-Sleep to pause rather than Thread.Sleep
### Cmdlet Signature
- [x] Cmdlet name uses an approved PowerShell verb - use the enums for `VerbsCommon`, `VerbsCommunication`, `VerbsLifecycle`, `VerbsOther` whenever possible
- [ ] Cmdlet noun name uses the AzureRm prefix for management cmdlets, and the Azure prefix for data plane cmdlets
- [x] Cmdlet specifies the `OutputType` attribute if any output is produced; if the cmdlet produces no output, it should implement a `PassThrough` parameter
- [x] If the cmdlet makes changes or has side effects, it should implement `ShouldProcess` and have `SupportShouldProcess = true` specified in the cmdlet attribute. See a discussion about correct `ShouldProcess` implementation [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change)
- [x] Cmdlets should derive from AzureRmCmdlet for management cmdlets, and AzureDataCmdlet for data cmdlets
- [ ] If multiple parameter sets are implemented, the cmdlet should specify a `DefaultParameterSetName` in its cmdlet attribute
### Parameters
- [ ] Cmdlets should have no more than four positional parameters
- [ ] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets
- [ ] Parameter types should not expose types from the management library - complex parameter types should be defined in the module
- [ ] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet
- [ ] Parameters should be explicitly marked as Mandatory or not, and should contain a HelpMessage
- [ ] No parameter is of type `object`.
  - Management cmdlets should have the following parameters and aliases:
    - ResourceGroupName with (optional) alias to `ResourceGroup` type string marked as [ValueFromPipelineByPropertyName]
    - Name with alias to `ResourceName` type string marked as [ValueFromPipelineByPropertyName]
    - Location (if appropriate) type string
    - Tag, type `HashTable`
### Parameters and the Pipeline
- [ ] Complex parameters should take values from the pipeline when possible, and certainly when they match the output type of another cmdlet
- [ ] Only one parameter should use ValueFromPipeline per parameter set; parameters from different parameter sets may have this attribute, but should not be convertible
- [ ] No parameter is of type `object`
- [x] Each management cmdlet should have a parameter set that takes `ResourceGroupName` and `Name` from the pipeline by property value
- [x] For a given resource type, it should be possible to pipe the output of `Get` and `New` cmdlets to the input of `Set`, `Update`, `Remove` and other action cmdlets for that resource

### CODE REVIEW

**Comment by cormacpayne** [comment]
@matthew-rollitt in the file `src\ResourceManager\AzureBatch\Commands.Batch\packages.config`, the versions of ClientRuntime were downgraded:

```
<package id="Microsoft.Rest.ClientRuntime" version="2.3.1" targetFramework="net45" />
<package id="Microsoft.Rest.ClientRuntime.Azure" version="3.3.1" targetFramework="net45" />
<package id="Microsoft.Rest.ClientRuntime.Azure.Authentication" version="2.2.5-preview" targetFramework="net45" />
```

Why were these changes made?

**Comment by cormacpayne** [comment]
@matthew-rollitt in this file `src\ResourceManager\AzureBatch\Commands.Batch.Test\ScenarioTests\ScenarioTestHelpers.cs`, the following line (line 489) uses the `Sleep` method:

```
Sleep(20000);
```

Please use [this wrapper code](https://github.com/Azure/azure-powershell/blob/dev/src/Common/Commands.Common/TestMockSupport.cs) to have `Sleep` used only in record mode.

**Comment by matthew-rollitt** [comment]
@cormacpayne Looks like this happened due to a rebase from one of my branches, can be reversed.

---
In reply to: [248447394](https://github.com/Azure/azure-powershell/pull/2952#issuecomment-248447394) [](ancestors = 248447394)

**Comment by matthew-rollitt** [comment]
@cormacpayne I'll update this thanks.

---
In reply to: [248450582](https://github.com/Azure/azure-powershell/pull/2952#issuecomment-248450582) [](ancestors = 248450582)

**Comment by cormacpayne** [comment]
:shipit:

**Comment by cormacpayne** [comment]
On-demand: **waiting**

**Comment by cormacpayne** [comment]
@matthew-rollitt Hey Matthew, would you mind pulling from dev to get the latest changes that fix the on-demand build?

**Comment by cormacpayne** [comment]
On-demand: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1205/

**Pull request merged**
