### PR TITLE
P2S and SKU feature new command lets

### PR DESCRIPTION
**Pull request by Nilambari**

### CODE REVIEW

**Comment by jianghaolu** [comment]
@azuresdkci retest this please

**Comment by Nilambari** [comment]
Build passed. Can you help accept PR? Thanks.

**Comment by jianghaolu** [comment]
on-demand failed here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/406/. The failures are in Sql tests. If you don't know what the failures are about, I'm starting another one here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/407/.

**Comment by Nilambari** [comment]
Yes, I am not very sure about SQL tests. Network tests are passed. Also, the second on-demand job is passed.

**Pull request merged**
