### PR TITLE
VMSS Instance Mix Flex Update Bug Fix

### PR DESCRIPTION
**Pull request by msdorahu**
## Description

VMSS Instance Mix Update was only adding new sizes instead of replacing the sizes with the new set of sizes. Changed to during update always use the new list of sizes provided. Update feature was recently enabled in EastUS2 and tests were updated accordingly.

Design spec: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/1456
Original PR: https://github.com/Azure/azure-powershell/pull/25980

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by Nickcandy** [comment]
@msdorahu Hi, please mask cred info manually from test file:
1. Credential Scanner Error CSCAN-GENERAL0060 - File: SecurityTmp/src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfile.json:SecurityTmp/src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfile.json. Line: 2514. Column 313. 
 2. Credential Scanner Error CSCAN-GENERAL0060 - File: SecurityTmp/src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfile.json:SecurityTmp/src/Compute/Compute.Test/SessionRecords/Microsoft.Azure.Commands.Compute.Test.ScenarioTests.VirtualMachineScaleSetTests/TestVirtualMachineScaleSetSkuProfile.json. Line: 2604. Column 312.

**Review by haagha — APPROVED** [review]

**Comment by Nickcandy** [comment]
@msdorahu  Hi there, you missed your changelog here. Please help to raise a pr to fix it.

**Comment by msdorahu** [comment]
hi @Nickcandy, the previous PR had the change log: https://github.com/Azure/azure-powershell/pull/25980
since this will be part of the same release, it is already covered

**Pull request merged**
