### PR TITLE
[Storage] Support blob query acceleration

### PR DESCRIPTION
**Pull request by blueww**
## Description

design pass review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/676
This PR also upgrade Azure.Core to 1.3.0, since Storage SDK dependency upgrade.
Please merge it after 8/4 PSH release is out. (the change log might need resolve conflict.)

By upgrade SDK, also can resolve the issue: https://github.com/Azure/azure-powershell/issues/12553

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by blueww** [comment]
@erich-wang 
Would you please suggest how to fix the Az.StorageSync test case fail, related with Azure.Core:

> PowerShell Error Record : Test failed due to a non-empty error stream. First error : PowerShell Error Record: Could not load file or assembly 'Azure.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621) [D:\a\1\s\build.proj]
>   Exception:System.IO.FileLoadException: Could not load file or assembly 'Azure.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'. Could not find or load a specific file. (Exception from HRESULT: 0x80131621)
>    File name: 'Azure.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8' ---> System.IO.FileLoadException: Could not load file or assembly 'Azure.Core, Version=1.3.0.0, Culture=neutral, PublicKeyToken=92742159e12e44c8'.

**Comment by blueww** [comment]
Add 2 static analysis exception:
1. `New-AzStorageBlobQueryConfig` don't need Should process, since it will only create a local object, won't change anything on server.
2. `Query-AzStorageBlob`, "Query" is not an approved verb. 
The current cmdlet name pass design review in : Azure/azure-powershell-cmdlet-review-pr#676
I can't find an approved verb which match the function of: Query a blob content with a query expression, and only return the subset of blob content which matches the query expression.  If it's required to change the verb, do you have any suggestion for the verb?

**Comment by isra-fel** [comment]
> Add 2 static analysis exception:
> 
> 1. `New-AzStorageBlobQueryConfig` don't need Should process, since it will only create a local object, won't change anything on server.
> 2. `Query-AzStorageBlob`, "Query" is not an approved verb.
> 
> * The current cmdlet name pass design review in : [Azure/azure-powershell-cmdlet-review-pr#676](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/676)
> * I can't find an approved verb which match the function of: Query a blob content with a query expression, and only return the subset of blob content which matches the query expression.
> * If it's required to change the verb, please suggest the verb, and cmdlet name?

The first suppression is valid, but I'm afraid we can't accept the second. Let's discuss in the design issue  [Azure/azure-powershell-cmdlet-review-pr#676](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/676)

**Comment by blueww** [comment]
@isra-fel 
I have removed the 2nd breaking change exception, and change the cmdlet name from "Query-AzStorageBlob" to "Get-AzStorageBlobQueryResult".
Please help to review again.

**Pull request merged**
