### PR TITLE
RemoteApp: RestartVm teanat admin cmdlet

### PR DESCRIPTION
**Pull request by xamarsinx**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@amarsi__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (amarsin). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by amarsi** [comment]
@markcowl Mark, should I start on-demand builds for it or you will take care?

**Comment by amarsi** [comment]
Started on-demand builds
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/141/
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/428/

**Comment by amarsi** [comment]
On-demand builds are finished successfully. Please integrate the change if it looks OK.

**Pull request merged**
