### PR TITLE
Pass auth headers for virtualHubVnetConnection support across different tenants 

### PR DESCRIPTION
**Pull request by nagula-ritvika**
## Description
The VirtualHubVnetConnection resource uses VnetPeering in its underlying implementation. To support peering a vnet to a hub across different tenants, we need to pass auxiliary authorization headers. These headers are not being passed due to a code bug.

Updated the cmdlets New-AzVirtualHubVnetConnection and Update-AzVirtualHubVnetConnection to pass the required headers. 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by dedhar** [comment]
this.CreateOrUpdateVirtualHub(this.ResourceGroupName, this.ParentResourceName, parentVirtualHub, parentVirtualHub.Tag, auxAuthHeader);
----- What happens if auxAuthHeader is null? do you want to initialize to empty dictionary

**Comment by dedhar** [comment]
Do you have to fix Update hub also? Can update or create hub ever pass hub vnet connection in the input request and hit same issue

**Comment by nagula-ritvika** [comment]
> ```
>                 this.CreateOrUpdateVirtualHub(this.ResourceGroupName, this.ParentResourceName, parentVirtualHub, parentVirtualHub.Tag, auxAuthHeader);
> ```
> 
> ----- What happens if auxAuthHeader is null? do you want to initialize to empty dictionary

If the auth header is null then the code calls the CreateORUpdate method which internally takes cares of the empty dictionary.

**Comment by nagula-ritvika** [comment]
> Do you have to fix Update hub also? Can update or create hub ever pass hub vnet connection in the input request and hit same issue

yup, you were right. updated the hub cmdlets also.

**Comment by dedhar** [comment]
Changes look good to me. Signing off from vWAN Team

**Comment by nagula-ritvika** [comment]
Hi, can someone start the build again please

**Pull request merged**
