### PR TITLE
Fix Deployment Type Issue #26752

### PR DESCRIPTION
**Pull request by tsmallig33**
## Description

Fixes issue https://github.com/Azure/azure-powershell/issues/26752. Updates to try to deserialize response after receiving 202 from long running operations. 

Tries to deserialize to DeploymentExtended for success as ValidationErrors and CloudErrors are handled as exceptions that are thrown. 

## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [X] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [X] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by VeryEarly — APPROVED** [review]

**Comment by Jigar191089** [comment]
Hi @VeryEarly,
it seems even after this PR is completed we get the same error.
image
image

Note : We are using template spec for deployment to ADF. Support ticket 2411250050002160  is raised from last 10 days.

**Comment by Jigar191089** [comment]
@sgoyal100 same for us. Sometime retry works but most of the times it fails.

**Comment by Jigar191089** [comment]
Even after using specific version of Az powershell, we are getting same error
image

**Comment by VeryEarly** [comment]
Hi @Jigar191089 @sgoyal100 , please expect fix in Az.Resources 7.8.0 on 2015-01-13 PST

**Pull request merged**
