### PR TITLE
Azurerm.Profile not listed in "requiredmodules"

### PR DESCRIPTION
**Pull request by whiggs**
## Description

Adding Azurerm.profile to list of required modules, which is missing. This creates an issue where, after the azurerm module has been installed on a fresh machine (did not have the module installed prior), the azurerm.profile module is not being imported into the powershell session with the other azurerm modules, and the user has to either a) import the module manually, or b) restart the powershell console. By adding the azurerm.profile module to the list of required modules (why was it removed in the first place?), this should fix this issue.>

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by whiggs** [comment]
I have a powershell script which has a gui and uses background jobs in order to ensure that the gui remains responsive when the events associated with its controls are being executed.  When the GUI loads, the GUI_loads event is supposed to install the azurerm module on the machine, connect to it with a set of credentials, and access some values in a key vault.  However, when the project is run on a clean vm (without azurerm already installed on it), the first run generates the below errors:
image
However, it is not an issue with the code (as I did run the "connect-azurermaccount command) because when I close the script and immediately launch it again, it loads without error.  Please accept pull request.  If the specified change does not resolve the issue, then find what does, but I am confident that it is.

**Comment by MiYanni** [comment]
@whiggs It is listed. It is the first entry in RequiredModules:
https://github.com/Azure/azure-powershell/blob/17b6a038a0e2508769334827f674921bd32c222a/tools/AzureRM/AzureRM.psd1#L54

If you are having an issue, please [submit an issue](https://github.com/Azure/azure-powershell/issues/new). Thank you.

**Comment by whiggs** [comment]
@cormacpayne I have no problem providing the script (with sensitive info pulled out of course), but this is the section specifically throwing the error:
`
Get-PackageProvider -Name NuGet -ForceBootstrap -Force
		Set-PSRepository -Name PSGallery -InstallationPolicy Trusted
		iex ((New-Object System.Net.WebClient).DownloadString('https://chocolatey.org/install.ps1'))
		import-module "C:\ProgramData\chocolatey\helpers\chocolateyInstaller.psm1" -Force
		import-module "C:\ProgramData\chocolatey\helpers\chocolateyProfile.psm1" -Force
		Update-SessionEnvironment
		#install the latest version of the departmodule from the VSTS package feed.
		choco upgrade NuGet.commandline -y
		Update-SessionEnvironment
		NuGet update -self
		Install-Module Powershellget -Repository PSGallery -RequiredVersion 1.5.0.0 -Force -AllowClobber
		Remove-Module powershellget -Force
		Import-Module powershellget -RequiredVersion 1.5.0.0 -Force
		If (!(Test-Path "$env:ProgramFiles\WindowsPowerShell\Modules\PoshInternals"))
		{
			Install-Module PoshInternals -AllowClobber -Force -Repository "PSGallery"
		}
		Else
		{
			Update-Module PoshInternals -Force
		}
		If (!(Test-Path "$env:ProgramFiles\WindowsPowerShell\Modules\AzureRM.KeyVault"))
		{
			Install-Module AzureRm -AllowClobber -Force -Repository "PSGallery"
		}
		else
		{
			Update-Module Azurerm -Force
		}
		If (!(Test-Path $env:ProgramFiles\WindowsPowerShell\Modules\SharePointPnPPowerShellOnline))
		{
			Install-Module SharePointPnPPowerShellOnline -AllowClobber -Force -Repository "PSGallery"
		}
		Else
		{
			Update-Module SharePointPnPPowerShell* -Force
		}
		If (!(Test-Path $env:ProgramFiles\WindowsPowerShell\Modules\MSOnline))
		{
			Install-Module MSOnline -AllowClobber -Force -Repository "PSGallery"
		}
		Else
		{
			Update-Module MSOnline -Force
		}

Import-Module AzureRM
		#test to see if the Remote server administration tools are installed on the system.
		#If they are not, install them.
		Try
		{
			Import-Module Activedirectory -Force -ErrorAction Stop
		}
		Catch
		{
			$wmi = Get-WmiObject -Class Win32_OperatingSystem -Namespace Root\cimv2 -Property "caption"
			If ($wmi.caption -like "*server*")
			{
				Add-WindowsFeature -Name RSAT-AD-Tools
				Add-windowsFeature -Name RSAT-AD-PowerShell
				Import-Module ActiveDirectory
			}
			Else
			{
				Install-RSATTools
				Import-Module ActiveDirectory
			}
		}
		choco upgrade serviceassistant --source https://www.myget.org/F/serviceassistant/api/v2 -y
		choco upgrade sharepointconsole --source https://www.myget.org/F/sharepointconsole/api/v2 -y
		Import-Module "$env:ProgramFiles\SharePoint Online Management Shell\Microsoft.Online.SharePoint.PowerShell" -Force

Connect-AzureRmAccount -Credential $creds
		if (Test-Path "$env:APPDATA\azure.json")
		{
			Remove-Item "$env:APPDATA\azure.json" -Force
		}
		Save-AzureRmContext -Path "$env:APPDATA\azure.json" -Force #this is likely where the error is occuring, since it is the first command other than the connect-azurermaccount.  But if it is an issue where the "azurerm.profile" module is not being imported, it may not be this one.
		$clientid = $null
		$clientsecret = $null
		$passphrase = $null
		$privatekey = $null
		$publickeyid = $null
		$enterpriseid = $null
		$clientid2 = $null
		$clientsecret2 = $null
		$passphrase2 = $null
		$privatekey2 = $null
		$publickeyid2 = $null
		$enterpriseid2 = $null
		$secrets = Get-AzureKeyVaultSecret -VaultName boxauth #This is the other possible command which could be generating the error.  The last command relating to azurerm in the faulty section.
		Foreach ($item in $secrets)
		{
			$azkey = Get-AzureKeyVaultSecret -name $item.Name -VaultName $item.VaultName
			If ($azkey.Name -like "clientID")
			{
				$clientid = $azkey.SecretValueText
			}
			ElseIf ($azkey.Name -like "clientSecret")
			{
				$clientsecret = $azkey.SecretValueText
			}
			Elseif ($azkey.Name -like "passphrase")
			{
				$passphrase = $azkey.SecretValueText
			}
			ElseIf ($azkey.Name -like "privateKey")
			{
				$privatekey = $azkey.SecretValueText #.replace("\n","`n").ToString()
			}
			Elseif ($azkey.Name -like "publicKeyID")
			{
				$publickeyid = $azkey.SecretValueText
			}
			Elseif ($azkey.Name -like "enterpriseID")
			{
				$enterpriseid = $azkey.SecretValueText
			}
			If ($azkey.Name -like "clientID2")
			{
				$clientid2 = $azkey.SecretValueText
			}
			ElseIf ($azkey.Name -like "clientSecret2")
			{
				$clientsecret2 = $azkey.SecretValueText
			}
			Elseif ($azkey.Name -like "passphrase2")
			{
				$passphrase2 = $azkey.SecretValueText
			}
			ElseIf ($azkey.Name -like "privateKey2")
			{
				$privatekey2 = $azkey.SecretValueText #.replace("\n","`n").ToString()
			}
			Elseif ($azkey.Name -like "publicKeyID2")
			{
				$publickeyid2 = $azkey.SecretValueText
			}
			Elseif ($azkey.Name -like "enterpriseID2")
			{
				$enterpriseid2 = $azkey.SecretValueText
			}
			Else
			{
			}
		}
`

**Comment by whiggs** [comment]
And this is the return (it does look like it was the Get-AzureKeyVaultSecret)

`

WARNING: It's very likely you will need to close and reopen your shell 
  before you can use choco.
WARNING: You can safely ignore errors related to missing log files when 
  upgrading from a version of Chocolatey less than 0.9.9. 
  'Batch file could not be found' is also safe to ignore. 
  'The system cannot find the file specified' - also safe.
PATH environment variable does not have C:\ProgramData\chocolatey\bin in it. Adding...
The names of some imported commands from the module 'Microsoft.Online.SharePoint.PowerShell' include unapproved verbs that might make them less discoverable. To find the commands with unapproved verbs, run the Import-Module command again with the Verbose parameter. For a list of approved verbs, type Get-Verb.
Run Connect-AzureRmAccount to login.
    + CategoryInfo          : CloseError: (:) [Get-AzureKeyVaultSecret], PSInvalidOperationException
    + FullyQualifiedErrorId : Microsoft.Azure.Commands.KeyVault.GetAzureKeyVaultSecret
    + PSComputerName        : localhost
 
Exception calling "AdminToken" with "0" argument(s): "{"error":"invalid_client","error_description":"The client credentials are invalid"}"
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BoxException
    + PSComputerName        : localhost
 
Exception calling "AdminToken" with "0" argument(s): "{"error":"invalid_client","error_description":"The client credentials are invalid"}"
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : BoxException
    + PSComputerName        : localhost
 
Exception calling "Wait" with "0" argument(s): "One or more errors occurred."
    + CategoryInfo          : NotSpecified: (:) [], MethodInvocationException
    + FullyQualifiedErrorId : AggregateException
    + PSComputerName        : localhost


 `

**Comment by cormacpayne** [comment]
@whiggs Hey William, I'm going to close this PR in favor of the issue that you recently opened: https://github.com/Azure/azure-powershell/issues/6214

**Pull request closed without merging**
