### PR TITLE
Fixing KeyOps documentation for Wrap / Unwrap

### PR DESCRIPTION
**Pull request by felickz**
As per    https://tools.ietf.org/html/draft-ietf-jose-json-web-key-41

* "wrapKey" (encrypt key)
* "unwrapKey" (decrypt key and validate decryption, if applicable)

These values are required as inputs to the KeyOps parameter
ex: "key_ops":["wrapKey","unwrapKey"]

Using the value "wrap" and "unwrap" is not correct.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by markcowl** [comment]
@felickz Agreed that these are the correct key_ops values per the specification, but unsure whether the operations match exactly, or are mapped in the service.  Looping in some KeyVault folks

**Comment by markcowl** [comment]
@felickz Also, could you add an entry to the KeyVault module Changelog for this change [here](https://github.com/Azure/azure-powershell/blob/master/src/KeyVault/KeyVault/ChangeLog.md)

**Comment by markcowl** [comment]
@RandalliLama Can you validate that these options will correctly work for this parameter

**Comment by wyunchi-ms** [comment]
Hi @felickz , could you please resolve the conflicts? Thanks a lot.

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Thanks for your contribution again @felickz 😀  . As this PR contains too many conflicts I cherry-picked your commit to #11810 , so I'm closing this one.

**Pull request closed without merging**
