### PR TITLE
Fixing restore and recovery bug 

### PR DESCRIPTION
**Pull request by mkherani**

### CODE REVIEW

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@mkherani POlease include tests to catch this bug and prevent regressions

**Comment by mkherani** [comment]
@markcowl Added the test coverage. Please Merge the PR.

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1108/

LGTM once this passes.  Note that you might need to rebase on the latest commit for this to pass

**Comment by mkherani** [comment]
@markcowl  Thanks!! On demand run was green. I did rebase to latest commit as well. Please merge the PR once the run will be green.

**Pull request merged**
