### PR TITLE
New powershell cmdlets for CMv2

### PR DESCRIPTION
**Pull request by hofattahMicrosoft**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by hofattahMicrosoft** [comment]
Irina,

Please find my answer below

**Comment by VeryEarly** [comment]
Hi @hofattahMicrosoft ,

Please fix CI issue

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by msJinLei** [comment]
@hofattahMicrosoft  could you resolve conflicts?

**Comment by hofattahMicrosoft** [comment]
> You shouldn't remove old set of parameters (like source and destination) from connection monitor.
> We need to have both sets of parameters.
> Ideally, if customer set the old parameters, we need to make a call with 2019-06-01 version. If it’s a new set of parameters, it’ll be current version.
> You also need to validate that customer didn’t messed up parameters from different sets and throw validation exception if this is the case.
> The API version is hardcoded in SDK. So, to implement this, you can try the following approach:
> 
> In Network SDK repo you can add custom methods with 2019-06-01 API version (in ConnectionMonitorsOperartions) to "azure-sdk-for-net\sdk\network\Microsoft.Azure.Management.Network\src\Customizations"
> This will be shipped with official SDK release
> You can reference this custom method when making a PUT call for connection monitor (if customer set old parameters)
> 
> This is the reference on file which you will need to add (and update with old API version in SDK: https://github.com/Azure/azure-sdk-for-net/blob/master/sdk/network/Microsoft.Azure.Management.Network/src/Generated/ConnectionMonitorsOperations.cs#L816

This is  done

**Comment by hofattahMicrosoft** [comment]
Hi Jin,

Conflicts are resolved .

Thanks
Hossam

**Comment by hofattahMicrosoft** [comment]
Need to move this PR to december-release branch

**Pull request closed without merging**
