### PR TITLE
Fixed broken link to contribution guidelines

### PR DESCRIPTION
**Pull request by devdeer-alex**
I assume the correct link should be `https://opensource.microsoft.com/collaborate` like it was updated in other projects like [azure-sdk](https://github.com/Azure/azure-sdk-for-c/issues/1101).

## Description

I replaced a broken link in the root `readme.md`.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@dcaro could you help to review the PR？

**Review by dcaro — APPROVED** [review]
@devdeer-alex thank you for this PR. I corrected another broken link in the contributing guide.

**Comment by msJinLei** [comment]
@devdeer-alex could you sign the CLA

**Comment by dcaro** [comment]
@devdeer-alex  can you please sign the CLA agreement so that we can merge this PR?  Thank you so much !

**Comment by devdeer-alex** [comment]
@dcaro just did it.

**Pull request merged**
