### PR TITLE
Set-AzureApiManagementHostnames fix + new SDK version

### PR DESCRIPTION
**Pull request by ailn**
- fixed bug in Set-AzureApiManagementHostnames cmdlet
- updated SDK version
- recorded new tests

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@ailn__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (ailn). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
LGTM. On-demand job - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/248/

**Comment by markcowl** [comment]
new on demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/253/

**Comment by markcowl** [comment]
@alin please pull the latest from the dev branch to allow the on-demand run to pass

**Comment by hovsepm** [comment]
On-demand job - http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/279/

**Comment by hovsepm** [comment]
@alin your merge did not pull anything. the SQL tests that are failing in your PR are fixed in https://github.com/Azure/azure-powershell dev branch. Please make sure you pulled from that branch (check that your upstream points to that one and not to your fork). The update your PR with merge and rerun the on-demand job.

**Comment by markcowl** [comment]
@ailn there are merge conflicts, please update

**Comment by ailn** [comment]
@hovsepm Sorry, merged with the wrong branch...

**Comment by markcowl** [comment]
@ailn we just created the rlease branch, please retarget this PR at this branch if you want it in for this release

**Comment by markcowl** [comment]
@ailn If you want this PR to go into this release, you need to open it against the dev branch.  Otheriwse, we will look at merging it after the release next week.

**Comment by ailn** [comment]
@markcowl Did you mean to open against 'release' branch?

**Comment by ailn** [comment]
Opened new PR against release-1.0.0: https://github.com/Azure/azure-powershell/pull/1226

**Comment by markcowl** [comment]
@ailn closing as the PR targeted at the release branch is merged

**Pull request closed without merging**
