### PR TITLE
Connect-AzAccount Use Host instead of Warning

### LINKED ISSUE #16963: Connect-AzAccount uses Warning stream to convey Sign-In URL and token
### Description

Connect-AzAccount uses Warning stream to convey Sign-In URL and token. In sessions that choose to set the WarningActionPreference to SilentlyContinue or Ignore, this means that their script will hang indefinitely without any indication.

To me this is not the ideal behavior. The login information should not be a warning. The cmdlet should either attempt to detect if the Warning stream is ignored or silenced and display the message, or another, more appropriate way of conveying this information should be used.

### Issue script & Debug output

```PowerShell
Connect-AzAccount -UseDeviceAuthentication -WarningAction SilentlyContinue
Write-Host "I am never to be seen"
```

### Environment data

```PowerShell
Name                           Value
----                           -----
PSVersion                      5.1.22000.282
PSEdition                      Desktop
PSCompatibleVersions           {1.0, 2.0, 3.0, 4.0...}
BuildVersion                   10.0.22000.282
CLRVersion                     4.0.30319.42000
WSManStackVersion              3.0
PSRemotingProtocolVersion      2.3
SerializationVersion           1.1.0.1
```

### Module versions

```PowerShell
ModuleType Version    Name                                ExportedCommands                                             
---------- -------    ----                                ----------------                                             
Script     2.7.1      Az.Accounts                         {Add-AzEnvironment, Clear-AzContext, Clear-AzDefault, Conn...
```

### Error output

```PowerShell
No error, just no output at all. Console hangs indefinitely, until CTRL-C is pressed to cancel the login.
```

### PR DESCRIPTION
**Pull request by nyanhp**
## Description

Modified the default stream from Warning to Host in case the parameter `UseDeviceAuthentication` is used within `Connect-AzAccount`. Fixes #16963

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by BethanyZhou — CHANGES_REQUESTED** [review]
I don't think this is right place to modify UseDeviceAuthentication's behavior. @isra-fel , could you help confirm

**Comment by BethanyZhou** [comment]
Hi @nyanhp , could you let your GitHub account join Azure org so that we don't mark you as customer.

**Comment by isra-fel** [comment]
Just to be clear @nyanhp , the message that you are trying to **make it appear** is `To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ****** to authenticate.` but not `Please run "Connect-AzAccount -DeviceCode" if browser is not supported in this session.`. Am I right?
If so, here you should update instead:
https://github.com/Azure/azure-powershell/blob/5b8946efc345818cd997852e826404bae4057444/src/Accounts/Authenticators/DeviceCodeAuthenticator.cs#L67

**Comment by nyanhp** [comment]
> Just to be clear @nyanhp , the message that you are trying to **make it appear** is `To sign in, use a web browser to open the page https://microsoft.com/devicelogin and enter the code ****** to authenticate.` but not `Please run "Connect-AzAccount -DeviceCode" if browser is not supported in this session.`. Am I right? If so, here you should update instead:
> 
> https://github.com/Azure/azure-powershell/blob/5b8946efc345818cd997852e826404bae4057444/src/Accounts/Authenticators/DeviceCodeAuthenticator.cs#L67

Yes, that is probably right. I am unable to build the project locally and was unable to test.

**Comment by nyanhp** [comment]
Seeing as the class DeviceCodeAuthenticator does not have access to the console host and there is no WriteInformation or WriteHost functionality in AzureRMCmdlet.cs I am closing this PR and just accept that Connect-AzAccount will display loads of warnings, among them my device authentication code.

**Pull request closed without merging**
