### PR TITLE
[Do not merge]: Co-existence API and stats API

### PR DESCRIPTION
**Pull request by dihan0604**

### CODE REVIEW

**Comment by dihan0604** [comment]
On demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/610/

**Comment by markcowl** [comment]
@dihan0604 This PR is failing due to static analysis issues (1) you added 2 cmdlets without online help; (2) [non-critical] there is now an unused assembly reference in commands.network to the storage management library

You will need to resolve these issues

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by dihan0604** [comment]
On demand job: http://azuresdkci.cloudapp.net/job/powershell-demand/626/

**Comment by dihan0604** [comment]
On demand job pass.

**Comment by DeepakRajendranMsft** [comment]
This change has been built on top off https://github.com/Azure/azure-powershell/pull/1986

**Comment by DeepakRajendranMsft** [comment]
why are we not adding tests for the new cmdlets

**Comment by dihan0604** [comment]
We have not release the new API at our service side. (Gateway manager). 
We do not want to miss this PS release. So we decide to add test later once service side code is updated

**Comment by hovsepm** [comment]
@dihan0604 
You are missing licence header from: 
```
src\ResourceManager\Network\Commands.Network\ExpressRouteCircuit\Stats\GetAzureExpressRouteARPTableCommand.cs 
```

**Comment by hovsepm** [comment]
@dihan0604 missing header in: 
```
src\ResourceManager\Network\Commands.Network\Models\PSExpressRouteCircuitRoutesTableSummary.cs
```

**Comment by hovsepm** [comment]
in src\ResourceManager\Network\Commands.Network\Commands.Network.csproj
remove 
```
 <!--Compile Include="ExpressRouteCircuit\Stats\GetAzureExpressRouteRouteTableSummaryCommand.cs" /--> 
```
line

**Comment by hovsepm** [comment]
in src\ResourceManager\Network\Commands.Network.Test\ScenarioTests\ExpressRouteCircuitTests.ps1 file remove commented lines:

```
      
      #$getCircuit = Set-AzureRmExpressRouteCircuit -ExpressRouteCircuit $getCircuit -AllowClassicOperations $true
      #Assert-AreEqual $true $getCircuit.AllowClassicOperations
```

**Comment by dihan0604** [comment]
Have addressed comments

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/631/

**Comment by markcowl** [comment]
closing as this was just merged into the release branch

**Pull request closed without merging**
