### PR TITLE
[Cosmosdb] Refactoring CosmosDB Set-AzCosmosDB* cmdlets 

### PR DESCRIPTION
**Pull request by MehaKaushik**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by MehaKaushik** [comment]
@wyunchi-ms  Please merge at your earliest convenience.

**Comment by wyunchi-ms** [comment]
@MehaKaushik , please add `changelog.md`. I can not find it.

**Comment by wyunchi-ms** [comment]
Hi @MehaKaushik , could you please revolve the conflicts?

**Comment by MehaKaushik** [comment]
Hey @wyunchi-ms since the rebase with master, the CI tests are failing. The error stack is:
 
System.Management.Automation.RuntimeException : Test failed due to a non-empty error stream. First error : PowerShell Error Record: The specified module 'D:\a\1\s\artifacts\Debug\Az.Network\Az.Network.psd1' was not loaded because no valid module file was found in any module directory. [D:\a\1\s\build.proj] 

 Exception:System.IO.FileNotFoundException: The specified module 'D:\a\1\s\artifacts\Debug\Az.Network\Az.Network.psd1' was not loaded because no valid module file was found in any module directory. 

 Details: 

 Script Stack Trace: at <ScriptBlock>, <No file>: line 1 

 : Target: D:\a\1\s\artifacts\Debug\Az.Network\Az.Network.psd1 

 Check the error stream in the test log for additional errors. 

 Stack Trace: 

 at Microsoft.WindowsAzure.Commands.ScenarioTest.EnvironmentSetupHelper.RunPowerShellTest(String[] scripts) in D:\a\1\s\tools\ScenarioTest.ResourceManager\EnvironmentSetupHelper.cs:line 578 

 at Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.TestController.RunPsTestWorkflow(Func`1 scriptBuilder, Action cleanup, String callingClassType, String mockName) in D:\a\1\s\src\CosmosDB\CosmosDB.Test\ScenarioTests\TestController.cs:line 122 

 at Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.TestController.RunPowerShellTest(XunitTracingInterceptor logger, String[] scripts) in D:\a\1\s\src\CosmosDB\CosmosDB.Test\ScenarioTests\TestController.cs:line 72 

 at Microsoft.Azure.Commands.CosmosDB.Test.ScenarioTests.ScenarioTest.AccountTests.TestAddRegionOperation() in D:\a\1\s\src\CosmosDB\CosmosDB.Test\ScenarioTests\AccountTests.cs:line 55 

 Standard Output Messages: 

 Test-AddRegionOperation 

 Caught Exception: System.Management.Automation.RuntimeException: Test failed due to a non-empty error stream. First error: PowerShell Error Record: The specified module 'D:\a\1\s\artifacts\Debug\Az.Network\Az.Network.psd1' was not loaded because no valid module file was found in any module directory. 

 Exception:System.IO.FileNotFoundException: The specified module 'D:\a\1\s\artifacts\Debug\Az.Network\Az.Network.psd1' was not loaded because no valid module file was found in any module directory.

**Comment by isra-fel** [comment]
Judged from the error message, you need to reference network's csproj in cosmosdb's sln file. Example:
 https://github.com/Azure/azure-powershell/blob/58ded2ba3e0a5f7da0d1ffed9e0adb986986ab6f/src/Compute/Compute.sln#L11 and https://github.com/Azure/azure-powershell/blob/58ded2ba3e0a5f7da0d1ffed9e0adb986986ab6f/src/Compute/Compute.sln#L41-L44

Our CI system works this way: it only builds those modules related to the changes in your PR; which roughly translates to "build everything declared in your module's *.sln file". Now that on master branch the test cases in cosmosdb are (referencing Network's cmdlets)[https://github.com/Azure/azure-powershell/pull/11584/files#diff-87951af352fbbcb06e2ec811c0c1d6e1R207], but network wasn't added to cosmosdb.sln, so it wasn't built, so the cases failed to find network module.

**Comment by MehaKaushik** [comment]
@wyunchi-ms @isra-fel ChangeLog added, CI looks good now, please approve and merge at your convenience.

**Pull request merged**
