### PR TITLE
Fix RDP cmdlet

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**
The cmdlet seems to be broken during the port to use swagger

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@DeepakRajendranMsft test?

**Comment by markcowl** [comment]
@azuresdkci restet this please

**Comment by DeepakRajendranMsft** [comment]
@markcowl Its a bit involved, i will try to get the tests by next week.This PR was just to fix the broken cmdlet (but ya this cmdlet previously didnt have any tests either)

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by DeepakRajendranMsft** [comment]
Thanks @markcowl, I have RDBug:5449271 to track adding tests.

**Pull request merged**
