### PR TITLE
LogicApp/IntegrationAccount PSCmdlets

### PR DESCRIPTION
**Pull request by pankajsn**
This includes the PS cmdlets for the LogicApp/IntegrationAccounts. Currently LogicApp SDK (for Integration Account related updates) in review and the nuget package is yet not published in Nuget Gallery. We want to start this pull request to fix review comments in parallel. Once SDK pull request is complete, we need to publish the nuget package and merge this request.

### CODE REVIEW

**Comment by markcowl** [comment]
@pankajsn Looks like you need to publish your management package to nuget

**Comment by pankajsn** [comment]
Is there any specific steps we need to follow to publish the management package ? (The pull request for the same is completed now)

**Comment by markcowl** [comment]
@pankajsn It looks like there are some new CredScan issues in your help document - you can either change them, or add this file to exceptions here: https://github.com/Azure/azure-powershell/blob/dev/tools/GlobalFilters.xml  after PR #2524 is merged

**Comment by markcowl** [comment]
@pankajsn This has way too many changes outside your folder.

First: Please squash the commits 91 commits is too many for a cmdlet update
Second:  It looks like this has many more changes than you anticipated, please pare this down to the changes you need

**Comment by pankajsn** [comment]
I have a created a new request #2528<https://github.com/Azure/azure-powershell/pull/2528> to exclude commits outside of our folder as suggested.
Just wondering why this pull request is labeled as “cla-required”

**Comment by markcowl** [comment]
Closing in favor of the other PR.

**Pull request closed without merging**
