### PR TITLE
Perform null check before accessing it

### PR DESCRIPTION
**Pull request by pregress**
## Description

Perform the null check on RouteTable.Routes before accessing it with SingleOrDefault.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
@pregress Thanks for the contribution! 
Please add a line to describe your change of this PR in https://github.com/Azure/azure-powershell/blob/05a86d3c19079361ffd103e1167b89e0c4583484/src/Network/Network/ChangeLog.md
BTW, are you a Microsoft team member?

**Comment by pregress** [comment]
Described the change in the changelog.
No, I'm not a MSFT team member.

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hey, `src/Network/Network/Generated/RouteTable/Route/AddAzureRmRouteConfigCommand.cs` this file is generated so we probably should not update it manually.

@Sandido Hey Adam what's you advice here?

**Comment by pregress** [comment]
Can somebody point me in the right direction, from where the source code is generated? 
I'll change it there.

**Comment by msJinLei** [comment]
> Can somebody point me in the right direction, from where the source code is generated? I'll change it there.

`src/Network/Network/Generated/RouteTable/Route/AddAzureRmRouteConfigCommand.cs` looks generated. Need @MikhailTryakhov to confirm.

**Review by wyunchi-ms — APPROVED** [review]

**Comment by wyunchi-ms** [comment]
Please resolve the conflicts

**Review by wyunchi-ms — APPROVED** [review]

**Review by isra-fel — APPROVED** [review]

**Pull request merged**
