### PR TITLE
ProviderHub doc/tests update

### PR DESCRIPTION
**Pull request by wwendyc**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
The test cases fails. Please fix them.

**Comment by wwendyc** [comment]
@wyunchi-ms Updated the PR but there seems to be some error related to Az.Accounts required assemblies. Nothing related to Az.Accounts was changed in this PR, do you know what the issue might be?

`Write-Error: ERROR: Assembly Azure.Core was not included in the required assemblies field for module Az.Accounts
  Write-Error: ERROR: Assembly Azure.Identity was not included in the required assemblies field for module Az.Accounts
  Write-Error: ERROR: Assembly Microsoft.Bcl.AsyncInterfaces was not included in the required assemblies field for module Az.Accounts
  Write-Error: ERROR: Assembly Microsoft.Identity.Client was not included in the required assemblies field for module Az.Accounts
  Write-Error: ERROR: Assembly Microsoft.Identity.Client.Extensions.Msal was not included in the required assemblies field for module Az.Accounts
  Write-Error: ERROR: Assembly System.Text.Encodings.Web was not included in the required assemblies field for module Az.Accounts
  Exception: D:\a\1\s\tools\CheckAssemblies.ps1:100
`

**Review by wyunchi-ms — APPROVED** [review]

**Pull request merged**
