### PR TITLE
Update vmbackup publisher

### PR DESCRIPTION
**Pull request by krkhan**
The OSTC team does not own the VMBackup extension anymore.

### CODE REVIEW

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1228/

**Comment by cormacpayne** [comment]
@krkhan please pull from dev to get the fix for the on-demand build that we made yesterday

**Comment by cormacpayne** [comment]
@krkhan also, please target the **release-3.0.0** branch rather than **dev** if you would like this to go into the Ignite release

**Comment by krkhan** [comment]
@markcowl @cormacpayne Merged upstream/dev, retargeted PR to release-3.0.0 and kicked off new on-demand run: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1231/

**Comment by krkhan** [comment]
@markcowl @cormacpayne The on-demand run succeeded.

**Comment by krkhan** [comment]
Merged release-3.0.0 to pull in the latest changes, kicked off on-demand run again: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/1232/

**Comment by krkhan** [comment]
@markcowl @cormacpayne On-demand run succeeded after the merge.

**Comment by markcowl** [comment]
LGTM once the branch is ready

**Pull request merged**
