### PR TITLE
Support multi Ipconfiguration on the network interface, rerecord tests with 5.0.1 version of SDK

### PR DESCRIPTION
**Pull request by skomarag**
HI,

Here are the changes:
1. Added a new field called Primary for NetworkinterfaceIpconfiguration
2. Using the primary in related commandlets
3. Wrote tests but disabled them as NRP code is not ready yet
This PR also contains Deepak's changes which are
1. Rerecord all tests as the NRP version is changed to 5.0.1
2. Change the version for management.network.dll everywhere to 5.0.1
3. Edited the name from "Virtualnetwork" to "VirtualNetwork"
4. All tests passed locally and also on the build

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@skomarag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@skomarag Please change the title of the PR to something more human readable

**Comment by hovsepm** [comment]
@skomarag please pull from upstream and resolve conflicts

**Comment by skomarag** [comment]
fork is out of sync for a while which is creating a lot of commits and lot of unnecessary code merges..
closing this PR,  sync the fork and create new PR

**Comment by skomarag** [comment]
fork is out of sync for a while which is creating a lot of commits and lot of unnecessary code merges..
closing this PR, sync the fork and create new PR

**Pull request closed without merging**
