### PR TITLE
[PostgreSQL] Add Database CRUD Cmdlets and test

### PR DESCRIPTION
**Pull request by DaeunYim**
## Description
- Added Database CRUD
[Design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/996)

- Need to GA the module in September

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by VeryEarly — CHANGES_REQUESTED** [review]
please make parameter "ProxyUseDefaultCredentials" to "ProxyUseDefaultCredential"

**Comment by DaeunYim** [comment]
> please make parameter "ProxyUseDefaultCredentials" to "ProxyUseDefaultCredential"

As this one was autogenerated, do I need to change anything from read me or make a custom file to change the parameter name?

**Comment by VeryEarly** [comment]
> > please make parameter "ProxyUseDefaultCredentials" to "ProxyUseDefaultCredential"
> 
> As this one was autogenerated, do I need to change anything from read me or make a custom file to change the parameter name?

yes please use directive in readme.md to update these parameter names

**Comment by DaeunYim** [comment]
> ProxyUseDefaultCredential

Hi, could you kindly give me simple example how to change this,,? I tried a few things, but it didn't generate correctly.. 

Tried this following https://github.com/Azure/autorest.powershell/blob/main/docs/directives.md#parameter-rename 
  - where:
      parameter-name: (.*)ProxyUseDefaultCredentials$
    set:
      parameter-name: ProxyUseDefaultCredential
Any advice would be appreciated

**Comment by VeryEarly** [comment]
Hi @DaeunYim ,

We discovered it's a bug in our pipeline and was fixed now, please sync your branch with `generation`, no action need to be taken for parameter `ProxyUseDefaultCredentials`

**Comment by DaeunYim** [comment]
> Hi @DaeunYim ,
> 
> We discovered it's a bug in our pipeline and was fixed now, please sync your branch with `generation`, no action need to be taken for parameter `ProxyUseDefaultCredentials`

Thanks a lot for the update.

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
