### PR TITLE
Update docs to indicate [Get/Disable/Enable]-AzHDInsightMonitoring cmdlets are 'Classic'

### PR DESCRIPTION
**Pull request by proazr**
## Description

This PR includes updates to the synopsis & descriptions for the Enable-AzHDInsightMonitoring, Disable-AzHDInsightMonitoring & Get-AzHDInsightMonitoring cmdlets to indicate that they are for managing the Classic Azure Monitor logs integration on an HDInsight cluster.

Following are a few reasons why this is necessary:

1. At present, there are two sets of cmdlets for managing the integration of Azure Monitor Logs w/ an HDInsight cluster, namely:
     1. Enable-AzHDInsightMonitoring, Disable-AzHDInsightMonitoring & Get-AzHDInsightMonitoring 
     2. Enable-AzHDInsightAzureMonitor, Disable-AzHDInsightAzureMonitor & Get-AzHDInsightAzureMonitor

    However, the help docs for both sets of cmdlets don't mention how they are different, i.e., the first set of cmdlets integrate the cluster w/ Azure Monitor Logs in the "classic" way, while the second set of cmdlets being the newer ones. This causes confusion and would require further researching to identify how they differ (happened to me). 

   On the other hand, the docs for the Azure CLI HDInsight commands do highlight this difference - https://docs.microsoft.com/en-us/cli/azure/hdinsight/monitor?view=azure-cli-latest

2. Here is an example on how the docs for Enable-AzHDInsightMonitoring & Enable-AzHDInsightAzureMonitor appear to be mostly be the same:

    image

    image

3. The portal currently indicates the Log Analytics integration for HDInsight as "Classic" under Monitoring > Monitor Integration. It would help to indicate the same in the help docs for the respective set of cmdlets.

    image
 
4. The classic integration of Azure Monitor Logs is soon to be deprecated and the recommendation is for customers to migrate to the newer integration as documented here  - https://docs.microsoft.com/en-us/azure/hdinsight/log-analytics-migration. Updating the help docs to indicate that the first set of cmdlets are "classic" will help make users aware of this distinction. 

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [] If applicable, the changes made in the PR have proper test coverage
- [] For public API changes to cmdlets:
    - [] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
@proazr thanks for your contribution! Let me route this to the correct team...

Hi @idear1203  @aim-for-better  would you be able to help review this? Thanks!

**Comment by aim-for-better** [comment]
Hi @isra-fel  is changing the description a breaking change or not?

**Comment by isra-fel** [comment]
Not a breaking change. It's fine.

**Review by aim-for-better — COMMENTED** [review]
Hi @proazr , thanks for your contribution.

Could you please also update the related description in the src/HDInsight/HDInsight/help/Az.HDInsight.md file?

The related locations are as bellow:
https://github.com/Azure/azure-powershell/blob/186c05b31242bf54653585eb2082be3fd594e2ce/src/HDInsight/HDInsight/help/Az.HDInsight.md#get-azhdinsightmonitoring

https://github.com/Azure/azure-powershell/blob/186c05b31242bf54653585eb2082be3fd594e2ce/src/HDInsight/HDInsight/help/Az.HDInsight.md#disable-azhdinsightmonitoring

https://github.com/Azure/azure-powershell/blob/186c05b31242bf54653585eb2082be3fd594e2ce/src/HDInsight/HDInsight/help/Az.HDInsight.md#enable-azhdinsightmonitoring

**Comment by aim-for-better** [comment]
> Not a breaking change. It's fine.

Thanks

**Comment by proazr** [comment]
> Hi @proazr , thanks for your contribution.
> 
> Could you please also update the related description in the src/HDInsight/HDInsight/help/Az.HDInsight.md file?
> 
> The related locations are as bellow:
> https://github.com/Azure/azure-powershell/blob/186c05b31242bf54653585eb2082be3fd594e2ce/src/HDInsight/HDInsight/help/Az.HDInsight.md#get-azhdinsightmonitoring
> 
> https://github.com/Azure/azure-powershell/blob/186c05b31242bf54653585eb2082be3fd594e2ce/src/HDInsight/HDInsight/help/Az.HDInsight.md#disable-azhdinsightmonitoring
> 
> https://github.com/Azure/azure-powershell/blob/186c05b31242bf54653585eb2082be3fd594e2ce/src/HDInsight/HDInsight/help/Az.HDInsight.md#enable-azhdinsightmonitoring

@aim-for-better - Thanks, I didn't realize there was this file as well. I've made the updates.

**Review by isra-fel — APPROVED** [review]
Looking good. Let me merged the PR. Thank you both :)

**Pull request merged**
