### PR TITLE
FQDN support for LocalNetworkGateway and VpnSiteLink objects

### PR DESCRIPTION
**Pull request by aknandagit**
## Description

Updated New-LocalNetworkGateway and New-VpnSiteLink cmdlets to support FQDN based LocalNetworkGateways and VpnSites resources for on premise to Azure connectivity over VPN.

## Checklist

- [X] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [X] The title of the PR is clear and informative
- [X] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/Network/Network/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [X] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [X] If applicable, the changes made in the PR have proper test coverage
- [X] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [X] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by aknandagit** [comment]
I have fixed the test failures.

**Comment by aknandagit** [comment]
> Please fix the failed tests.

I fixed the failed tests

**Comment by aknandagit** [comment]
Hi I have fixed the test failure. Please review and merge.
Thanks... Amit
    	
    	

    	Get Outlook for iOS
    
  




On Tue, Apr 7, 2020 at 12:45 AM -0700, "Jin Lei" <notifications@github.com> wrote:















@msJinLei requested changes on this pull request.



Can you fix the failed tests? Thanks

**Pull request merged**
