### PR TITLE
Porting simple vm parameter sets in New-AzureRmVM/New-AzureRMVMSS to stack compute module

### PR DESCRIPTION
**Pull request by bganapa**
## Description

This does not change SDK reference and will still use the api-version 2017-03-30. The compute module refers to the storage and network modules of stack to use the correct api versions. 

The module has been tested against azure stack

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@bganapa CI is failing, please take a look.

**Comment by deathly809** [comment]
@bganapa cred scan!

```
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVmssTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVmssTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVmssTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
C:\workspace\powershell\src\StackAdmin\Compute\Commands.Compute.Test\ScenarioTests\StrategiesVirtualMachineTests.ps1
```

**Comment by bganapa** [comment]
ps-sign - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/ps-sign/1520/
psnetsign - https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/psnetsign/289

**Comment by maddieclayton** [comment]
@bganapa Can you get @deathly809 to sign off on these changes?

**Comment by bganapa** [comment]
Closing this PR as we are looking at releasing this only in Jan End timeframe

**Pull request closed without merging**
