### PR TITLE
Dpdtimeout for Gateway Connections

### PR DESCRIPTION
**Pull request by henry416**
## Description

This PR adds the DPDTimeout field to Virtual Network Gateway Connections, allowing setting of dead peer detection timeout values in seconds.

This cmdlet change requires 2020-03-01 network package.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by msJinLei** [comment]
cmdlet review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/552

**Comment by msJinLei** [comment]
@henry416 Please fix the test failure.

**Comment by henry416** [comment]
@msJinLei This requires the 2020-03-01 package, the test that I updated uses this package. I see there is a PR out for updating package: https://github.com/Azure/azure-powershell/pull/11537/files

**Comment by number213** [comment]
Hi @henry416, changes from `network-march` were merged into master. Please retarget your PR to master as well to make the release. Please also note that `master` was rebased due to credentials leaking into it so it's basically incompatible with `network-march`. My suggestion is to create a new branch from master and copy your changes there.

**Comment by henry416** [comment]
@msJinLei All tests passed now

**Comment by henry416** [comment]
@msJinLei Changelog updated

**Comment by henry416** [comment]
@msJinLei Please merge, thanks!

**Pull request merged**
