### PR TITLE
Show sku get azure rm resource

### PR DESCRIPTION
**Pull request by chidmdxx**
Show the Sku property with with Get and New azure resource cmdlet, also addresses comments from a previous PR

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@chidmdxx__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by ogail** [comment]
@chidmdxx fix tests

**Comment by chidmdxx** [comment]
@azuresdkci retest this please

**Comment by stankovski** [comment]
@azuresdkci retest this please

**Pull request merged**
