### PR TITLE
Upgrading SDK version to 1.13.0 for Azure-Reservations

### PR DESCRIPTION
**Pull request by Only2125**
## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
Hi @Only2125 every PR need an entry in readme.md
Please find details in the "checklist" on the top of this page.

Also fix the tests please.

**Comment by Only2125** [comment]
> Hi @Only2125 every PR need an entry in readme.md
> Please find details in the "checklist" on the top of this page.
> Also fix the tests please.

Hi @isra-fe, thanks for the reply. I will check the list and update the file.
And question. All tests passed locally. How should I debug this checking failure? and clue?

**Comment by isra-fel** [comment]
> > Hi @Only2125 every PR need an entry in readme.md
> > Please find details in the "checklist" on the top of this page.
> > Also fix the tests please.
> 
> Hi @isra-fe, thanks for the reply. I will check the list and update the file.
> And question. All tests passed locally. How should I debug this checking failure? any clue?

Do you mean all test passed locally *in record mode*?
All the session records were removed in this PR, that's why the test failed.

**Pull request closed without merging**
