### PR TITLE
Added iaas cmdlets for Azure Batch module

### PR DESCRIPTION
**Pull request by brnleehng**

### CODE REVIEW

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/703/

**Comment by hovsepm** [comment]
new on-demand: on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/706/

**Comment by hovsepm** [comment]
on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/707/

**Comment by brnleehng** [comment]
Random test failed. New job looks good now. new on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/710

**Pull request merged**
