### PR TITLE
Websites strategy library update

### PR DESCRIPTION
**Pull request by sergey-shandar**
## Description

The PR contains some breaking changes for the Strategy library so don't merge it yet until we prepare a version change for the library.

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by MiYanni** [comment]
@sergey-shandar Well, I was looking at the error, but the build restarted for some reason. I think you changed something in NewAzureRmWebApp that wasn't being referenced properly for NetCore. At least that is what the error indicated in Travis.

**Comment by vladimir-shcherbakov** [comment]
What do you mean by Websites strategy library?

**Comment by vladimir-shcherbakov** [comment]
@sergey-shandar 
Is it possible for you organize the commits by
1) ResourceManager/Common/Commands.Common.Strategies changes
2) ResourceManager/Compute/AzureRM.Compute changes
3) ResourceManager/Websites chages

or you may want to split up the PR into 3 and leave in the PR only changes related to Websites.

**Comment by sergey-shandar** [comment]
See this PR #6239

**Pull request closed without merging**
