### PR TITLE
AppService: Removed TestSetAzureStorageWebAppHyperVSlot test.

### PR DESCRIPTION
**Pull request by Kotasudhakarreddy**
## Description

Removed TestSetAzureStorageWebAppHyperVSlot test.
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by panchagnula — APPROVED** [review]
Thanks for the quick turn around here

**Review by isra-fel — CHANGES_REQUESTED** [review]
Hi, could you give us some backgroud why this test is removed?

**Comment by Kotasudhakarreddy** [comment]
> Hi, could you give us some backgroud why this test is removed?

@panchagnula your comments plz.

**Comment by panchagnula** [comment]
> Hi, could you give us some backgroud why this test is removed?

@isra-fel , this test is exposing secrets ignorer to verify storage account is setup & functioning as expected. This is a security issue that was Brought to our notice, we rotated the secrets on our end, but also want to remove the test case. Thanks!

**Review by isra-fel — APPROVED** [review]

**Comment by isra-fel** [comment]
OKay. LGTM

**Pull request merged**
