### PR TITLE
{AzureCXP} fixes Azure/azure-powershell#18607

### PR DESCRIPTION
**Pull request by navba-MSFT**
This documentation says "Registers an Azure provider feature in your account." which is vague and makes it sound like its ties to a user account. 

The below REST API docs clearly mentions that it registers feature to the current subscription context.
https://docs.microsoft.com/en-us/rest/api/resources/features/register

fixes Azure/azure-powershell#18607

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by dingmeng-xue** [comment]
Please change it as well.

https://github.com/Azure/azure-powershell/blob/d812b8ac688035236f2c6e2782655f27aa48c0e6/src/Resources/Resources/help/Az.Resources.md

**Comment by navba-MSFT** [comment]
> Please change it as well.
> 
> https://github.com/Azure/azure-powershell/blob/d812b8ac688035236f2c6e2782655f27aa48c0e6/src/Resources/Resources/help/Az.Resources.md

@dingmeng-xue This is done. Thanks.

**Review by dingmeng-xue — APPROVED** [review]

**Comment by navba-MSFT** [comment]
@dingmeng-xue Thanks for approving this. Could you merge this once you get a chance ? Thanks in advance.

**Pull request merged**
