### PR TITLE
[Storage] Support HNS soft delete

### PR DESCRIPTION
**Pull request by blueww**
## Description

Design pass review in: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/813

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by blueww** [comment]
The Unit test failure is following, looks not related with my change:

> 2021-05-19T09:27:43.3278287Z System.Management.Automation.RuntimeException : Test failed due to a non-empty error stream. First error : PowerShell Error Record: The specified module '/home/vsts/work/1/s/artifacts/Debug/Az.ContainerInstance/Az.ContainerInstance.psd1' was not loaded because no valid module file was found in any module directory. [/home/vsts/work/1/s/build.proj]
> 2021-05-19T09:27:43.3304758Z   Exception:System.IO.FileNotFoundException: The specified module '/home/vsts/work/1/s/artifacts/Debug/Az.ContainerInstance/Az.ContainerInstance.psd1' was not loaded because no valid module file was found in any module directory.

**Comment by msJinLei** [comment]
> The Unit test failure is following, looks not related with my change:
> 
> > 2021-05-19T09:27:43.3278287Z System.Management.Automation.RuntimeException : Test failed due to a non-empty error stream. First error : PowerShell Error Record: The specified module '/home/vsts/work/1/s/artifacts/Debug/Az.ContainerInstance/Az.ContainerInstance.psd1' was not loaded because no valid module file was found in any module directory. [/home/vsts/work/1/s/build.proj]
> > 2021-05-19T09:27:43.3304758Z   Exception:System.IO.FileNotFoundException: The specified module '/home/vsts/work/1/s/artifacts/Debug/Az.ContainerInstance/Az.ContainerInstance.psd1' was not loaded because no valid module file was found in any module directory.

```
diff --git a/src/Network/Network.sln b/src/Network/Network.sln
index c8636be56a..5d47082fcb 100644
--- a/src/Network/Network.sln
+++ b/src/Network/Network.sln
@@ -18,7 +18,7 @@ Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Compute", "..\Compute\Compu
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "OperationalInsights", "..\OperationalInsights\OperationalInsights\OperationalInsights.csproj", "{5BE35A94-C20F-4659-AA29-9B9AEBCFAF36}"
 EndProject
-Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ContainerInstance", "..\ContainerInstance\ContainerInstance\ContainerInstance.csproj", "{0E11B67A-1257-40D0-BD33-8315759FDB01}"
+Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ContainerInstance", "..\ContainerInstance\Az.ContainerInstance.csproj", "{0E11B67A-1257-40D0-BD33-8315759FDB01}"
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ManagedServiceIdentity", "..\ManagedServiceIdentity\ManagedServiceIdentity\ManagedServiceIdentity.csproj", "{72C596A0-636E-47F2-B81B-4BC9E6F1EBCE}"
 EndProject
```
@blueww  Please try to commit the change above to see whether the issue is fixed.

**Comment by msJinLei** [comment]
> > The Unit test failure is following, looks not related with my change:
> > > 2021-05-19T09:27:43.3278287Z System.Management.Automation.RuntimeException : Test failed due to a non-empty error stream. First error : PowerShell Error Record: The specified module '/home/vsts/work/1/s/artifacts/Debug/Az.ContainerInstance/Az.ContainerInstance.psd1' was not loaded because no valid module file was found in any module directory. [/home/vsts/work/1/s/build.proj]
> > > 2021-05-19T09:27:43.3304758Z   Exception:System.IO.FileNotFoundException: The specified module '/home/vsts/work/1/s/artifacts/Debug/Az.ContainerInstance/Az.ContainerInstance.psd1' was not loaded because no valid module file was found in any module directory.
> 
> @blueww Please try to commit the change above to see whether the issue is fixed.

```
diff --git a/src/Network/Network.Test/Network.Test.csproj b/src/Network/Network.Test/Network.Test.csproj
index 7fdece36eb..d551b67108 100644
--- a/src/Network/Network.Test/Network.Test.csproj
+++ b/src/Network/Network.Test/Network.Test.csproj
@@ -19,7 +19,6 @@
     <PackageReference Include="Microsoft.Azure.Management.KeyVault" Version="3.1.0-preview.2" />
     <PackageReference Include="Microsoft.Azure.Insights" Version="0.16.0-preview" />
     <PackageReference Include="Microsoft.Azure.Management.Compute" Version="46.0.0" />
-    <PackageReference Include="Microsoft.Azure.Management.ContainerInstance" Version="2.0.0" />
     <PackageReference Include="Microsoft.Azure.Management.PrivateDns" Version="1.0.0" />
     <PackageReference Include="Microsoft.Azure.Management.Redis" Version="4.4.1" />
     <PackageReference Include="Microsoft.Azure.Management.OperationalInsights" Version="0.21.0-preview" />
diff --git a/src/Network/Network.Test/ScenarioTests/NetworkTestRunner.cs b/src/Network/Network.Test/ScenarioTests/NetworkTestRunner.cs
index 70a25c4166..c508360769 100644
--- a/src/Network/Network.Test/ScenarioTests/NetworkTestRunner.cs
+++ b/src/Network/Network.Test/ScenarioTests/NetworkTestRunner.cs
@@ -40,7 +40,6 @@ namespace Microsoft.Azure.Commands.Network.Test.ScenarioTests
                     helper.GetRMModulePath("AzureRM.Compute.psd1"),
                     helper.GetRMModulePath("AzureRM.Storage.psd1"),
                     helper.GetRMModulePath("AzureRM.Sql.psd1"),
-                    helper.GetRMModulePath("AzureRM.ContainerInstance.psd1"),
                     helper.GetRMModulePath("AzureRM.OperationalInsights.psd1"),
                     helper.GetRMModulePath("AzureRM.KeyVault.psd1"),
                     helper.GetRMModulePath("AzureRM.ManagedServiceIdentity.psd1"),
diff --git a/src/Network/Network.sln b/src/Network/Network.sln
index 5d47082fcb..1dfab450a6 100644
--- a/src/Network/Network.sln
+++ b/src/Network/Network.sln
@@ -18,8 +18,6 @@ Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Compute", "..\Compute\Compu
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "OperationalInsights", "..\OperationalInsights\OperationalInsights\OperationalInsights.csproj", "{5BE35A94-C20F-4659-AA29-9B9AEBCFAF36}"
 EndProject
-Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ContainerInstance", "..\ContainerInstance\Az.ContainerInstance.csproj", "{0E11B67A-1257-40D0-BD33-8315759FDB01}"
-EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "ManagedServiceIdentity", "..\ManagedServiceIdentity\ManagedServiceIdentity\ManagedServiceIdentity.csproj", "{72C596A0-636E-47F2-B81B-4BC9E6F1EBCE}"
 EndProject
 Project("{9A19103F-16F7-4668-BE54-9A1E7A4F7556}") = "Storage", "..\Storage\Storage\Storage.csproj", "{A2591FA5-BF93-4358-9097-E6D58FE1DDC4}"
```

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
