### PR TITLE
Fixing static analysis issues, breaking changes are expected and AzureStack does not ship MSI

### PR DESCRIPTION
**Pull request by bganapa**
## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by bganapa** [comment]
@isra-fel any idea why would this fail in Mac build ?
 /var/folders/24/8k48jl6d249_n_qfxwsl6xvm0000gn/T/tmpfcf10d15c4464127a0d542090fdfe62f.exec.cmd: line 2:   869 Abort trap: 6           dotnet sln /Users/runner/work/1/s/artifacts/Azure.PowerShell.sln add "/Users/runner/work/1/s/src/Network/Network/Network.csproj"
/Users/runner/work/1/s/build.proj(155,5): error MSB3073: The command "dotnet sln /Users/runner/work/1/s/artifacts/Azure.PowerShell.sln add "/Users/runner/work/1/s/src/Network/Network/Network.csproj"" exited with code 134.
##[error]Error: The process '/usr/local/bin/dotnet' failed with exit code 1
Info: Azure Pipelines hosted agents have been updated and now contain .Net 5.x SDK/Runtime along with the older .Net Core version which are currently lts. Unless you have locked down a SDK version for your project(s), 5.x SDK might be picked up which might have breaking behavior as compared to previous versions. You can learn more about the breaking changes here: https://docs.microsoft.com/en-us/dotnet/core/tools/ and https://docs.microsoft.com/en-us/dotnet/core/compatibility/ . To learn about more such changes and troubleshoot, refer here: https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/build/dotnet-core-cli?view=azure-devops#troubleshooting
##[error]Dotnet command failed with non-zero exit code on the following projects : 

https://dev.azure.com/azure-sdk/internal/_build/results?buildId=680822&view=logs&j=3b059b26-55fe-5273-567a-5b3fa6c051e7&t=d79fef56-5c6d-5ef0-ffef-933b2ad3a58e&l=120

**Comment by isra-fel** [comment]
Hi, we just fixed an issue that blocked build on master branch. You'll need to cherry-pick this commit b66c72034476c9a93e5d3bc782ef5b609c54d0af to get it working on your branch. Sorry for the inconvenience.

**Comment by bganapa** [comment]
@isra-fel I cherry picked that commit and i now hit this error in static analysis
Write-Error: ERROR: Assembly Azure.Core was not included in the required assemblies field for module Az.Storage
  Write-Error: ERROR: Assembly System.Text.Json was not included in the required assemblies field for module Az.Storage
  Write-Error: ERROR: Assembly Microsoft.Bcl.AsyncInterfaces was not included in the required assemblies field for module Az.Storage
  Exception: /Users/runner/work/1/s/tools/CheckAssemblies.ps1:75

I believe these assemblies should not be needed in az.storage.psd1. Do i need to pick another commit to this branhc?

**Comment by isra-fel** [comment]
Hi @bganapa you are using one of the newer versions of Az.Storage that depends on Azure.Core. It is a special library because all the track 2 SDKs depend on it, plus Azure.Identity.

For the time being, I believe it's OK to handle it by adding to psd1, because there's no other module depends on Azure.Core.
However, if you plan to update Az.Accounts (which now depends on Azure.Identity, and Azure.Core), it must be handled as a shared assembly, as what we are doing on the master branch.

**Comment by bganapa** [comment]
Thanks for the quick response @isra-fel . Our plan is to consume the latest az.accounts based on azure.identity. We will always be using the latest Az.Accounts after the upcoming release. 
Thanks for bringing this up.

**Comment by bganapa** [comment]
@isra-fel Also i was not aware that the az.storage version that i picked up depends on azure.core. I am going to merge this PR and will generate a build and verify

**Pull request merged**
