### PR TITLE
Update sign pipeline of Az.Tools.Predictor

### PR DESCRIPTION
**Pull request by dingmeng-xue**
## Description

* Bump PowerShell version to 7.2.0-preview
* Bump Dotnet SDK version to 6.0.x even preview version
* Install Dotnet 2.1 runtime which is required by signing task

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by VeryEarly — APPROVED** [review]

**Comment by kceiw** [comment]
Thanks for updating it. Can you bump to .Net 6 preview? The Az.Tools.Predictor requires .Net 6. It runs in PowerShell 7.2. I don't know if that's required to create the package.

.Net 6 and PowerShell 7.2 are required after my only PR is complete.

**Comment by kceiw** [comment]
> Thanks for updating it. Can you bump to .Net 6 preview? The Az.Tools.Predictor requires .Net 6. It runs in PowerShell 7.2. I don't know if that's required to create the package.
> 
> .Net 6 and PowerShell 7.2 are required after my only PR is complete. 

Here is my PR #14041. The build should fail now. I appreciate you take on this task.

**Comment by dingmeng-xue** [comment]
> Thanks for updating it. Can you bump to .Net 6 preview? The Az.Tools.Predictor requires .Net 6. It runs in PowerShell 7.2. I don't know if that's required to create the package.
> 
> .Net 6 and PowerShell 7.2 are required after my only PR is complete.

Hi @Kceiw,

I recommend that you don't stick to the latest version of PowerShell or .NET except your feature requires that. Normally, dotnet doesn't allow module loads a higher version of assembly if lower version is already loaded in PowerShell. If Predictor uses the latest assembly, its usage will be impacted by that constraint. Do you need the latest version? My approach is lower version is better than higher version and stable version is better than preview version.

**Comment by kceiw** [comment]
> > Thanks for updating it. Can you bump to .Net 6 preview? The Az.Tools.Predictor requires .Net 6. It runs in PowerShell 7.2. I don't know if that's required to create the package.
> > 
> > .Net 6 and PowerShell 7.2 are required after my only PR is complete.
> 
> Hi @Kceiw,
> 
> I recommend that you don't stick to the latest version of PowerShell or .NET except your feature requires that. Normally, dotnet doesn't allow module loads a higher version of assembly if lower version is already loaded in PowerShell. If Predictor uses the latest assembly, its usage will be impacted by that constraint. Do you need the latest version? My approach is lower version is better than higher version and stable version is better than preview version. 

Az.Tools.Predictor cannot build without .Net 6 preview. 

That's required by PowerShell 7.2 preview and the API we rely on. Our dependency is built on .Net 6 preview. I totally agree with your approach. But all we need are in preview.

**Comment by dingmeng-xue** [comment]
> > > Thanks for updating it. Can you bump to .Net 6 preview? The Az.Tools.Predictor requires .Net 6. It runs in PowerShell 7.2. I don't know if that's required to create the package.
> > > .Net 6 and PowerShell 7.2 are required after my only PR is complete.
> > 
> > 
> > Hi @kceiw,
> > I recommend that you don't stick to the latest version of PowerShell or .NET except your feature requires that. Normally, dotnet doesn't allow module loads a higher version of assembly if lower version is already loaded in PowerShell. If Predictor uses the latest assembly, its usage will be impacted by that constraint. Do you need the latest version? My approach is lower version is better than higher version and stable version is better than preview version.
> 
> Az.Tools.Predictor cannot build without .Net 6 preview.
> 
> That's required by PowerShell 7.2 preview and the API we rely on. Our dependency is built on .Net 6 preview. I totally agree with your approach. But all we need are in preview.

I really don't want to use the latest version. Many our big customer cannot use preview version. Anyway, let me change configuration further.

**Comment by dingmeng-xue** [comment]
@kceiw , ready for review.

**Review by kceiw — APPROVED** [review]

**Pull request merged**
