### PR TITLE
App Insight integration draft

### PR DESCRIPTION
**Pull request by xindzhan**
Draft implementation

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@xindzhan__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by hovsepm** [comment]
Please fix the build breaks

**Comment by stankovski** [comment]
@xindzhan merge conflicts

**Comment by xindzhan** [comment]
@hovsepm @stankovski  do you mind updating the cla-required tag for this one?

BTW this PR needs to wait for Mark's change in installer. I just want start the review early to catch any issues in the implementation.

**Comment by yugangw-msft** [comment]
please resolve the confliction

**Comment by ogail** [comment]
@xindzhan please resolve conflicts and resend the PR again

**Pull request closed without merging**
