### PR TITLE
[SQL] Fix\add AzSqlServerActiveDirectoryOnlyAuthentication APIs

### PR DESCRIPTION
**Pull request by amolagar5**
## Description

* Fix `Disable-AzSqlServerActiveDirectoryOnlyAuthentication`
* Added cmdlet `Get-AzSqlServerActiveDirectoryOnlyAuthentication`
* Added cmdlet `Enable-AzSqlServerActiveDirectoryOnlyAuthentication`

## Checklist

- [ ] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [ ] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — CHANGES_REQUESTED** [review]
Your PR has breaking change

```
 D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv Errors
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Cmdlet.DisableAzureSqlServerActiveDirectoryOnlyAuthentication","Disable-AzSqlServerActiveDirectoryOnlyAuthentication","0","1020","The cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' no longer has output type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'.","Make cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' return type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'."
  
  
  D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv:
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Cmdlet.DisableAzureSqlServerActiveDirectoryOnlyAuthentication","Disable-AzSqlServerActiveDirectoryOnlyAuthentication","0","1020","The cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' no longer has output type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'.","Make cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' return type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'."
```
Please try to remove the breaking change.

**Comment by amolagar5** [comment]
Hello, @msJinLei . 
this break is expected as we changed the API itself and created a new API. this is not impacting customers at this point as this is not being used by any customer right now. It was unusable right now. 
Do I need to add this to an override file to suppress this error. ?

**Comment by amolagar5** [comment]
> Your PR has breaking change
> 
> ```
>  D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv Errors
>   "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
>   "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Cmdlet.DisableAzureSqlServerActiveDirectoryOnlyAuthentication","Disable-AzSqlServerActiveDirectoryOnlyAuthentication","0","1020","The cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' no longer has output type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'.","Make cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' return type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'."
>   
>   
>   D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv:
>   "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
>   "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Cmdlet.DisableAzureSqlServerActiveDirectoryOnlyAuthentication","Disable-AzSqlServerActiveDirectoryOnlyAuthentication","0","1020","The cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' no longer has output type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'.","Make cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' return type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'."
> ```
> 
> Please try to remove the breaking change.

Hello @msJinLei ,
This break is expected as we changed the API itself and created a new API. this is not impacting customers at this point as this is not being used by any customer right now. It was unusable right now.
Do I need to add this to an override file to suppress this error. ?

**Comment by amolagar5** [comment]
Hello @msJinLei , let me know if there are any questions on this. 
I think below PR need to go in first, before I can merge this PR 
[SQL] Add Managed Database Log Replay service cmdlets #12800

**Comment by msJinLei** [comment]
> > Your PR has breaking change
> > ```
> >  D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv Errors
> >   "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
> >   "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Cmdlet.DisableAzureSqlServerActiveDirectoryOnlyAuthentication","Disable-AzSqlServerActiveDirectoryOnlyAuthentication","0","1020","The cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' no longer has output type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'.","Make cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' return type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'."
> >   
> >   
> >   D:\a\1\s\artifacts//StaticAnalysisResults\BreakingChangeIssues.csv:
> >   "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
> >   "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Cmdlet.DisableAzureSqlServerActiveDirectoryOnlyAuthentication","Disable-AzSqlServerActiveDirectoryOnlyAuthentication","0","1020","The cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' no longer has output type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'.","Make cmdlet 'Disable-AzSqlServerActiveDirectoryOnlyAuthentication' return type 'Microsoft.Azure.Commands.Sql.ServerActiveDirectoryAdministrator.Model.AzureSqlServerActiveDirectoryAdministratorModel'."
> > ```
> > 
> > 
> > Please try to remove the breaking change.
> 
> Hello @msJinLei ,
> This break is expected as we changed the API itself and created a new API. this is not impacting customers at this point as this is not being used by any customer right now. It was unusable right now.
> Do I need to add this to an override file to suppress this error. ?

Sorry for late response.

Can you email to @dcaro for the breaking change you want to suppress? We need confirmation of our PM, Thanks.

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
