### PR TITLE
Fixed pipelining issue with Get-AzureRmDisk

### PR DESCRIPTION
**Pull request by lfshr**
## Description
Partial fix for issue #3719 
Currently Get-AzureRmDisk returns a List<PSDisk> object, which is passed down the pipeline (as a List) which was not handled correctly. The following command will not work:
```
Get-AzureRmDisk | ? Name -eq 'Disk1'
```
The List object gets passed through the pipeline instead of the PSDisk object, so this query would return null, even if 'Disk1' exists (as a List object doesn't contain a Name parameter). The current work around is to create 2 pipelines:
```
(Get-AzureRmDisk) | ? Name -eq 'Disk1'
```

This PR strips out the List and writes the objects directly to the pipeline.

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270(v=vs.85).aspx).

- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [x] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyPSHelp-documentation.md).**
- [x] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**

### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).

### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.
- [x] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.

### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [x] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [x] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThru` parameter.

### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [x] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [x] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [x] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by markcowl** [comment]
@lfshr we aren't accepting any PRs until 4/12, please reopen after that

**Comment by markcowl** [comment]
@lfshr Again, why not just enumerate=true in the WriteObject call.  Also, we need a test for this so we don't regress

**Comment by lfshr** [comment]
Hi @markcowl, thanks for the response. I didn't realise WriteObject had a second overload. I'll give that a shot, thanks.

**Comment by lfshr** [comment]
@markcowl, worked a charm! Thanks very much 😄

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@lfshr  I like this change, we will need to move it to the preview branch, and we will get signoff from the storage team.

@blueww I think we want to accept this, please take a look and let me know if you have any concerns

**Comment by singhkays** [comment]
@hyonholee Can you review?

**Comment by markcowl** [comment]
@hyonholee @huangpf @singhkays Can you take a look at this PR?  The suggested fix appears to be in your code generator, and it should be enumerating collections by default if they are written to the output stream.  If this looks good, can we make this change acorss the board for the generator?

**Comment by lfshr** [comment]
@markcowl @hyonholee @huangpf @singhkays  I was wondering why there was a 'Generated' folder in the path. Is the generator open source / is there any documentation on this generator? Seems interesting

**Comment by lfshr** [comment]
@markcowl should I raise a new PR to preview?

**Comment by markcowl** [comment]
@lfshr Talked offlien with the service team - this code comes from a genrator and they have agrreed to update the generaotr to produce coee that enumerates collections, like this.  Closing, as we want to update the generator rather then the generated code.

**Comment by lfshr** [comment]
@markcowl awesome news, and good work :smile:

**Pull request closed without merging**
