### PR TITLE
Added Web Deploy change summary output

### PR DESCRIPTION
**Pull request by aneillans**
Part of issue #1095

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@aneillans__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by aneillans** [comment]
Looks like the test failure exists in the core branch of dev.

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by hovsepm** [comment]
@aneillans dev branch does not have any build issue. It looks like you have introduced a new dependency in your PR. In that case you will have to regenerate setup\azurecmdfiles.wxi file. You can do that by running tools\BuildInstaller.ps1 file.

**Comment by aneillans** [comment]
@hovsepm  Thanks for the info -- it's not a new dependency however - it's used by other assemblies in this package already, or is the tracking per assembly hence requiring the update? (Incidentally I can't see it being listed in the wxi file already).

**Comment by markcowl** [comment]
@aneillans assemblies are loaded per folder, so any new or removed dependencies in your project will require a wxi change.

**Comment by markcowl** [comment]
@aneillans You will need to make sure that this assembly is actually copied to the directory and that it is included in the wxi file.  You can find instructions on regenerating the wxi file here:  https://github.com/Azure/azure-powershell/wiki/Microsoft-Azure-PowerShell-Developer-Guide#updating-the-installer

**Comment by markcowl** [comment]
@aneillans Please respond, or we will have to close this pull request

**Comment by aneillans** [comment]
@markcowl apologies been backed up at work - will get to this hopefully this week.

**Comment by aneillans** [comment]
@markcowl Mark, I'm struggling to identify where this is actually failing - the assembly in question, Microsoft.Web.Deployment has not been added to any new locations that did not already reference it (Commands.Utilities and Commands) as such there should be no additional requirements to include any assemblies for the wxi file ?

**Comment by hovsepm** [comment]
@azuresdkci add to whitelist

**Comment by markcowl** [comment]
@aneillans The project may have had a reference to Microsoft.Web.Deployment, but this is the first actual usage, so that first time that reference was actually carried into the dll.

**Comment by aneillans** [comment]
@markcowl thats just it - it must have been used as its how WebDeploy is actually implemented.  I did not that there are records in the Exceptions files for the same errors. Wonder if they were being ignored?

**Comment by markcowl** [comment]
@aneillans  The previous references were from the utility assembly, which includes web deploymwnt in packages.config.  To fix this, please add the packages.config reference in the Commands package, and add in the exceptions for the new assembly. You will probably need to regenerate the wix file to have the assembly included.

After this, we'll take a look to make sure the assembly is copied to all the necessary directories.

**Comment by markcowl** [comment]
@aneillans looks like some ytest failures in website projects

**Comment by aneillans** [comment]
@markcowl took a bit of experimentation to get the tests running locally; but think I've resolved them. Fingers crossed!

**Comment by markcowl** [comment]
on demand run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/803/

**Comment by markcowl** [comment]
signing run here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-sign/433/

**Pull request merged**
