### PR TITLE
Feature/cplat add az vhd improve

### PR DESCRIPTION
**Pull request by grizzlytheodore**
## Description

This iteration of improvment
- Resolve VHD file path and only use that
- refactor validateVHD to getVDSLength
- covertVHD() and resizeVHD() functions return new filepaths
- if upload fails, clean up resource and return terminating error
- check OS at the beginning of resizeVHD() and convertVHD()
- add warnings at the beginning of resizeVHD() and convertVHD()

Future iteration
- option to skip MD5 hasing
- resize on the fly
- convert VHDX to VHD on the fly

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [ ] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by grizzlytheodore** [comment]
@VeryEarly @msJinLei  could someone be assigned approve/merge please !

**Comment by VeryEarly** [comment]
please update https://github.com/Azure/azure-powershell/blob/feature/cplat-Add-AzVhdImprove/src/Compute/Compute/ChangeLog.md

**Comment by grizzlytheodore** [comment]
@VeryEarly updated. most of the changes are behind the scenes change that do not change any customer experience, but i added the the changes that do impact customers

**Comment by VeryEarly** [comment]
> @VeryEarly updated. most of the changes are behind the scenes change that do not change any customer experience, but i added the the changes that do impact customers

**Comment by VeryEarly** [comment]
closed the pr in accident, will merge after CI passed

**Review by VeryEarly — DISMISSED** [review]

**Review by VeryEarly — APPROVED** [review]

**Pull request merged**
