### PR TITLE
vulnerability assessment cmdlets add support for using server managed…

### PR DESCRIPTION
**Pull request by a7mad-3bbas**
… identity for authentication with storage

remove git ignore elements that were added by mistake

more changes with change logs and updates to tests

resolve conflict that was introduced after sync

update test record sessions and solve issues with found by tests.

more fixes

update documentation for new parameter.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by isra-fel** [comment]
Hi @a7mad-3bbas please join azure-members team: http://aka.ms/AzureGithub and also fix the conflicts. THanks

**Comment by a7mad-3bbas** [comment]
> Hi @a7mad-3bbas please join azure-members team: http://aka.ms/AzureGithub and also fix the conflicts. THanks

done.

**Comment by isra-fel** [comment]
Static analysis failed because it detected breaking change:
```
  "AssemblyFileName","ClassName","Target","Severity","ProblemId","Description","Remediation"
  "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.VulnerabilityAssessment.Cmdlet.VulnerabilityAssessmentRuleBaseline.SetAzureSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline","Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline","0","1050","The parameter set 'SetByInputObjectParameterSet' for cmdlet 'Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline' has been removed.","Add parameter set 'SetByInputObjectParameterSet' back to cmdlet 'Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline'."
  "Microsoft.Azure.PowerShell.Cmdlets.Sql.dll","Microsoft.Azure.Commands.Sql.VulnerabilityAssessment.Cmdlet.VulnerabilityAssessmentRuleBaseline.SetAzureSqlManagedDatabaseVulnerabilityAssessmentRuleBaseline","Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline","0","1050","The parameter set '__AllParameterSets' for cmdlet 'Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline' has been removed.","Add parameter set '__AllParameterSets' back to cmdlet 'Set-AzSqlInstanceDatabaseVulnerabilityAssessmentRuleBaseline'."
```

**Comment by msJinLei** [comment]
@a7mad-3bbas Please resolve the conflicts.

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by isra-fel** [comment]
We are closing the PR @a7mad-3bbas
If you decide to continue working on the PR, we suggest create a new branch and cherry-pick your commits.
(10000 commits shows up in the history because we force-pushed to master a few months ago due to a security issue. Sorry for the inconvenience!)

**Pull request closed without merging**
