### PR TITLE
Fix for New-AzureRmRoleAssignment and Remove-AzureRmRoleAssignment fo…

### PR DESCRIPTION
**Pull request by bganapa**
## Description

Fix for New-AzureRmRoleAssignment and Remove-AzureRmRoleAssignment for ADFS scenario

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by bganapa** [comment]
Updated this PR with commits from https://github.com/Azure/azure-powershell/pull/7221 which got in to preview already

**Comment by bganapa** [comment]
@maddieclayton Could you please help why these IOTHub tests are failing... I have already retried..

If they are fixed in preview branch.. can we override and merge this PR?

System.Management.Automation.ParameterBindingException : A parameter cannot be found that matches parameter name '-TextExtension'.

**Comment by bganapa** [comment]
@cormacpayne /@markcowl as well if they know about these IOT hub test failures.. I have already retired. Thanks for looking in to this!

**Comment by deathly809** [comment]
@bganapa All the admin tests seem to be failing.

```
Import-Module : The required module 'AzureRM.Profile' is not loaded. Load the 
```

**Comment by bganapa** [comment]
@deathly809 Asides we should enable failing of the job when the pester tests are failing..

**Comment by bganapa** [comment]
@maddieclayton @deathly809  The admin tests are passing now

**Pull request merged**
