### PR TITLE
(AzureCXP) Add a note about handling Production slots during Swap operations

### PR DESCRIPTION
**Pull request by BhargaviAnnadevara**
Address feedback provided as part of https://github.com/MicrosoftDocs/azure-docs-powershell/issues/1887

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] **(N/A)** The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] **(N/A)** If applicable, the changes made in the PR have proper test coverage
- [x] **(N/A)** For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - {Please put the link here}
    - [x] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikefrobbins This PR just adds a note about handling production slots while performing a swap operation. No breaking changes as such. Marked the tasks in checklist accordingly.

Please review and provide feedback. Thanks.

**Review by mikefrobbins — CHANGES_REQUESTED** [review]
See my suggestion for changes.

**Comment by BhargaviAnnadevara-MSFT** [comment]
@mikefrobbins Thanks for the feedback! Committed suggestions.

**Review by mikefrobbins — APPROVED** [review]
LGTM

**Comment by BhargaviAnnadevara-MSFT** [comment]
@isra-fel Is this good to go?

**Pull request merged**
