### PR TITLE
Added secure string conversion in New-TestCredential and made minor fixes

### PR DESCRIPTION
**Pull request by ArmaanMcleod**
## Description

Added secure string conversion to example commands in test framework documentation. The `ServicePrincipalSecret` parameter is of type `System.SecureString` so passing in a plain text password to `New-TestCredential` will not work.

Also fixed up some of the environment variable setting code to make sure output is consistent with `TEST_CSM_ORGID_AUTHENTICATION` env variable, and used `AppId` instead of `ApplicationId` when setting the application ID for the SPN.

## Checklist

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** select appropriate branch. Cmdlets from Autorest.PowerShell should go to [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch. 
* **SHOULD** make the title of PR clear and informative, and in the present imperative tense. 
* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. Add changelog in description section if PR goes into [`generation`](https://github.com/Azure/azure-powershell/tree/generation) branch.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** have approved design review for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) ([_Microsoft internal only_](../blob/main/CONTRIBUTING.md#onboarding)) with following situations
    * Create new module from scratch
    * Create new resource types which are not easy to conform to [Azure PowerShell Design Guidelines](../blob/main/documentation/development-docs/design-guidelines)
    * Create new resource type which name doesn't use module name as prefix
    * Have design question before implementation
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** introduce [breaking changes](../blob/main/documentation/breaking-changes/breaking-changes-definition.md) in Az minor release except preview version.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Comment by dingmeng-xue** [comment]
@vidai-msft , please review this pull request.

**Comment by vidai-msft** [comment]
@ArmaanMcleod Thanks for your efforts and contribution to the Azure PowerShell. We have received lots of feedback from both internal and external regarding the documentation and script on the test framework. So we planned to re-write the script to build up the test environment and then revise the document accordingly. If you still see anything wrong or something can be improved after that, welcome to raise a new PR. Thank you again for your continuous participation and support on Microsoft open-source projects!

**Comment by ArmaanMcleod** [comment]
> @ArmaanMcleod Thanks for your efforts and contribution to the Azure PowerShell. We have received lots of feedback from both internal and external regarding the documentation and script on the test framework. So we planned to re-write the script to build up the test environment and then revise the document accordingly. If you still see anything wrong or something can be improved after that, welcome to raise a new PR. Thank you again for your continuous participation and support on Microsoft open-source projects!

@vidai-msft Appreciate the response. Its great hearing it's going to rewritten and improved from feedback. When will this be ready to be consumed?

In the current state there are quite a bit of problems as I've addressed in this PR, what can we use in the meantime until the new version is ready? Would it not be better to at least fix some of the obvious problems temporarily until the better version is ready to go? That at least lets new contributors and others not get stumped just trying to get the test environment sorted.

**Comment by vidai-msft** [comment]
@ArmaanMcleod The work will be done within this month. The function Print-ConnectionString you modified will be removed and  New-TestCredential will be replaced with a better version because except for what you changed, it also has other issues. Please kindly re-visit this page once the new one is released. Thanks!

**Comment by ArmaanMcleod** [comment]
@vidai-msft No worries, thanks for taking the time to respond. Looking forward to seeing the new testing framework. I will close this PR and and add any new changes after the new version is released 🙂.

**Pull request closed without merging**
