### PR TITLE
Creating cmdlets for Health Deidentification (GA)

### PR DESCRIPTION
**Pull request by alexathomases**
## Mandatory Checklist

- Please choose the target release of Azure PowerShell. (⚠️**Target release** is a different concept from **API readiness**. Please click below links for details.)
  - [x] [General release](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Public preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Private preview](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] [Engineering build](../blob/main/CONTRIBUTING.md#target-release-types)
  - [ ] No need for a release

- [x] Check this box to confirm: **I have read the [_Submitting Changes_](../blob/main/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/main/CONTRIBUTING.md) and reviewed the following information:**

* **SHOULD** update `ChangeLog.md` file(s) appropriately
    * For SDK-based development mode, update `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`.
        * A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header in the past tense. 
    * For autorest-based development mode, include the changelog in the PR description.
    * Should **not** change `ChangeLog.md` if no new release is required, such as fixing test case only.
* **SHOULD** regenerate markdown help files if there is cmdlet API change. [Instruction](../blob/main/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)
* **SHOULD** have proper test coverage for changes in pull request.
* **SHOULD NOT** adjust version of module manually in pull request

### CODE REVIEW

**Review by Nickcandy — APPROVED** [review]

**Comment by Nickcandy** [comment]
Hi @alexathomases, I'd like to ask whether you're expecting the Health Deidentification module to be released as the 0.1.0 preview version or the 1.0.0 GA version?

**Comment by Nickcandy** [comment]
@alexathomases  And your code have some issues here. Please help fix them: https://dev.azure.com/azclitools/public/_build/results?buildId=199240&view=logs&j=b9afb22f-0837-5d02-bc24-6c30aee08bcf&t=990f6f37-4a21-5927-092a-220f38a460e9

**Comment by alexathomases** [comment]
> Hi @alexathomases, I'd like to ask whether you're expecting the Health Deidentification module to be released as the 0.1.0 preview version or the 1.0.0 GA version?

Hi @Nickcandy, the Health Deidentification module is part of our GA lifecycle requirement, but we are using our preview API version. Should I change the version in README.md to 1.0.0?

**Comment by alexathomases** [comment]
> @alexathomases And your code have some issues here. Please help fix them: https://dev.azure.com/azclitools/public/_build/results?buildId=199240&view=logs&j=b9afb22f-0837-5d02-bc24-6c30aee08bcf&t=990f6f37-4a21-5927-092a-220f38a460e9

@Nickcandy, I found the issue - I removed the documentation and examples for the Get-AzHealthDeidPrivateLink cmdlet because I do not want it to be used. However, I didn't know how to stop the cmdlet from being generated. Is the proper way to do that to add a directive to remove it in README.md?

**Comment by Nickcandy** [comment]
> > Hi @alexathomases, I'd like to ask whether you're expecting the Health Deidentification module to be released as the 0.1.0 preview version or the 1.0.0 GA version?
> 
> Hi @Nickcandy, the Health Deidentification module is part of our GA lifecycle requirement, but we are using our preview API version. Should I change the version in README.md to 1.0.0?

No need. Your first module version would be 0.1.0

**Pull request merged**
