### PR TITLE
Batch cmdlets for terminating job schedules, jobs, and tasks

### PR DESCRIPTION
**Pull request by jasper-schneider**
3 new cmdlets:
Stop-AzureBatchJobSchedule
Stop-AzureBatchJob
Stop-AzureBatchTask

Includes test updates and help.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@jasper-schneider__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (jaschnei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by jasper-schneider** [comment]
Test errors don't look related to my changes.  How would you like me to proceed?

"D:\workspace\powershell\build.proj" (Full target) (1) ->
(InvokeXUnit target) -> 
  D:\workspace\powershell\AzurePowershell.test.targets(83,5): error MSB3073: The command "D:\workspace\powershell\packages\xunit.runner.console.2.0.0\tools\xunit.console.x86.exe ".\src\ResourceManager\Compute\Commands.Compute.Test\bin\Debug\Microsoft.Azure.Commands.Compute.Test.dll" -trait "AcceptanceType=CheckIn" -html ".\src\Publish\TestResults\Microsoft.Azure.Commands.Compute.Test.html"" exited with code 1. [D:\workspace\powershell\build.proj]


"D:\workspace\powershell\build.proj" (Full target) (1) ->
(TimeoutErrorHandler target) -> 
  D:\workspace\powershell\AzurePowershell.test.targets(99,5): error : XUnit tests in assembly "Microsoft.Azure.Commands.AzureBackup.Test.dll" failed or timed out. Ensure that all tests in a project pass and collectively take less than 1 minute to run. [D:\workspace\powershell\build.proj]

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by markcowl** [comment]
on-dmeand run is here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/161/

**Comment by markcowl** [comment]
@jasper-schneider Please add these changes to the changelog

**Comment by jasper-schneider** [comment]
Updated changelog to include these cmdlets as well as some cmdlets that were added last week.

**Comment by markcowl** [comment]
on demand run here:  http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/168/

**Pull request merged**
