### PR TITLE
Call validate when submitting deployments

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by vivsriaus** [comment]
On demand job here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/645/

**Comment by markcowl** [comment]
@azuresdkci retest this please

**Comment by vivsriaus** [comment]
@markcowl new on demand job here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/647/

**Comment by vivsriaus** [comment]
New on demand here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/649/

**Pull request merged**
