### PR TITLE
Get Server Variables API Powershell Changes

### PR DESCRIPTION
**Pull request by nirkum18**
## Description

Application Gateway supports certain server variables that can be used for Header CRUD feature. There are lists of suggested Request and Response Headers. These commandlets will allow the user to fetch the supported server variables' list and the suggested request and response headers' lists.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by vladimir-shcherbakov** [comment]
@azuresdkci Add to whitelist

**Comment by vladimir-shcherbakov** [comment]
@nirkum18 ci-builds failed.

**Comment by maddieclayton** [comment]
@nirkum18 Please link the related design review for this issue: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues. If you have not done this yet, please do so and link it here.

**Comment by maddieclayton** [comment]
@nirkum18 It also look like you have picked up some extra changes unrelated to yours. Please make sure that only your commits are included in this PR.

**Comment by nirkum18** [comment]
Design Review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/224

**Comment by maddieclayton** [comment]
@nirkum18 Please update this PR so that the only changes are your own. Please also add help for your new cmdlets: https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md

**Comment by nirkum18** [comment]
> @nirkum18 Please update this PR so that the only changes are your own. Please also add help for your new cmdlets: https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md

@maddieclayton This branch got messed up with large number of unwanted changes. Had to create a new PR for this with the exact same changes. PR link: https://github.com/Azure/azure-powershell/pull/8532

**Comment by maddieclayton** [comment]
Closing in favor of new PR with correct commit history

**Pull request closed without merging**
