### PR TITLE
Dtl ps mithuns

### PR DESCRIPTION
**Pull request by mithunshanbhag**
Initial commit of the powershell cmdlets for the new Azure DevTestLab RP 

The following cmdlets are now exposed:
- Get-AzureDtlLab
- Get-AzureDtlEnvironment
- Get-AzureDtlVMTemplate
- New-AzureDtlEnvironment

Cmdlet help and usage examples can now been seen by running "get-help" and "get-help -examples" on the DevTestLab cmdlets.

Scenario tests added.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@mithunshanbhag__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>
        In order for us to evaluate and accept your PR, we ask that you sign a contribution license agreement. It's all electronic and will take just minutes. I promise there's no faxing. https://cla.azure.com.
    </span>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
__@mithunshanbhag__, Thanks for signing the contribution license agreement so quickly! Actual humans will now validate the agreement and then evaluate the PR.
<br />Thanks, AZPRBOT;

**Comment by hovsepm** [comment]
Please pull and merge from upstream dev branch.

**Comment by mithunshanbhag** [comment]
Done.

**Comment by hovsepm** [comment]
@azuresdkci test this please

**Comment by markcowl** [comment]
@mithunshanbhag We are creting an installer for partner testing today and have created a release branch.  Please retarget your PR at the release branch (release-1.0.0) to make it into this release.

**Pull request closed without merging**
