### PR TITLE
Add private link support for Redis Enterprise

### PR DESCRIPTION
**Pull request by greenms**
## Description

Update 1 file (ProviderConfiguration.cs) on master branch to support Redis Enterprise private links.

This is a companion PR to #13498

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
        - https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/767
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Review by msJinLei — CHANGES_REQUESTED** [review]
@greenms Please add the description item to ChangeLog.md of src/Network.

**Comment by greenms** [comment]
> @greenms Please add the description item to ChangeLog.md of src/Network.

@msJinLei It doesn't appear that we update the change log in this case.  At least, that's what @isra-fel said 12 days ago.  Link to support my statement: https://github.com/Azure/azure-powershell/pull/13403

**Comment by isra-fel** [comment]
Taked with Jin Lei offline. Yes, you don't need to update changelog for enabling private link

**Review by msJinLei — APPROVED** [review]

**Pull request merged**
