### PR TITLE
remove azureASN parameter

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
@DeepakRajendranMsft please update module version to reflect the change in the API. Since we have not gone 1.0 yet, it's OK to just increase a minor version yet, however after 1.0 release this will be considered a major version change.

**Comment by DeepakRajendranMsft** [comment]
@stankovski I have updated the versions to 0.9.11. is that okay?

**Comment by ogail** [comment]
@DeepakRajendranMsft please update https://github.com/DeepakRajendranMsft/azure-powershell/blob/ERBugs/src/ResourceManager/Network/AzureRM.Network.psd1 as well

**Comment by DeepakRajendranMsft** [comment]
@ogail done!

**Pull request merged**
