### PR TITLE
Shows tags table in output for Get-AzResource

### PR DESCRIPTION
**Pull request by hamidtirmizi**
## Description

This change only modifies the output format for the `Get-AzResource` cmdlet to display tags. Same output for tags is already present in other cmdlets like `Get-AzResourceGroup`.

No change to the behavior.

## Checklist

- [x] I have read the [_Submitting Changes_](../blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](../blob/master/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate `ChangeLog.md` file(s) has been updated:
    - For any service, the `ChangeLog.md` file can be found at `src/{{SERVICE}}/{{SERVICE}}/ChangeLog.md`
    - A snippet outlining the change(s) made in the PR should be written under the `## Upcoming Release` header -- no new version header should be added
- [x] The PR does not introduce [breaking changes](../blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [ ] a cmdlet design review was approved for the changes in [this repository](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (_Microsoft internal only_)
    - [ ] the markdown help files have been regenerated using the commands listed [here](../blob/master/documentation/development-docs/help-generation.md#updating-all-markdown-files-in-a-module)

### CODE REVIEW

**Comment by wyunchi-ms** [comment]
Hi @hamidtirmizi , it's great to add the tags table of `Get-AzResource`. Would you like to add this to the examples in the help document of `Get-AzResource`. Thanks!

**Comment by cormacpayne** [comment]
@hamidtirmizi Hey Hamid, I'm no longer a part of the Azure PowerShell team, so I have removed myself as a reviewer 😊

**Pull request merged**
