### PR TITLE
Check deployment exists before calling listOperations on a deployment

### PR DESCRIPTION
**Pull request by vivsriaus**

### CODE REVIEW

**Comment by vivsriaus** [comment]
On demand here: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/743/

**Comment by markcowl** [comment]
@vivsriaus  there is a release branch, so if this is intended for this release, please retarget

**Comment by vivsriaus** [comment]
@markcowl Thanks. [Here](https://github.com/Azure/azure-powershell/pull/2171) is the new PR targeting the release branch.

**Comment by hovsepm** [comment]
PR re-targeted to release branch in #2171

**Pull request closed without merging**
