### PR TITLE
RDBug 6413346:[PSH] Get-AzureStorageAccount failed with TooManyRequests when there are 85+ accounts in a subscription

### PR DESCRIPTION
**Pull request by blueww**
Changes:
1. Fixed the following bug by implement the prototype code from Mark in both service and resource mode code.: RDBug 6413346:[PSH] Get-AzureStorageAccount failed with TooManyRequests when there are 85+ accounts in a subscription
2. Fix the AzureStorageContext.EndPointSuffix get function, as it can't get suffix on blobStorage Kind Accounts (don't have table endpoint).

What test we have done:
1. The PR has passed storage team regression test.
2. In manual test, get-AzureStorageAccount running time decrease from 75s to 15s for 67 accounts. (resource mode has similar behavior)

### CODE REVIEW

**Comment by blueww** [comment]
The on demond build is:http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/808/

**Comment by blueww** [comment]
I tried to run [on demond test,](http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-demand/811/), 4 cases failed with: 

> File not found Resources\TestApplicationPackage.zip

Other cases all passed.

It seems this is a test issue, and is related with my code change.

**Comment by markcowl** [comment]
LGTM, need to wait until github gets over its minor issues with pushes before mreging.

**Comment by hovsepm** [comment]
@blueww on-demand failures are fixed in dev branch now.

**Pull request merged**
