### PR TITLE
Bump Network SDK version to 19.0.0-preview

### PR DESCRIPTION
**Pull request by anton-evseev**
## Description

Bump Network SDK version to 19.0.0-preview

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by maddieclayton** [comment]
@number213 You will need to bump the version of Network for all dependent modules.  For an example of the last bump to network, see here: https://github.com/Azure/azure-powershell/pull/5993

**Comment by maddieclayton** [comment]
@number213 One more small fix, please update the network change file to ensure this change gets released: https://github.com/Azure/azure-powershell/blob/preview/src/ResourceManager/Network/ChangeLog.md

**Comment by number213** [comment]
@maddieclayton done

**Comment by maddieclayton** [comment]
on demand run here: https://azuresdkci.westus2.cloudapp.azure.com/view/PowerShell/job/powershell-demand/821/

**Pull request merged**
