### PR TITLE
ADL Updates to latest SDK in preparation for GA

### PR DESCRIPTION
**Pull request by begoldsm**
## Description

This brings ADL powershell up to the latest SDK version in preparation for GA. The latest SDK is still preview, however it is our first GA candidate SDK and needs to be included in powershell to bring the following features:
1. Drastically improved download performance for distributed file and folder downloads
2. Better error handling and messaging for uploads and downloads
3. Full credential CRUD management, which is replacing Secret CRUD (secret CRUD is deprecated this release)
4. Full Firewall Rule CRUD
5. Full TrustedIdProvider CRUD
6. ADLS Account encryption support
7. Help improvements to better explain the difference between GET and LIST jobs
8. Get-AdlCatalogItem fixes for bad input.

---

This checklist is used to make sure that common guidelines for a pull request are followed. You can find a more complete discussion of PowerShell cmdlet best practices [here](https://msdn.microsoft.com/en-us/library/dd878270%28v=vs.85%29.aspx).
- [x] **I have read the [contribution guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md).**
- [x] **If changes were made to any cmdlet, the XML help was regenerated using the [platyPSHelp module](https://github.com/Azure/azure-powershell/blob/dev/documentation/platyps-help.md).**
- [x] **If any large changes are made to a service, they are reflected in the respective [change log](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#updating-the-change-log).**
### [General Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#general-guidelines)
- [x] Title of the pull request is clear and informative.
- [x] There are a small number of commits, each of which have an informative message. This means that previously merged commits do not appear in the history of the PR. For more information on cleaning up the commits in your PR, [see this page](https://github.com/Azure/azure-powershell/blob/dev/documentation/cleaning-up-commits.md).
- [x] The pull request does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/dev/documentation/breaking-changes.md) (unless a major version change occurs in the assembly and module).
### [Testing Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#testing-guidelines)
- [x] Pull request includes test coverage for the included changes.
- [x] PowerShell scripts used in tests should do any necessary setup as part of the test or suite setup, and should not use hard-coded values for locations or existing resources.
### [Cmdlet Signature Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-signature-guidelines)
- [x] New cmdlets that make changes or have side effects should implement `ShouldProcess` and have `SupportShouldProcess=true` specified in the cmdlet attribute. You can find more information on `ShouldProcess` [here](https://gist.github.com/markcowl/338e16fe5c8bbf195aff9f8af0db585d#what-is-the-change).
- [x] Cmdlet specifies `OutputType` attribute if any output is produced - if the cmdlet produces no output, it should implement a `PassThrough` parameter.
### [Cmdlet Parameter Guidelines](https://github.com/Azure/azure-powershell/blob/dev/CONTRIBUTING.md#cmdlet-parameter-guidelines)
- [x] Parameter types should not expose types from the management library - complex parameter types should be defined in the module.
- [x] Complex parameter types are discouraged - a parameter type should be simple types as often as possible. If complex types are used, they should be shallow and easily creatable from a constructor or another cmdlet.
- [x] Cmdlet parameter sets should be mutually exclusive - each parameter set must have at least one mandatory parameter not in other parameter sets.

### CODE REVIEW

**Comment by begoldsm** [comment]
@markcowl everything is passing here, but this shouldn't be merged until my SDK PR (https://github.com/Azure/azure-sdk-for-net/pull/2496) is merged. At that point, I will publish the packages and remove them from the localfeed in this PR.

**Comment by markcowl** [comment]
@begoldsm your .net sdk PR is merged.  Please remove [Hopld] from the PR title once you have integrated the SDK from nuget

**Comment by begoldsm** [comment]
@markcowl done! All packages are published now and I have commited the removal of the localfeed directory and updated the title. I will monitor the CI to ensure that it is properly pulling from the published packages.

**Comment by markcowl** [comment]
Marked as hold pending a discussion of breaking changes

**Comment by begoldsm** [comment]
@markcowl I made the obsolete updates we discussed for USqlCredential (made a new object aptly named "ObsoleteUSqlCredential") which contains obsolete tags and warnings, particularly for the properties that are explicitly gone. In the future we may further clean up the credential object to remove it from the base "CatalogItem", since "computeAccountName" and "version" are never used, but that is a change for another day :).

**Comment by begoldsm** [comment]
Closing this PR to re-target the release branch.

**Pull request closed without merging**
