### PR TITLE
[HDINSIGHT] NullRef SShCreds bug

### PR DESCRIPTION
**Pull request by nemanja88**
Fixing a bug where a null ref was thrown when SSh is not provided for Linux clusters.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@nemanja88__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (nemadj). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@azuresdkci test this please

**Comment by shahabhijeet** [comment]
@nemanja88 I don't see any test coverage for this case, as it seems like you fixed a null ref issue.

**Comment by markcowl** [comment]
@nemanja88 Please add test coverage to prevent regressions.

**Comment by markcowl** [comment]
@nemanja88 Please respond.  We will have to close this PR at EOW if there is no response to review comments.

**Comment by markcowl** [comment]
@azuresdkci add to whitelist

**Pull request merged**
