### PR TITLE
New cmdlets to create/enter PSSession in remote container app

### PR DESCRIPTION
**Pull request by vinisoto**
## Description

Adding cmdlets for Entering/Creating a PowerShell remote session into a Windows Containers web app

Design Review: https://github.com/Azure/azure-powershell-cmdlet-review-pr/issues/145

These changes where excluded from [a previous PR](https://github.com/Azure/azure-powershell/pull/7307/commits/8fe05041420f90aa3f16956574c18fc4a8d78fb6)

Followed recommendations from @MiYanni and have made changes to check for PowerShell version and make sure that we don't expect WSMAN when not running on Windows.

## Checklist

- [x] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md)
- [x] The title of the PR is clear and informative
- [x] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/preview/CONTRIBUTING.md#updating-the-change-log)
- [x] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/preview/documentation/breaking-changes/breaking-changes-definition.md)
- [x] If applicable, the changes made in the PR have proper test coverage
- [x] For public API changes to cmdlets:
    - [x] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr)
    - [x] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/preview/documentation/development-docs/help-generation.md)

FYI @jvano , @panchagnula

### CODE REVIEW

**Comment by adxsdkps** [comment]
Can one of the admins verify this patch?

**Comment by cormacpayne** [comment]
@azuresdkci add to whitelist

**Comment by vinisoto** [comment]
Hi @MiYanni - since all checks have passed. Would you mind reviewing this? I have opened [an Issue](https://github.com/Azure/azure-powershell/issues/7440) to track the issue where xUnit configuration is using PowerShell 6.0 instead of 6.1.

**Comment by vinisoto** [comment]
Thanks @MiYanni - updated the Changelog

**Pull request merged**
