### PR TITLE
Merge pull request #8033 from zwswim/network-november-release

### PR DESCRIPTION
**Pull request by zwswim**
## Description

[NSG Flowlog] add three optional parameters to NetworkWatcherConfigFlowLog Operations

This request is to merger the  pull request #8033 from zwswim/network-november-release, which has been merged to master at "12/10/2018"

## Checklist

- [ ] I have read the [_Submitting Changes_](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#submitting-changes) section of [`CONTRIBUTING.md`](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md)
- [ ] The title of the PR is clear and informative
- [ ] The appropriate [change log has been updated](https://github.com/Azure/azure-powershell/blob/master/CONTRIBUTING.md#updating-the-change-log)
- [ ] The PR does not introduce [breaking changes](https://github.com/Azure/azure-powershell/blob/master/documentation/breaking-changes/breaking-changes-definition.md)
- [ ] If applicable, the changes made in the PR have proper test coverage
- [ ] For public API changes to cmdlets:
    - [ ] the changes have gone through a [cmdlet design review](https://github.com/Azure/azure-powershell-cmdlet-review-pr) (Microsoft internal partners only)
    - [ ] the cmdlet markdown files were [generated using the `platyPS` module](https://github.com/Azure/azure-powershell/blob/master/documentation/development-docs/help-generation.md)

### CODE REVIEW

**Comment by markcowl** [comment]
@MikhailTryakhov Can you please take  alook at this?

**Comment by MiYanni** [comment]
This PR is waiting for `Azure:network-december-release` to be updated with latest master. @MikhailTryakhov is working on the PR for this.

**Comment by cormacpayne** [comment]
@zwswim would you mind pulling the latest changes from `master` and resolve the merge conflicts?

**Comment by zwswim** [comment]
@cormacpayne  Just want to make sure we are on the same page.  I do the cherry-pick to my local Network-Dec branch. Then, I created this PR request.

when you said that "pull the latest changes from Master":  Do you mean you want to "Azure:network-december-release to be updated with latest master" ?   Then I think that we should create another PR to do it

**Comment by MiYanni** [comment]
@cormacpayne This PR was waiting on @MikhailTryakhov to update the `network-december-release` branch. Then, this branch would pull in the latest from that.

**Comment by zwswim** [comment]
@cormacpayne Got u.  As soon as the upstream Network-December branch ready, I will pull from upstream Network-December.

Or you mean, it is ready ?

**Comment by cormacpayne** [comment]
@zwswim oops, correct, pull from `network-december-release` instead of `master` 😁

**Comment by zwswim** [comment]
@cormacpayne Just curious,  if we already merger latest change from master,  it should already include all my changes in the PR.  Do we need this pr any more ?

**Comment by zwswim** [comment]
@cormacpayne I confirmed that the change I made before  Dec 10, 2018  are already in "network-december" branch. 

Looks like that we could cancel  this PR

**Pull request closed without merging**
