### PR TITLE
AzureRT S52 - Preview Cmdlets

### PR DESCRIPTION
**Pull request by huangpf**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@huangpf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (phuang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by huangpf** [comment]
retest this please

**Comment by azurecla** [comment]
Hi __@huangpf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (phuang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by azurecla** [comment]
Hi __@huangpf__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (phuang). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by stankovski** [comment]
Running on-demand job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/32/
Running msi job: http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/354/

**Comment by stankovski** [comment]
@huangpf please review test output

**Comment by huangpf** [comment]
@stankovski 
The errors are not related to our project, and the message seems to be inconsistent.

Test message - Passed:
```

  Discovering: Microsoft.Azure.Commands.AzureBackup.Test
  Discovered:  Microsoft.Azure.Commands.AzureBackup.Test
  Starting:    Microsoft.Azure.Commands.AzureBackup.Test
  Finished:    Microsoft.Azure.Commands.AzureBackup.Test
  
  === TEST EXECUTION SUMMARY ===
     Microsoft.Azure.Commands.AzureBackup.Test  Total: 2, Errors: 0, Failed: 0, Skipped: 0, Time: 15.443s
```

Build message - Failed:
```

(TimeoutErrorHandler target) -> 
error : XUnit tests in assembly "Microsoft.Azure.Commands.AzureBackup.Test.dll" failed or timed out. Ensure that all tests in a project pass and collectively take less than 1 minute to run. 
```

The actual failed test:
```
Microsoft.WindowsAzure.Commands.Test.Websites.SaveAzureWebsiteLogTests.SaveAzureWebsiteLogTest [FAIL]
        System.IO.FileNotFoundException : Could not find file 'D:\workspace\powershell-on-demand\logs.zip'.
        Stack Trace:
              at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
              at System.IO.FileStream.Init(String path, FileMode mode, FileAccess access, Int32 rights, Boolean useRights, FileShare share, Int32 bufferSize, FileOptions options, SECURITY_ATTRIBUTES secAttrs, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
              at System.IO.FileStream..ctor(String path, FileMode mode, FileAccess access, FileShare share, Int32 bufferSize, FileOptions options, String msgPath, Boolean bFromProxy, Boolean useLongPath, Boolean checkHost)
              at System.IO.StreamReader..ctor(String path, Encoding encoding, Boolean detectEncodingFromByteOrderMarks, Int32 bufferSize, Boolean checkHost)
              at System.IO.File.InternalReadAllText(String path, Encoding encoding, Boolean checkHost)
              at System.IO.File.ReadAllText(String path)
              at Microsoft.Azure.Common.Authentication.Models.DiskDataStore.ReadFileAsText(String path)
           src\ServiceManagement\Services\Commands.Test\Websites\SaveAzureWebsiteLogTests.cs(98,0): at Microsoft.WindowsAzure.Commands.Test.Websites.SaveAzureWebsiteLogTests.SaveAzureWebsiteLogTest()
     Microsoft.WindowsAzure.Commands.Test.Websites.ShowAzurePortalTests.ProcessGetAzurePublishSettingsTest [SKIP]
        Consider removing these.
     Microsoft.WindowsAzure.Commands.Test.Websites.ShowAzureWebsiteTests.ProcessShowWebsiteTest [SKIP]
        Consider removing these.
  Finished:    Microsoft.WindowsAzure.Commands.Test
  
  === TEST EXECUTION SUMMARY ===
     Microsoft.WindowsAzure.Commands.Test  Total: 430, Errors: 0, Failed: 1, Skipped: 12, Time: 54.784s
```

**Comment by huangpf** [comment]
Rerun:
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/36/

**Pull request merged**
