### PR TITLE
change help for Get-AzureStorageFile since cmdlet behavior change

### PR DESCRIPTION
**Pull request by blueww**
change help for Get-AzureStorageFile since cmdlet behavior change.

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@blueww__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (weiwei). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by hovsepm** [comment]
LGTM.
@blueww Please send a code review mail whenever you will finish this PR.

**Comment by EmmaZhu** [comment]
@blueww is from storage team, we've reviewed this change. Thanks for reminding her for the review.

**Comment by blueww** [comment]
Emma has already merge the CR to her CR

**Pull request closed without merging**
