### PR TITLE
Use Network swagger client

### PR DESCRIPTION
**Pull request by DeepakRajendranMsft**

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@DeepakRajendranMsft__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <span>You've already signed the contribution license agreement. Thanks!</span>
        <span>We will now validate the agreement and then real humans will evaluate your PR.</span>

TTYL, AZPRBOT;

**Comment by markcowl** [comment]
@DeepakRajendranMsft There are merge conflicts, please update

**Comment by Nilambari** [comment]
Discussed with @markcowl , as there were some merge conflicts. Opened new PR for merging these changes after resolving merge conflicts. New PR:- https://github.com/Azure/azure-powershell/pull/1376   So,we can close this PR (https://github.com/Azure/azure-powershell/pull/1351)

**Comment by markcowl** [comment]
@DeepakRajendranMsft @Nilambari Closing in favor of Nilambari's PR

**Pull request closed without merging**
