### PR TITLE
AzureRT update

### PR DESCRIPTION
**Pull request by hyonholee**
1. Fix Publish Extension cmdlets
2. Update VMAccess cmdlets to support Json config.
3. Update CustomScript cmdlet for SAS Uri

### CODE REVIEW

**Comment by azurecla** [comment]
Hi __@hyonholee__, I'm your friendly neighborhood Azure Pull Request Bot (You can call me AZPRBOT). Thanks for your contribution!
    <p>
        It looks like you're working at Microsoft (hylee). If you're full-time, we DON'T require a contribution license agreement.
    </p>
    <p>
        If you are a vendor, or work for Microsoft Open Technologies, DO please sign the electronic contribution license agreement. It will take 2 minutes and there's no faxing! https://cla.azure.com.
    </p>

TTYL, AZPRBOT;

**Comment by yugangw-msft** [comment]
http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-msi/

http://azuresdkci.cloudapp.net/view/1-AzurePowerShell/job/powershell-on-demand/55/

**Comment by huangpf** [comment]
@hyonholee 
LGTM. One suggestion is that we may want to write record/playback tests in ```Commands.ScenarioTest.csproj```. Thanks.

**Comment by yugangw-msft** [comment]
Merging this has no impact on other PRs which already need to resolve conflicts.
So merging

**Pull request merged**
